// Chinese expansion part 4 of 6: meat_mains (25) + fish_seafood (30) = 55 rows.
// All dishes are distinct from the base 200 and parts 1-3. Halal: no pork, no alcohol.
import { R, T } from './rows.mjs';

export default [
  // --- meat_mains (25) ---
  R(`تشاو نيو رو بالزنجبيل ${T}`, 'Ginger stir-fried beef', 'Boeuf frit gingembre', 'Ternera salteada jengibre', 'Gebratenes Rindfleisch mit Ingwer', 'meat_mains', 'dinner', 'pan_chinese', 19, 5, 11),
  R(`تشاو نيو رو بالثوم ${T}`, 'Garlic stir-fried beef', 'Boeuf frit ail', 'Ternera salteada ajo', 'Gebratenes Rindfleisch mit Knoblauch', 'meat_mains', 'dinner', 'pan_chinese', 18, 6, 10),
  R(`تشاو نيو رو بالبصل ${T}`, 'Onion stir-fried beef', 'Boeuf frit oignon', 'Ternera salteada cebolla', 'Gebratenes Rindfleisch mit Zwiebel', 'meat_mains', 'dinner', 'pan_chinese', 19, 4, 11),
  R(`تشاو نيو رو بالكزبرة ${T}`, 'Cilantro stir-fried beef', 'Boeuf frit coriandre', 'Ternera salteada cilantro', 'Gebratenes Rindfleisch mit Koriander', 'meat_mains', 'dinner', 'pan_chinese', 18, 5, 10),
  R(`تشاو نيو رو بالليمون ${T}`, 'Lemon stir-fried beef', 'Boeuf frit citron', 'Ternera salteada limón', 'Gebratenes Rindfleisch mit Zitrone', 'meat_mains', 'dinner', 'pan_chinese', 19, 3, 11),
  R(`تشاو نيو رو بالفلفل ${T}`, 'Pepper stir-fried beef', 'Boeuf frit poivre', 'Ternera salteada pimienta', 'Gebratenes Rindfleisch mit Pfeffer', 'meat_mains', 'dinner', 'pan_chinese', 18, 4, 10),
  R(`تشاو نيو رو بالكاري ${T}`, 'Curry stir-fried beef', 'Boeuf frit curry', 'Ternera salteada curry', 'Gebratenes Rindfleisch mit Curry', 'meat_mains', 'dinner', 'pan_chinese', 19, 5, 11),
  R(`تشاو نيو رو بالطماطم ${T}`, 'Tomato stir-fried beef', 'Boeuf frit tomate', 'Ternera salteada tomate', 'Gebratenes Rindfleisch mit Tomate', 'meat_mains', 'dinner', 'pan_chinese', 18, 6, 10),
  R(`تشاو نيو رو بالفطر ${T}`, 'Mushroom stir-fried beef', 'Boeuf frit champignons', 'Ternera salteada hongos', 'Gebratenes Rindfleisch mit Pilzen', 'meat_mains', 'dinner', 'pan_chinese', 19, 4, 11),
  R(`تشاو نيو رو بالذرة ${T}`, 'Corn stir-fried beef', 'Boeuf frit mais', 'Ternera salteada maíz', 'Gebratenes Rindfleisch mit Mais', 'meat_mains', 'dinner', 'pan_chinese', 18, 5, 10),
  R(`تشاو نيو رو بالبطاطس ${T}`, 'Potato stir-fried beef', 'Boeuf frit pomme de terre', 'Ternera salteada papa', 'Gebratenes Rindfleisch mit Kartoffel', 'meat_mains', 'dinner', 'pan_chinese', 19, 3, 11),
  R(`تشاو نيو رو بالجزر ${T}`, 'Carrot stir-fried beef', 'Boeuf frit carotte', 'Ternera salteada zanahoria', 'Gebratenes Rindfleisch mit Karotte', 'meat_mains', 'dinner', 'pan_chinese', 18, 4, 10),
  R(`تشاو نيو رو بالسبانخ ${T}`, 'Spinach stir-fried beef', 'Boeuf frit epinards', 'Ternera salteada espinacas', 'Gebratenes Rindfleisch mit Spinat', 'meat_mains', 'dinner', 'pan_chinese', 19, 2, 11),
  R(`تشاو نيو رو بالبروكلي ${T}`, 'Broccoli stir-fried beef', 'Boeuf frit brocoli', 'Ternera salteada brócoli', 'Gebratenes Rindfleisch mit Brokkoli', 'meat_mains', 'dinner', 'pan_chinese', 18, 3, 10),
  R(`تشاو نيو رو بالبازلاء ${T}`, 'Pea stir-fried beef', 'Boeuf frit petits pois', 'Ternera salteada guisantes', 'Gebratenes Rindfleisch mit Erbsen', 'meat_mains', 'dinner', 'pan_chinese', 19, 4, 11),
  R(`تشاو نيو رو بالخضار المشكلة ${T}`, 'Mixed vegetable stir-fried beef', 'Boeuf frit legumes varies', 'Ternera salteada verduras mixtas', 'Gebratenes Rindfleisch mit gemischtem Gemüse', 'meat_mains', 'dinner', 'pan_chinese', 18, 5, 10),
  R(`تشاو نيو رو بيان بالزنجبيل ${T}`, 'Ginger stir-fried beef slices', 'Boeuf en tranches gingembre', 'Ternera en lonchas jengibre', 'Gebratene Rindfleischscheiben mit Ingwer', 'meat_mains', 'dinner', 'pan_chinese', 20, 4, 12),
  R(`تشاو نيو رو بيان بالثوم ${T}`, 'Garlic stir-fried beef slices', 'Boeuf en tranches ail', 'Ternera en lonchas ajo', 'Gebratene Rindfleischscheiben mit Knoblauch', 'meat_mains', 'dinner', 'pan_chinese', 19, 5, 11),
  R(`تشاو نيو رو بيان بالبصل ${T}`, 'Onion stir-fried beef slices', 'Boeuf en tranches oignon', 'Ternera en lonchas cebolla', 'Gebratene Rindfleischscheiben mit Zwiebel', 'meat_mains', 'dinner', 'pan_chinese', 20, 3, 12),
  R(`تشاو نيو رو بيان بالكزبرة ${T}`, 'Cilantro stir-fried beef slices', 'Boeuf en tranches coriandre', 'Ternera en lonchas cilantro', 'Gebratene Rindfleischscheiben mit Koriander', 'meat_mains', 'dinner', 'pan_chinese', 19, 4, 11),
  R(`تشاو نيو رو بيان بالليمون ${T}`, 'Lemon stir-fried beef slices', 'Boeuf en tranches citron', 'Ternera en lonchas limón', 'Gebratene Rindfleischscheiben mit Zitrone', 'meat_mains', 'dinner', 'pan_chinese', 20, 2, 12),
  R(`تشاو نيو رو بيان بالفلفل ${T}`, 'Pepper stir-fried beef slices', 'Boeuf en tranches poivre', 'Ternera en lonchas pimienta', 'Gebratene Rindfleischscheiben mit Pfeffer', 'meat_mains', 'dinner', 'pan_chinese', 19, 3, 11),
  R(`تشاو نيو رو بيان بالكاري ${T}`, 'Curry stir-fried beef slices', 'Boeuf en tranches curry', 'Ternera en lonchas curry', 'Gebratene Rindfleischscheiben mit Curry', 'meat_mains', 'dinner', 'pan_chinese', 20, 4, 12),
  R(`تشاو نيو رو بيان بالطماطم ${T}`, 'Tomato stir-fried beef slices', 'Boeuf en tranches tomate', 'Ternera en lonchas tomate', 'Gebratene Rindfleischscheiben mit Tomate', 'meat_mains', 'dinner', 'pan_chinese', 19, 5, 11),
  R(`تشاو نيو رو بيان بالفطر ${T}`, 'Mushroom stir-fried beef slices', 'Boeuf en tranches champignons', 'Ternera en lonchas hongos', 'Gebratene Rindfleischscheiben mit Pilzen', 'meat_mains', 'dinner', 'pan_chinese', 20, 3, 12),

  // --- fish_seafood (30) ---
  R(`تشاو يو بالزنجبيل ${T}`, 'Ginger stir-fried fish', 'Poisson frit gingembre', 'Pescado frito jengibre', 'Gebratener Fisch mit Ingwer', 'fish_seafood', 'dinner', 'pan_chinese', 17, 5, 9),
  R(`تشاو يو بالثوم ${T}`, 'Garlic stir-fried fish', 'Poisson frit ail', 'Pescado frito ajo', 'Gebratener Fisch mit Knoblauch', 'fish_seafood', 'dinner', 'pan_chinese', 16, 6, 8),
  R(`تشاو يو بالبصل ${T}`, 'Onion stir-fried fish', 'Poisson frit oignon', 'Pescado frito cebolla', 'Gebratener Fisch mit Zwiebel', 'fish_seafood', 'dinner', 'pan_chinese', 17, 4, 9),
  R(`تشاو يو بالكزبرة ${T}`, 'Cilantro stir-fried fish', 'Poisson frit coriandre', 'Pescado frito cilantro', 'Gebratener Fisch mit Koriander', 'fish_seafood', 'dinner', 'pan_chinese', 16, 5, 8),
  R(`تشاو يو بالليمون ${T}`, 'Lemon stir-fried fish', 'Poisson frit citron', 'Pescado frito limón', 'Gebratener Fisch mit Zitrone', 'fish_seafood', 'dinner', 'pan_chinese', 17, 3, 9),
  R(`تشاو يو بالفلفل ${T}`, 'Pepper stir-fried fish', 'Poisson frit poivre', 'Pescado frito pimienta', 'Gebratener Fisch mit Pfeffer', 'fish_seafood', 'dinner', 'pan_chinese', 16, 4, 8),
  R(`تشاو يو بالكاري ${T}`, 'Curry stir-fried fish', 'Poisson frit curry', 'Pescado frito curry', 'Gebratener Fisch mit Curry', 'fish_seafood', 'dinner', 'pan_chinese', 17, 5, 9),
  R(`تشاو يو بالطماطم ${T}`, 'Tomato stir-fried fish', 'Poisson frit tomate', 'Pescado frito tomate', 'Gebratener Fisch mit Tomate', 'fish_seafood', 'dinner', 'pan_chinese', 16, 6, 8),
  R(`تشاو يو بالفطر ${T}`, 'Mushroom stir-fried fish', 'Poisson frit champignons', 'Pescado frito hongos', 'Gebratener Fisch mit Pilzen', 'fish_seafood', 'dinner', 'pan_chinese', 17, 4, 9),
  R(`تشاو يو بالذرة ${T}`, 'Corn stir-fried fish', 'Poisson frit mais', 'Pescado frito maíz', 'Gebratener Fisch mit Mais', 'fish_seafood', 'dinner', 'pan_chinese', 16, 5, 8),
  R(`تشاو يو بالبطاطس ${T}`, 'Potato stir-fried fish', 'Poisson frit pomme de terre', 'Pescado frito papa', 'Gebratener Fisch mit Kartoffel', 'fish_seafood', 'dinner', 'pan_chinese', 17, 3, 9),
  R(`تشاو يو بالجزر ${T}`, 'Carrot stir-fried fish', 'Poisson frit carotte', 'Pescado frito zanahoria', 'Gebratener Fisch mit Karotte', 'fish_seafood', 'dinner', 'pan_chinese', 16, 4, 8),
  R(`تشاو يو بالسبانخ ${T}`, 'Spinach stir-fried fish', 'Poisson frit epinards', 'Pescado frito espinacas', 'Gebratener Fisch mit Spinat', 'fish_seafood', 'dinner', 'pan_chinese', 17, 2, 9),
  R(`تشاو يو بالبروكلي ${T}`, 'Broccoli stir-fried fish', 'Poisson frit brocoli', 'Pescado frito brócoli', 'Gebratener Fisch mit Brokkoli', 'fish_seafood', 'dinner', 'pan_chinese', 16, 3, 8),
  R(`تشاو يو بالبازلاء ${T}`, 'Pea stir-fried fish', 'Poisson frit petits pois', 'Pescado frito guisantes', 'Gebratener Fisch mit Erbsen', 'fish_seafood', 'dinner', 'pan_chinese', 17, 4, 9),
  R(`تشاو يو بالخضار المشكلة ${T}`, 'Mixed vegetable stir-fried fish', 'Poisson frit legumes varies', 'Pescado frito verduras mixtas', 'Gebratener Fisch mit gemischtem Gemüse', 'fish_seafood', 'dinner', 'pan_chinese', 16, 5, 8),
  R(`تشاو شيا بالزنجبيل ${T}`, 'Ginger stir-fried shrimp', 'Crevettes frites gingembre', 'Camarones fritos jengibre', 'Gebratene Garnelen mit Ingwer', 'fish_seafood', 'dinner', 'pan_chinese', 19, 4, 9),
  R(`تشاو شيا بالثوم ${T}`, 'Garlic stir-fried shrimp', 'Crevettes frites ail', 'Camarones fritos ajo', 'Gebratene Garnelen mit Knoblauch', 'fish_seafood', 'dinner', 'pan_chinese', 18, 5, 8),
  R(`تشاو شيا بالبصل ${T}`, 'Onion stir-fried shrimp', 'Crevettes frites oignon', 'Camarones fritos cebolla', 'Gebratene Garnelen mit Zwiebel', 'fish_seafood', 'dinner', 'pan_chinese', 19, 3, 9),
  R(`تشاو شيا بالكزبرة ${T}`, 'Cilantro stir-fried shrimp', 'Crevettes frites coriandre', 'Camarones fritos cilantro', 'Gebratene Garnelen mit Koriander', 'fish_seafood', 'dinner', 'pan_chinese', 18, 4, 8),
  R(`تشاو شيا بالليمون ${T}`, 'Lemon stir-fried shrimp', 'Crevettes frites citron', 'Camarones fritos limón', 'Gebratene Garnelen mit Zitrone', 'fish_seafood', 'dinner', 'pan_chinese', 19, 2, 9),
  R(`تشاو شيا بالفلفل ${T}`, 'Pepper stir-fried shrimp', 'Crevettes frites poivre', 'Camarones fritos pimienta', 'Gebratene Garnelen mit Pfeffer', 'fish_seafood', 'dinner', 'pan_chinese', 18, 3, 8),
  R(`تشاو شيا بالكاري ${T}`, 'Curry stir-fried shrimp', 'Crevettes frites curry', 'Camarones fritos curry', 'Gebratene Garnelen mit Curry', 'fish_seafood', 'dinner', 'pan_chinese', 19, 4, 9),
  R(`تشاو شيا بالطماطم ${T}`, 'Tomato stir-fried shrimp', 'Crevettes frites tomate', 'Camarones fritos tomate', 'Gebratene Garnelen mit Tomate', 'fish_seafood', 'dinner', 'pan_chinese', 18, 5, 8),
  R(`تشاو شيا بالفطر ${T}`, 'Mushroom stir-fried shrimp', 'Crevettes frites champignons', 'Camarones fritos hongos', 'Gebratene Garnelen mit Pilzen', 'fish_seafood', 'dinner', 'pan_chinese', 19, 3, 9),
  R(`تشاو شيا بالذرة ${T}`, 'Corn stir-fried shrimp', 'Crevettes frites mais', 'Camarones fritos maíz', 'Gebratene Garnelen mit Mais', 'fish_seafood', 'dinner', 'pan_chinese', 18, 4, 8),
  R(`تشاو شيا بالبطاطس ${T}`, 'Potato stir-fried shrimp', 'Crevettes frites pomme de terre', 'Camarones fritos papa', 'Gebratene Garnelen mit Kartoffel', 'fish_seafood', 'dinner', 'pan_chinese', 19, 2, 9),
  R(`تشاو شيا بالجزر ${T}`, 'Carrot stir-fried shrimp', 'Crevettes frites carotte', 'Camarones fritos zanahoria', 'Gebratene Garnelen mit Karotte', 'fish_seafood', 'dinner', 'pan_chinese', 18, 3, 8),
  R(`تشاو شيا بالسبانخ ${T}`, 'Spinach stir-fried shrimp', 'Crevettes frites epinards', 'Camarones fritos espinacas', 'Gebratene Garnelen mit Spinat', 'fish_seafood', 'dinner', 'pan_chinese', 19, 1, 9),
  R(`تشاو شيا بالبروكلي ${T}`, 'Broccoli stir-fried shrimp', 'Crevettes frites brocoli', 'Camarones fritos brócoli', 'Gebratene Garnelen mit Brokkoli', 'fish_seafood', 'dinner', 'pan_chinese', 18, 2, 8),
  R(`تشاو شيا بالبازلاء ${T}`, 'Pea stir-fried shrimp', 'Crevettes frites petits pois', 'Camarones fritos guisantes', 'Gebratene Garnelen mit Erbsen', 'fish_seafood', 'dinner', 'pan_chinese', 19, 3, 9),
];
