// Chinese expansion part 3 of 6: soups_stews (25) + poultry_mains (25) = 50 rows.
// All dishes are distinct from the base 200 and parts 1-2. Halal: no pork, no alcohol.
import { R, T } from './rows.mjs';

export default [
  // --- soups_stews (25) ---
  R(`تان تان تانغ بالزنجبيل ${T}`, 'Ginger hot and sour soup', 'Soupe aigre piquante gingembre', 'Sopa agria picante jengibre', 'Saure scharfe Suppe mit Ingwer', 'soups_stews', 'lunch', 'pan_chinese', 7, 5, 3),
  R(`تان تان تانغ بالثوم ${T}`, 'Garlic hot and sour soup', 'Soupe aigre piquante ail', 'Sopa agria picante ajo', 'Saure scharfe Suppe mit Knoblauch', 'soups_stews', 'lunch', 'pan_chinese', 6, 6, 2),
  R(`تان تان تانغ بالبصل ${T}`, 'Onion hot and sour soup', 'Soupe aigre piquante oignon', 'Sopa agria picante cebolla', 'Saure scharfe Suppe mit Zwiebel', 'soups_stews', 'lunch', 'pan_chinese', 7, 4, 3),
  R(`تان تان تانغ بالكزبرة ${T}`, 'Cilantro hot and sour soup', 'Soupe aigre piquante coriandre', 'Sopa agria picante cilantro', 'Saure scharfe Suppe mit Koriander', 'soups_stews', 'lunch', 'pan_chinese', 6, 5, 2),
  R(`تان تان تانغ بالليمون ${T}`, 'Lemon hot and sour soup', 'Soupe aigre piquante citron', 'Sopa agria picante limón', 'Saure scharfe Suppe mit Zitrone', 'soups_stews', 'lunch', 'pan_chinese', 7, 3, 3),
  R(`تان تان تانغ بالفلفل ${T}`, 'Pepper hot and sour soup', 'Soupe aigre piquante poivre', 'Sopa agria picante pimienta', 'Saure scharfe Suppe mit Pfeffer', 'soups_stews', 'lunch', 'pan_chinese', 6, 4, 2),
  R(`تان تان تانغ بالكاري ${T}`, 'Curry hot and sour soup', 'Soupe aigre piquante curry', 'Sopa agria picante curry', 'Saure scharfe Suppe mit Curry', 'soups_stews', 'lunch', 'pan_chinese', 7, 5, 3),
  R(`تان تان تانغ بالطماطم ${T}`, 'Tomato hot and sour soup', 'Soupe aigre piquante tomate', 'Sopa agria picante tomate', 'Saure scharfe Suppe mit Tomate', 'soups_stews', 'lunch', 'pan_chinese', 6, 6, 2),
  R(`تان تان تانغ بالفطر ${T}`, 'Mushroom hot and sour soup', 'Soupe aigre piquante champignons', 'Sopa agria picante hongos', 'Saure scharfe Suppe mit Pilzen', 'soups_stews', 'lunch', 'pan_chinese', 7, 4, 3),
  R(`تان تان تانغ بالذرة ${T}`, 'Corn hot and sour soup', 'Soupe aigre piquante mais', 'Sopa agria picante maíz', 'Saure scharfe Suppe mit Mais', 'soups_stews', 'lunch', 'pan_chinese', 6, 5, 2),
  R(`تان تان تانغ بالبطاطس ${T}`, 'Potato hot and sour soup', 'Soupe aigre piquante pomme de terre', 'Sopa agria picante papa', 'Saure scharfe Suppe mit Kartoffel', 'soups_stews', 'lunch', 'pan_chinese', 7, 3, 3),
  R(`تان تان تانغ بالجزر ${T}`, 'Carrot hot and sour soup', 'Soupe aigre piquante carotte', 'Sopa agria picante zanahoria', 'Saure scharfe Suppe mit Karotte', 'soups_stews', 'lunch', 'pan_chinese', 6, 4, 2),
  R(`تان تان تانغ بالسبانخ ${T}`, 'Spinach hot and sour soup', 'Soupe aigre piquante epinards', 'Sopa agria picante espinacas', 'Saure scharfe Suppe mit Spinat', 'soups_stews', 'lunch', 'pan_chinese', 7, 3, 3),
  R(`تان تان تانغ بالبروكلي ${T}`, 'Broccoli hot and sour soup', 'Soupe aigre piquante brocoli', 'Sopa agria picante brócoli', 'Saure scharfe Suppe mit Brokkoli', 'soups_stews', 'lunch', 'pan_chinese', 6, 4, 2),
  R(`تان تان تانغ بالبازلاء ${T}`, 'Pea hot and sour soup', 'Soupe aigre piquante petits pois', 'Sopa agria picante guisantes', 'Saure scharfe Suppe mit Erbsen', 'soups_stews', 'lunch', 'pan_chinese', 7, 5, 3),
  R(`تان تان تانغ بالخضار المشكلة ${T}`, 'Mixed vegetable hot and sour soup', 'Soupe aigre piquante legumes varies', 'Sopa agria picante verduras mixtas', 'Saure scharfe Suppe mit gemischtem Gemüse', 'soups_stews', 'lunch', 'pan_chinese', 6, 6, 2),
  R(`سي تشوان تانغ بالزنجبيل ${T}`, 'Ginger Sichuan spicy soup', 'Soupe epicee Sichuan gingembre', 'Sopa picante Sichuan jengibre', 'Scharfe Sichuan-Suppe mit Ingwer', 'soups_stews', 'dinner', 'pan_chinese', 9, 4, 5),
  R(`سي تشوان تانغ بالثوم ${T}`, 'Garlic Sichuan spicy soup', 'Soupe epicee Sichuan ail', 'Sopa picante Sichuan ajo', 'Scharfe Sichuan-Suppe mit Knoblauch', 'soups_stews', 'dinner', 'pan_chinese', 8, 5, 4),
  R(`سي تشوان تانغ بالبصل ${T}`, 'Onion Sichuan spicy soup', 'Soupe epicee Sichuan oignon', 'Sopa picante Sichuan cebolla', 'Scharfe Sichuan-Suppe mit Zwiebel', 'soups_stews', 'dinner', 'pan_chinese', 9, 3, 5),
  R(`سي تشوان تانغ بالكزبرة ${T}`, 'Cilantro Sichuan spicy soup', 'Soupe epicee Sichuan coriandre', 'Sopa picante Sichuan cilantro', 'Scharfe Sichuan-Suppe mit Koriander', 'soups_stews', 'dinner', 'pan_chinese', 8, 4, 4),
  R(`سي تشوان تانغ بالليمون ${T}`, 'Lemon Sichuan spicy soup', 'Soupe epicee Sichuan citron', 'Sopa picante Sichuan limón', 'Scharfe Sichuan-Suppe mit Zitrone', 'soups_stews', 'dinner', 'pan_chinese', 9, 2, 5),
  R(`سي تشوان تانغ بالفلفل ${T}`, 'Pepper Sichuan spicy soup', 'Soupe epicee Sichuan poivre', 'Sopa picante Sichuan pimienta', 'Scharfe Sichuan-Suppe mit Pfeffer', 'soups_stews', 'dinner', 'pan_chinese', 8, 3, 4),
  R(`سي تشوان تانغ بالكاري ${T}`, 'Curry Sichuan spicy soup', 'Soupe epicee Sichuan curry', 'Sopa picante Sichuan curry', 'Scharfe Sichuan-Suppe mit Curry', 'soups_stews', 'dinner', 'pan_chinese', 9, 4, 5),
  R(`سي تشوان تانغ بالطماطم ${T}`, 'Tomato Sichuan spicy soup', 'Soupe epicee Sichuan tomate', 'Sopa picante Sichuan tomate', 'Scharfe Sichuan-Suppe mit Tomate', 'soups_stews', 'dinner', 'pan_chinese', 8, 5, 4),
  R(`سي تشوان تانغ بالفطر ${T}`, 'Mushroom Sichuan spicy soup', 'Soupe epicee Sichuan champignons', 'Sopa picante Sichuan hongos', 'Scharfe Sichuan-Suppe mit Pilzen', 'soups_stews', 'dinner', 'pan_chinese', 9, 3, 5),

  // --- poultry_mains (25) ---
  R(`كونغ باو جي دينغ بالزنجبيل ${T}`, 'Ginger Kung Pao chicken', 'Poulet Kung Pao gingembre', 'Pollo Kung Pao jengibre', 'Kung-Pao-Hähnchen mit Ingwer', 'poultry_mains', 'dinner', 'pan_chinese', 17, 11, 13),
  R(`كونغ باو جي دينغ بالثوم ${T}`, 'Garlic Kung Pao chicken', 'Poulet Kung Pao ail', 'Pollo Kung Pao ajo', 'Kung-Pao-Hähnchen mit Knoblauch', 'poultry_mains', 'dinner', 'pan_chinese', 16, 12, 12),
  R(`كونغ باو جي دينغ بالبصل ${T}`, 'Onion Kung Pao chicken', 'Poulet Kung Pao oignon', 'Pollo Kung Pao cebolla', 'Kung-Pao-Hähnchen mit Zwiebel', 'poultry_mains', 'dinner', 'pan_chinese', 17, 10, 13),
  R(`كونغ باو جي دينغ بالكزبرة ${T}`, 'Cilantro Kung Pao chicken', 'Poulet Kung Pao coriandre', 'Pollo Kung Pao cilantro', 'Kung-Pao-Hähnchen mit Koriander', 'poultry_mains', 'dinner', 'pan_chinese', 16, 11, 12),
  R(`كونغ باو جي دينغ بالليمون ${T}`, 'Lemon Kung Pao chicken', 'Poulet Kung Pao citron', 'Pollo Kung Pao limón', 'Kung-Pao-Hähnchen mit Zitrone', 'poultry_mains', 'dinner', 'pan_chinese', 17, 9, 13),
  R(`كونغ باو جي دينغ بالفلفل ${T}`, 'Pepper Kung Pao chicken', 'Poulet Kung Pao poivre', 'Pollo Kung Pao pimienta', 'Kung-Pao-Hähnchen mit Pfeffer', 'poultry_mains', 'dinner', 'pan_chinese', 16, 10, 12),
  R(`كونغ باو جي دينغ بالكاري ${T}`, 'Curry Kung Pao chicken', 'Poulet Kung Pao curry', 'Pollo Kung Pao curry', 'Kung-Pao-Hähnchen mit Curry', 'poultry_mains', 'dinner', 'pan_chinese', 17, 11, 13),
  R(`كونغ باو جي دينغ بالطماطم ${T}`, 'Tomato Kung Pao chicken', 'Poulet Kung Pao tomate', 'Pollo Kung Pao tomate', 'Kung-Pao-Hähnchen mit Tomate', 'poultry_mains', 'dinner', 'pan_chinese', 16, 12, 12),
  R(`كونغ باو جي دينغ بالفطر ${T}`, 'Mushroom Kung Pao chicken', 'Poulet Kung Pao champignons', 'Pollo Kung Pao hongos', 'Kung-Pao-Hähnchen mit Pilzen', 'poultry_mains', 'dinner', 'pan_chinese', 17, 10, 13),
  R(`كونغ باو جي دينغ بالذرة ${T}`, 'Corn Kung Pao chicken', 'Poulet Kung Pao mais', 'Pollo Kung Pao maíz', 'Kung-Pao-Hähnchen mit Mais', 'poultry_mains', 'dinner', 'pan_chinese', 16, 11, 12),
  R(`كونغ باو جي دينغ بالبطاطس ${T}`, 'Potato Kung Pao chicken', 'Poulet Kung Pao pomme de terre', 'Pollo Kung Pao papa', 'Kung-Pao-Hähnchen mit Kartoffel', 'poultry_mains', 'dinner', 'pan_chinese', 17, 9, 13),
  R(`كونغ باو جي دينغ بالجزر ${T}`, 'Carrot Kung Pao chicken', 'Poulet Kung Pao carotte', 'Pollo Kung Pao zanahoria', 'Kung-Pao-Hähnchen mit Karotte', 'poultry_mains', 'dinner', 'pan_chinese', 16, 10, 12),
  R(`كونغ باو جي دينغ بالسبانخ ${T}`, 'Spinach Kung Pao chicken', 'Poulet Kung Pao epinards', 'Pollo Kung Pao espinacas', 'Kung-Pao-Hähnchen mit Spinat', 'poultry_mains', 'dinner', 'pan_chinese', 17, 8, 13),
  R(`كونغ باو جي دينغ بالبروكلي ${T}`, 'Broccoli Kung Pao chicken', 'Poulet Kung Pao brocoli', 'Pollo Kung Pao brócoli', 'Kung-Pao-Hähnchen mit Brokkoli', 'poultry_mains', 'dinner', 'pan_chinese', 16, 9, 12),
  R(`كونغ باو جي دينغ بالبازلاء ${T}`, 'Pea Kung Pao chicken', 'Poulet Kung Pao petits pois', 'Pollo Kung Pao guisantes', 'Kung-Pao-Hähnchen mit Erbsen', 'poultry_mains', 'dinner', 'pan_chinese', 17, 10, 13),
  R(`كونغ باو جي دينغ بالخضار المشكلة ${T}`, 'Mixed vegetable Kung Pao chicken', 'Poulet Kung Pao legumes varies', 'Pollo Kung Pao verduras mixtas', 'Kung-Pao-Hähnchen mit gemischtem Gemüse', 'poultry_mains', 'dinner', 'pan_chinese', 16, 11, 12),
  R(`تشاو جي دينغ بالزنجبيل ${T}`, 'Ginger stir-fried chicken cubes', 'Poulet en cubes gingembre', 'Pollo en cubos jengibre', 'Huhnwürfel mit Ingwer', 'poultry_mains', 'dinner', 'pan_chinese', 18, 7, 11),
  R(`تشاو جي دينغ بالثوم ${T}`, 'Garlic stir-fried chicken cubes', 'Poulet en cubes ail', 'Pollo en cubos ajo', 'Huhnwürfel mit Knoblauch', 'poultry_mains', 'dinner', 'pan_chinese', 17, 8, 10),
  R(`تشاو جي دينغ بالبصل ${T}`, 'Onion stir-fried chicken cubes', 'Poulet en cubes oignon', 'Pollo en cubos cebolla', 'Huhnwürfel mit Zwiebel', 'poultry_mains', 'dinner', 'pan_chinese', 18, 6, 11),
  R(`تشاو جي دينغ بالكزبرة ${T}`, 'Cilantro stir-fried chicken cubes', 'Poulet en cubes coriandre', 'Pollo en cubos cilantro', 'Huhnwürfel mit Koriander', 'poultry_mains', 'dinner', 'pan_chinese', 17, 7, 10),
  R(`تشاو جي دينغ بالليمون ${T}`, 'Lemon stir-fried chicken cubes', 'Poulet en cubes citron', 'Pollo en cubos limón', 'Huhnwürfel mit Zitrone', 'poultry_mains', 'dinner', 'pan_chinese', 18, 5, 11),
  R(`تشاو جي دينغ بالفلفل ${T}`, 'Pepper stir-fried chicken cubes', 'Poulet en cubes poivre', 'Pollo en cubos pimienta', 'Huhnwürfel mit Pfeffer', 'poultry_mains', 'dinner', 'pan_chinese', 17, 6, 10),
  R(`تشاو جي دينغ بالكاري ${T}`, 'Curry stir-fried chicken cubes', 'Poulet en cubes curry', 'Pollo en cubos curry', 'Huhnwürfel mit Curry', 'poultry_mains', 'dinner', 'pan_chinese', 18, 7, 11),
  R(`تشاو جي دينغ بالطماطم ${T}`, 'Tomato stir-fried chicken cubes', 'Poulet en cubes tomate', 'Pollo en cubos tomate', 'Huhnwürfel mit Tomate', 'poultry_mains', 'dinner', 'pan_chinese', 17, 8, 10),
  R(`تشاو جي دينغ بالفطر ${T}`, 'Mushroom stir-fried chicken cubes', 'Poulet en cubes champignons', 'Pollo en cubos hongos', 'Huhnwürfel mit Pilzen', 'poultry_mains', 'dinner', 'pan_chinese', 18, 6, 11),
];
