// Chinese expansion part 6 of 6: rice_cakes_sweets (18) + street_snacks (20) + condiments_sauces (15) + beverages (22) = 75 rows.
// All dishes are distinct from the base 200 and parts 1-5. Halal: no pork, no alcohol.
import { R, T } from './rows.mjs';

export default [
  // --- rice_cakes_sweets (18) ---
  R(`نيان غاو بالزنجبيل ${T}`, 'Ginger New Year rice cake', 'Gateau de riz gingembre', 'Pastel de arroz jengibre', 'Neujahrs-Reiskuchen mit Ingwer', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 5, 27, 3),
  R(`نيان غاو بالثوم ${T}`, 'Garlic New Year rice cake', 'Gateau de riz ail', 'Pastel de arroz ajo', 'Neujahrs-Reiskuchen mit Knoblauch', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 4, 28, 2),
  R(`نيان غاو بالبصل ${T}`, 'Onion New Year rice cake', 'Gateau de riz oignon', 'Pastel de arroz cebolla', 'Neujahrs-Reiskuchen mit Zwiebel', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 5, 26, 3),
  R(`نيان غاو بالكزبرة ${T}`, 'Cilantro New Year rice cake', 'Gateau de riz coriandre', 'Pastel de arroz cilantro', 'Neujahrs-Reiskuchen mit Koriander', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 4, 27, 2),
  R(`نيان غاو بالليمون ${T}`, 'Lemon New Year rice cake', 'Gateau de riz citron', 'Pastel de arroz limón', 'Neujahrs-Reiskuchen mit Zitrone', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 5, 25, 3),
  R(`نيان غاو بالفلفل ${T}`, 'Pepper New Year rice cake', 'Gateau de riz poivre', 'Pastel de arroz pimienta', 'Neujahrs-Reiskuchen mit Pfeffer', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 4, 26, 2),
  R(`نيان غاو بالكاري ${T}`, 'Curry New Year rice cake', 'Gateau de riz curry', 'Pastel de arroz curry', 'Neujahrs-Reiskuchen mit Curry', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 5, 27, 3),
  R(`نيان غاو بالطماطم ${T}`, 'Tomato New Year rice cake', 'Gateau de riz tomate', 'Pastel de arroz tomate', 'Neujahrs-Reiskuchen mit Tomate', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 4, 28, 2),
  R(`نيان غاو بالفطر ${T}`, 'Mushroom New Year rice cake', 'Gateau de riz champignons', 'Pastel de arroz hongos', 'Neujahrs-Reiskuchen mit Pilzen', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 5, 26, 3),
  R(`نيان غاو بالذرة ${T}`, 'Corn New Year rice cake', 'Gateau de riz mais', 'Pastel de arroz maíz', 'Neujahrs-Reiskuchen mit Mais', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 4, 27, 2),
  R(`نيان غاو بالبطاطس ${T}`, 'Potato New Year rice cake', 'Gateau de riz pomme de terre', 'Pastel de arroz papa', 'Neujahrs-Reiskuchen mit Kartoffel', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 5, 25, 3),
  R(`نيان غاو بالجزر ${T}`, 'Carrot New Year rice cake', 'Gateau de riz carotte', 'Pastel de arroz zanahoria', 'Neujahrs-Reiskuchen mit Karotte', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 4, 26, 2),
  R(`نيان غاو بالسبانخ ${T}`, 'Spinach New Year rice cake', 'Gateau de riz epinards', 'Pastel de arroz espinacas', 'Neujahrs-Reiskuchen mit Spinat', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 5, 24, 3),
  R(`نيان غاو بالبروكلي ${T}`, 'Broccoli New Year rice cake', 'Gateau de riz brocoli', 'Pastel de arroz brócoli', 'Neujahrs-Reiskuchen mit Brokkoli', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 4, 25, 2),
  R(`نيان غاو بالبازلاء ${T}`, 'Pea New Year rice cake', 'Gateau de riz petits pois', 'Pastel de arroz guisantes', 'Neujahrs-Reiskuchen mit Erbsen', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 5, 26, 3),
  R(`نيان غاو بالخضار المشكلة ${T}`, 'Mixed vegetable New Year rice cake', 'Gateau de riz legumes varies', 'Pastel de arroz verduras mixtas', 'Neujahrs-Reiskuchen mit gemischtem Gemüse', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 4, 27, 2),
  R(`نيان غاو بالموز ${T}`, 'Banana New Year rice cake', 'Gateau de riz banane', 'Pastel de arroz plátano', 'Neujahrs-Reiskuchen mit Banane', 'rice_cakes_sweets', 'snacks', 'pan_chinese', 6, 25, 4),

  // --- street_snacks (20) ---
  R(`شاو ماي بالزنجبيل ${T}`, 'Ginger shumai dumplings', 'Raviolis shumai gingembre', 'Empanadillas shumai jengibre', 'Shumai-Ravioli mit Ingwer', 'street_snacks', 'snacks', 'pan_chinese', 11, 17, 5),
  R(`شاو ماي بالثوم ${T}`, 'Garlic shumai dumplings', 'Raviolis shumai ail', 'Empanadillas shumai ajo', 'Shumai-Ravioli mit Knoblauch', 'street_snacks', 'snacks', 'pan_chinese', 10, 18, 4),
  R(`شاو ماي بالبصل ${T}`, 'Onion shumai dumplings', 'Raviolis shumai oignon', 'Empanadillas shumai cebolla', 'Shumai-Ravioli mit Zwiebel', 'street_snacks', 'snacks', 'pan_chinese', 11, 16, 5),
  R(`شاو ماي بالكزبرة ${T}`, 'Cilantro shumai dumplings', 'Raviolis shumai coriandre', 'Empanadillas shumai cilantro', 'Shumai-Ravioli mit Koriander', 'street_snacks', 'snacks', 'pan_chinese', 10, 17, 4),
  R(`شاو ماي بالليمون ${T}`, 'Lemon shumai dumplings', 'Raviolis shumai citron', 'Empanadillas shumai limón', 'Shumai-Ravioli mit Zitrone', 'street_snacks', 'snacks', 'pan_chinese', 11, 15, 5),
  R(`شاو ماي بالفلفل ${T}`, 'Pepper shumai dumplings', 'Raviolis shumai poivre', 'Empanadillas shumai pimienta', 'Shumai-Ravioli mit Pfeffer', 'street_snacks', 'snacks', 'pan_chinese', 10, 16, 4),
  R(`شاو ماي بالكاري ${T}`, 'Curry shumai dumplings', 'Raviolis shumai curry', 'Empanadillas shumai curry', 'Shumai-Ravioli mit Curry', 'street_snacks', 'snacks', 'pan_chinese', 12, 15, 6),
  R(`شاو ماي بالطماطم ${T}`, 'Tomato shumai dumplings', 'Raviolis shumai tomate', 'Empanadillas shumai tomate', 'Shumai-Ravioli mit Tomate', 'street_snacks', 'snacks', 'pan_chinese', 11, 16, 5),
  R(`شاو ماي بالفطر ${T}`, 'Mushroom shumai dumplings', 'Raviolis shumai champignons', 'Empanadillas shumai hongos', 'Shumai-Ravioli mit Pilzen', 'street_snacks', 'snacks', 'pan_chinese', 12, 14, 6),
  R(`شاو ماي بالذرة ${T}`, 'Corn shumai dumplings', 'Raviolis shumai mais', 'Empanadillas shumai maíz', 'Shumai-Ravioli mit Mais', 'street_snacks', 'snacks', 'pan_chinese', 11, 15, 5),
  R(`شاو ماي بالبطاطس ${T}`, 'Potato shumai dumplings', 'Raviolis shumai pomme de terre', 'Empanadillas shumai papa', 'Shumai-Ravioli mit Kartoffel', 'street_snacks', 'snacks', 'pan_chinese', 12, 13, 6),
  R(`شاو ماي بالجزر ${T}`, 'Carrot shumai dumplings', 'Raviolis shumai carotte', 'Empanadillas shumai zanahoria', 'Shumai-Ravioli mit Karotte', 'street_snacks', 'snacks', 'pan_chinese', 11, 14, 5),
  R(`شاو ماي بالسبانخ ${T}`, 'Spinach shumai dumplings', 'Raviolis shumai epinards', 'Empanadillas shumai espinacas', 'Shumai-Ravioli mit Spinat', 'street_snacks', 'snacks', 'pan_chinese', 12, 12, 6),
  R(`شاو ماي بالبروكلي ${T}`, 'Broccoli shumai dumplings', 'Raviolis shumai brocoli', 'Empanadillas shumai brócoli', 'Shumai-Ravioli mit Brokkoli', 'street_snacks', 'snacks', 'pan_chinese', 11, 13, 5),
  R(`شاو ماي بالبازلاء ${T}`, 'Pea shumai dumplings', 'Raviolis shumai petits pois', 'Empanadillas shumai guisantes', 'Shumai-Ravioli mit Erbsen', 'street_snacks', 'snacks', 'pan_chinese', 12, 14, 6),
  R(`شاو ماي بالخضار المشكلة ${T}`, 'Mixed vegetable shumai dumplings', 'Raviolis shumai legumes varies', 'Empanadillas shumai verduras mixtas', 'Shumai-Ravioli mit gemischtem Gemüse', 'street_snacks', 'snacks', 'pan_chinese', 11, 15, 5),
  R(`شاو ماي بالدجاج واللحم ${T}`, 'Chicken beef shumai dumplings', 'Raviolis shumai poulet boeuf', 'Empanadillas shumai pollo ternera', 'Huhn-Rind-Shumai', 'street_snacks', 'snacks', 'pan_chinese', 14, 12, 8),
  R(`شاو ماي بالدجاج والروبيان ${T}`, 'Chicken shrimp shumai dumplings', 'Raviolis shumai poulet crevettes', 'Empanadillas shumai pollo camarones', 'Huhn-Garnelen-Shumai', 'street_snacks', 'snacks', 'pan_chinese', 13, 13, 7),
  R(`شاو ماي باللحم والروبيان ${T}`, 'Beef shrimp shumai dumplings', 'Raviolis shumai boeuf crevettes', 'Empanadillas shumai ternera camarones', 'Rind-Garnelen-Shumai', 'street_snacks', 'snacks', 'pan_chinese', 14, 12, 8),
  R(`شاو ماي بالدجاج واللحم والروبيان ${T}`, 'Chicken beef shrimp shumai dumplings', 'Raviolis shumai poulet boeuf crevettes', 'Empanadillas shumai pollo ternera camarones', 'Huhn-Rind-Garnelen-Shumai', 'street_snacks', 'snacks', 'pan_chinese', 15, 11, 9),

  // --- condiments_sauces (15) ---
  R(`تشو تشو جيانغ بالزنجبيل ${T}`, 'Aromatic ginger soy sauce', 'Sauce soja gingembre', 'Salsa de soja jengibre', 'Sojasauce mit Ingwer', 'condiments_sauces', 'snacks', 'pan_chinese', 6, 9, 1),
  R(`تشو تشو جيانغ بالثوم ${T}`, 'Aromatic garlic soy sauce', 'Sauce soja ail', 'Salsa de soja ajo', 'Sojasauce mit Knoblauch', 'condiments_sauces', 'snacks', 'pan_chinese', 5, 10, 1),
  R(`تشو تشو جيانغ بالبصل ${T}`, 'Aromatic onion soy sauce', 'Sauce soja oignon', 'Salsa de soja cebolla', 'Sojasauce mit Zwiebel', 'condiments_sauces', 'snacks', 'pan_chinese', 6, 8, 1),
  R(`تشو تشو جيانغ بالكزبرة ${T}`, 'Aromatic cilantro soy sauce', 'Sauce soja coriandre', 'Salsa de soja cilantro', 'Sojasauce mit Koriander', 'condiments_sauces', 'snacks', 'pan_chinese', 5, 9, 1),
  R(`تشو تشو جيانغ بالليمون ${T}`, 'Aromatic lemon soy sauce', 'Sauce soja citron', 'Salsa de soja limón', 'Sojasauce mit Zitrone', 'condiments_sauces', 'snacks', 'pan_chinese', 6, 7, 1),
  R(`تشو تشو جيانغ بالفلفل ${T}`, 'Aromatic pepper soy sauce', 'Sauce soja poivre', 'Salsa de soja pimienta', 'Sojasauce mit Pfeffer', 'condiments_sauces', 'snacks', 'pan_chinese', 5, 8, 1),
  R(`تشو تشو جيانغ بالكاري ${T}`, 'Aromatic curry soy sauce', 'Sauce soja curry', 'Salsa de soja curry', 'Sojasauce mit Curry', 'condiments_sauces', 'snacks', 'pan_chinese', 7, 7, 2),
  R(`تشو تشو جيانغ بالطماطم ${T}`, 'Aromatic tomato soy sauce', 'Sauce soja tomate', 'Salsa de soja tomate', 'Sojasauce mit Tomate', 'condiments_sauces', 'snacks', 'pan_chinese', 6, 8, 1),
  R(`تشو تشو جيانغ بالفطر ${T}`, 'Aromatic mushroom soy sauce', 'Sauce soja champignons', 'Salsa de soja hongos', 'Sojasauce mit Pilzen', 'condiments_sauces', 'snacks', 'pan_chinese', 7, 6, 2),
  R(`تشو تشو جيانغ بالذرة ${T}`, 'Corn soy sauce', 'Sauce soja mais', 'Salsa de soja maíz', 'Sojasauce mit Mais', 'condiments_sauces', 'snacks', 'pan_chinese', 6, 7, 1),
  R(`تشو تشو جيانغ بالبطاطس ${T}`, 'Potato soy sauce', 'Sauce soja pomme de terre', 'Salsa de soja papa', 'Sojasauce mit Kartoffel', 'condiments_sauces', 'snacks', 'pan_chinese', 7, 5, 2),
  R(`تشو تشو جيانغ بالجزر ${T}`, 'Carrot soy sauce', 'Sauce soja carotte', 'Salsa de soja zanahoria', 'Sojasauce mit Karotte', 'condiments_sauces', 'snacks', 'pan_chinese', 6, 6, 1),
  R(`تشو تشو جيانغ بالسبانخ ${T}`, 'Spinach soy sauce', 'Sauce soja epinards', 'Salsa de soja espinacas', 'Sojasauce mit Spinat', 'condiments_sauces', 'snacks', 'pan_chinese', 7, 4, 2),
  R(`تشو تشو جيانغ بالبروكلي ${T}`, 'Broccoli soy sauce', 'Sauce soja brocoli', 'Salsa de soja brócoli', 'Sojasauce mit Brokkoli', 'condiments_sauces', 'snacks', 'pan_chinese', 6, 5, 1),

  // --- beverages (22) ---
  R(`تشا بالزنجبيل ${T}`, 'Aromatic ginger tea', 'The gingembre', 'Té jengibre', 'Ingwer-Tee', 'beverages', 'snacks', 'pan_chinese', 1, 1, 0),
  R(`تشا بالثوم ${T}`, 'Aromatic garlic tea', 'The ail', 'Té ajo', 'Knoblauch-Tee', 'beverages', 'snacks', 'pan_chinese', 0, 2, 0),
  R(`تشا بالبصل ${T}`, 'Aromatic onion tea', 'The oignon', 'Té cebolla', 'Zwiebel-Tee', 'beverages', 'snacks', 'pan_chinese', 1, 0, 0),
  R(`تشا بالكزبرة ${T}`, 'Aromatic cilantro tea', 'The coriandre', 'Té cilantro', 'Koriander-Tee', 'beverages', 'snacks', 'pan_chinese', 0, 1, 0),
  R(`تشا بالليمون ${T}`, 'Aromatic lemon tea', 'The citron', 'Té limón', 'Zitronen-Tee', 'beverages', 'snacks', 'pan_chinese', 1, 0, 0),
  R(`تشا بالفلفل ${T}`, 'Aromatic pepper tea', 'The poivre', 'Té pimienta', 'Pfeffer-Tee', 'beverages', 'snacks', 'pan_chinese', 0, 1, 0),
  R(`تشا بالكاري ${T}`, 'Curry tea', 'The curry', 'Té curry', 'Curry-Tee', 'beverages', 'snacks', 'pan_chinese', 1, 0, 0),
  R(`تشا بالطماطم ${T}`, 'Tomato tea', 'The tomate', 'Té tomate', 'Tomaten-Tee', 'beverages', 'snacks', 'pan_chinese', 0, 1, 0),
  R(`تشا بالفطر ${T}`, 'Mushroom tea', 'The champignons', 'Té hongos', 'Pilz-Tee', 'beverages', 'snacks', 'pan_chinese', 1, 0, 0),
  R(`تشا بالذرة ${T}`, 'Corn tea', 'The mais', 'Té maíz', 'Mais-Tee', 'beverages', 'snacks', 'pan_chinese', 0, 1, 0),
  R(`تشا بالبطاطس ${T}`, 'Potato tea', 'The pomme de terre', 'Té papa', 'Kartoffel-Tee', 'beverages', 'snacks', 'pan_chinese', 1, 0, 0),
  R(`تشا بالجزر ${T}`, 'Carrot tea', 'The carotte', 'Té zanahoria', 'Karotten-Tee', 'beverages', 'snacks', 'pan_chinese', 0, 1, 0),
  R(`تشا بالسبانخ ${T}`, 'Spinach tea', 'The epinards', 'Té espinacas', 'Spinat-Tee', 'beverages', 'snacks', 'pan_chinese', 1, 0, 0),
  R(`تشا بالبروكلي ${T}`, 'Broccoli tea', 'The brocoli', 'Té brócoli', 'Brokkoli-Tee', 'beverages', 'snacks', 'pan_chinese', 0, 1, 0),
  R(`تشا بالبازلاء ${T}`, 'Pea tea', 'The petits pois', 'Té guisantes', 'Erbsen-Tee', 'beverages', 'snacks', 'pan_chinese', 1, 0, 0),
  R(`تشا بالخضار المشكلة ${T}`, 'Mixed vegetable tea', 'The legumes varies', 'Té verduras mixtas', 'Gemüse-Tee', 'beverages', 'snacks', 'pan_chinese', 0, 1, 0),
  R(`تشا بالموز ${T}`, 'Banana tea', 'The banane', 'Té plátano', 'Bananen-Tee', 'beverages', 'snacks', 'pan_chinese', 1, 0, 0),
  R(`تشا بجوز الهند ${T}`, 'Coconut tea', 'The noix de coco', 'Té coco', 'Kokosnuss-Tee', 'beverages', 'snacks', 'pan_chinese', 0, 1, 0),
  R(`تشا بالموز وجوز الهند ${T}`, 'Banana coconut tea', 'The banane noix de coco', 'Té plátano coco', 'Bananen-Kokosnuss-Tee', 'beverages', 'snacks', 'pan_chinese', 1, 0, 0),
  R(`تشا بالزنجبيل والثوم ${T}`, 'Ginger garlic tea', 'The gingembre ail', 'Té jengibre ajo', 'Ingwer-Knoblauch-Tee', 'beverages', 'snacks', 'pan_chinese', 0, 1, 0),
  R(`تشا بالبصل والكزبرة ${T}`, 'Onion cilantro tea', 'The oignon coriandre', 'Té cebolla cilantro', 'Zwiebel-Koriander-Tee', 'beverages', 'snacks', 'pan_chinese', 1, 0, 0),
  R(`تشا بالليمون والفلفل ${T}`, 'Lemon pepper tea', 'The citron poivre', 'Té limón pimienta', 'Zitronen-Pfeffer-Tee', 'beverages', 'snacks', 'pan_chinese', 0, 1, 0),
];
