// Chinese expansion part 1 of 6: breakfast_items (25) + rice_dishes (30) = 55 rows.
// All dishes are distinct from the base 200. Halal: no pork, no alcohol.
import { R, T } from './rows.mjs';

export default [
  // --- breakfast_items (25) ---
  R(`كون تياو بالدجاج بالزنجبيل ${T}`, 'Ginger chicken rice noodles', 'Nouilles de riz poulet gingembre', 'Fideos de arroz pollo jengibre', 'Huhnreisnudeln mit Ingwer', 'breakfast_items', 'breakfast', 'pan_chinese', 9, 17, 3),
  R(`كون تياو بالدجاج بالثوم ${T}`, 'Garlic chicken rice noodles', 'Nouilles de riz poulet ail', 'Fideos de arroz pollo ajo', 'Huhnreisnudeln mit Knoblauch', 'breakfast_items', 'breakfast', 'pan_chinese', 8, 18, 2),
  R(`كون تياو بالدجاج بالبصل ${T}`, 'Onion chicken rice noodles', 'Nouilles de riz poulet oignon', 'Fideos de arroz pollo cebolla', 'Huhnreisnudeln mit Zwiebel', 'breakfast_items', 'breakfast', 'pan_chinese', 9, 16, 3),
  R(`كون تياو بالدجاج بالكزبرة ${T}`, 'Cilantro chicken rice noodles', 'Nouilles de riz poulet coriandre', 'Fideos de arroz pollo cilantro', 'Huhnreisnudeln mit Koriander', 'breakfast_items', 'breakfast', 'pan_chinese', 8, 17, 2),
  R(`كون تياو بالدجاج بالليمون ${T}`, 'Lemon chicken rice noodles', 'Nouilles de riz poulet citron', 'Fideos de arroz pollo limón', 'Huhnreisnudeln mit Zitrone', 'breakfast_items', 'breakfast', 'pan_chinese', 9, 15, 3),
  R(`كون تياو بالدجاج بالفلفل ${T}`, 'Pepper chicken rice noodles', 'Nouilles de riz poulet poivre', 'Fideos de arroz pollo pimienta', 'Huhnreisnudeln mit Pfeffer', 'breakfast_items', 'breakfast', 'pan_chinese', 8, 16, 2),
  R(`كون تياو بالدجاج بالكاري ${T}`, 'Curry chicken rice noodles', 'Nouilles de riz poulet curry', 'Fideos de arroz pollo curry', 'Huhnreisnudeln mit Curry', 'breakfast_items', 'breakfast', 'pan_chinese', 9, 17, 3),
  R(`كون تياو بالدجاج بالطماطم ${T}`, 'Tomato chicken rice noodles', 'Nouilles de riz poulet tomate', 'Fideos de arroz pollo tomate', 'Huhnreisnudeln mit Tomate', 'breakfast_items', 'breakfast', 'pan_chinese', 8, 18, 2),
  R(`كون تياو بالدجاج بالفطر ${T}`, 'Mushroom chicken rice noodles', 'Nouilles de riz poulet champignons', 'Fideos de arroz pollo hongos', 'Huhnreisnudeln mit Pilzen', 'breakfast_items', 'breakfast', 'pan_chinese', 9, 16, 3),
  R(`كون تياو بالدجاج بالذرة ${T}`, 'Corn chicken rice noodles', 'Nouilles de riz poulet mais', 'Fideos de arroz pollo maíz', 'Huhnreisnudeln mit Mais', 'breakfast_items', 'breakfast', 'pan_chinese', 8, 17, 2),
  R(`كون تياو بالدجاج بالبطاطس ${T}`, 'Potato chicken rice noodles', 'Nouilles de riz poulet pomme de terre', 'Fideos de arroz pollo papa', 'Huhnreisnudeln mit Kartoffel', 'breakfast_items', 'breakfast', 'pan_chinese', 9, 15, 3),
  R(`كون تياو بالدجاج بالجزر ${T}`, 'Carrot chicken rice noodles', 'Nouilles de riz poulet carotte', 'Fideos de arroz pollo zanahoria', 'Huhnreisnudeln mit Karotte', 'breakfast_items', 'breakfast', 'pan_chinese', 8, 16, 2),
  R(`كون تياو بالدجاج بالسبانخ ${T}`, 'Spinach chicken rice noodles', 'Nouilles de riz poulet epinards', 'Fideos de arroz pollo espinacas', 'Huhnreisnudeln mit Spinat', 'breakfast_items', 'breakfast', 'pan_chinese', 9, 14, 3),
  R(`كون تياو بالدجاج بالبروكلي ${T}`, 'Broccoli chicken rice noodles', 'Nouilles de riz poulet brocoli', 'Fideos de arroz pollo brócoli', 'Huhnreisnudeln mit Brokkoli', 'breakfast_items', 'breakfast', 'pan_chinese', 8, 15, 2),
  R(`كون تياو بالدجاج بالبازلاء ${T}`, 'Pea chicken rice noodles', 'Nouilles de riz poulet petits pois', 'Fideos de arroz pollo guisantes', 'Huhnreisnudeln mit Erbsen', 'breakfast_items', 'breakfast', 'pan_chinese', 9, 16, 3),
  R(`كون تياو بالدجاج بالخضار المشكلة ${T}`, 'Mixed vegetable chicken rice noodles', 'Nouilles de riz poulet legumes varies', 'Fideos de arroz pollo verduras mixtas', 'Huhnreisnudeln mit gemischtem Gemüse', 'breakfast_items', 'breakfast', 'pan_chinese', 8, 17, 2),
  R(`يو تياو بالزنجبيل ${T}`, 'Ginger fried dough sticks', 'Beignets gingembre', 'Churros jengibre', 'Gebratene Teigstangen mit Ingwer', 'breakfast_items', 'breakfast', 'pan_chinese', 7, 34, 11),
  R(`يو تياو بالثوم ${T}`, 'Garlic fried dough sticks', 'Beignets ail', 'Churros ajo', 'Gebratene Teigstangen mit Knoblauch', 'breakfast_items', 'breakfast', 'pan_chinese', 6, 35, 10),
  R(`يو تياو بالبصل ${T}`, 'Onion fried dough sticks', 'Beignets oignon', 'Churros cebolla', 'Gebratene Teigstangen mit Zwiebel', 'breakfast_items', 'breakfast', 'pan_chinese', 7, 33, 11),
  R(`يو تياو بالكزبرة ${T}`, 'Cilantro fried dough sticks', 'Beignets coriandre', 'Churros cilantro', 'Gebratene Teigstangen mit Koriander', 'breakfast_items', 'breakfast', 'pan_chinese', 6, 34, 10),
  R(`يو تياو بالليمون ${T}`, 'Lemon fried dough sticks', 'Beignets citron', 'Churros limón', 'Gebratene Teigstangen mit Zitrone', 'breakfast_items', 'breakfast', 'pan_chinese', 7, 32, 11),
  R(`يو تياو بالفلفل ${T}`, 'Pepper fried dough sticks', 'Beignets poivre', 'Churros pimienta', 'Gebratene Teigstangen mit Pfeffer', 'breakfast_items', 'breakfast', 'pan_chinese', 6, 33, 10),
  R(`يو تياو بالكاري ${T}`, 'Curry fried dough sticks', 'Beignets curry', 'Churros curry', 'Gebratene Teigstangen mit Curry', 'breakfast_items', 'breakfast', 'pan_chinese', 7, 34, 11),
  R(`يو تياو بالطماطم ${T}`, 'Tomato fried dough sticks', 'Beignets tomate', 'Churros tomate', 'Gebratene Teigstangen mit Tomate', 'breakfast_items', 'breakfast', 'pan_chinese', 6, 35, 10),
  R(`يو تياو بالفطر ${T}`, 'Mushroom fried dough sticks', 'Beignets champignons', 'Churros hongos', 'Gebratene Teigstangen mit Pilzen', 'breakfast_items', 'breakfast', 'pan_chinese', 7, 33, 11),

  // --- rice_dishes (30) ---
  R(`تشاو فان بالدجاج بالزنجبيل ${T}`, 'Ginger chicken fried rice', 'Riz frit poulet gingembre', 'Arroz frito pollo jengibre', 'Huhnreis mit Ingwer', 'rice_dishes', 'lunch', 'pan_chinese', 10, 27, 7),
  R(`تشاو فان بالدجاج بالثوم ${T}`, 'Garlic chicken fried rice', 'Riz frit poulet ail', 'Arroz frito pollo ajo', 'Huhnreis mit Knoblauch', 'rice_dishes', 'lunch', 'pan_chinese', 9, 28, 6),
  R(`تشاو فان بالدجاج بالبصل ${T}`, 'Onion chicken fried rice', 'Riz frit poulet oignon', 'Arroz frito pollo cebolla', 'Huhnreis mit Zwiebel', 'rice_dishes', 'lunch', 'pan_chinese', 10, 26, 7),
  R(`تشاو فان بالدجاج بالكزبرة ${T}`, 'Cilantro chicken fried rice', 'Riz frit poulet coriandre', 'Arroz frito pollo cilantro', 'Huhnreis mit Koriander', 'rice_dishes', 'lunch', 'pan_chinese', 9, 27, 6),
  R(`تشاو فان بالدجاج بالليمون ${T}`, 'Lemon chicken fried rice', 'Riz frit poulet citron', 'Arroz frito pollo limón', 'Huhnreis mit Zitrone', 'rice_dishes', 'lunch', 'pan_chinese', 10, 25, 7),
  R(`تشاو فان بالدجاج بالفلفل ${T}`, 'Pepper chicken fried rice', 'Riz frit poulet poivre', 'Arroz frito pollo pimienta', 'Huhnreis mit Pfeffer', 'rice_dishes', 'lunch', 'pan_chinese', 9, 26, 6),
  R(`تشاو فان بالدجاج بالكاري ${T}`, 'Curry chicken fried rice', 'Riz frit poulet curry', 'Arroz frito pollo curry', 'Huhnreis mit Curry', 'rice_dishes', 'lunch', 'pan_chinese', 10, 27, 7),
  R(`تشاو فان بالدجاج بالطماطم ${T}`, 'Tomato chicken fried rice', 'Riz frit poulet tomate', 'Arroz frito pollo tomate', 'Huhnreis mit Tomate', 'rice_dishes', 'lunch', 'pan_chinese', 9, 28, 6),
  R(`تشاو فان بالدجاج بالفطر ${T}`, 'Mushroom chicken fried rice', 'Riz frit poulet champignons', 'Arroz frito pollo hongos', 'Huhnreis mit Pilzen', 'rice_dishes', 'lunch', 'pan_chinese', 10, 26, 7),
  R(`تشاو فان بالدجاج بالذرة ${T}`, 'Corn chicken fried rice', 'Riz frit poulet mais', 'Arroz frito pollo maíz', 'Huhnreis mit Mais', 'rice_dishes', 'lunch', 'pan_chinese', 9, 27, 6),
  R(`تشاو فان بالدجاج بالبطاطس ${T}`, 'Potato chicken fried rice', 'Riz frit poulet pomme de terre', 'Arroz frito pollo papa', 'Huhnreis mit Kartoffel', 'rice_dishes', 'lunch', 'pan_chinese', 10, 25, 7),
  R(`تشاو فان بالدجاج بالجزر ${T}`, 'Carrot chicken fried rice', 'Riz frit poulet carotte', 'Arroz frito pollo zanahoria', 'Huhnreis mit Karotte', 'rice_dishes', 'lunch', 'pan_chinese', 9, 26, 6),
  R(`تشاو فان بالدجاج بالسبانخ ${T}`, 'Spinach chicken fried rice', 'Riz frit poulet epinards', 'Arroz frito pollo espinacas', 'Huhnreis mit Spinat', 'rice_dishes', 'lunch', 'pan_chinese', 10, 24, 7),
  R(`تشاو فان بالدجاج بالبروكلي ${T}`, 'Broccoli chicken fried rice', 'Riz frit poulet brocoli', 'Arroz frito pollo brócoli', 'Huhnreis mit Brokkoli', 'rice_dishes', 'lunch', 'pan_chinese', 9, 25, 6),
  R(`تشاو فان بالدجاج بالبازلاء ${T}`, 'Pea chicken fried rice', 'Riz frit poulet petits pois', 'Arroz frito pollo guisantes', 'Huhnreis mit Erbsen', 'rice_dishes', 'lunch', 'pan_chinese', 10, 26, 7),
  R(`تشاو فان بالدجاج بالخضار المشكلة ${T}`, 'Mixed vegetable chicken fried rice', 'Riz frit poulet legumes varies', 'Arroz frito pollo verduras mixtas', 'Huhnreis mit gemischtem Gemüse', 'rice_dishes', 'lunch', 'pan_chinese', 9, 27, 6),
  R(`تشاو فان باللحم بالزنجبيل ${T}`, 'Ginger beef fried rice', 'Riz frit boeuf gingembre', 'Arroz frito ternera jengibre', 'Rindreis mit Ingwer', 'rice_dishes', 'lunch', 'pan_chinese', 12, 25, 8),
  R(`تشاو فان باللحم بالثوم ${T}`, 'Garlic beef fried rice', 'Riz frit boeuf ail', 'Arroz frito ternera ajo', 'Rindreis mit Knoblauch', 'rice_dishes', 'lunch', 'pan_chinese', 11, 26, 7),
  R(`تشاو فان باللحم بالبصل ${T}`, 'Onion beef fried rice', 'Riz frit boeuf oignon', 'Arroz frito ternera cebolla', 'Rindreis mit Zwiebel', 'rice_dishes', 'lunch', 'pan_chinese', 12, 24, 8),
  R(`تشاو فان باللحم بالكزبرة ${T}`, 'Cilantro beef fried rice', 'Riz frit boeuf coriandre', 'Arroz frito ternera cilantro', 'Rindreis mit Koriander', 'rice_dishes', 'lunch', 'pan_chinese', 11, 25, 7),
  R(`تشاو فان باللحم بالليمون ${T}`, 'Lemon beef fried rice', 'Riz frit boeuf citron', 'Arroz frito ternera limón', 'Rindreis mit Zitrone', 'rice_dishes', 'lunch', 'pan_chinese', 12, 23, 8),
  R(`تشاو فان باللحم بالفلفل ${T}`, 'Pepper beef fried rice', 'Riz frit boeuf poivre', 'Arroz frito ternera pimienta', 'Rindreis mit Pfeffer', 'rice_dishes', 'lunch', 'pan_chinese', 11, 24, 7),
  R(`تشاو فان باللحم بالكاري ${T}`, 'Curry beef fried rice', 'Riz frit boeuf curry', 'Arroz frito ternera curry', 'Rindreis mit Curry', 'rice_dishes', 'lunch', 'pan_chinese', 12, 25, 8),
  R(`تشاو فان باللحم بالطماطم ${T}`, 'Tomato beef fried rice', 'Riz frit boeuf tomate', 'Arroz frito ternera tomate', 'Rindreis mit Tomate', 'rice_dishes', 'lunch', 'pan_chinese', 11, 26, 7),
  R(`تشاو فان باللحم بالفطر ${T}`, 'Mushroom beef fried rice', 'Riz frit boeuf champignons', 'Arroz frito ternera hongos', 'Rindreis mit Pilzen', 'rice_dishes', 'lunch', 'pan_chinese', 12, 24, 8),
  R(`تشاو فان باللحم بالذرة ${T}`, 'Corn beef fried rice', 'Riz frit boeuf mais', 'Arroz frito ternera maíz', 'Rindreis mit Mais', 'rice_dishes', 'lunch', 'pan_chinese', 11, 25, 7),
  R(`تشاو فان باللحم بالبطاطس ${T}`, 'Potato beef fried rice', 'Riz frit boeuf pomme de terre', 'Arroz frito ternera papa', 'Rindreis mit Kartoffel', 'rice_dishes', 'lunch', 'pan_chinese', 12, 23, 8),
  R(`تشاو فان باللحم بالجزر ${T}`, 'Carrot beef fried rice', 'Riz frit boeuf carotte', 'Arroz frito ternera zanahoria', 'Rindreis mit Karotte', 'rice_dishes', 'lunch', 'pan_chinese', 11, 24, 7),
  R(`تشاو فان باللحم بالسبانخ ${T}`, 'Spinach beef fried rice', 'Riz frit boeuf epinards', 'Arroz frito ternera espinacas', 'Rindreis mit Spinat', 'rice_dishes', 'lunch', 'pan_chinese', 12, 22, 8),
  R(`تشاو فان باللحم بالبروكلي ${T}`, 'Broccoli beef fried rice', 'Riz frit boeuf brocoli', 'Arroz frito ternera brócoli', 'Rindreis mit Brokkoli', 'rice_dishes', 'lunch', 'pan_chinese', 11, 23, 7),
  R(`تشاو فان باللحم بالبازلاء ${T}`, 'Pea beef fried rice', 'Riz frit boeuf petits pois', 'Arroz frito ternera guisantes', 'Rindreis mit Erbsen', 'rice_dishes', 'lunch', 'pan_chinese', 12, 24, 8),
];
