// Japanese expansion part 4 of 6: meat_mains (25) + fish_seafood (30) = 55 rows.
// All dishes are distinct from the base 200 and parts 1-3. Halal: no pork, no alcohol.
import { R, T } from './rows.mjs';

export default [
  // --- meat_mains (25) ---
  R(`غيوياكي باللحم بالزنجبيل ${T}`, 'Ginger beef gyoza', 'Gyoza boeuf gingembre', 'Gyoza ternera jengibre', 'Rind-Gyoza mit Ingwer', 'meat_mains', 'dinner', 'pan_japanese', 15, 17, 9),
  R(`غيوياكي باللحم بالثوم ${T}`, 'Garlic beef gyoza', 'Gyoza boeuf ail', 'Gyoza ternera ajo', 'Rind-Gyoza mit Knoblauch', 'meat_mains', 'dinner', 'pan_japanese', 14, 18, 8),
  R(`غيوياكي باللحم بالبصل ${T}`, 'Onion beef gyoza', 'Gyoza boeuf oignon', 'Gyoza ternera cebolla', 'Rind-Gyoza mit Zwiebel', 'meat_mains', 'dinner', 'pan_japanese', 15, 16, 9),
  R(`غيوياكي باللحم بالكزبرة ${T}`, 'Cilantro beef gyoza', 'Gyoza boeuf coriandre', 'Gyoza ternera cilantro', 'Rind-Gyoza mit Koriander', 'meat_mains', 'dinner', 'pan_japanese', 14, 17, 8),
  R(`غيوياكي باللحم بالليمون ${T}`, 'Lemon beef gyoza', 'Gyoza boeuf citron', 'Gyoza ternera limón', 'Rind-Gyoza mit Zitrone', 'meat_mains', 'dinner', 'pan_japanese', 15, 15, 9),
  R(`غيوياكي باللحم بالفلفل ${T}`, 'Pepper beef gyoza', 'Gyoza boeuf poivre', 'Gyoza ternera pimienta', 'Rind-Gyoza mit Pfeffer', 'meat_mains', 'dinner', 'pan_japanese', 14, 16, 8),
  R(`غيوياكي باللحم بالكاري ${T}`, 'Curry beef gyoza', 'Gyoza boeuf curry', 'Gyoza ternera curry', 'Rind-Gyoza mit Curry', 'meat_mains', 'dinner', 'pan_japanese', 15, 17, 9),
  R(`غيوياكي باللحم بالطماطم ${T}`, 'Tomato beef gyoza', 'Gyoza boeuf tomate', 'Gyoza ternera tomate', 'Rind-Gyoza mit Tomate', 'meat_mains', 'dinner', 'pan_japanese', 14, 18, 8),
  R(`غيوياكي باللحم بالفطر ${T}`, 'Mushroom beef gyoza', 'Gyoza boeuf champignons', 'Gyoza ternera hongos', 'Rind-Gyoza mit Pilzen', 'meat_mains', 'dinner', 'pan_japanese', 15, 16, 9),
  R(`غيوياكي باللحم بالذرة ${T}`, 'Corn beef gyoza', 'Gyoza boeuf mais', 'Gyoza ternera maíz', 'Rind-Gyoza mit Mais', 'meat_mains', 'dinner', 'pan_japanese', 14, 17, 8),
  R(`غيوياكي باللحم بالبطاطس ${T}`, 'Potato beef gyoza', 'Gyoza boeuf pomme de terre', 'Gyoza ternera papa', 'Rind-Gyoza mit Kartoffel', 'meat_mains', 'dinner', 'pan_japanese', 15, 15, 9),
  R(`غيوياكي باللحم بالجزر ${T}`, 'Carrot beef gyoza', 'Gyoza boeuf carotte', 'Gyoza ternera zanahoria', 'Rind-Gyoza mit Karotte', 'meat_mains', 'dinner', 'pan_japanese', 14, 16, 8),
  R(`غيوياكي باللحم بالسبانخ ${T}`, 'Spinach beef gyoza', 'Gyoza boeuf epinards', 'Gyoza ternera espinacas', 'Rind-Gyoza mit Spinat', 'meat_mains', 'dinner', 'pan_japanese', 15, 14, 9),
  R(`غيوياكي باللحم بالبروكلي ${T}`, 'Broccoli beef gyoza', 'Gyoza boeuf brocoli', 'Gyoza ternera brócoli', 'Rind-Gyoza mit Brokkoli', 'meat_mains', 'dinner', 'pan_japanese', 14, 15, 8),
  R(`غيوياكي باللحم بالبازلاء ${T}`, 'Pea beef gyoza', 'Gyoza boeuf petits pois', 'Gyoza ternera guisantes', 'Rind-Gyoza mit Erbsen', 'meat_mains', 'dinner', 'pan_japanese', 15, 16, 9),
  R(`غيوياكي باللحم بالخضار المشكلة ${T}`, 'Mixed vegetable beef gyoza', 'Gyoza boeuf legumes varies', 'Gyoza ternera verduras mixtas', 'Rind-Gyoza mit gemischtem Gemüse', 'meat_mains', 'dinner', 'pan_japanese', 14, 17, 8),
  R(`غيوياكي بالدجاج بالزنجبيل ${T}`, 'Ginger chicken gyoza', 'Gyoza poulet gingembre', 'Gyoza pollo jengibre', 'Huhn-Gyoza mit Ingwer', 'meat_mains', 'dinner', 'pan_japanese', 14, 18, 8),
  R(`غيوياكي بالدجاج بالثوم ${T}`, 'Garlic chicken gyoza', 'Gyoza poulet ail', 'Gyoza pollo ajo', 'Huhn-Gyoza mit Knoblauch', 'meat_mains', 'dinner', 'pan_japanese', 13, 19, 7),
  R(`غيوياكي بالدجاج بالبصل ${T}`, 'Onion chicken gyoza', 'Gyoza poulet oignon', 'Gyoza pollo cebolla', 'Huhn-Gyoza mit Zwiebel', 'meat_mains', 'dinner', 'pan_japanese', 14, 17, 8),
  R(`غيوياكي بالدجاج بالكزبرة ${T}`, 'Cilantro chicken gyoza', 'Gyoza poulet coriandre', 'Gyoza pollo cilantro', 'Huhn-Gyoza mit Koriander', 'meat_mains', 'dinner', 'pan_japanese', 13, 18, 7),
  R(`غيوياكي بالدجاج بالليمون ${T}`, 'Lemon chicken gyoza', 'Gyoza poulet citron', 'Gyoza pollo limón', 'Huhn-Gyoza mit Zitrone', 'meat_mains', 'dinner', 'pan_japanese', 14, 16, 8),
  R(`غيوياكي بالدجاج بالفلفل ${T}`, 'Pepper chicken gyoza', 'Gyoza poulet poivre', 'Gyoza pollo pimienta', 'Huhn-Gyoza mit Pfeffer', 'meat_mains', 'dinner', 'pan_japanese', 13, 17, 7),
  R(`غيوياكي بالدجاج بالكاري ${T}`, 'Curry chicken gyoza', 'Gyoza poulet curry', 'Gyoza pollo curry', 'Huhn-Gyoza mit Curry', 'meat_mains', 'dinner', 'pan_japanese', 14, 18, 8),
  R(`غيوياكي بالدجاج بالطماطم ${T}`, 'Tomato chicken gyoza', 'Gyoza poulet tomate', 'Gyoza pollo tomate', 'Huhn-Gyoza mit Tomate', 'meat_mains', 'dinner', 'pan_japanese', 13, 19, 7),
  R(`غيوياكي بالدجاج بالفطر ${T}`, 'Mushroom chicken gyoza', 'Gyoza poulet champignons', 'Gyoza pollo hongos', 'Huhn-Gyoza mit Pilzen', 'meat_mains', 'dinner', 'pan_japanese', 14, 17, 8),

  // --- fish_seafood (30) ---
  R(`ساشيمي بالسلمون بالزنجبيل ${T}`, 'Ginger salmon sashimi', 'Sashimi saumon gingembre', 'Sashimi salmón jengibre', 'Lachs-Sashimi mit Ingwer', 'fish_seafood', 'dinner', 'pan_japanese', 19, 0, 7),
  R(`ساشيمي بالسلمون بالثوم ${T}`, 'Garlic salmon sashimi', 'Sashimi saumon ail', 'Sashimi salmón ajo', 'Lachs-Sashimi mit Knoblauch', 'fish_seafood', 'dinner', 'pan_japanese', 18, 0, 6),
  R(`ساشيمي بالسلمون بالبصل ${T}`, 'Onion salmon sashimi', 'Sashimi saumon oignon', 'Sashimi salmón cebolla', 'Lachs-Sashimi mit Zwiebel', 'fish_seafood', 'dinner', 'pan_japanese', 19, 0, 7),
  R(`ساشيمي بالسلمون بالكزبرة ${T}`, 'Cilantro salmon sashimi', 'Sashimi saumon coriandre', 'Sashimi salmón cilantro', 'Lachs-Sashimi mit Koriander', 'fish_seafood', 'dinner', 'pan_japanese', 18, 0, 6),
  R(`ساشيمي بالسلمون بالليمون ${T}`, 'Lemon salmon sashimi', 'Sashimi saumon citron', 'Sashimi salmón limón', 'Lachs-Sashimi mit Zitrone', 'fish_seafood', 'dinner', 'pan_japanese', 19, 0, 7),
  R(`ساشيمي بالسلمون بالفلفل ${T}`, 'Pepper salmon sashimi', 'Sashimi saumon poivre', 'Sashimi salmón pimienta', 'Lachs-Sashimi mit Pfeffer', 'fish_seafood', 'dinner', 'pan_japanese', 18, 0, 6),
  R(`ساشيمي بالسلمون بالكاري ${T}`, 'Curry salmon sashimi', 'Sashimi saumon curry', 'Sashimi salmón curry', 'Lachs-Sashimi mit Curry', 'fish_seafood', 'dinner', 'pan_japanese', 19, 0, 7),
  R(`ساشيمي بالسلمون بالطماطم ${T}`, 'Tomato salmon sashimi', 'Sashimi saumon tomate', 'Sashimi salmón tomate', 'Lachs-Sashimi mit Tomate', 'fish_seafood', 'dinner', 'pan_japanese', 18, 1, 6),
  R(`ساشيمي بالسلمون بالفطر ${T}`, 'Mushroom salmon sashimi', 'Sashimi saumon champignons', 'Sashimi salmón hongos', 'Lachs-Sashimi mit Pilzen', 'fish_seafood', 'dinner', 'pan_japanese', 19, 0, 7),
  R(`ساشيمي بالسلمون بالذرة ${T}`, 'Corn salmon sashimi', 'Sashimi saumon mais', 'Sashimi salmón maíz', 'Lachs-Sashimi mit Mais', 'fish_seafood', 'dinner', 'pan_japanese', 18, 1, 6),
  R(`ساشيمي بالسلمون بالبطاطس ${T}`, 'Potato salmon sashimi', 'Sashimi saumon pomme de terre', 'Sashimi salmón papa', 'Lachs-Sashimi mit Kartoffel', 'fish_seafood', 'dinner', 'pan_japanese', 19, 0, 7),
  R(`ساشيمي بالسلمون بالجزر ${T}`, 'Carrot salmon sashimi', 'Sashimi saumon carotte', 'Sashimi salmón zanahoria', 'Lachs-Sashimi mit Karotte', 'fish_seafood', 'dinner', 'pan_japanese', 18, 1, 6),
  R(`ساشيمي بالسلمون بالسبانخ ${T}`, 'Spinach salmon sashimi', 'Sashimi saumon epinards', 'Sashimi salmón espinacas', 'Lachs-Sashimi mit Spinat', 'fish_seafood', 'dinner', 'pan_japanese', 19, 1, 7),
  R(`ساشيمي بالسلمون بالبروكلي ${T}`, 'Broccoli salmon sashimi', 'Sashimi saumon brocoli', 'Sashimi salmón brócoli', 'Lachs-Sashimi mit Brokkoli', 'fish_seafood', 'dinner', 'pan_japanese', 18, 1, 6),
  R(`ساشيمي بالسلمون بالبازلاء ${T}`, 'Pea salmon sashimi', 'Sashimi saumon petits pois', 'Sashimi salmón guisantes', 'Lachs-Sashimi mit Erbsen', 'fish_seafood', 'dinner', 'pan_japanese', 19, 2, 7),
  R(`ساشيمي بالتونة بالزنجبيل ${T}`, 'Ginger tuna sashimi', 'Sashimi thon gingembre', 'Sashimi atún jengibre', 'Thunfisch-Sashimi mit Ingwer', 'fish_seafood', 'dinner', 'pan_japanese', 21, 0, 5),
  R(`ساشيمي بالتونة بالثوم ${T}`, 'Garlic tuna sashimi', 'Sashimi thon ail', 'Sashimi atún ajo', 'Thunfisch-Sashimi mit Knoblauch', 'fish_seafood', 'dinner', 'pan_japanese', 20, 0, 4),
  R(`ساشيمي بالتونة بالبصل ${T}`, 'Onion tuna sashimi', 'Sashimi thon oignon', 'Sashimi atún cebolla', 'Thunfisch-Sashimi mit Zwiebel', 'fish_seafood', 'dinner', 'pan_japanese', 21, 0, 5),
  R(`ساشيمي بالتونة بالكزبرة ${T}`, 'Cilantro tuna sashimi', 'Sashimi thon coriandre', 'Sashimi atún cilantro', 'Thunfisch-Sashimi mit Koriander', 'fish_seafood', 'dinner', 'pan_japanese', 20, 0, 4),
  R(`ساشيمي بالتونة بالليمون ${T}`, 'Lemon tuna sashimi', 'Sashimi thon citron', 'Sashimi atún limón', 'Thunfisch-Sashimi mit Zitrone', 'fish_seafood', 'dinner', 'pan_japanese', 21, 0, 5),
  R(`ساشيمي بالتونة بالفلفل ${T}`, 'Pepper tuna sashimi', 'Sashimi thon poivre', 'Sashimi atún pimienta', 'Thunfisch-Sashimi mit Pfeffer', 'fish_seafood', 'dinner', 'pan_japanese', 20, 0, 4),
  R(`ساشيمي بالتونة بالكاري ${T}`, 'Curry tuna sashimi', 'Sashimi thon curry', 'Sashimi atún curry', 'Thunfisch-Sashimi mit Curry', 'fish_seafood', 'dinner', 'pan_japanese', 21, 0, 5),
  R(`ساشيمي بالتونة بالطماطم ${T}`, 'Tomato tuna sashimi', 'Sashimi thon tomate', 'Sashimi atún tomate', 'Thunfisch-Sashimi mit Tomate', 'fish_seafood', 'dinner', 'pan_japanese', 20, 1, 4),
  R(`ساشيمي بالتونة بالفطر ${T}`, 'Mushroom tuna sashimi', 'Sashimi thon champignons', 'Sashimi atún hongos', 'Thunfisch-Sashimi mit Pilzen', 'fish_seafood', 'dinner', 'pan_japanese', 21, 0, 5),
  R(`ساشيمي بالتونة بالذرة ${T}`, 'Corn tuna sashimi', 'Sashimi thon mais', 'Sashimi atún maíz', 'Thunfisch-Sashimi mit Mais', 'fish_seafood', 'dinner', 'pan_japanese', 20, 1, 4),
  R(`ساشيمي بالتونة بالبطاطس ${T}`, 'Potato tuna sashimi', 'Sashimi thon pomme de terre', 'Sashimi atún papa', 'Thunfisch-Sashimi mit Kartoffel', 'fish_seafood', 'dinner', 'pan_japanese', 21, 0, 5),
  R(`ساشيمي بالتونة بالجزر ${T}`, 'Carrot tuna sashimi', 'Sashimi thon carotte', 'Sashimi atún zanahoria', 'Thunfisch-Sashimi mit Karotte', 'fish_seafood', 'dinner', 'pan_japanese', 20, 1, 4),
  R(`ساشيمي بالتونة بالسبانخ ${T}`, 'Spinach tuna sashimi', 'Sashimi thon epinards', 'Sashimi atún espinacas', 'Thunfisch-Sashimi mit Spinat', 'fish_seafood', 'dinner', 'pan_japanese', 21, 1, 5),
  R(`ساشيمي بالتونة بالبروكلي ${T}`, 'Broccoli tuna sashimi', 'Sashimi thon brocoli', 'Sashimi atún brócoli', 'Thunfisch-Sashimi mit Brokkoli', 'fish_seafood', 'dinner', 'pan_japanese', 20, 1, 4),
  R(`ساشيمي بالتونة بالبازلاء ${T}`, 'Pea tuna sashimi', 'Sashimi thon petits pois', 'Sashimi atún guisantes', 'Thunfisch-Sashimi mit Erbsen', 'fish_seafood', 'dinner', 'pan_japanese', 21, 2, 5),
];

