// Japanese expansion part 3 of 6: soups_stews (25) + poultry_mains (25) = 50 rows.
// All dishes are distinct from the base 200 and parts 1-2. Halal: no pork, no alcohol.
import { R, T } from './rows.mjs';

export default [
  // --- soups_stews (25) ---
  R(`ميسو شيرو بالزنجبيل ${T}`, 'Ginger vegetable miso soup', 'Soupe miso gingembre', 'Sopa miso jengibre', 'Gemüse-Miso-Suppe mit Ingwer', 'soups_stews', 'lunch', 'pan_japanese', 5, 7, 2),
  R(`ميسو شيرو بالثوم ${T}`, 'Garlic vegetable miso soup', 'Soupe miso ail', 'Sopa miso ajo', 'Gemüse-Miso-Suppe mit Knoblauch', 'soups_stews', 'lunch', 'pan_japanese', 4, 8, 1),
  R(`ميسو شيرو بالبصل ${T}`, 'Onion vegetable miso soup', 'Soupe miso oignon', 'Sopa miso cebolla', 'Gemüse-Miso-Suppe mit Zwiebel', 'soups_stews', 'lunch', 'pan_japanese', 5, 6, 2),
  R(`ميسو شيرو بالكزبرة ${T}`, 'Cilantro vegetable miso soup', 'Soupe miso coriandre', 'Sopa miso cilantro', 'Gemüse-Miso-Suppe mit Koriander', 'soups_stews', 'lunch', 'pan_japanese', 4, 7, 1),
  R(`ميسو شيرو بالليمون ${T}`, 'Lemon vegetable miso soup', 'Soupe miso citron', 'Sopa miso limón', 'Gemüse-Miso-Suppe mit Zitrone', 'soups_stews', 'lunch', 'pan_japanese', 5, 5, 2),
  R(`ميسو شيرو بالفلفل ${T}`, 'Pepper vegetable miso soup', 'Soupe miso poivre', 'Sopa miso pimienta', 'Gemüse-Miso-Suppe mit Pfeffer', 'soups_stews', 'lunch', 'pan_japanese', 4, 6, 1),
  R(`ميسو شيرو بالكاري ${T}`, 'Curry vegetable miso soup', 'Soupe miso curry', 'Sopa miso curry', 'Gemüse-Miso-Suppe mit Curry', 'soups_stews', 'lunch', 'pan_japanese', 5, 7, 2),
  R(`ميسو شيرو بالطماطم ${T}`, 'Tomato vegetable miso soup', 'Soupe miso tomate', 'Sopa miso tomate', 'Gemüse-Miso-Suppe mit Tomate', 'soups_stews', 'lunch', 'pan_japanese', 4, 8, 1),
  R(`ميسو شيرو بالفطر ${T}`, 'Mushroom vegetable miso soup', 'Soupe miso champignons', 'Sopa miso hongos', 'Gemüse-Miso-Suppe mit Pilzen', 'soups_stews', 'lunch', 'pan_japanese', 5, 6, 2),
  R(`ميسو شيرو بالذرة ${T}`, 'Corn vegetable miso soup', 'Soupe miso mais', 'Sopa miso maíz', 'Gemüse-Miso-Suppe mit Mais', 'soups_stews', 'lunch', 'pan_japanese', 4, 7, 1),
  R(`ميسو شيرو بالبطاطس ${T}`, 'Potato vegetable miso soup', 'Soupe miso pomme de terre', 'Sopa miso papa', 'Gemüse-Miso-Suppe mit Kartoffel', 'soups_stews', 'lunch', 'pan_japanese', 5, 5, 2),
  R(`ميسو شيرو بالجزر ${T}`, 'Carrot vegetable miso soup', 'Soupe miso carotte', 'Sopa miso zanahoria', 'Gemüse-Miso-Suppe mit Karotte', 'soups_stews', 'lunch', 'pan_japanese', 4, 6, 1),
  R(`ميسو شيرو بالسبانخ ${T}`, 'Spinach vegetable miso soup', 'Soupe miso epinards', 'Sopa miso espinacas', 'Gemüse-Miso-Suppe mit Spinat', 'soups_stews', 'lunch', 'pan_japanese', 5, 4, 2),
  R(`ميسو شيرو بالبروكلي ${T}`, 'Broccoli vegetable miso soup', 'Soupe miso brocoli', 'Sopa miso brócoli', 'Gemüse-Miso-Suppe mit Brokkoli', 'soups_stews', 'lunch', 'pan_japanese', 4, 5, 1),
  R(`ميسو شيرو بالبازلاء ${T}`, 'Pea vegetable miso soup', 'Soupe miso petits pois', 'Sopa miso guisantes', 'Gemüse-Miso-Suppe mit Erbsen', 'soups_stews', 'lunch', 'pan_japanese', 5, 6, 2),
  R(`ميسو شيرو بالخضار المشكلة ${T}`, 'Mixed vegetable miso soup', 'Soupe miso legumes varies', 'Sopa miso verduras mixtas', 'Gemüse-Miso-Suppe mit gemischtem Gemüse', 'soups_stews', 'lunch', 'pan_japanese', 4, 7, 1),
  R(`سوكيياكي بالدجاج بالزنجبيل ${T}`, 'Ginger chicken sukiyaki', 'Sukiyaki poulet gingembre', 'Sukiyaki pollo jengibre', 'Huhn-Sukiyaki mit Ingwer', 'soups_stews', 'dinner', 'pan_japanese', 15, 9, 9),
  R(`سوكيياكي بالدجاج بالثوم ${T}`, 'Garlic chicken sukiyaki', 'Sukiyaki poulet ail', 'Sukiyaki pollo ajo', 'Huhn-Sukiyaki mit Knoblauch', 'soups_stews', 'dinner', 'pan_japanese', 14, 10, 8),
  R(`سوكيياكي بالدجاج بالبصل ${T}`, 'Onion chicken sukiyaki', 'Sukiyaki poulet oignon', 'Sukiyaki pollo cebolla', 'Huhn-Sukiyaki mit Zwiebel', 'soups_stews', 'dinner', 'pan_japanese', 15, 8, 9),
  R(`سوكيياكي بالدجاج بالكزبرة ${T}`, 'Cilantro chicken sukiyaki', 'Sukiyaki poulet coriandre', 'Sukiyaki pollo cilantro', 'Huhn-Sukiyaki mit Koriander', 'soups_stews', 'dinner', 'pan_japanese', 14, 9, 8),
  R(`سوكيياكي بالدجاج بالليمون ${T}`, 'Lemon chicken sukiyaki', 'Sukiyaki poulet citron', 'Sukiyaki pollo limón', 'Huhn-Sukiyaki mit Zitrone', 'soups_stews', 'dinner', 'pan_japanese', 15, 7, 9),
  R(`سوكيياكي بالدجاج بالفلفل ${T}`, 'Pepper chicken sukiyaki', 'Sukiyaki poulet poivre', 'Sukiyaki pollo pimienta', 'Huhn-Sukiyaki mit Pfeffer', 'soups_stews', 'dinner', 'pan_japanese', 14, 8, 8),
  R(`سوكيياكي بالدجاج بالكاري ${T}`, 'Curry chicken sukiyaki', 'Sukiyaki poulet curry', 'Sukiyaki pollo curry', 'Huhn-Sukiyaki mit Curry', 'soups_stews', 'dinner', 'pan_japanese', 15, 9, 9),
  R(`سوكيياكي بالدجاج بالطماطم ${T}`, 'Tomato chicken sukiyaki', 'Sukiyaki poulet tomate', 'Sukiyaki pollo tomate', 'Huhn-Sukiyaki mit Tomate', 'soups_stews', 'dinner', 'pan_japanese', 14, 10, 8),
  R(`سوكيياكي بالدجاج بالفطر ${T}`, 'Mushroom chicken sukiyaki', 'Sukiyaki poulet champignons', 'Sukiyaki pollo hongos', 'Huhn-Sukiyaki mit Pilzen', 'soups_stews', 'dinner', 'pan_japanese', 15, 8, 9),

  // --- poultry_mains (25) ---
  R(`توري ياكي بالزنجبيل ${T}`, 'Aromatic ginger grilled chicken', 'Poulet grille gingembre', 'Pollo asado jengibre', 'Gegrilltes Hähnchen mit Ingwer', 'poultry_mains', 'dinner', 'pan_japanese', 21, 3, 8),
  R(`توري ياكي بالثوم ${T}`, 'Aromatic garlic grilled chicken', 'Poulet grille ail', 'Pollo asado ajo', 'Gegrilltes Hähnchen mit Knoblauch', 'poultry_mains', 'dinner', 'pan_japanese', 20, 4, 7),
  R(`توري ياكي بالبصل ${T}`, 'Aromatic onion grilled chicken', 'Poulet grille oignon', 'Pollo asado cebolla', 'Gegrilltes Hähnchen mit Zwiebel', 'poultry_mains', 'dinner', 'pan_japanese', 21, 2, 8),
  R(`توري ياكي بالكزبرة ${T}`, 'Aromatic cilantro grilled chicken', 'Poulet grille coriandre', 'Pollo asado cilantro', 'Gegrilltes Hähnchen mit Koriander', 'poultry_mains', 'dinner', 'pan_japanese', 20, 3, 7),
  R(`توري ياكي بالليمون ${T}`, 'Aromatic lemon grilled chicken', 'Poulet grille citron', 'Pollo asado limón', 'Gegrilltes Hähnchen mit Zitrone', 'poultry_mains', 'dinner', 'pan_japanese', 21, 1, 8),
  R(`توري ياكي بالفلفل ${T}`, 'Aromatic pepper grilled chicken', 'Poulet grille poivre', 'Pollo asado pimienta', 'Gegrilltes Hähnchen mit Pfeffer', 'poultry_mains', 'dinner', 'pan_japanese', 20, 2, 7),
  R(`توري ياكي بالكاري ${T}`, 'Aromatic curry grilled chicken', 'Poulet grille curry', 'Pollo asado curry', 'Gegrilltes Hähnchen mit Curry', 'poultry_mains', 'dinner', 'pan_japanese', 21, 3, 8),
  R(`توري ياكي بالطماطم ${T}`, 'Aromatic tomato grilled chicken', 'Poulet grille tomate', 'Pollo asado tomate', 'Gegrilltes Hähnchen mit Tomate', 'poultry_mains', 'dinner', 'pan_japanese', 20, 4, 7),
  R(`توري ياكي بالفطر ${T}`, 'Aromatic mushroom grilled chicken', 'Poulet grille champignons', 'Pollo asado hongos', 'Gegrilltes Hähnchen mit Pilzen', 'poultry_mains', 'dinner', 'pan_japanese', 21, 2, 8),
  R(`توري ياكي بالذرة ${T}`, 'Aromatic corn grilled chicken', 'Poulet grille mais', 'Pollo asado maíz', 'Gegrilltes Hähnchen mit Mais', 'poultry_mains', 'dinner', 'pan_japanese', 20, 3, 7),
  R(`توري ياكي بالبطاطس ${T}`, 'Aromatic potato grilled chicken', 'Poulet grille pomme de terre', 'Pollo asado papa', 'Gegrilltes Hähnchen mit Kartoffel', 'poultry_mains', 'dinner', 'pan_japanese', 21, 1, 8),
  R(`توري ياكي بالجزر ${T}`, 'Aromatic carrot grilled chicken', 'Poulet grille carotte', 'Pollo asado zanahoria', 'Gegrilltes Hähnchen mit Karotte', 'poultry_mains', 'dinner', 'pan_japanese', 20, 2, 7),
  R(`توري ياكي بالسبانخ ${T}`, 'Aromatic spinach grilled chicken', 'Poulet grille epinards', 'Pollo asado espinacas', 'Gegrilltes Hähnchen mit Spinat', 'poultry_mains', 'dinner', 'pan_japanese', 21, 1, 8),
  R(`توري ياكي بالبروكلي ${T}`, 'Aromatic broccoli grilled chicken', 'Poulet grille brocoli', 'Pollo asado brócoli', 'Gegrilltes Hähnchen mit Brokkoli', 'poultry_mains', 'dinner', 'pan_japanese', 20, 2, 7),
  R(`توري ياكي بالبازلاء ${T}`, 'Aromatic pea grilled chicken', 'Poulet grille petits pois', 'Pollo asado guisantes', 'Gegrilltes Hähnchen mit Erbsen', 'poultry_mains', 'dinner', 'pan_japanese', 21, 3, 8),
  R(`توري ياكي بالخضار المشكلة ${T}`, 'Aromatic mixed vegetable grilled chicken', 'Poulet grille legumes varies', 'Pollo asado verduras mixtas', 'Gegrilltes Hähnchen mit gemischtem Gemüse', 'poultry_mains', 'dinner', 'pan_japanese', 20, 4, 7),
  R(`توري ياكي بالدجاج والخضار ${T}`, 'Aromatic chicken grilled with vegetables', 'Poulet grille poulet legumes', 'Pollo asado pollo verduras', 'Huhn-Gemüse-Gegrillt', 'poultry_mains', 'dinner', 'pan_japanese', 22, 2, 9),
  R(`توري ياكي بالدجاج واللحم ${T}`, 'Chicken beef grilled chicken', 'Poulet grille poulet boeuf', 'Pollo asado pollo ternera', 'Huhn-Rind-Gegrillt', 'poultry_mains', 'dinner', 'pan_japanese', 23, 2, 10),
  R(`توري ياكي بالدجاج والروبيان ${T}`, 'Chicken shrimp grilled chicken', 'Poulet grille poulet crevettes', 'Pollo asado pollo camarones', 'Huhn-Garnelen-Gegrillt', 'poultry_mains', 'dinner', 'pan_japanese', 22, 3, 9),
  R(`توري ياكي باللحم والروبيان ${T}`, 'Beef shrimp grilled chicken', 'Poulet grille boeuf crevettes', 'Pollo asado ternera camarones', 'Rind-Garnelen-Gegrillt', 'poultry_mains', 'dinner', 'pan_japanese', 23, 2, 10),
  R(`توري ياكي بالدجاج واللحم والروبيان ${T}`, 'Chicken beef shrimp grilled chicken', 'Poulet grille poulet boeuf crevettes', 'Pollo asado pollo ternera camarones', 'Huhn-Rind-Garnelen-Gegrillt', 'poultry_mains', 'dinner', 'pan_japanese', 24, 2, 11),
  R(`توري ياكي بالخضار والدجاج واللحم ${T}`, 'Vegetable chicken beef grilled chicken', 'Poulet grille legumes poulet boeuf', 'Pollo asado verduras pollo ternera', 'Gemüse-Huhn-Rind-Gegrillt', 'poultry_mains', 'dinner', 'pan_japanese', 22, 3, 10),
  R(`توري ياكي بالخضار والروبيان والبيض ${T}`, 'Vegetable shrimp egg grilled chicken', 'Poulet grille legumes crevettes oeufs', 'Pollo asado verduras camarones huevo', 'Gemüse-Garnelen-Eier-Gegrillt', 'poultry_mains', 'dinner', 'pan_japanese', 20, 5, 8),
  R(`توري ياكي بالدجاج والخضار والبيض ${T}`, 'Chicken vegetable egg grilled chicken', 'Poulet grille poulet legumes oeufs', 'Pollo asado pollo verduras huevo', 'Huhn-Gemüse-Eier-Gegrillt', 'poultry_mains', 'dinner', 'pan_japanese', 21, 4, 9),
  R(`توري ياكي باللحم والخضار والبيض ${T}`, 'Beef vegetable egg grilled chicken', 'Poulet grille boeuf legumes oeufs', 'Pollo asado ternera verduras huevo', 'Rind-Gemüse-Eier-Gegrillt', 'poultry_mains', 'dinner', 'pan_japanese', 22, 3, 10),
];

