// Japanese expansion part 6 of 6: rice_cakes_sweets (18) + street_snacks (20) + condiments_sauces (10) + beverages (27) = 75 rows.
// All dishes are distinct from the base 200 and parts 1-5. Halal: no pork, no alcohol.
import { R, T } from './rows.mjs';

export default [
  // --- rice_cakes_sweets (18) ---
  R(`موتشي بالفول بالزنجبيل ${T}`, 'Aromatic ginger red bean mochi', 'Mochi haricots rouges gingembre', 'Mochi frijoles rojos jengibre', 'Rote-Bohnen-Mochi mit Ingwer', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 5, 25, 3),
  R(`موتشي بالفول بالثوم ${T}`, 'Aromatic garlic red bean mochi', 'Mochi haricots rouges ail', 'Mochi frijoles rojos ajo', 'Rote-Bohnen-Mochi mit Knoblauch', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 4, 26, 2),
  R(`موتشي بالفول بالبصل ${T}`, 'Aromatic onion red bean mochi', 'Mochi haricots rouges oignon', 'Mochi frijoles rojos cebolla', 'Rote-Bohnen-Mochi mit Zwiebel', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 5, 24, 3),
  R(`موتشي بالفول بالكزبرة ${T}`, 'Aromatic cilantro red bean mochi', 'Mochi haricots rouges coriandre', 'Mochi frijoles rojos cilantro', 'Rote-Bohnen-Mochi mit Koriander', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 4, 25, 2),
  R(`موتشي بالفول بالليمون ${T}`, 'Aromatic lemon red bean mochi', 'Mochi haricots rouges citron', 'Mochi frijoles rojos limón', 'Rote-Bohnen-Mochi mit Zitrone', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 5, 23, 3),
  R(`موتشي بالفول بالفلفل ${T}`, 'Aromatic pepper red bean mochi', 'Mochi haricots rouges poivre', 'Mochi frijoles rojos pimienta', 'Rote-Bohnen-Mochi mit Pfeffer', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 4, 24, 2),
  R(`موتشي بالفول بالكاري ${T}`, 'Aromatic curry red bean mochi', 'Mochi haricots rouges curry', 'Mochi frijoles rojos curry', 'Rote-Bohnen-Mochi mit Curry', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 5, 25, 3),
  R(`موتشي بالفول بالطماطم ${T}`, 'Aromatic tomato red bean mochi', 'Mochi haricots rouges tomate', 'Mochi frijoles rojos tomate', 'Rote-Bohnen-Mochi mit Tomate', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 4, 26, 2),
  R(`موتشي بالفول بالفطر ${T}`, 'Aromatic mushroom red bean mochi', 'Mochi haricots rouges champignons', 'Mochi frijoles rojos hongos', 'Rote-Bohnen-Mochi mit Pilzen', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 5, 24, 3),
  R(`موتشي بالفول بالذرة ${T}`, 'Aromatic corn red bean mochi', 'Mochi haricots rouges mais', 'Mochi frijoles rojos maíz', 'Rote-Bohnen-Mochi mit Mais', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 4, 25, 2),
  R(`موتشي بالفول بالبطاطس ${T}`, 'Aromatic potato red bean mochi', 'Mochi haricots rouges pomme de terre', 'Mochi frijoles rojos papa', 'Rote-Bohnen-Mochi mit Kartoffel', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 5, 23, 3),
  R(`موتشي بالفول بالجزر ${T}`, 'Aromatic carrot red bean mochi', 'Mochi haricots rouges carotte', 'Mochi frijoles rojos zanahoria', 'Rote-Bohnen-Mochi mit Karotte', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 4, 24, 2),
  R(`موتشي بالفول بالسبانخ ${T}`, 'Aromatic spinach red bean mochi', 'Mochi haricots rouges epinards', 'Mochi frijoles rojos espinacas', 'Rote-Bohnen-Mochi mit Spinat', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 5, 22, 3),
  R(`موتشي بالفول بالبروكلي ${T}`, 'Aromatic broccoli red bean mochi', 'Mochi haricots rouges brocoli', 'Mochi frijoles rojos brócoli', 'Rote-Bohnen-Mochi mit Brokkoli', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 4, 23, 2),
  R(`موتشي بالفول بالبازلاء ${T}`, 'Aromatic pea red bean mochi', 'Mochi haricots rouges petits pois', 'Mochi frijoles rojos guisantes', 'Rote-Bohnen-Mochi mit Erbsen', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 5, 24, 3),
  R(`موتشي بالفول بالخضار المشكلة ${T}`, 'Aromatic mixed vegetable red bean mochi', 'Mochi haricots rouges legumes varies', 'Mochi frijoles rojos verduras mixtas', 'Rote-Bohnen-Mochi mit gemischtem Gemüse', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 4, 25, 2),
  R(`موتشي بالفول بالموز ${T}`, 'Aromatic banana red bean mochi', 'Mochi haricots rouges banane', 'Mochi frijoles rojos plátano', 'Rote-Bohnen-Mochi mit Banane', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 6, 23, 4),
  R(`موتشي بالفول بجوز الهند ${T}`, 'Aromatic coconut red bean mochi', 'Mochi haricots rouges noix de coco', 'Mochi frijoles rojos coco', 'Rote-Bohnen-Mochi mit Kokosnuss', 'rice_cakes_sweets', 'snacks', 'pan_japanese', 5, 24, 3),

  // --- street_snacks (20) ---
  R(`تاكوياكي بالدجاج بالزنجبيل ${T}`, 'Ginger chicken takoyaki', 'Takoyaki poulet gingembre', 'Takoyaki pollo jengibre', 'Huhn-Takoyaki mit Ingwer', 'street_snacks', 'snacks', 'pan_japanese', 11, 17, 7),
  R(`تاكوياكي بالدجاج بالثوم ${T}`, 'Garlic chicken takoyaki', 'Takoyaki poulet ail', 'Takoyaki pollo ajo', 'Huhn-Takoyaki mit Knoblauch', 'street_snacks', 'snacks', 'pan_japanese', 10, 18, 6),
  R(`تاكوياكي بالدجاج بالبصل ${T}`, 'Onion chicken takoyaki', 'Takoyaki poulet oignon', 'Takoyaki pollo cebolla', 'Huhn-Takoyaki mit Zwiebel', 'street_snacks', 'snacks', 'pan_japanese', 11, 16, 7),
  R(`تاكوياكي بالدجاج بالكزبرة ${T}`, 'Cilantro chicken takoyaki', 'Takoyaki poulet coriandre', 'Takoyaki pollo cilantro', 'Huhn-Takoyaki mit Koriander', 'street_snacks', 'snacks', 'pan_japanese', 10, 17, 6),
  R(`تاكوياكي بالدجاج بالليمون ${T}`, 'Lemon chicken takoyaki', 'Takoyaki poulet citron', 'Takoyaki pollo limón', 'Huhn-Takoyaki mit Zitrone', 'street_snacks', 'snacks', 'pan_japanese', 11, 15, 7),
  R(`تاكوياكي بالدجاج بالفلفل ${T}`, 'Pepper chicken takoyaki', 'Takoyaki poulet poivre', 'Takoyaki pollo pimienta', 'Huhn-Takoyaki mit Pfeffer', 'street_snacks', 'snacks', 'pan_japanese', 10, 16, 6),
  R(`تاكوياكي بالدجاج بالكاري ${T}`, 'Curry chicken takoyaki', 'Takoyaki poulet curry', 'Takoyaki pollo curry', 'Huhn-Takoyaki mit Curry', 'street_snacks', 'snacks', 'pan_japanese', 11, 17, 7),
  R(`تاكوياكي بالدجاج بالطماطم ${T}`, 'Tomato chicken takoyaki', 'Takoyaki poulet tomate', 'Takoyaki pollo tomate', 'Huhn-Takoyaki mit Tomate', 'street_snacks', 'snacks', 'pan_japanese', 10, 18, 6),
  R(`تاكوياكي بالدجاج بالفطر ${T}`, 'Mushroom chicken takoyaki', 'Takoyaki poulet champignons', 'Takoyaki pollo hongos', 'Huhn-Takoyaki mit Pilzen', 'street_snacks', 'snacks', 'pan_japanese', 11, 16, 7),
  R(`تاكوياكي بالدجاج بالذرة ${T}`, 'Corn chicken takoyaki', 'Takoyaki poulet mais', 'Takoyaki pollo maíz', 'Huhn-Takoyaki mit Mais', 'street_snacks', 'snacks', 'pan_japanese', 10, 17, 6),
  R(`تاكوياكي بالدجاج بالبطاطس ${T}`, 'Potato chicken takoyaki', 'Takoyaki poulet pomme de terre', 'Takoyaki pollo papa', 'Huhn-Takoyaki mit Kartoffel', 'street_snacks', 'snacks', 'pan_japanese', 11, 15, 7),
  R(`تاكوياكي بالدجاج بالجزر ${T}`, 'Carrot chicken takoyaki', 'Takoyaki poulet carotte', 'Takoyaki pollo zanahoria', 'Huhn-Takoyaki mit Karotte', 'street_snacks', 'snacks', 'pan_japanese', 10, 16, 6),
  R(`تاكوياكي بالدجاج بالسبانخ ${T}`, 'Spinach chicken takoyaki', 'Takoyaki poulet epinards', 'Takoyaki pollo espinacas', 'Huhn-Takoyaki mit Spinat', 'street_snacks', 'snacks', 'pan_japanese', 11, 14, 7),
  R(`تاكوياكي بالدجاج بالبروكلي ${T}`, 'Broccoli chicken takoyaki', 'Takoyaki poulet brocoli', 'Takoyaki pollo brócoli', 'Huhn-Takoyaki mit Brokkoli', 'street_snacks', 'snacks', 'pan_japanese', 10, 15, 6),
  R(`تاكوياكي بالدجاج بالبازلاء ${T}`, 'Pea chicken takoyaki', 'Takoyaki poulet petits pois', 'Takoyaki pollo guisantes', 'Huhn-Takoyaki mit Erbsen', 'street_snacks', 'snacks', 'pan_japanese', 11, 16, 7),
  R(`تاكوياكي بالدجاج بالخضار المشكلة ${T}`, 'Mixed vegetable chicken takoyaki', 'Takoyaki poulet legumes varies', 'Takoyaki pollo verduras mixtas', 'Huhn-Takoyaki mit gemischtem Gemüse', 'street_snacks', 'snacks', 'pan_japanese', 10, 17, 6),
  R(`تاكوياكي باللحم بالزنجبيل ${T}`, 'Ginger beef takoyaki', 'Takoyaki boeuf gingembre', 'Takoyaki ternera jengibre', 'Rind-Takoyaki mit Ingwer', 'street_snacks', 'snacks', 'pan_japanese', 13, 15, 9),
  R(`تاكوياكي باللحم بالثوم ${T}`, 'Garlic beef takoyaki', 'Takoyaki boeuf ail', 'Takoyaki ternera ajo', 'Rind-Takoyaki mit Knoblauch', 'street_snacks', 'snacks', 'pan_japanese', 12, 16, 8),
  R(`تاكوياكي باللحم بالبصل ${T}`, 'Onion beef takoyaki', 'Takoyaki boeuf oignon', 'Takoyaki ternera cebolla', 'Rind-Takoyaki mit Zwiebel', 'street_snacks', 'snacks', 'pan_japanese', 13, 14, 9),
  R(`تاكوياكي باللحم بالكزبرة ${T}`, 'Cilantro beef takoyaki', 'Takoyaki boeuf coriandre', 'Takoyaki ternera cilantro', 'Rind-Takoyaki mit Koriander', 'street_snacks', 'snacks', 'pan_japanese', 12, 15, 8),

  // --- condiments_sauces (10) ---
  R(`شويو بالزنجبيل ${T}`, 'Aromatic ginger soy sauce', 'Sauce soja gingembre', 'Salsa de soja jengibre', 'Sojasauce mit Ingwer', 'condiments_sauces', 'snacks', 'pan_japanese', 6, 9, 1),
  R(`شويو بالثوم ${T}`, 'Aromatic garlic soy sauce', 'Sauce soja ail', 'Salsa de soja ajo', 'Sojasauce mit Knoblauch', 'condiments_sauces', 'snacks', 'pan_japanese', 5, 10, 1),
  R(`شويو بالبصل ${T}`, 'Aromatic onion soy sauce', 'Sauce soja oignon', 'Salsa de soja cebolla', 'Sojasauce mit Zwiebel', 'condiments_sauces', 'snacks', 'pan_japanese', 6, 8, 1),
  R(`شويو بالكزبرة ${T}`, 'Aromatic cilantro soy sauce', 'Sauce soja coriandre', 'Salsa de soja cilantro', 'Sojasauce mit Koriander', 'condiments_sauces', 'snacks', 'pan_japanese', 5, 9, 1),
  R(`شويو بالليمون ${T}`, 'Aromatic lemon soy sauce', 'Sauce soja citron', 'Salsa de soja limón', 'Sojasauce mit Zitrone', 'condiments_sauces', 'snacks', 'pan_japanese', 6, 7, 1),
  R(`شويو بالفلفل ${T}`, 'Aromatic pepper soy sauce', 'Sauce soja poivre', 'Salsa de soja pimienta', 'Sojasauce mit Pfeffer', 'condiments_sauces', 'snacks', 'pan_japanese', 5, 8, 1),
  R(`شويو بالكاري ${T}`, 'Aromatic curry soy sauce', 'Sauce soja curry', 'Salsa de soja curry', 'Sojasauce mit Curry', 'condiments_sauces', 'snacks', 'pan_japanese', 7, 7, 2),
  R(`شويو بالطماطم ${T}`, 'Aromatic tomato soy sauce', 'Sauce soja tomate', 'Salsa de soja tomate', 'Sojasauce mit Tomate', 'condiments_sauces', 'snacks', 'pan_japanese', 6, 8, 1),
  R(`شويو بالفطر ${T}`, 'Aromatic mushroom soy sauce', 'Sauce soja champignons', 'Salsa de soja hongos', 'Sojasauce mit Pilzen', 'condiments_sauces', 'snacks', 'pan_japanese', 7, 6, 2),
  R(`شويو بالذرة ${T}`, 'Corn soy sauce', 'Sauce soja mais', 'Salsa de soja maíz', 'Sojasauce mit Mais', 'condiments_sauces', 'snacks', 'pan_japanese', 6, 7, 1),

  // --- beverages (27) ---
  R(`شاي أخضر بالزنجبيل ${T}`, 'Aromatic ginger green tea', 'The vert gingembre', 'Té verde jengibre', 'Grüner Tee mit Ingwer', 'beverages', 'snacks', 'pan_japanese', 1, 1, 0),
  R(`شاي أخضر بالثوم ${T}`, 'Aromatic garlic green tea', 'The vert ail', 'Té verde ajo', 'Grüner Tee mit Knoblauch', 'beverages', 'snacks', 'pan_japanese', 0, 2, 0),
  R(`شاي أخضر بالبصل ${T}`, 'Aromatic onion green tea', 'The vert oignon', 'Té verde cebolla', 'Grüner Tee mit Zwiebel', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بالكزبرة ${T}`, 'Aromatic cilantro green tea', 'The vert coriandre', 'Té verde cilantro', 'Grüner Tee mit Koriander', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالليمون ${T}`, 'Aromatic lemon green tea', 'The vert citron', 'Té verde limón', 'Grüner Tee mit Zitrone', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بالفلفل ${T}`, 'Aromatic pepper green tea', 'The vert poivre', 'Té verde pimienta', 'Grüner Tee mit Pfeffer', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالكاري ${T}`, 'Curry green tea', 'The vert curry', 'Té verde curry', 'Grüner Tee mit Curry', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بالطماطم ${T}`, 'Tomato green tea', 'The vert tomate', 'Té verde tomate', 'Grüner Tee mit Tomate', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالفطر ${T}`, 'Mushroom green tea', 'The vert champignons', 'Té verde hongos', 'Grüner Tee mit Pilzen', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بالذرة ${T}`, 'Corn green tea', 'The vert mais', 'Té verde maíz', 'Grüner Tee mit Mais', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالبطاطس ${T}`, 'Potato green tea', 'The vert pomme de terre', 'Té verde papa', 'Grüner Tee mit Kartoffel', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بالجزر ${T}`, 'Carrot green tea', 'The vert carotte', 'Té verde zanahoria', 'Grüner Tee mit Karotte', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالسبانخ ${T}`, 'Spinach green tea', 'The vert epinards', 'Té verde espinacas', 'Grüner Tee mit Spinat', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بالبروكلي ${T}`, 'Broccoli green tea', 'The vert brocoli', 'Té verde brócoli', 'Grüner Tee mit Brokkoli', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالبازلاء ${T}`, 'Pea green tea', 'The vert petits pois', 'Té verde guisantes', 'Grüner Tee mit Erbsen', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بالخضار المشكلة ${T}`, 'Mixed vegetable green tea', 'The vert legumes varies', 'Té verde verduras mixtas', 'Grüner Tee mit gemischtem Gemüse', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالموز ${T}`, 'Banana green tea', 'The vert banane', 'Té verde plátano', 'Grüner Tee mit Banane', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بجوز الهند ${T}`, 'Coconut green tea', 'The vert noix de coco', 'Té verde coco', 'Grüner Tee mit Kokosnuss', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالموز وجوز الهند ${T}`, 'Banana coconut green tea', 'The vert banane noix de coco', 'Té verde plátano coco', 'Grüner Tee mit Banane und Kokosnuss', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بالزنجبيل والثوم ${T}`, 'Ginger garlic green tea', 'The vert gingembre ail', 'Té verde jengibre ajo', 'Grüner Tee mit Ingwer und Knoblauch', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالبصل والكزبرة ${T}`, 'Onion cilantro green tea', 'The vert oignon coriandre', 'Té verde cebolla cilantro', 'Grüner Tee mit Zwiebel und Koriander', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بالليمون والفلفل ${T}`, 'Lemon pepper green tea', 'The vert citron poivre', 'Té verde limón pimienta', 'Grüner Tee mit Zitrone und Pfeffer', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالكاري والطماطم ${T}`, 'Curry tomato green tea', 'The vert curry tomate', 'Té verde curry tomate', 'Grüner Tee mit Curry und Tomate', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بالفطر والذرة ${T}`, 'Mushroom corn green tea', 'The vert champignons mais', 'Té verde hongos maíz', 'Grüner Tee mit Pilzen und Mais', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالبطاطس والجزر ${T}`, 'Potato carrot green tea', 'The vert pomme de terre carotte', 'Té verde papa zanahoria', 'Grüner Tee mit Kartoffel und Karotte', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
  R(`شاي أخضر بالسبانخ والبروكلي ${T}`, 'Spinach broccoli green tea', 'The vert epinards brocoli', 'Té verde espinacas brócoli', 'Grüner Tee mit Spinat und Brokkoli', 'beverages', 'snacks', 'pan_japanese', 0, 1, 0),
  R(`شاي أخضر بالبازلاء والخضار المشكلة ${T}`, 'Pea mixed vegetable green tea', 'The vert petits pois legumes varies', 'Té verde guisantes verduras mixtas', 'Grüner Tee mit Erbsen und gemischtem Gemüse', 'beverages', 'snacks', 'pan_japanese', 1, 0, 0),
];

