// Japanese expansion part 1 of 6: breakfast_items (25) + rice_dishes (30) = 55 rows.
// All dishes are distinct from the base 200. Halal: no pork, no alcohol.
import { R, T } from './rows.mjs';

export default [
  // --- breakfast_items (25) ---
  R(`أونيجيري بالماكريل بالزنجبيل ${T}`, 'Ginger mackerel onigiri', 'Boule de riz maquereau gingembre', 'Bola de arroz caballa jengibre', 'Makrelen-Onigiri mit Ingwer', 'breakfast_items', 'breakfast', 'pan_japanese', 7, 27, 3),
  R(`أونيجيري بالماكريل بالثوم ${T}`, 'Garlic mackerel onigiri', 'Boule de riz maquereau ail', 'Bola de arroz caballa ajo', 'Makrelen-Onigiri mit Knoblauch', 'breakfast_items', 'breakfast', 'pan_japanese', 6, 28, 2),
  R(`أونيجيري بالماكريل بالبصل ${T}`, 'Onion mackerel onigiri', 'Boule de riz maquereau oignon', 'Bola de arroz caballa cebolla', 'Makrelen-Onigiri mit Zwiebel', 'breakfast_items', 'breakfast', 'pan_japanese', 7, 26, 3),
  R(`أونيجيري بالماكريل بالكزبرة ${T}`, 'Cilantro mackerel onigiri', 'Boule de riz maquereau coriandre', 'Bola de arroz caballa cilantro', 'Makrelen-Onigiri mit Koriander', 'breakfast_items', 'breakfast', 'pan_japanese', 6, 27, 2),
  R(`أونيجيري بالماكريل بالليمون ${T}`, 'Lemon mackerel onigiri', 'Boule de riz maquereau citron', 'Bola de arroz caballa limón', 'Makrelen-Onigiri mit Zitrone', 'breakfast_items', 'breakfast', 'pan_japanese', 7, 25, 3),
  R(`أونيجيري بالماكريل بالفلفل ${T}`, 'Pepper mackerel onigiri', 'Boule de riz maquereau poivre', 'Bola de arroz caballa pimienta', 'Makrelen-Onigiri mit Pfeffer', 'breakfast_items', 'breakfast', 'pan_japanese', 6, 26, 2),
  R(`أونيجيري بالماكريل بالكاري ${T}`, 'Curry mackerel onigiri', 'Boule de riz maquereau curry', 'Bola de arroz caballa curry', 'Makrelen-Onigiri mit Curry', 'breakfast_items', 'breakfast', 'pan_japanese', 7, 27, 3),
  R(`أونيجيري بالماكريل بالطماطم ${T}`, 'Tomato mackerel onigiri', 'Boule de riz maquereau tomate', 'Bola de arroz caballa tomate', 'Makrelen-Onigiri mit Tomate', 'breakfast_items', 'breakfast', 'pan_japanese', 6, 28, 2),
  R(`أونيجيري بالماكريل بالفطر ${T}`, 'Mushroom mackerel onigiri', 'Boule de riz maquereau champignons', 'Bola de arroz caballa hongos', 'Makrelen-Onigiri mit Pilzen', 'breakfast_items', 'breakfast', 'pan_japanese', 7, 26, 3),
  R(`أونيجيري بالماكريل بالذرة ${T}`, 'Corn mackerel onigiri', 'Boule de riz maquereau mais', 'Bola de arroz caballa maíz', 'Makrelen-Onigiri mit Mais', 'breakfast_items', 'breakfast', 'pan_japanese', 6, 27, 2),
  R(`أونيجيري بالماكريل بالبطاطس ${T}`, 'Potato mackerel onigiri', 'Boule de riz maquereau pomme de terre', 'Bola de arroz caballa papa', 'Makrelen-Onigiri mit Kartoffel', 'breakfast_items', 'breakfast', 'pan_japanese', 7, 25, 3),
  R(`أونيجيري بالماكريل بالجزر ${T}`, 'Carrot mackerel onigiri', 'Boule de riz maquereau carotte', 'Bola de arroz caballa zanahoria', 'Makrelen-Onigiri mit Karotte', 'breakfast_items', 'breakfast', 'pan_japanese', 6, 26, 2),
  R(`أونيجيري بالماكريل بالسبانخ ${T}`, 'Spinach mackerel onigiri', 'Boule de riz maquereau epinards', 'Bola de arroz caballa espinacas', 'Makrelen-Onigiri mit Spinat', 'breakfast_items', 'breakfast', 'pan_japanese', 7, 24, 3),
  R(`أونيجيري بالماكريل بالبروكلي ${T}`, 'Broccoli mackerel onigiri', 'Boule de riz maquereau brocoli', 'Bola de arroz caballa brócoli', 'Makrelen-Onigiri mit Brokkoli', 'breakfast_items', 'breakfast', 'pan_japanese', 6, 25, 2),
  R(`أونيجيري بالماكريل بالبازلاء ${T}`, 'Pea mackerel onigiri', 'Boule de riz maquereau petits pois', 'Bola de arroz caballa guisantes', 'Makrelen-Onigiri mit Erbsen', 'breakfast_items', 'breakfast', 'pan_japanese', 7, 26, 3),
  R(`أونيجيري بالماكريل بالخضار المشكلة ${T}`, 'Mixed vegetable mackerel onigiri', 'Boule de riz maquereau legumes varies', 'Bola de arroz caballa verduras mixtas', 'Makrelen-Onigiri mit gemischtem Gemüse', 'breakfast_items', 'breakfast', 'pan_japanese', 6, 27, 2),
  R(`أونيجيري بالتونة بالزنجبيل ${T}`, 'Ginger tuna onigiri', 'Boule de riz thon gingembre', 'Bola de arroz atún jengibre', 'Thunfisch-Onigiri mit Ingwer', 'breakfast_items', 'breakfast', 'pan_japanese', 9, 25, 4),
  R(`أونيجيري بالتونة بالثوم ${T}`, 'Garlic tuna onigiri', 'Boule de riz thon ail', 'Bola de arroz atún ajo', 'Thunfisch-Onigiri mit Knoblauch', 'breakfast_items', 'breakfast', 'pan_japanese', 8, 26, 3),
  R(`أونيجيري بالتونة بالبصل ${T}`, 'Onion tuna onigiri', 'Boule de riz thon oignon', 'Bola de arroz atún cebolla', 'Thunfisch-Onigiri mit Zwiebel', 'breakfast_items', 'breakfast', 'pan_japanese', 9, 24, 4),
  R(`أونيجيري بالتونة بالكزبرة ${T}`, 'Cilantro tuna onigiri', 'Boule de riz thon coriandre', 'Bola de arroz atún cilantro', 'Thunfisch-Onigiri mit Koriander', 'breakfast_items', 'breakfast', 'pan_japanese', 8, 25, 3),
  R(`أونيجيري بالتونة بالليمون ${T}`, 'Lemon tuna onigiri', 'Boule de riz thon citron', 'Bola de arroz atún limón', 'Thunfisch-Onigiri mit Zitrone', 'breakfast_items', 'breakfast', 'pan_japanese', 9, 23, 4),
  R(`أونيجيري بالتونة بالفلفل ${T}`, 'Pepper tuna onigiri', 'Boule de riz thon poivre', 'Bola de arroz atún pimienta', 'Thunfisch-Onigiri mit Pfeffer', 'breakfast_items', 'breakfast', 'pan_japanese', 8, 24, 3),
  R(`أونيجيري بالتونة بالكاري ${T}`, 'Curry tuna onigiri', 'Boule de riz thon curry', 'Bola de arroz atún curry', 'Thunfisch-Onigiri mit Curry', 'breakfast_items', 'breakfast', 'pan_japanese', 9, 25, 4),
  R(`أونيجيري بالتونة بالطماطم ${T}`, 'Tomato tuna onigiri', 'Boule de riz thon tomate', 'Bola de arroz atún tomate', 'Thunfisch-Onigiri mit Tomate', 'breakfast_items', 'breakfast', 'pan_japanese', 8, 26, 3),
  R(`أونيجيري بالتونة بالفطر ${T}`, 'Mushroom tuna onigiri', 'Boule de riz thon champignons', 'Bola de arroz atún hongos', 'Thunfisch-Onigiri mit Pilzen', 'breakfast_items', 'breakfast', 'pan_japanese', 9, 24, 4),

  // --- rice_dishes (30) ---
  R(`تشاكان بالدجاج بالزنجبيل ${T}`, 'Ginger chicken chazuke', 'Chazuke poulet gingembre', 'Chazuke pollo jengibre', 'Huhn-Chazuke mit Ingwer', 'rice_dishes', 'lunch', 'pan_japanese', 9, 24, 4),
  R(`تشاكان بالدجاج بالثوم ${T}`, 'Garlic chicken chazuke', 'Chazuke poulet ail', 'Chazuke pollo ajo', 'Huhn-Chazuke mit Knoblauch', 'rice_dishes', 'lunch', 'pan_japanese', 8, 25, 3),
  R(`تشاكان بالدجاج بالبصل ${T}`, 'Onion chicken chazuke', 'Chazuke poulet oignon', 'Chazuke pollo cebolla', 'Huhn-Chazuke mit Zwiebel', 'rice_dishes', 'lunch', 'pan_japanese', 9, 23, 4),
  R(`تشاكان بالدجاج بالكزبرة ${T}`, 'Cilantro chicken chazuke', 'Chazuke poulet coriandre', 'Chazuke pollo cilantro', 'Huhn-Chazuke mit Koriander', 'rice_dishes', 'lunch', 'pan_japanese', 8, 24, 3),
  R(`تشاكان بالدجاج بالليمون ${T}`, 'Lemon chicken chazuke', 'Chazuke poulet citron', 'Chazuke pollo limón', 'Huhn-Chazuke mit Zitrone', 'rice_dishes', 'lunch', 'pan_japanese', 9, 22, 4),
  R(`تشاكان بالدجاج بالفلفل ${T}`, 'Pepper chicken chazuke', 'Chazuke poulet poivre', 'Chazuke pollo pimienta', 'Huhn-Chazuke mit Pfeffer', 'rice_dishes', 'lunch', 'pan_japanese', 8, 23, 3),
  R(`تشاكان بالدجاج بالكاري ${T}`, 'Curry chicken chazuke', 'Chazuke poulet curry', 'Chazuke pollo curry', 'Huhn-Chazuke mit Curry', 'rice_dishes', 'lunch', 'pan_japanese', 9, 24, 4),
  R(`تشاكان بالدجاج بالطماطم ${T}`, 'Tomato chicken chazuke', 'Chazuke poulet tomate', 'Chazuke pollo tomate', 'Huhn-Chazuke mit Tomate', 'rice_dishes', 'lunch', 'pan_japanese', 8, 25, 3),
  R(`تشاكان بالدجاج بالفطر ${T}`, 'Mushroom chicken chazuke', 'Chazuke poulet champignons', 'Chazuke pollo hongos', 'Huhn-Chazuke mit Pilzen', 'rice_dishes', 'lunch', 'pan_japanese', 9, 23, 4),
  R(`تشاكان بالدجاج بالذرة ${T}`, 'Corn chicken chazuke', 'Chazuke poulet mais', 'Chazuke pollo maíz', 'Huhn-Chazuke mit Mais', 'rice_dishes', 'lunch', 'pan_japanese', 8, 24, 3),
  R(`تشاكان بالدجاج بالبطاطس ${T}`, 'Potato chicken chazuke', 'Chazuke poulet pomme de terre', 'Chazuke pollo papa', 'Huhn-Chazuke mit Kartoffel', 'rice_dishes', 'lunch', 'pan_japanese', 9, 22, 4),
  R(`تشاكان بالدجاج بالجزر ${T}`, 'Carrot chicken chazuke', 'Chazuke poulet carotte', 'Chazuke pollo zanahoria', 'Huhn-Chazuke mit Karotte', 'rice_dishes', 'lunch', 'pan_japanese', 8, 23, 3),
  R(`تشاكان بالدجاج بالسبانخ ${T}`, 'Spinach chicken chazuke', 'Chazuke poulet epinards', 'Chazuke pollo espinacas', 'Huhn-Chazuke mit Spinat', 'rice_dishes', 'lunch', 'pan_japanese', 9, 21, 4),
  R(`تشاكان بالدجاج بالبروكلي ${T}`, 'Broccoli chicken chazuke', 'Chazuke poulet brocoli', 'Chazuke pollo brócoli', 'Huhn-Chazuke mit Brokkoli', 'rice_dishes', 'lunch', 'pan_japanese', 8, 22, 3),
  R(`تشاكان بالدجاج بالبازلاء ${T}`, 'Pea chicken chazuke', 'Chazuke poulet petits pois', 'Chazuke pollo guisantes', 'Huhn-Chazuke mit Erbsen', 'rice_dishes', 'lunch', 'pan_japanese', 9, 23, 4),
  R(`تشاكان باللحم بالزنجبيل ${T}`, 'Ginger beef chazuke', 'Chazuke boeuf gingembre', 'Chazuke ternera jengibre', 'Rind-Chazuke mit Ingwer', 'rice_dishes', 'lunch', 'pan_japanese', 11, 22, 6),
  R(`تشاكان باللحم بالثوم ${T}`, 'Garlic beef chazuke', 'Chazuke boeuf ail', 'Chazuke ternera ajo', 'Rind-Chazuke mit Knoblauch', 'rice_dishes', 'lunch', 'pan_japanese', 10, 23, 5),
  R(`تشاكان باللحم بالبصل ${T}`, 'Onion beef chazuke', 'Chazuke boeuf oignon', 'Chazuke ternera cebolla', 'Rind-Chazuke mit Zwiebel', 'rice_dishes', 'lunch', 'pan_japanese', 11, 21, 6),
  R(`تشاكان باللحم بالكزبرة ${T}`, 'Cilantro beef chazuke', 'Chazuke boeuf coriandre', 'Chazuke ternera cilantro', 'Rind-Chazuke mit Koriander', 'rice_dishes', 'lunch', 'pan_japanese', 10, 22, 5),
  R(`تشاكان باللحم بالليمون ${T}`, 'Lemon beef chazuke', 'Chazuke boeuf citron', 'Chazuke ternera limón', 'Rind-Chazuke mit Zitrone', 'rice_dishes', 'lunch', 'pan_japanese', 11, 20, 6),
  R(`تشاكان باللحم بالفلفل ${T}`, 'Pepper beef chazuke', 'Chazuke boeuf poivre', 'Chazuke ternera pimienta', 'Rind-Chazuke mit Pfeffer', 'rice_dishes', 'lunch', 'pan_japanese', 10, 21, 5),
  R(`تشاكان باللحم بالكاري ${T}`, 'Curry beef chazuke', 'Chazuke boeuf curry', 'Chazuke ternera curry', 'Rind-Chazuke mit Curry', 'rice_dishes', 'lunch', 'pan_japanese', 11, 22, 6),
  R(`تشاكان باللحم بالطماطم ${T}`, 'Tomato beef chazuke', 'Chazuke boeuf tomate', 'Chazuke ternera tomate', 'Rind-Chazuke mit Tomate', 'rice_dishes', 'lunch', 'pan_japanese', 10, 23, 5),
  R(`تشاكان باللحم بالفطر ${T}`, 'Mushroom beef chazuke', 'Chazuke boeuf champignons', 'Chazuke ternera hongos', 'Rind-Chazuke mit Pilzen', 'rice_dishes', 'lunch', 'pan_japanese', 11, 21, 6),
  R(`تشاكان باللحم بالذرة ${T}`, 'Corn beef chazuke', 'Chazuke boeuf mais', 'Chazuke ternera maíz', 'Rind-Chazuke mit Mais', 'rice_dishes', 'lunch', 'pan_japanese', 10, 22, 5),
  R(`تشاكان باللحم بالبطاطس ${T}`, 'Potato beef chazuke', 'Chazuke boeuf pomme de terre', 'Chazuke ternera papa', 'Rind-Chazuke mit Kartoffel', 'rice_dishes', 'lunch', 'pan_japanese', 11, 20, 6),
  R(`تشاكان باللحم بالجزر ${T}`, 'Carrot beef chazuke', 'Chazuke boeuf carotte', 'Chazuke ternera zanahoria', 'Rind-Chazuke mit Karotte', 'rice_dishes', 'lunch', 'pan_japanese', 10, 21, 5),
  R(`تشاكان باللحم بالسبانخ ${T}`, 'Spinach beef chazuke', 'Chazuke boeuf epinards', 'Chazuke ternera espinacas', 'Rind-Chazuke mit Spinat', 'rice_dishes', 'lunch', 'pan_japanese', 11, 19, 6),
  R(`تشاكان باللحم بالبروكلي ${T}`, 'Broccoli beef chazuke', 'Chazuke boeuf brocoli', 'Chazuke ternera brócoli', 'Rind-Chazuke mit Brokkoli', 'rice_dishes', 'lunch', 'pan_japanese', 10, 20, 5),
  R(`تشاكان باللحم بالبازلاء ${T}`, 'Pea beef chazuke', 'Chazuke boeuf petits pois', 'Chazuke ternera guisantes', 'Rind-Chazuke mit Erbsen', 'rice_dishes', 'lunch', 'pan_japanese', 11, 21, 6),
];

