import { B, diasporaFor } from '../australasia-base-data/rows.mjs';

const R = 'pan_australasian';
const NSW = 'nsw';
const V = 'victoria';
const Q = 'queensland';
const WA = 'western_australia';
const SA = 'south_australia';
const T = 'tasmania';
const NT = 'northern_territory';
const AK = 'auckland';
const W = 'wellington';
const C = 'canterbury';
const O = 'otago';
const M = 'maori';

export default [
  B('طبق أسترالي من عصيدة الكمثرى وبذور الوتل', 'Wattleseed Pear Porridge', 'Porridge de poire aux graines de wattleseed', 'Gachas de pera con semillas de wattleseed', 'Birnenbrei mit Wattlesamen', 'breakfast_items', 'breakfast', 6, 24, 5, 'boiling', NSW, diasporaFor(NSW)),
  B('طبق أسترالي من بطاطس التروتة وبيض مسلوق', 'Smoked Trout and Potato Breakfast Hash', 'Poêlée matinale de truite fumée et pommes de terre', 'Salteado matinal de trucha ahumada y patata', 'Frühstückspfanne mit geräucherter Forelle und Kartoffeln', 'breakfast_items', 'breakfast', 13, 17, 9, 'frying', V, diasporaFor(V)),
  B('طبق أسترالي من كعكات الموز ومكسرات المكاديميا', 'Macadamia Banana Griddle Cakes', 'Galettes de banane aux noix de macadamia', 'Tortitas de plátano con nueces de macadamia', 'Bananenpfannkuchen mit Macadamianüssen', 'breakfast_items', 'breakfast', 7, 38, 14, 'grilling', Q, diasporaFor(Q)),
  B('طبق أسترالي من الدخن والكواندونغ للإفطار', 'Quandong Millet Breakfast Bowl', 'Bol matinal de millet au quandong', 'Cuenco de mijo y quandong para el desayuno', 'Hirsefrühstück mit Quandong', 'breakfast_items', 'breakfast', 5, 29, 4, 'boiling', SA, diasporaFor(SA)),
  B('طبق أسترالي من الشوفان والتفاح والبندق المخبوز', 'Tasmanian Apple Hazelnut Oat Bake', 'Gratin matinal aux flocons d’avoine, pomme et noisette', 'Avena horneada con manzana y avellana', 'Gebackener Hafer mit Apfel und Haselnuss', 'breakfast_items', 'breakfast', 6, 31, 10, 'baking', T, diasporaFor(T)),
  B('طبق أسترالي من البيض المخفوق وصلصة الطماطم الصحراوية', 'Bush Tomato Breakfast Scramble', 'Œufs brouillés matinaux à la tomate du désert', 'Huevos revueltos de desayuno con tomate del desierto', 'Rührei zum Frühstück mit Buschtomate', 'breakfast_items', 'breakfast', 12, 8, 11, 'frying', NT, diasporaFor(NT)),
  B('طبق نيوزيلندي من فريتاتا الكومارا وبلح البحر الأخضر', 'Kumara and Green-Lipped Mussel Frittata', 'Frittata de kumara aux moules vertes', 'Frittata de kumara y mejillones de labio verde', 'Kumara-Frittata mit Grünlippmuscheln', 'breakfast_items', 'breakfast', 12, 16, 10, 'baking', AK, diasporaFor(AK)),
  B('طبق نيوزيلندي من الحنطة السوداء والفيجوا واللبن', 'Feijoa Yogurt Buckwheat Bowl', 'Bol de sarrasin au yaourt et à la feijoa', 'Cuenco de trigo sarraceno con yogur y feijoa', 'Buchweizenschale mit Joghurt und Feijoa', 'breakfast_items', 'breakfast', 8, 28, 6, 'mixing', W, diasporaFor(W)),
  B('طبق نيوزيلندي من كعكات الكومارا وسمك الكاهواي المدخن', 'Smoked Kahawai Kumara Breakfast Cakes', 'Galettes matinales de kumara au kahawai fumé', 'Tortitas matinales de kumara con kahawai ahumado', 'Kumara-Frühstücksküchlein mit geräuchertem Kahawai', 'breakfast_items', 'breakfast', 15, 21, 8, 'frying', C, diasporaFor(C)),
  B('طبق نيوزيلندي من الشوفان والمشمش وعسل المانوكا', 'Apricot Manuka Honey Oat Bake', 'Flocons d’avoine cuits à l’abricot et au miel de manuka', 'Avena horneada con albaricoque y miel de manuka', 'Gebackener Hafer mit Aprikose und Manukahonig', 'breakfast_items', 'breakfast', 5, 35, 7, 'baking', O, diasporaFor(O)),
  B('طبق نيوزيلندي من خبز ريوينا والبيض والبوهة', 'Rewena Bread with Puha and Eggs', 'Pain rewena aux œufs et au puha', 'Pan rewena con huevos y puha', 'Rewena-Brot mit Puha und Eiern', 'breakfast_items', 'breakfast', 11, 33, 9, 'toasting', M, diasporaFor(M)),
  B('طبق أسترالي من الأرز البني والدجاج والليمون العطري', 'Lemon Myrtle Chicken Brown Rice', 'Riz complet au poulet et myrte citronnée', 'Arroz integral con pollo y mirto limón', 'Vollkornreis mit Zitronenmyrtenhuhn', 'rice_dishes', 'dinner', 16, 28, 7, 'steaming', NSW, diasporaFor(NSW)),
  B('طبق أسترالي من أرز جوز الهند وسمك الباراموندي', 'Coconut Barramundi Rice', 'Riz à la noix de coco et au barramundi', 'Arroz con coco y barramundi', 'Kokosreis mit Barramundi', 'rice_dishes', 'dinner', 17, 26, 10, 'simmering', Q, diasporaFor(Q)),
  B('طبق أسترالي من بيلاف المارون والمكاديميا', 'Marron Macadamia Pilaf', 'Pilaf de marron aux noix de macadamia', 'Pilaf de marrón con nueces de macadamia', 'Marron-Pilaw mit Macadamianüssen', 'rice_dishes', 'dinner', 16, 29, 9, 'simmering', WA, diasporaFor(WA)),
  B('طبق نيوزيلندي من أرز الهانغي بلحم الضأن والكومارا', 'Hangi Lamb Kumara Rice', 'Riz hangi à l’agneau et au kumara', 'Arroz hangi con cordero y kumara', 'Hangi-Reis mit Lamm und Kumara', 'rice_dishes', 'dinner', 17, 25, 11, 'baking', M, diasporaFor(M)),
  B('طبق نيوزيلندي من بيلاف الأرز والكومارا وبلح البحر', 'Green-Lipped Mussel Kumara Rice Pilaf', 'Pilaf de riz au kumara et aux moules vertes', 'Pilaf de arroz con kumara y mejillones de labio verde', 'Reispilaw mit Kumara und Grünlippmuscheln', 'rice_dishes', 'dinner', 15, 31, 8, 'simmering', AK, diasporaFor(AK)),
  B('طبق أسترالي من نودلز الأرز والروبيان والملح بوش', 'Saltbush Prawn Rice Noodles', 'Nouilles de riz aux crevettes et salicorne australienne', 'Fideos de arroz con langostinos y salicornia australiana', 'Reisnudeln mit Garnelen und australischem Queller', 'noodle_dishes', 'dinner', 15, 32, 8, 'stir_frying', V, diasporaFor(V)),
  B('طبق أسترالي من نودلز الأرز والبقر وفلفل الأدغال', 'Native Pepper Beef Rice Noodle Bowl', 'Bol de nouilles de riz au bœuf et poivre indigène', 'Cuenco de fideos de arroz con res y pimienta nativa', 'Reisnudelschale mit Rind und australischem Pfeffer', 'noodle_dishes', 'lunch', 17, 34, 9, 'stir_frying', SA, diasporaFor(SA)),
  B('طبق نيوزيلندي من نودلز الحنطة السوداء وثعبان البحر المدخن', 'Smoked Eel Buckwheat Noodles', 'Nouilles de sarrasin à l’anguille fumée', 'Fideos de trigo sarraceno con anguila ahumada', 'Buchweizennudeln mit geräuchertem Aal', 'noodle_dishes', 'dinner', 18, 29, 8, 'boiling', W, diasporaFor(W)),
  B('طبق نيوزيلندي من لينغويني جراد البحر والليمون الأسبن', 'Crayfish Lemon Aspen Linguine', 'Linguine aux langoustes et citron aspen', 'Linguini de cigala con limón aspen', 'Linguine mit Languste und Lemon Aspen', 'noodle_dishes', 'dinner', 17, 34, 7, 'boiling', C, diasporaFor(C)),
  B('طبق أسترالي من مرق الشعير وأذن البحر التسماني', 'Tasmanian Abalone Barley Broth', 'Bouillon d’orge à l’ormeau de Tasmanie', 'Caldo de cebada con abalón de Tasmania', 'Gerstenbrühe mit tasmanischer Seeohrmuschel', 'soups_stews', 'lunch', 13, 18, 4, 'simmering', T, diasporaFor(T)),
  B('طبق أسترالي من حساء اليقطين وسرطان البحر الأزرق', 'Blue Swimmer Crab Pumpkin Soup', 'Soupe de potiron au crabe nageur bleu', 'Sopa de calabaza con cangrejo nadador azul', 'Kürbissuppe mit blauer Schwimmkrabbe', 'soups_stews', 'lunch', 10, 16, 6, 'boiling', WA, diasporaFor(WA)),
  B('طبق أسترالي من حساء جوز الهند وسمك الباراموندي', 'Barramundi Coconut Soup', 'Soupe de barramundi au lait de coco', 'Sopa de barramundi con coco', 'Barramundi-Kokossuppe', 'soups_stews', 'dinner', 14, 12, 9, 'simmering', NT, diasporaFor(NT)),
  B('طبق نيوزيلندي من مرق الضأن والكومارا والبوهة', 'Lamb Kumara Puha Broth', 'Bouillon d’agneau au kumara et au puha', 'Caldo de cordero con kumara y puha', 'Lammbrühe mit Kumara und Puha', 'soups_stews', 'dinner', 15, 13, 8, 'stewing', M, diasporaFor(M)),
  B('طبق نيوزيلندي من حساء بلح البحر والذرة', 'Otago Mussel Corn Chowder', 'Soupe épaisse de moules et maïs d’Otago', 'Crema espesa de mejillones y maíz de Otago', 'Otago-Muschelsuppe mit Mais', 'soups_stews', 'lunch', 11, 20, 8, 'boiling', O, diasporaFor(O)),
  B('طبق أسترالي من حساء الذرة وسمك الشعاب', 'Reef Fish Corn Soup', 'Soupe de poisson récifal au maïs', 'Sopa de pescado de arrecife con maíz', 'Riff-Fischsuppe mit Mais', 'soups_stews', 'dinner', 12, 15, 5, 'simmering', Q, diasporaFor(Q)),
  B('طبق أسترالي من دجاج الليمون العطري والخضار الجذرية', 'Lemon Myrtle Roast Chicken with Root Vegetables', 'Poulet rôti à la myrte citronnée et légumes-racines', 'Pollo asado al mirto limón con raíces', 'Zitronenmyrtenhuhn mit Wurzelgemüse', 'poultry_mains', 'dinner', 23, 12, 12, 'roasting', V, diasporaFor(V)),
  B('طبق أسترالي من فطيرة الدجاج وفلفل التسمان', 'Chicken and Pepperberry Hand Pie', 'Tourte portative au poulet et poivre de Tasmanie', 'Empanada de pollo con pimienta de Tasmania', 'Handpastete mit Huhn und Tasmanischem Bergpfeffer', 'poultry_mains', 'lunch', 15, 27, 13, 'baking', NSW, diasporaFor(NSW)),
  B('طبق أسترالي من يخنة الدجاج والتفاح والميرمية', 'Apple Sage Chicken Casserole', 'Mijoté de poulet à la pomme et à la sauge', 'Guiso de pollo con manzana y salvia', 'Hähncheneintopf mit Apfel und Salbei', 'poultry_mains', 'dinner', 20, 11, 10, 'stewing', T, diasporaFor(T)),
  B('طبق أسترالي من الدجاج المغطى بالمكاديميا', 'Macadamia Crusted Chicken', 'Poulet en croûte de macadamia', 'Pollo con costra de macadamia', 'Hähnchen mit Macadamiakruste', 'poultry_mains', 'dinner', 24, 9, 16, 'baking', Q, diasporaFor(Q)),
  B('طبق نيوزيلندي من دجاج الهانغي والكومارا', 'Hangi Chicken with Kumara', 'Poulet hangi accompagné de kumara', 'Pollo hangi con kumara', 'Hangi-Huhn mit Kumara', 'poultry_mains', 'dinner', 21, 17, 9, 'steaming', M, diasporaFor(M)),
  B('طبق نيوزيلندي من فطيرة الدجاج والسلق', 'Chicken Silverbeet Pie', 'Tourte au poulet et à la bette à carde', 'Pastel de pollo y acelga', 'Hähnchenpastete mit Mangold', 'poultry_mains', 'dinner', 16, 25, 14, 'baking', C, diasporaFor(C)),
  B('طبق أسترالي من كتف الضأن وصلصة الطماطم الصحراوية', 'Bush Tomato Lamb Shoulder', 'Épaule d’agneau à la tomate du désert', 'Paletilla de cordero con tomate del desierto', 'Lammschulter mit Buschtomate', 'meat_mains', 'dinner', 22, 6, 17, 'roasting', SA, diasporaFor(SA)),
  B('طبق أسترالي من لحم البقر بطبقة الكواندونغ', 'Quandong Glazed Beef', 'Bœuf laqué au quandong', 'Res glaseada con quandong', 'Rind mit Quandong-Glasur', 'meat_mains', 'dinner', 24, 12, 13, 'roasting', WA, diasporaFor(WA)),
  B('طبق نيوزيلندي من خاصرة الضأن وخضار البوهة', 'Lamb Rump with Puha Greens', 'Rumsteck d’agneau aux feuilles de puha', 'Cadera de cordero con hojas de puha', 'Lammhüfte mit Puha-Blättern', 'meat_mains', 'dinner', 25, 5, 15, 'grilling', O, diasporaFor(O)),
  B('طبق أسترالي من أسياخ البقر والليمون الصحراوي', 'Desert Lime Beef Skewers', 'Brochettes de bœuf au citron du désert', 'Brochetas de res con limón del desierto', 'Rindfleischspieße mit Wüstenlimette', 'meat_mains', 'dinner', 26, 7, 12, 'grilling', NT, diasporaFor(NT)),
  B('طبق أسترالي من سمك النهاش والليمون الإصبعي', 'Finger Lime Grilled Snapper', 'Vivaneau grillé au citron doigt', 'Pargo a la parrilla con lima dedo', 'Gegrillter Schnapper mit Fingerlimette', 'fish_seafood', 'dinner', 22, 2, 7, 'grilling', NSW, diasporaFor(NSW)),
  B('طبق أسترالي من ذيل حشرة خليج موريتون بالمكاديميا', 'Moreton Bay Bug Tail with Macadamia Garlic Butter', 'Queue de cigale de mer de Moreton Bay au beurre d’ail et macadamia', 'Cola de cigarra marina de Moreton Bay con mantequilla de ajo y macadamia', 'Moreton-Bay-Heuschreckenkrebs mit Knoblauch-Macadamia-Butter', 'fish_seafood', 'dinner', 20, 3, 16, 'grilling', Q, diasporaFor(Q)),
  B('طبق أسترالي من المحار الإسكالوب والبقدونس البحري', 'Tasmanian Scallops with Sea Parsley', 'Pétoncles de Tasmanie au persil de mer', 'Vieiras de Tasmania con perejil marino', 'Tasmanische Jakobsmuscheln mit Meerespetersilie', 'fish_seafood', 'dinner', 18, 4, 8, 'searing', T, diasporaFor(T)),
  B('طبق أسترالي من سمك الكينغ فيش وقشرة الملح بوش', 'Saltbush Crusted Kingfish', 'Sériole en croûte de salicorne australienne', 'Jurel con costra de salicornia australiana', 'Bernsteinmakrele mit australischer Quellerkruste', 'fish_seafood', 'dinner', 21, 1, 9, 'baking', SA, diasporaFor(SA)),
  B('طبق نيوزيلندي من بلح البحر الأخضر بمرق جوز الهند', 'Green-Lipped Mussels in Coconut Broth', 'Moules vertes dans un bouillon à la noix de coco', 'Mejillones de labio verde en caldo de coco', 'Grünlippmuscheln in Kokosbrühe', 'fish_seafood', 'dinner', 17, 9, 7, 'steaming', AK, diasporaFor(AK)),
  B('طبق نيوزيلندي من فطائر أذن البحر', 'Paua Fritters', 'Beignets de paua', 'Buñuelos de paua', 'Paua-Küchlein', 'fish_seafood', 'lunch', 15, 19, 8, 'frying', W, diasporaFor(W)),
  B('طبق نيوزيلندي من كعكات السمك الأبيض', 'Canterbury Whitebait Cakes', 'Galettes de petits poissons blancs de Canterbury', 'Tortitas de pescaditos blancos de Canterbury', 'Küchlein aus kleinen Weißfischen aus Canterbury', 'fish_seafood', 'lunch', 16, 14, 9, 'frying', C, diasporaFor(C)),
  B('طبق نيوزيلندي من قنفذ البحر والكومارا المخبوز', 'Kina Kumara Gratin', 'Gratin de kina au kumara', 'Gratén de kina con kumara', 'Kina-Kumara-Gratin', 'fish_seafood', 'dinner', 14, 18, 10, 'baking', M, diasporaFor(M)),
  B('طبق أسترالي من فطيرة خضار الواريغال', 'Warrigal Greens Vegetable Pie', 'Tourte aux feuilles de warrigal', 'Pastel de hojas de warrigal', 'Pastete mit Warrigal-Blättern', 'vegetable_mains', 'dinner', 7, 25, 12, 'baking', V, diasporaFor(V)),
  B('طبق أسترالي من خرشوف القدس والبندق المحمص', 'Roasted Jerusalem Artichokes with Hazelnuts', 'Topinambours rôtis aux noisettes', 'Topinambures asados con avellanas', 'Geröstete Topinambur mit Haselnüssen', 'vegetable_mains', 'dinner', 5, 22, 11, 'roasting', T, diasporaFor(T)),
  B('طبق أسترالي من اليقطين المحمص والملح بوش', 'Roasted Pumpkin with Saltbush', 'Potiron rôti à la salicorne australienne', 'Calabaza asada con salicornia australiana', 'Gerösteter Kürbis mit australischem Queller', 'vegetable_mains', 'dinner', 3, 18, 7, 'roasting', NT, diasporaFor(NT)),
  B('طبق أسترالي من شرائح البطاطس والليمون العطري', 'Lemon Myrtle Potato Scallops', 'Tranches de pomme de terre à la myrte citronnée', 'Rodajas de patata al mirto limón', 'Kartoffelscheiben mit Zitronenmyrte', 'street_snacks', 'snack', 4, 30, 12, 'frying', Q, diasporaFor(Q)),
  B('طبق أسترالي من فطيرة البقر وفلفل التسمان', 'Beef Pepperberry Hand Pie', 'Tourte portative au bœuf et poivre de Tasmanie', 'Empanada de res con pimienta de Tasmania', 'Handpastete mit Rind und Tasmanischem Bergpfeffer', 'street_snacks', 'snack', 13, 27, 14, 'baking', NSW, diasporaFor(NSW)),
  B('طبق أسترالي من تارت اللوز والكواندونغ', 'Quandong Almond Tart', 'Tarte aux amandes et au quandong', 'Tarta de almendra y quandong', 'Mandeltarte mit Quandong', 'rice_cakes_sweets', 'snack', 6, 43, 18, 'baking', SA, diasporaFor(SA)),
];
