import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-138', 'روبيان بصلصة فلفل موريتا والطماطم', 'Shrimp with Morita Chile and Tomato Sauce', 'Crevettes à la sauce tomate et piment morita', 'Camarones en salsa de chile morita y tomate', 'Garnelen in Morita-Chili-Tomatensoße', 'fish_seafood', 'dinner', 19, 7, 7, 'braising', 'veracruz'),
  B('mx-phase-a-139', 'دجاج بصلصة اللوز على طريقة موريلوس', 'Morelos-Style Chicken in Almond Sauce', 'Poulet à la sauce aux amandes façon Morelos', 'Pollo en salsa de almendra estilo Morelos', 'Hähnchen in Mandelsoße nach Morelos-Art', 'poultry_mains', 'dinner', 21, 6, 11, 'braising', 'central_mexico'),
  B('mx-phase-a-140', 'هواخمولي لحم البقر بفلفل غواخيو', 'Beef Huaxmole with Guajillo Chile', 'Huaxmole de bœuf au piment guajillo', 'Huaxmole de res con chile guajillo', 'Rindfleisch-Huaxmole mit Guajillo-Chili', 'meat_mains', 'dinner', 19, 8, 9, 'stewing', 'oaxaca'),
  B('mx-phase-a-141', 'شرائح بوبلانو بالذرة وجبن أواكساكا', 'Poblano Strips with Corn and Oaxaca Cheese', 'Lanières de poblano au maïs et fromage d’Oaxaca', 'Rajas de poblano con maíz y queso Oaxaca', 'Poblano-Streifen mit Mais und Oaxaca-Käse', 'vegetable_mains', 'lunch', 13, 12, 9, 'sauteing', 'puebla'),
  B('mx-phase-a-142', 'سمك شاراليس بصلصة غواخيو والليمون', 'Charales with Guajillo and Lime', 'Charales au guajillo et citron vert', 'Charales con guajillo y lima', 'Charales mit Guajillo-Chili und Limette', 'fish_seafood', 'lunch', 20, 5, 7, 'pan_frying', 'jalisco'),
  B('mx-phase-a-143', 'مولوتيس البطاطس بجبن القريش والإبيزوتي', 'Potato Molotes with Cottage Cheese and Epazote', 'Molotes de pommes de terre au fromage frais et épazote', 'Molotes de papa con requesón y epazote', 'Kartoffel-Molotes mit Hüttenkäse und Epazote', 'street_snacks', 'snack', 12, 23, 8, 'pan_frying', 'oaxaca'),
  B('mx-phase-a-144', 'كوكتيل كامبيتشي بالسلطعون والأخطبوط', 'Campeche Seafood Cocktail with Crab and Octopus', 'Cocktail de Campeche au crabe et poulpe', 'Cóctel campechano de jaiba y pulpo', 'Campeche-Meeresfrüchtecocktail mit Krabbe und Oktopus', 'fish_seafood', 'lunch', 18, 8, 4, 'assembling', 'veracruz'),
  B('mx-phase-a-145', 'بامباز محشو بالدجاج والبطاطس والفاصولياء', 'Pambazo Stuffed with Chicken, Potato and Beans', 'Pambazo farci au poulet, pomme de terre et haricots', 'Pambazo relleno de pollo, papa y frijoles', 'Pambazo gefüllt mit Hähnchen, Kartoffel und Bohnen', 'street_snacks', 'lunch', 15, 23, 8, 'griddling', 'central_mexico'),
  B('mx-phase-a-146', 'شوربة تشيبيلين بالدجاج والذرة', 'Chipilin Chicken Soup with Corn', 'Soupe au chipilin, poulet et maïs', 'Sopa de chipilín con pollo y maíz', 'Chipilin-Hähnchensuppe mit Mais', 'soups_stews', 'lunch', 14, 9, 4, 'simmering', 'chiapas'),
  B('mx-phase-a-147', 'فطر ونوبال بصلصة الفلفل باسيا', 'Mushrooms and Nopales in Pasilla Chile Sauce', 'Champignons et nopales à la sauce au piment pasilla', 'Hongos y nopales en salsa de chile pasilla', 'Pilze und Nopales in Pasilla-Chilisoße', 'vegetable_mains', 'lunch', 8, 11, 5, 'stewing', 'central_mexico'),
  B('mx-phase-a-148', 'روبيان بصلصة بذور القرع الخضراء', 'Shrimp in Green Pumpkin Seed Sauce', 'Crevettes à la sauce verte aux graines de courge', 'Camarones en salsa verde de pepita', 'Garnelen in grüner Kürbiskernsoße', 'fish_seafood', 'dinner', 19, 6, 9, 'braising', 'veracruz'),
  B('mx-phase-a-149', 'تامال السلق بجبن بانلا والطماطم', 'Swiss Chard Tamal with Panela and Tomato', 'Tamal aux blettes, panela et tomate', 'Tamal de acelga con panela y tomate', 'Mangold-Tamal mit Panela und Tomate', 'street_snacks', 'lunch', 12, 20, 7, 'steaming', 'chiapas'),
  B('mx-phase-a-150', 'سمك بصلصة زوكونوستلي والطماطم', 'Fish with Xoconostle and Tomato Sauce', 'Poisson à la sauce de xoconostle et tomate', 'Pescado en salsa de xoconostle y tomate', 'Fisch in Xoconostle-Tomatensoße', 'fish_seafood', 'dinner', 20, 7, 6, 'braising', 'central_mexico'),
];
