import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-264', 'أرز أسود يوكاتاني بالحبار والفاصولياء', 'Yucatecan Black Rice with Squid and Beans', 'Riz noir yucatèque au calamar et haricots', 'Arroz negro yucateco con calamar y frijoles', 'Yucatekischer schwarzer Reis mit Tintenfisch und Bohnen', 'fish_seafood', 'dinner', 17, 21, 6, 'simmering', 'yucatan'),
  B('mx-phase-a-265', 'بوكول هواستيكي بالفاصولياء السوداء والجبن الطازج', 'Huasteca Bocol with Black Beans and Fresh Cheese', 'Bocol huastèque aux haricots noirs et fromage frais', 'Bocol huasteco con frijoles negros y queso fresco', 'Huasteca-Bocol mit schwarzen Bohnen und Frischkäse', 'street_snacks', 'lunch', 12, 22, 7, 'griddling', 'veracruz'),
  B('mx-phase-a-266', 'كالديو لحم البقر بفلفل غواخيو والقرع', 'Beef Caldillo with Guajillo Chile and Squash', 'Caldillo de bœuf au guajillo et courge', 'Caldillo de res con chile guajillo y calabaza', 'Rinder-Caldillo mit Guajillo-Chili und Kürbis', 'meat_mains', 'lunch', 17, 9, 7, 'simmering', 'northern_mexico'),
  B('mx-phase-a-267', 'فلاوتا لحم البقر بالكريمة والأفوكادو', 'Beef Flautas with Crema and Avocado', 'Flautas de bœuf à la crème et avocat', 'Flautas de res con crema y aguacate', 'Rindfleisch-Flautas mit Crema und Avocado', 'street_snacks', 'dinner', 19, 18, 9, 'pan_frying', 'central_mexico'),
  B('mx-phase-a-268', 'سمك بتشيرمول بذور القرع والطماطم', 'Fish in Pumpkin Seed and Tomato Chirmol', 'Poisson au chirmol de graines de courge et tomate', 'Pescado en chirmol de pepita y tomate', 'Fisch in Kürbiskern-Tomaten-Chirmol', 'fish_seafood', 'dinner', 20, 7, 8, 'braising', 'veracruz'),
  B('mx-phase-a-269', 'ديك رومي بصلصة أنشو والذرة المحمصة', 'Turkey with Ancho Sauce and Charred Corn', 'Dinde à la sauce ancho et maïs grillé', 'Pavo con salsa de ancho y maíz tatemado', 'Pute mit Ancho-Soße und geröstetem Mais', 'poultry_mains', 'dinner', 21, 8, 7, 'braising', 'central_mexico'),
  B('mx-phase-a-270', 'ديك رومي مخبوز بصلصة غواخيو والبرتقال', 'Baked Turkey with Guajillo and Orange Sauce', 'Dinde au four à la sauce guajillo et orange', 'Pavo al horno con salsa de guajillo y naranja', 'Ofenpute mit Guajillo-Orangen-Soße', 'poultry_mains', 'dinner', 22, 7, 7, 'roasting', 'yucatan'),
  B('mx-phase-a-271', 'سمك بصلصة جامايكا والفلفل الحار', 'Fish with Hibiscus and Chile Sauce', 'Poisson à la sauce jamaica et piment', 'Pescado en salsa de jamaica y chile', 'Fisch mit Hibiskus-Chilisoße', 'fish_seafood', 'dinner', 19, 8, 6, 'braising', 'central_mexico'),
  B('mx-phase-a-272', 'سوبا فيديو جاف بالفاصولياء وجبن بانلا', 'Sopa Seca Fideo with Beans and Panela', 'Sopa seca de fideo aux haricots et panela', 'Sopa seca de fideo con frijoles y panela', 'Trockene Fideo-Suppe mit Bohnen und Panela', 'vegetable_mains', 'lunch', 12, 23, 7, 'baking', 'central_mexico'),
  B('mx-phase-a-273', 'كساديّا تشايا وجبن أواكساكا', 'Chaya and Oaxaca Cheese Quesadilla', 'Quesadilla à la chaya et fromage d’Oaxaca', 'Quesadilla de chaya y queso Oaxaca', 'Chaya-Oaxaca-Käse-Quesadilla', 'street_snacks', 'snack', 13, 20, 8, 'griddling', 'yucatan'),
  B('mx-phase-a-274', 'فطر إسكابيشي بالنوبال وجبن بانلا', 'Mushroom Escabeche with Nopales and Panela', 'Escabèche de champignons aux nopales et panela', 'Escabeche de hongos con nopales y panela', 'Pilz-Escabeche mit Nopales und Panela', 'vegetable_mains', 'lunch', 10, 9, 6, 'braising', 'central_mexico'),
  B('mx-phase-a-275', 'شوربة حمص وفاصولياء عريضة بصلصة الطماطم', 'Chickpea and Fava Bean Soup with Tomato', 'Soupe de pois chiches et fèves à la tomate', 'Sopa de garbanzos y habas con tomate', 'Kichererbsen-Ackerbohnensuppe mit Tomate', 'soups_stews', 'lunch', 10, 15, 4, 'simmering', 'central_mexico'),
];
