import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-214', 'خبز بان دي كاسون بالسمك والفاصولياء السوداء', 'Campeche Pan de Cazon with Fish and Black Beans', 'Pan de cazón de Campeche au poisson et haricots noirs', 'Pan de cazón campechano con pescado y frijoles negros', 'Campeche-Pan-de-Cazon mit Fisch und schwarzen Bohnen', 'fish_seafood', 'lunch', 17, 20, 6, 'baking', 'veracruz'),
  B('mx-phase-a-215', 'طاجن مأكولات بحرية بالأشيوت والطماطم', 'Seafood Cazuela with Achiote and Tomato', 'Cazuela de fruits de mer à l’achiote et tomate', 'Cazuela de mariscos con achiote y tomate', 'Meeresfrüchte-Cazuela mit Achiote und Tomate', 'fish_seafood', 'dinner', 17, 8, 6, 'simmering', 'veracruz'),
  B('mx-phase-a-216', 'دجاج ألكابارادو بالزيتون والكبر', 'Chicken Alcaparrado with Olives and Capers', 'Poulet alcaparrado aux olives et câpres', 'Pollo alcaparrado con aceitunas y alcaparras', 'Alcaparrado-Hähnchen mit Oliven und Kapern', 'poultry_mains', 'dinner', 21, 5, 9, 'braising', 'yucatan'),
  B('mx-phase-a-217', 'كيبي يوكاتاني بلحم البقر والبرغل', 'Yucatecan Kibis with Beef and Bulgur', 'Kibis yucatèques au bœuf et boulgour', 'Kibis yucatecos de res y trigo bulgur', 'Yucatekische Kibis mit Rindfleisch und Bulgur', 'street_snacks', 'snack', 17, 18, 8, 'baking', 'yucatan'),
  B('mx-phase-a-218', 'إنشيلادا هواستيكا بالسيسينا والفاصولياء', 'Huasteca Enchiladas with Cecina and Beans', 'Enchiladas huastèques à la cecina et aux haricots', 'Enchiladas huastecas con cecina y frijoles', 'Huasteca-Enchiladas mit Cecina und Bohnen', 'meat_mains', 'dinner', 19, 19, 8, 'griddling', 'veracruz'),
  B('mx-phase-a-219', 'كورونداس ميتشواكانية بجبن بانلا', 'Michoacan Corundas with Panela Cheese', 'Corundas du Michoacán au fromage panela', 'Corundas michoacanas con queso panela', 'Michoacán-Corundas mit Panela-Käse', 'street_snacks', 'lunch', 11, 24, 7, 'steaming', 'jalisco'),
  B('mx-phase-a-220', 'سمك بكريمة الكزبرة والنوبال', 'Fish with Cilantro Cream and Nopales', 'Poisson à la crème de coriandre et nopales', 'Pescado con crema de cilantro y nopales', 'Fisch mit Koriandercreme und Nopales', 'fish_seafood', 'dinner', 20, 6, 8, 'braising', 'central_mexico'),
  B('mx-phase-a-221', 'سلطة تونة بزوكونوستلي والبصل الأحمر', 'Tuna Salad with Xoconostle and Red Onion', 'Salade de thon au xoconostle et oignon rouge', 'Ensalada de atún con xoconostle y cebolla morada', 'Thunfischsalat mit Xoconostle und roter Zwiebel', 'fish_seafood', 'lunch', 19, 7, 6, 'assembling', 'central_mexico'),
  B('mx-phase-a-222', 'شوربة مرق الدجاج بكرات ماسا وفاصولياء', 'Chicken Broth with Masa Dumplings and Beans', 'Bouillon de poulet aux boulettes de masa et haricots', 'Caldo de pollo con chochoyotes de masa y frijoles', 'Hühnerbrühe mit Masa-Klößchen und Bohnen', 'soups_stews', 'lunch', 14, 12, 5, 'simmering', 'central_mexico'),
  B('mx-phase-a-223', 'بطاطس مكسيكية بالبيض وفلفل أنشو', 'Mexican Potatoes with Egg and Ancho Chile', 'Pommes de terre mexicaines aux œufs et ancho', 'Papas a la mexicana con huevo y chile ancho', 'Mexikanische Kartoffeln mit Ei und Ancho-Chili', 'breakfast_items', 'breakfast', 12, 16, 8, 'sauteing', 'central_mexico'),
  B('mx-phase-a-224', 'روبيان بوبلانو بالذرة وجبن أواكساكا', 'Poblano Shrimp with Corn and Oaxaca Cheese', 'Crevettes poblano au maïs et fromage d’Oaxaca', 'Camarones poblanos con maíz y queso Oaxaca', 'Poblano-Garnelen mit Mais und Oaxaca-Käse', 'fish_seafood', 'dinner', 19, 8, 7, 'sauteing', 'veracruz'),
  B('mx-phase-a-225', 'تونة مشوية بفلفل كساتيك والليمون', 'Grilled Tuna with Xcatik Chile and Lime', 'Thon grillé au piment xcatik et citron vert', 'Atún a la parrilla con chile xcatik y lima', 'Gegrillter Thunfisch mit Xcatik-Chili und Limette', 'fish_seafood', 'dinner', 22, 3, 7, 'grilling', 'yucatan'),
];
