import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-238', 'تامال سمك فيراكروز بأوراق أكويو', 'Veracruz Fish Tamal with Acuyo Leaves', 'Tamal de Veracruz au poisson et feuilles d’acuyo', 'Tamal veracruzano de pescado con hoja de acuyo', 'Veracruz-Fischtamal mit Acuyo-Blättern', 'fish_seafood', 'lunch', 17, 23, 6, 'steaming', 'veracruz'),
  B('mx-phase-a-239', 'تاكو سلة بالفول العريض وجبن أواكساكا', 'Basket Tacos with Fava Beans and Oaxaca Cheese', 'Tacos de canasta aux fèves et fromage d’Oaxaca', 'Tacos de canasta con habas y queso Oaxaca', 'Canasta-Tacos mit Ackerbohnen und Oaxaca-Käse', 'street_snacks', 'snack', 13, 21, 8, 'steaming', 'central_mexico'),
  B('mx-phase-a-240', 'ألبامبري ديك رومي بالفلفل وجبن أواكساكا', 'Turkey Alambre with Peppers and Oaxaca Cheese', 'Alambre de dinde aux poivrons et fromage d’Oaxaca', 'Alambre de pavo con pimientos y queso Oaxaca', 'Puten-Alambre mit Paprika und Oaxaca-Käse', 'poultry_mains', 'dinner', 20, 6, 9, 'sauteing', 'central_mexico'),
  B('mx-phase-a-241', 'فلفل بوبلانو محشو بالتونة والذرة', 'Poblano Chile Stuffed with Tuna and Corn', 'Piment poblano farci au thon et maïs', 'Chile poblano relleno de atún y maíz', 'Poblano-Chili gefüllt mit Thunfisch und Mais', 'fish_seafood', 'lunch', 18, 8, 7, 'roasting', 'puebla'),
  B('mx-phase-a-242', 'روبيان تشيبوتلي بصلصة البرتقال الحامض', 'Chipotle Shrimp with Sour Orange Sauce', 'Crevettes chipotle à la sauce d’orange amère', 'Camarones al chipotle con salsa de naranja agria', 'Chipotle-Garnelen mit Bitterorangensoße', 'fish_seafood', 'dinner', 20, 5, 6, 'sauteing', 'veracruz'),
  B('mx-phase-a-243', 'شوربة أرز بوبلانو بالدجاج والشايوتي', 'Poblano Rice Soup with Chicken and Chayote', 'Soupe de riz poblano au poulet et chayotte', 'Sopa de arroz poblana con pollo y chayote', 'Poblano-Reissuppe mit Hähnchen und Chayote', 'soups_stews', 'lunch', 13, 13, 5, 'simmering', 'puebla'),
  B('mx-phase-a-244', 'تامال هويتلاكوتشي بجبن بانلا', 'Huitlacoche Tamal with Panela Cheese', 'Tamal au huitlacoche et fromage panela', 'Tamal de huitlacoche con queso panela', 'Huitlacoche-Tamal mit Panela-Käse', 'street_snacks', 'lunch', 11, 22, 7, 'steaming', 'central_mexico'),
  B('mx-phase-a-245', 'يخنة البطاطس والنوبال بجبن بانلا', 'Potato and Nopal Stew with Panela Cheese', 'Ragoût de pommes de terre et nopales au panela', 'Guiso de papa y nopal con queso panela', 'Kartoffel-Nopal-Eintopf mit Panela-Käse', 'vegetable_mains', 'lunch', 11, 14, 6, 'stewing', 'central_mexico'),
  B('mx-phase-a-246', 'سمك هواشينانغو بأوراق الهوجا سانتا والكبر', 'Huachinango with Hoja Santa and Capers', 'Huachinango à la hoja santa et aux câpres', 'Huachinango con hoja santa y alcaparras', 'Huachinango mit Hoja Santa und Kapern', 'fish_seafood', 'dinner', 21, 4, 7, 'baking', 'veracruz'),
  B('mx-phase-a-247', 'شوربة كيليتس بكرات الذرة والفاصولياء', 'Quelites Soup with Corn Dumplings and Beans', 'Soupe de quelites aux boulettes de maïs et haricots', 'Sopa de quelites con chochoyotes de maíz y frijoles', 'Quelites-Suppe mit Maisklößchen und Bohnen', 'soups_stews', 'lunch', 10, 15, 4, 'simmering', 'chiapas'),
  B('mx-phase-a-248', 'مارلين مكسيكي بالطماطم والزيتون والفلفل', 'Mexican Marlin with Tomato, Olives and Chile', 'Marlín mexicain à la tomate, olives et piment', 'Marlin a la mexicana con tomate, aceitunas y chile', 'Mexikanischer Marlin mit Tomate, Oliven und Chili', 'fish_seafood', 'dinner', 21, 6, 8, 'sauteing', 'baja_california'),
  B('mx-phase-a-249', 'سوبس جبن القريش بصلصة موريتا', 'Cottage Cheese Sopes with Morita Salsa', 'Sopes au fromage frais et salsa morita', 'Sopes de requesón con salsa morita', 'Sopes mit Hüttenkäse und Morita-Salsa', 'street_snacks', 'snack', 13, 20, 7, 'griddling', 'central_mexico'),
  B('mx-phase-a-250', 'أقراص تشايا بجبن بانلا وبذور القرع', 'Chaya Cakes with Panela and Pumpkin Seeds', 'Galettes de chaya au panela et graines de courge', 'Tortitas de chaya con panela y pepitas', 'Chaya-Küchlein mit Panela und Kürbiskernen', 'vegetable_mains', 'lunch', 12, 10, 7, 'pan_frying', 'yucatan'),
];
