import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-288', 'كساديّا زهرة الإيزوتي بجبن بانلا', 'Izote Flower Quesadilla with Panela Cheese', 'Quesadilla à la fleur d’izote et fromage panela', 'Quesadilla de flor de izote con queso panela', 'Izote-Blüten-Quesadilla mit Panela-Käse', 'street_snacks', 'snack', 12, 21, 8, 'griddling', 'veracruz'),
  B('mx-phase-a-289', 'دجاج بموليه كولوراديتو والبرتقال', 'Chicken Mole Coloradito with Orange', 'Poulet au mole coloradito et orange', 'Pollo con mole coloradito y naranja', 'Hähnchen mit Mole Coloradito und Orange', 'poultry_mains', 'dinner', 20, 9, 9, 'braising', 'oaxaca'),
  B('mx-phase-a-290', 'لحم بقري بفطر هويتلاكوتشي وفلفل باسيا', 'Beef with Huitlacoche and Pasilla Chile', 'Bœuf au huitlacoche et piment pasilla', 'Res con huitlacoche y chile pasilla', 'Rindfleisch mit Huitlacoche und Pasilla-Chili', 'meat_mains', 'dinner', 20, 7, 9, 'stewing', 'central_mexico'),
  B('mx-phase-a-291', 'أقراص سلطعون بصلصة كساتيك والليمون', 'Crab Cakes with Xcatik Chile and Lime', 'Galettes de crabe au piment xcatik et citron vert', 'Tortitas de jaiba con chile xcatik y lima', 'Krabbenküchlein mit Xcatik-Chili und Limette', 'fish_seafood', 'lunch', 17, 10, 6, 'pan_frying', 'veracruz'),
  B('mx-phase-a-292', 'مشروب بينولي بالحليب وبذور القرع', 'Pinole Drink with Milk and Pumpkin Seeds', 'Boisson au pinole, lait et graines de courge', 'Bebida de pinole con leche y pepitas', 'Pinole-Getränk mit Milch und Kürbiskernen', 'beverages', 'breakfast', 9, 22, 6, 'blending', 'northern_mexico'),
  B('mx-phase-a-293', 'شرائح لحم بقري بصلصة جامايكا والفلفل', 'Beef Strips with Hibiscus and Chile Sauce', 'Émincé de bœuf à la sauce jamaica et piment', 'Tiras de res en salsa de jamaica y chile', 'Rindfleischstreifen mit Hibiskus-Chilisoße', 'meat_mains', 'dinner', 21, 7, 8, 'sauteing', 'central_mexico'),
  B('mx-phase-a-294', 'شوربة طماطم مشوية بجبن بانلا والذرة', 'Roasted Tomato Soup with Panela and Corn', 'Soupe de tomates rôties au panela et maïs', 'Sopa de tomate asado con panela y maíz', 'Suppe aus gerösteten Tomaten mit Panela und Mais', 'soups_stews', 'lunch', 10, 12, 5, 'simmering', 'central_mexico'),
  B('mx-phase-a-295', 'أقراص كيليتس بالحمص وفلفل غواخيو', 'Quelites Patties with Chickpeas and Guajillo Chile', 'Galettes de quelites aux pois chiches et guajillo', 'Tortitas de quelites con garbanzos y chile guajillo', 'Quelites-Küchlein mit Kichererbsen und Guajillo-Chili', 'vegetable_mains', 'lunch', 12, 15, 6, 'pan_frying', 'chiapas'),
  B('mx-phase-a-296', 'سمك بالتونة وصلصة تشيبيلين', 'Tuna with Chipilin Sauce', 'Thon à la sauce chipilin', 'Atún en salsa de chipilín', 'Thunfisch mit Chipilin-Soße', 'fish_seafood', 'dinner', 21, 6, 7, 'braising', 'chiapas'),
  B('mx-phase-a-297', 'بطاطس محشوة بالفاصولياء السوداء وجبن بانلا', 'Potatoes Stuffed with Black Beans and Panela Cheese', 'Pommes de terre farcies aux haricots noirs et panela', 'Papas rellenas de frijoles negros y queso panela', 'Kartoffeln gefüllt mit schwarzen Bohnen und Panela', 'vegetable_mains', 'lunch', 12, 20, 7, 'baking', 'central_mexico'),
  B('mx-phase-a-298', 'ديك رومي بصلصة زوكونوستلي والبرتقال', 'Turkey with Xoconostle and Orange Sauce', 'Dinde à la sauce xoconostle et orange', 'Pavo en salsa de xoconostle y naranja', 'Pute mit Xoconostle-Orangen-Soße', 'poultry_mains', 'dinner', 21, 8, 7, 'braising', 'central_mexico'),
  B('mx-phase-a-299', 'سمك بيجيلاغارتو بصلصة الطماطم الخضراء', 'Pejelagarto with Green Tomato Sauce', 'Pejelagarto à la sauce de tomate verte', 'Pejelagarto en salsa de tomate verde', 'Pejelagarto mit grüner Tomatensoße', 'fish_seafood', 'dinner', 20, 6, 7, 'grilling', 'veracruz'),
  B('mx-phase-a-300', 'خيريكايا غوادالاخارا بالقرفة والفانيليا', 'Guadalajara Jericalla with Cinnamon and Vanilla', 'Jericalla de Guadalajara à la cannelle et vanille', 'Jericalla de Guadalajara con canela y vainilla', 'Jericalla aus Guadalajara mit Zimt und Vanille', 'rice_cakes_sweets', 'snack', 8, 22, 7, 'baking', 'jalisco'),
];
