import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-088', 'تاكو دجاج مقرمش مخبوز بصلصة الأفوكادو', 'Baked Crispy Chicken Tacos with Avocado Salsa', 'Tacos de poulet croustillants au four et salsa à l’avocat', 'Tacos crujientes de pollo al horno con salsa de aguacate', 'Knusprige Ofen-Hähnchen-Tacos mit Avocado-Salsa', 'poultry_mains', 'dinner', 19, 16, 7, 'baking', 'central_mexico'),
  B('mx-phase-a-089', 'بيض موتوليني بالفاصولياء والبازلاء والموز', 'Huevos Motuleños with Beans, Peas and Plantain', 'Huevos motuleños aux haricots, pois et banane plantain', 'Huevos motuleños con frijoles, chícharos y plátano', 'Huevos Motuleños mit Bohnen, Erbsen und Kochbanane', 'breakfast_items', 'breakfast', 13, 14, 9, 'pan_frying', 'yucatan'),
  B('mx-phase-a-090', 'ديك رومي تشيلمولي بفلفل الأنشو', 'Turkey Chilmole with Ancho Chile', 'Dinde chilmole au piment ancho', 'Pavo en chilmole con chile ancho', 'Pute in Chilmole mit Ancho-Chili', 'poultry_mains', 'dinner', 21, 7, 8, 'simmering', 'yucatan'),
  B('mx-phase-a-091', 'فلفل حلو محشو بالروبيان والليمون', 'Sweet Chile Stuffed with Shrimp and Lime', 'Piment doux farci aux crevettes et citron vert', 'Chile dulce relleno de camarón y lima', 'Süße Chili gefüllt mit Garnelen und Limette', 'fish_seafood', 'lunch', 16, 6, 6, 'roasting', 'veracruz'),
  B('mx-phase-a-092', 'تامال فلفل باسيا بلحم البقر', 'Beef and Pasilla Chile Tamal', 'Tamal au bœuf et piment pasilla', 'Tamal de res con chile pasilla', 'Rindfleisch-Tamal mit Pasilla-Chili', 'street_snacks', 'lunch', 17, 21, 8, 'steaming', 'oaxaca'),
  B('mx-phase-a-093', 'تاكو عدس بالأفوكادو وصلصة الفلفل', 'Lentil Tacos with Avocado and Chile Salsa', 'Tacos de lentilles à l’avocat et salsa pimentée', 'Tacos de lentejas con aguacate y salsa de chile', 'Linsen-Tacos mit Avocado und Chili-Salsa', 'vegetable_mains', 'lunch', 10, 22, 7, 'sauteing', 'chiapas'),
  B('mx-phase-a-094', 'وعاء تونة ونوبال بالأفوكادو والطماطم', 'Tuna and Nopal Bowl with Avocado and Tomato', 'Bol de thon et nopales à l’avocat et tomate', 'Tazón de atún y nopales con aguacate y tomate', 'Thunfisch-Nopales-Schale mit Avocado und Tomate', 'fish_seafood', 'lunch', 19, 7, 8, 'assembling', 'baja_california'),
  B('mx-phase-a-095', 'إنشيلادا دجاج ببيبيان أخضر', 'Chicken Enchiladas with Green Pipian', 'Enchiladas au poulet et pipian vert', 'Enchiladas de pollo con pipián verde', 'Hähnchen-Enchiladas mit grünem Pipián', 'poultry_mains', 'dinner', 19, 15, 9, 'baking', 'puebla'),
  B('mx-phase-a-096', 'سلطة ذرة وفاصولياء سوداء ببذور القرع', 'Corn and Black Bean Salad with Pumpkin Seeds', 'Salade de maïs et haricots noirs aux graines de courge', 'Ensalada de maíz y frijoles negros con pepitas', 'Mais-Schwarze-Bohnen-Salat mit Kürbiskernen', 'salads', 'lunch', 10, 21, 7, 'assembling', 'chiapas'),
  B('mx-phase-a-097', 'توستادا سمك باخا بالكرنب والليمون', 'Baja Fish Tostada with Cabbage and Lime', 'Tostada de poisson de Basse-Californie au chou et citron vert', 'Tostada de pescado estilo Baja con col y lima', 'Baja-Fisch-Tostada mit Kohl und Limette', 'fish_seafood', 'lunch', 18, 14, 6, 'grilling', 'baja_california'),
  B('mx-phase-a-098', 'ميميلا أواكساكية بالبيض والفاصولياء السوداء', 'Oaxacan Memela with Egg and Black Beans', 'Memela oaxaqueña à l’œuf et aux haricots noirs', 'Memela oaxaqueña con huevo y frijoles negros', 'Oaxacanische Memela mit Ei und schwarzen Bohnen', 'breakfast_items', 'breakfast', 13, 23, 7, 'griddling', 'oaxaca'),
  B('mx-phase-a-099', 'سلطة دجاج بالأفوكادو والحمضيات', 'Chicken Avocado and Citrus Salad', 'Salade de poulet, avocat et agrumes', 'Ensalada de pollo, aguacate y cítricos', 'Hähnchensalat mit Avocado und Zitrusfrüchten', 'salads', 'lunch', 19, 6, 9, 'grilling', 'pan_mexican'),
  B('mx-phase-a-100', 'وعاء أمارانت بالحليب والقرع والفاكهة', 'Amaranth Bowl with Milk, Pumpkin Seeds and Fruit', 'Bol d’amarante au lait, graines de courge et fruits', 'Tazón de amaranto con leche, pepitas y fruta', 'Amaranth-Schale mit Milch, Kürbiskernen und Obst', 'breakfast_items', 'breakfast', 11, 23, 7, 'simmering', 'central_mexico'),
];
