import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-164', 'شوربة روبيان مجفف بالخضار وفلفل غواخيو', 'Dried Shrimp Soup with Vegetables and Guajillo Chile', 'Soupe de crevettes séchées aux légumes et guajillo', 'Sopa de camarón seco con verduras y chile guajillo', 'Suppe mit getrockneten Garnelen, Gemüse und Guajillo-Chili', 'fish_seafood', 'lunch', 15, 9, 4, 'simmering', 'veracruz'),
  B('mx-phase-a-165', 'أقراص تونة مكسيكية بصلصة تشيبوتلي', 'Mexican Tuna Patties with Chipotle Sauce', 'Galettes mexicaines de thon à la sauce chipotle', 'Tortitas mexicanas de atún con salsa de chipotle', 'Mexikanische Thunfischküchlein mit Chipotle-Soße', 'fish_seafood', 'lunch', 19, 9, 7, 'pan_frying', 'central_mexico'),
  B('mx-phase-a-166', 'دجاج بهويتلاكوتشي وصلصة الذرة الطازجة', 'Chicken with Huitlacoche and Fresh Corn Sauce', 'Poulet au huitlacoche et sauce de maïs frais', 'Pollo con huitlacoche y salsa de elote', 'Hähnchen mit Huitlacoche und frischer Maissoße', 'poultry_mains', 'dinner', 20, 8, 9, 'braising', 'central_mexico'),
  B('mx-phase-a-167', 'إنشيلادا بوتوسينا محشوة بالجبن والفاصولياء', 'Potosina Enchiladas Filled with Cheese and Beans', 'Enchiladas potosinas farcies au fromage et haricots', 'Enchiladas potosinas rellenas de queso y frijoles', 'Potosina-Enchiladas gefüllt mit Käse und Bohnen', 'street_snacks', 'lunch', 13, 20, 8, 'griddling', 'central_mexico'),
  B('mx-phase-a-168', 'يخنة ديك رومي بالشايوتي وفلفل غواخيو', 'Turkey Stew with Chayote and Guajillo Chile', 'Ragoût de dinde à la chayotte et au guajillo', 'Guiso de pavo con chayote y chile guajillo', 'Puteneintopf mit Chayote und Guajillo-Chili', 'poultry_mains', 'dinner', 19, 8, 7, 'stewing', 'chiapas'),
  B('mx-phase-a-169', 'نوبال مشوي بجبن أواكساكا وصلصة باسيا', 'Grilled Nopal with Oaxaca Cheese and Pasilla Salsa', 'Nopal grillé au fromage d’Oaxaca et salsa pasilla', 'Nopal asado con queso Oaxaca y salsa de pasilla', 'Gegrillter Nopal mit Oaxaca-Käse und Pasilla-Salsa', 'vegetable_mains', 'lunch', 13, 7, 8, 'grilling', 'central_mexico'),
  B('mx-phase-a-170', 'شوربة نخاع البقر بالخضار والليمون', 'Beef Marrow Soup with Vegetables and Lime', 'Soupe de moelle de bœuf aux légumes et citron vert', 'Sopa de médula de res con verduras y lima', 'Rinder-Mark-Suppe mit Gemüse und Limette', 'soups_stews', 'lunch', 14, 7, 8, 'simmering', 'central_mexico'),
  B('mx-phase-a-171', 'سمك بمرق الكيليتس والليمون', 'Fish in Quelites and Lime Broth', 'Poisson au bouillon de quelites et citron vert', 'Pescado en caldo de quelites y lima', 'Fisch in Quelites-Limetten-Brühe', 'fish_seafood', 'lunch', 19, 7, 5, 'simmering', 'chiapas'),
  B('mx-phase-a-172', 'ديك رومي بصلصة الجوافة وفلفل أنشو', 'Turkey with Guava and Ancho Chile Sauce', 'Dinde à la sauce goyave et piment ancho', 'Pavo en salsa de guayaba y chile ancho', 'Pute mit Guaven-Ancho-Chili-Soße', 'poultry_mains', 'dinner', 21, 10, 7, 'braising', 'central_mexico'),
  B('mx-phase-a-173', 'روبيان بفلفل غواخيو وأوراق الهوجا سانتا', 'Shrimp with Guajillo Chile and Hoja Santa', 'Crevettes au guajillo et hoja santa', 'Camarones con chile guajillo y hoja santa', 'Garnelen mit Guajillo-Chili und Hoja Santa', 'fish_seafood', 'dinner', 19, 5, 6, 'sauteing', 'veracruz'),
  B('mx-phase-a-174', 'سلطة فاصولياء سوداء بالنوبال والبرتقال', 'Black Bean Salad with Nopales and Orange', 'Salade de haricots noirs aux nopales et à l’orange', 'Ensalada de frijoles negros con nopales y naranja', 'Schwarze-Bohnen-Salat mit Nopales und Orange', 'salads', 'lunch', 10, 18, 5, 'assembling', 'chiapas'),
  B('mx-phase-a-175', 'تونة بصلصة التوماتيو الخضراء والذرة', 'Tuna with Green Tomatillo Sauce and Corn', 'Thon à la sauce verte de tomatilles et maïs', 'Atún con salsa verde de tomatillo y maíz', 'Thunfisch mit grüner Tomatillo-Soße und Mais', 'fish_seafood', 'dinner', 20, 8, 6, 'braising', 'veracruz'),
];
