import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-188', 'دجاج بصلصة موريتا وزوكونوستلي', 'Chicken with Morita Chile and Xoconostle Sauce', 'Poulet à la sauce morita et xoconostle', 'Pollo en salsa de morita y xoconostle', 'Hähnchen mit Morita-Chili-Xoconostle-Soße', 'poultry_mains', 'dinner', 21, 8, 8, 'braising', 'central_mexico'),
  B('mx-phase-a-189', 'أقراص تونة مكسيكية بصلصة الطماطم الحارة', 'Tuna Patties in Spicy Mexican Tomato Sauce', 'Galettes de thon à la sauce tomate mexicaine relevée', 'Tortitas de atún en salsa mexicana de tomate picante', 'Thunfischküchlein in würziger mexikanischer Tomatensoße', 'fish_seafood', 'dinner', 18, 8, 7, 'pan_frying', 'veracruz'),
  B('mx-phase-a-190', 'كابيروتادا بجبن بانلا والفول السوداني', 'Capirotada with Panela Cheese and Peanuts', 'Capirotada au fromage panela et cacahuètes', 'Capirotada con queso panela y cacahuates', 'Capirotada mit Panela-Käse und Erdnüssen', 'rice_cakes_sweets', 'snack', 10, 31, 9, 'baking', 'central_mexico'),
  B('mx-phase-a-191', 'سلق مطهو بالفاصولياء بينتو والفلفل', 'Swiss Chard Stewed with Pinto Beans and Chile', 'Blettes mijotées aux haricots pinto et piment', 'Acelgas guisadas con frijoles pintos y chile', 'Mangold mit Pintobohnen und Chili geschmort', 'vegetable_mains', 'lunch', 10, 13, 4, 'stewing', 'chiapas'),
  B('mx-phase-a-192', 'تاكو دورادو بالبطاطس وجبن بانلا', 'Crispy Potato and Panela Tacos', 'Tacos croustillants aux pommes de terre et panela', 'Tacos dorados de papa y panela', 'Knusprige Kartoffel-Panela-Tacos', 'street_snacks', 'snack', 12, 24, 8, 'pan_frying', 'central_mexico'),
  B('mx-phase-a-193', 'لحم بقري بفلفل دي أربول وزوكونوستلي', 'Beef with Chile de Arbol and Xoconostle', 'Bœuf au chile de árbol et xoconostle', 'Res con chile de árbol y xoconostle', 'Rindfleisch mit Chile de Arbol und Xoconostle', 'meat_mains', 'dinner', 20, 7, 9, 'stewing', 'northern_mexico'),
  B('mx-phase-a-194', 'سلطة جيكاما وبرتقال وجبن بانلا', 'Jicama, Orange and Panela Salad', 'Salade de jicama, orange et panela', 'Ensalada de jícama, naranja y panela', 'Jicama-Orangen-Panela-Salat', 'salads', 'lunch', 9, 15, 6, 'assembling', 'central_mexico'),
  B('mx-phase-a-195', 'دجاج بالكيليتس والطماطم المحمصة', 'Chicken with Quelites and Roasted Tomato', 'Poulet aux quelites et tomate rôtie', 'Pollo con quelites y tomate asado', 'Hähnchen mit Quelites und gerösteter Tomate', 'poultry_mains', 'dinner', 20, 6, 7, 'braising', 'chiapas'),
  B('mx-phase-a-196', 'تورتاس روبيان مجفف بالنوبال وفلفل باسيا', 'Dried Shrimp Patties with Nopales and Pasilla Chile', 'Galettes de crevettes séchées aux nopales et pasilla', 'Tortitas de camarón seco con nopales y chile pasilla', 'Küchlein aus getrockneten Garnelen mit Nopales und Pasilla-Chili', 'fish_seafood', 'dinner', 18, 8, 6, 'pan_frying', 'veracruz'),
  B('mx-phase-a-197', 'ديك رومي بصلصة الطماطم الخضراء وأوراق الهوجا سانتا', 'Turkey with Green Tomatillo and Hoja Santa Sauce', 'Dinde à la tomatille verte et hoja santa', 'Pavo con tomatillo verde y hoja santa', 'Pute mit grüner Tomatillo-Hoja-Santa-Soße', 'poultry_mains', 'dinner', 21, 6, 7, 'braising', 'veracruz'),
  B('mx-phase-a-198', 'شوربة فول عريض بالفيردولاغاس والذرة', 'Fava Bean Soup with Purslane and Corn', 'Soupe de fèves au pourpier et maïs', 'Sopa de habas con verdolagas y maíz', 'Ackerbohnensuppe mit Portulak und Mais', 'soups_stews', 'lunch', 10, 16, 4, 'simmering', 'central_mexico'),
  B('mx-phase-a-199', 'أخطبوط إسكابيشي بالبصل الأحمر والبرتقال', 'Octopus Escabeche with Red Onion and Orange', 'Escabèche de poulpe à l’oignon rouge et orange', 'Escabeche de pulpo con cebolla morada y naranja', 'Oktopus-Escabeche mit roter Zwiebel und Orange', 'fish_seafood', 'dinner', 21, 7, 6, 'braising', 'yucatan'),
  B('mx-phase-a-200', 'موز بلانتين محشو بالفاصولياء السوداء وجبن بانلا', 'Plantain Stuffed with Black Beans and Panela', 'Banane plantain farcie aux haricots noirs et panela', 'Plátano macho relleno de frijoles negros y panela', 'Kochbanane gefüllt mit schwarzen Bohnen und Panela', 'vegetable_mains', 'lunch', 11, 24, 7, 'baking', 'chiapas'),
];
