import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-114', 'شوربة تورتيلا بالدجاج والأفوكادو', 'Chicken Tortilla Soup with Avocado', 'Soupe de tortilla au poulet et à l’avocat', 'Sopa de tortilla con pollo y aguacate', 'Tortilla-Suppe mit Hähnchen und Avocado', 'soups_stews', 'lunch', 14, 12, 7, 'simmering', 'central_mexico'),
  B('mx-phase-a-115', 'بابادزول يوكاتاني بالبيض وصلصة بذور القرع', 'Yucatecan Papadzules with Egg and Pumpkin Seed Sauce', 'Papadzules yucatèques à l’œuf et sauce aux graines de courge', 'Papadzules yucatecos con huevo y salsa de pepita', 'Yucatekische Papadzules mit Ei und Kürbiskernsoße', 'vegetable_mains', 'lunch', 13, 19, 10, 'assembling', 'yucatan'),
  B('mx-phase-a-116', 'سالبوت ديك رومي بالبصل الأحمر المخلل', 'Turkey Salbut with Pickled Red Onion', 'Salbut de dinde à l’oignon rouge mariné', 'Salbut de pavo con cebolla morada encurtida', 'Puten-Salbut mit eingelegter roter Zwiebel', 'street_snacks', 'lunch', 16, 18, 7, 'frying', 'yucatan'),
  B('mx-phase-a-117', 'سمك بورق الموز مع الهوجا سانتا', 'Banana-Leaf Fish with Hoja Santa', 'Poisson en feuille de bananier à la hoja santa', 'Pescado en hoja de plátano con hoja santa', 'Fisch im Bananenblatt mit Hoja Santa', 'fish_seafood', 'dinner', 20, 4, 7, 'steaming', 'veracruz'),
  B('mx-phase-a-118', 'تشيلباتشولي السلطعون بالفلفل الحار', 'Crab Chilpachole with Chile', 'Chilpachole de crabe au piment', 'Chilpachole de jaiba con chile', 'Krabben-Chilpachole mit Chili', 'fish_seafood', 'lunch', 16, 8, 4, 'simmering', 'veracruz'),
  B('mx-phase-a-119', 'كيساديّا هويتلاكوتشي بجبن أواكساكا', 'Huitlacoche Quesadilla with Oaxaca Cheese', 'Quesadilla au huitlacoche et fromage d’Oaxaca', 'Quesadilla de huitlacoche con queso Oaxaca', 'Huitlacoche-Quesadilla mit Oaxaca-Käse', 'street_snacks', 'snack', 12, 22, 8, 'griddling', 'central_mexico'),
  B('mx-phase-a-120', 'طماطم محشوة بالتونة والذرة والفلفل', 'Tomato Stuffed with Tuna, Corn and Chile', 'Tomate farcie au thon, maïs et piment', 'Tomate relleno de atún, maíz y chile', 'Tomate gefüllt mit Thunfisch, Mais und Chili', 'fish_seafood', 'lunch', 16, 7, 5, 'baking', 'baja_california'),
  B('mx-phase-a-121', 'غورديتا بجبن القريش وزهر القرع والفاصولياء', 'Gordita with Cottage Cheese, Squash Blossom and Beans', 'Gordita au fromage frais, fleur de courge et haricots', 'Gordita de requesón, flor de calabaza y frijoles', 'Gordita mit Hüttenkäse, Kürbisblüte und Bohnen', 'street_snacks', 'snack', 14, 24, 7, 'griddling', 'puebla'),
  B('mx-phase-a-122', 'شوربة زهر القرع بجبن بانلا', 'Squash Blossom Soup with Panela Cheese', 'Soupe de fleurs de courge au fromage panela', 'Sopa de flor de calabaza con queso panela', 'Kürbisblütensuppe mit Panela-Käse', 'soups_stews', 'lunch', 10, 8, 6, 'simmering', 'chiapas'),
  B('mx-phase-a-123', 'أخطبوط مشوي بالفلفل وصلصة كسنيبيك', 'Grilled Octopus with Chile and Xnipec Salsa', 'Poulpe grillé au piment et salsa xnipec', 'Pulpo a la parrilla con chile y salsa xnipec', 'Gegrillter Oktopus mit Chili und Xnipec-Salsa', 'fish_seafood', 'dinner', 22, 5, 6, 'grilling', 'baja_california'),
  B('mx-phase-a-124', 'ديك رومي إسكابيشي من بلد الوليد', 'Valladolid-Style Turkey Escabeche', 'Escabèche de dinde façon Valladolid', 'Escabeche de pavo estilo Valladolid', 'Putten-Escabeche nach Valladolid-Art', 'poultry_mains', 'dinner', 20, 6, 8, 'braising', 'yucatan'),
  B('mx-phase-a-125', 'سمك بصلصة التمر الهندي وفلفل غواخيو', 'Fish with Tamarind and Guajillo Chile Sauce', 'Poisson à la sauce tamarin et piment guajillo', 'Pescado en salsa de tamarindo y chile guajillo', 'Fisch mit Tamarinden-Guajillo-Soße', 'fish_seafood', 'dinner', 19, 9, 6, 'braising', 'veracruz'),
];
