import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-038', 'فلفل بوبلانو محشو بالدجاج والذرة', 'Poblano Chile Stuffed with Chicken and Corn', 'Piment poblano farci au poulet et maïs', 'Chile poblano relleno de pollo y maíz', 'Poblano-Chili gefüllt mit Hähnchen und Mais', 'poultry_mains', 'dinner', 18, 10, 7, 'roasting', 'puebla'),
  B('mx-phase-a-039', 'فاهيتا لحم البقر بالنوبال والفلفل', 'Beef Fajitas with Nopales and Peppers', 'Fajitas de bœuf aux nopales et poivrons', 'Fajitas de res con nopales y pimientos', 'Rinder-Fajitas mit Nopales und Paprika', 'meat_mains', 'dinner', 21, 7, 9, 'grilling', 'northern_mexico'),
  B('mx-phase-a-040', 'شوربة ليما يوكاتانية بالدجاج والليمون', 'Yucatecan Sopa de Lima with Chicken', 'Sopa de lima yucatèque au poulet', 'Sopa de lima yucateca con pollo', 'Yucatekische Sopa de Lima mit Hähnchen', 'soups_stews', 'lunch', 14, 8, 4, 'simmering', 'yucatan'),
  B('mx-phase-a-041', 'وعاء فاصولياء سوداء بالذرة والأفوكادو', 'Black Bean Bowl with Corn and Avocado', 'Bol de haricots noirs au maïs et avocat', 'Tazón de frijoles negros con maíz y aguacate', 'Schwarze-Bohnen-Schale mit Mais und Avocado', 'vegetable_mains', 'lunch', 10, 23, 8, 'assembling', 'chiapas'),
  B('mx-phase-a-042', 'دجاج مشوي بأدوبو الفلفل الحار', 'Grilled Chicken with Chile Adobo', 'Poulet grillé à l’adobo de piments', 'Pollo asado con adobo de chiles', 'Gegrilltes Hähnchen mit Chili-Adobo', 'poultry_mains', 'dinner', 23, 4, 7, 'grilling', 'northern_mexico'),
  B('mx-phase-a-043', 'توستادا تونة بسيفيتشي الخيار والليمون', 'Tuna Ceviche Tostada with Cucumber and Lime', 'Tostada de ceviche de thon au concombre et citron vert', 'Tostada de ceviche de atún con pepino y lima', 'Thunfisch-Ceviche-Tostada mit Gurke und Limette', 'fish_seafood', 'lunch', 18, 13, 4, 'marinating', 'baja_california'),
  B('mx-phase-a-044', 'سلطة نوبال بالفاصولياء البيضاء والذرة', 'Nopal Salad with White Beans and Corn', 'Salade de nopales aux haricots blancs et maïs', 'Ensalada de nopales con alubias blancas y maíz', 'Nopales-Salat mit weißen Bohnen und Mais', 'salads', 'lunch', 9, 18, 4, 'boiling', 'pan_mexican'),
  B('mx-phase-a-045', 'تاكو سمك بالملفوف وصلصة الليمون', 'Fish Tacos with Cabbage and Lime Salsa', 'Tacos de poisson au chou et salsa au citron vert', 'Tacos de pescado con col y salsa de lima', 'Fisch-Tacos mit Kohl und Limetten-Salsa', 'fish_seafood', 'dinner', 18, 15, 6, 'grilling', 'baja_california'),
  B('mx-phase-a-046', 'دجاج بيبيان ببذور القرع والسمسم', 'Chicken Pipian with Pumpkin and Sesame Seeds', 'Poulet pipian aux graines de courge et sésame', 'Pollo en pipián con pepitas y ajonjolí', 'Hähnchen-Pipián mit Kürbis- und Sesamsamen', 'poultry_mains', 'dinner', 20, 7, 11, 'braising', 'oaxaca'),
  B('mx-phase-a-047', 'كيساديّا بالفاصولياء السوداء وجبن بانلا', 'Black Bean and Panela Cheese Quesadilla', 'Quesadilla aux haricots noirs et fromage panela', 'Quesadilla de frijoles negros y queso panela', 'Quesadilla mit schwarzen Bohnen und Panela-Käse', 'street_snacks', 'snack', 13, 24, 7, 'griddling', 'central_mexico'),
  B('mx-phase-a-048', 'بيض مخفوق بالطماطم والنوبال', 'Scrambled Eggs with Tomato and Nopales', 'Œufs brouillés à la tomate et aux nopales', 'Huevos revueltos con tomate y nopales', 'Rührei mit Tomate und Nopales', 'breakfast_items', 'breakfast', 12, 5, 9, 'sauteing', 'pan_mexican'),
  B('mx-phase-a-049', 'تاكو روبيان بالأفوكادو والكرنب', 'Shrimp Tacos with Avocado and Cabbage', 'Tacos de crevettes à l’avocat et au chou', 'Tacos de camarón con aguacate y col', 'Garnelen-Tacos mit Avocado und Kohl', 'fish_seafood', 'dinner', 17, 14, 7, 'grilling', 'baja_california'),
  B('mx-phase-a-050', 'تامال أخضر بالفاصولياء والجبن الطازج', 'Green Tamal with Beans and Fresh Cheese', 'Tamal vert aux haricots et fromage frais', 'Tamal verde con frijoles y queso fresco', 'Grüner Tamal mit Bohnen und Frischkäse', 'street_snacks', 'lunch', 11, 24, 7, 'steaming', 'oaxaca'),
];
