import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-014', 'أغواتشيلي روبيان بالليمون والخيار', 'Shrimp Aguachile with Lime and Cucumber', 'Aguachile de crevettes au citron vert et concombre', 'Aguachile de camarón con lima y pepino', 'Garnelen-Aguachile mit Limette und Gurke', 'fish_seafood', 'lunch', 18, 4, 2, 'marinating', 'baja_california'),
  B('mx-phase-a-015', 'ديك رومي بيبيل بصلصة الحمضيات', 'Citrus Pavo Pibil', 'Dinde pibil aux agrumes', 'Pavo pibil con cítricos', 'Pavo Pibil mit Zitrusfrüchten', 'poultry_mains', 'dinner', 21, 5, 5, 'slow_roasting', 'yucatan'),
  B('mx-phase-a-016', 'ميميلا أواكساكية بالفاصولياء السوداء والجبن', 'Oaxacan Memela with Black Beans and Cheese', 'Memela oaxaqueña aux haricots noirs et fromage', 'Memela oaxaqueña con frijoles negros y queso', 'Oaxacanische Memela mit schwarzen Bohnen und Käse', 'street_snacks', 'snack', 12, 25, 7, 'griddling', 'oaxaca'),
  B('mx-phase-a-017', 'بوزولي أخضر بالدجاج والذرة', 'Green Chicken Pozole with Hominy', 'Pozole vert au poulet et maïs nixtamalisé', 'Pozole verde de pollo con maíz cacahuazintle', 'Grünes Pozole mit Hähnchen und Mais', 'soups_stews', 'lunch', 15, 10, 4, 'simmering', 'jalisco'),
  B('mx-phase-a-018', 'لحم بقري مشوي مع النوبال والبصل', 'Grilled Beef with Nopales and Onion', 'Bœuf grillé aux nopales et à l’oignon', 'Res asada con nopales y cebolla', 'Gegrilltes Rindfleisch mit Nopales und Zwiebel', 'meat_mains', 'dinner', 22, 4, 8, 'grilling', 'northern_mexico'),
  B('mx-phase-a-019', 'توستادا تونة بالأفوكادو والليمون', 'Tuna Avocado Lime Tostada', 'Tostada au thon, avocat et citron vert', 'Tostada de atún con aguacate y lima', 'Thunfisch-Avocado-Limetten-Tostada', 'fish_seafood', 'lunch', 19, 13, 7, 'assembling', 'baja_california'),
  B('mx-phase-a-020', 'شوربة عدس بالقرع والفلفل الحار', 'Lentil Soup with Squash and Chile', 'Soupe de lentilles à la courge et au piment', 'Sopa de lentejas con calabaza y chile', 'Linsensuppe mit Kürbis und Chili', 'soups_stews', 'lunch', 8, 16, 3, 'simmering', 'chiapas'),
  B('mx-phase-a-021', 'فلفل بوبلانو محشو بجبن بانلا والنوبال', 'Poblano Chile Stuffed with Panela and Nopales', 'Piment poblano farci au panela et nopales', 'Chile poblano relleno de panela y nopales', 'Poblano-Chili gefüllt mit Panela und Nopales', 'vegetable_mains', 'dinner', 12, 8, 7, 'roasting', 'puebla'),
  B('mx-phase-a-022', 'تامال دجاج بالذرة والفاصولياء', 'Chicken Corn and Bean Tamal', 'Tamal au poulet, maïs et haricots', 'Tamal de pollo, maíz y frijoles', 'Hähnchen-Tamal mit Mais und Bohnen', 'street_snacks', 'lunch', 14, 22, 6, 'steaming', 'oaxaca'),
  B('mx-phase-a-023', 'توستادا إفطار بالبيض والفاصولياء والأفوكادو', 'Breakfast Tostada with Egg, Beans and Avocado', 'Tostada du matin à l’œuf, haricots et avocat', 'Tostada de desayuno con huevo, frijoles y aguacate', 'Frühstücks-Tostada mit Ei, Bohnen und Avocado', 'breakfast_items', 'breakfast', 13, 15, 9, 'assembling', 'pan_mexican'),
  B('mx-phase-a-024', 'ألبونديغاس لحم البقر بالكوسا والطماطم', 'Beef Albondigas with Zucchini and Tomato', 'Albondigas de bœuf à la courgette et tomate', 'Albondigas de res con calabacita y tomate', 'Rinder-Albondigas mit Zucchini und Tomate', 'soups_stews', 'dinner', 15, 8, 8, 'simmering', 'central_mexico'),
  B('mx-phase-a-025', 'سلطة دجاج بالأفوكادو والفاصولياء السوداء', 'Chicken Avocado and Black Bean Salad', 'Salade de poulet, avocat et haricots noirs', 'Ensalada de pollo, aguacate y frijoles negros', 'Hähnchensalat mit Avocado und schwarzen Bohnen', 'salads', 'lunch', 18, 9, 8, 'grilling', 'pan_mexican'),
];
