import { B } from '../mexico-base-data/rows.mjs';

export default [
  B('mx-phase-a-064', 'دجاج موليه نيغرو ببذور السمسم', 'Chicken Mole Negro with Sesame Seeds', 'Poulet au mole negro et graines de sésame', 'Pollo con mole negro y ajonjolí', 'Hähnchen mit Mole Negro und Sesam', 'poultry_mains', 'dinner', 20, 9, 10, 'simmering', 'oaxaca'),
  B('mx-phase-a-065', 'تاكو سمك بصلصة المانجو والليمون', 'Fish Tacos with Mango Lime Salsa', 'Tacos de poisson à la salsa mangue et citron vert', 'Tacos de pescado con salsa de mango y lima', 'Fisch-Tacos mit Mango-Limetten-Salsa', 'fish_seafood', 'dinner', 18, 16, 6, 'grilling', 'baja_california'),
  B('mx-phase-a-066', 'عجة هويتلاكوتشي بالذرة وجبن بانلا', 'Huitlacoche Corn and Panela Omelet', 'Omelette au maïs, huitlacoche et panela', 'Omelet de huitlacoche, maíz y panela', 'Huitlacoche-Mais-Omelett mit Panela', 'breakfast_items', 'breakfast', 14, 8, 10, 'pan_frying', 'central_mexico'),
  B('mx-phase-a-067', 'شوربة لحم البقر بفلفل الأنشو', 'Beef Soup with Ancho Chile', 'Soupe de bœuf au piment ancho', 'Sopa de res con chile ancho', 'Rindersuppe mit Ancho-Chili', 'soups_stews', 'lunch', 15, 7, 6, 'simmering', 'puebla'),
  B('mx-phase-a-068', 'توستادا ديك رومي تينغا بالأفوكادو', 'Turkey Tinga Tostada with Avocado', 'Tostada de dinde tinga à l’avocat', 'Tostada de tinga de pavo con aguacate', 'Puten-Tinga-Tostada mit Avocado', 'poultry_mains', 'lunch', 18, 14, 7, 'braising', 'central_mexico'),
  B('mx-phase-a-069', 'وعاء سيفيتشي روبيان بالأفوكادو والطماطم', 'Shrimp Ceviche Bowl with Avocado and Tomato', 'Bol de ceviche de crevettes à l’avocat et tomate', 'Tazón de ceviche de camarón con aguacate y tomate', 'Garnelen-Ceviche-Schale mit Avocado und Tomate', 'fish_seafood', 'lunch', 17, 8, 8, 'marinating', 'baja_california'),
  B('mx-phase-a-070', 'تلاكيو نوبال بالفاصولياء السوداء', 'Nopal Tlacoyo with Black Beans', 'Tlacoyo de nopal aux haricots noirs', 'Tlacoyo de nopal con frijoles negros', 'Nopal-Tlacoyo mit schwarzen Bohnen', 'street_snacks', 'snack', 10, 23, 5, 'griddling', 'central_mexico'),
  B('mx-phase-a-071', 'شوربة فيديو بالدجاج والطماطم', 'Chicken Fideo Soup with Tomato', 'Soupe de fideo au poulet et à la tomate', 'Sopa de fideo con pollo y tomate', 'Fideo-Suppe mit Hähnchen und Tomate', 'soups_stews', 'lunch', 12, 13, 4, 'simmering', 'central_mexico'),
  B('mx-phase-a-072', 'إنشيلادا دجاج بفلفل تشيبوتلي', 'Chicken Enchiladas with Chipotle Chile', 'Enchiladas au poulet et piment chipotle', 'Enchiladas de pollo con chile chipotle', 'Hähnchen-Enchiladas mit Chipotle-Chili', 'poultry_mains', 'dinner', 18, 17, 8, 'baking', 'puebla'),
  B('mx-phase-a-073', 'جبن بانلا بالفاصولياء وصلصة الطماطم', 'Panela Cheese with Beans and Tomato Salsa', 'Fromage panela aux haricots et salsa tomate', 'Queso panela con frijoles y salsa de tomate', 'Panela-Käse mit Bohnen und Tomatensalsa', 'vegetable_mains', 'lunch', 14, 12, 8, 'grilling', 'jalisco'),
  B('mx-phase-a-074', 'دجاج بيبيان القرع مع الذرة', 'Squash-Seed Pipian Chicken with Corn', 'Poulet pipian aux graines de courge et maïs', 'Pollo en pipián de pepitas con maíz', 'Pipián-Hähnchen mit Kürbiskernen und Mais', 'poultry_mains', 'dinner', 20, 8, 10, 'braising', 'oaxaca'),
  B('mx-phase-a-075', 'سلطة ديك رومي يوكاتانية بالحمضيات', 'Yucatecan Turkey Citrus Salad', 'Salade yucatèque de dinde aux agrumes', 'Ensalada yucateca de pavo con cítricos', 'Yucatekischer Putensalat mit Zitrusfrüchten', 'salads', 'lunch', 19, 7, 6, 'roasting', 'yucatan'),
];
