import { B, diasporaFor } from '../germany-base-data/rows.mjs';

const P = 'pan_german';

export default [
  B('شوربة الشعير بالقشدة', 'Creamy Barley Soup', 'Veloute d orge a la creme', 'Crema de cebada con nata', 'Cremige Gerstensuppe', 'soups_stews', 'lunch', 5, 19, 5, 'simmering', P, diasporaFor(P)),
  B('قرص البطاطس بالخبز', 'Potato Fritter with Bread', 'Galette de pomme de terre au pain', 'Patata frita con pan', 'Kartoffelpuffer mit Brot', 'breakfast_items', 'breakfast', 5, 22, 8, 'frying', P, diasporaFor(P)),
  B('شوربة الطماطم بالأعشاب', 'Herb Tomato Soup', 'Veloute de tomates aux herbes', 'Sopa de tomate con hierbas', 'Kräuter-Tomatensuppe', 'soups_stews', 'lunch', 2, 11, 4, 'simmering', P, diasporaFor(P)),
  B('كعك التفاح بالسكر', 'Apple Cake with Sugar', 'Gâteau aux pommes sucre', 'Bizcocho de manzana con azúcar', 'Zucker-Apfelkuchen', 'rice_cakes_sweets', 'snack', 3, 29, 10, 'baking', P, diasporaFor(P)),
  B('مرق الدجاج المنزلي', 'Home Chicken Stock', 'Bouillon de poulet maison', 'Caldo de pollo casero', 'Hühnerbrühe selbst gemacht', 'soups_stews', 'dinner', 9, 3, 6, 'simmering', P, diasporaFor(P)),
  B('لحم البقر المشوي بالزعتر', 'Roast Beef with Thyme', 'Roti de boeuf au thym', 'Asado de res con tomillo', 'Rinderbraten mit Thymian', 'meat_mains', 'dinner', 19, 3, 13, 'roasting', P, diasporaFor(P)),
  B('شوربة العدس بالقشدة', 'Creamy Lentil Soup', 'Veloute de lentilles a la creme', 'Crema de lentejas con nata', 'Cremige Linsensuppe', 'soups_stews', 'lunch', 8, 22, 6, 'simmering', P, diasporaFor(P)),
  B('سلطة الطماطم والموزاريلا', 'Tomato Mozzarella Salad', 'Salade tomates mozzarella', 'Ensalada de tomate y mozzarella', 'Tomaten-Mozzarella-Salat', 'vegetable_mains', 'lunch', 7, 5, 15, 'tossing', P, diasporaFor(P)),
  B('شوربة الكوسا', 'Zucchini Soup', 'Veloute de courgette', 'Crema de calabacín', 'Zucchinisuppe', 'soups_stews', 'lunch', 2, 9, 5, 'simmering', P, diasporaFor(P)),
  B('فاصولياء خضراء بالزبدة', 'Green Beans with Butter', 'Haricots verts au beurre', 'Judias verdes con mantequilla', 'Grüne Bohnen mit Butter', 'vegetable_mains', 'lunch', 3, 9, 9, 'simmering', P, diasporaFor(P)),
  B('خبز القمح الكامل', 'Wholemeal Bread', 'Pain complet', 'Pan integral', 'Vollkornbrot', 'breakfast_items', 'breakfast', 8, 25, 5, 'baking', P, diasporaFor(P)),
  B('شوربة البصل بالليمون', 'Lemon Onion Soup', 'Soupe citron-oignon', 'Sopa de limón y cebolla', 'Zitronenzwiebelsuppe', 'soups_stews', 'lunch', 2, 13, 5, 'simmering', P, diasporaFor(P)),
  B('قرص باللحم المفروم', 'Ground Meat Patty', 'Galette de viande hachee', 'Hamburguesa de carne picada', 'Hackfrikadelle', 'meat_mains', 'dinner', 15, 6, 13, 'pan_frying', P, diasporaFor(P)),
  B('سلطة الأرز بالخضار', 'Rice and Vegetable Salad', 'Salade de riz aux legumes', 'Ensalada de arroz con verduras', 'Reis-Gemüse-Salat', 'rice_dishes', 'lunch', 5, 24, 6, 'tossing', P, diasporaFor(P)),
  B('شوربة الكبانة', 'Cabbage Soup', 'Soupe au chou', 'Sopa de col', 'Krautsuppe', 'soups_stews', 'lunch', 4, 15, 4, 'simmering', P, diasporaFor(P)),
  B('صلصة الكزبوت', 'Cumin Sauce', 'Sauce au cumin', 'Salsa de comino', 'Kreuzkümmelsauce', 'condiments_sauces', 'snack', 1, 7, 6, 'assembling', P, diasporaFor(P)),
  B('شوربة الفراولة الباردة', 'Cold Strawberry Soup', 'Veloute de fraises froid', 'Crema fría de fresa', 'Kalte Erdbeersuppe', 'soups_stews', 'snack', 1, 14, 3, 'chilling', P, diasporaFor(P)),
  B('سمك مقلي بالبطاطس', 'Fried Fish with Potatoes', 'Poisson frit avec pommes de terre', 'Pescado frito con patata', 'Gebratener Fisch mit Kartoffeln', 'fish_seafood', 'dinner', 16, 20, 11, 'frying', P, diasporaFor(P)),
  B('شوربة السبانخ', 'Spinach Soup', 'Veloute d epinards', 'Crema de espinacas', 'Spinatsuppe', 'soups_stews', 'lunch', 5, 9, 5, 'simmering', P, diasporaFor(P)),
  B('سلطة الجزر بالمايونيز', 'Carrot Mayonnaise Salad', 'Salade de carottes mayonnaise', 'Ensalada de zanahoria mayonesa', 'Karottensalat mit Mayonnaise', 'vegetable_mains', 'lunch', 2, 12, 9, 'tossing', P, diasporaFor(P)),
  B('فطيرة اللحم المفروم', 'Ground Meat Pie', 'Tourte a la viande hachee', 'Tarta de carne picada', 'Hackfleischpastete', 'meat_mains', 'dinner', 15, 18, 13, 'baking', P, diasporaFor(P)),
  B('شوربة الفاصولياء بالمعكرونة', 'Bean Soup with Noodles', 'Soupe de haricots aux nouilles', 'Sopa de judias con fideos', 'Bohnensuppe mit Nudeln', 'soups_stews', 'dinner', 8, 22, 5, 'simmering', P, diasporaFor(P)),
  B('برجر الجشعير', 'Buckwheat Burger', 'Burger de sarrasin', 'Hamburguesa de alforfón', 'Buchweizen-Burger', 'vegetable_mains', 'lunch', 8, 20, 8, 'grilling', P, diasporaFor(P)),
  B('كرات الكينوا', 'Quinoa Balls', 'Boulettes de quinoa', 'Albóndigas de quinoa', 'Quinoa-Klötze', 'vegetable_mains', 'dinner', 7, 20, 6, 'baking', P, diasporaFor(P)),
  B('شوربة اللحم والخضار', 'Meat and Vegetable Soup', 'Soupe de viande et legumes', 'Sopa de carne y verduras', 'Fleisch-Gemüse-Suppe', 'soups_stews', 'dinner', 12, 14, 7, 'stewing', P, diasporaFor(P)),
  B('خبز بالسمسم', 'Sesame Bread', 'Pain au sesame', 'Pan con sésamo', 'Sesambrot', 'breakfast_items', 'snack', 7, 25, 6, 'baking', P, diasporaFor(P)),
  B('بسكويت الشوفان بالعسل', 'Honey Oatmeal Cookies', 'Biscuits d avoine au miel', 'Galletas de avena con miel', 'Haferkekse mit Honig', 'rice_cakes_sweets', 'snack', 5, 30, 10, 'baking', P, diasporaFor(P)),
  B('سلطة الفاصولياء الحمراء', 'Red Bean Salad', 'Salade de haricots rouges', 'Ensalada de judias rojas', 'Rote-Bohnen-Salat', 'vegetable_mains', 'lunch', 8, 17, 5, 'tossing', P, diasporaFor(P)),
  B('مرق عصير التفاح', 'Apple Juice Consomme', 'Consomme de jus de pomme', 'Consomé de zumo de manzana', 'Apfelsaft-Consomme', 'soups_stews', 'lunch', 3, 11, 3, 'simmering', P, diasporaFor(P)),
  B('شوربة الجزر بالبرتقال', 'Carrot Orange Soup', 'Veloute de carottes a l orange', 'Crema de zanahoria con naranja', 'Karotten-Orangen-Suppe', 'soups_stews', 'lunch', 3, 15, 4, 'simmering', P, diasporaFor(P)),
  B('معجون الفاصولياء بالخبز', 'Bean Spread with Bread', 'Pate de haricots avec pain', 'Paté de judias con pan', 'Bohnenaufstrich mit Brot', 'condiments_sauces', 'snack', 7, 16, 5, 'assembling', P, diasporaFor(P)),
  B('سلطة الطماطم بالريحان', 'Tomato Basil Salad', 'Salade tomates basilic', 'Ensalada de tomate y albahaca', 'Tomaten-Basilikum-Salat', 'vegetable_mains', 'lunch', 3, 7, 9, 'tossing', P, diasporaFor(P)),
  B('شوربة المشروم بالكريمة', 'Creamy Mushroom Soup', 'Veloute de champignons a la creme', 'Crema de champinones con nata', 'Rahmchampignonsuppe', 'soups_stews', 'lunch', 4, 11, 8, 'simmering', P, diasporaFor(P)),
  B('قرص الموز', 'Banana Pancake', 'Pancake a la banane', 'Panqueque de plátano', 'Bananenpfannkuchen', 'breakfast_items', 'breakfast', 5, 26, 7, 'frying', P, diasporaFor(P)),
  B('شوربة بذور الخشخاش', 'Poppy Seed Soup', 'Soupe aux graines de pavot', 'Sopa de semillas de amapola', 'Mohnsuppe', 'soups_stews', 'lunch', 4, 12, 6, 'simmering', P, diasporaFor(P)),
  B('مكعبات لحم البقر بالصلصة', 'Beef Cubes in Sauce', 'Bofu de boeuf en sauce', 'Cubos de res en salsa', 'Rinderragout in Sauce', 'meat_mains', 'dinner', 18, 8, 14, 'stewing', P, diasporaFor(P)),
  B('شوربة التفاح', 'Apple Soup', 'Veloute de pommes', 'Crema de manzana', 'Apfelsuppe', 'soups_stews', 'snack', 1, 13, 3, 'simmering', P, diasporaFor(P)),
  B('برجر الفاصولياء الحمراء', 'Red Bean Burger', 'Burger de haricots rouges', 'Hamburguesa de judias rojas', 'Rote-Bohnen-Burger', 'vegetable_mains', 'lunch', 9, 21, 8, 'grilling', P, diasporaFor(P)),
  B('سلطة المكسرات والجبن', 'Cheese and Nut Salad', 'Salade de fromage et noix', 'Ensalada de queso y nueces', 'Käse-Nuss-Salat', 'vegetable_mains', 'lunch', 9, 8, 16, 'tossing', P, diasporaFor(P)),
  B('شوربة الكعكة المرّة', 'Bitter Cocoa Soup', 'Veloute au cacao amer', 'Crema de cacao amargo', 'Bittere-Kakao-Suppe', 'soups_stews', 'snack', 5, 16, 7, 'simmering', P, diasporaFor(P)),
  B('كعك الجوز الحلو', 'Sweet Walnut Loaf', 'Pain aux noix sucre', 'Bizcocho dulce de nueces', 'Süßer Walnusskuchen', 'rice_cakes_sweets', 'snack', 5, 28, 12, 'baking', P, diasporaFor(P)),
  B('شوربة الفطر بالخبز', 'Mushroom Bread Soup', 'Veloute de champignons au pain', 'Crema de champinones con pan', 'Pilz-Brot-Suppe', 'soups_stews', 'lunch', 5, 18, 6, 'simmering', P, diasporaFor(P)),
  B('شوربة العدس بالكمون', 'Lentil Soup with Cumin', 'Soupe de lentilles au cumin', 'Sopa de lentejas con comino', 'Linsensuppe mit Kreuzkümmel', 'soups_stews', 'lunch', 8, 22, 4, 'simmering', P, diasporaFor(P)),
  B('قرص الشوفان بالتمر', 'Oatmeal Date Bar', 'Barre d avoine aux dattes', 'Barra de avena con dátiles', 'Hafer-Dattel-Riegel', 'rice_cakes_sweets', 'snack', 5, 29, 9, 'baking', P, diasporaFor(P)),
];