import { B, diasporaFor } from '../germany-base-data/rows.mjs';

const P = 'pan_german';
const BAV = 'bavaria';

export default [
  B('شوربة السبانخ بالبيضة', 'Spinach Egg Soup', 'Veloute d epinards a l oeuf', 'Crema de espinacas con huevo', 'Spinat-Ei-Suppe', 'soups_stews', 'lunch', 7, 10, 6, 'simmering', P, diasporaFor(P)),
  B('سلطة الفاصولياء الحمراء بالكمون', 'Kidney Bean Salad', 'Salade de haricots au cumin', 'Ensalada de judias con comino', 'Kidney-Bohnen-Salat', 'vegetable_mains', 'lunch', 8, 18, 5, 'tossing', P, diasporaFor(P)),
  B('كعك اللوز', 'Almond Cake', 'Gateau aux amandes', 'Bizcocho de almendras', 'Mandelkuchen', 'rice_cakes_sweets', 'snack', 6, 29, 15, 'baking', P, diasporaFor(P)),
  B('شوربة الكرفس بالقشدة', 'Cream of Celery Soup', 'Veloute de celeri a la creme', 'Crema de apionabo con nata', 'Selleriecremesuppe', 'soups_stews', 'lunch', 3, 10, 6, 'simmering', P, diasporaFor(P)),
  B('مقبلات اللحم بالبيضة', 'Egg and Meat Starter', 'Entrée viande-oeuf', 'Entrante de carne y huevo', 'Eier-Fleisch-Vorspeise', 'meat_mains', 'snack', 12, 4, 11, 'assembling', P, diasporaFor(P)),
  B('شوربة الخضار المهيأة', 'Vegetable Puree Soup', 'Veloute de légumes mixte', 'Crema de verduras mixta', 'Gemüsepüree-Suppe', 'soups_stews', 'lunch', 4, 15, 5, 'simmering', P, diasporaFor(P)),
  B('دجاج المشوي بالخشب', 'Rotisserie Chicken Plate', 'Poulet rôti', 'Pollo asado', 'Rotisserie-Hähnchen', 'poultry_mains', 'dinner', 18, 3, 12, 'roasting', P, diasporaFor(P)),
  B('شوربة البطاطس بالقشدة', 'Creamy Potato Soup', 'Veloute de pommes de terre a la creme', 'Crema de patata con nata', 'Cremige Kartoffelsuppe', 'soups_stews', 'lunch', 5, 18, 7, 'simmering', P, diasporaFor(P)),
  B('سلطة الفاصولياء والخضار', 'Bean and Vegetable Salad', 'Salade de haricots et legumes', 'Ensalada de judias y verduras', 'Bohnen-Gemüse-Salat', 'vegetable_mains', 'lunch', 7, 16, 6, 'tossing', P, diasporaFor(P)),
  B('شوربة لحم الدجاج والأرز', 'Chicken Rice Soup', 'Soupe de poulet au riz', 'Sopa de pollo con arroz', 'Huhn-Reis-Suppe', 'soups_stews', 'dinner', 10, 20, 5, 'simmering', P, diasporaFor(P)),
  B('فطيرة الزعتر والجبنة', 'Thyme Cheese Pie', 'Tourte au thym et fromage', 'Tarta de tomillo y queso', 'Thymian-Käse-Tarte', 'vegetable_mains', 'snack', 8, 20, 14, 'baking', P, diasporaFor(P)),
  B('قرص بيتزا بالجبنة', 'Cheese Flatbread', 'Pizza au fromage', 'Pizza de queso', 'Käsefladen', 'rice_dishes', 'lunch', 11, 26, 12, 'baking', P, diasporaFor(P)),
  B('شوربة الطماطم الحلوة', 'Sweet Tomato Soup', 'Veloute de tomates douce', 'Crema de tomate dulce', 'Süße Tomatensuppe', 'soups_stews', 'lunch', 2, 12, 4, 'simmering', P, diasporaFor(P)),
  B('سلطة الخس واليصليص', 'Lettuce and Tomato Salad', 'Salade laitue tomate', 'Ensalada de lechuga y tomate', 'Salat aus Gurke und Tomate', 'vegetable_mains', 'lunch', 2, 7, 6, 'tossing', P, diasporaFor(P)),
  B('شوربة الشعير بالخبز', 'Barley Bread Soup', 'Veloute d orge au pain', 'Crema de cebada con pan', 'Gersten-Brot-Suppe', 'soups_stews', 'lunch', 6, 20, 5, 'simmering', P, diasporaFor(P)),
  B('كعك اللوز الحلقي', 'Almond Ring Cake', 'Gateau aux amandes en anneau', 'Bizcocho de anillo de almendras', 'Mandelring', 'rice_cakes_sweets', 'snack', 6, 30, 14, 'baking', P, diasporaFor(P)),
  B('لحم البقر المشوي بالثوم', 'Roast Beef with Garlic', 'Roti de boeuf a l ail', 'Asado de res con ajo', 'Rinderbraten mit Knoblauch', 'meat_mains', 'dinner', 19, 4, 14, 'roasting', P, diasporaFor(P)),
  B('شوربة البازلاء والجزر', 'Pea and Carrot Soup', 'Veloute de petits pois et carottes', 'Crema de guisantes y zanahoria', 'Erbsen-Karotten-Suppe', 'soups_stews', 'lunch', 5, 14, 4, 'simmering', P, diasporaFor(P)),
  B('سلطة الشعير بالجزر', 'Barley Carrot Salad', 'Salade d orge et carottes', 'Ensalada de cebada y zanahoria', 'Gerste-Karotten-Salat', 'vegetable_mains', 'lunch', 5, 22, 5, 'tossing', P, diasporaFor(P)),
  B('فطيرة التفاح بالقشدة', 'Apple Cream Pie', 'Tourte aux pommes a la creme', 'Tarta de manzana con crema', 'Apfel-Sahne-Torte', 'rice_cakes_sweets', 'snack', 4, 30, 12, 'baking', P, diasporaFor(P)),
  B('شوربة عين الجمل', 'Peanut Soup', 'Soupe de cacahuètes', 'Sopa de cacahuete', 'Erdnuss-Suppe', 'soups_stews', 'lunch', 8, 13, 10, 'simmering', P, diasporaFor(P)),
  B('برجر الفول والجمبري', 'Shrimp Bean Burger', 'Burger crevettes haricots', 'Hamburguesa de judias y camarones', 'Kraddelbohnen-Burger', 'vegetable_mains', 'lunch', 11, 18, 9, 'grilling', P, diasporaFor(P)),
  B('شوربة الجزر بالقشدة', 'Creamy Carrot Soup', 'Veloute de carottes a la creme', 'Crema de zanahoria con nata', 'Cremige Karottensuppe', 'soups_stews', 'lunch', 3, 13, 6, 'simmering', P, diasporaFor(P)),
  B('قرص الزنجبيل', 'Ginger Biscuit', 'Biscuit au gingembre', 'Galleta de jengibre', 'Ingwerkeks', 'rice_cakes_sweets', 'snack', 4, 29, 9, 'baking', P, diasporaFor(P)),
  B('سلطة الكوسا والزيتون', 'Courgette Olive Salad', 'Salade courgette olives', 'Ensalada de calabacín y aceitunas', 'Zucchini-Oliven-Salat', 'vegetable_mains', 'lunch', 3, 10, 9, 'tossing', P, diasporaFor(P)),
  B('شوربة لحم البقر والخضار الجذرية', 'Beef Root Soup', 'Veloute de boeuf et racines', 'Crema de res y raíz', 'Rindfleisch-Wurzelsuppe', 'soups_stews', 'dinner', 13, 15, 8, 'stewing', P, diasporaFor(P)),
  B('كعك الأرز', 'Rice Cake', 'Gateau de riz', 'Bizcocho de arroz', 'Reiskuchen', 'rice_cakes_sweets', 'snack', 5, 28, 10, 'baking', P, diasporaFor(P)),
  B('مقبلات الفاصولياء بالسماق', 'Bean Hummus', 'Houmous de haricots', 'Hummus de judias', 'Bohnen-Hummus', 'condiments_sauces', 'snack', 8, 14, 8, 'assembling', P, diasporaFor(P)),
  B('شوربة البصل والكزبوت', 'Onion Cumin Soup', 'Veloute d oignon cumin', 'Crema de cebolla y comino', 'Zwiebel-Kümmel-Suppe', 'soups_stews', 'lunch', 3, 12, 5, 'simmering', P, diasporaFor(P)),
  B('شوربة التفاح بالقرفة', 'Apple Cinnamon Soup', 'Veloute de pommes a la cannelle', 'Crema de manzana con canela', 'Apfel-Zimt-Suppe', 'soups_stews', 'snack', 1, 14, 3, 'simmering', P, diasporaFor(P)),
  B('لحم البقر والطماطم', 'Beef with Tomato', 'Boeuf a la tomate', 'Res con tomate', 'Rindfleisch mit Tomate', 'meat_mains', 'dinner', 18, 9, 13, 'stewing', P, diasporaFor(P)),
  B('سلطة الخردل والفاصولياء', 'Mustard Bean Salad', 'Salade haricots moutarde', 'Ensalada de judias y mostaza', 'Senf-Bohnen-Salat', 'vegetable_mains', 'lunch', 8, 16, 8, 'tossing', P, diasporaFor(P)),
  B('فطيرة العجين المقرمش', 'Puff Pastry Pie', 'Tourte en pâte feuilletée', 'Tarta de hojaldre', 'Blätterteig-Torte', 'rice_cakes_sweets', 'snack', 5, 31, 14, 'baking', P, diasporaFor(P)),
  B('شوربة الخرشوف', 'Artichoke Soup', 'Veloute d artichaut', 'Crema de alcachofa', 'Artischockensuppe', 'soups_stews', 'lunch', 3, 13, 5, 'simmering', P, diasporaFor(P)),
  B('برجر التونة بالخبز', 'Tuna Burger with Bread', 'Burger au thon', 'Hamburguesa de atún', 'Thunfisch-Burger', 'fish_seafood', 'lunch', 14, 18, 10, 'grilling', P, diasporaFor(P)),
  B('شوربة العمران', 'Chicken Cream Soup', 'Veloute de poulet a la creme', 'Crema de pollo con nata', 'Hühnercremesuppe', 'soups_stews', 'lunch', 9, 10, 7, 'simmering', P, diasporaFor(P)),
  B('كعك الموز بالعسل', 'Honey Banana Bread', 'Pain banane miel', 'Bizcocho de plátano con miel', 'Bananenbrot mit Honig', 'rice_cakes_sweets', 'snack', 4, 30, 10, 'baking', P, diasporaFor(P)),
  B('سلطة البصل والتفاح', 'Onion Apple Salad', 'Salade oignons pommes', 'Ensalada de cebolla y manzana', 'Zwiebel-Apfel-Salat', 'vegetable_mains', 'lunch', 2, 13, 6, 'tossing', P, diasporaFor(P)),
  B('شوربة الفاصولياء بالأعشاب', 'Herb Bean Soup', 'Veloute de haricots aux herbes', 'Crema de judias con hierbas', 'Kräuterbohnensuppe', 'soups_stews', 'lunch', 7, 17, 5, 'simmering', P, diasporaFor(P)),
  B('قرص البطاطا بالمقلاة', 'Potato Pancake', 'Galette de pomme de terre', 'Panqueque de patata', 'Kartoffelpuffer', 'breakfast_items', 'breakfast', 6, 23, 9, 'frying', P, diasporaFor(P)),
  B('كعك الفواكه الجافة', 'Dried Fruit Cake', 'Gateau aux fruits secs', 'Bizcocho de fruta seca', 'Trockenobstkuchen', 'rice_cakes_sweets', 'snack', 5, 30, 11, 'baking', P, diasporaFor(P)),
  B('شوربة الدجاج والخضار', 'Chicken Vegetable Soup', 'Soupe de poulet aux legumes', 'Sopa de pollo con verduras', 'Huhn-Gemüse-Suppe', 'soups_stews', 'dinner', 11, 16, 6, 'simmering', P, diasporaFor(P)),

  B('مقبلات الجبن البافارية', 'Bavarian Cheese Platter', 'Plateau de fromages bavarois', 'Plato de quesos bávaros', 'Bayerische Käseplatte', 'street_snacks', 'snack', 12, 4, 19, 'assembling', BAV, diasporaFor(BAV)),
  B('شوربة الشعير البافارية', 'Bavarian Barley Soup', 'Veloute d orge bavaroise', 'Crema de cebada bávara', 'Bayerische Gerstensuppe', 'soups_stews', 'lunch', 5, 19, 5, 'simmering', BAV, diasporaFor(BAV)),
  B('برجر الفطر بالقشدة البافاري', 'Bavarian Mushroom Burger', 'Burger aux champignons bavarois', 'Hamburguesa de champinones bávara', 'Bayerischer Pilzburger', 'vegetable_mains', 'lunch', 8, 18, 10, 'grilling', BAV, diasporaFor(BAV)),
  B('فطيرة الشوكولاتة البافارية', 'Bavarian Chocolate Pie', 'Tourte chocolat bavarois', 'Tarta de chocolate bávara', 'Bayerischer Schokoladenkuchen', 'rice_cakes_sweets', 'snack', 5, 31, 13, 'baking', BAV, diasporaFor(BAV)),
  B('شوربة الدجاج بالأعشاب البافارية', 'Bavarian Herb Chicken Soup', 'Veloute poulet herbes bavaroise', 'Crema de pollo y hierbas bávara', 'Bayerische Kräuterhühnersuppe', 'soups_stews', 'lunch', 10, 15, 6, 'simmering', BAV, diasporaFor(BAV)),
];