import { B, diasporaFor } from './rows.mjs';

const P = 'pan_german';
const BAV = 'bavaria';

export default [
  B('قرص البطاطس بالقشدة الحامضة', 'Kartoffelpuffer with Sour Cream', 'Galette de pommes de terre a la creme fraiche', 'Patata frita con nata agria', 'Kartoffelpuffer mit Sauerrahm', 'breakfast_items', 'breakfast', 7, 22, 9, 'frying', P, diasporaFor(P)),
  B('مرقة اللحم البقر مع الجزر', 'Beef Broth with Carrot', 'Bouillon de boeuf a la carotte', 'Caldo de res con zanahoria', 'Rinderbruehe mit Moehren', 'soups_stews', 'lunch', 8, 6, 4, 'simmering', P, diasporaFor(P)),
  B('برغل مع اللحم البقر', 'Beef Bulgur Pilaf', 'Boulgur de boeuf', 'Bulgur con res', 'Bulgur-Pilaw mit Rindfleisch', 'rice_dishes', 'dinner', 14, 24, 8, 'simmering', P, diasporaFor(P)),
  B('سلطة البطاطس بالكريمة', 'Creamy Potato Salad', 'Salade de pommes de terre a la creme', 'Ensalada de patata cremosa', 'Kartoffelsalat mit Sahnemajo', 'vegetable_mains', 'lunch', 4, 20, 7, 'tossing', P, diasporaFor(P)),
  B('شوربة الشعير بالخضار', 'Barley Vegetable Soup', 'Soupe d orge aux legumes', 'Sopa de cebada con verduras', 'Gerstensuppe mit Gemuese', 'soups_stews', 'lunch', 5, 18, 3, 'simmering', P, diasporaFor(P)),
  B('كوسة مشوية بزيت الزيتون', 'Grilled Zucchini with Olive Oil', 'Courge grill a l huile d olive', 'Calabacin a la plancha con aceite de oliva', 'Zucchini gegrillt mit Olivenoel', 'vegetable_mains', 'lunch', 2, 7, 8, 'grilling', P, diasporaFor(P)),
  B('بيض مخبوز بالخضار', 'Baked Egg with Vegetables', 'Oeuf au four aux legumes', 'Huevo al horno con verduras', 'Gebackenes Ei mit Gemuese', 'breakfast_items', 'lunch', 7, 8, 6, 'baking', P, diasporaFor(P)),
  B('لحم البقر المشوي بخردل ديجون', 'Roast Beef with Dijon Mustard', 'Roti de boeuf a la moutarde de Dijon', 'Asado de res con mostaza de Dijon', 'Rinderbraten mit Dijoner Senf', 'meat_mains', 'dinner', 19, 4, 14, 'roasting', P, diasporaFor(P)),
  B('فطيرة الفاصولياء الحمراء', 'Red Bean Tart', 'Tarte aux haricots rouges', 'Tarta de judias rojas', 'Rote-Bohnen-Tarte', 'vegetable_mains', 'snack', 8, 26, 9, 'baking', P, diasporaFor(P)),
  B('شوربة الجزر بالكمون', 'Carrot Soup with Cumin', 'Veloute de carottes au cumin', 'Crema de zanahoria con comino', 'Karottensuppe mit Kreuzkuemmel', 'soups_stews', 'lunch', 2, 11, 4, 'simmering', P, diasporaFor(P)),
  B('فتة الخبز مع خضار مطهوة', 'Bread with Vegetable Ragout', 'Pain avec ragout de legumes', 'Pan con ragout de verduras', 'Brot mit Gemuese-Ragout', 'vegetable_mains', 'lunch', 6, 22, 7, 'assembling', P, diasporaFor(P)),
  B('مكرونة بالصلصة البيضاء', 'Pasta with White Sauce', 'Pates a la sauce blanche', 'Pasta con salsa blanca', 'Nudeln mit heller Sauce', 'noodle_dishes', 'lunch', 8, 26, 9, 'simmering', P, diasporaFor(P)),
  B('كعك الحنطة السوداء', 'Buckwheat Pancakes', 'Galettes de sarrasin', 'Panqueques de alforfon', 'Buchweizenpfannkuchen', 'breakfast_items', 'breakfast', 5, 28, 8, 'frying', P, diasporaFor(P)),
  B('شرائح البطاطس في الفرن', 'Baked Potato Slices', 'Frites au four', 'Patatas al horno', 'Ofenkartoffelscheiben', 'vegetable_mains', 'snack', 3, 24, 8, 'baking', P, diasporaFor(P)),
  B('شوربة الفاصولياء البيضاء', 'White Bean Soup', 'Soupe de haricots blancs', 'Sopa de judias blancas', 'Weisse-Bohnen-Suppe', 'soups_stews', 'lunch', 6, 16, 3, 'simmering', P, diasporaFor(P)),
  B('سلمون مدخن بالكاتشب', 'Smoked Salmon with Ketchup', 'Saumon fume au ketchup', 'Salmon ahumado con ketchup', 'Raeucherlachs mit Ketchup', 'fish_seafood', 'snack', 12, 4, 12, 'grilling', P, diasporaFor(P)),
  B('شوربة الطماطم بالريحان', 'Tomato Soup with Basil', 'Veloute de tomates au basilic', 'Sopa de tomate con albahaca', 'Tomatensuppe mit Basilikum', 'soups_stews', 'lunch', 2, 10, 4, 'simmering', P, diasporaFor(P)),
  B('قرنبيط مشوي بصلصة الباربكيو', 'Barbecued Cauliflower', 'Chou-fleur au barbecue', 'Coliflor a la barbacoa', 'Grill-Blumenkohl mit Barbecue-Glasur', 'vegetable_mains', 'dinner', 4, 12, 10, 'grilling', P, diasporaFor(P)),
  B('سلطة البازلاء والجزر', 'Pea and Carrot Salad', 'Salade de petits pois et carottes', 'Ensalada de guisantes y zanahoria', 'Erbsen-Karotten-Salat', 'vegetable_mains', 'lunch', 5, 14, 4, 'tossing', P, diasporaFor(P)),
  B('خبز بالبصل والزيت', 'Onion Bread with Oil', 'Pain aux oignons a l huile', 'Pan de cebolla con aceite', 'Zwiebelbrot mit Oel', 'breakfast_items', 'snack', 6, 24, 7, 'baking', P, diasporaFor(P)),
  B('فاصولياء خضراء بزيت الزيتون', 'Green Beans with Olive Oil', 'Haricots verts a l huile d olive', 'Judias verdes con aceite de oliva', 'Gruene Bohnen mit Olivenoel', 'vegetable_mains', 'lunch', 3, 9, 6, 'simmering', P, diasporaFor(P)),
  B('بسكويت الشوفان', 'Oatmeal Cookies', 'Biscuits d avoine', 'Galletas de avena', 'Haferkekse', 'rice_cakes_sweets', 'snack', 5, 30, 11, 'baking', P, diasporaFor(P)),
  B('شرائح التفاح بالقرفة', 'Apple Slices with Cinnamon', 'Tranches de pomme a la cannelle', 'Rodajas de manzana con canela', 'Apfelscheiben mit Zimt', 'fruit', 'snack', 1, 16, 1, 'assembling', P, diasporaFor(P)),
  B('ماء الورد', 'Rose Water', 'Eau de rose', 'Agua de rosas', 'Rosenwasser', 'beverages', 'snack', 0, 3, 0, 'brewing', P, diasporaFor(P)),
  B('صلصة التوت البري', 'Cranberry Sauce', 'Sauce aux airelles', 'Salsa de arandanos', 'Preiselbeersauce', 'condiments_sauces', 'snack', 0, 14, 0, 'simmering', P, diasporaFor(P)),
  B('سلطة الدجاج بالأوراق الخضراء', 'Chicken Salad with Greens', 'Salade de poulet aux Greene', 'Ensalada de pollo con hojas verdes', 'Huhner-Salat mit Gruenkraut', 'poultry_mains', 'lunch', 14, 6, 10, 'tossing', P, diasporaFor(P)),
  B('الشوفان بالحليب', 'Oatmeal with Milk', 'Flocons d avoine au lait', 'Avena con leche', 'Hafergruetze mit Milch', 'breakfast_items', 'breakfast', 5, 18, 4, 'boiling', P, diasporaFor(P)),
  
  B('كرستن لحم البقر', 'Beef Roulade with Red Cabbage', 'Rouleau de boeuf au chou rouge', 'Rollito de res con col lombarda', 'Rinderroulade mit Rotkohl', 'meat_mains', 'dinner', 18, 10, 13, 'braising', BAV, diasporaFor(BAV)),
  B('سوبياء لحم العجل', 'Veal Sausage with Sauerkraut', 'Saucisse de veau au choucroute', 'Salchicha de ternera con chucrut', 'Kalbswurst mit Sauerkraut', 'meat_mains', 'dinner', 13, 10, 12, 'simmering', BAV, diasporaFor(BAV)),
  B('شنيتزل العجل', 'Veal Schnitzel', 'Escalope de veau', 'Escalope de ternera', 'Kalbsschnitzel', 'meat_mains', 'dinner', 17, 8, 14, 'frying', BAV, diasporaFor(BAV)),
  B('قرص بطاطس مزدوج السطح', 'Double-Baked Potato', 'Pomme de terre deux fois au four', 'Patata doble horneada', 'Doppelt gebackene Kartoffel', 'vegetable_mains', 'dinner', 5, 24, 8, 'baking', BAV, diasporaFor(BAV)),
  B('قرص فطيرة اللحم', 'Meat Pie with Onion', 'Tourte a la viande et aux oignons', 'Pastel de carne y cebolla', 'Zwiebel-Fleischpastete', 'meat_mains', 'dinner', 14, 20, 12, 'baking', BAV, diasporaFor(BAV)),
  B('كروسبان لحم البقر', 'Beef Croissant', 'Croissant au boeuf', 'Croissant de carne de res', 'Rindfleisch-Croissant', 'breakfast_items', 'breakfast', 10, 20, 12, 'baking', BAV, diasporaFor(BAV)),
  B('سلطة الملفوف بالخل', 'Coleslaw with Vinegar', 'Coleslaw au vinaigre', 'Ensalada de col con vinagre', 'Krautsalat mit Essig', 'vegetable_mains', 'lunch', 2, 9, 5, 'tossing', BAV, diasporaFor(BAV)),
  B('شوربة الدجاج بالبصل', 'Chicken Onion Soup', 'Soupe de poulet a l oignon', 'Sopa de pollo con cebolla', 'Hühner-Zwiebelsuppe', 'soups_stews', 'lunch', 9, 7, 4, 'simmering', BAV, diasporaFor(BAV)),
  B('جبن الكامامبير بالخبز', 'Camembert with Bread', 'Camembert avec pain', 'Camembert con pan', 'Camembert mit Brot', 'street_snacks', 'snack', 8, 18, 12, 'assembling', BAV, diasporaFor(BAV)),
  B('حساء الدجاج بالنودلز', 'Chicken Noodle Soup', 'Soupe de poulet aux nouilles', 'Sopa de pollo con fideos', 'Huhn-Nudelsuppe', 'soups_stews', 'lunch', 10, 16, 4, 'simmering', BAV, diasporaFor(BAV)),
  B('قرص بطاطس بالجبنة', 'Potato Wedges with Cheese', 'Frites de pomme de terre au fromage', 'Patatas en gajos con queso', 'Kartoffelkeile mit Käse', 'vegetable_mains', 'lunch', 6, 24, 11, 'baking', BAV, diasporaFor(BAV)),
  B('شوربة كفتة اللحم', 'Beef Dumpling Soup', 'Soupe de ravioles de boeuf', 'Sopa de dumplings de res', 'Rindfleischkloss-Suppe', 'soups_stews', 'dinner', 12, 18, 7, 'simmering', BAV, diasporaFor(BAV)),
  B('خبز البافاري الحلو', 'Bavarian Sweet Bread', 'Pain doux bavarois', 'Pan dulce bávaro', 'Bayerisches Suessbrot', 'rice_cakes_sweets', 'snack', 4, 30, 9, 'baking', BAV, diasporaFor(BAV)),
  B('سلطة اللحم البقر', 'Beef Salad', 'Salade de boeuf', 'Ensalada de res', 'Rindfleisch-Salat', 'meat_mains', 'lunch', 15, 5, 11, 'tossing', BAV, diasporaFor(BAV)),
  B('شوربة كريمية يومية', 'Cream Soup of the Day', 'Veloute du jour', 'Crema del día', 'Tagescremesuppe', 'soups_stews', 'lunch', 3, 12, 6, 'simmering', BAV, diasporaFor(BAV)),
  B('برجر الفطر', 'Mushroom Burger', 'Burger aux champignons', 'Hamburguesa de champinones', 'Pilz-Burger', 'vegetable_mains', 'lunch', 8, 18, 11, 'grilling', BAV, diasporaFor(BAV)),
  B('بيض مخبوز بالصلصة', 'Eggs Baked in Sauce', 'Oeufs au plat en sauce', 'Huevos al horno en salsa', 'Gebackene Eier in Sauce', 'breakfast_items', 'breakfast', 9, 5, 11, 'baking', BAV, diasporaFor(BAV)),
  ];