import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  indian: [
    { name_en: 'Masala Dosa', name_ar: 'دوسا ماسالا', mealType: 'breakfast', calories: 270, protein: 7.5, carbs: 48, fat: 6.8 },
    { name_en: 'Idli Sambar', name_ar: 'إدلي سامبار', mealType: 'breakfast', calories: 135, protein: 5.3, carbs: 24, fat: 1.5 },
    { name_en: 'Poha', name_ar: 'بوهة', mealType: 'breakfast', calories: 260, protein: 7, carbs: 50, fat: 6 },
    { name_en: 'Upma', name_ar: 'أوبما', mealType: 'breakfast', calories: 350, protein: 10, carbs: 55, fat: 10 },
    { name_en: 'Chicken Biryani', name_ar: 'بيرياني دجاج', mealType: 'lunch', calories: 390, protein: 24, carbs: 42, fat: 13.5 },
    { name_en: 'Butter Chicken', name_ar: 'دجاج بالزبدة', mealType: 'lunch', calories: 360, protein: 22, carbs: 14, fat: 24 },
    { name_en: 'Dal Makhani', name_ar: 'دال ماخاني', mealType: 'lunch', calories: 450, protein: 20, carbs: 42.5, fat: 20 },
    { name_en: 'Chana Masala', name_ar: 'شانا ماسالا', mealType: 'lunch', calories: 300, protein: 12.5, carbs: 42.5, fat: 8.8 },
    { name_en: 'Chicken Tikka Masala', name_ar: 'دجاج تيكا ماسالا', mealType: 'dinner', calories: 300, protein: 20, carbs: 20, fat: 14 },
    { name_en: 'Palak Paneer', name_ar: 'بالاك بانير', mealType: 'dinner', calories: 270, protein: 14, carbs: 14, fat: 18 },
    { name_en: 'Rogan Josh', name_ar: 'روغان جوش', mealType: 'dinner', calories: 400, protein: 35, carbs: 15, fat: 22.5 },
    { name_en: 'Vegetable Pulao', name_ar: 'بولاو خضار', mealType: 'dinner', calories: 420, protein: 11.2, carbs: 72.8, fat: 9.8 },
    { name_en: 'Samosa', name_ar: 'سمبوسة', mealType: 'snack', calories: 208, protein: 4, carbs: 21.6, fat: 12 },
    { name_en: 'Jalebi', name_ar: 'جاليبي', mealType: 'snack', calories: 192, protein: 1.8, carbs: 45, fat: 3.6 },
  ],
  pakistani: [
    { name_en: 'Nihari', name_ar: 'نيهاري', mealType: 'breakfast', calories: 450, protein: 36, carbs: 24, fat: 24 },
    { name_en: 'Halwa Puri', name_ar: 'حلوى بوري', mealType: 'breakfast', calories: 640, protein: 12, carbs: 70, fat: 34 },
    { name_en: 'Aloo Paratha', name_ar: 'ألو براتا', mealType: 'breakfast', calories: 360, protein: 7.5, carbs: 48, fat: 14.3 },
    { name_en: 'Anda Paratha', name_ar: 'أندا براتا', mealType: 'breakfast', calories: 442, protein: 13.6, carbs: 57.8, fat: 17 },
    { name_en: 'Chicken Karahi', name_ar: 'كراهي دجاج', mealType: 'lunch', calories: 413, protein: 37.5, carbs: 15, fat: 20 },
    { name_en: 'Chicken Biryani', name_ar: 'بيرياني دجاج', mealType: 'lunch', calories: 390, protein: 24, carbs: 42, fat: 13.5 },
    { name_en: 'Seekh Kebab', name_ar: 'كباب سيخ', mealType: 'lunch', calories: 400, protein: 32, carbs: 16, fat: 24 },
    { name_en: 'Haleem', name_ar: 'حليم', mealType: 'lunch', calories: 390, protein: 27, carbs: 36, fat: 15 },
    { name_en: 'Chicken Tikka', name_ar: 'تيكا دجاج', mealType: 'dinner', calories: 336, protein: 56, carbs: 5.6, fat: 8.4 },
    { name_en: 'Daal Chawal', name_ar: 'دال تشاوال', mealType: 'dinner', calories: 392, protein: 16.8, carbs: 70, fat: 7 },
    { name_en: 'Chapli Kebab', name_ar: 'كباب تشابلي', mealType: 'dinner', calories: 336, protein: 28.8, carbs: 9.6, fat: 20.8 },
    { name_en: 'Beef Karahi', name_ar: 'كراهي لحم', mealType: 'dinner', calories: 504, protein: 42, carbs: 14, fat: 30.8 },
    { name_en: 'Chana Chaat', name_ar: 'شانا شات', mealType: 'snack', calories: 84, protein: 3, carbs: 12, fat: 2.4 },
    { name_en: 'Gol Gappay', name_ar: 'جول جابي', mealType: 'snack', calories: 130, protein: 2.5, carbs: 20, fat: 4 },
  ],
  chinese: [
    { name_en: 'Congee', name_ar: 'كونغي', mealType: 'breakfast', calories: 150, protein: 4.5, carbs: 30, fat: 0.6 },
    { name_en: 'Jianbing', name_ar: 'جيانبينغ', mealType: 'breakfast', calories: 450, protein: 17.5, carbs: 60, fat: 15 },
    { name_en: 'Har Gow', name_ar: 'هار غاو', mealType: 'breakfast', calories: 250, protein: 12.5, carbs: 30, fat: 7.5 },
    { name_en: 'Scallion Pancake', name_ar: 'فطيرة البصل الأخضر', mealType: 'breakfast', calories: 568, protein: 16, carbs: 70, fat: 24.3 },
    { name_en: 'Kung Pao Chicken', name_ar: 'دجاج كونغ باو', mealType: 'lunch', calories: 320, protein: 28, carbs: 18, fat: 16 },
    { name_en: 'Beef Chow Fun', name_ar: 'تشاو فون باللحم', mealType: 'lunch', calories: 450, protein: 27, carbs: 54, fat: 13.5 },
    { name_en: 'Mapo Tofu', name_ar: 'مابو توفو', mealType: 'lunch', calories: 300, protein: 18, carbs: 12, fat: 20 },
    { name_en: 'Dan Dan Noodles', name_ar: 'نودلز دان دان', mealType: 'lunch', calories: 570, protein: 24, carbs: 72, fat: 21 },
    { name_en: 'Peking Duck', name_ar: 'بط بكين', mealType: 'dinner', calories: 460, protein: 38, carbs: 8, fat: 30 },
    { name_en: 'Wonton Noodle Soup', name_ar: 'حساء نودلز بالوانتون', mealType: 'dinner', calories: 168, protein: 7, carbs: 25.2, fat: 4.2 },
    { name_en: 'Yangzhou Fried Rice', name_ar: 'أرز يانغتشو المقلي', mealType: 'dinner', calories: 326, protein: 10, carbs: 56, fat: 8 },
    { name_en: 'Sichuan Eggplant', name_ar: 'باذنجان سيتشوان', mealType: 'dinner', calories: 336, protein: 5.6, carbs: 33.6, fat: 21 },
    { name_en: 'Spring Roll', name_ar: 'رول الربيع', mealType: 'snack', calories: 180, protein: 4, carbs: 26, fat: 6.5 },
    { name_en: 'Sesame Balls', name_ar: 'كرات السمسم', mealType: 'snack', calories: 150, protein: 2.5, carbs: 27.5, fat: 3.5 },
  ],
  korean: [
    { name_en: 'Juk', name_ar: 'جوك', mealType: 'breakfast', calories: 125, protein: 3.8, carbs: 25, fat: 0.5 },
    { name_en: 'Kimchi Jjigae', name_ar: 'كيمتشي جيغاي', mealType: 'breakfast', calories: 163, protein: 12.5, carbs: 15, fat: 6.3 },
    { name_en: 'Miyeokguk', name_ar: 'مياوك غوك', mealType: 'breakfast', calories: 100, protein: 7.5, carbs: 12.5, fat: 2.5 },
    { name_en: 'Gyeran Bap', name_ar: 'غيران باب', mealType: 'breakfast', calories: 425, protein: 17.5, carbs: 60, fat: 12.5 },
    { name_en: 'Bibimbap', name_ar: 'بيبيمباب', mealType: 'lunch', calories: 455, protein: 21, carbs: 63, fat: 12.3 },
    { name_en: 'Bulgogi', name_ar: 'بولغوغي', mealType: 'lunch', calories: 340, protein: 28, carbs: 20, fat: 16 },
    { name_en: 'Japchae', name_ar: 'جابتشي', mealType: 'lunch', calories: 300, protein: 10, carbs: 42.5, fat: 10 },
    { name_en: 'Gimbap', name_ar: 'غيمباب', mealType: 'lunch', calories: 375, protein: 12.5, carbs: 70, fat: 6.3 },
    { name_en: 'Doenjang Jjigae', name_ar: 'دوينجانغ جيغاي', mealType: 'dinner', calories: 224, protein: 14, carbs: 16.8, fat: 11.2 },
    { name_en: 'Samgyeopsal', name_ar: 'سامغيوبسال', mealType: 'dinner', calories: 660, protein: 34, carbs: 2, fat: 58 },
    { name_en: 'Galbi', name_ar: 'غالبي', mealType: 'dinner', calories: 700, protein: 57.5, carbs: 12.5, fat: 47.5 },
    { name_en: 'Yukgaejang', name_ar: 'يوكغايجانغ', mealType: 'dinner', calories: 336, protein: 28, carbs: 22.4, fat: 15.4 },
    { name_en: 'Tteokbokki', name_ar: 'تيوكبوكي', mealType: 'snack', calories: 400, protein: 10, carbs: 84, fat: 3 },
    { name_en: 'Kimchi Pancake', name_ar: 'فطيرة الكيمتشي', mealType: 'snack', calories: 341, protein: 9.6, carbs: 42, fat: 14.6 },
  ],
  japanese: [
    { name_en: 'Miso Soup', name_ar: 'حساء ميسو', mealType: 'breakfast', calories: 54, protein: 4.3, carbs: 7.2, fat: 1.8 },
    { name_en: 'Tamagoyaki', name_ar: 'تاماغوياكي', mealType: 'breakfast', calories: 150, protein: 11, carbs: 2, fat: 10 },
    { name_en: 'Okayu', name_ar: 'أوكايو', mealType: 'breakfast', calories: 125, protein: 3.8, carbs: 25, fat: 0.5 },
    { name_en: 'Natto Gohan', name_ar: 'ناتو غوهان', mealType: 'breakfast', calories: 450, protein: 22.5, carbs: 65, fat: 10 },
    { name_en: 'Sushi', name_ar: 'سوشي', mealType: 'lunch', calories: 225, protein: 10.5, carbs: 40.5, fat: 2.3 },
    { name_en: 'Ramen', name_ar: 'رامين', mealType: 'lunch', calories: 585, protein: 22.5, carbs: 81, fat: 15.8 },
    { name_en: 'Kare Raisu', name_ar: 'أرز بالكاري الياباني', mealType: 'lunch', calories: 520, protein: 24, carbs: 80, fat: 12 },
    { name_en: 'Teriyaki Salmon', name_ar: 'سلمون ترياكي', mealType: 'lunch', calories: 420, protein: 36, carbs: 24, fat: 18 },
    { name_en: 'Katsudon', name_ar: 'كاتسو دون', mealType: 'dinner', calories: 455, protein: 17.5, carbs: 63, fat: 12.3 },
    { name_en: 'Gyudon', name_ar: 'غيو دون', mealType: 'dinner', calories: 543, protein: 31.5, carbs: 59.5, fat: 17.5 },
    { name_en: 'Shabu-Shabu', name_ar: 'شابو شابو', mealType: 'dinner', calories: 480, protein: 42, carbs: 12, fat: 27 },
    { name_en: 'Tempura Udon', name_ar: 'أودون تيمبورا', mealType: 'dinner', calories: 480, protein: 16, carbs: 76, fat: 12 },
    { name_en: 'Onigiri', name_ar: 'أونيغيري', mealType: 'snack', calories: 170, protein: 4, carbs: 35, fat: 1 },
    { name_en: 'Mochi', name_ar: 'موتشي', mealType: 'snack', calories: 144, protein: 2.4, carbs: 33, fat: 0.3 },
  ],
  thai: [
    { name_en: 'Khao Tom', name_ar: 'خاو توم', mealType: 'breakfast', calories: 125, protein: 3.8, carbs: 25, fat: 0.5 },
    { name_en: 'Jok', name_ar: 'جوك', mealType: 'breakfast', calories: 325, protein: 12.5, carbs: 60, fat: 3.8 },
    { name_en: 'Kai Jeow', name_ar: 'كاي جيو', mealType: 'breakfast', calories: 450, protein: 25, carbs: 10, fat: 32.5 },
    { name_en: 'Pa Thong Ko', name_ar: 'با تونغ كو', mealType: 'breakfast', calories: 750, protein: 15, carbs: 112.5, fat: 27.5 },
    { name_en: 'Pad Thai', name_ar: 'باد تاي', mealType: 'lunch', calories: 375, protein: 15, carbs: 60, fat: 8.8 },
    { name_en: 'Green Curry', name_ar: 'كاري أخضر', mealType: 'lunch', calories: 280, protein: 24, carbs: 16, fat: 13 },
    { name_en: 'Tom Yum Goong', name_ar: 'توم يام غونغ', mealType: 'lunch', calories: 140, protein: 16, carbs: 12, fat: 4 },
    { name_en: 'Massaman Curry', name_ar: 'كاري ماسامان', mealType: 'lunch', calories: 375, protein: 25, carbs: 22.5, fat: 20 },
    { name_en: 'Pad Krapow', name_ar: 'باد كراباو', mealType: 'dinner', calories: 375, protein: 15, carbs: 60, fat: 8.8 },
    { name_en: 'Khao Soi', name_ar: 'خاو سوي', mealType: 'dinner', calories: 630, protein: 24.5, carbs: 63, fat: 31.5 },
    { name_en: 'Tom Kha Gai', name_ar: 'توم خا غاي', mealType: 'dinner', calories: 336, protein: 22.4, carbs: 16.8, fat: 22.4 },
    { name_en: 'Panang Curry', name_ar: 'كاري باناينغ', mealType: 'dinner', calories: 392, protein: 33.6, carbs: 22.4, fat: 18.2 },
    { name_en: 'Mango Sticky Rice', name_ar: 'أرز المانجو اللزج', mealType: 'snack', calories: 300, protein: 6, carbs: 60, fat: 5 },
    { name_en: 'Chicken Satay', name_ar: 'ساتاي دجاج', mealType: 'snack', calories: 150, protein: 14, carbs: 5, fat: 8 },
  ],
};