import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  indian: [
    { name_en: 'Masala Dosa', name_ar: 'دوسا ماسالا', mealType: 'breakfast', calories: 380, protein: 9, carbs: 58, fat: 12 },
    { name_en: 'Idli Sambar', name_ar: 'إدلي سامبار', mealType: 'breakfast', calories: 250, protein: 8, carbs: 45, fat: 5 },
    { name_en: 'Poha', name_ar: 'بوهة', mealType: 'breakfast', calories: 280, protein: 6, carbs: 50, fat: 7 },
    { name_en: 'Upma', name_ar: 'أوبما', mealType: 'breakfast', calories: 220, protein: 5, carbs: 38, fat: 6 },
    { name_en: 'Chicken Biryani', name_ar: 'بيرياني دجاج', mealType: 'lunch', calories: 520, protein: 26, carbs: 68, fat: 14 },
    { name_en: 'Butter Chicken', name_ar: 'دجاج بالزبدة', mealType: 'lunch', calories: 540, protein: 32, carbs: 15, fat: 38 },
    { name_en: 'Dal Makhani', name_ar: 'دال ماخاني', mealType: 'lunch', calories: 320, protein: 14, carbs: 42, fat: 11 },
    { name_en: 'Chana Masala', name_ar: 'شانا ماسالا', mealType: 'lunch', calories: 340, protein: 13, carbs: 48, fat: 11 },
    { name_en: 'Chicken Tikka Masala', name_ar: 'دجاج تيكا ماسالا', mealType: 'dinner', calories: 500, protein: 35, carbs: 15, fat: 34 },
    { name_en: 'Palak Paneer', name_ar: 'بالاك بانير', mealType: 'dinner', calories: 380, protein: 16, carbs: 14, fat: 30 },
    { name_en: 'Rogan Josh', name_ar: 'روغان جوش', mealType: 'dinner', calories: 450, protein: 34, carbs: 10, fat: 30 },
    { name_en: 'Vegetable Pulao', name_ar: 'بولاو خضار', mealType: 'dinner', calories: 320, protein: 6, carbs: 58, fat: 8 },
    { name_en: 'Samosa', name_ar: 'سمبوسة', mealType: 'snack', calories: 260, protein: 5, carbs: 25, fat: 15 },
    { name_en: 'Jalebi', name_ar: 'جاليبي', mealType: 'snack', calories: 200, protein: 2, carbs: 44, fat: 2 },
  ],
  pakistani: [
    { name_en: 'Nihari', name_ar: 'نيهاري', mealType: 'breakfast', calories: 390, protein: 28, carbs: 18, fat: 24 },
    { name_en: 'Halwa Puri', name_ar: 'حلوى بوري', mealType: 'breakfast', calories: 450, protein: 7, carbs: 60, fat: 20 },
    { name_en: 'Aloo Paratha', name_ar: 'ألو براتا', mealType: 'breakfast', calories: 320, protein: 7, carbs: 40, fat: 15 },
    { name_en: 'Anda Paratha', name_ar: 'أندا براتا', mealType: 'breakfast', calories: 380, protein: 12, carbs: 42, fat: 18 },
    { name_en: 'Chicken Karahi', name_ar: 'كراهي دجاج', mealType: 'lunch', calories: 420, protein: 34, carbs: 12, fat: 27 },
    { name_en: 'Chicken Biryani', name_ar: 'بيرياني دجاج', mealType: 'lunch', calories: 550, protein: 28, carbs: 70, fat: 16 },
    { name_en: 'Seekh Kebab', name_ar: 'كباب سيخ', mealType: 'lunch', calories: 490, protein: 26, carbs: 42, fat: 25 },
    { name_en: 'Haleem', name_ar: 'حليم', mealType: 'lunch', calories: 380, protein: 24, carbs: 36, fat: 16 },
    { name_en: 'Chicken Tikka', name_ar: 'تيكا دجاج', mealType: 'dinner', calories: 350, protein: 38, carbs: 6, fat: 18 },
    { name_en: 'Daal Chawal', name_ar: 'دال تشاوال', mealType: 'dinner', calories: 420, protein: 17, carbs: 72, fat: 7 },
    { name_en: 'Chapli Kebab', name_ar: 'كباب تشابلي', mealType: 'dinner', calories: 400, protein: 26, carbs: 18, fat: 26 },
    { name_en: 'Beef Karahi', name_ar: 'كراهي لحم', mealType: 'dinner', calories: 460, protein: 32, carbs: 12, fat: 31 },
    { name_en: 'Chana Chaat', name_ar: 'شانا شات', mealType: 'snack', calories: 230, protein: 8, carbs: 32, fat: 8 },
    { name_en: 'Gol Gappay', name_ar: 'جول جابي', mealType: 'snack', calories: 190, protein: 4, carbs: 28, fat: 7 },
  ],
  chinese: [
    { name_en: 'Congee', name_ar: 'كونغي', mealType: 'breakfast', calories: 210, protein: 6, carbs: 38, fat: 4 },
    { name_en: 'Jianbing', name_ar: 'جيانبينغ', mealType: 'breakfast', calories: 350, protein: 11, carbs: 42, fat: 15 },
    { name_en: 'Har Gow', name_ar: 'هار غاو', mealType: 'breakfast', calories: 180, protein: 8, carbs: 20, fat: 7 },
    { name_en: 'Scallion Pancake', name_ar: 'فطيرة البصل الأخضر', mealType: 'breakfast', calories: 280, protein: 6, carbs: 34, fat: 13 },
    { name_en: 'Kung Pao Chicken', name_ar: 'دجاج كونغ باو', mealType: 'lunch', calories: 390, protein: 30, carbs: 22, fat: 20 },
    { name_en: 'Beef Chow Fun', name_ar: 'تشاو فون باللحم', mealType: 'lunch', calories: 480, protein: 26, carbs: 58, fat: 16 },
    { name_en: 'Mapo Tofu', name_ar: 'مابو توفو', mealType: 'lunch', calories: 300, protein: 18, carbs: 14, fat: 19 },
    { name_en: 'Dan Dan Noodles', name_ar: 'نودلز دان دان', mealType: 'lunch', calories: 420, protein: 14, carbs: 52, fat: 17 },
    { name_en: 'Peking Duck', name_ar: 'بط بكين', mealType: 'dinner', calories: 500, protein: 34, carbs: 20, fat: 31 },
    { name_en: 'Wonton Noodle Soup', name_ar: 'حساء نودلز بالوانتون', mealType: 'dinner', calories: 340, protein: 20, carbs: 46, fat: 8 },
    { name_en: 'Yangzhou Fried Rice', name_ar: 'أرز يانغتشو المقلي', mealType: 'dinner', calories: 460, protein: 18, carbs: 66, fat: 13 },
    { name_en: 'Sichuan Eggplant', name_ar: 'باذنجان سيتشوان', mealType: 'dinner', calories: 330, protein: 7, carbs: 26, fat: 22 },
    { name_en: 'Spring Roll', name_ar: 'رول الربيع', mealType: 'snack', calories: 190, protein: 4, carbs: 22, fat: 9 },
    { name_en: 'Sesame Balls', name_ar: 'كرات السمسم', mealType: 'snack', calories: 210, protein: 3, carbs: 34, fat: 7 },
  ],
  korean: [
    { name_en: 'Juk', name_ar: 'جوك', mealType: 'breakfast', calories: 230, protein: 6, carbs: 44, fat: 3 },
    { name_en: 'Kimchi Jjigae', name_ar: 'كيمتشي جيغاي', mealType: 'breakfast', calories: 260, protein: 15, carbs: 16, fat: 15 },
    { name_en: 'Miyeokguk', name_ar: 'مياوك غوك', mealType: 'breakfast', calories: 150, protein: 10, carbs: 10, fat: 8 },
    { name_en: 'Gyeran Bap', name_ar: 'غيران باب', mealType: 'breakfast', calories: 320, protein: 13, carbs: 44, fat: 10 },
    { name_en: 'Bibimbap', name_ar: 'بيبيمباب', mealType: 'lunch', calories: 550, protein: 22, carbs: 78, fat: 16 },
    { name_en: 'Bulgogi', name_ar: 'بولغوغي', mealType: 'lunch', calories: 400, protein: 32, carbs: 16, fat: 24 },
    { name_en: 'Japchae', name_ar: 'جابتشي', mealType: 'lunch', calories: 330, protein: 8, carbs: 52, fat: 9 },
    { name_en: 'Gimbap', name_ar: 'غيمباب', mealType: 'lunch', calories: 350, protein: 12, carbs: 58, fat: 8 },
    { name_en: 'Doenjang Jjigae', name_ar: 'دوينجانغ جيغاي', mealType: 'dinner', calories: 180, protein: 13, carbs: 12, fat: 9 },
    { name_en: 'Samgyeopsal', name_ar: 'سامغيوبسال', mealType: 'dinner', calories: 520, protein: 28, carbs: 4, fat: 44 },
    { name_en: 'Galbi', name_ar: 'غالبي', mealType: 'dinner', calories: 480, protein: 32, carbs: 16, fat: 33 },
    { name_en: 'Yukgaejang', name_ar: 'يوكغايجانغ', mealType: 'dinner', calories: 280, protein: 24, carbs: 12, fat: 15 },
    { name_en: 'Tteokbokki', name_ar: 'تيوكبوكي', mealType: 'snack', calories: 290, protein: 6, carbs: 58, fat: 3 },
    { name_en: 'Kimchi Pancake', name_ar: 'فطيرة الكيمتشي', mealType: 'snack', calories: 250, protein: 8, carbs: 30, fat: 10 },
  ],
  japanese: [
    { name_en: 'Miso Soup', name_ar: 'حساء ميسو', mealType: 'breakfast', calories: 90, protein: 7, carbs: 8, fat: 3 },
    { name_en: 'Tamagoyaki', name_ar: 'تاماغوياكي', mealType: 'breakfast', calories: 190, protein: 14, carbs: 4, fat: 13 },
    { name_en: 'Okayu', name_ar: 'أوكايو', mealType: 'breakfast', calories: 160, protein: 4, carbs: 30, fat: 2 },
    { name_en: 'Natto Gohan', name_ar: 'ناتو غوهان', mealType: 'breakfast', calories: 280, protein: 13, carbs: 42, fat: 6 },
    { name_en: 'Sushi', name_ar: 'سوشي', mealType: 'lunch', calories: 450, protein: 22, carbs: 72, fat: 8 },
    { name_en: 'Ramen', name_ar: 'رامين', mealType: 'lunch', calories: 520, protein: 24, carbs: 64, fat: 18 },
    { name_en: 'Kare Raisu', name_ar: 'أرز بالكاري الياباني', mealType: 'lunch', calories: 620, protein: 24, carbs: 88, fat: 17 },
    { name_en: 'Teriyaki Salmon', name_ar: 'سلمون ترياكي', mealType: 'lunch', calories: 380, protein: 32, carbs: 22, fat: 17 },
    { name_en: 'Katsudon', name_ar: 'كاتسو دون', mealType: 'dinner', calories: 640, protein: 32, carbs: 80, fat: 18 },
    { name_en: 'Gyudon', name_ar: 'غيو دون', mealType: 'dinner', calories: 600, protein: 24, carbs: 66, fat: 26 },
    { name_en: 'Shabu-Shabu', name_ar: 'شابو شابو', mealType: 'dinner', calories: 420, protein: 28, carbs: 20, fat: 26 },
    { name_en: 'Tempura Udon', name_ar: 'أودون تيمبورا', mealType: 'dinner', calories: 480, protein: 16, carbs: 70, fat: 13 },
    { name_en: 'Onigiri', name_ar: 'أونيغيري', mealType: 'snack', calories: 200, protein: 6, carbs: 38, fat: 3 },
    { name_en: 'Mochi', name_ar: 'موتشي', mealType: 'snack', calories: 180, protein: 3, carbs: 38, fat: 1 },
  ],
  thai: [
    { name_en: 'Khao Tom', name_ar: 'خاو توم', mealType: 'breakfast', calories: 180, protein: 7, carbs: 30, fat: 4 },
    { name_en: 'Jok', name_ar: 'جوك', mealType: 'breakfast', calories: 220, protein: 15, carbs: 28, fat: 5 },
    { name_en: 'Kai Jeow', name_ar: 'كاي جيو', mealType: 'breakfast', calories: 340, protein: 18, carbs: 40, fat: 12 },
    { name_en: 'Pa Thong Ko', name_ar: 'با تونغ كو', mealType: 'breakfast', calories: 190, protein: 4, carbs: 28, fat: 7 },
    { name_en: 'Pad Thai', name_ar: 'باد تاي', mealType: 'lunch', calories: 480, protein: 18, carbs: 62, fat: 17 },
    { name_en: 'Green Curry', name_ar: 'كاري أخضر', mealType: 'lunch', calories: 430, protein: 28, carbs: 14, fat: 29 },
    { name_en: 'Tom Yum Goong', name_ar: 'توم يام غونغ', mealType: 'lunch', calories: 160, protein: 18, carbs: 9, fat: 5 },
    { name_en: 'Massaman Curry', name_ar: 'كاري ماسامان', mealType: 'lunch', calories: 480, protein: 26, carbs: 26, fat: 30 },
    { name_en: 'Pad Krapow', name_ar: 'باد كراباو', mealType: 'dinner', calories: 460, protein: 28, carbs: 38, fat: 22 },
    { name_en: 'Khao Soi', name_ar: 'خاو سوي', mealType: 'dinner', calories: 540, protein: 22, carbs: 54, fat: 26 },
    { name_en: 'Tom Kha Gai', name_ar: 'توم خا غاي', mealType: 'dinner', calories: 240, protein: 18, carbs: 12, fat: 13 },
    { name_en: 'Panang Curry', name_ar: 'كاري باناينغ', mealType: 'dinner', calories: 420, protein: 26, carbs: 12, fat: 29 },
    { name_en: 'Mango Sticky Rice', name_ar: 'أرز المانجو اللزج', mealType: 'snack', calories: 500, protein: 8, carbs: 88, fat: 13 },
    { name_en: 'Chicken Satay', name_ar: 'ساتاي دجاج', mealType: 'snack', calories: 260, protein: 32, carbs: 8, fat: 11 },
  ],
};