import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  italian: [
    { name_en: 'Italian Frittata', name_ar: 'فريتاتا إيطالية', mealType: 'breakfast', calories: 310, protein: 18, carbs: 8, fat: 23 },
    { name_en: 'Cornetto with Jam', name_ar: 'كورنيتو بالمربى', mealType: 'breakfast', calories: 250, protein: 6, carbs: 38, fat: 8 },
    { name_en: 'Ricotta with Honey and Berries', name_ar: 'ريكوتا بالعسل والتوت', mealType: 'breakfast', calories: 220, protein: 12, carbs: 24, fat: 8 },
    { name_en: 'Biscotti with Coffee', name_ar: 'بسكوتي بالقهوة', mealType: 'breakfast', calories: 180, protein: 4, carbs: 30, fat: 5 },
    { name_en: 'Pizza Margherita', name_ar: 'بيتزا مارغريتا', mealType: 'lunch', calories: 660, protein: 28, carbs: 90, fat: 20 },
    { name_en: 'Spaghetti Carbonara', name_ar: 'سباغيتي كاربونارا', mealType: 'lunch', calories: 620, protein: 24, carbs: 72, fat: 26 },
    { name_en: 'Caprese Salad', name_ar: 'سلطة كابريزي', mealType: 'lunch', calories: 280, protein: 14, carbs: 10, fat: 20 },
    { name_en: 'Minestrone Soup', name_ar: 'حساء مينيستروني', mealType: 'lunch', calories: 180, protein: 8, carbs: 24, fat: 6 },
    { name_en: 'Lasagna alla Bolognese', name_ar: 'لازانيا بولونيز', mealType: 'dinner', calories: 540, protein: 30, carbs: 48, fat: 22 },
    { name_en: 'Risotto ai Funghi', name_ar: 'ريزوتو بالفطر', mealType: 'dinner', calories: 430, protein: 12, carbs: 62, fat: 14 },
    { name_en: 'Chicken Parmigiana', name_ar: 'دجاج بارميجيانا', mealType: 'dinner', calories: 520, protein: 42, carbs: 30, fat: 24 },
    { name_en: 'Cotoletta alla Milanese', name_ar: 'كوتوليتا ميلانية', mealType: 'dinner', calories: 460, protein: 34, carbs: 26, fat: 23 },
    { name_en: 'Tiramisu', name_ar: 'تيراميسو', mealType: 'snack', calories: 380, protein: 6, carbs: 42, fat: 21 },
    { name_en: 'Gelato', name_ar: 'جيلاتي', mealType: 'snack', calories: 210, protein: 4, carbs: 28, fat: 9 },
  ],
  french: [
    { name_en: 'Butter Croissant', name_ar: 'كورواسون بالزبدة', mealType: 'breakfast', calories: 260, protein: 5, carbs: 30, fat: 14 },
    { name_en: 'Pain Perdu', name_ar: 'بان بيردو الفرنسي', mealType: 'breakfast', calories: 380, protein: 12, carbs: 48, fat: 15 },
    { name_en: 'Tartine with Jam', name_ar: 'ترتين بالمربى', mealType: 'breakfast', calories: 240, protein: 6, carbs: 40, fat: 6 },
    { name_en: 'Pain au Chocolat', name_ar: 'بان أو شوكولا', mealType: 'breakfast', calories: 290, protein: 6, carbs: 34, fat: 14 },
    { name_en: 'Croque Monsieur', name_ar: 'كروك مسيو', mealType: 'lunch', calories: 520, protein: 28, carbs: 34, fat: 28 },
    { name_en: 'Quiche Lorraine', name_ar: 'كيش لورين', mealType: 'lunch', calories: 470, protein: 20, carbs: 30, fat: 28 },
    { name_en: 'Ratatouille', name_ar: 'راتاتوي', mealType: 'lunch', calories: 230, protein: 6, carbs: 32, fat: 9 },
    { name_en: 'French Onion Soup', name_ar: 'حساء البصل الفرنسي', mealType: 'lunch', calories: 280, protein: 10, carbs: 34, fat: 11 },
    { name_en: 'Coq au Vin', name_ar: 'كوك أو فان', mealType: 'dinner', calories: 560, protein: 40, carbs: 20, fat: 30 },
    { name_en: 'Beef Bourguignon', name_ar: 'لحم بقري بورغينيون', mealType: 'dinner', calories: 610, protein: 44, carbs: 18, fat: 36 },
    { name_en: 'Duck à l’Orange', name_ar: 'بط بالبرتقال', mealType: 'dinner', calories: 540, protein: 36, carbs: 28, fat: 28 },
    { name_en: 'Steak Frites', name_ar: 'ستيك ببطاطا مقلية', mealType: 'dinner', calories: 700, protein: 40, carbs: 50, fat: 36 },
    { name_en: 'Crêpes with Sugar', name_ar: 'كريب بالسكر', mealType: 'snack', calories: 240, protein: 6, carbs: 34, fat: 9 },
    { name_en: 'Macaron', name_ar: 'ماكارون', mealType: 'snack', calories: 90, protein: 1, carbs: 12, fat: 4 },
  ],
  spanish: [
    { name_en: 'Tortilla Española', name_ar: 'تورتيلا إسبانية', mealType: 'breakfast', calories: 320, protein: 13, carbs: 20, fat: 21 },
    { name_en: 'Pan con Tomate', name_ar: 'خبز بالطماطم', mealType: 'breakfast', calories: 180, protein: 5, carbs: 24, fat: 7 },
    { name_en: 'Churros con Chocolate', name_ar: 'تشوروس بالشوكولاتة', mealType: 'breakfast', calories: 400, protein: 6, carbs: 50, fat: 19 },
    { name_en: 'Tostada con Aceite y Jamón', name_ar: 'توستادا بالزيت ولحم الخنزير', mealType: 'breakfast', calories: 260, protein: 12, carbs: 24, fat: 13 },
    { name_en: 'Paella Valenciana', name_ar: 'باييا فالنسية', mealType: 'lunch', calories: 620, protein: 30, carbs: 78, fat: 18 },
    { name_en: 'Gazpacho', name_ar: 'غازباتشو', mealType: 'lunch', calories: 160, protein: 4, carbs: 20, fat: 7 },
    { name_en: 'Fabada Asturiana', name_ar: 'فابادا أستورية', mealType: 'lunch', calories: 680, protein: 38, carbs: 58, fat: 32 },
    { name_en: 'Pulpo a la Gallega', name_ar: 'بولبو لا غاييغا', mealType: 'lunch', calories: 280, protein: 34, carbs: 14, fat: 10 },
    { name_en: 'Pollo al Ajillo', name_ar: 'دجاج بالثوم', mealType: 'dinner', calories: 420, protein: 36, carbs: 8, fat: 26 },
    { name_en: 'Cocido Madrileño', name_ar: 'كوسيدو مدريد', mealType: 'dinner', calories: 640, protein: 40, carbs: 56, fat: 28 },
    { name_en: 'Bacalao a la Vizcaína', name_ar: 'بكالاو بصلصة البيسكاي', mealType: 'dinner', calories: 460, protein: 38, carbs: 22, fat: 24 },
    { name_en: 'Zarzuela de Pescado', name_ar: 'زارزويلا دي بسكادو', mealType: 'dinner', calories: 520, protein: 40, carbs: 30, fat: 24 },
    { name_en: 'Patatas Bravas', name_ar: 'بطاطا برافاس', mealType: 'snack', calories: 340, protein: 5, carbs: 34, fat: 20 },
    { name_en: 'Turrón de Jijona', name_ar: 'تورون دي خيخونا', mealType: 'snack', calories: 210, protein: 6, carbs: 24, fat: 10 },
  ],
  greek: [
    { name_en: 'Greek Yogurt with Honey and Walnuts', name_ar: 'زبادي يوناني بالعسل والجوز', mealType: 'breakfast', calories: 290, protein: 16, carbs: 22, fat: 16 },
    { name_en: 'Spanakopita', name_ar: 'سباناكوبيتا', mealType: 'breakfast', calories: 380, protein: 12, carbs: 28, fat: 24 },
    { name_en: 'Koulouri', name_ar: 'كولوري', mealType: 'breakfast', calories: 240, protein: 7, carbs: 40, fat: 6 },
    { name_en: 'Bougatsa', name_ar: 'بوجاتسا', mealType: 'breakfast', calories: 340, protein: 8, carbs: 40, fat: 16 },
    { name_en: 'Greek Salad', name_ar: 'سلطة يونانية', mealType: 'lunch', calories: 260, protein: 8, carbs: 10, fat: 21 },
    { name_en: 'Moussaka', name_ar: 'موساكا', mealType: 'lunch', calories: 540, protein: 24, carbs: 30, fat: 36 },
    { name_en: 'Souvlaki Wrap', name_ar: 'سوفلاكي', mealType: 'lunch', calories: 500, protein: 28, carbs: 46, fat: 22 },
    { name_en: 'Gemista', name_ar: 'جمستا', mealType: 'lunch', calories: 280, protein: 8, carbs: 38, fat: 11 },
    { name_en: 'Pastitsio', name_ar: 'باستيتسيو', mealType: 'dinner', calories: 560, protein: 28, carbs: 52, fat: 26 },
    { name_en: 'Keftedes', name_ar: 'كيفتيديس', mealType: 'dinner', calories: 420, protein: 28, carbs: 18, fat: 26 },
    { name_en: 'Stifado', name_ar: 'ستيفادو', mealType: 'dinner', calories: 480, protein: 40, carbs: 22, fat: 24 },
    { name_en: 'Grilled Octopus', name_ar: 'أخطبوط مشوي', mealType: 'dinner', calories: 320, protein: 38, carbs: 16, fat: 12 },
    { name_en: 'Baklava', name_ar: 'بقلاوة', mealType: 'snack', calories: 380, protein: 6, carbs: 38, fat: 22 },
    { name_en: 'Loukoumades', name_ar: 'لقيمات يونانية', mealType: 'snack', calories: 300, protein: 5, carbs: 44, fat: 12 },
  ],
  turkish: [
    { name_en: 'Menemen', name_ar: 'مينيمين', mealType: 'breakfast', calories: 260, protein: 13, carbs: 10, fat: 18 },
    { name_en: 'Simit', name_ar: 'سيميت', mealType: 'breakfast', calories: 230, protein: 7, carbs: 40, fat: 5 },
    { name_en: 'Cheese Börek', name_ar: 'بوريك بالجبن', mealType: 'breakfast', calories: 320, protein: 12, carbs: 34, fat: 15 },
    { name_en: 'Sucuklu Yumurta', name_ar: 'بيض بالسجق التركي', mealType: 'breakfast', calories: 340, protein: 20, carbs: 6, fat: 26 },
    { name_en: 'İskender Kebab', name_ar: 'إسكندر كباب', mealType: 'lunch', calories: 640, protein: 36, carbs: 44, fat: 34 },
    { name_en: 'Döner', name_ar: 'دونر', mealType: 'lunch', calories: 580, protein: 34, carbs: 48, fat: 28 },
    { name_en: 'Mercimek Çorbası', name_ar: 'شوربة العدس التركية', mealType: 'lunch', calories: 220, protein: 12, carbs: 30, fat: 6 },
    { name_en: 'Lahmacun', name_ar: 'لاكماچون', mealType: 'lunch', calories: 420, protein: 22, carbs: 46, fat: 16 },
    { name_en: 'Adana Kebab', name_ar: 'كباب أضنة', mealType: 'dinner', calories: 560, protein: 38, carbs: 24, fat: 32 },
    { name_en: 'Tandır Kebab', name_ar: 'كباب تندور', mealType: 'dinner', calories: 600, protein: 40, carbs: 18, fat: 38 },
    { name_en: 'Peynirli Pide', name_ar: 'بيدي بالجبن', mealType: 'dinner', calories: 540, protein: 24, carbs: 58, fat: 22 },
    { name_en: 'Imam Bayildi', name_ar: 'إمام بايلدي', mealType: 'dinner', calories: 280, protein: 6, carbs: 30, fat: 15 },
    { name_en: 'Künefe', name_ar: 'كنافة تركية', mealType: 'snack', calories: 480, protein: 10, carbs: 60, fat: 22 },
    { name_en: 'Turkish Delight', name_ar: 'راحة الحلقوم', mealType: 'snack', calories: 160, protein: 1, carbs: 38, fat: 1 },
  ],
  german: [
    { name_en: 'Muesli with Yogurt', name_ar: 'مويسلي بالزبادي', mealType: 'breakfast', calories: 320, protein: 12, carbs: 48, fat: 9 },
    { name_en: 'Bauernfrühstück', name_ar: 'باورنفروشتاك', mealType: 'breakfast', calories: 420, protein: 22, carbs: 30, fat: 23 },
    { name_en: 'Brötchen with Cheese and Cold Cuts', name_ar: 'خبز صغير بالجبن واللحوم الباردة', mealType: 'breakfast', calories: 400, protein: 18, carbs: 42, fat: 17 },
    { name_en: 'Quark with Berries', name_ar: 'كفارك بالتوت', mealType: 'breakfast', calories: 230, protein: 16, carbs: 26, fat: 6 },
    { name_en: 'Bratwurst with Sauerkraut', name_ar: 'نقانق براتفورست مع مخلل الملفوف', mealType: 'lunch', calories: 520, protein: 26, carbs: 26, fat: 34 },
    { name_en: 'Currywurst', name_ar: 'كاري فورست', mealType: 'lunch', calories: 470, protein: 20, carbs: 44, fat: 24 },
    { name_en: 'Frankfurter with Potato Salad', name_ar: 'نقانق فرانكفورت مع سلطة البطاطا', mealType: 'lunch', calories: 560, protein: 24, carbs: 44, fat: 30 },
    { name_en: 'Käsespätzle', name_ar: 'كايز سباتزلي', mealType: 'lunch', calories: 640, protein: 26, carbs: 62, fat: 30 },
    { name_en: 'Wiener Schnitzel', name_ar: 'شنيتزل', mealType: 'dinner', calories: 640, protein: 38, carbs: 44, fat: 32 },
    { name_en: 'Sauerbraten', name_ar: 'زاوربراتن', mealType: 'dinner', calories: 650, protein: 46, carbs: 30, fat: 34 },
    { name_en: 'Rouladen', name_ar: 'رولادين', mealType: 'dinner', calories: 540, protein: 38, carbs: 24, fat: 30 },
    { name_en: 'Eisbein with Sauerkraut', name_ar: 'أيسباين مع مخلل الملفوف', mealType: 'dinner', calories: 720, protein: 48, carbs: 30, fat: 42 },
    { name_en: 'Bavarian Pretzel', name_ar: 'برتزل بافاري', mealType: 'snack', calories: 280, protein: 9, carbs: 52, fat: 3 },
    { name_en: 'Apfelstrudel', name_ar: 'فطيرة التفاح الألمانية', mealType: 'snack', calories: 380, protein: 5, carbs: 52, fat: 16 },
  ],
};