import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  italian: [
    { name_en: 'Italian Frittata', name_ar: 'فريتاتا إيطالية', mealType: 'breakfast', calories: 270, protein: 19.8, carbs: 5.4, fat: 18 },
    { name_en: 'Cornetto with Jam', name_ar: 'كورنيتو بالمربى', mealType: 'breakfast', calories: 288, protein: 6.3, carbs: 41.4, fat: 10.8 },
    { name_en: 'Ricotta with Honey and Berries', name_ar: 'ريكوتا بالعسل والتوت', mealType: 'breakfast', calories: 450, protein: 17.5, carbs: 55, fat: 17.5 },
    { name_en: 'Biscotti with Coffee', name_ar: 'بسكوتي بالقهوة', mealType: 'breakfast', calories: 550, protein: 17.5, carbs: 95, fat: 12.5 },
    { name_en: 'Pizza Margherita', name_ar: 'بيتزا مارغريتا', mealType: 'lunch', calories: 399, protein: 16.5, carbs: 49.5, fat: 14.7 },
    { name_en: 'Spaghetti Carbonara', name_ar: 'سباغيتي كاربونارا', mealType: 'lunch', calories: 660, protein: 26, carbs: 60, fat: 36 },
    { name_en: 'Caprese Salad', name_ar: 'سلطة كابريزي', mealType: 'lunch', calories: 320, protein: 14, carbs: 8, fat: 26 },
    { name_en: 'Minestrone Soup', name_ar: 'حساء مينيستروني', mealType: 'lunch', calories: 150, protein: 7.5, carbs: 25, fat: 2.5 },
    { name_en: 'Lasagna alla Bolognese', name_ar: 'لازانيا بولونيز', mealType: 'dinner', calories: 450, protein: 24, carbs: 46, fat: 20 },
    { name_en: 'Risotto ai Funghi', name_ar: 'ريزوتو بالفطر', mealType: 'dinner', calories: 325, protein: 8.8, carbs: 52.5, fat: 8.8 },
    { name_en: 'Chicken Parmigiana', name_ar: 'دجاج بارميجيانا', mealType: 'dinner', calories: 550, protein: 40, carbs: 35, fat: 27.5 },
    { name_en: 'Cotoletta alla Milanese', name_ar: 'كوتوليتا ميلانية', mealType: 'dinner', calories: 625, protein: 42.5, carbs: 37.5, fat: 32.5 },
    { name_en: 'Tiramisu', name_ar: 'تيراميسو', mealType: 'snack', calories: 318, protein: 6, carbs: 28.8, fat: 20.4 },
    { name_en: 'Gelato', name_ar: 'جيلاتي', mealType: 'snack', calories: 210, protein: 3.6, carbs: 25, fat: 11 },
  ],
  french: [
    { name_en: 'Butter Croissant', name_ar: 'كورواسون بالزبدة', mealType: 'breakfast', calories: 244, protein: 4.9, carbs: 27.5, fat: 12.6 },
    { name_en: 'Pain Perdu', name_ar: 'بان بيردو الفرنسي', mealType: 'breakfast', calories: 573, protein: 19.3, carbs: 70, fat: 27 },
    { name_en: 'Tartine with Jam', name_ar: 'ترتين بالمربى', mealType: 'breakfast', calories: 500, protein: 12.5, carbs: 90, fat: 12.5 },
    { name_en: 'Pain au Chocolat', name_ar: 'بان أو شوكولا', mealType: 'breakfast', calories: 331, protein: 6.4, carbs: 39.2, fat: 16.8 },
    { name_en: 'Croque Monsieur', name_ar: 'كروك مسيو', mealType: 'lunch', calories: 750, protein: 39, carbs: 60, fat: 39 },
    { name_en: 'Quiche Lorraine', name_ar: 'كيش لورين', mealType: 'lunch', calories: 428, protein: 16.5, carbs: 27, fat: 27 },
    { name_en: 'Ratatouille', name_ar: 'راتاتوي', mealType: 'lunch', calories: 216, protein: 5.1, carbs: 24, fat: 11.7 },
    { name_en: 'French Onion Soup', name_ar: 'حساء البصل الفرنسي', mealType: 'lunch', calories: 98, protein: 4.5, carbs: 12, fat: 3.3 },
    { name_en: 'Coq au Vin', name_ar: 'كوك أو فان', mealType: 'dinner', calories: 450, protein: 54, carbs: 12, fat: 18 },
    { name_en: 'Beef Bourguignon', name_ar: 'لحم بقري بورغينيون', mealType: 'dinner', calories: 480, protein: 54, carbs: 15, fat: 21 },
    { name_en: 'Duck à l’Orange', name_ar: 'بط بالبرتقال', mealType: 'dinner', calories: 540, protein: 36, carbs: 28, fat: 28 },
    { name_en: 'Steak Frites', name_ar: 'ستيك ببطاطا مقلية', mealType: 'dinner', calories: 700, protein: 63, carbs: 52.5, fat: 24.5 },
    { name_en: 'Crêpes with Sugar', name_ar: 'كريب بالسكر', mealType: 'snack', calories: 240, protein: 6, carbs: 34, fat: 9 },
    { name_en: 'Macaron', name_ar: 'ماكارون', mealType: 'snack', calories: 76, protein: 0.9, carbs: 11, fat: 3.2 },
  ],
  spanish: [
    { name_en: 'Tortilla Española', name_ar: 'تورتيلا إسبانية', mealType: 'breakfast', calories: 320, protein: 13, carbs: 20, fat: 21 },
    { name_en: 'Pan con Tomate', name_ar: 'خبز بالطماطم', mealType: 'breakfast', calories: 300, protein: 7.5, carbs: 50, fat: 7.5 },
    { name_en: 'Churros con Chocolate', name_ar: 'تشوروس بالشوكولاتة', mealType: 'breakfast', calories: 360, protein: 5, carbs: 50, fat: 15 },
    { name_en: 'Tostada con Aceite y Jamón', name_ar: 'توستادا بالزيت ولحم الخنزير', mealType: 'breakfast', calories: 260, protein: 12, carbs: 24, fat: 13 },
    { name_en: 'Paella Valenciana', name_ar: 'باييا فالنسية', mealType: 'lunch', calories: 455, protein: 24.5, carbs: 59.5, fat: 10.5 },
    { name_en: 'Gazpacho', name_ar: 'غازباتشو', mealType: 'lunch', calories: 75, protein: 2.3, carbs: 12.5, fat: 2.3 },
    { name_en: 'Fabada Asturiana', name_ar: 'فابادا أستورية', mealType: 'lunch', calories: 510, protein: 27, carbs: 45, fat: 24 },
    { name_en: 'Pulpo a la Gallega', name_ar: 'بولبو لا غاييغا', mealType: 'lunch', calories: 360, protein: 60, carbs: 15, fat: 7.5 },
    { name_en: 'Pollo al Ajillo', name_ar: 'دجاج بالثوم', mealType: 'dinner', calories: 532, protein: 50.4, carbs: 11.2, fat: 30.8 },
    { name_en: 'Cocido Madrileño', name_ar: 'كوسيدو مدريد', mealType: 'dinner', calories: 640, protein: 40, carbs: 56, fat: 28 },
    { name_en: 'Bacalao a la Vizcaína', name_ar: 'بكالاو بصلصة البيسكاي', mealType: 'dinner', calories: 460, protein: 38, carbs: 22, fat: 24 },
    { name_en: 'Zarzuela de Pescado', name_ar: 'زارزويلا دي بسكادو', mealType: 'dinner', calories: 308, protein: 36.4, carbs: 16.8, fat: 9.8 },
    { name_en: 'Patatas Bravas', name_ar: 'بطاطا برافاس', mealType: 'snack', calories: 300, protein: 5, carbs: 36, fat: 15 },
    { name_en: 'Turrón de Jijona', name_ar: 'تورون دي خيخونا', mealType: 'snack', calories: 210, protein: 6, carbs: 24, fat: 10 },
  ],
  greek: [
    { name_en: 'Greek Yogurt with Honey and Walnuts', name_ar: 'زبادي يوناني بالعسل والجوز', mealType: 'breakfast', calories: 260, protein: 16, carbs: 24, fat: 11 },
    { name_en: 'Spanakopita', name_ar: 'سباناكوبيتا', mealType: 'breakfast', calories: 368, protein: 7.5, carbs: 25.5, fat: 25.5 },
    { name_en: 'Koulouri', name_ar: 'كولوري', mealType: 'breakfast', calories: 750, protein: 22.5, carbs: 130, fat: 17.5 },
    { name_en: 'Bougatsa', name_ar: 'بوجاتسا', mealType: 'breakfast', calories: 700, protein: 17.5, carbs: 90, fat: 30 },
    { name_en: 'Greek Salad', name_ar: 'سلطة يونانية', mealType: 'lunch', calories: 260, protein: 6, carbs: 10, fat: 22 },
    { name_en: 'Moussaka', name_ar: 'موساكا', mealType: 'lunch', calories: 388, protein: 22.5, carbs: 22.5, fat: 22.5 },
    { name_en: 'Souvlaki Wrap', name_ar: 'سوفلاكي', mealType: 'lunch', calories: 550, protein: 35, carbs: 55, fat: 21.3 },
    { name_en: 'Gemista', name_ar: 'جمستا', mealType: 'lunch', calories: 330, protein: 9, carbs: 42, fat: 12 },
    { name_en: 'Pastitsio', name_ar: 'باستيتسيو', mealType: 'dinner', calories: 475, protein: 25, carbs: 45, fat: 22.5 },
    { name_en: 'Keftedes', name_ar: 'كيفتيديس', mealType: 'dinner', calories: 400, protein: 34, carbs: 8, fat: 24 },
    { name_en: 'Stifado', name_ar: 'ستيفادو', mealType: 'dinner', calories: 448, protein: 44.8, carbs: 16.8, fat: 22.4 },
    { name_en: 'Grilled Octopus', name_ar: 'أخطبوط مشوي', mealType: 'dinner', calories: 459, protein: 84, carbs: 11.2, fat: 7 },
    { name_en: 'Baklava', name_ar: 'بقلاوة', mealType: 'snack', calories: 342, protein: 4.8, carbs: 33.6, fat: 20.8 },
    { name_en: 'Loukoumades', name_ar: 'لقيمات يونانية', mealType: 'snack', calories: 186, protein: 3, carbs: 27.6, fat: 7.2 },
  ],
  turkish: [
    { name_en: 'Menemen', name_ar: 'مينيمين', mealType: 'breakfast', calories: 300, protein: 17.5, carbs: 17.5, fat: 17.5 },
    { name_en: 'Simit', name_ar: 'سيميت', mealType: 'breakfast', calories: 280, protein: 9, carbs: 50, fat: 5 },
    { name_en: 'Cheese Börek', name_ar: 'بوريك بالجبن', mealType: 'breakfast', calories: 320, protein: 12, carbs: 34, fat: 15 },
    { name_en: 'Sucuklu Yumurta', name_ar: 'بيض بالسجق التركي', mealType: 'breakfast', calories: 550, protein: 27.5, carbs: 10, fat: 45 },
    { name_en: 'İskender Kebab', name_ar: 'إسكندر كباب', mealType: 'lunch', calories: 640, protein: 36, carbs: 44, fat: 34 },
    { name_en: 'Döner', name_ar: 'دونر', mealType: 'lunch', calories: 580, protein: 34, carbs: 48, fat: 28 },
    { name_en: 'Mercimek Çorbası', name_ar: 'شوربة العدس التركية', mealType: 'lunch', calories: 220, protein: 12, carbs: 30, fat: 6 },
    { name_en: 'Lahmacun', name_ar: 'لاكماچون', mealType: 'lunch', calories: 345, protein: 13.5, carbs: 45, fat: 12 },
    { name_en: 'Adana Kebab', name_ar: 'كباب أضنة', mealType: 'dinner', calories: 690, protein: 51, carbs: 9, fat: 51 },
    { name_en: 'Tandır Kebab', name_ar: 'كباب تندور', mealType: 'dinner', calories: 600, protein: 40, carbs: 18, fat: 38 },
    { name_en: 'Peynirli Pide', name_ar: 'بيدي بالجبن', mealType: 'dinner', calories: 675, protein: 25, carbs: 80, fat: 27.5 },
    { name_en: 'Imam Bayildi', name_ar: 'إمام بايلدي', mealType: 'dinner', calories: 252, protein: 5.6, carbs: 22.4, fat: 16.8 },
    { name_en: 'Künefe', name_ar: 'كنافة تركية', mealType: 'snack', calories: 480, protein: 10, carbs: 60, fat: 22 },
    { name_en: 'Turkish Delight', name_ar: 'راحة الحلقوم', mealType: 'snack', calories: 128, protein: 0.3, carbs: 31.2, fat: 0.3 },
  ],
  german: [
    { name_en: 'Muesli with Yogurt', name_ar: 'مويسلي بالزبادي', mealType: 'breakfast', calories: 400, protein: 17.5, carbs: 50, fat: 12.5 },
    { name_en: 'Bauernfrühstück', name_ar: 'باورنفروشتاك', mealType: 'breakfast', calories: 420, protein: 22, carbs: 30, fat: 23 },
    { name_en: 'Brötchen with Cheese and Cold Cuts', name_ar: 'خبز صغير بالجبن واللحوم الباردة', mealType: 'breakfast', calories: 400, protein: 18, carbs: 42, fat: 17 },
    { name_en: 'Quark with Berries', name_ar: 'كفارك بالتوت', mealType: 'breakfast', calories: 275, protein: 30, carbs: 25, fat: 5 },
    { name_en: 'Bratwurst with Sauerkraut', name_ar: 'نقانق براتفورست مع مخلل الملفوف', mealType: 'lunch', calories: 625, protein: 32.5, carbs: 11.3, fat: 50 },
    { name_en: 'Currywurst', name_ar: 'كاري فورست', mealType: 'lunch', calories: 690, protein: 36, carbs: 24, fat: 48 },
    { name_en: 'Frankfurter with Potato Salad', name_ar: 'نقانق فرانكفورت مع سلطة البطاطا', mealType: 'lunch', calories: 660, protein: 27, carbs: 42, fat: 42 },
    { name_en: 'Käsespätzle', name_ar: 'كايز سباتزلي', mealType: 'lunch', calories: 640, protein: 26, carbs: 62, fat: 30 },
    { name_en: 'Wiener Schnitzel', name_ar: 'شنيتزل', mealType: 'dinner', calories: 625, protein: 55, carbs: 20, fat: 35 },
    { name_en: 'Sauerbraten', name_ar: 'زاوربراتن', mealType: 'dinner', calories: 532, protein: 61.6, carbs: 11.2, fat: 28 },
    { name_en: 'Rouladen', name_ar: 'رولادين', mealType: 'dinner', calories: 504, protein: 56, carbs: 11.2, fat: 25.2 },
    { name_en: 'Eisbein with Sauerkraut', name_ar: 'أيسباين مع مخلل الملفوف', mealType: 'dinner', calories: 644, protein: 61.6, carbs: 11.2, fat: 42 },
    { name_en: 'Bavarian Pretzel', name_ar: 'برتزل بافاري', mealType: 'snack', calories: 379, protein: 9.3, carbs: 79.6, fat: 4 },
    { name_en: 'Apfelstrudel', name_ar: 'فطيرة التفاح الألمانية', mealType: 'snack', calories: 270, protein: 4.5, carbs: 36, fat: 12 },
  ],
};