import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  saudi: [
    { name_en: 'Saleeg with Chicken', name_ar: 'سليق بالدجاج', mealType: 'breakfast', calories: 450, protein: 22, carbs: 52, fat: 17 },
    { name_en: 'Ful Medames with Olive Oil', name_ar: 'فول مدمس بزيت الزيتون', mealType: 'breakfast', calories: 240, protein: 15, carbs: 32, fat: 6 },
    { name_en: 'Regag Bread with Cheese', name_ar: 'رقاق بالجبن', mealType: 'breakfast', calories: 260, protein: 11, carbs: 34, fat: 9 },
    { name_en: 'Tamis Bread with Egg', name_ar: 'تميس بالبيض', mealType: 'breakfast', calories: 220, protein: 9, carbs: 32, fat: 6 },
    { name_en: 'Saudi Kabsa with Chicken', name_ar: 'كبسة دجاج سعودية', mealType: 'lunch', calories: 580, protein: 34, carbs: 78, fat: 14 },
    { name_en: 'Madfoon with Lamb', name_ar: 'مدفون لحم', mealType: 'lunch', calories: 560, protein: 30, carbs: 55, fat: 23 },
    { name_en: 'Matazeez with Lamb', name_ar: 'مطازيز لحم', mealType: 'lunch', calories: 420, protein: 22, carbs: 58, fat: 11 },
    { name_en: 'Harees', name_ar: 'هريس', mealType: 'lunch', calories: 320, protein: 16, carbs: 46, fat: 8 },
    { name_en: 'Jareesh (Crushed Wheat)', name_ar: 'جريش', mealType: 'dinner', calories: 340, protein: 16, carbs: 52, fat: 8 },
    { name_en: 'Thareed with Lamb', name_ar: 'ثريد لحم', mealType: 'dinner', calories: 380, protein: 20, carbs: 50, fat: 11 },
    { name_en: 'Qursan with Chicken', name_ar: 'قرصان دجاج', mealType: 'dinner', calories: 350, protein: 14, carbs: 58, fat: 7 },
    { name_en: 'Margoog (Vegetable Stew)', name_ar: 'مرقوق', mealType: 'dinner', calories: 330, protein: 18, carbs: 44, fat: 9 },
    { name_en: 'Motabbaq', name_ar: 'مطبق', mealType: 'snack', calories: 300, protein: 8, carbs: 34, fat: 14 },
    { name_en: 'Dates with Arabic Gahwa', name_ar: 'تمر مع قهوة عربية', mealType: 'snack', calories: 180, protein: 2, carbs: 42, fat: 1 },
  ],
  emirati: [
    { name_en: 'Balaleet (Sweet Vermicelli)', name_ar: 'بلاليط', mealType: 'breakfast', calories: 320, protein: 8, carbs: 54, fat: 8 },
    { name_en: 'Chebab Date Pancakes', name_ar: 'شباب بالتمر', mealType: 'breakfast', calories: 280, protein: 8, carbs: 44, fat: 8 },
    { name_en: 'Regag Bread with Cheese', name_ar: 'رقاق بالجبن', mealType: 'breakfast', calories: 260, protein: 11, carbs: 34, fat: 9 },
    { name_en: 'Khameer Bread with Date Syrup', name_ar: 'خمير بدبس التمر', mealType: 'breakfast', calories: 290, protein: 7, carbs: 50, fat: 7 },
    { name_en: 'Machboos with Chicken', name_ar: 'مكبوس دجاج', mealType: 'lunch', calories: 580, protein: 34, carbs: 78, fat: 14 },
    { name_en: 'Saloona with Lamb', name_ar: 'سلونة لحم', mealType: 'lunch', calories: 350, protein: 22, carbs: 18, fat: 20 },
    { name_en: 'Emirati Harees', name_ar: 'هريس إماراتي', mealType: 'lunch', calories: 320, protein: 16, carbs: 46, fat: 8 },
    { name_en: 'Jeshid (Spiced Rice with Fish)', name_ar: 'جشيد سمك', mealType: 'lunch', calories: 420, protein: 24, carbs: 55, fat: 10 },
    { name_en: 'Tharid with Lamb', name_ar: 'ثريد لحم', mealType: 'dinner', calories: 380, protein: 20, carbs: 50, fat: 11 },
    { name_en: 'Machboos Samak (Fish Rice)', name_ar: 'مكبوس سمك', mealType: 'dinner', calories: 460, protein: 28, carbs: 62, fat: 11 },
    { name_en: 'Margooga with Flatbread', name_ar: 'مرقوقة', mealType: 'dinner', calories: 330, protein: 18, carbs: 44, fat: 9 },
    { name_en: 'Ghoozi (Stuffed Lamb with Rice)', name_ar: 'غوزي', mealType: 'dinner', calories: 620, protein: 38, carbs: 66, fat: 22 },
    { name_en: 'Luqaimat with Date Syrup', name_ar: 'لقيمات بدبس التمر', mealType: 'snack', calories: 260, protein: 3, carbs: 42, fat: 9 },
    { name_en: 'Gahwa with Dates', name_ar: 'قهوة عربية مع التمر', mealType: 'snack', calories: 120, protein: 1, carbs: 28, fat: 1 },
  ],
  omani: [
    { name_en: 'Khabees (Sweet Wheat)', name_ar: 'خبيص', mealType: 'breakfast', calories: 300, protein: 4, carbs: 52, fat: 8 },
    { name_en: 'Omani Balaleet', name_ar: 'بلاليط عماني', mealType: 'breakfast', calories: 320, protein: 8, carbs: 54, fat: 8 },
    { name_en: 'Madrouba (Mashed Fish and Rice)', name_ar: 'مدروبة', mealType: 'breakfast', calories: 330, protein: 20, carbs: 44, fat: 8 },
    { name_en: 'Rukhal Bread with Honey', name_ar: 'رخال مع العسل', mealType: 'breakfast', calories: 230, protein: 6, carbs: 42, fat: 5 },
    { name_en: 'Shuwa with Rice', name_ar: 'شواء مع الأرز', mealType: 'lunch', calories: 680, protein: 40, carbs: 62, fat: 30 },
    { name_en: 'Mashuai (Grilled Kingfish with Rice)', name_ar: 'مشوي سمك مع الأرز', mealType: 'lunch', calories: 520, protein: 40, carbs: 52, fat: 15 },
    { name_en: 'Qubooli (Lamb Rice)', name_ar: 'قوبولو لحم', mealType: 'lunch', calories: 540, protein: 28, carbs: 72, fat: 14 },
    { name_en: 'Omani Harees', name_ar: 'هريس عماني', mealType: 'lunch', calories: 320, protein: 16, carbs: 46, fat: 8 },
    { name_en: 'Mishkak (Grilled Lamb Skewers) with Rice', name_ar: 'مشاكيك مع الأرز', mealType: 'dinner', calories: 380, protein: 26, carbs: 40, fat: 11 },
    { name_en: 'Sakhuni (Omani Lentil Stew)', name_ar: 'سخوني', mealType: 'dinner', calories: 260, protein: 14, carbs: 36, fat: 7 },
    { name_en: 'Omani Salona (Chicken Stew)', name_ar: 'سلونة عماني دجاج', mealType: 'dinner', calories: 300, protein: 24, carbs: 16, fat: 14 },
    { name_en: 'Omani Seafood Machboos', name_ar: 'مكبوس بحري عماني', mealType: 'dinner', calories: 460, protein: 28, carbs: 62, fat: 11 },
    { name_en: 'Halwa Omaniya', name_ar: 'حلوى عمانية', mealType: 'snack', calories: 240, protein: 2, carbs: 40, fat: 8 },
    { name_en: 'Kangari (Sweet Saffron Rice)', name_ar: 'كنغري', mealType: 'snack', calories: 280, protein: 4, carbs: 48, fat: 8 },
  ],
  kuwaiti: [
    { name_en: 'Gers Ogaily (Kuwaiti Pancakes)', name_ar: 'قرص عقيلي', mealType: 'breakfast', calories: 200, protein: 6, carbs: 30, fat: 6 },
    { name_en: 'Kuwaiti Balaleet', name_ar: 'بلاليط كويتي', mealType: 'breakfast', calories: 320, protein: 8, carbs: 54, fat: 8 },
    { name_en: 'Regag Bread with Cheese', name_ar: 'رقاق بالجبن', mealType: 'breakfast', calories: 260, protein: 11, carbs: 34, fat: 9 },
    { name_en: 'Chebab Date Pancakes', name_ar: 'شباب بالتمر', mealType: 'breakfast', calories: 280, protein: 8, carbs: 44, fat: 8 },
    { name_en: 'Machboos Laham (Lamb Rice)', name_ar: 'مكبوس لحم كويتي', mealType: 'lunch', calories: 600, protein: 36, carbs: 72, fat: 18 },
    { name_en: 'Murabyan (Prawn Rice)', name_ar: 'مربيان', mealType: 'lunch', calories: 470, protein: 30, carbs: 58, fat: 12 },
    { name_en: 'Gabout (Salted Shrimp Stew)', name_ar: 'قبوط', mealType: 'lunch', calories: 260, protein: 24, carbs: 14, fat: 11 },
    { name_en: 'Kuwaiti Saloona (Lamb Stew)', name_ar: 'سلونة كويتي', mealType: 'lunch', calories: 350, protein: 22, carbs: 18, fat: 20 },
    { name_en: 'Jireesh (Crushed Wheat)', name_ar: 'جريش كويتي', mealType: 'dinner', calories: 340, protein: 16, carbs: 52, fat: 8 },
    { name_en: 'Kuwaiti Harees', name_ar: 'هريس كويتي', mealType: 'dinner', calories: 320, protein: 16, carbs: 46, fat: 8 },
    { name_en: 'Mutabbaq Samak (Stuffed Fish Bread)', name_ar: 'مطبق سمك', mealType: 'dinner', calories: 390, protein: 22, carbs: 44, fat: 13 },
    { name_en: 'Kuwaiti Thareed', name_ar: 'ثريد كويتي', mealType: 'dinner', calories: 380, protein: 20, carbs: 50, fat: 11 },
    { name_en: 'Samboosa with Meat', name_ar: 'سمبوسة لحم', mealType: 'snack', calories: 240, protein: 8, carbs: 26, fat: 11 },
    { name_en: 'Luqaimat (Sweet Dumplings)', name_ar: 'لقيمات', mealType: 'snack', calories: 250, protein: 3, carbs: 40, fat: 9 },
  ],
  qatar: [
    { name_en: 'Qatari Balaleet', name_ar: 'بلاليط قطري', mealType: 'breakfast', calories: 320, protein: 8, carbs: 54, fat: 8 },
    { name_en: 'Regag Bread with Cheese', name_ar: 'رقاق بالجبن', mealType: 'breakfast', calories: 260, protein: 11, carbs: 34, fat: 9 },
    { name_en: 'Chebab Date Pancakes', name_ar: 'شباب بالتمر', mealType: 'breakfast', calories: 280, protein: 8, carbs: 44, fat: 8 },
    { name_en: 'Ful Medames Qatari', name_ar: 'فول مدمس قطري', mealType: 'breakfast', calories: 240, protein: 15, carbs: 32, fat: 6 },
    { name_en: 'Qatari Machboos Dajaj', name_ar: 'مكبوس دجاج قطري', mealType: 'lunch', calories: 580, protein: 34, carbs: 78, fat: 14 },
    { name_en: 'Saloonat with Lamb', name_ar: 'سلونة لحم', mealType: 'lunch', calories: 350, protein: 22, carbs: 18, fat: 20 },
    { name_en: 'Qatari Harees', name_ar: 'هريس قطري', mealType: 'lunch', calories: 320, protein: 16, carbs: 46, fat: 8 },
    { name_en: 'Mandi Dajaj with Rice', name_ar: 'مندي دجاج', mealType: 'lunch', calories: 540, protein: 32, carbs: 70, fat: 14 },
    { name_en: 'Machboos Samak (Fish Rice)', name_ar: 'مكبوس سمك', mealType: 'dinner', calories: 460, protein: 28, carbs: 62, fat: 11 },
    { name_en: 'Qatari Jareesh', name_ar: 'جريش قطري', mealType: 'dinner', calories: 340, protein: 16, carbs: 52, fat: 8 },
    { name_en: 'Thareed Qatari', name_ar: 'ثريد قطري', mealType: 'dinner', calories: 380, protein: 20, carbs: 50, fat: 11 },
    { name_en: 'Madrooba (Mashed Fish Rice)', name_ar: 'مدروبة', mealType: 'dinner', calories: 340, protein: 20, carbs: 46, fat: 8 },
    { name_en: 'Luqaimat (Sweet Dumplings)', name_ar: 'لقيمات', mealType: 'snack', calories: 250, protein: 3, carbs: 40, fat: 9 },
    { name_en: 'Khabees (Sweet Wheat)', name_ar: 'خبيص', mealType: 'snack', calories: 300, protein: 4, carbs: 52, fat: 8 },
  ],
  bahraini: [
    { name_en: 'Bahraini Balaleet', name_ar: 'بلاليط بحريني', mealType: 'breakfast', calories: 320, protein: 8, carbs: 54, fat: 8 },
    { name_en: 'Regag Bread with Cheese', name_ar: 'رقاق بالجبن', mealType: 'breakfast', calories: 260, protein: 11, carbs: 34, fat: 9 },
    { name_en: 'Ful Medames Bahraini', name_ar: 'فول مدمس بحريني', mealType: 'breakfast', calories: 240, protein: 15, carbs: 32, fat: 6 },
    { name_en: 'Khameer Bread with Date Syrup', name_ar: 'خمير بدبس التمر', mealType: 'breakfast', calories: 290, protein: 7, carbs: 50, fat: 7 },
    { name_en: 'Machboos Hammour (Grouper Rice)', name_ar: 'مكبوس حامور', mealType: 'lunch', calories: 440, protein: 34, carbs: 56, fat: 9 },
    { name_en: 'Muhammar (Sweet Brown Rice)', name_ar: 'محمر', mealType: 'lunch', calories: 400, protein: 10, carbs: 74, fat: 7 },
    { name_en: 'Bahraini Saloona (Fish Stew)', name_ar: 'سلونة سمك', mealType: 'lunch', calories: 280, protein: 24, carbs: 16, fat: 12 },
    { name_en: 'Bahraini Harees', name_ar: 'هريس بحريني', mealType: 'lunch', calories: 320, protein: 16, carbs: 46, fat: 8 },
    { name_en: 'Machboos Laham (Lamb Rice)', name_ar: 'مكبوس لحم بحريني', mealType: 'dinner', calories: 600, protein: 36, carbs: 72, fat: 18 },
    { name_en: 'Thareed Bahraini', name_ar: 'ثريد بحريني', mealType: 'dinner', calories: 380, protein: 20, carbs: 50, fat: 11 },
    { name_en: 'Jireesh Bahraini (Crushed Wheat)', name_ar: 'جريش بحريني', mealType: 'dinner', calories: 340, protein: 16, carbs: 52, fat: 8 },
    { name_en: 'Murabyan (Prawn Rice)', name_ar: 'مربيان بحريني', mealType: 'dinner', calories: 470, protein: 30, carbs: 58, fat: 12 },
    { name_en: 'Samboosa with Chicken', name_ar: 'سمبوسة دجاج', mealType: 'snack', calories: 230, protein: 9, carbs: 26, fat: 10 },
    { name_en: 'Lugaimat (Sweet Dumplings)', name_ar: 'لقيمات', mealType: 'snack', calories: 250, protein: 3, carbs: 40, fat: 9 },
  ],
};