import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  saudi: [
    { name_en: 'Saleeg with Chicken', name_ar: 'سليق بالدجاج', mealType: 'breakfast', calories: 450, protein: 18, carbs: 60, fat: 15 },
    { name_en: 'Ful Medames with Olive Oil', name_ar: 'فول مدمس بزيت الزيتون', mealType: 'breakfast', calories: 350, protein: 19, carbs: 35, fat: 11.3 },
    { name_en: 'Regag Bread with Cheese', name_ar: 'رقاق بالجبن', mealType: 'breakfast', calories: 300, protein: 10, carbs: 40, fat: 11 },
    { name_en: 'Tamis Bread with Egg', name_ar: 'تميس بالبيض', mealType: 'breakfast', calories: 600, protein: 27.5, carbs: 75, fat: 21.3 },
    { name_en: 'Saudi Kabsa with Chicken', name_ar: 'كبسة دجاج سعودية', mealType: 'lunch', calories: 450, protein: 24, carbs: 54, fat: 13.5 },
    { name_en: 'Madfoon with Lamb', name_ar: 'مدفون لحم', mealType: 'lunch', calories: 660, protein: 45, carbs: 57, fat: 27 },
    { name_en: 'Matazeez with Lamb', name_ar: 'مطازيز لحم', mealType: 'lunch', calories: 660, protein: 39, carbs: 66, fat: 27 },
    { name_en: 'Harees', name_ar: 'هريس', mealType: 'lunch', calories: 275, protein: 20, carbs: 30, fat: 8.8 },
    { name_en: 'Jareesh (Crushed Wheat)', name_ar: 'جريش', mealType: 'dinner', calories: 350, protein: 15, carbs: 60, fat: 6.3 },
    { name_en: 'Thareed with Lamb', name_ar: 'ثريد لحم', mealType: 'dinner', calories: 448, protein: 25.2, carbs: 44.8, fat: 16.8 },
    { name_en: 'Qursan with Chicken', name_ar: 'قرصان دجاج', mealType: 'dinner', calories: 700, protein: 39.2, carbs: 78.4, fat: 26.6 },
    { name_en: 'Margoog (Vegetable Stew)', name_ar: 'مرقوق', mealType: 'dinner', calories: 336, protein: 11.2, carbs: 50.4, fat: 11.2 },
    { name_en: 'Motabbaq', name_ar: 'مطبق', mealType: 'snack', calories: 360, protein: 9.6, carbs: 33.6, fat: 20.4 },
    { name_en: 'Dates with Arabic Gahwa', name_ar: 'تمر مع قهوة عربية', mealType: 'snack', calories: 169, protein: 1.5, carbs: 45, fat: 0.2 },
  ],
  emirati: [
    { name_en: 'Balaleet (Sweet Vermicelli)', name_ar: 'بلاليط', mealType: 'breakfast', calories: 450, protein: 10, carbs: 75, fat: 12.5 },
    { name_en: 'Chebab Date Pancakes', name_ar: 'شباب بالتمر', mealType: 'breakfast', calories: 204, protein: 5.8, carbs: 25.2, fat: 8.7 },
    { name_en: 'Regag Bread with Cheese', name_ar: 'رقاق بالجبن', mealType: 'breakfast', calories: 300, protein: 10, carbs: 40, fat: 11 },
    { name_en: 'Khameer Bread with Date Syrup', name_ar: 'خمير بدبس التمر', mealType: 'breakfast', calories: 700, protein: 17.5, carbs: 125, fat: 15 },
    { name_en: 'Machboos with Chicken', name_ar: 'مكبوس دجاج', mealType: 'lunch', calories: 450, protein: 24, carbs: 54, fat: 13.5 },
    { name_en: 'Saloona with Lamb', name_ar: 'سلونة لحم', mealType: 'lunch', calories: 570, protein: 36, carbs: 42, fat: 27 },
    { name_en: 'Emirati Harees', name_ar: 'هريس إماراتي', mealType: 'lunch', calories: 330, protein: 24, carbs: 36, fat: 10.5 },
    { name_en: 'Jeshid (Spiced Rice with Fish)', name_ar: 'جشيد سمك', mealType: 'lunch', calories: 540, protein: 30, carbs: 66, fat: 18 },
    { name_en: 'Tharid with Lamb', name_ar: 'ثريد لحم', mealType: 'dinner', calories: 476, protein: 30.8, carbs: 50.4, fat: 16.8 },
    { name_en: 'Machboos Samak (Fish Rice)', name_ar: 'مكبوس سمك', mealType: 'dinner', calories: 390, protein: 24, carbs: 42, fat: 13.5 },
    { name_en: 'Margooga with Flatbread', name_ar: 'مرقوقة', mealType: 'dinner', calories: 532, protein: 22.4, carbs: 61.6, fat: 22.4 },
    { name_en: 'Ghoozi (Stuffed Lamb with Rice)', name_ar: 'غوزي', mealType: 'dinner', calories: 431, protein: 9.6, carbs: 89.6, fat: 3.4 },
    { name_en: 'Luqaimat with Date Syrup', name_ar: 'لقيمات بدبس التمر', mealType: 'snack', calories: 320, protein: 4, carbs: 55, fat: 9 },
    { name_en: 'Gahwa with Dates', name_ar: 'قهوة عربية مع التمر', mealType: 'snack', calories: 113, protein: 1, carbs: 30, fat: 0.2 },
  ],
  omani: [
    { name_en: 'Khabees (Sweet Wheat)', name_ar: 'خبيص', mealType: 'breakfast', calories: 375, protein: 5, carbs: 75, fat: 7.5 },
    { name_en: 'Omani Balaleet', name_ar: 'بلاليط عماني', mealType: 'breakfast', calories: 450, protein: 10, carbs: 75, fat: 12.5 },
    { name_en: 'Madrouba (Mashed Fish and Rice)', name_ar: 'مدروبة', mealType: 'breakfast', calories: 325, protein: 17.5, carbs: 45, fat: 7.5 },
    { name_en: 'Rukhal Bread with Honey', name_ar: 'رخال مع العسل', mealType: 'breakfast', calories: 650, protein: 17.5, carbs: 120, fat: 12.5 },
    { name_en: 'Shuwa with Rice', name_ar: 'شواء مع الأرز', mealType: 'lunch', calories: 690, protein: 66, carbs: 18, fat: 39 },
    { name_en: 'Mashuai (Grilled Kingfish with Rice)', name_ar: 'مشوي سمك مع الأرز', mealType: 'lunch', calories: 369, protein: 8.2, carbs: 76.8, fat: 2.9 },
    { name_en: 'Qubooli (Lamb Rice)', name_ar: 'قوبولو لحم', mealType: 'lunch', calories: 495, protein: 24, carbs: 60, fat: 15 },
    { name_en: 'Omani Harees', name_ar: 'هريس عماني', mealType: 'lunch', calories: 330, protein: 24, carbs: 36, fat: 10.5 },
    { name_en: 'Mishkak (Grilled Lamb Skewers) with Rice', name_ar: 'مشاكيك مع الأرز', mealType: 'dinner', calories: 500, protein: 50, carbs: 10, fat: 27.5 },
    { name_en: 'Sakhuni (Omani Lentil Stew)', name_ar: 'سخوني', mealType: 'dinner', calories: 185, protein: 13.7, carbs: 28, fat: 3.4 },
    { name_en: 'Omani Salona (Chicken Stew)', name_ar: 'سلونة عماني دجاج', mealType: 'dinner', calories: 476, protein: 33.6, carbs: 33.6, fat: 22.4 },
    { name_en: 'Omani Seafood Machboos', name_ar: 'مكبوس بحري عماني', mealType: 'dinner', calories: 364, protein: 22.4, carbs: 39.2, fat: 12.6 },
    { name_en: 'Halwa Omaniya', name_ar: 'حلوى عمانية', mealType: 'snack', calories: 228, protein: 3.6, carbs: 34.8, fat: 8.4 },
    { name_en: 'Kangari (Sweet Saffron Rice)', name_ar: 'كنغري', mealType: 'snack', calories: 96, protein: 1.8, carbs: 19.2, fat: 1.8 },
  ],
  kuwaiti: [
    { name_en: 'Gers Ogaily (Kuwaiti Pancakes)', name_ar: 'قرص عقيلي', mealType: 'breakfast', calories: 568, protein: 16, carbs: 70, fat: 24.3 },
    { name_en: 'Kuwaiti Balaleet', name_ar: 'بلاليط كويتي', mealType: 'breakfast', calories: 450, protein: 10, carbs: 75, fat: 12.5 },
    { name_en: 'Regag Bread with Cheese', name_ar: 'رقاق بالجبن', mealType: 'breakfast', calories: 300, protein: 10, carbs: 40, fat: 11 },
    { name_en: 'Chebab Date Pancakes', name_ar: 'شباب بالتمر', mealType: 'breakfast', calories: 204, protein: 5.8, carbs: 25.2, fat: 8.7 },
    { name_en: 'Machboos Laham (Lamb Rice)', name_ar: 'مكبوس لحم كويتي', mealType: 'lunch', calories: 390, protein: 24, carbs: 42, fat: 13.5 },
    { name_en: 'Murabyan (Prawn Rice)', name_ar: 'مربيان', mealType: 'lunch', calories: 369, protein: 8.2, carbs: 76.8, fat: 2.9 },
    { name_en: 'Gabout (Salted Shrimp Stew)', name_ar: 'قبوط', mealType: 'lunch', calories: 450, protein: 36, carbs: 24, fat: 24 },
    { name_en: 'Kuwaiti Saloona (Lamb Stew)', name_ar: 'سلونة كويتي', mealType: 'lunch', calories: 555, protein: 36, carbs: 39, fat: 30 },
    { name_en: 'Jireesh (Crushed Wheat)', name_ar: 'جريش كويتي', mealType: 'dinner', calories: 350, protein: 15, carbs: 60, fat: 6.3 },
    { name_en: 'Kuwaiti Harees', name_ar: 'هريس كويتي', mealType: 'dinner', calories: 308, protein: 22.4, carbs: 33.6, fat: 9.8 },
    { name_en: 'Mutabbaq Samak (Stuffed Fish Bread)', name_ar: 'مطبق سمك', mealType: 'dinner', calories: 616, protein: 33.6, carbs: 61.6, fat: 25.2 },
    { name_en: 'Kuwaiti Thareed', name_ar: 'ثريد كويتي', mealType: 'dinner', calories: 462, protein: 28, carbs: 50.4, fat: 16.8 },
    { name_en: 'Samboosa with Meat', name_ar: 'سمبوسة لحم', mealType: 'snack', calories: 270, protein: 7.2, carbs: 25.2, fat: 15.3 },
    { name_en: 'Luqaimat (Sweet Dumplings)', name_ar: 'لقيمات', mealType: 'snack', calories: 320, protein: 4, carbs: 55, fat: 9 },
  ],
  qatar: [
    { name_en: 'Qatari Balaleet', name_ar: 'بلاليط قطري', mealType: 'breakfast', calories: 450, protein: 10, carbs: 75, fat: 12.5 },
    { name_en: 'Regag Bread with Cheese', name_ar: 'رقاق بالجبن', mealType: 'breakfast', calories: 300, protein: 10, carbs: 40, fat: 11 },
    { name_en: 'Chebab Date Pancakes', name_ar: 'شباب بالتمر', mealType: 'breakfast', calories: 204, protein: 5.8, carbs: 25.2, fat: 8.7 },
    { name_en: 'Ful Medames Qatari', name_ar: 'فول مدمس قطري', mealType: 'breakfast', calories: 165, protein: 11.4, carbs: 29.4, fat: 0.6 },
    { name_en: 'Qatari Machboos Dajaj', name_ar: 'مكبوس دجاج قطري', mealType: 'lunch', calories: 390, protein: 24, carbs: 42, fat: 13.5 },
    { name_en: 'Saloonat with Lamb', name_ar: 'سلونة لحم', mealType: 'lunch', calories: 540, protein: 36, carbs: 42, fat: 27 },
    { name_en: 'Qatari Harees', name_ar: 'هريس قطري', mealType: 'lunch', calories: 330, protein: 24, carbs: 36, fat: 10.5 },
    { name_en: 'Mandi Dajaj with Rice', name_ar: 'مندي دجاج', mealType: 'lunch', calories: 495, protein: 27, carbs: 51, fat: 16.5 },
    { name_en: 'Machboos Samak (Fish Rice)', name_ar: 'مكبوس سمك', mealType: 'dinner', calories: 390, protein: 24, carbs: 42, fat: 13.5 },
    { name_en: 'Qatari Jareesh', name_ar: 'جريش قطري', mealType: 'dinner', calories: 350, protein: 15, carbs: 60, fat: 6.3 },
    { name_en: 'Thareed Qatari', name_ar: 'ثريد قطري', mealType: 'dinner', calories: 462, protein: 28, carbs: 50.4, fat: 16.8 },
    { name_en: 'Madrooba (Mashed Fish Rice)', name_ar: 'مدروبة', mealType: 'dinner', calories: 344, protein: 7.7, carbs: 71.7, fat: 2.7 },
    { name_en: 'Luqaimat (Sweet Dumplings)', name_ar: 'لقيمات', mealType: 'snack', calories: 320, protein: 4, carbs: 55, fat: 9 },
    { name_en: 'Khabees (Sweet Wheat)', name_ar: 'خبيص', mealType: 'snack', calories: 375, protein: 5, carbs: 75, fat: 7.5 },
  ],
  bahraini: [
    { name_en: 'Bahraini Balaleet', name_ar: 'بلاليط بحريني', mealType: 'breakfast', calories: 450, protein: 10, carbs: 75, fat: 12.5 },
    { name_en: 'Regag Bread with Cheese', name_ar: 'رقاق بالجبن', mealType: 'breakfast', calories: 300, protein: 10, carbs: 40, fat: 11 },
    { name_en: 'Ful Medames Bahraini', name_ar: 'فول مدمس بحريني', mealType: 'breakfast', calories: 165, protein: 11.4, carbs: 29.4, fat: 0.6 },
    { name_en: 'Khameer Bread with Date Syrup', name_ar: 'خمير بدبس التمر', mealType: 'breakfast', calories: 700, protein: 17.5, carbs: 125, fat: 15 },
    { name_en: 'Machboos Hammour (Grouper Rice)', name_ar: 'مكبوس حامور', mealType: 'lunch', calories: 390, protein: 24, carbs: 42, fat: 13.5 },
    { name_en: 'Muhammar (Sweet Brown Rice)', name_ar: 'محمر', mealType: 'lunch', calories: 425, protein: 7.5, carbs: 80, fat: 7.5 },
    { name_en: 'Bahraini Saloona (Fish Stew)', name_ar: 'سلونة سمك', mealType: 'lunch', calories: 450, protein: 33, carbs: 30, fat: 21 },
    { name_en: 'Bahraini Harees', name_ar: 'هريس بحريني', mealType: 'lunch', calories: 330, protein: 24, carbs: 36, fat: 10.5 },
    { name_en: 'Machboos Laham (Lamb Rice)', name_ar: 'مكبوس لحم بحريني', mealType: 'dinner', calories: 390, protein: 24, carbs: 42, fat: 13.5 },
    { name_en: 'Thareed Bahraini', name_ar: 'ثريد بحريني', mealType: 'dinner', calories: 462, protein: 28, carbs: 50.4, fat: 16.8 },
    { name_en: 'Jireesh Bahraini (Crushed Wheat)', name_ar: 'جريش بحريني', mealType: 'dinner', calories: 350, protein: 15, carbs: 60, fat: 6.3 },
    { name_en: 'Murabyan (Prawn Rice)', name_ar: 'مربيان بحريني', mealType: 'dinner', calories: 369, protein: 8.2, carbs: 76.8, fat: 2.9 },
    { name_en: 'Samboosa with Chicken', name_ar: 'سمبوسة دجاج', mealType: 'snack', calories: 257, protein: 8.1, carbs: 24.3, fat: 14.4 },
    { name_en: 'Lugaimat (Sweet Dumplings)', name_ar: 'لقيمات', mealType: 'snack', calories: 320, protein: 4, carbs: 55, fat: 9 },
  ],
};