import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  lebanese: [
    { name_en: 'Foul with Tahini', name_ar: 'فول بالطحينة', mealType: 'breakfast', calories: 165, protein: 11.4, carbs: 29.4, fat: 0.6 },
    { name_en: 'Labneh with Zaatar', name_ar: 'لبنة بالزعتر', mealType: 'breakfast', calories: 130, protein: 6.5, carbs: 4.6, fat: 9.8 },
    { name_en: 'Manakish Zaatar', name_ar: 'مناقيش زعتر', mealType: 'breakfast', calories: 360, protein: 10.8, carbs: 54, fat: 10.8 },
    { name_en: 'Shakshuka', name_ar: 'شكشوكة', mealType: 'breakfast', calories: 275, protein: 15, carbs: 20, fat: 15 },
    { name_en: 'Musakhan', name_ar: 'مسخن', mealType: 'lunch', calories: 660, protein: 42, carbs: 60, fat: 27 },
    { name_en: 'Maqluba', name_ar: 'مقلوبة', mealType: 'lunch', calories: 390, protein: 18, carbs: 48, fat: 13.5 },
    { name_en: 'Shawarma Chicken', name_ar: 'شاورما دجاج', mealType: 'lunch', calories: 323, protein: 27, carbs: 9, fat: 19.5 },
    { name_en: 'Kabsa-style Rice', name_ar: 'كبسة', mealType: 'lunch', calories: 450, protein: 24, carbs: 54, fat: 13.5 },
    { name_en: 'Tabbouleh & Hummus Plate', name_ar: 'تبولة مع حمص', mealType: 'dinner', calories: 160, protein: 4.8, carbs: 18, fat: 9 },
    { name_en: 'Kibbeh', name_ar: 'كبة', mealType: 'dinner', calories: 450, protein: 28.8, carbs: 27, fat: 23.4 },
    { name_en: 'Grilled Kofta', name_ar: 'كفتة مشوية', mealType: 'dinner', calories: 400, protein: 32, carbs: 16, fat: 24 },
    { name_en: 'Sayadieh', name_ar: 'صيادية', mealType: 'dinner', calories: 540, protein: 27, carbs: 81, fat: 13.5 },
    { name_en: 'Kanafeh', name_ar: 'كنافة', mealType: 'snack', calories: 384, protein: 7.2, carbs: 54, fat: 15.6 },
    { name_en: 'Halva', name_ar: 'حلاوة', mealType: 'snack', calories: 282, protein: 6.6, carbs: 30, fat: 15.6 },
  ],
  african: [
    { name_en: 'Akara', name_ar: 'أكارا', mealType: 'breakfast', calories: 250, protein: 8, carbs: 20, fat: 15 },
    { name_en: 'Fit-Fit', name_ar: 'فتفت', mealType: 'breakfast', calories: 500, protein: 20, carbs: 70, fat: 17.5 },
    { name_en: 'Uji Porridge', name_ar: 'عصيدة أوجي', mealType: 'breakfast', calories: 225, protein: 7.5, carbs: 50, fat: 1.3 },
    { name_en: 'Chapati with Egg', name_ar: 'شباتي بالبيض', mealType: 'breakfast', calories: 600, protein: 22.5, carbs: 80, fat: 22.5 },
    { name_en: 'Jollof Rice with Chicken', name_ar: 'أرز جولوف مع دجاج', mealType: 'lunch', calories: 455, protein: 14, carbs: 70, fat: 12.3 },
    { name_en: 'Ugali with Sukuma Wiki', name_ar: 'أوغالي مع سوكوما', mealType: 'lunch', calories: 420, protein: 12, carbs: 75, fat: 9 },
    { name_en: 'Injera with Doro Wat', name_ar: 'إنجيرا مع دورو وات', mealType: 'lunch', calories: 420, protein: 28, carbs: 52.5, fat: 10.5 },
    { name_en: 'Fufu with Egusi Soup', name_ar: 'فوفو مع حساء إيغوسي', mealType: 'lunch', calories: 280, protein: 10.5, carbs: 31.5, fat: 14 },
    { name_en: 'Bobotie', name_ar: 'بوبوتي', mealType: 'dinner', calories: 510, protein: 30, carbs: 39, fat: 24 },
    { name_en: 'Braai Grilled Fish', name_ar: 'سمك مشوي بالفحم', mealType: 'dinner', calories: 336, protein: 56, carbs: 2.8, fat: 11.2 },
    { name_en: 'Groundnut Stew', name_ar: 'حساء الفول السوداني', mealType: 'dinner', calories: 448, protein: 25.2, carbs: 22.4, fat: 28 },
    { name_en: 'Thieboudienne', name_ar: 'تيبوديين', mealType: 'dinner', calories: 364, protein: 22.4, carbs: 44.8, fat: 9.8 },
    { name_en: 'Mandazi', name_ar: 'مندازي', mealType: 'snack', calories: 240, protein: 5.6, carbs: 36, fat: 8 },
    { name_en: 'Chin Chin', name_ar: 'تشين تشين', mealType: 'snack', calories: 252, protein: 4.8, carbs: 36, fat: 9.6 },
  ],
};