import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  egyptian: [
    { name_en: 'Foul Medames with Olive Oil', name_ar: 'فول مدمس بزيت الزيتون', mealType: 'breakfast', calories: 165, protein: 11.4, carbs: 29.4, fat: 0.6 },
    { name_en: 'Egyptian Taameya Falafel', name_ar: 'طعمية', mealType: 'breakfast', calories: 333, protein: 13.3, carbs: 31.8, fat: 17.8 },
    { name_en: 'Alexandrian Eggs', name_ar: 'بيض إسكندراني', mealType: 'breakfast', calories: 325, protein: 22.5, carbs: 7.5, fat: 22.5 },
    { name_en: 'Feteer Baladi with Honey', name_ar: 'فطير بلدي بالعسل', mealType: 'breakfast', calories: 384, protein: 9.6, carbs: 50.4, fat: 15.6 },
    { name_en: 'Koshari', name_ar: 'كشري', mealType: 'lunch', calories: 338, protein: 11.3, carbs: 60, fat: 6.3 },
    { name_en: 'Egyptian Hawawshi', name_ar: 'حواوشي', mealType: 'lunch', calories: 500, protein: 24, carbs: 50, fat: 22 },
    { name_en: 'Molokhia with Chicken and Rice', name_ar: 'ملوخية بالفراخ والأرز', mealType: 'lunch', calories: 260, protein: 18, carbs: 28, fat: 6 },
    { name_en: 'Egyptian Fatta with Lamb', name_ar: 'فتة', mealType: 'lunch', calories: 555, protein: 27, carbs: 60, fat: 21 },
    { name_en: 'Stuffed Vine Leaves', name_ar: 'محشي ورق عنب', mealType: 'dinner', calories: 212, protein: 4.1, carbs: 23.4, fat: 10.8 },
    { name_en: 'Grilled Kofta with Rice', name_ar: 'كفتة مشوية بالأرز', mealType: 'dinner', calories: 448, protein: 33.6, carbs: 39.2, fat: 15.4 },
    { name_en: 'Stuffed Pigeon with Freekeh', name_ar: 'حمام محشي', mealType: 'dinner', calories: 644, protein: 56, carbs: 28, fat: 33.6 },
    { name_en: 'Egyptian Shish Tawook', name_ar: 'شيش طاووق', mealType: 'dinner', calories: 392, protein: 50.4, carbs: 19.6, fat: 12.6 },
    { name_en: 'Basbousa Semolina Cake', name_ar: 'بسبوسة', mealType: 'snack', calories: 304, protein: 3.2, carbs: 46.4, fat: 12 },
    { name_en: 'Ghorayebah Shortbread', name_ar: 'غريبة', mealType: 'snack', calories: 300, protein: 3, carbs: 34.8, fat: 16.8 },
  ],
  libyan: [
    { name_en: 'Asida with Honey and Ghee', name_ar: 'عصيدة بالعسل', mealType: 'breakfast', calories: 825, protein: 12.5, carbs: 137.5, fat: 27.5 },
    { name_en: 'Libyan Shakshouka', name_ar: 'شكشوكة ليبية', mealType: 'breakfast', calories: 275, protein: 15, carbs: 20, fat: 15 },
    { name_en: 'Couscous with Milk', name_ar: 'كسكسي بالحليب', mealType: 'breakfast', calories: 300, protein: 10, carbs: 50, fat: 7.5 },
    { name_en: 'Tishkishti Semolina Sweet', name_ar: 'تشكيشتي', mealType: 'breakfast', calories: 850, protein: 15, carbs: 145, fat: 25 },
    { name_en: 'Bazin with Lamb and Tomato Sauce', name_ar: 'بازين باللحم', mealType: 'lunch', calories: 540, protein: 18, carbs: 90, fat: 12 },
    { name_en: 'Libyan Couscous with Meat', name_ar: 'كسكسي بالقدرة', mealType: 'lunch', calories: 336, protein: 11.4, carbs: 69.6, fat: 0.5 },
    { name_en: 'Mbakbaka Spicy Pasta', name_ar: 'مبكبكة', mealType: 'lunch', calories: 630, protein: 27, carbs: 90, fat: 19.5 },
    { name_en: 'Rice with Vegetables', name_ar: 'رز بالخضرة', mealType: 'lunch', calories: 420, protein: 12, carbs: 78, fat: 9 },
    { name_en: 'Libyan Grilled Lamb Liver', name_ar: 'كبدة مشوية ليبية', mealType: 'dinner', calories: 532, protein: 58.8, carbs: 14, fat: 28 },
    { name_en: 'Stuffed Vine Leaves', name_ar: 'محشي ورق عنب', mealType: 'dinner', calories: 212, protein: 4.1, carbs: 23.4, fat: 10.8 },
    { name_en: 'Grilled Chicken with Potatoes', name_ar: 'دجاج مشوي بالبطاطا', mealType: 'dinner', calories: 462, protein: 86.8, carbs: 0, fat: 10.1 },
    { name_en: 'Lamb and Okra Stew', name_ar: 'بامية باللحم', mealType: 'dinner', calories: 448, protein: 28, carbs: 33.6, fat: 22.4 },
    { name_en: 'Ghrayba Cookies', name_ar: 'غريبة', mealType: 'snack', calories: 288, protein: 4.2, carbs: 33, fat: 15.6 },
    { name_en: 'Rice Pudding', name_ar: 'رز بالحليب', mealType: 'snack', calories: 72, protein: 1.8, carbs: 12, fat: 1.8 },
  ],
  tunisian: [
    { name_en: 'Lablabi Chickpea Soup', name_ar: 'لبلابي', mealType: 'breakfast', calories: 200, protein: 12.5, carbs: 22.5, fat: 6.3 },
    { name_en: 'Ojja Merguez and Eggs', name_ar: 'أوجة مرقاز', mealType: 'breakfast', calories: 475, protein: 30, carbs: 15, fat: 32.5 },
    { name_en: 'Brik a l Oeuf', name_ar: 'بريك بالبيض', mealType: 'breakfast', calories: 198, protein: 8.1, carbs: 16.2, fat: 11.7 },
    { name_en: 'Masfouf Sweet Couscous', name_ar: 'كسكسي مسفوف بالحليب', mealType: 'breakfast', calories: 280, protein: 9.5, carbs: 58, fat: 0.4 },
    { name_en: 'Couscous with Lamb and Vegetables', name_ar: 'كسكسي بالخضرة واللحم', mealType: 'lunch', calories: 336, protein: 11.4, carbs: 69.6, fat: 0.5 },
    { name_en: 'Tunisian Mlukhia Stew', name_ar: 'ملوخية تونسية', mealType: 'lunch', calories: 110, protein: 7, carbs: 16, fat: 2.4 },
    { name_en: 'Kafteji Fried Vegetables', name_ar: 'كفتاجي', mealType: 'lunch', calories: 450, protein: 12, carbs: 48, fat: 25.5 },
    { name_en: 'Tunisian Tagine', name_ar: 'طاجين تونسي', mealType: 'lunch', calories: 600, protein: 42, carbs: 30, fat: 36 },
    { name_en: 'Grilled Fish with Harissa', name_ar: 'سمك مشوي بالهريسة', mealType: 'dinner', calories: 308, protein: 22.4, carbs: 33.6, fat: 9.8 },
    { name_en: 'Chakchouka', name_ar: 'شكشوكة', mealType: 'dinner', calories: 250, protein: 12.5, carbs: 20, fat: 12.5 },
    { name_en: 'Osbane Stuffed Tripe', name_ar: 'عصبان', mealType: 'dinner', calories: 616, protein: 39.2, carbs: 33.6, fat: 33.6 },
    { name_en: 'Couscous with Fish', name_ar: 'كسكسي بالسمك', mealType: 'dinner', calories: 314, protein: 10.6, carbs: 65, fat: 0.4 },
    { name_en: 'Brik with Tuna', name_ar: 'بريك بالتونة', mealType: 'snack', calories: 70, protein: 15.3, carbs: 0, fat: 0.5 },
    { name_en: 'Makroud with Dates', name_ar: 'مخرود', mealType: 'snack', calories: 280, protein: 3.5, carbs: 43.4, fat: 10.5 },
  ],
  algerian: [
    { name_en: 'Mhadjeb Stuffed Flatbread', name_ar: 'محجب', mealType: 'breakfast', calories: 650, protein: 20, carbs: 95, fat: 22.5 },
    { name_en: 'Baghrir with Honey and Butter', name_ar: 'بغرير بالعسل', mealType: 'breakfast', calories: 550, protein: 12.5, carbs: 85, fat: 20 },
    { name_en: 'Karantika Chickpea Flan', name_ar: 'كارنتيكا', mealType: 'breakfast', calories: 300, protein: 12.5, carbs: 42.5, fat: 8.8 },
    { name_en: 'Fava Beans with Cumin', name_ar: 'فول بالكمون', mealType: 'breakfast', calories: 325, protein: 22.5, carbs: 50, fat: 5 },
    { name_en: 'Couscous with Lamb and Vegetables', name_ar: 'كسكسي باللحم', mealType: 'lunch', calories: 336, protein: 11.4, carbs: 69.6, fat: 0.5 },
    { name_en: 'Chakhchoukha', name_ar: 'شخشوخة', mealType: 'lunch', calories: 630, protein: 27, carbs: 84, fat: 22.5 },
    { name_en: 'Algerian Chicken and Olive Tagine', name_ar: 'طاجين الزيتون', mealType: 'lunch', calories: 600, protein: 42, carbs: 30, fat: 33 },
    { name_en: 'Boulfaf Grilled Liver Skewers', name_ar: 'بولفاف', mealType: 'lunch', calories: 585, protein: 63, carbs: 18, fat: 30 },
    { name_en: 'Rechta with Chicken and Chickpeas', name_ar: 'رشتة بالدجاج', mealType: 'dinner', calories: 336, protein: 14, carbs: 47.6, fat: 9.8 },
    { name_en: 'Chorba Frik Soup', name_ar: 'شوربة فريك', mealType: 'dinner', calories: 224, protein: 14, carbs: 28, fat: 7 },
    { name_en: 'Berkoukes with Lamb', name_ar: 'بركوكس', mealType: 'dinner', calories: 588, protein: 28, carbs: 67.2, fat: 23.8 },
    { name_en: 'Bourek with Meat and Egg', name_ar: 'بوراك باللحم', mealType: 'dinner', calories: 700, protein: 30.8, carbs: 67.2, fat: 36.4 },
    { name_en: 'Mtakem Sweet Fritters', name_ar: 'متقم', mealType: 'snack', calories: 198, protein: 3.6, carbs: 27.6, fat: 8.4 },
    { name_en: 'Griwech Honey Pastry', name_ar: 'قراوش', mealType: 'snack', calories: 228, protein: 3, carbs: 31.2, fat: 10.8 },
  ],
  moroccan: [
    { name_en: 'Msemen with Honey', name_ar: 'مسمن بالعسل', mealType: 'breakfast', calories: 312, protein: 6, carbs: 50.4, fat: 9.6 },
    { name_en: 'Baghrir Pancakes', name_ar: 'بغرير', mealType: 'breakfast', calories: 272, protein: 7.7, carbs: 33.6, fat: 11.6 },
    { name_en: 'Amlou with Bread', name_ar: 'أملو', mealType: 'breakfast', calories: 210, protein: 5.4, carbs: 18, fat: 13.2 },
    { name_en: 'Bissara Fava Soup', name_ar: 'بيسارة', mealType: 'breakfast', calories: 225, protein: 12.5, carbs: 32.5, fat: 5 },
    { name_en: 'Couscous with Seven Vegetables', name_ar: 'كسكسي بالخضار السبعة', mealType: 'lunch', calories: 336, protein: 11.4, carbs: 69.6, fat: 0.5 },
    { name_en: 'Rfissa with Lentils and Chicken', name_ar: 'رفيسة', mealType: 'lunch', calories: 198, protein: 14.7, carbs: 30, fat: 3.6 },
    { name_en: 'Kefta and Egg Tagine', name_ar: 'طاجين الكفتة', mealType: 'lunch', calories: 425, protein: 32.5, carbs: 12.5, fat: 27.5 },
    { name_en: 'Chicken Tagine with Preserved Lemon', name_ar: 'طاجين الدجاج بالحامض مصير', mealType: 'lunch', calories: 450, protein: 45, carbs: 18, fat: 21 },
    { name_en: 'Harira Soup with Dates', name_ar: 'حريرة', mealType: 'dinner', calories: 275, protein: 15, carbs: 37.5, fat: 7.5 },
    { name_en: 'Chicken Bastilla', name_ar: 'بسطيلة', mealType: 'dinner', calories: 330, protein: 18, carbs: 30, fat: 16.5 },
    { name_en: 'Lamb Tagine with Prunes and Almonds', name_ar: 'طاجين اللحم بالبرقوق واللوز', mealType: 'dinner', calories: 1621, protein: 59.4, carbs: 60.5, fat: 139.7 },
    { name_en: 'Grilled Sardine Kefta', name_ar: 'كفتة السردين', mealType: 'dinner', calories: 532, protein: 53.2, carbs: 8.4, fat: 30.8 },
    { name_en: 'Chebakia Sesame Pastry', name_ar: 'شباكية', mealType: 'snack', calories: 288, protein: 3, carbs: 39, fat: 13.2 },
    { name_en: 'Sellou Flour and Nut Mix', name_ar: 'سلو', mealType: 'snack', calories: 270, protein: 6, carbs: 27, fat: 15.6 },
  ],
};