import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  american: [
    { name_en: 'Pancakes with Maple Syrup', name_ar: 'بان كيك بشراب القيقب', mealType: 'breakfast', calories: 221, protein: 5.4, carbs: 34.2, fat: 7.2 },
    { name_en: 'Scrambled Eggs and Turkey Bacon', name_ar: 'بيض مخفوق مع بيكون ديك رومي', mealType: 'breakfast', calories: 240, protein: 16.8, carbs: 2.4, fat: 16.2 },
    { name_en: 'Waffles with Butter', name_ar: 'وافل بالزبدة', mealType: 'breakfast', calories: 262, protein: 7.1, carbs: 29.6, fat: 12.7 },
    { name_en: 'Cinnamon French Toast', name_ar: 'خبز فرنسي بالقرفة', mealType: 'breakfast', calories: 275, protein: 9.2, carbs: 33.6, fat: 13 },
    { name_en: 'Cheeseburger', name_ar: 'تشيز برجر', mealType: 'lunch', calories: 635, protein: 29.9, carbs: 50.6, fat: 34.5 },
    { name_en: 'BBQ Beef Ribs', name_ar: 'أضلاع لحم البقر بالباربكيو', mealType: 'lunch', calories: 728, protein: 67.5, carbs: 0, fat: 49 },
    { name_en: 'Grilled Salmon', name_ar: 'سلمون مشوي', mealType: 'lunch', calories: 312, protein: 30, carbs: 0, fat: 19.5 },
    { name_en: 'Caesar Chicken Wrap', name_ar: 'لفة دجاج سيزر', mealType: 'lunch', calories: 440, protein: 28, carbs: 44, fat: 16 },
    { name_en: 'Meatloaf with Mashed Potatoes', name_ar: 'رغيف اللحم مع البطاطا المهروسة', mealType: 'dinner', calories: 420, protein: 25.2, carbs: 33.6, fat: 18.2 },
    { name_en: 'Macaroni and Cheese', name_ar: 'معكرونة بالجبن', mealType: 'dinner', calories: 361, protein: 15.2, carbs: 39.6, fat: 17.6 },
    { name_en: 'Chicken Pot Pie', name_ar: 'فطيرة الدجاج', mealType: 'dinner', calories: 550, protein: 20, carbs: 50, fat: 27.5 },
    { name_en: 'New England Clam Chowder', name_ar: 'شوربة المحار بني إنجلاند', mealType: 'dinner', calories: 175, protein: 7.9, carbs: 25.7, fat: 4.8 },
    { name_en: 'Chocolate Chip Cookies', name_ar: 'بسكويت برقائق الشوكولاتة', mealType: 'snack', calories: 148, protein: 1.8, carbs: 19.5, fat: 7.2 },
    { name_en: 'Apple Pie Slice', name_ar: 'شريحة فطيرة التفاح', mealType: 'snack', calories: 284, protein: 2.3, carbs: 40.8, fat: 13.2 },
  ],
  mexican: [
    { name_en: 'Huevos Rancheros', name_ar: 'هويفوس رانشيروس', mealType: 'breakfast', calories: 352, protein: 22, carbs: 17.6, fat: 22 },
    { name_en: 'Chilaquiles with Eggs', name_ar: 'تشيلاكيليس مع البيض', mealType: 'breakfast', calories: 475, protein: 15, carbs: 55, fat: 22.5 },
    { name_en: 'Breakfast Burrito', name_ar: 'بوريتو الفطور', mealType: 'breakfast', calories: 494, protein: 26, carbs: 62.4, fat: 15.6 },
    { name_en: 'Huevos a la Mexicana', name_ar: 'بيض على الطريقة المكسيكية', mealType: 'breakfast', calories: 260, protein: 18, carbs: 8, fat: 18 },
    { name_en: 'Tacos al Pastor', name_ar: 'تاكو آل باستور', mealType: 'lunch', calories: 342, protein: 16.2, carbs: 25.2, fat: 16.2 },
    { name_en: 'Enchiladas Verdes', name_ar: 'إنتشلاداس فيردي', mealType: 'lunch', calories: 453, protein: 22.5, carbs: 35, fat: 25 },
    { name_en: 'Burrito Bowl', name_ar: 'طبق بوريتو', mealType: 'lunch', calories: 450, protein: 30, carbs: 60, fat: 10.5 },
    { name_en: 'Quesadilla de Pollo', name_ar: 'كيساديلا الدجاج', mealType: 'lunch', calories: 588, protein: 22, carbs: 48, fat: 34 },
    { name_en: 'Carne Asada', name_ar: 'كارني أسادا', mealType: 'dinner', calories: 420, protein: 50, carbs: 4, fat: 22 },
    { name_en: 'Pozole Rojo', name_ar: 'بوزولي روخو', mealType: 'dinner', calories: 240, protein: 21, carbs: 27, fat: 6 },
    { name_en: 'Chiles Rellenos', name_ar: 'تشيليس ريينوس', mealType: 'dinner', calories: 380, protein: 16, carbs: 24, fat: 24 },
    { name_en: 'Mole Poblano with Chicken', name_ar: 'موليه بوبلانو مع الدجاج', mealType: 'dinner', calories: 350, protein: 22.5, carbs: 22.5, fat: 17.5 },
    { name_en: 'Churros', name_ar: 'تشوروس', mealType: 'snack', calories: 297, protein: 3.6, carbs: 36, fat: 15.3 },
    { name_en: 'Tamales', name_ar: 'تاماليس', mealType: 'snack', calories: 312, protein: 6, carbs: 28.8, fat: 20.4 },
  ],
  canadian: [
    { name_en: 'Maple Pancakes', name_ar: 'فطائر بالشراب القيقبي', mealType: 'breakfast', calories: 204, protein: 5.8, carbs: 25.2, fat: 8.7 },
    { name_en: 'Peameal Beef Bacon Sandwich', name_ar: 'ساندويتش بيكون لحم بقري', mealType: 'breakfast', calories: 700, protein: 45, carbs: 82.5, fat: 20 },
    { name_en: 'Beaver Tails', name_ar: 'بيفر تيلز (حلوى البيور)', mealType: 'breakfast', calories: 750, protein: 15, carbs: 137.5, fat: 15 },
    { name_en: 'Oatmeal with Maple Syrup', name_ar: 'شوفان بشراب القيقب', mealType: 'breakfast', calories: 178, protein: 6.3, carbs: 30.5, fat: 3.8 },
    { name_en: 'Poutine', name_ar: 'بوتين', mealType: 'lunch', calories: 690, protein: 21, carbs: 75, fat: 33 },
    { name_en: 'Montreal Smoked Meat Sandwich', name_ar: 'ساندويتش اللحم المدخن بمونتريال', mealType: 'lunch', calories: 700, protein: 42.5, carbs: 75, fat: 27.5 },
    { name_en: 'Tourtière', name_ar: 'تورتيير (فطيرة اللحم)', mealType: 'lunch', calories: 560, protein: 26, carbs: 44, fat: 32 },
    { name_en: 'Nova Scotia Lobster Roll', name_ar: 'لفة الكركند نوفا سكوشا', mealType: 'lunch', calories: 690, protein: 42, carbs: 66, fat: 27 },
    { name_en: 'Maple Glazed Salmon', name_ar: 'سلمون بطلاء القيقب', mealType: 'dinner', calories: 582, protein: 56, carbs: 0, fat: 36.4 },
    { name_en: 'B.C. Salmon Bake', name_ar: 'سلمون مطهو على طريقة كولومبيا البريطانية', mealType: 'dinner', calories: 582, protein: 56, carbs: 0, fat: 36.4 },
    { name_en: 'Butter Chicken Poutine', name_ar: 'بوتين بالدجاج بالزبدة', mealType: 'dinner', calories: 504, protein: 30.8, carbs: 19.6, fat: 33.6 },
    { name_en: 'Shepherd\'s Pie', name_ar: 'فطيرة الراعي', mealType: 'dinner', calories: 520, protein: 26, carbs: 50, fat: 24 },
    { name_en: 'Butter Tarts', name_ar: 'فطائر الزبدة', mealType: 'snack', calories: 228, protein: 2.4, carbs: 30, fat: 10.8 },
    { name_en: 'Nanaimo Bar', name_ar: 'لوح نانيمو', mealType: 'snack', calories: 246, protein: 2.4, carbs: 28.8, fat: 13.8 },
  ],
  cuban: [
    { name_en: 'Cuban Breakfast Tostadas', name_ar: 'توستادا على الفطور الكوبي', mealType: 'breakfast', calories: 500, protein: 15, carbs: 70, fat: 17.5 },
    { name_en: 'Cafe con Leche with Bread', name_ar: 'قهوة بالحليب مع الخبز', mealType: 'breakfast', calories: 325, protein: 12.5, carbs: 45, fat: 10 },
    { name_en: 'Cuban Frittata', name_ar: 'فريتاتا كوبية', mealType: 'breakfast', calories: 375, protein: 27.5, carbs: 7.5, fat: 25 },
    { name_en: 'Mangu con Huevos', name_ar: 'مانجو مع البيض', mealType: 'breakfast', calories: 425, protein: 17.5, carbs: 65, fat: 12.5 },
    { name_en: 'Cubano Sandwich', name_ar: 'ساندويتش كوبانو', mealType: 'lunch', calories: 650, protein: 37.5, carbs: 70, fat: 25 },
    { name_en: 'Medianoche Sandwich', name_ar: 'ساندويتش ميديانونشي', mealType: 'lunch', calories: 750, protein: 42, carbs: 90, fat: 24 },
    { name_en: 'Black Bean Soup', name_ar: 'شوربة الفاصوليا السوداء', mealType: 'lunch', calories: 180, protein: 11.4, carbs: 30, fat: 1.5 },
    { name_en: 'Ropa Vieja with Rice', name_ar: 'روبا فييها مع الأرز', mealType: 'lunch', calories: 369, protein: 8.2, carbs: 76.8, fat: 2.9 },
    { name_en: 'Moros y Cristianos', name_ar: 'موروس إي كريستيانوس', mealType: 'dinner', calories: 400, protein: 15, carbs: 65, fat: 7.5 },
    { name_en: 'Lechon Asado', name_ar: 'ليشون أسادو (لحم مشوي)', mealType: 'dinner', calories: 525, protein: 50, carbs: 2.5, fat: 35 },
    { name_en: 'Picadillo Cubano', name_ar: 'بيكاديو كوبانو', mealType: 'dinner', calories: 532, protein: 33.6, carbs: 33.6, fat: 28 },
    { name_en: 'Arroz con Pollo', name_ar: 'أرز بالدجاج', mealType: 'dinner', calories: 450, protein: 24, carbs: 51, fat: 15 },
    { name_en: 'Tostones', name_ar: 'توستونيس', mealType: 'snack', calories: 135, protein: 0.9, carbs: 21, fat: 5.7 },
    { name_en: 'Cuban Flan', name_ar: 'فلان كوبي', mealType: 'snack', calories: 126, protein: 3.6, carbs: 18, fat: 4.2 },
  ],
  jamaican: [
    { name_en: 'Ackee and Saltfish', name_ar: 'أكي مع السمك المملح', mealType: 'breakfast', calories: 375, protein: 30, carbs: 15, fat: 22.5 },
    { name_en: 'Jamaican Cornmeal Porridge', name_ar: 'عصيدة الذرة الجامايكية', mealType: 'breakfast', calories: 325, protein: 10, carbs: 65, fat: 3.8 },
    { name_en: 'Callaloo and Johnnycakes', name_ar: 'كالالو مع جوني كيك', mealType: 'breakfast', calories: 525, protein: 17.5, carbs: 75, fat: 17.5 },
    { name_en: 'Fried Dumplings with Eggs', name_ar: 'زلابية مقلية مع البيض', mealType: 'breakfast', calories: 575, protein: 22.5, carbs: 85, fat: 17.5 },
    { name_en: 'Jerk Chicken', name_ar: 'دجاج جيرك', mealType: 'lunch', calories: 396, protein: 44, carbs: 13.2, fat: 19.8 },
    { name_en: 'Jamaican Beef Pattie', name_ar: 'باتي لحم بقري جامايكي', mealType: 'lunch', calories: 390, protein: 15.6, carbs: 36.4, fat: 20.8 },
    { name_en: 'Brown Stew Chicken', name_ar: 'دجاج بيني ستيو', mealType: 'lunch', calories: 510, protein: 42, carbs: 30, fat: 27 },
    { name_en: 'Curry Chicken with Rice and Peas', name_ar: 'دجاج بالكاري مع أرز وبازلاء', mealType: 'lunch', calories: 525, protein: 49, carbs: 56, fat: 12.3 },
    { name_en: 'Oxtail Stew', name_ar: 'يخنة ذيل الثور', mealType: 'dinner', calories: 560, protein: 39.2, carbs: 22.4, fat: 33.6 },
    { name_en: 'Curry Goat', name_ar: 'ماعز بالكاري', mealType: 'dinner', calories: 392, protein: 33.6, carbs: 22.4, fat: 18.2 },
    { name_en: 'Rice and Peas with Jerk Chicken', name_ar: 'أرز وبازلاء مع دجاج جيرك', mealType: 'dinner', calories: 532, protein: 33.6, carbs: 67.2, fat: 14 },
    { name_en: 'Escovitch Fish', name_ar: 'سمك إسكوفيتش', mealType: 'dinner', calories: 448, protein: 47.6, carbs: 16.8, fat: 19.6 },
    { name_en: 'Jamaican Pattie', name_ar: 'باتي جامايكي', mealType: 'snack', calories: 180, protein: 7.2, carbs: 16.8, fat: 9.6 },
    { name_en: 'Grater Cake', name_ar: 'كعكة الجزر المبشور', mealType: 'snack', calories: 204, protein: 1.8, carbs: 33, fat: 7.2 },
  ],
  costa_rican: [
    { name_en: 'Gallo Pinto', name_ar: 'جايو بينتو', mealType: 'breakfast', calories: 325, protein: 12.5, carbs: 55, fat: 4.5 },
    { name_en: 'Gallo Pinto with Eggs', name_ar: 'جايو بينتو مع البيض', mealType: 'breakfast', calories: 325, protein: 12.5, carbs: 55, fat: 4.5 },
    { name_en: 'Corn Tortilla Breakfast', name_ar: 'فطور تورتيلا الذرة', mealType: 'breakfast', calories: 545, protein: 14.3, carbs: 111.5, fat: 7 },
    { name_en: 'Sopa Negra', name_ar: 'سوبا نيغرا (شوربة الفاصوليا)', mealType: 'breakfast', calories: 175, protein: 10, carbs: 27.5, fat: 2.5 },
    { name_en: 'Casado', name_ar: 'كاسادو', mealType: 'lunch', calories: 490, protein: 24.5, carbs: 63, fat: 14 },
    { name_en: 'Ceviche Tico', name_ar: 'سيفيتشي تيكو', mealType: 'lunch', calories: 180, protein: 24, carbs: 10, fat: 6 },
    { name_en: 'Black Bean Rice Bowl', name_ar: 'طبق أرز بالفاصوليا السوداء', mealType: 'lunch', calories: 390, protein: 15, carbs: 72, fat: 4.5 },
    { name_en: 'Pinto with Salsa Lizano', name_ar: 'بينتو مع صلصة ليزانو', mealType: 'lunch', calories: 405, protein: 18, carbs: 63, fat: 6 },
    { name_en: 'Olla de Carne', name_ar: 'أويا دي كارني (حساء اللحم)', mealType: 'dinner', calories: 392, protein: 28, carbs: 25.2, fat: 19.6 },
    { name_en: 'Arroz con Pollo Costarricense', name_ar: 'أرز بالدجاج كوستاريكي', mealType: 'dinner', calories: 450, protein: 24, carbs: 51, fat: 15 },
    { name_en: 'Chifrijo', name_ar: 'تشيفريهو', mealType: 'dinner', calories: 504, protein: 22.4, carbs: 56, fat: 19.6 },
    { name_en: 'Rice and Beans with Fried Fish', name_ar: 'أرز وفاصوليا مع سمك مقلي', mealType: 'dinner', calories: 406, protein: 25.2, carbs: 50.4, fat: 11.2 },
    { name_en: 'Fried Plantains', name_ar: 'موز مقلي', mealType: 'snack', calories: 73, protein: 0.5, carbs: 14.4, fat: 2.7 },
    { name_en: 'Tres Leches Cake', name_ar: 'كعكة الحليب الثلاثي', mealType: 'snack', calories: 156, protein: 3.6, carbs: 19.2, fat: 7.2 },
  ],
};
