import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  american: [
    { name_en: 'Pancakes with Maple Syrup', name_ar: 'بان كيك بشراب القيقب', mealType: 'breakfast', calories: 480, protein: 9, carbs: 84, fat: 12 },
    { name_en: 'Scrambled Eggs and Turkey Bacon', name_ar: 'بيض مخفوق مع بيكون ديك رومي', mealType: 'breakfast', calories: 420, protein: 24, carbs: 4, fat: 34 },
    { name_en: 'Waffles with Butter', name_ar: 'وافل بالزبدة', mealType: 'breakfast', calories: 380, protein: 8, carbs: 58, fat: 13 },
    { name_en: 'Cinnamon French Toast', name_ar: 'خبز فرنسي بالقرفة', mealType: 'breakfast', calories: 410, protein: 12, carbs: 60, fat: 15 },
    { name_en: 'Cheeseburger', name_ar: 'تشيز برجر', mealType: 'lunch', calories: 540, protein: 28, carbs: 42, fat: 29 },
    { name_en: 'BBQ Beef Ribs', name_ar: 'أضلاع لحم البقر بالباربكيو', mealType: 'lunch', calories: 620, protein: 42, carbs: 30, fat: 37 },
    { name_en: 'Grilled Salmon', name_ar: 'سلمون مشوي', mealType: 'lunch', calories: 380, protein: 36, carbs: 6, fat: 24 },
    { name_en: 'Caesar Chicken Wrap', name_ar: 'لفة دجاج سيزر', mealType: 'lunch', calories: 450, protein: 30, carbs: 40, fat: 18 },
    { name_en: 'Meatloaf with Mashed Potatoes', name_ar: 'رغيف اللحم مع البطاطا المهروسة', mealType: 'dinner', calories: 560, protein: 34, carbs: 46, fat: 28 },
    { name_en: 'Macaroni and Cheese', name_ar: 'معكرونة بالجبن', mealType: 'dinner', calories: 500, protein: 20, carbs: 52, fat: 24 },
    { name_en: 'Chicken Pot Pie', name_ar: 'فطيرة الدجاج', mealType: 'dinner', calories: 550, protein: 26, carbs: 45, fat: 31 },
    { name_en: 'New England Clam Chowder', name_ar: 'شوربة المحار بني إنجلاند', mealType: 'dinner', calories: 380, protein: 16, carbs: 34, fat: 21 },
    { name_en: 'Chocolate Chip Cookies', name_ar: 'بسكويت برقائق الشوكولاتة', mealType: 'snack', calories: 220, protein: 3, carbs: 30, fat: 11 },
    { name_en: 'Apple Pie Slice', name_ar: 'شريحة فطيرة التفاح', mealType: 'snack', calories: 320, protein: 3, carbs: 46, fat: 14 },
  ],
  mexican: [
    { name_en: 'Huevos Rancheros', name_ar: 'هويفوس رانشيروس', mealType: 'breakfast', calories: 420, protein: 20, carbs: 32, fat: 24 },
    { name_en: 'Chilaquiles with Eggs', name_ar: 'تشيلاكيليس مع البيض', mealType: 'breakfast', calories: 460, protein: 18, carbs: 48, fat: 22 },
    { name_en: 'Breakfast Burrito', name_ar: 'بوريتو الفطور', mealType: 'breakfast', calories: 520, protein: 26, carbs: 52, fat: 24 },
    { name_en: 'Huevos a la Mexicana', name_ar: 'بيض على الطريقة المكسيكية', mealType: 'breakfast', calories: 320, protein: 19, carbs: 10, fat: 23 },
    { name_en: 'Tacos al Pastor', name_ar: 'تاكو آل باستور', mealType: 'lunch', calories: 480, protein: 26, carbs: 44, fat: 20 },
    { name_en: 'Enchiladas Verdes', name_ar: 'إنتشلاداس فيردي', mealType: 'lunch', calories: 520, protein: 28, carbs: 50, fat: 23 },
    { name_en: 'Burrito Bowl', name_ar: 'طبق بوريتو', mealType: 'lunch', calories: 560, protein: 32, carbs: 62, fat: 18 },
    { name_en: 'Quesadilla de Pollo', name_ar: 'كيساديلا الدجاج', mealType: 'lunch', calories: 470, protein: 28, carbs: 44, fat: 20 },
    { name_en: 'Carne Asada', name_ar: 'كارني أسادا', mealType: 'dinner', calories: 550, protein: 48, carbs: 16, fat: 32 },
    { name_en: 'Pozole Rojo', name_ar: 'بوزولي روخو', mealType: 'dinner', calories: 420, protein: 30, carbs: 40, fat: 17 },
    { name_en: 'Chiles Rellenos', name_ar: 'تشيليس ريينوس', mealType: 'dinner', calories: 480, protein: 24, carbs: 36, fat: 28 },
    { name_en: 'Mole Poblano with Chicken', name_ar: 'موليه بوبلانو مع الدجاج', mealType: 'dinner', calories: 560, protein: 38, carbs: 36, fat: 30 },
    { name_en: 'Churros', name_ar: 'تشوروس', mealType: 'snack', calories: 300, protein: 4, carbs: 42, fat: 14 },
    { name_en: 'Tamales', name_ar: 'تاماليس', mealType: 'snack', calories: 280, protein: 8, carbs: 34, fat: 13 },
  ],
  canadian: [
    { name_en: 'Maple Pancakes', name_ar: 'فطائر بالشراب القيقبي', mealType: 'breakfast', calories: 500, protein: 10, carbs: 88, fat: 12 },
    { name_en: 'Peameal Beef Bacon Sandwich', name_ar: 'ساندويتش بيكون لحم بقري', mealType: 'breakfast', calories: 430, protein: 24, carbs: 50, fat: 15 },
    { name_en: 'Beaver Tails', name_ar: 'بيفر تيلز (حلوى البيور)', mealType: 'breakfast', calories: 380, protein: 6, carbs: 60, fat: 13 },
    { name_en: 'Oatmeal with Maple Syrup', name_ar: 'شوفان بشراب القيقب', mealType: 'breakfast', calories: 280, protein: 10, carbs: 52, fat: 5 },
    { name_en: 'Poutine', name_ar: 'بوتين', mealType: 'lunch', calories: 720, protein: 20, carbs: 82, fat: 36 },
    { name_en: 'Montreal Smoked Meat Sandwich', name_ar: 'ساندويتش اللحم المدخن بمونتريال', mealType: 'lunch', calories: 530, protein: 34, carbs: 48, fat: 22 },
    { name_en: 'Tourtière', name_ar: 'تورتيير (فطيرة اللحم)', mealType: 'lunch', calories: 560, protein: 26, carbs: 44, fat: 32 },
    { name_en: 'Nova Scotia Lobster Roll', name_ar: 'لفة الكركند نوفا سكوشا', mealType: 'lunch', calories: 460, protein: 30, carbs: 38, fat: 21 },
    { name_en: 'Maple Glazed Salmon', name_ar: 'سلمون بطلاء القيقب', mealType: 'dinner', calories: 420, protein: 36, carbs: 22, fat: 21 },
    { name_en: 'B.C. Salmon Bake', name_ar: 'سلمون مطهو على طريقة كولومبيا البريطانية', mealType: 'dinner', calories: 440, protein: 38, carbs: 20, fat: 23 },
    { name_en: 'Butter Chicken Poutine', name_ar: 'بوتين بالدجاج بالزبدة', mealType: 'dinner', calories: 690, protein: 28, carbs: 74, fat: 32 },
    { name_en: 'Shepherd\'s Pie', name_ar: 'فطيرة الراعي', mealType: 'dinner', calories: 520, protein: 26, carbs: 50, fat: 24 },
    { name_en: 'Butter Tarts', name_ar: 'فطائر الزبدة', mealType: 'snack', calories: 260, protein: 3, carbs: 34, fat: 13 },
    { name_en: 'Nanaimo Bar', name_ar: 'لوح نانيمو', mealType: 'snack', calories: 330, protein: 4, carbs: 38, fat: 19 },
  ],
  cuban: [
    { name_en: 'Cuban Breakfast Tostadas', name_ar: 'توستادا على الفطور الكوبي', mealType: 'breakfast', calories: 300, protein: 10, carbs: 38, fat: 13 },
    { name_en: 'Cafe con Leche with Bread', name_ar: 'قهوة بالحليب مع الخبز', mealType: 'breakfast', calories: 220, protein: 9, carbs: 32, fat: 7 },
    { name_en: 'Cuban Frittata', name_ar: 'فريتاتا كوبية', mealType: 'breakfast', calories: 340, protein: 22, carbs: 10, fat: 23 },
    { name_en: 'Mangu con Huevos', name_ar: 'مانجو مع البيض', mealType: 'breakfast', calories: 380, protein: 14, carbs: 64, fat: 9 },
    { name_en: 'Cubano Sandwich', name_ar: 'ساندويتش كوبانو', mealType: 'lunch', calories: 520, protein: 30, carbs: 50, fat: 21 },
    { name_en: 'Medianoche Sandwich', name_ar: 'ساندويتش ميديانونشي', mealType: 'lunch', calories: 480, protein: 26, carbs: 52, fat: 19 },
    { name_en: 'Black Bean Soup', name_ar: 'شوربة الفاصوليا السوداء', mealType: 'lunch', calories: 260, protein: 14, carbs: 46, fat: 3 },
    { name_en: 'Ropa Vieja with Rice', name_ar: 'روبا فييها مع الأرز', mealType: 'lunch', calories: 480, protein: 32, carbs: 44, fat: 20 },
    { name_en: 'Moros y Cristianos', name_ar: 'موروس إي كريستيانوس', mealType: 'dinner', calories: 330, protein: 12, carbs: 62, fat: 4 },
    { name_en: 'Lechon Asado', name_ar: 'ليشون أسادو (لحم مشوي)', mealType: 'dinner', calories: 560, protein: 46, carbs: 14, fat: 37 },
    { name_en: 'Picadillo Cubano', name_ar: 'بيكاديو كوبانو', mealType: 'dinner', calories: 460, protein: 30, carbs: 42, fat: 20 },
    { name_en: 'Arroz con Pollo', name_ar: 'أرز بالدجاج', mealType: 'dinner', calories: 520, protein: 32, carbs: 60, fat: 17 },
    { name_en: 'Tostones', name_ar: 'توستونيس', mealType: 'snack', calories: 220, protein: 2, carbs: 38, fat: 8 },
    { name_en: 'Cuban Flan', name_ar: 'فلان كوبي', mealType: 'snack', calories: 280, protein: 7, carbs: 44, fat: 9 },
  ],
  jamaican: [
    { name_en: 'Ackee and Saltfish', name_ar: 'أكي مع السمك المملح', mealType: 'breakfast', calories: 350, protein: 24, carbs: 26, fat: 18 },
    { name_en: 'Jamaican Cornmeal Porridge', name_ar: 'عصيدة الذرة الجامايكية', mealType: 'breakfast', calories: 320, protein: 8, carbs: 56, fat: 8 },
    { name_en: 'Callaloo and Johnnycakes', name_ar: 'كالالو مع جوني كيك', mealType: 'breakfast', calories: 340, protein: 12, carbs: 48, fat: 12 },
    { name_en: 'Fried Dumplings with Eggs', name_ar: 'زلابية مقلية مع البيض', mealType: 'breakfast', calories: 400, protein: 14, carbs: 60, fat: 13 },
    { name_en: 'Jerk Chicken', name_ar: 'دجاج جيرك', mealType: 'lunch', calories: 430, protein: 38, carbs: 18, fat: 24 },
    { name_en: 'Jamaican Beef Pattie', name_ar: 'باتي لحم بقري جامايكي', mealType: 'lunch', calories: 470, protein: 16, carbs: 46, fat: 25 },
    { name_en: 'Brown Stew Chicken', name_ar: 'دجاج بيني ستيو', mealType: 'lunch', calories: 450, protein: 34, carbs: 28, fat: 23 },
    { name_en: 'Curry Chicken with Rice and Peas', name_ar: 'دجاج بالكاري مع أرز وبازلاء', mealType: 'lunch', calories: 560, protein: 36, carbs: 58, fat: 20 },
    { name_en: 'Oxtail Stew', name_ar: 'يخنة ذيل الثور', mealType: 'dinner', calories: 620, protein: 42, carbs: 40, fat: 34 },
    { name_en: 'Curry Goat', name_ar: 'ماعز بالكاري', mealType: 'dinner', calories: 540, protein: 38, carbs: 22, fat: 34 },
    { name_en: 'Rice and Peas with Jerk Chicken', name_ar: 'أرز وبازلاء مع دجاج جيرك', mealType: 'dinner', calories: 550, protein: 30, carbs: 60, fat: 21 },
    { name_en: 'Escovitch Fish', name_ar: 'سمك إسكوفيتش', mealType: 'dinner', calories: 420, protein: 34, carbs: 24, fat: 22 },
    { name_en: 'Jamaican Pattie', name_ar: 'باتي جامايكي', mealType: 'snack', calories: 300, protein: 10, carbs: 30, fat: 16 },
    { name_en: 'Grater Cake', name_ar: 'كعكة الجزر المبشور', mealType: 'snack', calories: 250, protein: 3, carbs: 48, fat: 6 },
  ],
  costa_rican: [
    { name_en: 'Gallo Pinto', name_ar: 'جايو بينتو', mealType: 'breakfast', calories: 380, protein: 12, carbs: 68, fat: 7 },
    { name_en: 'Gallo Pinto with Eggs', name_ar: 'جايو بينتو مع البيض', mealType: 'breakfast', calories: 460, protein: 18, carbs: 70, fat: 12 },
    { name_en: 'Corn Tortilla Breakfast', name_ar: 'فطور تورتيلا الذرة', mealType: 'breakfast', calories: 290, protein: 8, carbs: 46, fat: 8 },
    { name_en: 'Sopa Negra', name_ar: 'سوبا نيغرا (شوربة الفاصوليا)', mealType: 'breakfast', calories: 240, protein: 12, carbs: 40, fat: 4 },
    { name_en: 'Casado', name_ar: 'كاسادو', mealType: 'lunch', calories: 620, protein: 34, carbs: 78, fat: 18 },
    { name_en: 'Ceviche Tico', name_ar: 'سيفيتشي تيكو', mealType: 'lunch', calories: 260, protein: 30, carbs: 20, fat: 7 },
    { name_en: 'Black Bean Rice Bowl', name_ar: 'طبق أرز بالفاصوليا السوداء', mealType: 'lunch', calories: 480, protein: 18, carbs: 76, fat: 12 },
    { name_en: 'Pinto with Salsa Lizano', name_ar: 'بينتو مع صلصة ليزانو', mealType: 'lunch', calories: 410, protein: 13, carbs: 74, fat: 8 },
    { name_en: 'Olla de Carne', name_ar: 'أويا دي كارني (حساء اللحم)', mealType: 'dinner', calories: 380, protein: 28, carbs: 36, fat: 15 },
    { name_en: 'Arroz con Pollo Costarricense', name_ar: 'أرز بالدجاج كوستاريكي', mealType: 'dinner', calories: 520, protein: 30, carbs: 64, fat: 16 },
    { name_en: 'Chifrijo', name_ar: 'تشيفريهو', mealType: 'dinner', calories: 540, protein: 24, carbs: 56, fat: 24 },
    { name_en: 'Rice and Beans with Fried Fish', name_ar: 'أرز وفاصوليا مع سمك مقلي', mealType: 'dinner', calories: 560, protein: 36, carbs: 66, fat: 17 },
    { name_en: 'Fried Plantains', name_ar: 'موز مقلي', mealType: 'snack', calories: 220, protein: 1, carbs: 48, fat: 5 },
    { name_en: 'Tres Leches Cake', name_ar: 'كعكة الحليب الثلاثي', mealType: 'snack', calories: 380, protein: 7, carbs: 48, fat: 18 },
  ],
};
