import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  egyptian: [
    { name_en: 'Foul Medames with Olive Oil', name_ar: 'فول مدمس بزيت الزيتون', mealType: 'breakfast', calories: 250, protein: 14, carbs: 28, fat: 9 },
    { name_en: 'Egyptian Taameya Falafel', name_ar: 'طعمية', mealType: 'breakfast', calories: 320, protein: 12, carbs: 34, fat: 16 },
    { name_en: 'Alexandrian Eggs', name_ar: 'بيض إسكندراني', mealType: 'breakfast', calories: 240, protein: 16, carbs: 6, fat: 17 },
    { name_en: 'Feteer Baladi with Honey', name_ar: 'فطير بلدي بالعسل', mealType: 'breakfast', calories: 350, protein: 8, carbs: 40, fat: 18 },
    { name_en: 'Koshari', name_ar: 'كشري', mealType: 'lunch', calories: 520, protein: 18, carbs: 88, fat: 12 },
    { name_en: 'Egyptian Hawawshi', name_ar: 'حواوشي', mealType: 'lunch', calories: 420, protein: 24, carbs: 45, fat: 16 },
    { name_en: 'Molokhia with Chicken and Rice', name_ar: 'ملوخية بالفراخ والأرز', mealType: 'lunch', calories: 380, protein: 30, carbs: 35, fat: 13 },
    { name_en: 'Egyptian Fatta with Lamb', name_ar: 'فتة', mealType: 'lunch', calories: 450, protein: 25, carbs: 48, fat: 16 },
    { name_en: 'Stuffed Vine Leaves', name_ar: 'محشي ورق عنب', mealType: 'dinner', calories: 300, protein: 10, carbs: 38, fat: 12 },
    { name_en: 'Grilled Kofta with Rice', name_ar: 'كفتة مشوية بالأرز', mealType: 'dinner', calories: 480, protein: 32, carbs: 35, fat: 22 },
    { name_en: 'Stuffed Pigeon with Freekeh', name_ar: 'حمام محشي', mealType: 'dinner', calories: 430, protein: 34, carbs: 30, fat: 18 },
    { name_en: 'Egyptian Shish Tawook', name_ar: 'شيش طاووق', mealType: 'dinner', calories: 420, protein: 38, carbs: 18, fat: 22 },
    { name_en: 'Basbousa Semolina Cake', name_ar: 'بسبوسة', mealType: 'snack', calories: 280, protein: 4, carbs: 48, fat: 9 },
    { name_en: 'Ghorayebah Shortbread', name_ar: 'غريبة', mealType: 'snack', calories: 220, protein: 3, carbs: 26, fat: 12 },
  ],
  libyan: [
    { name_en: 'Asida with Honey and Ghee', name_ar: 'عصيدة بالعسل', mealType: 'breakfast', calories: 320, protein: 5, carbs: 52, fat: 11 },
    { name_en: 'Libyan Shakshouka', name_ar: 'شكشوكة ليبية', mealType: 'breakfast', calories: 260, protein: 14, carbs: 15, fat: 16 },
    { name_en: 'Couscous with Milk', name_ar: 'كسكسي بالحليب', mealType: 'breakfast', calories: 330, protein: 9, carbs: 58, fat: 8 },
    { name_en: 'Tishkishti Semolina Sweet', name_ar: 'تشكيشتي', mealType: 'breakfast', calories: 290, protein: 4, carbs: 46, fat: 10 },
    { name_en: 'Bazin with Lamb and Tomato Sauce', name_ar: 'بازين باللحم', mealType: 'lunch', calories: 560, protein: 32, carbs: 55, fat: 24 },
    { name_en: 'Libyan Couscous with Meat', name_ar: 'كسكسي بالقدرة', mealType: 'lunch', calories: 540, protein: 28, carbs: 65, fat: 20 },
    { name_en: 'Mbakbaka Spicy Pasta', name_ar: 'مبكبكة', mealType: 'lunch', calories: 460, protein: 20, carbs: 70, fat: 11 },
    { name_en: 'Rice with Vegetables', name_ar: 'رز بالخضرة', mealType: 'lunch', calories: 360, protein: 9, carbs: 62, fat: 9 },
    { name_en: 'Libyan Grilled Lamb Liver', name_ar: 'كبدة مشوية ليبية', mealType: 'dinner', calories: 380, protein: 30, carbs: 12, fat: 24 },
    { name_en: 'Stuffed Vine Leaves', name_ar: 'محشي ورق عنب', mealType: 'dinner', calories: 300, protein: 10, carbs: 38, fat: 12 },
    { name_en: 'Grilled Chicken with Potatoes', name_ar: 'دجاج مشوي بالبطاطا', mealType: 'dinner', calories: 400, protein: 32, carbs: 30, fat: 15 },
    { name_en: 'Lamb and Okra Stew', name_ar: 'بامية باللحم', mealType: 'dinner', calories: 430, protein: 28, carbs: 28, fat: 23 },
    { name_en: 'Ghrayba Cookies', name_ar: 'غريبة', mealType: 'snack', calories: 220, protein: 3, carbs: 26, fat: 12 },
    { name_en: 'Rice Pudding', name_ar: 'رز بالحليب', mealType: 'snack', calories: 260, protein: 6, carbs: 44, fat: 7 },
  ],
  tunisian: [
    { name_en: 'Lablabi Chickpea Soup', name_ar: 'لبلابي', mealType: 'breakfast', calories: 420, protein: 20, carbs: 58, fat: 12 },
    { name_en: 'Ojja Merguez and Eggs', name_ar: 'أوجة مرقاز', mealType: 'breakfast', calories: 330, protein: 20, carbs: 8, fat: 24 },
    { name_en: 'Brik a l Oeuf', name_ar: 'بريك بالبيض', mealType: 'breakfast', calories: 280, protein: 12, carbs: 24, fat: 16 },
    { name_en: 'Masfouf Sweet Couscous', name_ar: 'كسكسي مسفوف بالحليب', mealType: 'breakfast', calories: 340, protein: 10, carbs: 60, fat: 8 },
    { name_en: 'Couscous with Lamb and Vegetables', name_ar: 'كسكسي بالخضرة واللحم', mealType: 'lunch', calories: 580, protein: 32, carbs: 70, fat: 19 },
    { name_en: 'Tunisian Mlukhia Stew', name_ar: 'ملوخية تونسية', mealType: 'lunch', calories: 400, protein: 25, carbs: 24, fat: 23 },
    { name_en: 'Kafteji Fried Vegetables', name_ar: 'كفتاجي', mealType: 'lunch', calories: 380, protein: 13, carbs: 42, fat: 19 },
    { name_en: 'Tunisian Tagine', name_ar: 'طاجين تونسي', mealType: 'lunch', calories: 350, protein: 24, carbs: 12, fat: 23 },
    { name_en: 'Grilled Fish with Harissa', name_ar: 'سمك مشوي بالهريسة', mealType: 'dinner', calories: 350, protein: 36, carbs: 9, fat: 19 },
    { name_en: 'Chakchouka', name_ar: 'شكشوكة', mealType: 'dinner', calories: 260, protein: 14, carbs: 15, fat: 16 },
    { name_en: 'Osbane Stuffed Tripe', name_ar: 'عصبان', mealType: 'dinner', calories: 420, protein: 26, carbs: 24, fat: 25 },
    { name_en: 'Couscous with Fish', name_ar: 'كسكسي بالسمك', mealType: 'dinner', calories: 540, protein: 34, carbs: 62, fat: 17 },
    { name_en: 'Brik with Tuna', name_ar: 'بريك بالتونة', mealType: 'snack', calories: 270, protein: 14, carbs: 22, fat: 14 },
    { name_en: 'Makroud with Dates', name_ar: 'مخرود', mealType: 'snack', calories: 250, protein: 3, carbs: 38, fat: 10 },
  ],
  algerian: [
    { name_en: 'Mhadjeb Stuffed Flatbread', name_ar: 'محجب', mealType: 'breakfast', calories: 320, protein: 7, carbs: 46, fat: 12 },
    { name_en: 'Baghrir with Honey and Butter', name_ar: 'بغرير بالعسل', mealType: 'breakfast', calories: 280, protein: 6, carbs: 42, fat: 10 },
    { name_en: 'Karantika Chickpea Flan', name_ar: 'كارنتيكا', mealType: 'breakfast', calories: 260, protein: 9, carbs: 26, fat: 13 },
    { name_en: 'Fava Beans with Cumin', name_ar: 'فول بالكمون', mealType: 'breakfast', calories: 260, protein: 14, carbs: 30, fat: 9 },
    { name_en: 'Couscous with Lamb and Vegetables', name_ar: 'كسكسي باللحم', mealType: 'lunch', calories: 580, protein: 32, carbs: 72, fat: 18 },
    { name_en: 'Chakhchoukha', name_ar: 'شخشوخة', mealType: 'lunch', calories: 520, protein: 22, carbs: 62, fat: 20 },
    { name_en: 'Algerian Chicken and Olive Tagine', name_ar: 'طاجين الزيتون', mealType: 'lunch', calories: 380, protein: 30, carbs: 16, fat: 22 },
    { name_en: 'Boulfaf Grilled Liver Skewers', name_ar: 'بولفاف', mealType: 'lunch', calories: 350, protein: 27, carbs: 5, fat: 24 },
    { name_en: 'Rechta with Chicken and Chickpeas', name_ar: 'رشتة بالدجاج', mealType: 'dinner', calories: 470, protein: 24, carbs: 62, fat: 14 },
    { name_en: 'Chorba Frik Soup', name_ar: 'شوربة فريك', mealType: 'dinner', calories: 280, protein: 16, carbs: 32, fat: 10 },
    { name_en: 'Berkoukes with Lamb', name_ar: 'بركوكس', mealType: 'dinner', calories: 480, protein: 26, carbs: 56, fat: 17 },
    { name_en: 'Bourek with Meat and Egg', name_ar: 'بوراك باللحم', mealType: 'dinner', calories: 320, protein: 13, carbs: 28, fat: 17 },
    { name_en: 'Mtakem Sweet Fritters', name_ar: 'متقم', mealType: 'snack', calories: 260, protein: 4, carbs: 34, fat: 13 },
    { name_en: 'Griwech Honey Pastry', name_ar: 'قراوش', mealType: 'snack', calories: 380, protein: 5, carbs: 44, fat: 20 },
  ],
  moroccan: [
    { name_en: 'Msemen with Honey', name_ar: 'مسمن بالعسل', mealType: 'breakfast', calories: 320, protein: 7, carbs: 46, fat: 12 },
    { name_en: 'Baghrir Pancakes', name_ar: 'بغرير', mealType: 'breakfast', calories: 260, protein: 6, carbs: 38, fat: 10 },
    { name_en: 'Amlou with Bread', name_ar: 'أملو', mealType: 'breakfast', calories: 300, protein: 6, carbs: 24, fat: 20 },
    { name_en: 'Bissara Fava Soup', name_ar: 'بيسارة', mealType: 'breakfast', calories: 300, protein: 15, carbs: 38, fat: 10 },
    { name_en: 'Couscous with Seven Vegetables', name_ar: 'كسكسي بالخضار السبعة', mealType: 'lunch', calories: 520, protein: 18, carbs: 82, fat: 12 },
    { name_en: 'Rfissa with Lentils and Chicken', name_ar: 'رفيسة', mealType: 'lunch', calories: 540, protein: 28, carbs: 62, fat: 19 },
    { name_en: 'Kefta and Egg Tagine', name_ar: 'طاجين الكفتة', mealType: 'lunch', calories: 420, protein: 28, carbs: 22, fat: 24 },
    { name_en: 'Chicken Tagine with Preserved Lemon', name_ar: 'طاجين الدجاج بالحامض مصير', mealType: 'lunch', calories: 400, protein: 32, carbs: 18, fat: 22 },
    { name_en: 'Harira Soup with Dates', name_ar: 'حريرة', mealType: 'dinner', calories: 300, protein: 14, carbs: 42, fat: 9 },
    { name_en: 'Chicken Bastilla', name_ar: 'بسطيلة', mealType: 'dinner', calories: 450, protein: 20, carbs: 38, fat: 24 },
    { name_en: 'Lamb Tagine with Prunes and Almonds', name_ar: 'طاجين اللحم بالبرقوق واللوز', mealType: 'dinner', calories: 550, protein: 30, carbs: 46, fat: 27 },
    { name_en: 'Grilled Sardine Kefta', name_ar: 'كفتة السردين', mealType: 'dinner', calories: 330, protein: 28, carbs: 15, fat: 18 },
    { name_en: 'Chebakia Sesame Pastry', name_ar: 'شباكية', mealType: 'snack', calories: 430, protein: 5, carbs: 52, fat: 23 },
    { name_en: 'Sellou Flour and Nut Mix', name_ar: 'سلو', mealType: 'snack', calories: 350, protein: 7, carbs: 38, fat: 20 },
  ],
};