import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  brazilian: [
    { name_en: 'Pão de Queijo', name_ar: 'باودي كويجو', mealType: 'breakfast', calories: 180, protein: 4, carbs: 20, fat: 9 },
    { name_en: 'Tapioca de Queijo', name_ar: 'تابيوكا بالجبن', mealType: 'breakfast', calories: 330, protein: 10.5, carbs: 48, fat: 10.5 },
    { name_en: 'Bolo de Fubá', name_ar: 'كعكة دقيق الذرة', mealType: 'breakfast', calories: 220, protein: 4, carbs: 34, fat: 8 },
    { name_en: 'Açaí na Tigela', name_ar: 'أكاي في الوعاء', mealType: 'breakfast', calories: 200, protein: 3, carbs: 34, fat: 6 },
    { name_en: 'Feijoada', name_ar: 'فيجودا', mealType: 'lunch', calories: 550, protein: 40, carbs: 30, fat: 27.5 },
    { name_en: 'Picanha', name_ar: 'بيكانا', mealType: 'lunch', calories: 432, protein: 34.2, carbs: 0, fat: 32.4 },
    { name_en: 'Moqueca de Peixe', name_ar: 'موكيكا السمك', mealType: 'lunch', calories: 425, protein: 37.5, carbs: 20, fat: 20 },
    { name_en: 'Galinhada', name_ar: 'غالينهادا', mealType: 'lunch', calories: 600, protein: 42, carbs: 66, fat: 19.5 },
    { name_en: 'Strogonoff de Frango', name_ar: 'ستروجونوف الدجاج', mealType: 'dinner', calories: 374, protein: 35.2, carbs: 22, fat: 17.6 },
    { name_en: 'Churrasco', name_ar: 'شوراسكو', mealType: 'dinner', calories: 625, protein: 55, carbs: 5, fat: 42.5 },
    { name_en: 'Bobó de Camarão', name_ar: 'بوبو الجمبري', mealType: 'dinner', calories: 460, protein: 30, carbs: 34, fat: 23 },
    { name_en: 'Virado à Paulista', name_ar: 'فيرادو باوليستا', mealType: 'dinner', calories: 500, protein: 28, carbs: 50, fat: 21 },
    { name_en: 'Coxinha', name_ar: 'كوكسينيا', mealType: 'snack', calories: 252, protein: 9, carbs: 27, fat: 11.7 },
    { name_en: 'Brigadeiro', name_ar: 'بريغاديرو', mealType: 'snack', calories: 114, protein: 1.8, carbs: 16.5, fat: 4.8 },
  ],
  argentinian: [
    { name_en: 'Medialunas', name_ar: 'ميديالوناس', mealType: 'breakfast', calories: 330, protein: 7, carbs: 46, fat: 13 },
    { name_en: 'Facturas', name_ar: 'فاكتوراس', mealType: 'breakfast', calories: 825, protein: 17.5, carbs: 115, fat: 32.5 },
    { name_en: 'Tostadas con Mermelada', name_ar: 'توستاداس بالمربى', mealType: 'breakfast', calories: 450, protein: 12.5, carbs: 80, fat: 10 },
    { name_en: 'Mate Cocido con Pan', name_ar: 'ماتيه كوكيدو مع الخبز', mealType: 'breakfast', calories: 350, protein: 12.5, carbs: 55, fat: 8.8 },
    { name_en: 'Milanesa a la Napolitana', name_ar: 'ميلانيزا نابوليتانا', mealType: 'lunch', calories: 572, protein: 39.6, carbs: 35.2, fat: 28.6 },
    { name_en: 'Asado', name_ar: 'أسادو', mealType: 'lunch', calories: 700, protein: 55, carbs: 2.5, fat: 52.5 },
    { name_en: 'Locro', name_ar: 'لوكرو', mealType: 'lunch', calories: 540, protein: 27, carbs: 60, fat: 21 },
    { name_en: 'Guiso de Lentejas', name_ar: 'يخنة العدس', mealType: 'lunch', calories: 480, protein: 27, carbs: 60, fat: 15 },
    { name_en: 'Parrillada', name_ar: 'باريلادا', mealType: 'dinner', calories: 750, protein: 63, carbs: 3, fat: 54 },
    { name_en: 'Bife de Chorizo', name_ar: 'شريحة لحم تشوريزو', mealType: 'dinner', calories: 728, protein: 58.8, carbs: 0, fat: 53.2 },
    { name_en: 'Sorrentinos', name_ar: 'سورينتينوس', mealType: 'dinner', calories: 616, protein: 30.8, carbs: 72.8, fat: 22.4 },
    { name_en: 'Matambre a la Pizza', name_ar: 'ماتامبري بيتزا', mealType: 'dinner', calories: 745, protein: 30.8, carbs: 92.4, fat: 27.4 },
    { name_en: 'Empanada de Carne', name_ar: 'إمبانادا باللحم', mealType: 'snack', calories: 360, protein: 12, carbs: 33.6, fat: 19.2 },
    { name_en: 'Alfajores', name_ar: 'ألفاخور', mealType: 'snack', calories: 336, protein: 4.8, carbs: 46.4, fat: 14.4 },
  ],
  peruvian: [
    { name_en: 'Tamales', name_ar: 'تاماليس', mealType: 'breakfast', calories: 312, protein: 6, carbs: 28.8, fat: 20.4 },
    { name_en: 'Pan con Chicharrón', name_ar: 'خبز مع تشيتشارون', mealType: 'breakfast', calories: 320, protein: 18, carbs: 32, fat: 13 },
    { name_en: 'Pan con Pavo', name_ar: 'خبز مع الديك الرومي', mealType: 'breakfast', calories: 650, protein: 35, carbs: 80, fat: 22.5 },
    { name_en: 'Caldo de Gallina', name_ar: 'شوربة الدجاج', mealType: 'breakfast', calories: 300, protein: 25, carbs: 20, fat: 12.5 },
    { name_en: 'Ceviche', name_ar: 'سيفيتشي', mealType: 'lunch', calories: 180, protein: 26, carbs: 10, fat: 4 },
    { name_en: 'Lomo Saltado', name_ar: 'لومو سالتادو', mealType: 'lunch', calories: 450, protein: 36, carbs: 36, fat: 18 },
    { name_en: 'Aji de Gallina', name_ar: 'أخي دي غايينا', mealType: 'lunch', calories: 425, protein: 32.5, carbs: 25, fat: 22.5 },
    { name_en: 'Arroz con Pollo', name_ar: 'أرز بالدجاج', mealType: 'lunch', calories: 450, protein: 24, carbs: 51, fat: 15 },
    { name_en: 'Seco de Res', name_ar: 'سيكو دي ريس', mealType: 'dinner', calories: 476, protein: 30.8, carbs: 33.6, fat: 25.2 },
    { name_en: 'Cau Cau', name_ar: 'كاو كاو', mealType: 'dinner', calories: 420, protein: 33.6, carbs: 39.2, fat: 16.8 },
    { name_en: 'Pollo a la Brasa', name_ar: 'دجاج مشوي', mealType: 'dinner', calories: 525, protein: 45, carbs: 7.5, fat: 35 },
    { name_en: 'Chupe de Camarones', name_ar: 'تشوبي دي جمبري', mealType: 'dinner', calories: 420, protein: 33.6, carbs: 39.2, fat: 15.4 },
    { name_en: 'Causa Rellena', name_ar: 'كاوسا ريينا', mealType: 'snack', calories: 132, protein: 3.6, carbs: 16.8, fat: 6 },
    { name_en: 'Picarones', name_ar: 'بيكارونيس', mealType: 'snack', calories: 180, protein: 3, carbs: 30, fat: 5.4 },
  ],
  colombian: [
    { name_en: 'Arepa con Huevo', name_ar: 'أريبا بالبيض', mealType: 'breakfast', calories: 360, protein: 12, carbs: 45, fat: 15 },
    { name_en: 'Calentado', name_ar: 'كالينتادو', mealType: 'breakfast', calories: 450, protein: 20, carbs: 65, fat: 15 },
    { name_en: 'Tamales Tolimenses', name_ar: 'تاماليس توليمنسيس', mealType: 'breakfast', calories: 650, protein: 12.5, carbs: 60, fat: 42.5 },
    { name_en: 'Chocolate con Almojábana', name_ar: 'شوكولاتة مع الموخابانا', mealType: 'breakfast', calories: 240, protein: 6, carbs: 34, fat: 9 },
    { name_en: 'Bandeja Paisa', name_ar: 'باندخا بايسا', mealType: 'lunch', calories: 1040, protein: 56, carbs: 104, fat: 44 },
    { name_en: 'Ajiaco', name_ar: 'أخياكو', mealType: 'lunch', calories: 390, protein: 21, carbs: 54, fat: 12 },
    { name_en: 'Sancocho', name_ar: 'سانكوتشو', mealType: 'lunch', calories: 360, protein: 27, carbs: 30, fat: 15 },
    { name_en: 'Lechona', name_ar: 'ليتشونا', mealType: 'lunch', calories: 840, protein: 39, carbs: 72, fat: 45 },
    { name_en: 'Picada Colombiana', name_ar: 'بيكادا كولومبيانا', mealType: 'dinner', calories: 700, protein: 36.4, carbs: 42, fat: 42 },
    { name_en: 'Mondongo', name_ar: 'موندونغو', mealType: 'dinner', calories: 364, protein: 28, carbs: 22.4, fat: 16.8 },
    { name_en: 'Trucha Frita con Arroz y Patacones', name_ar: 'تراوت مقلي مع أرز وباتاكون', mealType: 'dinner', calories: 633, protein: 33.6, carbs: 36.4, fat: 39.2 },
    { name_en: 'Cazuela de Mariscos', name_ar: 'كازويلا دي ماريسكوس', mealType: 'dinner', calories: 392, protein: 36.4, carbs: 28, fat: 16.8 },
    { name_en: 'Buñuelos', name_ar: 'بونويلوس', mealType: 'snack', calories: 180, protein: 4, carbs: 18, fat: 10 },
    { name_en: 'Empanada Colombiana', name_ar: 'إمبانادا كولومبية', mealType: 'snack', calories: 270, protein: 9, carbs: 25.2, fat: 14.4 },
  ],
  chilean: [
    { name_en: 'Marraqueta con Palta', name_ar: 'ماراكيتا مع الأفوكادو', mealType: 'breakfast', calories: 550, protein: 15, carbs: 75, fat: 22.5 },
    { name_en: 'Pan Amasado con Huevo', name_ar: 'خبز مع البيض', mealType: 'breakfast', calories: 575, protein: 20, carbs: 80, fat: 20 },
    { name_en: 'Hallulla con Mermelada', name_ar: 'هالولا بالمربى', mealType: 'breakfast', calories: 500, protein: 15, carbs: 85, fat: 12.5 },
    { name_en: 'Té con Leche y Sopaipillas', name_ar: 'شاي بالحليب مع سوبايبلاس', mealType: 'breakfast', calories: 240, protein: 5, carbs: 36, fat: 9 },
    { name_en: 'Porotos Granados', name_ar: 'بوروتوس غرنادوس', mealType: 'lunch', calories: 450, protein: 24, carbs: 60, fat: 15 },
    { name_en: 'Pastel de Choclo', name_ar: 'فطيرة الذرة التشيلية', mealType: 'lunch', calories: 425, protein: 20, carbs: 55, fat: 15 },
    { name_en: 'Humitas', name_ar: 'هوميتاس', mealType: 'lunch', calories: 540, protein: 15, carbs: 72, fat: 21 },
    { name_en: 'Cazuela de Vacuno', name_ar: 'كازويلا لحوم البقر', mealType: 'lunch', calories: 420, protein: 30, carbs: 30, fat: 21 },
    { name_en: 'Charquicán', name_ar: 'تشاركيكان', mealType: 'dinner', calories: 430, protein: 24, carbs: 48, fat: 16 },
    { name_en: 'Curanto', name_ar: 'كورانتو', mealType: 'dinner', calories: 504, protein: 36.4, carbs: 39.2, fat: 25.2 },
    { name_en: 'Caldillo de Congrio', name_ar: 'حساء السمك', mealType: 'dinner', calories: 364, protein: 39.2, carbs: 22.4, fat: 14 },
    { name_en: 'Chorrillana', name_ar: 'تشوريينا', mealType: 'dinner', calories: 588, protein: 28, carbs: 50.4, fat: 30.8 },
    { name_en: 'Completo', name_ar: 'كومبليتو', mealType: 'snack', calories: 480, protein: 20, carbs: 60, fat: 18 },
    { name_en: 'Empanada de Pino', name_ar: 'إمبانادا بينو', mealType: 'snack', calories: 360, protein: 12, carbs: 33.6, fat: 19.2 },
  ],
  venezuelan: [
    { name_en: 'Arepa Reina Pepiada', name_ar: 'أريبا ريينا بيبيادا', mealType: 'breakfast', calories: 360, protein: 13.5, carbs: 48, fat: 13.5 },
    { name_en: 'Cachapa', name_ar: 'كاشابا', mealType: 'breakfast', calories: 345, protein: 9, carbs: 51, fat: 12 },
    { name_en: 'Arepa de Perico', name_ar: 'أريبا دي بيريكو', mealType: 'breakfast', calories: 625, protein: 22.5, carbs: 80, fat: 25 },
    { name_en: 'Mandocas', name_ar: 'ماندوكاس', mealType: 'breakfast', calories: 600, protein: 12.5, carbs: 75, fat: 27.5 },
    { name_en: 'Pabellón Criollo', name_ar: 'بابيون كريولو', mealType: 'lunch', calories: 460, protein: 24, carbs: 48, fat: 20 },
    { name_en: 'Hallaca', name_ar: 'هالاكا', mealType: 'lunch', calories: 480, protein: 20, carbs: 48, fat: 24 },
    { name_en: 'Asado Negro', name_ar: 'أسادو نيغرو', mealType: 'lunch', calories: 660, protein: 45, carbs: 42, fat: 36 },
    { name_en: 'Sancocho de Pescado', name_ar: 'سانكوتشو السمك', mealType: 'lunch', calories: 390, protein: 39, carbs: 24, fat: 15 },
    { name_en: 'Pisca Andina', name_ar: 'بيسكا أندينا', mealType: 'dinner', calories: 336, protein: 19.6, carbs: 33.6, fat: 14 },
    { name_en: 'Pasticho', name_ar: 'باستيتشو', mealType: 'dinner', calories: 560, protein: 28, carbs: 61.6, fat: 22.4 },
    { name_en: 'Hervido de Res', name_ar: 'حساء اللحم البقري', mealType: 'dinner', calories: 392, protein: 30.8, carbs: 25.2, fat: 19.6 },
    { name_en: 'Bollo Pelón', name_ar: 'بويو بيلون', mealType: 'dinner', calories: 380, protein: 14, carbs: 48, fat: 15 },
    { name_en: 'Tequeños', name_ar: 'تيكينوس', mealType: 'snack', calories: 320, protein: 9, carbs: 30, fat: 18 },
    { name_en: 'Caraotas Negras Refritas', name_ar: 'كاريوتاس سوداء مقلية', mealType: 'snack', calories: 108, protein: 6, carbs: 15.6, fat: 2.4 },
  ],
};