import type { RegionalFood } from '../cuisineCatalog';

export const FOODS: Record<string, RegionalFood[]> = {
  mediterranean: [
    { name_en: 'Greek Yogurt Parfait', name_ar: 'بارفيه الزبادي اليوناني', mealType: 'breakfast', calories: 320, protein: 20, carbs: 42, fat: 8 },
    { name_en: 'Olive Oil Toast', name_ar: 'خبز محمص بزيت الزيتون', mealType: 'breakfast', calories: 260, protein: 6, carbs: 30, fat: 13 },
    { name_en: 'Shakshuka', name_ar: 'شكشوكة', mealType: 'breakfast', calories: 280, protein: 16, carbs: 15, fat: 17 },
    { name_en: 'Spinach & Feta Omelette', name_ar: 'أومليت بالسبانخ وجبنة الفيتا', mealType: 'breakfast', calories: 330, protein: 21, carbs: 7, fat: 24 },
    { name_en: 'Grilled Salmon', name_ar: 'سلمون مشوي', mealType: 'lunch', calories: 420, protein: 36, carbs: 2, fat: 29 },
    { name_en: 'Fattoush Salad', name_ar: 'سلطة فتوش', mealType: 'lunch', calories: 280, protein: 8, carbs: 34, fat: 13 },
    { name_en: 'Seafood Paella-Style', name_ar: 'باييلا المأكولات البحرية', mealType: 'lunch', calories: 480, protein: 30, carbs: 55, fat: 13 },
    { name_en: 'Chickpea & Vegetable Stew', name_ar: 'يخنة الحمص مع الخضار', mealType: 'lunch', calories: 350, protein: 16, carbs: 48, fat: 11 },
    { name_en: 'Grilled Chicken Souvlaki', name_ar: 'سوفلاكي الدجاج المشوي', mealType: 'dinner', calories: 400, protein: 38, carbs: 8, fat: 23 },
    { name_en: 'Baked Cod with Tomatoes & Olives', name_ar: 'قد مخبوز بالطماطم والزيتون', mealType: 'dinner', calories: 360, protein: 32, carbs: 6, fat: 23 },
    { name_en: 'Stuffed Bell Peppers', name_ar: 'فلفل رومي محشي', mealType: 'dinner', calories: 380, protein: 12, carbs: 45, fat: 17 },
    { name_en: 'Lamb Kofta with Vegetables', name_ar: 'كفتة لحم مع خضار مشوية', mealType: 'dinner', calories: 450, protein: 32, carbs: 10, fat: 30 },
    { name_en: 'Hummus & Vegetable Sticks', name_ar: 'حمص مع أصابع الخضار', mealType: 'snack', calories: 220, protein: 8, carbs: 24, fat: 11 },
    { name_en: 'Feta with Black Olives', name_ar: 'جبنة فيتا مع زيتون أسود', mealType: 'snack', calories: 200, protein: 6, carbs: 4, fat: 19 },
  ],
  keto: [
    { name_en: 'Cheese Omelette', name_ar: 'أومليت بالجبن', mealType: 'breakfast', calories: 350, protein: 24, carbs: 2, fat: 27 },
    { name_en: 'Avocado & Turkey Bacon', name_ar: 'أفوكادو مع بيكون ديك رومي', mealType: 'breakfast', calories: 390, protein: 14, carbs: 8, fat: 34 },
    { name_en: 'Scrambled Eggs with Butter', name_ar: 'بيض مخفوق بالزبدة', mealType: 'breakfast', calories: 330, protein: 20, carbs: 2, fat: 27 },
    { name_en: 'Keto Cheese & Seed Bowl', name_ar: 'طبق الجبن والبذور', mealType: 'breakfast', calories: 300, protein: 22, carbs: 7, fat: 20 },
    { name_en: 'Steak with Butter', name_ar: 'ستيك بالزبدة', mealType: 'lunch', calories: 550, protein: 44, carbs: 1, fat: 40 },
    { name_en: 'Bunless Cheeseburger', name_ar: 'تشيز برجر بدون خبز', mealType: 'lunch', calories: 600, protein: 40, carbs: 3, fat: 46 },
    { name_en: 'Cauliflower Fried Rice', name_ar: 'أرز القرنبيط المقلي', mealType: 'lunch', calories: 220, protein: 12, carbs: 9, fat: 15 },
    { name_en: 'Grilled Salmon with Asparagus', name_ar: 'سلمون مشوي مع الهليون', mealType: 'lunch', calories: 420, protein: 36, carbs: 4, fat: 29 },
    { name_en: 'Turkey Bacon-Wrapped Chicken Thighs', name_ar: 'أفخاذ دجاج ملفوفة ببيكون الديك الرومي', mealType: 'dinner', calories: 520, protein: 38, carbs: 2, fat: 39 },
    { name_en: 'Zucchini Noodles with Beef Marinara', name_ar: 'نودلز الكوسا مع لحم البقر والمارينارا', mealType: 'dinner', calories: 380, protein: 30, carbs: 10, fat: 24 },
    { name_en: 'Garlic Butter Shrimp', name_ar: 'جمبري بزبدة الثوم', mealType: 'dinner', calories: 340, protein: 28, carbs: 4, fat: 24 },
    { name_en: 'Chicken & Cheddar Lettuce Wraps', name_ar: 'لفائف الخس بالدجاج والشيدر', mealType: 'dinner', calories: 420, protein: 34, carbs: 5, fat: 29 },
    { name_en: 'Cheddar Cheese Cubes', name_ar: 'مكعبات جبن الشيدر', mealType: 'snack', calories: 180, protein: 11, carbs: 2, fat: 14 },
    { name_en: 'Mixed Nuts', name_ar: 'مكسرات مشكلة', mealType: 'snack', calories: 220, protein: 7, carbs: 6, fat: 20 },
  ],
  high_protein: [
    { name_en: 'Egg White Scramble with Chicken', name_ar: 'بياض البيض مع الدجاج', mealType: 'breakfast', calories: 420, protein: 42, carbs: 6, fat: 24 },
    { name_en: 'Whey Protein Pancakes', name_ar: 'بان كيك بالبروتين', mealType: 'breakfast', calories: 400, protein: 35, carbs: 40, fat: 10 },
    { name_en: 'Greek Yogurt Protein Bowl', name_ar: 'وعاء الزبادي اليوناني بالبروتين', mealType: 'breakfast', calories: 350, protein: 30, carbs: 35, fat: 10 },
    { name_en: 'Turkey Sausage & Egg Breakfast', name_ar: 'سجق الديك الرومي مع البيض', mealType: 'breakfast', calories: 380, protein: 36, carbs: 8, fat: 22 },
    { name_en: 'Grilled Chicken Breast', name_ar: 'صدر دجاج مشوي', mealType: 'lunch', calories: 430, protein: 45, carbs: 4, fat: 26 },
    { name_en: 'Tuna Steak', name_ar: 'ستيك التونة', mealType: 'lunch', calories: 400, protein: 40, carbs: 2, fat: 25 },
    { name_en: 'Lean Beef Bowl', name_ar: 'وعاء اللحم البقري الخالي من الدهون', mealType: 'lunch', calories: 500, protein: 42, carbs: 45, fat: 16 },
    { name_en: 'Chicken & Rice Protein Bowl', name_ar: 'وعاء الدجاج والأرز بالبروتين', mealType: 'lunch', calories: 520, protein: 44, carbs: 52, fat: 14 },
    { name_en: 'Grilled Salmon Fillet', name_ar: 'فيليه سلمون مشوي', mealType: 'dinner', calories: 460, protein: 40, carbs: 2, fat: 32 },
    { name_en: 'Chicken Burrito Bowl', name_ar: 'وعاء بوريتو الدجاج', mealType: 'dinner', calories: 550, protein: 46, carbs: 48, fat: 18 },
    { name_en: 'Beef Steak with Sweet Potato', name_ar: 'ستيك لحم مع بطاطا حلوة', mealType: 'dinner', calories: 580, protein: 45, carbs: 40, fat: 26 },
    { name_en: 'Turkey Pasta Protein Bowl', name_ar: 'طبق معكرونة الديك الرومي بالبروتين', mealType: 'dinner', calories: 520, protein: 40, carbs: 42, fat: 20 },
    { name_en: 'Cottage Cheese', name_ar: 'جبنة قريش', mealType: 'snack', calories: 150, protein: 24, carbs: 6, fat: 3 },
    { name_en: 'Protein Shake', name_ar: 'مخفوق البروتين', mealType: 'snack', calories: 200, protein: 30, carbs: 8, fat: 4 },
  ],
  vegetarian: [
    { name_en: 'Yogurt Bowl with Fruit & Nuts', name_ar: 'وعاء الزبادي مع الفواكه والمكسرات', mealType: 'breakfast', calories: 320, protein: 18, carbs: 45, fat: 9 },
    { name_en: 'Paneer Scramble on Toast', name_ar: 'بانير مخفوق على الخبز المحمص', mealType: 'breakfast', calories: 360, protein: 24, carbs: 32, fat: 16 },
    { name_en: 'Oatmeal with Berries & Almonds', name_ar: 'شوفان مع التوت واللوز', mealType: 'breakfast', calories: 340, protein: 12, carbs: 52, fat: 10 },
    { name_en: 'Veggie Breakfast Bowl', name_ar: 'وعاء إفطار نباتي', mealType: 'breakfast', calories: 350, protein: 16, carbs: 44, fat: 12 },
    { name_en: 'Falafel Bowl', name_ar: 'وعاء الفلافل', mealType: 'lunch', calories: 480, protein: 18, carbs: 55, fat: 22 },
    { name_en: 'Lentil Soup with Bread', name_ar: 'شوربة العدس مع الخبز', mealType: 'lunch', calories: 400, protein: 20, carbs: 60, fat: 10 },
    { name_en: 'Veggie Burger', name_ar: 'برجر نباتي', mealType: 'lunch', calories: 420, protein: 20, carbs: 45, fat: 18 },
    { name_en: 'Chickpea Salad', name_ar: 'سلطة الحمص', mealType: 'lunch', calories: 380, protein: 16, carbs: 50, fat: 14 },
    { name_en: 'Paneer Tikka with Vegetables', name_ar: 'بانير تيكا مع الخضار', mealType: 'dinner', calories: 420, protein: 25, carbs: 20, fat: 28 },
    { name_en: 'Tofu Stir Fry with Rice', name_ar: 'توفو مقلي مع الأرز', mealType: 'dinner', calories: 450, protein: 22, carbs: 55, fat: 16 },
    { name_en: 'Vegetable Curry with Chickpeas & Rice', name_ar: 'كاري خضار مع الحمص والأرز', mealType: 'dinner', calories: 430, protein: 16, carbs: 62, fat: 14 },
    { name_en: 'Veggie Pasta with Cheese', name_ar: 'معكرونة نباتية بالجبن', mealType: 'dinner', calories: 480, protein: 18, carbs: 65, fat: 16 },
    { name_en: 'Trail Mix', name_ar: 'ترايل مكس', mealType: 'snack', calories: 250, protein: 8, carbs: 20, fat: 16 },
    { name_en: 'Hummus & Pita', name_ar: 'حمص مع خبز البيتا', mealType: 'snack', calories: 240, protein: 8, carbs: 30, fat: 10 },
  ],
};