import { B } from '../chile-base-data/rows.mjs';

export default [
  B('cl-phase-a-064', 'سمك توربوت مخبوز مع الكينوا والطماطم', 'Baked Turbot with Quinoa and Tomato', 'Turbot au four avec quinoa et tomate', 'Rodaballo al horno con quinua y tomate', 'Gebackener Steinbutt mit Quinoa und Tomate', 'fish_seafood', 'dinner', 23, 16, 7, 'baking', 'valparaiso'),
  B('cl-phase-a-065', 'إمبانادا خايبا بالذرة والجبن الطازج', 'Jaiba Empanada with Corn and Fresh Cheese', 'Empanada de jaiba au maïs et fromage frais', 'Empanada de jaiba con choclo y queso fresco', 'Jaiba-Empanada mit Mais und Frischkäse', 'street_snacks', 'lunch', 18, 24, 9, 'baking', 'coquimbo'),
  B('cl-phase-a-066', 'كازويلا السلمون بالبطاطس والقرع والذرة', 'Salmon Cazuela with Potato, Squash and Corn', 'Cazuela de saumon à la pomme de terre, courge et maïs', 'Cazuela de salmón con papa, zapallo y choclo', 'Lachs-Cazuela mit Kartoffel, Kürbis und Mais', 'fish_seafood', 'lunch', 20, 18, 8, 'simmering', 'los_lagos'),
  B('cl-phase-a-067', 'يخنة بوروتوس غرانادوس بالجبن الطازج والريحان', 'Porotos Granados with Quesillo and Basil', 'Porotos granados au quesillo et basilic', 'Porotos granados con quesillo y albahaca', 'Porotos Granados mit Quesillo und Basilikum', 'vegetable_mains', 'lunch', 13, 25, 6, 'stewing', 'maule'),
  B('cl-phase-a-068', 'كالابوركا تشيليّة بلحم البقر والذرة والبطاطس', 'Chilean Calapurca with Beef, Corn and Potato', 'Calapurca chilienne au bœuf, maïs et pomme de terre', 'Calapurca chilena con res, choclo y papa', 'Chilenische Calapurca mit Rind, Mais und Kartoffel', 'soups_stews', 'lunch', 18, 20, 7, 'simmering', 'atacama'),
  B('cl-phase-a-069', 'تشولغاس بميركين مع الكينوا والطماطم', 'Cholgas with Merkén, Quinoa and Tomato', 'Cholgas au merkén, quinoa et tomate', 'Cholgas al merkén con quinua y tomate', 'Cholgas mit Merkén, Quinoa und Tomate', 'fish_seafood', 'dinner', 21, 15, 7, 'sauteing', 'los_lagos'),
  B('cl-phase-a-070', 'موتي بالأفوكادو والبيض المسلوق', 'Mote with Avocado and Poached Egg', 'Mote à l’avocat et à l’œuf poché', 'Mote con palta y huevo pochado', 'Mote mit Avocado und pochiertem Ei', 'breakfast_items', 'breakfast', 12, 25, 10, 'boiling', 'santiago'),
  B('cl-phase-a-071', 'دجاج أرفيخادو بالبصل والبازلاء والجزر', 'Pollo Arvejado with Onion, Peas and Carrot', 'Pollo arvejado à l’oignon, petits pois et carotte', 'Pollo arvejado con cebolla, arvejas y zanahoria', 'Pollo Arvejado mit Zwiebel, Erbsen und Karotte', 'poultry_mains', 'dinner', 23, 15, 7, 'stewing', 'santiago'),
  B('cl-phase-a-072', 'باستيل تشوكلو نباتي بالعدس والذرة والريحان', 'Vegetarian Pastel de Choclo with Lentils and Basil', 'Pastel de choclo végétarien aux lentilles et basilic', 'Pastel de choclo vegetariano con lentejas y albahaca', 'Vegetarisches Pastel de Choclo mit Linsen und Basilikum', 'vegetable_mains', 'dinner', 13, 24, 6, 'baking', 'maule'),
  B('cl-phase-a-073', 'إمبانادا الخضار بالفاصولياء والجبن الطازج', 'Vegetable Empanada with Beans and Fresh Cheese', 'Empanada aux légumes, haricots et fromage frais', 'Empanada de verduras con porotos y queso fresco', 'Gemüse-Empanada mit Bohnen und Frischkäse', 'street_snacks', 'lunch', 14, 26, 9, 'baking', 'valparaiso'),
  B('cl-phase-a-074', 'كازويلا ميرلوزا بالبطاطس والذرة والفاصولياء', 'Merluza Cazuela with Potato, Corn and Green Beans', 'Cazuela de merluza à la pomme de terre, maïs et haricots verts', 'Cazuela de merluza con papa, choclo y porotos verdes', 'Merluza-Cazuela mit Kartoffel, Mais und grünen Bohnen', 'fish_seafood', 'lunch', 19, 18, 6, 'simmering', 'coquimbo'),
  B('cl-phase-a-075', 'سلطة الكوچايو بالعدس والأفوكادو والطماطم', 'Cochayuyo Salad with Lentils, Avocado and Tomato', 'Salade de cochayuyo aux lentilles, avocat et tomate', 'Ensalada de cochayuyo con lentejas, palta y tomate', 'Cochayuyo-Salat mit Linsen, Avocado und Tomate', 'salads', 'lunch', 12, 20, 8, 'assembling', 'valparaiso'),
];
