import { B } from '../chile-base-data/rows.mjs';

export default [
  B('cl-phase-a-038', 'إمبانادا المأكولات البحرية بالروبيان والجبن الطازج', 'Seafood Empanada with Shrimp and Fresh Cheese', 'Empanada aux fruits de mer, crevettes et fromage frais', 'Empanada de mariscos con camarones y queso fresco', 'Meeresfrüchte-Empanada mit Garnelen und Frischkäse', 'street_snacks', 'lunch', 18, 23, 9, 'baking', 'valparaiso'),
  B('cl-phase-a-039', 'كالدييو ماشاس بالبطاطس والطماطم والكزبرة', 'Machas Caldillo with Potato, Tomato and Cilantro', 'Caldillo de machas à la pomme de terre, tomate et coriandre', 'Caldillo de machas con papa, tomate y cilantro', 'Machas-Caldillo mit Kartoffel, Tomate und Koriander', 'fish_seafood', 'lunch', 18, 15, 6, 'simmering', 'atacama'),
  B('cl-phase-a-040', 'سلمون مشوي مع بطاطس تشيلوتي واللفت', 'Grilled Salmon with Chilote Potatoes and Turnip', 'Saumon grillé aux pommes de terre chilotes et navet', 'Salmón a la plancha con papas chilotas y nabo', 'Gegrillter Lachs mit Chilote-Kartoffeln und Rübe', 'fish_seafood', 'dinner', 24, 18, 10, 'grilling', 'los_lagos'),
  B('cl-phase-a-041', 'إمبانادا التونة بنخيل القلب والبيض', 'Tuna and Palmito Empanada with Egg', 'Empanada au thon, cœur de palmier et œuf', 'Empanada de atún y palmito con huevo', 'Thunfisch-Palmito-Empanada mit Ei', 'street_snacks', 'lunch', 18, 23, 8, 'baking', 'valparaiso'),
  B('cl-phase-a-042', 'يخنة الفاصولياء السوداء بلحم البقر والقرع', 'Black Bean Stew with Beef and Squash', 'Ragoût de haricots noirs au bœuf et courge', 'Guiso de porotos negros con res y zapallo', 'Schwarzer-Bohnen-Eintopf mit Rind und Kürbis', 'meat_mains', 'dinner', 17, 22, 7, 'stewing', 'santiago'),
  B('cl-phase-a-043', 'توماتيكان الديك الرومي بالطماطم والذرة', 'Turkey Tomatican with Tomato, Corn and Basil', 'Tomaticán de dinde à la tomate, maïs et basilic', 'Tomaticán de pavo con tomate, choclo y albahaca', 'Puten-Tomaticán mit Tomate, Mais und Basilikum', 'poultry_mains', 'lunch', 19, 20, 6, 'stewing', 'maule'),
  B('cl-phase-a-044', 'كازويلا لحم الضأن بالشعير والقرع', 'Lamb Cazuela with Barley and Squash', 'Cazuela d’agneau à l’orge et courge', 'Cazuela de cordero con cebada y zapallo', 'Lamm-Cazuela mit Gerste und Kürbis', 'meat_mains', 'dinner', 18, 20, 8, 'simmering', 'magallanes'),
  B('cl-phase-a-045', 'كونغريو بالكزبرة والموتي والبازلاء', 'Congrio with Cilantro, Mote and Peas', 'Congrio à la coriandre, mote et petits pois', 'Congrio con cilantro, mote y arvejas', 'Congrio mit Koriander, Mote und Erbsen', 'fish_seafood', 'dinner', 22, 19, 6, 'baking', 'coquimbo'),
  B('cl-phase-a-046', 'باستيل تشوريتوس بالكينوا والذرة', 'Choritos Pastel with Quinoa and Corn', 'Pastel de choritos au quinoa et maïs', 'Pastel de choritos con quinua y choclo', 'Choritos-Pastel mit Quinoa und Mais', 'fish_seafood', 'dinner', 20, 19, 8, 'baking', 'los_lagos'),
  B('cl-phase-a-047', 'تورتيّا السلق بالبطاطس والجبن الطازج', 'Swiss Chard Tortilla with Potato and Fresh Cheese', 'Tortilla de blettes à la pomme de terre et fromage frais', 'Tortilla de acelga con papa y queso fresco', 'Mangold-Tortilla mit Kartoffel und Frischkäse', 'vegetable_mains', 'lunch', 13, 16, 8, 'pan_frying', 'santiago'),
  B('cl-phase-a-048', 'أخياكو تشيلي بلحم البقر والبطاطس والجزر', 'Ajiaco Chileno with Beef, Potato and Carrot', 'Ajiaco chilien au bœuf, pomme de terre et carotte', 'Ajiaco chileno con res, papa y zanahoria', 'Chilenischer Ajiaco mit Rind, Kartoffel und Karotte', 'soups_stews', 'lunch', 18, 19, 7, 'simmering', 'santiago'),
  B('cl-phase-a-049', 'تشوريتوس مطهوّة بالبخار مع الليمون والبطاطس', 'Steamed Choritos with Lemon, Cilantro and Potato', 'Choritos vapeur au citron, coriandre et pomme de terre', 'Choritos al vapor con limón, cilantro y papa', 'Gedämpfte Choritos mit Zitrone, Koriander und Kartoffel', 'fish_seafood', 'lunch', 20, 14, 5, 'steaming', 'los_lagos'),
  B('cl-phase-a-050', 'مخبوزة ماراكيتا بالأفوكادو والديك الرومي', 'Marraqueta with Avocado and Turkey', 'Marraqueta à l’avocat et à la dinde', 'Marraqueta con palta y pavo', 'Marraqueta mit Avocado und Pute', 'breakfast_items', 'breakfast', 19, 27, 9, 'assembling', 'santiago'),
];
