import { B } from '../chile-base-data/rows.mjs';

export default [
  B('cl-phase-a-138', 'إمبانادا الميرلوزا بالذرة والبقدونس', 'Merluza Empanada with Corn and Parsley', 'Empanada de merluza au maïs et persil', 'Empanada de merluza con choclo y perejil', 'Merluza-Empanada mit Mais und Petersilie', 'street_snacks', 'lunch', 19, 24, 8, 'baking', 'coquimbo'),
  B('cl-phase-a-139', 'شوربة كازويلا القرع بالكينوا والذرة', 'Squash Cazuela Soup with Quinoa and Corn', 'Soupe-cazuela de courge au quinoa et maïs', 'Sopa cazuela de zapallo con quinua y choclo', 'Kürbis-Cazuela-Suppe mit Quinoa und Mais', 'soups_stews', 'lunch', 12, 23, 6, 'simmering', 'maule'),
  B('cl-phase-a-140', 'باستيل الباذنجان بالعدس والذرة والريحان', 'Eggplant Pastel with Lentils, Corn and Basil', 'Pastel d’aubergine aux lentilles, maïs et basilic', 'Pastel de berenjena con lentejas, choclo y albahaca', 'Auberginen-Pastel mit Linsen, Mais und Basilikum', 'vegetable_mains', 'dinner', 13, 22, 8, 'baking', 'santiago'),
  B('cl-phase-a-141', 'سلمون بالمرق مع البطاطس والذرة والبازلاء', 'Salmon Caldillo with Potato, Corn and Peas', 'Caldillo de saumon à la pomme de terre, maïs et petits pois', 'Caldillo de salmón con papa, choclo y arvejas', 'Lachs-Caldillo mit Kartoffel, Mais und Erbsen', 'fish_seafood', 'lunch', 20, 17, 7, 'simmering', 'aysen'),
  B('cl-phase-a-142', 'بوروتوس غرانادوس بالكينوا والريحان والقرع', 'Porotos Granados with Quinoa, Basil and Squash', 'Porotos granados au quinoa, basilic et courge', 'Porotos granados con quinua, albahaca y zapallo', 'Porotos Granados mit Quinoa, Basilikum und Kürbis', 'vegetable_mains', 'lunch', 13, 27, 6, 'stewing', 'maule'),
  B('cl-phase-a-143', 'دجاج مخبوز ببيبر الكوچايو والبطاطس', 'Baked Chicken with Cochayuyo Pebre and Potato', 'Poulet au four au pebre de cochayuyo et pomme de terre', 'Pollo al horno con pebre de cochayuyo y papa', 'Gebackenes Hähnchen mit Cochayuyo-Pebre und Kartoffel', 'poultry_mains', 'dinner', 24, 16, 8, 'baking', 'valparaiso'),
  B('cl-phase-a-144', 'تورتيّا المحار والبطاطس بالكزبرة', 'Mussel and Potato Tortilla with Cilantro', 'Tortilla de moules et pomme de terre à la coriandre', 'Tortilla de choritos y papa con cilantro', 'Muschel-Kartoffel-Tortilla mit Koriander', 'fish_seafood', 'lunch', 18, 18, 8, 'pan_frying', 'los_lagos'),
  B('cl-phase-a-145', 'كروكيت الماكي والكينوا بجبن الكيسيو', 'Maqui and Quinoa Croquettes with Quesillo', 'Croquettes de maqui et quinoa au quesillo', 'Croquetas de maqui y quinua con quesillo', 'Maqui-Quinoa-Kroketten mit Quesillo', 'vegetable_mains', 'snack', 12, 23, 7, 'baking', 'araucania'),
  B('cl-phase-a-146', 'كازويلا السلمون بالبطاطس والقرع والفاصولياء', 'Salmon Cazuela with Potato, Squash and Beans', 'Cazuela de saumon à la pomme de terre, courge et haricots', 'Cazuela de salmón con papa, zapallo y porotos', 'Lachs-Cazuela mit Kartoffel, Kürbis und Bohnen', 'fish_seafood', 'lunch', 20, 19, 8, 'simmering', 'los_lagos'),
  B('cl-phase-a-147', 'سلطة أفوكادو التشونغاس مع العدس والطماطم', 'Chungas Avocado Salad with Lentils and Tomato', 'Salade de chungas et avocat aux lentilles et tomate', 'Ensalada de chungas y palta con lentejas y tomate', 'Chungas-Avocado-Salat mit Linsen und Tomate', 'salads', 'lunch', 11, 19, 9, 'assembling', 'arica'),
  B('cl-phase-a-148', 'فطائر دقيق الحمص بالذرة والجبن الطازج', 'Chickpea Flour Cakes with Corn and Fresh Cheese', 'Galettes de farine de pois chiches au maïs et fromage frais', 'Tortitas de harina de garbanzo con choclo y queso fresco', 'Kichererbsenfladen mit Mais und Frischkäse', 'breakfast_items', 'breakfast', 14, 25, 8, 'pan_frying', 'santiago'),
  B('cl-phase-a-149', 'يخنة لحم الضأن بالكينوا والبطاطس الأنديزية', 'Lamb Stew with Quinoa and Native Potatoes', 'Ragoût d’agneau au quinoa et pommes de terre andines', 'Guiso de cordero con quinua y papas nativas', 'Lammtopf mit Quinoa und Andenkartoffeln', 'meat_mains', 'dinner', 21, 20, 9, 'stewing', 'magallanes'),
  B('cl-phase-a-150', 'بودينغ الذرة والكينوا بجبن الماعز الطازج', 'Corn and Quinoa Pudding with Fresh Goat Cheese', 'Budín de maïs et quinoa au fromage de chèvre frais', 'Budín de choclo y quinua con queso fresco de cabra', 'Mais-Quinoa-Auflauf mit frischem Ziegenkäse', 'vegetable_mains', 'dinner', 15, 24, 8, 'baking', 'coquimbo'),
];
