import { B } from '../chile-base-data/rows.mjs';

export default [
  B('cl-phase-a-014', 'إمبانادا الديك الرومي بالبيض والزيتون', 'Turkey Empanada with Egg and Olive', 'Empanada de dinde à l’œuf et olive', 'Empanada de pavo con huevo y aceituna', 'Puten-Empanada mit Ei und Olive', 'street_snacks', 'lunch', 18, 24, 8, 'baking', 'santiago'),
  B('cl-phase-a-015', 'ماشاس مخبوزة بجبن البارميزان والليمون', 'Baked Machas with Parmesan and Lemon', 'Machas gratinées au parmesan et citron', 'Machas al horno con parmesano y limón', 'Gebackene Machas mit Parmesan und Zitrone', 'fish_seafood', 'lunch', 19, 7, 9, 'baking', 'coquimbo'),
  B('cl-phase-a-016', 'كونغريو مشوي بالبيبر والبطاطس الأنديزية', 'Grilled Congrio with Pebre and Native Potato', 'Congrio grillé au pebre et pomme de terre andine', 'Congrio a la parrilla con pebre y papa nativa', 'Gegrillter Congrio mit Pebre und Andenkartoffel', 'fish_seafood', 'dinner', 23, 16, 7, 'grilling', 'valparaiso'),
  B('cl-phase-a-017', 'كالدييو المأكولات البحرية بالكونغريو والروبيان', 'Seafood Caldillo with Congrio and Shrimp', 'Caldillo de fruits de mer au congrio et crevettes', 'Caldillo de mariscos con congrio y camarones', 'Meeresfrüchte-Caldillo mit Congrio und Garnelen', 'fish_seafood', 'lunch', 20, 12, 6, 'simmering', 'valparaiso'),
  B('cl-phase-a-018', 'بوروتوس كون ريئنداس بلحم البقر والقرع', 'Porotos con Riendas with Beef and Squash', 'Porotos con riendas au bœuf et courge', 'Porotos con riendas con res y zapallo', 'Porotos con Riendas mit Rind und Kürbis', 'meat_mains', 'dinner', 17, 24, 7, 'stewing', 'maule'),
  B('cl-phase-a-019', 'تشوبي لوكوس بالبطاطس والذرة والجبن', 'Chupe de Locos with Potato, Corn and Cheese', 'Chupe de locos à la pomme de terre, maïs et fromage', 'Chupe de locos con papa, choclo y queso', 'Locos-Chupe mit Kartoffel, Mais und Käse', 'fish_seafood', 'lunch', 21, 17, 8, 'baking', 'coquimbo'),
  B('cl-phase-a-020', 'بطاطس محشوة بلحم البقر والبيض والزيتون', 'Chilean Papas Rellenas with Beef, Egg and Olive', 'Papas rellenas chiliennes au bœuf, œuf et olive', 'Papas rellenas chilenas con res, huevo y aceituna', 'Chilenische Papas Rellenas mit Rind, Ei und Olive', 'street_snacks', 'lunch', 17, 25, 9, 'baking', 'santiago'),
  B('cl-phase-a-021', 'سوباييلا مخبوزة بالقرع والديك الرومي والبيبر', 'Baked Sopaipilla with Squash, Turkey and Pebre', 'Sopaipilla au four à la courge, dinde et pebre', 'Sopaipilla al horno con zapallo, pavo y pebre', 'Gebackene Sopaipilla mit Kürbis, Pute und Pebre', 'street_snacks', 'snack', 15, 27, 7, 'baking', 'santiago'),
  B('cl-phase-a-022', 'وعاء كينوا البيبر بالدجاج المشوي والأفوكادو', 'Pebre Quinoa Bowl with Grilled Chicken and Avocado', 'Bol de quinoa au pebre, poulet grillé et avocat', 'Bowl de quinua al pebre con pollo a la parrilla y palta', 'Pebre-Quinoa-Bowl mit gegrilltem Hähnchen und Avocado', 'poultry_mains', 'lunch', 23, 18, 9, 'assembling', 'santiago'),
  B('cl-phase-a-023', 'باستيل تشوكلو الديك الرومي بالذرة والريحان', 'Turkey Pastel de Choclo with Corn and Basil', 'Pastel de choclo à la dinde, maïs et basilic', 'Pastel de choclo de pavo con maíz y albahaca', 'Puten-Pastel de Choclo mit Mais und Basilikum', 'poultry_mains', 'dinner', 19, 21, 7, 'baking', 'maule'),
  B('cl-phase-a-024', 'بانتروكاس بلحم البقر والخضار والبيض', 'Pantrucas with Beef, Vegetables and Egg', 'Pantrucas au bœuf, légumes et œuf', 'Pantrucas con res, verduras y huevo', 'Pantrucas mit Rind, Gemüse und Ei', 'soups_stews', 'lunch', 17, 19, 7, 'simmering', 'bio_bio'),
  B('cl-phase-a-025', 'سلطة الكوچايو بالعدس والبيض والليمون', 'Cochayuyo Salad with Lentils, Egg and Lemon', 'Salade de cochayuyo aux lentilles, œuf et citron', 'Ensalada de cochayuyo con lentejas, huevo y limón', 'Cochayuyo-Salat mit Linsen, Ei und Zitrone', 'salads', 'lunch', 13, 18, 7, 'assembling', 'valparaiso'),
];
