import { B } from '../chile-base-data/rows.mjs';

export default [
  B('cl-phase-a-114', 'كومبليتو الديك الرومي بالأفوكادو والطماطم والملفوف', 'Turkey Completo with Avocado, Tomato and Cabbage', 'Completo à la dinde, avocat, tomate et chou', 'Completo de pavo con palta, tomate y repollo', 'Puten-Completo mit Avocado, Tomate und Kohl', 'street_snacks', 'lunch', 21, 24, 9, 'grilling', 'santiago'),
  B('cl-phase-a-115', 'كازويلا الميرلوزا بالقرع والذرة والفاصولياء الخضراء', 'Merluza Cazuela with Squash, Corn and Green Beans', 'Cazuela de merluza à la courge, maïs et haricots verts', 'Cazuela de merluza con zapallo, choclo y porotos verdes', 'Merluza-Cazuela mit Kürbis, Mais und grünen Bohnen', 'fish_seafood', 'lunch', 20, 18, 6, 'simmering', 'atacama'),
  B('cl-phase-a-116', 'باستيل الكينوا بالخضار والجبن الطازج', 'Quinoa Pastel with Vegetables and Fresh Cheese', 'Pastel de quinoa aux légumes et fromage frais', 'Pastel de quinua con verduras y queso fresco', 'Quinoa-Pastel mit Gemüse und Frischkäse', 'vegetable_mains', 'dinner', 15, 23, 8, 'baking', 'araucania'),
  B('cl-phase-a-117', 'إمبانادا اللحم البقري والقرع والبيض', 'Beef and Squash Empanada with Egg', 'Empanada au bœuf, courge et œuf', 'Empanada de res y zapallo con huevo', 'Rindfleisch-Kürbis-Empanada mit Ei', 'street_snacks', 'lunch', 18, 24, 9, 'baking', 'maule'),
  B('cl-phase-a-118', 'تشوبي السلطعون بالأفوكادو والذرة', 'Crab Chupe with Avocado and Corn', 'Chupe de crabe à l’avocat et au maïs', 'Chupe de jaiba con palta y choclo', 'Krabben-Chupe mit Avocado und Mais', 'fish_seafood', 'lunch', 19, 17, 8, 'baking', 'valparaiso'),
  B('cl-phase-a-119', 'دجاج ميركين مع البوروتوس كيمادو والقرع', 'Merkén Chicken with Porotos Quemados and Squash', 'Poulet au merkén avec porotos quemados et courge', 'Pollo al merkén con porotos quemados y zapallo', 'Merkén-Hähnchen mit Porotos Quemados und Kürbis', 'poultry_mains', 'dinner', 23, 20, 7, 'stewing', 'araucania'),
  B('cl-phase-a-120', 'سلطة القلوب البحرية والبطاطس بالأفوكادو والليمون', 'Palmito and Potato Salad with Avocado and Lemon', 'Salade de cœurs de palmier et pomme de terre à l’avocat et citron', 'Ensalada de palmito y papa con palta y limón', 'Palmito-Kartoffelsalat mit Avocado und Zitrone', 'salads', 'lunch', 8, 22, 10, 'assembling', 'valparaiso'),
  B('cl-phase-a-121', 'أرز الكينوا بالماكريل والطماطم والبازلاء', 'Quinoa Rice with Mackerel, Tomato and Peas', 'Riz de quinoa au maquereau, tomate et petits pois', 'Arroz de quinua con jurel, tomate y arvejas', 'Quinoa-Reis mit Makrele, Tomate und Erbsen', 'fish_seafood', 'dinner', 20, 24, 8, 'simmering', 'valparaiso'),
  B('cl-phase-a-122', 'كروكيت الميرلوزا والبطاطس ببيبر الكزبرة', 'Merluza and Potato Croquettes with Cilantro Pebre', 'Croquettes de merluza et pomme de terre au pebre de coriandre', 'Croquetas de merluza y papa con pebre de cilantro', 'Merluza-Kartoffelkroketten mit Koriander-Pebre', 'fish_seafood', 'lunch', 19, 22, 8, 'baking', 'coquimbo'),
  B('cl-phase-a-123', 'شوربة كينوا تشيليّة بالديك الرومي والخضار', 'Chilean Quinoa Soup with Turkey and Vegetables', 'Soupe chilienne de quinoa à la dinde et aux légumes', 'Sopa chilena de quinua con pavo y verduras', 'Chilenische Quinoasuppe mit Pute und Gemüse', 'soups_stews', 'lunch', 17, 21, 6, 'simmering', 'santiago'),
  B('cl-phase-a-124', 'مخبوزات تشاباليلي محشوة بالجبن والسبانخ', 'Chapalele Filled with Cheese and Spinach', 'Chapalele farci au fromage et aux épinards', 'Chapalele relleno de queso y espinaca', 'Chapalele gefüllt mit Käse und Spinat', 'street_snacks', 'snack', 14, 25, 8, 'baking', 'los_lagos'),
  B('cl-phase-a-125', 'لوكو مشوي ببيبر الذرة والأفوكادو', 'Grilled Locos with Corn and Avocado Pebre', 'Locos grillés au pebre de maïs et avocat', 'Locos a la parrilla con pebre de choclo y palta', 'Gegrillte Locos mit Mais-Avocado-Pebre', 'fish_seafood', 'dinner', 23, 12, 7, 'grilling', 'coquimbo'),
];
