import { B } from '../chile-base-data/rows.mjs';

export default [
  B('cl-phase-a-088', 'باستيل البطاطس بالديك الرومي والبيض والزيتون', 'Turkey Pastel de Papas with Egg and Olive', 'Pastel de pommes de terre à la dinde, œuf et olive', 'Pastel de papas con pavo, huevo y aceituna', 'Puten-Kartoffel-Pastel mit Ei und Olive', 'poultry_mains', 'dinner', 19, 22, 8, 'baking', 'santiago'),
  B('cl-phase-a-089', 'ميرلوزا محشوة بخايبا الكينوا والليمون', 'Merluza Stuffed with Jaiba, Quinoa and Lemon', 'Merluza farcie à la jaiba, quinoa et citron', 'Merluza rellena de jaiba, quinua y limón', 'Merluza gefüllt mit Jaiba, Quinoa und Zitrone', 'fish_seafood', 'dinner', 22, 14, 7, 'baking', 'valparaiso'),
  B('cl-phase-a-090', 'إمبانادا كونغريو بالطماطم والجبن', 'Congrio Empanada with Tomato and Cheese', 'Empanada de congrio à la tomate et au fromage', 'Empanada de congrio con tomate y queso', 'Congrio-Empanada mit Tomate und Käse', 'street_snacks', 'lunch', 19, 24, 9, 'baking', 'coquimbo'),
  B('cl-phase-a-091', 'تشوبي أوستيونيس بالذرة والبطاطس والجبن', 'Ostiones Chupe with Corn, Potato and Cheese', 'Chupe d’ostiones au maïs, pomme de terre et fromage', 'Chupe de ostiones con choclo, papa y queso', 'Ostiones-Chupe mit Mais, Kartoffel und Käse', 'fish_seafood', 'lunch', 20, 16, 8, 'baking', 'atacama'),
  B('cl-phase-a-092', 'يخنة الموتي بالديك الرومي والخضار', 'Mote Stew with Turkey and Vegetables', 'Ragoût de mote à la dinde et aux légumes', 'Guiso de mote con pavo y verduras', 'Mote-Eintopf mit Pute und Gemüse', 'poultry_mains', 'dinner', 18, 23, 6, 'stewing', 'bio_bio'),
  B('cl-phase-a-093', 'أرز المأكولات البحرية التشيلي بالرينيتا والمحار', 'Chilean Seafood Rice with Reineta and Mussels', 'Riz chilien aux fruits de mer, reineta et moules', 'Arroz chileno de mariscos con reineta y choritos', 'Chilenischer Meeresfrüchtereis mit Reineta und Muscheln', 'fish_seafood', 'dinner', 19, 25, 7, 'simmering', 'valparaiso'),
  B('cl-phase-a-094', 'تورتيّا الإريزو بالبطاطس والبصل الأخضر', 'Sea Urchin Tortilla with Potato and Scallion', 'Tortilla d’oursins à la pomme de terre et ciboule', 'Tortilla de erizos con papa y cebollín', 'Seeigel-Tortilla mit Kartoffel und Frühlingszwiebel', 'fish_seafood', 'lunch', 18, 15, 9, 'pan_frying', 'coquimbo'),
  B('cl-phase-a-095', 'سلطة كينوا تشيليّة بالأفوكادو والطماطم والتونة', 'Chilean Quinoa Salad with Avocado, Tomato and Tuna', 'Salade chilienne de quinoa à l’avocat, tomate et thon', 'Ensalada chilena de quinua con palta, tomate y atún', 'Chilenischer Quinoasalat mit Avocado, Tomate und Thunfisch', 'salads', 'lunch', 18, 18, 9, 'assembling', 'santiago'),
  B('cl-phase-a-096', 'عدس بالقرع ولحم البقر قليل الدهن', 'Lentils with Squash and Lean Beef', 'Lentilles à la courge et au bœuf maigre', 'Lentejas con zapallo y res magra', 'Linsen mit Kürbis und magerem Rind', 'meat_mains', 'dinner', 18, 22, 6, 'stewing', 'maule'),
  B('cl-phase-a-097', 'فطائر الشوفان بالجبن الطازج وماكي والزبادي', 'Oat Pancakes with Quesillo, Maqui and Yogurt', 'Crêpes d’avoine au quesillo, maqui et yaourt', 'Panqueques de avena con quesillo, maqui y yogur', 'Haferpfannkuchen mit Quesillo, Maqui und Joghurt', 'breakfast_items', 'breakfast', 16, 23, 7, 'pan_frying', 'araucania'),
  B('cl-phase-a-098', 'موتي كون هويسيوس بالخوخ المجفف والقمح', 'Mote con Huesillos with Dried Peaches and Wheat', 'Mote con huesillos aux pêches séchées et blé', 'Mote con huesillos con duraznos secos y trigo', 'Mote con Huesillos mit Trockenpfirsichen und Weizen', 'beverages', 'snack', 4, 31, 1, 'simmering', 'santiago'),
  B('cl-phase-a-099', 'ليتشي آسادا بالجبن الطازج والقرفة', 'Leche Asada with Fresh Cheese and Cinnamon', 'Leche asada au fromage frais et à la cannelle', 'Leche asada con queso fresco y canela', 'Leche Asada mit Frischkäse und Zimt', 'rice_cakes_sweets', 'snack', 10, 19, 7, 'baking', 'santiago'),
  B('cl-phase-a-100', 'وعاء زبادي مورتي بالكينوا والتوت', 'Murta Yogurt Bowl with Quinoa and Berries', 'Bol de yaourt à la murta, quinoa et baies', 'Bowl de yogur de murta con quinua y berries', 'Murta-Joghurt-Bowl mit Quinoa und Beeren', 'breakfast_items', 'breakfast', 12, 21, 5, 'assembling', 'los_lagos'),
];
