import { B } from '../peru-base-data/rows.mjs';

export default [
  B('pe-phase-a-088', 'باتاسكا أريكويبي بلحم البقر والموتي', 'Arequipa Patasca with Beef and Mote', 'Patasca d’Arequipa au bœuf et mote', 'Patasca arequipeña de res con mote', 'Arequipa-Patasca mit Rind und Mote', 'soups_stews', 'lunch', 17, 13, 7, 'simmering', 'arequipa'),
  B('pe-phase-a-089', 'سيكو دجاج بالكزبرة والفاصولياء', 'Chicken Seco with Cilantro and Beans', 'Seco de poulet à la coriandre et haricots', 'Seco de pollo con cilantro y frijoles', 'Hähnchen-Seco mit Koriander und Bohnen', 'poultry_mains', 'dinner', 20, 11, 7, 'braising', 'cajamarca'),
  B('pe-phase-a-090', 'تالارينيس روخوس بالدجاج والطماطم', 'Tallarines Rojos with Chicken and Tomato', 'Tallarines rojos au poulet et tomate', 'Tallarines rojos con pollo y tomate', 'Tallarines Rojos mit Hähnchen und Tomate', 'poultry_mains', 'dinner', 17, 23, 7, 'simmering', 'lima'),
  B('pe-phase-a-091', 'سموذي مانجو بالمكا والزبادي', 'Mango Smoothie with Maca and Yogurt', 'Smoothie à la mangue, maca et yaourt', 'Batido de mango con maca y yogur', 'Mango-Smoothie mit Maca und Joghurt', 'beverages', 'breakfast', 10, 20, 4, 'blending', 'cusco'),
  B('pe-phase-a-092', 'سيفيتشي إسكالوب بفاكهة العاطفة والخيار', 'Scallop Ceviche with Passion Fruit and Cucumber', 'Ceviche de pétoncles au fruit de la passion et concombre', 'Ceviche de conchas de abanico con maracuyá y pepino', 'Jakobsmuschel-Ceviche mit Passionsfrucht und Gurke', 'fish_seafood', 'lunch', 18, 7, 3, 'marinating', 'piura'),
  B('pe-phase-a-093', 'روكوتو ريلينو بالدجاج والكينوا والجبن', 'Rocoto Relleno with Chicken, Quinoa and Cheese', 'Rocoto relleno au poulet, quinoa et fromage', 'Rocoto relleno de pollo, quinoa y queso', 'Rocoto Relleno mit Hähnchen, Quinoa und Käse', 'poultry_mains', 'dinner', 18, 12, 8, 'baking', 'arequipa'),
  B('pe-phase-a-094', 'لانغوستينو بصلصة أجي أماريلو والذرة', 'Langostino with Aji Amarillo Sauce and Corn', 'Langoustine à la sauce aji amarillo et maïs', 'Langostino en salsa de ají amarillo con maíz', 'Langostino mit Aji-Amarillo-Soße und Mais', 'fish_seafood', 'dinner', 19, 8, 6, 'sauteing', 'lima'),
  B('pe-phase-a-095', 'ألباكا مشوية بالكينوا والخضار', 'Grilled Alpaca with Quinoa and Vegetables', 'Alpaca grillée au quinoa et légumes', 'Alpaca a la parrilla con quinoa y verduras', 'Gegrilltes Alpaka mit Quinoa und Gemüse', 'meat_mains', 'dinner', 23, 12, 7, 'grilling', 'cusco'),
  B('pe-phase-a-096', 'سودادو سلطعون بالبطاطس والفلفل الأصفر', 'Crab Sudado with Potato and Aji Amarillo', 'Sudado de crabe à la pomme de terre et aji amarillo', 'Sudado de cangrejo con papa y ají amarillo', 'Krabben-Sudado mit Kartoffel und Aji Amarillo', 'fish_seafood', 'lunch', 18, 11, 6, 'braising', 'callao'),
  B('pe-phase-a-097', 'كروكيت البطاطا والسمك بالفلفل الأصفر', 'Potato and Fish Croquettes with Aji Amarillo', 'Croquettes de pomme de terre et poisson à l’aji amarillo', 'Croquetas de papa y pescado con ají amarillo', 'Kartoffel-Fisch-Kroketten mit Aji Amarillo', 'fish_seafood', 'snack', 16, 18, 7, 'baking', 'ancash'),
  B('pe-phase-a-098', 'ليتشي أسادا بالكينوا والحليب', 'Leche Asada with Quinoa and Milk', 'Leche asada au quinoa et lait', 'Leche asada con quinoa y leche', 'Leche Asada mit Quinoa und Milch', 'rice_cakes_sweets', 'snack', 9, 20, 7, 'baking', 'lima'),
  B('pe-phase-a-099', 'سلطة تاروي وكينوا بالأفوكادو والفلفل الأصفر', 'Tarwi and Quinoa Salad with Avocado and Aji Amarillo', 'Salade de tarwi et quinoa à l’avocat et aji amarillo', 'Ensalada de tarwi y quinoa con aguacate y ají amarillo', 'Tarwi-Quinoa-Salat mit Avocado und Aji Amarillo', 'salads', 'lunch', 13, 18, 7, 'assembling', 'puno'),
  B('pe-phase-a-100', 'سموذي شيريمويا بالشيا والزبادي', 'Chirimoya Smoothie with Chia and Yogurt', 'Smoothie de chirimoya au chia et yaourt', 'Batido de chirimoya con chía y yogur', 'Chirimoya-Smoothie mit Chia und Joghurt', 'beverages', 'breakfast', 9, 18, 5, 'blending', 'amazonas'),
];
