import { B } from '../peru-base-data/rows.mjs';

export default [
  B('pe-phase-a-138', 'دجاج بولّادا بصلصة الأعشاب وسلطة البطاطس', 'Pollo a la Pollada with Herb Sauce and Potato Salad', 'Pollo a la pollada, sauce aux herbes et salade de pommes de terre', 'Pollo a la pollada con salsa de hierbas y ensalada de papa', 'Pollo a la Pollada mit Kräutersoße und Kartoffelsalat', 'poultry_mains', 'dinner', 22, 10, 8, 'grilling', 'lima'),
  B('pe-phase-a-139', 'كاسويلا دي تونو بالذرة والبطاطس', 'Tuna Cazuela with Corn and Potato', 'Cazuela de thon au maïs et pomme de terre', 'Cazuela de atún con maíz y papa', 'Thunfisch-Cazuela mit Mais und Kartoffel', 'fish_seafood', 'dinner', 19, 15, 7, 'simmering', 'callao'),
  B('pe-phase-a-140', 'لومو ألباكا بصلصة أجي بانكا والبطاطس', 'Alpaca Lomo with Aji Panca Sauce and Potato', 'Lomo d’alpaga à la sauce aji panca et pomme de terre', 'Lomo de alpaca con salsa de ají panca y papa', 'Alpaka-Lomo mit Aji-Panca-Soße und Kartoffel', 'meat_mains', 'dinner', 23, 11, 8, 'sauteing', 'cusco'),
  B('pe-phase-a-141', 'ديك رومي بكريمة هواكاتاي والبازلاء', 'Turkey with Huacatay Cream and Peas', 'Dinde à la crème de huacatay et petits pois', 'Pavo con crema de huacatay y arvejas', 'Pute mit Huacatay-Creme und Erbsen', 'poultry_mains', 'dinner', 21, 8, 9, 'braising', 'arequipa'),
  B('pe-phase-a-142', 'سمك بقشرة أجي بانكا والكينوا', 'Fish with Aji Panca Crust and Quinoa', 'Poisson en croûte d’aji panca et quinoa', 'Pescado con costra de ají panca y quinoa', 'Fisch mit Aji-Panca-Kruste und Quinoa', 'fish_seafood', 'dinner', 20, 12, 8, 'baking', 'ancash'),
  B('pe-phase-a-143', 'شامبار دجاج بالقمح والفاصولياء', 'Chicken Shambar with Wheat and Beans', 'Shambar de poulet au blé et haricots', 'Shambar de pollo con trigo y frijoles', 'Hähnchen-Shambar mit Weizen und Bohnen', 'soups_stews', 'lunch', 16, 18, 6, 'simmering', 'lambayeque'),
  B('pe-phase-a-144', 'باستيل كينوا بالقرع والفلفل الأصفر', 'Quinoa Pastel with Squash and Aji Amarillo', 'Pastel de quinoa à la courge et aji amarillo', 'Pastel de quinoa con zapallo y ají amarillo', 'Quinoa-Pastel mit Kürbis und Aji Amarillo', 'vegetable_mains', 'dinner', 13, 21, 7, 'baking', 'cusco'),
  B('pe-phase-a-145', 'تروتا أونكوياس بالكينوا والليمون', 'Trout Uncuyas with Quinoa and Lime', 'Truite uncuyas au quinoa et citron vert', 'Trucha uncuyas con quinoa y lima', 'Uncuyas-Forelle mit Quinoa und Limette', 'fish_seafood', 'dinner', 21, 12, 7, 'grilling', 'ancash'),
  B('pe-phase-a-146', 'سوبيري دي ألباكا مع الذرة والبازلاء', 'Alpaca Sopa Seca with Corn and Peas', 'Sopa seca d’alpaga au maïs et petits pois', 'Sopa seca de alpaca con maíz y arvejas', 'Alpaka-Sopa-Seca mit Mais und Erbsen', 'meat_mains', 'dinner', 21, 21, 8, 'baking', 'cusco'),
  B('pe-phase-a-147', 'يوكا محشوة باللحم والبيض والزيتون', 'Cassava Stuffed with Beef, Egg and Olives', 'Manioc farci au bœuf, œuf et olives', 'Yuca rellena de res, huevo y aceitunas', 'Maniok gefüllt mit Rind, Ei und Oliven', 'meat_mains', 'lunch', 16, 23, 8, 'baking', 'lima'),
  B('pe-phase-a-148', 'شوربة كينوا بالفطر والأجي الأصفر', 'Quinoa Soup with Mushrooms and Aji Amarillo', 'Soupe de quinoa aux champignons et aji amarillo', 'Sopa de quinoa con hongos y ají amarillo', 'Quinoasuppe mit Pilzen und Aji Amarillo', 'soups_stews', 'lunch', 11, 16, 5, 'simmering', 'cajamarca'),
  B('pe-phase-a-149', 'أخطبوط بصلصة الزيتون والبطاطس', 'Octopus with Olive Sauce and Potato', 'Poulpe à la sauce aux olives et pomme de terre', 'Pulpo en salsa de aceituna con papa', 'Oktopus mit Olivensoße und Kartoffel', 'fish_seafood', 'dinner', 21, 8, 7, 'braising', 'lima'),
  B('pe-phase-a-150', 'مازامورا كيويتشا بالمانجو والقرفة', 'Kiwicha Mazamorra with Mango and Cinnamon', 'Mazamorra de kiwicha à la mangue et cannelle', 'Mazamorra de kiwicha con mango y canela', 'Kiwicha-Mazamorra mit Mango und Zimt', 'rice_cakes_sweets', 'snack', 9, 27, 5, 'simmering', 'amazonas'),
];
