import { B } from '../peru-base-data/rows.mjs';

export default [
  B('pe-phase-a-114', 'بولّادا دجاج بالبطاطس والسلطة', 'Pollo a la Pollada with Potato Salad', 'Pollo a la pollada et salade de pommes de terre', 'Pollo a la pollada con ensalada de papa', 'Pollo a la Pollada mit Kartoffelsalat', 'poultry_mains', 'dinner', 22, 9, 8, 'grilling', 'lima'),
  B('pe-phase-a-115', 'شوربة تيولوجا بالدجاج والأرز والخبز', 'Sopa Teologa with Chicken, Rice and Bread', 'Sopa teologa au poulet, riz et pain', 'Sopa teóloga con pollo, arroz y pan', 'Sopa Teologa mit Hähnchen, Reis und Brot', 'soups_stews', 'lunch', 15, 15, 6, 'simmering', 'lambayeque'),
  B('pe-phase-a-116', 'تروتا مقرمشة بكيواشا وسلطة البطاطس', 'Crispy Trout with Kiwicha and Potato Salad', 'Truite croustillante au kiwicha et salade de pommes de terre', 'Trucha crujiente con kiwicha y ensalada de papa', 'Knusprige Forelle mit Kiwicha und Kartoffelsalat', 'fish_seafood', 'dinner', 21, 15, 8, 'baking', 'puno'),
  B('pe-phase-a-117', 'بابا ريلينا بالديك الرومي والكينوا', 'Turkey and Quinoa Papa Rellena', 'Papa rellena à la dinde et quinoa', 'Papa rellena de pavo y quinoa', 'Papa Rellena mit Pute und Quinoa', 'poultry_mains', 'lunch', 17, 21, 8, 'baking', 'lima'),
  B('pe-phase-a-118', 'تشوبي باياريس بالروبيان والذرة', 'Pallares Chupe with Shrimp and Corn', 'Chupe de pallares aux crevettes et maïs', 'Chupe de pallares con camarones y maíz', 'Pallares-Chupe mit Garnelen und Mais', 'fish_seafood', 'lunch', 17, 15, 6, 'simmering', 'arequipa'),
  B('pe-phase-a-119', 'تالارينيس هواكّاينا بلحم البقر والجبن', 'Tallarines a la Huancaina with Beef and Cheese', 'Tallarines à la huancaína au bœuf et fromage', 'Tallarines a la huancaína con res y queso', 'Huancaina-Tallarines mit Rindfleisch und Käse', 'meat_mains', 'dinner', 19, 24, 9, 'boiling', 'huancayo'),
  B('pe-phase-a-120', 'فطائر كينوا بيروفية بالجبن الطازج وفاكهة العاطفة', 'Peruvian Quinoa Pancakes with Fresh Cheese and Passion Fruit', 'Crêpes péruviennes de quinoa au fromage frais et fruit de la passion', 'Panqueques peruanos de quinoa con queso fresco y maracuyá', 'Peruanische Quinoa-Pfannkuchen mit Frischkäse und Passionsfrucht', 'breakfast_items', 'breakfast', 13, 21, 7, 'pan_frying', 'cusco'),
  B('pe-phase-a-121', 'يخنة لحم ضأن بالكوسا والفلفل بانكا', 'Lamb Stew with Squash and Aji Panca', 'Ragoût d’agneau à la courge et aji panca', 'Guiso de cordero con zapallo y ají panca', 'Lammtopf mit Kürbis und Aji Panca', 'meat_mains', 'dinner', 20, 10, 9, 'stewing', 'cajamarca'),
  B('pe-phase-a-122', 'حساء كينوا بالبطاطس وجبن كويسو فريسكو', 'Quinoa Soup with Potato and Queso Fresco', 'Soupe de quinoa à la pomme de terre et queso fresco', 'Sopa de quinoa con papa y queso fresco', 'Quinoasuppe mit Kartoffel und Queso Fresco', 'soups_stews', 'lunch', 12, 17, 5, 'simmering', 'ancash'),
  B('pe-phase-a-123', 'تورتا الميمبريلو والكاسترد بالكينوا', 'Quince and Quinoa Custard Tart', 'Tarte à la pâte de coing et crème de quinoa', 'Tarta de membrillo y crema de quinoa', 'Quitten-Quinoa-Cremetarte', 'rice_cakes_sweets', 'snack', 8, 31, 8, 'baking', 'ica'),
  B('pe-phase-a-124', 'تروتا بصلصة هواكاتاي والليمون', 'Trout with Huacatay and Lime Sauce', 'Truite à la sauce huacatay et citron vert', 'Trucha con salsa de huacatay y lima', 'Forelle mit Huacatay-Limettensoße', 'fish_seafood', 'dinner', 22, 5, 8, 'grilling', 'puno'),
  B('pe-phase-a-125', 'تشوكلو بيروفي مشوي بالجبن والفلفل', 'Grilled Peruvian Choclo with Cheese and Chile', 'Choclo péruvien grillé au fromage et piment', 'Choclo peruano a la parrilla con queso y ají', 'Gegrillter peruanischer Choclo mit Käse und Chili', 'street_snacks', 'snack', 10, 26, 7, 'grilling', 'lima'),
];
