import { B } from '../peru-base-data/rows.mjs';

export default [
  B('pe-phase-a-188', 'شوربة أولّوكو بالدجاج والبطاطس', 'Olluco Soup with Chicken and Potato', 'Soupe d’olluco au poulet et pomme de terre', 'Sopa de olluco con pollo y papa', 'Olluco-Suppe mit Hähnchen und Kartoffel', 'soups_stews', 'lunch', 15, 14, 5, 'simmering', 'cusco'),
  B('pe-phase-a-189', 'تيراديتو لانغوستينو بالليمون والفلفل الأصفر', 'Langostino Tiradito with Lime and Aji Amarillo', 'Tiradito de langoustines au citron vert et aji amarillo', 'Tiradito de langostino con lima y ají amarillo', 'Langostino-Tiradito mit Limette und Aji Amarillo', 'fish_seafood', 'lunch', 19, 5, 3, 'marinating', 'callao'),
  B('pe-phase-a-190', 'تورتيا كيويتشا بالبيض والسبانخ', 'Kiwicha Tortilla with Egg and Spinach', 'Tortilla de kiwicha à l’œuf et épinards', 'Tortilla de kiwicha con huevo y espinaca', 'Kiwicha-Tortilla mit Ei und Spinat', 'breakfast_items', 'breakfast', 14, 14, 8, 'pan_frying', 'puno'),
  B('pe-phase-a-191', 'سيكو دي كابريتو بالكينوا والبازلاء', 'Seco de Cabrito with Quinoa and Peas', 'Seco de cabrito au quinoa et petits pois', 'Seco de cabrito con quinoa y arvejas', 'Seco de Cabrito mit Quinoa und Erbsen', 'meat_mains', 'dinner', 21, 13, 8, 'braising', 'cajamarca'),
  B('pe-phase-a-192', 'سلطة دجاج بالمانجو والتاروي والأفوكادو', 'Chicken Salad with Mango, Tarwi and Avocado', 'Salade de poulet à la mangue, tarwi et avocat', 'Ensalada de pollo con mango, tarwi y aguacate', 'Hähnchensalat mit Mango, Tarwi und Avocado', 'salads', 'lunch', 18, 11, 8, 'assembling', 'lima'),
  B('pe-phase-a-193', 'أريبا فريجوليرا بالفاصولياء والجبن', 'Frijolera Arepa with Beans and Cheese', 'Arepa frijolera aux haricots et fromage', 'Arepa frijolera con frijoles y queso', 'Frijolera-Arepa mit Bohnen und Käse', 'street_snacks', 'snack', 13, 22, 8, 'griddling', 'cusco'),
  B('pe-phase-a-194', 'أرز أندينو بالقرع والتاروي', 'Andean Rice with Squash and Tarwi', 'Riz andin à la courge et tarwi', 'Arroz andino con zapallo y tarwi', 'Andenreis mit Kürbis und Tarwi', 'vegetable_mains', 'lunch', 12, 23, 6, 'simmering', 'ancash'),
  B('pe-phase-a-195', 'بولّادا دي ميرلوزا باليوكا وصلصة أجي', 'Merluza Pollada with Cassava and Aji Sauce', 'Merluza pollada au manioc et sauce aji', 'Pollada de merluza con yuca y salsa de ají', 'Merluza-Pollada mit Maniok und Aji-Soße', 'fish_seafood', 'dinner', 20, 14, 7, 'grilling', 'piura'),
  B('pe-phase-a-196', 'كروكيت كينوا وأراجّاتشا بالجبن', 'Quinoa and Arracacha Croquettes with Cheese', 'Croquettes de quinoa et arracacha au fromage', 'Croquetas de quinoa y arracacha con queso', 'Quinoa-Arracacha-Kroketten mit Käse', 'vegetable_mains', 'snack', 12, 18, 7, 'baking', 'huancayo'),
  B('pe-phase-a-197', 'سمك كورفينا بصلصة لولو والذرة', 'Corvina with Lulo Sauce and Corn', 'Corvina à la sauce lulo et maïs', 'Corvina con salsa de lulo y maíz', 'Corvina mit Lulo-Soße und Mais', 'fish_seafood', 'dinner', 21, 8, 6, 'braising', 'piura'),
  B('pe-phase-a-198', 'بودينغ كينوا بالحليب والتفاح', 'Quinoa Pudding with Milk and Apple', 'Pudding de quinoa au lait et pomme', 'Pudín de quinoa con leche y manzana', 'Quinoapudding mit Milch und Apfel', 'rice_cakes_sweets', 'snack', 9, 25, 5, 'baking', 'cajamarca'),
  B('pe-phase-a-199', 'لومو ألباكا بالفلفل الأصفر والفاصولياء الخضراء', 'Alpaca Lomo with Aji Amarillo and Green Beans', 'Lomo d’alpaga à l’aji amarillo et haricots verts', 'Lomo de alpaca con ají amarillo y vainitas', 'Alpaka-Lomo mit Aji Amarillo und grünen Bohnen', 'meat_mains', 'dinner', 23, 8, 8, 'sauteing', 'cusco'),
  B('pe-phase-a-200', 'شوكولاتة ساخنة بالكينوا والقرفة', 'Peruvian Hot Chocolate with Quinoa and Cinnamon', 'Chocolat chaud péruvien au quinoa et cannelle', 'Chocolate caliente peruano con quinoa y canela', 'Peruanische heiße Schokolade mit Quinoa und Zimt', 'beverages', 'breakfast', 8, 22, 7, 'simmering', 'lima'),
];
