import { B } from '../peru-base-data/rows.mjs';

export default [
  B('pe-phase-a-164', 'شوربة شوروس بالتاروي والبطاطس', 'Choros Soup with Tarwi and Potato', 'Soupe de choros au tarwi et pomme de terre', 'Sopa de choros con tarwi y papa', 'Choros-Suppe mit Tarwi und Kartoffel', 'fish_seafood', 'lunch', 17, 12, 5, 'simmering', 'callao'),
  B('pe-phase-a-165', 'دجاج هواكاتاي بالقرع والكينوا', 'Chicken Huacatay with Squash and Quinoa', 'Poulet au huacatay, courge et quinoa', 'Pollo con huacatay, zapallo y quinoa', 'Hähnchen mit Huacatay, Kürbis und Quinoa', 'poultry_mains', 'dinner', 20, 12, 8, 'braising', 'arequipa'),
  B('pe-phase-a-166', 'سمك مطهو بالذرة والليمون والهوغاو', 'Fish Sudado with Corn, Lime and Hogao', 'Sudado de poisson au maïs, citron vert et hogao', 'Sudado de pescado con maíz, lima y hogao', 'Fisch-Sudado mit Mais, Limette und Hogao', 'fish_seafood', 'dinner', 20, 10, 6, 'braising', 'piura'),
  B('pe-phase-a-167', 'باستيل اليوكا بالسلطعون والجبن الطازج', 'Cassava Pastel with Crab and Fresh Cheese', 'Pastel de manioc au crabe et fromage frais', 'Pastel de yuca con jaiba y queso fresco', 'Maniok-Pastel mit Krabbe und Frischkäse', 'fish_seafood', 'dinner', 16, 20, 7, 'baking', 'callao'),
  B('pe-phase-a-168', 'لومو دي كابرا بصلصة الروكوتو', 'Beef Lomo with Rocoto Sauce', 'Lomo de bœuf à la sauce rocoto', 'Lomo de res con salsa de rocoto', 'Rinder-Lomo mit Rocoto-Soße', 'meat_mains', 'dinner', 23, 5, 11, 'grilling', 'arequipa'),
  B('pe-phase-a-169', 'سلطة سمك تاروي بالأفوكادو والذرة', 'Fish and Tarwi Salad with Avocado and Corn', 'Salade de poisson et tarwi à l’avocat et maïs', 'Ensalada de pescado y tarwi con aguacate y maíz', 'Fisch-Tarwi-Salat mit Avocado und Mais', 'fish_seafood', 'lunch', 18, 12, 6, 'assembling', 'puno'),
  B('pe-phase-a-170', 'بانكيك كينوا بالتوت والبطاطا الحلوة', 'Quinoa Pancakes with Berries and Sweet Potato', 'Crêpes de quinoa aux baies et patate douce', 'Panqueques de quinoa con frutos rojos y camote', 'Quinoa-Pfannkuchen mit Beeren und Süßkartoffel', 'breakfast_items', 'breakfast', 11, 23, 6, 'pan_frying', 'cusco'),
  B('pe-phase-a-171', 'تامال كاموتي بالدجاج والخضار', 'Camote Tamal with Chicken and Vegetables', 'Tamal de camote au poulet et légumes', 'Tamal de camote con pollo y verduras', 'Camote-Tamal mit Hähnchen und Gemüse', 'street_snacks', 'lunch', 14, 24, 6, 'steaming', 'amazonas'),
  B('pe-phase-a-172', 'رافيولي هوميتا بالدجاج وصلصة الفلفل', 'Humita Ravioli with Chicken and Chile Sauce', 'Raviolis de humita au poulet et sauce pimentée', 'Ravioles de humita con pollo y salsa de ají', 'Humita-Ravioli mit Hähnchen und Chilisauce', 'poultry_mains', 'dinner', 17, 23, 8, 'boiling', 'cusco'),
  B('pe-phase-a-173', 'تشيريمويا بالزبادي وبذور الكتان', 'Chirimoya Yogurt with Flaxseed', 'Yaourt à la chirimoya et graines de lin', 'Yogur de chirimoya con linaza', 'Chirimoya-Joghurt mit Leinsamen', 'breakfast_items', 'breakfast', 10, 18, 5, 'assembling', 'amazonas'),
  B('pe-phase-a-174', 'تروتا بونو بالفلفل الأحمر والذرة', 'Puno Trout with Red Pepper and Corn', 'Truite de Puno au poivron rouge et maïs', 'Trucha de Puno con pimiento rojo y maíz', 'Puno-Forelle mit roter Paprika und Mais', 'fish_seafood', 'dinner', 21, 9, 7, 'baking', 'puno'),
  B('pe-phase-a-175', 'تارت تونة أجي أماريو بالبطاطس والذرة', 'Aji Amarillo Tuna Tart with Potato and Corn', 'Tarte au thon, aji amarillo, pomme de terre et maïs', 'Tarta de atún con ají amarillo, papa y maíz', 'Thunfisch-Aji-Amarillo-Tarte mit Kartoffel und Mais', 'fish_seafood', 'lunch', 17, 17, 7, 'baking', 'lima'),
];
