import { B } from '../peru-base-data/rows.mjs';

export default [
  B('pe-phase-a-214', 'تشوبي السلطعون بالبطاطس والبازلاء الخضراء', 'Crab Chupe with Potato and Green Peas', 'Chupe de crabe à la pomme de terre et aux petits pois', 'Chupe de cangrejo con papa y arvejas', 'Krabben-Chupe mit Kartoffel und grünen Erbsen', 'fish_seafood', 'lunch', 19, 17, 7, 'simmering', 'callao'),
  B('pe-phase-a-215', 'خواني اليوكا بالدجاج والبيض والزيتون', 'Yuca Juane with Chicken, Egg and Olives', 'Juane de yuca au poulet, œuf et olives', 'Juane de yuca con pollo, huevo y aceitunas', 'Yuca-Juane mit Hähnchen, Ei und Oliven', 'poultry_mains', 'lunch', 18, 23, 8, 'steaming', 'loreto'),
  B('pe-phase-a-216', 'بيسكي الكينوا بالجبن الطازج والحليب', 'Pesque de Quinoa with Fresh Cheese and Milk', 'Pesque de quinoa au fromage frais et au lait', 'Pesque de quinua con queso fresco y leche', 'Quinoa-Pesque mit Frischkäse und Milch', 'breakfast_items', 'breakfast', 14, 25, 8, 'simmering', 'puno'),
  B('pe-phase-a-217', 'بيكانتي الباياريس بالبطاطس وأخي بانكا', 'Pallares Picante with Potato and Aji Panca', 'Pallares picantes à la pomme de terre et à l’aji panca', 'Picante de pallares con papa y ají panca', 'Pallares Picante mit Kartoffel und Aji Panca', 'vegetable_mains', 'dinner', 14, 25, 7, 'stewing', 'ica'),
  B('pe-phase-a-218', 'كالدو فيردي من كاخاماركا بالبطاطس والبيض والبايكو', 'Cajamarca Caldo Verde with Potato, Egg and Paico', 'Caldo verde de Cajamarca à la pomme de terre, œuf et paico', 'Caldo verde cajamarquino con papa, huevo y paico', 'Cajamarca-Caldo-Verde mit Kartoffel, Ei und Paico', 'soups_stews', 'breakfast', 11, 19, 7, 'simmering', 'cajamarca'),
  B('pe-phase-a-219', 'فطائر الذرة والهواكاتاي والجبن الطازج', 'Choclo Fritters with Huacatay and Fresh Cheese', 'Beignets de choclo au huacatay et fromage frais', 'Torrejas de choclo con huacatay y queso fresco', 'Choclo-Küchlein mit Huacatay und Frischkäse', 'street_snacks', 'snack', 11, 24, 8, 'pan_frying', 'arequipa'),
  B('pe-phase-a-220', 'كاو كاو المأكولات البحرية بالبطاطس والكركم', 'Seafood Cau Cau with Potato and Turmeric', 'Cau cau de fruits de mer à la pomme de terre et au curcuma', 'Cau cau de mariscos con papa y cúrcuma', 'Meeresfrüchte-Cau-Cau mit Kartoffel und Kurkuma', 'fish_seafood', 'dinner', 20, 15, 7, 'stewing', 'lima'),
  B('pe-phase-a-221', 'بيخيرِي مقلي مع كانشا وصلصة الكريويا', 'Fried Pejerrey with Cancha and Salsa Criolla', 'Pejerrey frit avec cancha et salsa criolla', 'Pejerrey frito con cancha y salsa criolla', 'Gebratener Pejerrey mit Cancha und Salsa Criolla', 'fish_seafood', 'lunch', 22, 16, 8, 'pan_frying', 'puno'),
  B('pe-phase-a-222', 'يخنة سمك ساحلية بالسلطعون واليوكا والليمون', 'Northern Coastal Fish Stew with Crab, Cassava and Lime', 'Ragoût de poisson côtier du nord au crabe, manioc et citron vert', 'Guiso norteño de pescado con cangrejo, yuca y limón', 'Nordperuanischer Fischeintopf mit Krabbe, Maniok und Limette', 'fish_seafood', 'dinner', 21, 18, 7, 'stewing', 'piura'),
  B('pe-phase-a-223', 'بيستيك آ لو بوبري بالموز والبيض والبطاطس', 'Bistec a lo Pobre with Plantain, Egg and Potato', 'Bistec a lo pobre à la banane plantain, œuf et pomme de terre', 'Bistec a lo pobre con plátano, huevo y papa', 'Bistec a lo Pobre mit Kochbanane, Ei und Kartoffel', 'meat_mains', 'dinner', 23, 28, 14, 'pan_frying', 'lima'),
  B('pe-phase-a-224', 'كايغوا محشوة بلحم البقر والزبيب والزيتون', 'Stuffed Caigua with Beef, Raisins and Olives', 'Caigua farcie au bœuf, raisins secs et olives', 'Caigua rellena de res, pasas y aceitunas', 'Gefüllte Caigua mit Rind, Rosinen und Oliven', 'vegetable_mains', 'lunch', 16, 14, 8, 'baking', 'lima'),
  B('pe-phase-a-225', 'قرع لوخي محشو بالكينوا والجبن الطازج', 'Loche Squash Stuffed with Quinoa and Fresh Cheese', 'Courge loche farcie au quinoa et fromage frais', 'Zapallo loche relleno de quinua y queso fresco', 'Loche-Kürbis gefüllt mit Quinoa und Frischkäse', 'vegetable_mains', 'dinner', 12, 23, 8, 'baking', 'lambayeque'),
];
