import { B } from '../peru-base-data/rows.mjs';

export default [
  B('pe-phase-a-014', 'سيفيتشي ميكستو بالسمك والروبيان والذرة', 'Mixed Fish and Shrimp Ceviche with Corn', 'Ceviche mixte de poisson et crevettes au maïs', 'Ceviche mixto de pescado y camarón con maíz', 'Gemischtes Fisch-Garnelen-Ceviche mit Mais', 'fish_seafood', 'lunch', 19, 9, 3, 'marinating', 'piura'),
  B('pe-phase-a-015', 'بابا ريلينا بلحم البقر والزيتون', 'Papa Rellena with Beef and Olives', 'Papa rellena au bœuf et olives', 'Papa rellena de res y aceitunas', 'Papa Rellena mit Rindfleisch und Oliven', 'meat_mains', 'lunch', 16, 23, 8, 'baking', 'lima'),
  B('pe-phase-a-016', 'سيكو دي ريس بالكزبرة والفاصولياء', 'Seco de Res with Cilantro and Beans', 'Seco de res à la coriandre et haricots', 'Seco de res con cilantro y frijoles', 'Seco de Res mit Koriander und Bohnen', 'meat_mains', 'dinner', 20, 10, 8, 'braising', 'piura'),
  B('pe-phase-a-017', 'تامال ليماوي بالدجاج والبيض والزيتون', 'Lima Tamal with Chicken, Egg and Olives', 'Tamal limeño au poulet, œuf et olives', 'Tamal limeño de pollo, huevo y aceitunas', 'Lima-Tamal mit Hähnchen, Ei und Oliven', 'street_snacks', 'lunch', 15, 23, 8, 'steaming', 'lima'),
  B('pe-phase-a-018', 'باريويلا مأكولات بحرية بالطماطم والليمون', 'Seafood Parihuela with Tomato and Lime', 'Parihuela de fruits de mer à la tomate et citron vert', 'Parihuela de mariscos con tomate y lima', 'Meeresfrüchte-Parihuela mit Tomate und Limette', 'fish_seafood', 'lunch', 18, 8, 5, 'simmering', 'callao'),
  B('pe-phase-a-019', 'أوكوبا بالبطاطس وصلصة الهواكاتاي والفول السوداني', 'Ocopa Potatoes with Huacatay and Peanut Sauce', 'Pommes de terre ocopa à la huacatay et sauce cacahuète', 'Papas ocopa con salsa de huacatay y maní', 'Ocopa-Kartoffeln mit Huacatay-Erdnusssoße', 'vegetable_mains', 'lunch', 10, 18, 8, 'boiling', 'arequipa'),
  B('pe-phase-a-020', 'أروز تابادو بلحم البقر والبيض والزيتون', 'Arroz Tapado with Beef, Egg and Olives', 'Arroz tapado au bœuf, œuf et olives', 'Arroz tapado de res con huevo y aceitunas', 'Arroz Tapado mit Rindfleisch, Ei und Oliven', 'meat_mains', 'dinner', 17, 21, 8, 'steaming', 'lima'),
  B('pe-phase-a-021', 'سولتيريتو أريكويبا بالفول العريض والذرة والجبن', 'Arequipa Solterito with Fava Beans, Corn and Cheese', 'Solterito d’Arequipa aux fèves, maïs et fromage', 'Solterito arequipeño con habas, maíz y queso', 'Arequipa-Solterito mit Ackerbohnen, Mais und Käse', 'salads', 'lunch', 12, 14, 6, 'assembling', 'arequipa'),
  B('pe-phase-a-022', 'تيراديتو بالسمك والفلفل الأصفر والليمون', 'Fish Tiradito with Aji Amarillo and Lime', 'Tiradito de poisson à l’aji amarillo et citron vert', 'Tiradito de pescado con ají amarillo y lima', 'Fisch-Tiradito mit Aji Amarillo und Limette', 'fish_seafood', 'lunch', 20, 5, 4, 'marinating', 'lima'),
  B('pe-phase-a-023', 'كينوا تشوفا بالدجاج والخضار', 'Chicken Quinoa Chaufa with Vegetables', 'Chaufa de quinoa au poulet et légumes', 'Quinua chaufa de pollo con verduras', 'Hähnchen-Quinoa-Chaufa mit Gemüse', 'poultry_mains', 'dinner', 18, 17, 7, 'sauteing', 'lima'),
  B('pe-phase-a-024', 'مازامورا مورادا بالذرة الأرجوانية والفاكهة', 'Mazamorra Morada with Purple Corn and Fruit', 'Mazamorra morada au maïs violet et fruits', 'Mazamorra morada de maíz morado con fruta', 'Mazamorra Morada aus violettem Mais mit Früchten', 'rice_cakes_sweets', 'snack', 3, 28, 1, 'simmering', 'lima'),
  B('pe-phase-a-025', 'ألفاخور بيروفي بدولسي دي ليتشي وجوز الهند', 'Peruvian Alfajor with Dulce de Leche and Coconut', 'Alfajor péruvien au dulce de leche et noix de coco', 'Alfajor peruano con dulce de leche y coco', 'Peruanischer Alfajor mit Dulce de Leche und Kokos', 'rice_cakes_sweets', 'snack', 6, 37, 11, 'baking', 'lima'),
];
