import { B } from '../peru-base-data/rows.mjs';

export default [
  B('pe-phase-a-238', 'أفوكادو محشو بالسلطعون والبطاطس والبازلاء', 'Stuffed Avocado with Crab, Potato and Peas', 'Avocat farci au crabe, pomme de terre et petits pois', 'Palta rellena de cangrejo, papa y arvejas', 'Gefüllte Avocado mit Krabbe, Kartoffel und Erbsen', 'fish_seafood', 'lunch', 16, 18, 10, 'assembling', 'callao'),
  B('pe-phase-a-239', 'تورتيّا الرايا باليوكا والبصل الأحمر', 'Tortilla de Raya with Cassava and Red Onion', 'Tortilla de raya au manioc et à l’oignon rouge', 'Tortilla de raya con yuca y cebolla morada', 'Raya-Tortilla mit Maniok und roter Zwiebel', 'fish_seafood', 'lunch', 20, 17, 8, 'pan_frying', 'piura'),
  B('pe-phase-a-240', 'تشانفاينيتا لحم البقر بالبطاطس والنعناع', 'Beef Chanfainita with Potato and Mint', 'Chanfainita de bœuf à la pomme de terre et à la menthe', 'Chanfainita de res con papa y hierbabuena', 'Rinder-Chanfainita mit Kartoffel und Minze', 'meat_mains', 'lunch', 18, 15, 8, 'stewing', 'lima'),
  B('pe-phase-a-241', 'يخنة البط مع قرع لوخي والكزبرة', 'Duck Stew with Loche Squash and Cilantro', 'Ragoût de canard à la courge loche et coriandre', 'Guiso de pato con zapallo loche y cilantro', 'Enteneintopf mit Loche-Kürbis und Koriander', 'poultry_mains', 'dinner', 22, 12, 9, 'stewing', 'lambayeque'),
  B('pe-phase-a-242', 'شوربة تشوتشوكا بلحم البقر والملفوف', 'Sopa de Chochoca with Beef and Cabbage', 'Soupe de chochoca au bœuf et au chou', 'Sopa de chochoca con res y col', 'Chochoca-Suppe mit Rind und Kohl', 'soups_stews', 'lunch', 17, 21, 7, 'simmering', 'arequipa'),
  B('pe-phase-a-243', 'تاماليتوس فيرديس بالدجاج والكزبرة', 'Tamalitos Verdes with Chicken and Cilantro', 'Tamalitos verdes au poulet et à la coriandre', 'Tamalitos verdes con pollo y cilantro', 'Tamalitos Verdes mit Hähnchen und Koriander', 'poultry_mains', 'lunch', 16, 24, 8, 'steaming', 'piura'),
  B('pe-phase-a-244', 'هوميتا حلوة بالذرة الطازجة والزبيب واليانسون', 'Sweet Corn Humita with Raisins and Anise', 'Humita sucrée au maïs frais, raisins secs et anis', 'Humita dulce de choclo con pasas y anís', 'Süße Humita aus frischem Mais mit Rosinen und Anis', 'rice_cakes_sweets', 'snack', 6, 34, 7, 'steaming', 'ancash'),
  B('pe-phase-a-245', 'بونديراسيونيس ليما مع كاسترد الفانيليا', 'Ponderaciones Limeñas with Vanilla Custard', 'Ponderaciones limeñas à la crème pâtissière vanillée', 'Ponderaciones limeñas con crema pastelera de vainilla', 'Limeñische Ponderaciones mit Vanillecreme', 'rice_cakes_sweets', 'snack', 6, 35, 10, 'frying', 'lima'),
  B('pe-phase-a-246', 'تشاباناس اليوكا بالبانِيلا واليانسون', 'Yuca Chapanas with Panela and Anise', 'Chapanas de yuca à la panela et à l’anis', 'Chapanas de yuca con panela y anís', 'Yuca-Chapanas mit Panela und Anis', 'rice_cakes_sweets', 'snack', 3, 37, 4, 'steaming', 'ica'),
  B('pe-phase-a-247', 'إيمولينتي بالشعير وبذور الكتان وأعشاب الأنديز', 'Emoliente with Barley, Flaxseed and Andean Herbs', 'Emoliente à l’orge, aux graines de lin et herbes andines', 'Emoliente con cebada, linaza y hierbas andinas', 'Emoliente mit Gerste, Leinsamen und Andenkräutern', 'beverages', 'breakfast', 4, 16, 3, 'simmering', 'lima'),
  B('pe-phase-a-248', 'يخنة لسان البقر بالبطاطس والجزر', 'Beef Tongue Stew with Potato and Carrot', 'Ragoût de langue de bœuf à la pomme de terre et carotte', 'Guiso de lengua de res con papa y zanahoria', 'Rinderzungeneintopf mit Kartoffel und Karotte', 'meat_mains', 'dinner', 20, 13, 10, 'stewing', 'cajamarca'),
  B('pe-phase-a-249', 'تشوبي الكانيوا بالخضار والجبن الطازج', 'Cañihua Chupe with Vegetables and Fresh Cheese', 'Chupe de cañihua aux légumes et fromage frais', 'Chupe de cañihua con verduras y queso fresco', 'Cañihua-Chupe mit Gemüse und Frischkäse', 'soups_stews', 'lunch', 12, 22, 7, 'simmering', 'puno'),
  B('pe-phase-a-250', 'باتشامانكا لحم الضأن بالبطاطس الأنديزية والفول العريض', 'Lamb Pachamanca with Native Potatoes and Fava Beans', 'Pachamanca d’agneau aux pommes de terre andines et fèves', 'Pachamanca de cordero con papas nativas y habas', 'Lamm-Pachamanca mit Andenkartoffeln und Ackerbohnen', 'meat_mains', 'dinner', 22, 19, 9, 'baking', 'ayacucho'),
];
