import { B } from '../peru-base-data/rows.mjs';

export default [
  B('pe-phase-a-038', 'شوربة كينوا بالدجاج والجبن الطازج', 'Quinoa Soup with Chicken and Fresh Cheese', 'Soupe de quinoa au poulet et fromage frais', 'Sopa de quinoa con pollo y queso fresco', 'Quinoasuppe mit Hähnchen und Frischkäse', 'soups_stews', 'lunch', 15, 12, 5, 'simmering', 'cusco'),
  B('pe-phase-a-039', 'روكوتو ريلينو نباتي بالكينوا والجبن', 'Vegetarian Rocoto Relleno with Quinoa and Cheese', 'Rocoto relleno végétarien au quinoa et fromage', 'Rocoto relleno vegetariano con quinoa y queso', 'Vegetarisches Rocoto Relleno mit Quinoa und Käse', 'vegetable_mains', 'dinner', 13, 11, 9, 'baking', 'arequipa'),
  B('pe-phase-a-040', 'كوسا دي لانغوستينو بالأفوكادو', 'Langostino Causa with Avocado', 'Causa aux langoustines et avocat', 'Causa de langostino con aguacate', 'Langostino-Causa mit Avocado', 'fish_seafood', 'lunch', 18, 13, 7, 'assembling', 'lima'),
  B('pe-phase-a-041', 'سوسبيرو ليمينيو بكريمة دولسي دي ليتشي', 'Suspiro Limeño with Dulce de Leche Cream', 'Suspiro limeño à la crème de dulce de leche', 'Suspiro limeño con crema de dulce de leche', 'Suspiro Limeño mit Dulce-de-Leche-Creme', 'rice_cakes_sweets', 'snack', 7, 32, 8, 'chilling', 'lima'),
  B('pe-phase-a-042', 'شوربة سمك باليوكا والفلفل الأصفر', 'Fish Soup with Cassava and Aji Amarillo', 'Soupe de poisson au manioc et aji amarillo', 'Sopa de pescado con yuca y ají amarillo', 'Fischsuppe mit Maniok und Aji Amarillo', 'fish_seafood', 'lunch', 18, 12, 5, 'simmering', 'ancash'),
  B('pe-phase-a-043', 'شامبار تروخيو بلحم البقر والقمح والفاصولياء', 'Trujillo Shambar with Beef, Wheat and Beans', 'Shambar de Trujillo au bœuf, blé et haricots', 'Shambar trujillano con res, trigo y frijoles', 'Trujillo-Shambar mit Rind, Weizen und Bohnen', 'soups_stews', 'lunch', 16, 18, 6, 'simmering', 'lima'),
  B('pe-phase-a-044', 'أنتيكوتشو دجاج بصلصة الفلفل والذرة', 'Chicken Anticuchos with Chile Sauce and Corn', 'Anticuchos de poulet à la sauce pimentée et maïs', 'Anticuchos de pollo con salsa de ají y choclo', 'Hähnchen-Anticuchos mit Chilisauce und Mais', 'poultry_mains', 'dinner', 22, 12, 7, 'grilling', 'lima'),
  B('pe-phase-a-045', 'إستوفادو لحم بقري بالفلفل بانكا والبازلاء', 'Beef Estofado with Aji Panca and Peas', 'Estofado de bœuf à l’aji panca et petits pois', 'Estofado de res con ají panca y arvejas', 'Rindfleisch-Estofado mit Aji Panca und Erbsen', 'meat_mains', 'dinner', 19, 9, 8, 'stewing', 'cajamarca'),
  B('pe-phase-a-046', 'بطاطا حلوة محشوة بالديك الرومي والفول السوداني', 'Sweet Potato Stuffed with Turkey and Peanuts', 'Patate douce farcie à la dinde et cacahuètes', 'Camote relleno de pavo y maní', 'Süßkartoffel gefüllt mit Pute und Erdnüssen', 'poultry_mains', 'dinner', 17, 15, 8, 'baking', 'amazonas'),
  B('pe-phase-a-047', 'كينوا تشوفا بلحم البقر والزنجبيل', 'Beef Quinoa Chaufa with Ginger', 'Chaufa de quinoa au bœuf et gingembre', 'Quinua chaufa de res con jengibre', 'Rindfleisch-Quinoa-Chaufa mit Ingwer', 'meat_mains', 'dinner', 19, 19, 8, 'sauteing', 'lima'),
  B('pe-phase-a-048', 'وعاء كيويتشا بالزبادي وفاكهة العاطفة', 'Kiwicha Bowl with Yogurt and Passion Fruit', 'Bol de kiwicha au yaourt et fruit de la passion', 'Tazón de kiwicha con yogur y maracuyá', 'Kiwicha-Schale mit Joghurt und Passionsfrucht', 'breakfast_items', 'breakfast', 12, 22, 6, 'assembling', 'cusco'),
  B('pe-phase-a-049', 'تروتا تيتكاكا بالكينوا والفاصولياء', 'Lake Titicaca Trout with Quinoa and Beans', 'Truite du lac Titicaca au quinoa et haricots', 'Trucha del Titicaca con quinoa y frijoles', 'Titicaca-Forelle mit Quinoa und Bohnen', 'fish_seafood', 'dinner', 22, 13, 7, 'grilling', 'puno'),
  B('pe-phase-a-050', 'بيكارونيس القرع والبطاطا الحلوة بالقرفة', 'Pumpkin and Sweet Potato Picarones with Cinnamon', 'Picarones de courge et patate douce à la cannelle', 'Picarones de zapallo y camote con canela', 'Kürbis-Süßkartoffel-Picarones mit Zimt', 'rice_cakes_sweets', 'snack', 5, 35, 8, 'frying', 'lima'),
];
