import { B } from '../peru-base-data/rows.mjs';

export default [
  B('pe-phase-a-088', 'كوسا لانغوستينو بالفلفل الأصفر والليمون', 'Langostino Causa with Aji Amarillo and Lime', 'Causa aux langoustines, aji amarillo et citron vert', 'Causa de langostino con ají amarillo y lima', 'Langostino-Causa mit Aji Amarillo und Limette', 'fish_seafood', 'lunch', 18, 13, 7, 'assembling', 'lima'),
  B('pe-phase-a-089', 'سيكو دجاج بالكزبرة والفاصولياء', 'Chicken Seco with Cilantro and Beans', 'Seco de poulet à la coriandre et haricots', 'Seco de pollo con cilantro y frijoles', 'Hähnchen-Seco mit Koriander und Bohnen', 'poultry_mains', 'dinner', 20, 11, 7, 'braising', 'cajamarca'),
  B('pe-phase-a-090', 'تالارينيس روخوس بالدجاج والطماطم', 'Tallarines Rojos with Chicken and Tomato', 'Tallarines rojos au poulet et tomate', 'Tallarines rojos con pollo y tomate', 'Tallarines Rojos mit Hähnchen und Tomate', 'poultry_mains', 'dinner', 17, 23, 7, 'simmering', 'lima'),
  B('pe-phase-a-091', 'سموذي مانجو بالمكا والزبادي', 'Mango Smoothie with Maca and Yogurt', 'Smoothie à la mangue, maca et yaourt', 'Batido de mango con maca y yogur', 'Mango-Smoothie mit Maca und Joghurt', 'beverages', 'breakfast', 10, 20, 4, 'blending', 'cusco'),
  B('pe-phase-a-092', 'سيفيتشي إسكالوب بفاكهة العاطفة والخيار', 'Scallop Ceviche with Passion Fruit and Cucumber', 'Ceviche de pétoncles au fruit de la passion et concombre', 'Ceviche de conchas de abanico con maracuyá y pepino', 'Jakobsmuschel-Ceviche mit Passionsfrucht und Gurke', 'fish_seafood', 'lunch', 18, 7, 3, 'marinating', 'piura'),
  B('pe-phase-a-093', 'روكوتو ريلينو بالدجاج والكينوا والجبن', 'Rocoto Relleno with Chicken, Quinoa and Cheese', 'Rocoto relleno au poulet, quinoa et fromage', 'Rocoto relleno de pollo, quinoa y queso', 'Rocoto Relleno mit Hähnchen, Quinoa und Käse', 'poultry_mains', 'dinner', 18, 12, 8, 'baking', 'arequipa'),
  B('pe-phase-a-094', 'لانغوستينو بصلصة أجي أماريلو والذرة', 'Langostino with Aji Amarillo Sauce and Corn', 'Langoustine à la sauce aji amarillo et maïs', 'Langostino en salsa de ají amarillo con maíz', 'Langostino mit Aji-Amarillo-Soße und Mais', 'fish_seafood', 'dinner', 19, 8, 6, 'sauteing', 'lima'),
  B('pe-phase-a-095', 'ألباكا مشوية بالكينوا والخضار', 'Grilled Alpaca with Quinoa and Vegetables', 'Alpaca grillée au quinoa et légumes', 'Alpaca a la parrilla con quinoa y verduras', 'Gegrilltes Alpaka mit Quinoa und Gemüse', 'meat_mains', 'dinner', 23, 12, 7, 'grilling', 'cusco'),
  B('pe-phase-a-096', 'تاكو تاكو الروبيان وصلصة كريولا', 'Shrimp Tacu Tacu with Criolla Salsa', 'Tacu tacu aux crevettes et salsa criolla', 'Tacu tacu de camarones con salsa criolla', 'Garnelen-Tacu-Tacu mit Criolla-Salsa', 'fish_seafood', 'lunch', 18, 21, 8, 'pan_frying', 'callao'),
  B('pe-phase-a-097', 'كروكيت البطاطا والسمك بالفلفل الأصفر', 'Potato and Fish Croquettes with Aji Amarillo', 'Croquettes de pomme de terre et poisson à l’aji amarillo', 'Croquetas de papa y pescado con ají amarillo', 'Kartoffel-Fisch-Kroketten mit Aji Amarillo', 'fish_seafood', 'snack', 16, 18, 7, 'baking', 'ancash'),
  B('pe-phase-a-098', 'ليتشي أسادا بالكينوا والحليب', 'Leche Asada with Quinoa and Milk', 'Leche asada au quinoa et lait', 'Leche asada con quinoa y leche', 'Leche Asada mit Quinoa und Milch', 'rice_cakes_sweets', 'snack', 9, 20, 7, 'baking', 'lima'),
  B('pe-phase-a-099', 'سلطة سوليتيريتو كينوا بالفول والذرة والجبن', 'Quinoa Solterito with Fava Beans, Corn and Cheese', 'Solterito de quinoa aux fèves, maïs et fromage', 'Solterito de quinoa con habas, maíz y queso', 'Quinoa-Solterito mit Ackerbohnen, Mais und Käse', 'salads', 'lunch', 12, 18, 7, 'assembling', 'arequipa'),
  B('pe-phase-a-100', 'سموذي شيريمويا بالشيا والزبادي', 'Chirimoya Smoothie with Chia and Yogurt', 'Smoothie de chirimoya au chia et yaourt', 'Batido de chirimoya con chía y yogur', 'Chirimoya-Smoothie mit Chia und Joghurt', 'beverages', 'breakfast', 9, 18, 5, 'blending', 'amazonas'),
];
