import { B } from '../peru-base-data/rows.mjs';

export default [
  B('pe-phase-a-064', 'سمك تشورّيلانا بالطماطم والبصل والبطاطس', 'Pescado a la Chorrillana with Tomato, Onion and Potato', 'Pescado a la chorrillana à la tomate, oignon et pomme de terre', 'Pescado a la chorrillana con tomate, cebolla y papa', 'Pescado a la Chorrillana mit Tomate, Zwiebel und Kartoffel', 'fish_seafood', 'dinner', 20, 12, 7, 'braising', 'lima'),
  B('pe-phase-a-065', 'تشوبي فول عريض بالقرع والجبن', 'Fava Bean Chupe with Squash and Cheese', 'Chupe de fèves à la courge et fromage', 'Chupe de habas con zapallo y queso', 'Ackerbohnen-Chupe mit Kürbis und Käse', 'soups_stews', 'lunch', 12, 16, 6, 'simmering', 'arequipa'),
  B('pe-phase-a-066', 'بالوميتا ريلينا بالدجاج والذرة', 'Palometa Rellena with Chicken and Corn', 'Palometa rellena au poulet et maïs', 'Palometa rellena de pollo y maíz', 'Gefüllte Palometa mit Hähnchen und Mais', 'fish_seafood', 'dinner', 19, 9, 8, 'baking', 'amazonas'),
  B('pe-phase-a-067', 'تاريّا دي كينوا بالسبانخ والطماطم', 'Quinoa Tacu with Spinach and Tomato', 'Tacu de quinoa aux épinards et tomate', 'Tacu de quinoa con espinaca y tomate', 'Quinoa-Tacu mit Spinat und Tomate', 'vegetable_mains', 'lunch', 12, 20, 6, 'pan_frying', 'cusco'),
  B('pe-phase-a-068', 'تورتيّا تاروي بالبيض والبطاطس', 'Tarwi Tortilla with Egg and Potato', 'Tortilla de tarwi à l’œuf et pomme de terre', 'Tortilla de tarwi con huevo y papa', 'Tarwi-Tortilla mit Ei und Kartoffel', 'breakfast_items', 'breakfast', 16, 12, 8, 'pan_frying', 'puno'),
  B('pe-phase-a-069', 'تروتا بصلصة الفلفل الأصفر والليمون', 'Trout with Aji Amarillo Lime Sauce', 'Truite à la sauce aji amarillo et citron vert', 'Trucha con salsa de ají amarillo y lima', 'Forelle mit Aji-Amarillo-Limettensoße', 'fish_seafood', 'dinner', 21, 5, 8, 'baking', 'puno'),
  B('pe-phase-a-070', 'كروكيت تاروي بالجبن والطماطم', 'Tarwi Croquettes with Cheese and Tomato', 'Croquettes de tarwi au fromage et tomate', 'Croquetas de tarwi con queso y tomate', 'Tarwi-Kroketten mit Käse und Tomate', 'vegetable_mains', 'snack', 15, 16, 7, 'baking', 'cusco'),
  B('pe-phase-a-071', 'لحم بقري بصلصة التاماريلو والبطاطس', 'Beef with Tamarillo Sauce and Potato', 'Bœuf à la sauce tomate en arbre et pomme de terre', 'Res con salsa de tomate de árbol y papa', 'Rindfleisch mit Baumtomatensoße und Kartoffel', 'meat_mains', 'dinner', 20, 10, 8, 'braising', 'cajamarca'),
  B('pe-phase-a-072', 'بولو كينوا بالدجاج والخضار', 'Quinoa Pilaf with Chicken and Vegetables', 'Pilaf de quinoa au poulet et légumes', 'Pilaf de quinoa con pollo y verduras', 'Quinoa-Pilaw mit Hähnchen und Gemüse', 'poultry_mains', 'dinner', 18, 17, 6, 'simmering', 'cusco'),
  B('pe-phase-a-073', 'بطاطس أونكوياس بصلصة الخردل', 'Uncuyas Potatoes with Mustard Sauce', 'Pommes de terre uncuyas à la sauce moutarde', 'Papas uncuyas con salsa de mostaza', 'Uncuyas-Kartoffeln mit Senfsoße', 'vegetable_mains', 'side', 9, 20, 5, 'boiling', 'ancash'),
  B('pe-phase-a-074', 'ألبوندجاس كينوا بصلصة الطماطم', 'Quinoa Meatballs in Tomato Sauce', 'Boulettes de quinoa à la sauce tomate', 'Albóndigas de quinoa en salsa de tomate', 'Quinoa-Bällchen in Tomatensoße', 'vegetable_mains', 'dinner', 13, 16, 6, 'simmering', 'lima'),
  B('pe-phase-a-075', 'مازامورا كينوا بالأناناس والقرفة', 'Quinoa Mazamorra with Pineapple and Cinnamon', 'Mazamorra de quinoa à l’ananas et cannelle', 'Mazamorra de quinoa con piña y canela', 'Quinoa-Mazamorra mit Ananas und Zimt', 'rice_cakes_sweets', 'snack', 8, 28, 4, 'simmering', 'cajamarca'),
];
