import { B, diasporaFor } from './rows.mjs';

const ML = 'midlands';
const NW = 'north_west';
const Y = 'yorkshire';

export default [
  B('فطيرة ستافوردشاير', 'Staffordshire Beef Pie', 'Tourte au boeuf du Staffordshire', 'Pastel de res de Staffordshire', 'Staffordshire-Rindfleischpastete', 'meat_mains', 'dinner', 13, 20, 12, 'baking', ML, diasporaFor(ML)),
  B('كرمبالت البيض', 'Egg Crumpets', 'Crumpets aux oeufs', 'Crumpets de huevo', 'Eier-Crumpets', 'breakfast_items', 'breakfast', 8, 18, 8, 'griddled', ML, diasporaFor(ML)),
  B('خبز بيشيا', 'Nottinghamshire Poppy Bread', 'Pain a la pavot', 'Pan de amapola', 'Mohnbrot', 'breakfast_items', 'breakfast', 5, 28, 3, 'baking', ML, diasporaFor(ML)),
  B('جبنة سيديتون', 'Red Leicester Cheese', 'Red Leicester', 'Queso Red Leicester', 'Red-Leicester-Kase', 'vegetable_mains', 'snack', 10, 2, 22, 'aging', ML, diasporaFor(ML)),
  B('جبنة ستيلتون', 'Stilton Cheese', 'Stilton', 'Queso Stilton', 'Stilton', 'vegetable_mains', 'snack', 10, 2, 22, 'aging', ML, diasporaFor(ML)),
  B('جبنة تشيستر', 'Cheshire Cheese', 'Cheshire', 'Queso Cheshire', 'Cheshire', 'vegetable_mains', 'snack', 10, 2, 22, 'aging', ML, diasporaFor(ML)),
  B('جيلي التوت الأسود', 'Blackberry Jelly', 'Gelée de mûres', 'Jalea de mora', 'Brombeer-Gelee', 'condiments_sauces', 'snack', 0, 20, 0, 'boiling', ML, diasporaFor(ML)),
  B('حساء الطماطم والريحان', 'Tomato and Basil Soup', 'Soupe tomates-basilic', 'Sopa de tomate y albahaca', 'Tomaten-Basilikum-Suppe', 'soups_stews', 'lunch', 2, 9, 3, 'simmering', ML, diasporaFor(ML)),
  B('مربى الكشمش الأحمر', 'Redcurrant Jam', 'Confiture de groseilles rouges', 'Mermelada de grosella roja', 'Rote-Johannisbeergelee', 'condiments_sauces', 'snack', 0, 20, 0, 'boiling', ML, diasporaFor(ML)),
  B('بطاطا بالجبن والتوابل', 'Cheese and Chive Potatoes', 'Pommes de terre au fromage et ciboulette', 'Patatas con queso y cebollino', 'Kase-Schnittlauch-Kartoffeln', 'vegetable_mains', 'dinner', 4, 18, 7, 'baking', ML, diasporaFor(ML)),
  B('حساء البازلاء والجزر', 'Split Pea and Carrot Broth', 'Bouillon pois-carottes', 'Caldo de guisantes y zanahoria', 'Erbsen-Möhren-Bruehe', 'soups_stews', 'lunch', 5, 8, 2, 'simmering', ML, diasporaFor(ML)),
  B('بودنج اللوز', 'Bakewell Tart', 'Tarte Bakewell', 'Tarta Bakewell', 'Bakewell-Tarte', 'rice_cakes_sweets', 'snack', 5, 30, 12, 'baking', ML, diasporaFor(ML)),
  B('كعك جنزبيل لينكولنشاير', 'Lincolnshire Gingerbread', 'Pain d épices du Lincolnshire', 'Pan de jengibre de Lincolnshire', 'Lincolnshire-Gingerbread', 'rice_cakes_sweets', 'snack', 3, 28, 9, 'baking', ML, diasporaFor(ML)),
  B('فطيرة لحم البقر والتفاح', 'Beef and Apple Pudding', 'Pudding boeuf-pommes', 'Pudin de res y manzana', 'Rindfleisch-Apfel-Pudding', 'meat_mains', 'dinner', 10, 20, 10, 'steaming', ML, diasporaFor(ML)),
  B('خبز بذور الكتان', 'Linseed Bread', 'Pain aux graines de lin', 'Pan de linaza', 'Leinsamenbrot', 'breakfast_items', 'breakfast', 6, 24, 6, 'baking', ML, diasporaFor(ML)),
  B('سلطة البطاطا بالخردل', 'Potato and Mustard Salad', 'Salade pommes de terre-moutarde', 'Ensalada de patatas con mostaza', 'Kartoffelsalat mit Senf', 'vegetable_mains', 'lunch', 3, 16, 6, 'boiling', ML, diasporaFor(ML)),
  B('جبنة ليستر الحمراء', 'Red Leicester with Onion', 'Red Leicester aux oignons', 'Red Leicester con cebolla', 'Red-Leicester mit Zwiebeln', 'vegetable_mains', 'snack', 9, 3, 20, 'aging', ML, diasporaFor(ML)),
  B('توت الأرض عصير', 'Strawberry Compote', 'Compote de fraises', 'Compota de fresa', 'Erdbeerkompott', 'fruit', 'snack', 1, 16, 0, 'simmering', ML, diasporaFor(ML)),
  B('حساء البصل', 'Onion Soup', 'Soupe a l oignon', 'Sopa de cebolla', 'Zwiebelsuppe', 'soups_stews', 'lunch', 2, 9, 5, 'simmering', ML, diasporaFor(ML)),
  B('خضار مشكلة مطهوة', 'Mixed Root Vegetables', 'Legumes racines mèles', 'Hortalizas de raíz', 'Gemüsewürfel', 'vegetable_mains', 'dinner', 2, 12, 2, 'boiling', ML, diasporaFor(ML)),
  B('فطيرة اللحم مانشستر', 'Manchester Meat Pudding', 'Pudding de viande de Manchester', 'Pudin de carne de Manchester', 'Manchester-Fleischpudding', 'meat_mains', 'dinner', 13, 18, 11, 'steaming', NW, diasporaFor(NW)),
  B('حساء لحم الضأن بالرندر', 'Lancashire Hotpot', 'Hotpot du Lancashire', 'Hotpot de Lancashire', 'Lancashire Hotpot', 'soups_stews', 'dinner', 15, 12, 12, 'baking', NW, diasporaFor(NW)),
  B('خبز مانشستر', 'Manchester Barm Loaf', 'Pain de Manchester', 'Pan de Manchester', 'Manchester-Brot', 'breakfast_items', 'breakfast', 6, 28, 3, 'baking', NW, diasporaFor(NW)),
  B('فطيرة الليمون مرزبان', 'Liverpool Lemon Tart', 'Tarte au citron de Liverpool', 'Tarta de limon de Liverpool', 'Liverpool-Zitronentarte', 'rice_cakes_sweets', 'snack', 3, 30, 11, 'baking', NW, diasporaFor(NW)),
  B('بودنج الشوكولا', 'Chocolate Pudding', 'Pudding au chocolat', 'Pudin de chocolate', 'Schokoladenpudding', 'rice_cakes_sweets', 'snack', 4, 28, 10, 'baking', NW, diasporaFor(NW)),
  B('جبنة تشيدر لانكشاير', 'Lancashire Cheese', 'Lancashire', 'Queso Lancashire', 'Lancashire-Kase', 'vegetable_mains', 'snack', 10, 2, 22, 'aging', NW, diasporaFor(NW)),
  B('جبنة كريسويل', 'Crumbland Cheese', 'Crumble cheese', 'Queso Crumble', 'Crumbland-Kase', 'vegetable_mains', 'snack', 9, 2, 20, 'aging', NW, diasporaFor(NW)),
  B('شاي بقشدة مانشستر', 'Manchester Cream Tea', 'Cream tea de Manchester', 'Merienda con crema', 'Manchester-Cream-Tea', 'rice_cakes_sweets', 'snack', 4, 28, 10, 'assembling', NW, diasporaFor(NW)),
  B('بطاطا مقلية بالزبدة', 'Buttered New Potatoes', 'Pommes de terre nouvelles au beurre', 'Patatas nuevas con mantequilla', 'Neue Kartoffeln mit Butter', 'vegetable_mains', 'dinner', 2, 16, 5, 'boiling', NW, diasporaFor(NW)),
  B('حساء الجزر والكرفس', 'Carrot and Celery Soup', 'Soupe carottes-celeri', 'Sopa de zanahoria y apio', 'Möhren-Sellerie-Suppe', 'soups_stews', 'lunch', 2, 9, 3, 'simmering', NW, diasporaFor(NW)),
  B('رقائق البطاطا', 'Crisp Potato Cakes', 'Galettes de pommes de terre', 'Tortas de patata', 'Kartoffelflocken-Kuchen', 'vegetable_mains', 'snack', 3, 20, 6, 'frying', NW, diasporaFor(NW)),
  B('حساء الفاصولي والبصل', 'Bean and Onion Broth', 'Bouillon haricots-oignons', 'Caldo de judias y cebolla', 'Bohnen-Zwiebel-Brühe', 'soups_stews', 'lunch', 5, 10, 2, 'simmering', NW, diasporaFor(NW)),
  B('معجون التفاح', 'Apple Purée', 'Puree de pommes', 'Pure de manzana', 'Apfelmus', 'fruit', 'snack', 0, 14, 0, 'simmering', NW, diasporaFor(NW)),
  B('خبز الشوفان', 'Oatmeal Bread', 'Pain a l avoine', 'Pan de avena', 'Haferbrot', 'breakfast_items', 'breakfast', 6, 26, 5, 'baking', NW, diasporaFor(NW)),
  B('فطيرة شيدر لانكشاير', 'Lancashire Cheese Pie', 'Tourte au fromage Lancashire', 'Pastel de queso Lancashire', 'Lancashire-Kasepastete', 'vegetable_mains', 'lunch', 9, 18, 12, 'baking', NW, diasporaFor(NW)),
  B('بسكويت الشوفان', 'Oat Biscuits', 'Biscuits a l avoine', 'Galletas de avena', 'Haferkekse', 'rice_cakes_sweets', 'snack', 3, 24, 10, 'baking', NW, diasporaFor(NW)),
  B('كعك الزنجبيل يوركشاير', 'Yorkshire Ginger Loaf', 'Pain au gingembre du Yorkshire', 'Pan de jengibre de Yorkshire', 'Yorkshire-Gebäck mit Ingwer', 'rice_cakes_sweets', 'snack', 3, 28, 8, 'baking', Y, diasporaFor(Y)),
  B('فطيرة يوركشاير', 'Yorkshire Pudding', 'Pudding Yorkshire', 'Pudin Yorkshire', 'Yorkshire Pudding', 'vegetable_mains', 'dinner', 4, 14, 6, 'baking', Y, diasporaFor(Y)),
  B('كرمبتس يوركشاير', 'Yorkshire Crumpets', 'Crumpets du Yorkshire', 'Crumpets de Yorkshire', 'Yorkshire-Crumpets', 'breakfast_items', 'breakfast', 4, 20, 4, 'griddled', Y, diasporaFor(Y)),
  B('فطيرة اللحم يوركشاير', 'Yorkshire Meat Pie', 'Tourte de viande du Yorkshire', 'Pastel de carne de Yorkshire', 'Yorkshire-Fleischpastete', 'meat_mains', 'dinner', 13, 20, 12, 'baking', Y, diasporaFor(Y)),
  B('شاي بقشدة يوركشاير', 'Yorkshire Cream Tea', 'Cream tea du Yorkshire', 'Merienda de crema de Yorkshire', 'Yorkshire-Cream-Tea', 'rice_cakes_sweets', 'snack', 4, 28, 10, 'assembling', Y, diasporaFor(Y)),
  B('جبنة ويدزورث', 'Wensleydale Cheese', 'Wensleydale', 'Queso Wensleydale', 'Wensleydale', 'vegetable_mains', 'snack', 10, 3, 20, 'aging', Y, diasporaFor(Y)),
  B('جبنة موراي', 'Swaledale Cheese', 'Swaledale', 'Queso Swaledale', 'Swaledale', 'vegetable_mains', 'snack', 9, 3, 20, 'aging', Y, diasporaFor(Y)),
  B('حساء البازلاء والشمندر', 'Pea and Beetroot Soup', 'Soupe petits pois-betteraves', 'Sopa de guisantes y remolacha', 'Erbsen-Rote-Bete-Suppe', 'soups_stews', 'lunch', 3, 10, 2, 'simmering', Y, diasporaFor(Y)),
  B('مربى التوت', 'Raspberry Jam', 'Confiture de framboises', 'Mermelada de frambuesa', 'Himbeer-Gelee', 'condiments_sauces', 'snack', 0, 20, 0, 'boiling', Y, diasporaFor(Y)),
  B('صلصة خردل وتفاح', 'Apple Mustard Sauce', 'Sauce pommes-moutarde', 'Salsa de manzana y mostaza', 'Apfel-Senf-Sauce', 'condiments_sauces', 'snack', 1, 10, 6, 'simmering', Y, diasporaFor(Y)),
  B('سلطة الجزر والكمثرى', 'Carrot and Pear Salad', 'Salade carottes-poires', 'Ensalada de zanahoria y pera', 'Möhren-Birnen-Salat', 'vegetable_mains', 'lunch', 2, 12, 4, 'raw', Y, diasporaFor(Y)),
  B('خبز الشعير', 'Barley Bread', 'Pain d orge', 'Pan de cebada', 'Gerstenbrot', 'breakfast_items', 'breakfast', 6, 24, 4, 'baking', Y, diasporaFor(Y)),
  B('بودنج الزنجبيل', 'Ginger Pudding', 'Pudding au gingembre', 'Pudin de jengibre', 'Ingwerpudding', 'rice_cakes_sweets', 'snack', 3, 28, 8, 'steaming', Y, diasporaFor(Y)),
  B('معجون التوت الأسود', 'Blackcurrant Purée', 'Puree de cassis', 'Pure de grosella negra', 'Johannisbeermus', 'fruit', 'snack', 0, 14, 0, 'simmering', Y, diasporaFor(Y)),
];
