import { B, diasporaFor } from './rows.mjs';

const SE = 'south_east';
const SW = 'south_west';
const EA = 'east_anglia';

export default [
  B('مثلث القشطة بالفراولة', 'Eton Mess', 'Eton mess', 'Eton mess', 'Eton-Mess', 'rice_cakes_sweets', 'snack', 3, 30, 8, 'assembling', SE, diasporaFor(SE)),
  B('لحم غنم بالروزماري السكسوني', 'Sussex Rosemary Lamb', 'Agneau au romarin du Sussex', 'Cordero con romero de Sussex', 'Sussex-Lamm mit Rosmarin', 'meat_mains', 'dinner', 16, 2, 13, 'roasting', SE, diasporaFor(SE)),
  B('فراولة كنت', 'Kent Strawberries', 'Fraises du Kent', 'Fresas de Kent', 'Kent-Erdbeeren', 'fruit', 'snack', 1, 8, 0, 'raw', SE, diasporaFor(SE)),
  B('تفاح شيبي', 'Sheppey Pippin Apples', 'Pommes Sheppey Pippin', 'Manzanas Sheppey Pippin', 'Sheppey-Pippin-Aepfel', 'fruit', 'snack', 0, 13, 0, 'raw', SE, diasporaFor(SE)),
  B('طماطم وايت آيلاند', 'Isle of Wight Tomatoes', 'Tomates de l Isle of Wight', 'Tomates de Isle of Wight', 'Insel-von-Wight-Tomaten', 'fruit', 'snack', 1, 4, 0, 'raw', SE, diasporaFor(SE)),
  B('رغيف خبز الجاودار', 'Rye Bread Loaf', 'Pain de seigle', 'Pan de centeno', 'Roggenbrot', 'breakfast_items', 'breakfast', 6, 30, 3, 'baking', SE, diasporaFor(SE)),
  B('حزمة جرجير الماء', 'Watercress Bund', 'Broussee de cresson', 'Racimo de-berro', 'Wasserkressebund', 'vegetable_mains', 'lunch', 3, 3, 1, 'raw', SE, diasporaFor(SE)),
  B('خل الشعير', 'Malt Vinegar', 'Vinaigre de malt', 'Vinagre de malta', 'Malzessig', 'condiments_sauces', 'snack', 0, 3, 0, 'fermentation', SE, diasporaFor(SE)),
  B('صلصة وورسترشاير', 'Worcestershire Sauce', 'Sauce Worcester', 'Salsa Worcester', 'Worcester-Sauce', 'condiments_sauces', 'snack', 1, 8, 0, 'simmering', SE, diasporaFor(SE)),
  B('صلصة الفجل', 'Horseradish Sauce', 'Sauce au raifort', 'Salsa de rábano', 'Meerrettichsauce', 'condiments_sauces', 'snack', 1, 6, 6, 'mixing', SE, diasporaFor(SE)),
  B('مربى الكشمش الاسود', 'Blackcurrant Jam', 'Confiture de cassis', 'Mermelada de grosella', 'Johannisbeergelee', 'condiments_sauces', 'snack', 0, 22, 0, 'boiling', SE, diasporaFor(SE)),
  B('بسكويت خلية النحل', 'Honeycomb Biscuits', 'Biscuits en nid d abeille', 'Galletas de panal', 'Honigwaben-Kekse', 'rice_cakes_sweets', 'snack', 2, 26, 8, 'baking', SE, diasporaFor(SE)),
  B('جبنة سلتكوت', 'Sussex Slipcote Cheese', 'Fromage Slipcote du Sussex', 'Queso Slipcote de Sussex', 'Sussex-Slipcote-Kase', 'vegetable_mains', 'snack', 9, 3, 22, 'aging', SE, diasporaFor(SE)),
  B('صلصة البقدونس والسمن', 'Parsley Butter Sauce', 'Sauce au beurre et persil', 'Salsa de mantequilla y perejil', 'Petersilien-Butter-Sauce', 'condiments_sauces', 'snack', 1, 4, 15, 'mixing', SE, diasporaFor(SE)),
  B('حساء البازلاء بالنعناع', 'Pea and Mint Soup', 'Soupe aux petits pois et menthe', 'Sopa de guisantes y menta', 'Erbsen-Minz-Suppe', 'soups_stews', 'lunch', 3, 9, 2, 'simmering', SE, diasporaFor(SE)),
  B('خس مطهو مع البازلاء', 'Braised Lettuce with Peas', 'Laitue braisee aux petits pois', 'Lechuga braseada con guisantes', 'Geschmortes Salat mit Erbsen', 'vegetable_mains', 'dinner', 2, 8, 5, 'braising', SE, diasporaFor(SE)),
  B('ترافل التوت الصيفي', 'Summer Berry Trifle', 'Trifle aux fruits des bois', 'Trifle de frutos rojos', 'Beeren-Trifle', 'rice_cakes_sweets', 'snack', 3, 26, 7, 'chilling', SE, diasporaFor(SE)),
  B('فطيرة لحم البقر والقرنبيط', 'Cornish Beef and Onion Pasty', 'Pasty de boeuf et oignons de Cornouailles', 'Empanada de res y cebolla de Cornualles', 'Cornwall-Rindpastete mit Zwiebeln', 'meat_mains', 'lunch', 11, 22, 12, 'baking', SW, diasporaFor(SW)),
  B('شاي القشطة كورنوول', 'Devonshire Cream Tea', 'Cream tea du Devonshire', 'Merienda de crema de Devonshire', 'Devonshire-Cream-Tea', 'rice_cakes_sweets', 'snack', 4, 30, 10, 'assembling', SW, diasporaFor(SW)),
  B('سكون بالقشطة الكورنية', 'Scone with Cornish Clotted Cream', 'Scone a la creme de Cornouailles', 'Scone con crema de Cornualles', 'Scone mitCornwall-Sahnne', 'rice_cakes_sweets', 'snack', 4, 28, 12, 'griddled', SW, diasporaFor(SW)),
  B('فطيرة سمك ستارغازي', 'Cornish Stargazy Pie', 'Tourte de poisson Stargazy', 'Pastel de pescado Stargazy', 'Stargazy-Fischpastete', 'fish_seafood', 'dinner', 12, 20, 12, 'baking', SW, diasporaFor(SW)),
  B('بلح البحر المطهو', 'Clovelly Steamed Mussels', 'Moules a la vapeur de Clovelly', 'Mejillones al vapor de Clovelly', 'Gedampfte Muscheln aus Clovelly', 'fish_seafood', 'dinner', 13, 6, 6, 'steaming', SW, diasporaFor(SW)),
  B('جبنة شيدر سومرست', 'Somerset Cheddar Cheese', 'Cheddar du Somerset', 'Queso Cheddar de Somerset', 'Somerset-Cheddar', 'vegetable_mains', 'snack', 10, 3, 26, 'aging', SW, diasporaFor(SW)),
  B('جبنة غلوسترشستر المزدوجة', 'Gloucestershire Double Cheese', 'Double Gloucester', 'Queso Double Gloucester', 'Double-Gloucester-Kase', 'vegetable_mains', 'snack', 9, 3, 25, 'aging', SW, diasporaFor(SW)),
  B('كعك باث', 'Bath Bun', 'Bath bun', 'Bun de Bath', 'Bath-Bun', 'breakfast_items', 'breakfast', 6, 28, 8, 'baking', SW, diasporaFor(SW)),
  B('بسكويت باث أوليفر', 'Bath Oliver Biscuit', 'Bath Oliver', 'Bath Oliver', 'Bath-Oliver', 'rice_cakes_sweets', 'snack', 4, 30, 12, 'baking', SW, diasporaFor(SW)),
  B('حساء القرع الكورني', 'Cornish Squash Soup', 'Veloute de squash', 'Crema de calabaza', 'Kurbissuppe', 'soups_stews', 'lunch', 2, 10, 4, 'simmering', SW, diasporaFor(SW)),
  B('بودنج التوت السريع', 'Hasty Berry Pudding', 'Hasty pudding aux fruits des bois', 'Hasty pudding de frutos rojos', 'Hasty-Pudding mit Beeren', 'rice_cakes_sweets', 'snack', 3, 26, 5, 'baking', SW, diasporaFor(SW)),
  B('كسر الكمثرى واللوز', 'Dorset Pear and Almond Crumble', 'Crumble de poires et amandes', 'Crumble de pera y almendra', 'Birnen-Mandel-Streusel', 'rice_cakes_sweets', 'snack', 2, 28, 8, 'baking', SW, diasporaFor(SW)),
  B('صلصة الترنجان الكريمية', 'Creamy Tarragon Sauce', 'Sauce a la creme et estragon', 'Salsa cremosa de estragon', 'Estragon-Rahm-Sauce', 'condiments_sauces', 'snack', 1, 5, 14, 'mixing', SW, diasporaFor(SW)),
  B('خبز محمّص بالسلطعون البني', 'Brown Crab Toast', 'Tartine au crabe', 'Tostada de cangrejo', 'Krabbenbrot', 'fish_seafood', 'snack', 11, 12, 7, 'grilling', SW, diasporaFor(SW)),
  B('فطيرة ستيك بال المشروم', 'Steak and Mushroom Pie', 'Tourte au boeuf et champignons', 'Pastel de vacuno y champinones', 'Rindersteak-Pilz-Pastete', 'meat_mains', 'dinner', 13, 22, 13, 'baking', SW, diasporaFor(SW)),
  B('ماكريل مشوي بالليمون', 'Grilled Mackerel with Lemon', 'Mackerel grille au citron', 'Caballa a la parrilla con limon', 'Gegrillte Makrele mit Zitrone', 'fish_seafood', 'dinner', 20, 0, 10, 'grilling', SW, diasporaFor(SW)),
  B('مازارين بالشوكولا', 'Chocolate Mazarin', 'Mazarin au chocolat', 'Mazarin de chocolate', 'Schokoladen-Mazarin', 'rice_cakes_sweets', 'snack', 6, 32, 16, 'baking', SW, diasporaFor(SW)),
  B('سلطعان كرومر بالزبدة', 'Cromer Crab with Butter', 'Crabe de Cromer au beurre', 'Cangrejo de Cromer con mantequilla', 'Cromer-Krabbe mit Butter', 'fish_seafood', 'dinner', 17, 2, 7, 'boiling', EA, diasporaFor(EA)),
  B('فيليه هادوك يارموث', 'Yarmouth Haddock Fillet', 'Filet de haddock de Yarmouth', 'Filete de bacalao de Yarmouth', 'Yarmouth-Schellfischfilet', 'fish_seafood', 'dinner', 20, 1, 3, 'roasting', EA, diasporaFor(EA)),
  B('ديك رومي مشوي بالكستناء', 'Roast Turkey with Chestnuts', 'Dinde rotie aux marechiches', 'Pavo asado con castanas', 'Truthahn mit Kastanien', 'poultry_mains', 'dinner', 20, 6, 12, 'roasting', EA, diasporaFor(EA)),
  B('بروكلي بنفسجي مشوي', 'Purple Sprouting Broccoli', 'Brocoli violet grenne', 'Brocoli morado alto', 'Violetter Brokkoli', 'vegetable_mains', 'dinner', 3, 6, 1, 'steaming', EA, diasporaFor(EA)),
  B(' خبز الزنجبيل من إيلي', 'خبز الزنجبيل من إيلي Gingerbread', 'Ely boat au gingembre', 'Ely boat de jengibre', 'Ely-Boat-Gingerbread', 'rice_cakes_sweets', 'snack', 2, 32, 6, 'baking', EA, diasporaFor(EA)),
  B('كعك الزعفران', 'Saffron Bun', 'Pain a la fleur de safran', 'Bollo de azafran', 'Safran-Brötchen', 'breakfast_items', 'breakfast', 5, 30, 8, 'baking', EA, diasporaFor(EA)),
  B('سلطة الشمندر', 'Beetroot Salad', 'Salade de betteraves', 'Ensalada de-remolacha', 'Rote-Bete-Salat', 'vegetable_mains', 'lunch', 2, 9, 5, 'roasting', EA, diasporaFor(EA)),
  B('مربى البرقوق', 'Plum Jam', 'Confiture de prunes', 'Mermelada de ciruela', 'Pflaumen-Gelee', 'condiments_sauces', 'snack', 0, 22, 0, 'boiling', EA, diasporaFor(EA)),
  B('صلصة بنية من إيبسويتش', 'Ipswich Brown Sauce', 'Sauce brune d Ipswich', 'Salsa brown de Ipswich', 'Ipswich-Brown-Sauce', 'condiments_sauces', 'snack', 1, 12, 0, 'simmering', EA, diasporaFor(EA)),
  B('قرص نورفولك بالأعشاب', 'Norfolk Herb Dumplings', 'Quenelles d herbes du Norfolk', 'Dumplings de hierbas del Norfolk', 'Norfolk-Krauterdelinge', 'vegetable_mains', 'dinner', 4, 14, 4, 'steaming', EA, diasporaFor(EA)),
  B(' عنب الثعلب المطهو', 'Braised Gooseberries', 'Groseilles braisees', 'Grossellas braseadas', 'Schmorchelkirschen', 'fruit', 'snack', 1, 12, 0, 'simmering', EA, diasporaFor(EA)),
  B('سلطة سامفير', 'الدبرو Samphire Salad', 'Salade de salicorne', 'Ensalada de salicornia', 'Salicorn-Salat', 'vegetable_mains', 'lunch', 2, 5, 3, 'steaming', EA, diasporaFor(EA)),
  B('بودنج بقطر السكب بالقطر', 'Batter Pudding with Syrup', 'Pudding a la batre au sirop', 'Pudin de pasta con jarabe', 'Frittaten-Pudding mit Sirup', 'rice_cakes_sweets', 'snack', 4, 30, 8, 'frying', EA, diasporaFor(EA)),
  B('كستناء محمصة', 'Roast Chestnuts', 'Marechiches grillees', 'Castanas asadas', 'Gerostete Kastanien', 'fruit', 'snack', 2, 15, 1, 'roasting', EA, diasporaFor(EA)),
  B('حساء الشمر والطماطم', 'Fennel and Tomato Soup', 'Soupe au fenouil et tomates', 'Sopa de hinojo y tomate', 'Fenchel-Tomaten-Suppe', 'soups_stews', 'lunch', 2, 8, 3, 'simmering', EA, diasporaFor(EA)),
  B('شاتني الجوزبيبي المعلب', 'Bottled Gooseberry Chutney', 'Chutney de groseilles', 'Chutney de grosella', 'Stachelbeer-Chutney', 'condiments_sauces', 'snack', 1, 18, 0, 'boiling', EA, diasporaFor(EA)),
];
