import { B, diasporaFor } from './rows.mjs';

const NE = 'north_east';
const HL = 'highlands';
const LL = 'lowlands';
const WAL = 'wales';
const NI = 'ulster';

export default [
  B('يخنة على طريقة نيوكاسل', 'Newcastle Style Stew', 'Ragout style Newcastle', 'Guiso estilo Newcastle', 'Newcastle-Eintopf', 'soups_stews', 'dinner', 12, 10, 10, 'stewing', NE, diasporaFor(NE)),
  B('حساء السلمون على الطريقة الشمالية', 'Northumberland Salmon Soup', 'Soupe de saumon du Northumberland', 'Sopa de salmon de Northumberland', 'Northumberland-Lachs-Suppe', 'soups_stews', 'lunch', 10, 8, 6, 'simmering', NE, diasporaFor(NE)),
  B('سمك الهادوك المشوي', 'Grilled North Sea Haddock', 'Haddock grille de la mer du Nord', 'Bacalao a la parrilla', 'Gegrillter Nordsee-Schellfisch', 'fish_seafood', 'dinner', 19, 1, 4, 'grilling', NE, diasporaFor(NE)),
  B('ملح البحر الشمالي', 'Sea Salt Crystals', 'Sel marin', 'Sal marina', 'Nordseesalz', 'condiments_sauces', 'snack', 0, 0, 0, 'raw', NE, diasporaFor(NE)),
  B('خبز القمح الكامل', 'Wholemeal Bread', 'Pain complet', 'Pan integral', 'Vollkornbrot', 'breakfast_items', 'breakfast', 7, 26, 4, 'baking', NE, diasporaFor(NE)),
  B('حساء الكرفس', 'Celery Soup', 'Soupe de celeri', 'Sopa de apio', 'Selleriesuppe', 'soups_stews', 'lunch', 2, 8, 3, 'simmering', NE, diasporaFor(NE)),
  B('سلطة البطاطا الحارة', 'Mustard Potato Salad', 'Salade pommes de terre a la moutarde', 'Ensalada de patatas picante', 'Senf-Kartoffelsalat', 'vegetable_mains', 'lunch', 3, 16, 6, 'boiling', NE, diasporaFor(NE)),
  B('حساء البازلاء الخضراء', 'Green Split Pea Soup', 'Soupe de pois verts', 'Sopa de guisantes verdes', 'Grune-Erbsen-Suppe', 'soups_stews', 'lunch', 5, 10, 2, 'simmering', NE, diasporaFor(NE)),
  B('بسكويت الشوفان الدافئ', 'Warm Oat Biscuits', 'Biscuits a l avoine chauds', 'Galletas de avena tibias', 'Warme Haferkekse', 'rice_cakes_sweets', 'snack', 3, 24, 9, 'baking', NE, diasporaFor(NE)),
  B('حساء الجزر', 'Carrot Soup', 'Soupe de carottes', 'Sopa de zanahoria', 'Karottensuppe', 'soups_stews', 'lunch', 2, 10, 3, 'simmering', NE, diasporaFor(NE)),
  B('سلطة اللفت', 'Turnip Salad', 'Salade de navets', 'Ensalada de nabo', 'Ruben-Salat', 'vegetable_mains', 'lunch', 2, 8, 3, 'raw', NE, diasporaFor(NE)),
  B('معجون السفرجل', 'Quince Puree', 'Puree de coings', 'Pure de membrillo', 'Quittenmus', 'fruit', 'snack', 0, 14, 0, 'simmering', NE, diasporaFor(NE)),
  B('خبز الشوفان الكامل', 'Malted Oat Bread', 'Pain d avoine malte', 'Pan de avena malteada', 'Malz-Haferbrot', 'breakfast_items', 'breakfast', 6, 24, 5, 'baking', NE, diasporaFor(NE)),
  B('بيض مسلوق مع البطاطا', 'Boiled Eggs with Potatoes', 'Oeufs durs et pommes de terre', 'Huevos cocidos con patatas', 'Gekochte Eier mit Kartoffeln', 'breakfast_items', 'dinner', 8, 16, 8, 'boiling', NE, diasporaFor(NE)),
  B('فطيرة لحم الضأن الجبلية', 'Highland Lamb Pie', 'Tourte agneau des Highlands', 'Pastel cordero Highlands', 'Highland-Lamm-Pastete', 'meat_mains', 'dinner', 12, 18, 11, 'baking', HL, diasporaFor(HL)),
  B('سمك السلمون الجبلي المشوي', 'Grilled Highland Salmon', 'Saumon grille des Highlands', 'Salmon a la parrilla Highlands', 'Gegrillter Highland-Lachs', 'fish_seafood', 'dinner', 20, 0, 12, 'grilling', HL, diasporaFor(HL)),
  B('حساء الجزر الجبلي', 'Highland Carrot Stew', 'Ragout carottes Highlands', 'Guiso zanahoria Highlands', 'Highland-Möhren-Eintopf', 'soups_stews', 'dinner', 3, 14, 4, 'stewing', HL, diasporaFor(HL)),
  B('شاي الجبال بالزبدة', 'Highland Butter Tea', 'The au beurre des Highlands', 'Te con mantequilla Highlands', 'Highland-Buttertee', 'beverages', 'snack', 2, 6, 6, 'brewing', HL, diasporaFor(HL)),
  B('خبز الشوفان الجبلي', 'Highland Oat Bread', 'Pain avoine Highlands', 'Pan avena Highlands', 'Highland-Haferbrot', 'breakfast_items', 'breakfast', 6, 24, 5, 'baking', HL, diasporaFor(HL)),
  B('سلطة البطاطا الجبلية', 'Highland Potato Salad', 'Salade pommes de terre Highlands', 'Ensalada patatas Highlands', 'Highland-Kartoffelsalat', 'vegetable_mains', 'lunch', 3, 16, 6, 'boiling', HL, diasporaFor(HL)),
  B('مربى التوت الجبلي', 'Highland Raspberry Jam', 'Confiture framboises Highlands', 'Mermelada frambuesa Highlands', 'Highland-Himbeergelee', 'condiments_sauces', 'snack', 0, 20, 0, 'boiling', HL, diasporaFor(HL)),
  B('حساء الملفوف الجبلي', 'Highland Cabbage Soup', 'Soupe choux Highlands', 'Sopa col Highlands', 'Highland-Kohlsuppe', 'soups_stews', 'lunch', 2, 8, 2, 'simmering', HL, diasporaFor(HL)),
  B('خضار مطهوة جبلية', 'Highland Root Stew', 'Ragout racines Highlands', 'Guiso raices Highlands', 'Highland-Wurzel-Eintopf', 'vegetable_mains', 'dinner', 3, 14, 4, 'stewing', HL, diasporaFor(HL)),
  B('بطاطا مسلوقة جبلية', 'Highland Boiled Potatoes', 'Pommes terre bouillies Highlands', 'Patatas cocidas Highlands', 'Highland-Gekochte Kartoffeln', 'vegetable_mains', 'dinner', 2, 18, 2, 'boiling', HL, diasporaFor(HL)),
  B('شوفان جبلي بالفواكه', 'Highland Berry Porridge', 'Porridge baies Highlands', 'Avena frutos Highlands', 'Highland-Beeren-Haferbrei', 'breakfast_items', 'breakfast', 4, 18, 2, 'boiling', HL, diasporaFor(HL)),
  B('مرق الاسكتلندي', 'Scottish Broth', 'Bouillon ecossais', 'Caldo escoces', 'Schottische Bouillon', 'soups_stews', 'lunch', 9, 10, 4, 'simmering', LL, diasporaFor(LL)),
  B('لفت مع بطاطا مهروسة', 'Neeps and Mash', 'Navets et puree', 'Nabos y pure', 'Ruben mit Kartoffelpuree', 'vegetable_mains', 'dinner', 3, 18, 5, 'boiling', LL, diasporaFor(LL)),
  B('مرق الشوفان الاسكتلندي', 'Scottish Oatmeal Soup', 'Soupe avoine ecossaise', 'Sopa avena escocesa', 'Schottische Hafersuppe', 'soups_stews', 'lunch', 4, 10, 3, 'simmering', LL, diasporaFor(LL)),
  B('مربى التوت الاسكتلندي', 'Scottish Raspberry Jam', 'Confiture framboises ecossaise', 'Mermelada frambuesa escocesa', 'Schottische Himbeergelee', 'condiments_sauces', 'snack', 0, 20, 0, 'boiling', LL, diasporaFor(LL)),
  B('خبز بذور الجاودار الاسكتلندي', 'Scottish Rye Bread', 'Pain seigle ecossais', 'Pan centeno escoces', 'Schottisches Roggenbrot', 'breakfast_items', 'breakfast', 6, 26, 3, 'baking', LL, diasporaFor(LL)),
  B('شرائح التفاح المحمصة الاسكتلندية', 'Scottish Apple Crumble', 'Crumble pommes ecossais', 'Crumble manzana escocesa', 'Schottischer Apfelstreusel', 'rice_cakes_sweets', 'snack', 1, 26, 6, 'baking', LL, diasporaFor(LL)),
  B('حساء الفاصولي الاسكتلندي', 'Scottish Bean Soup', 'Soupe haricots ecossaise', 'Sopa judias escocesa', 'Schottische Bohnensuppe', 'soups_stews', 'lunch', 6, 12, 2, 'simmering', LL, diasporaFor(LL)),
  B('سلطة اللفت الاسكتلندية', 'Scottish Turnip Salad', 'Salade navets ecossaise', 'Ensalada nabo escocesa', 'Schottischer Ruben-Salat', 'vegetable_mains', 'lunch', 2, 8, 3, 'raw', LL, diasporaFor(LL)),
  B('صلصة العسل الاسكتلندية', 'Scottish Honey Sauce', 'Sauce au miel', 'Salsa de miel', 'Honig-Sauce', 'condiments_sauces', 'snack', 0, 14, 3, 'simmering', LL, diasporaFor(LL)),
  B('فطيرة الشوفان الاسكتلندية', 'Scottish Oat Flapjack', 'Flapjack avoine ecossais', 'Flapjack avena escocesa', 'Schottischer Haferfladen', 'rice_cakes_sweets', 'snack', 3, 26, 9, 'baking', LL, diasporaFor(LL)),
  B('فطيرة الشوفان الويلزية', 'Welsh Oat Flapjack', 'Flapjack avoine gallois', 'Flapjack avena gales', 'Walisischer Haferfladen', 'rice_cakes_sweets', 'snack', 3, 26, 9, 'baking', WAL, diasporaFor(WAL)),
  B('شرائح التفاح المحمصة الويلزية', 'Welsh Apple Crumble', 'Crumble pommes gallois', 'Crumble manzana gales', 'Walisischer Apfelstreusel', 'rice_cakes_sweets', 'snack', 1, 26, 6, 'baking', WAL, diasporaFor(WAL)),
  B('شورتمبريد الويلزي', 'Welsh Shortbread', 'Shortbread gallois', 'Shortbread gales', 'Walisischer Shortbread', 'rice_cakes_sweets', 'snack', 2, 22, 13, 'baking', WAL, diasporaFor(WAL)),
  B('مربى التفاح الويلزي', 'Welsh Apple Jam', 'Confiture pommes galloise', 'Mermelada manzana galesa', 'Walisische Apfelgelee', 'condiments_sauces', 'snack', 0, 20, 0, 'boiling', WAL, diasporaFor(WAL)),
  B('صلصة البقدونس الويلزية', 'Welsh Parsley Sauce', 'Sauce persil galloise', 'Salsa perejil galesa', 'Walisische Petersiliensauce', 'condiments_sauces', 'snack', 1, 4, 14, 'mixing', WAL, diasporaFor(WAL)),
  B('خبز بذور الجاودار الويلزي', 'Welsh Rye Bread', 'Pain seigle gallois', 'Pan centeno gales', 'Walisisches Roggenbrot', 'breakfast_items', 'breakfast', 6, 26, 3, 'baking', WAL, diasporaFor(WAL)),
  B('فطيرة البطاطا الشمالية', 'Northern Irish Potato Pie', 'Tourte pommes de terre nord-irlandaise', 'Pastel patatas norirlandesa', 'Nordirlandische Kartoffelpastete', 'vegetable_mains', 'dinner', 5, 22, 8, 'baking', NI, diasporaFor(NI)),
  B('حساء البصل الأيرلندي', 'Irish Onion Soup', 'Soupe oignons irlandaise', 'Sopa cebolla irlandesa', 'Irische Zwiebelsuppe', 'soups_stews', 'lunch', 2, 9, 5, 'simmering', NI, diasporaFor(NI)),
  B('مربى التفاح الأيرلندي', 'Irish Apple Jam', 'Confiture pommes irlandaise', 'Mermelada manzana irlandesa', 'Irische Apfelgelee', 'condiments_sauces', 'snack', 0, 20, 0, 'boiling', NI, diasporaFor(NI)),
  B('شاي باللبن الأيرلندي', 'Irish Cream Tea', 'Cream tea irlandais', 'Merienda crema irlandesa', 'Irischer Cream Tea', 'rice_cakes_sweets', 'snack', 4, 24, 10, 'assembling', NI, diasporaFor(NI)),
  B('خبز الشوفان الأيرلندي', 'Irish Oat Bread', 'Pain avoine irlandais', 'Pan avena irlandes', 'Irisches Haferbrot', 'breakfast_items', 'breakfast', 6, 24, 5, 'baking', NI, diasporaFor(NI)),
  B('كعك الزبدة الأيرلندي', 'Irish Butter Scones', 'Scones beurre irlandais', 'Scones mantequilla irlandeses', 'Irische Butter-Scones', 'rice_cakes_sweets', 'snack', 4, 24, 10, 'griddled', NI, diasporaFor(NI)),
  B('فطيرة الشوفان الويلزية الثانية', 'Welsh Oat Shortbread', 'Shortbread avoine gallois', 'Shortbread de avena gales', 'Walisischer Hafer-Shortbread', 'rice_cakes_sweets', 'snack', 3, 24, 12, 'baking', WAL, diasporaFor(WAL)),
  B('حساء الفاصولي الويلزي', 'Welsh Bean Broth', 'Bouillon de haricots gallois', 'Caldo de judias gales', 'Walisische Bohnenbrühe', 'soups_stews', 'lunch', 6, 12, 2, 'simmering', WAL, diasporaFor(WAL)),
  B('مربى الكشمش الويلزي', 'Welsh Redcurrant Jam', 'Confiture de groseilles galloise', 'Mermelada de grosella galesa', 'Walisische Johannisbeergelee', 'condiments_sauces', 'snack', 0, 20, 0, 'boiling', WAL, diasporaFor(WAL)),
];
