import { B, diasporaFor } from './rows.mjs';

const P = 'pan_british';
const LON = 'london';

export default [
  B('طبق الفطور البريطاني', 'English Breakfast Plate', 'Assiette du petit-dejeuner anglais', 'Plato de desayuno ingles', 'Englisches Fruhstuck', 'breakfast_items', 'breakfast', 12, 12, 14, 'frying', P, diasporaFor(P)),
  B('لحم بقر مشوي مع بطاطا', 'Roast Beef with Roast Potatoes', 'Roti de boeuf avec pommes de terre roties', 'Asado de res con patatas asadas', 'Rinderbraten mit Kartoffeln', 'meat_mains', 'dinner', 18, 20, 12, 'roasting', P, diasporaFor(P)),
  B('سمك مقلي مع بطاطا', 'Fish and Chips with Mushy Peas', 'Poisson-frites avec petits pois', 'Pescado con patatas y guisantes', 'Fisch mit Pommes und Erbsenmus', 'fish_seafood', 'dinner', 9, 22, 11, 'frying', P, diasporaFor(P)),
  B('فطيرة اللحم المفروم', 'Beef Shepherd Pie', 'Shepherd pie au boeuf', 'Pastel de carne picada', 'Shepherd Pie mit Rindfleisch', 'meat_mains', 'dinner', 11, 20, 9, 'baking', P, diasporaFor(P)),
  B('فطيرة دجاج بالكرفس', 'Chicken and Leek Pie', 'Tourte au poulet aux poireaux', 'Pastel de pollo y puerro', 'Hahnchen-Lauch-Pastete', 'poultry_mains', 'dinner', 13, 18, 11, 'baking', P, diasporaFor(P)),
  B('بيض مخبوز بالجبن والبهارات', 'Scotch Eggs', 'Oeufs ecossais', 'Huevos scotch', 'Scotch Eggs', 'breakfast_items', 'lunch', 12, 8, 12, 'frying', P, diasporaFor(P)),
  B('بطاطا مقلية بالكرنب', 'Bubble and Squeak', 'Galette de pommes de terre et chou', 'Patatas con col', 'Kartoffel-Kohl-Puffer', 'breakfast_items', 'lunch', 7, 18, 9, 'frying', P, diasporaFor(P)),
  B('فاصولي مخبوزة على الخبز', 'Baked Beans on Toast', 'Haricots cuits sur toast', 'Judias horneadas sobre tostada', 'Ofenbohnen auf Toast', 'breakfast_items', 'breakfast', 6, 22, 3, 'simmering', P, diasporaFor(P)),
  B('بطاطا مخبوزة بالفاصولي', 'Jacket Potato with Baked Beans', 'Pomme de terre en robe aux haricots', 'Patata jacket con judias', 'Jacket Kartoffel mit Bohnen', 'vegetable_mains', 'lunch', 5, 26, 3, 'baking', P, diasporaFor(P)),
  B('يخنة لحم بقري بالقرش لعش', 'Beef Stew and Dumplings', 'Ragout de boeuf aux dumplings', 'Guiso de res con dumpling', 'Rindfleisch-Eintopf mit Klosen', 'soups_stews', 'dinner', 14, 16, 8, 'stewing', P, diasporaFor(P)),
  B('طبق فلاح بالجبنة والخبز', 'Ploughman Cheese Lunch', 'Dejeuner du fermier au fromage', 'Almuerzo del labrador con queso', 'Bauernbrot mit Kase', 'vegetable_mains', 'lunch', 11, 18, 12, 'assembling', P, diasporaFor(P)),
  B('شاي اللحم مع الخبز', 'Beef Tea and Toast', 'Soupe au boeuf et toast', 'Sopa de carne con tostada', 'Rindfleischsuppe mit Toast', 'beverages', 'snack', 8, 14, 4, 'brewing', P, diasporaFor(P)),
  B('حساء الكريمة بالفطر', 'Cream of Mushroom Soup', 'Veloute de champignons', 'Crema de setas', 'Champignoncremesuppe', 'soups_stews', 'lunch', 3, 7, 4, 'simmering', P, diasporaFor(P)),
  B('حساء الطماطم بالكريمة', 'Creamy Tomato Soup', 'Veloute de tomates a la creme', 'Sopa de tomate cremosa', 'Tomatencremesuppe', 'soups_stews', 'lunch', 2, 9, 3, 'simmering', P, diasporaFor(P)),
  B('حساء الكرفس والبطاطا', 'Leek and Potato Soup', 'Soupe aux poireaux et pommes de terre', 'Sopa de puerro y patata', 'Lauch-Kartoffel-Suppe', 'soups_stews', 'lunch', 2, 10, 3, 'simmering', P, diasporaFor(P)),
  B('قرنبيط بالجبنة', 'Cauliflower Cheese', 'Gratin de chou-fleur au fromage', 'Coliflor gratinado con queso', 'Blumenkohl mit Kase', 'vegetable_mains', 'dinner', 8, 12, 13, 'baking', P, diasporaFor(P)),
  B('سلطة الكرنب بالكريمة', 'Creamy Coleslaw', 'Coleslaw a la creme', 'Ensalada de col cremosa', 'Krautsalat mit Rahm', 'vegetable_mains', 'lunch', 2, 8, 6, 'tossing', P, diasporaFor(P)),
  B('بطاطا مشوية مقرمشة', 'Crisp Roast Potatoes', 'Pommes de terre roties croustillantes', 'Patatas asadas crujientes', 'Knusprige Rostkartoffeln', 'vegetable_mains', 'dinner', 3, 22, 9, 'roasting', P, diasporaFor(P)),
  B('بطاطا مهروسة بالسمن', 'Buttered Mashed Potatoes', 'Puree de pommes de terre au beurre', 'Patatas pisadas con mantequilla', 'Kartoffelpuree mit Butter', 'vegetable_mains', 'dinner', 2, 18, 5, 'mashed', P, diasporaFor(P)),
  B('حشوة المريمية والبصل', 'Sage and Onion Stuffing', 'Farce a la sauge et aux oignons', 'Relleno de salvia y cebolla', 'Salbei-Zwiebel-Fullung', 'vegetable_mains', 'dinner', 4, 14, 8, 'roasting', P, diasporaFor(P)),
  B('كستارد انجليزي', 'English Custard', 'Creme anglaise', 'Crema inglesa', 'Englische Creme', 'rice_cakes_sweets', 'snack', 3, 14, 5, 'stewing', P, diasporaFor(P)),
  B('بودنغ الكراميل اللزج', 'Sticky Toffee Pudding', 'Pudding au caramel collant', 'Pudin de caramelo pegajoso', 'Klebriger Toffee-Pudding', 'rice_cakes_sweets', 'snack', 3, 34, 8, 'baking', P, diasporaFor(P)),
  B('تارت الدبس', 'Treacle Tart', 'Tarte au melasse', 'Tarta de melaza', 'Sirup-Tarte', 'rice_cakes_sweets', 'snack', 3, 30, 10, 'baking', P, diasporaFor(P)),
  B('كسر التفاح', 'Apple Crumble', 'Crumble aux pommes', 'Crumble de manzana', 'Apfelstreusel', 'rice_cakes_sweets', 'snack', 1, 26, 6, 'baking', P, diasporaFor(P)),
  B('رز باللبن المخبوز', 'Baked Rice Pudding', 'Riz au lait au four', 'Arroz con leche horneado', 'Gebackener Milchreis', 'rice_cakes_sweets', 'snack', 3, 18, 4, 'baking', P, diasporaFor(P)),
  B('شورتمبريد بالزبد', 'Shortbread Fingers', 'Shortbread au beurre', 'Galletas shortbread', 'Butter-Shortbread', 'rice_cakes_sweets', 'snack', 2, 22, 14, 'baking', P, diasporaFor(P)),
  B('كعك الليمون', 'Lemon Drizzle Cake', 'Gateau au citron nappe', 'Bizcocho con glaseado de limon', 'Zitronenkuchen mit Glasur', 'rice_cakes_sweets', 'snack', 3, 30, 11, 'baking', P, diasporaFor(P)),
  B('كعك اسفنجي فكتوريا', 'Victoria Sponge', 'Gateau Victoria', 'Bizcocho Victoria', 'Victoria-Sandwichkuchen', 'rice_cakes_sweets', 'snack', 3, 28, 12, 'baking', P, diasporaFor(P)),
  B('شوفان باللبن', 'Oat Porridge', 'Porridge a l avoine', 'Avena cocida', 'Haferbrei', 'breakfast_items', 'breakfast', 4, 16, 2, 'boiling', P, diasporaFor(P)),
  B('كرمبتس', 'Crumpets', 'Crumpets', 'Crumpets', 'Crumpets', 'breakfast_items', 'breakfast', 3, 22, 3, 'griddled', P, diasporaFor(P)),
  B('دجاج بالتيمارلا', 'Chicken Tikka Masala', 'Poulet tikka masala', 'Pollo tikka masala', 'Hahnchen Tikka Masala', 'poultry_mains', 'dinner', 14, 9, 13, 'simmering', LON, diasporaFor(LON)),
  B('لحم غنم روجان جوش', 'Lamb Rogan Josh', 'Agneau rogan josh', 'Cordero rogan josh', 'Lamm Rogan Josh', 'meat_mains', 'dinner', 13, 8, 15, 'simmering', LON, diasporaFor(LON)),
  B('كاري لحم الغنم البلتي', 'Balti Lamb Curry', 'Curry d agneau Balti', 'Curry de cordero Balti', 'Balti-Lammcurry', 'meat_mains', 'dinner', 13, 10, 14, 'stir_frying', LON, diasporaFor(LON)),
  B('لحم غنم مطحون مع نان', 'Lamb Keema with Naan', 'Keema d agneau avec naan', 'Keema de cordero con naan', 'Lamm-Keema mit Naan', 'meat_mains', 'lunch', 12, 18, 11, 'stir_frying', LON, diasporaFor(LON)),
  B('لفافة سجق البقر المتبل', 'Spiced Beef Sausage Roll', 'Empaste de saucisse de boeuf epicee', 'Empanada de salchicha de res', 'Gewurz-Rindwurstpastete', 'street_snacks', 'lunch', 9, 20, 11, 'baking', LON, diasporaFor(LON)),
  B('فطيرة دجاج بالزيتير', 'Chicken and Thyme Pie', 'Tourte au poulet au thym', 'Pastel de pollo y tomillo', 'Hahnchen-Thymian-Pastete', 'poultry_mains', 'dinner', 14, 16, 12, 'baking', LON, diasporaFor(LON)),
  B('شريحة جبن مشوية', 'Cheese Toastie', 'Croque-fromage', 'Tostada de queso', 'Kasetoast', 'street_snacks', 'lunch', 8, 20, 12, 'grilling', LON, diasporaFor(LON)),
  B('سمبوسك بالخضار', 'Vegetable Samosas', 'Samoussas aux legumes', 'Empanadillas de verduras', 'Gemuse-Samosa', 'street_snacks', 'snack', 3, 18, 7, 'frying', LON, diasporaFor(LON)),
  B('باجي بصل مقرمش', 'Crispy Onion Bhajis', 'Bhajis aux oignons croustillants', 'Bhajis crujientes de cebolla', 'Knusprige Zwiebel-Bhajis', 'street_snacks', 'snack', 3, 16, 9, 'frying', LON, diasporaFor(LON)),
  B('حمص بالطماطم والبهارات', 'Chana Masala', 'Chana masala', 'Chana masala', 'Chana Masala', 'vegetable_mains', 'dinner', 6, 14, 5, 'simmering', LON, diasporaFor(LON)),
  B('سبانخ بالجبن', 'Palak Paneer', 'Palak paneer', 'Palak paneer', 'Palak Paneer', 'vegetable_mains', 'dinner', 8, 7, 11, 'simmering', LON, diasporaFor(LON)),
  B('اجنحة دجاج بالزبادي', 'Yogurt Chicken Wings', 'Ailes de poulet marinees au yaourt', 'Alitas de pollo marinadas en yogur', 'Joghurt-Huhnerflugel', 'poultry_mains', 'dinner', 15, 6, 12, 'roasting', LON, diasporaFor(LON)),
  B('برجر لحم بقر بالسلطة', 'Beef Lettuce Burgers', 'Hamburgers de boeuf salade', 'Hamburguesas de res con lechuga', 'Rindfleisch-Burger mit Salat', 'meat_mains', 'dinner', 13, 8, 12, 'grilling', LON, diasporaFor(LON)),
  B('بطاطا مخبوزة بالجبن', 'Loaded Jacket Potato with Cheese', 'Pomme de terre en robe au fromage', 'Patata jacket con queso', 'Uberbackene Jacket Kartoffel', 'vegetable_mains', 'lunch', 6, 24, 8, 'baking', LON, diasporaFor(LON)),
  B('فطيرة سمك بالكريمة', 'Fish Pie with Egg Custard', 'Tourte au poisson a la creme', 'Pastel de pescado con crema', 'Fischpastete mit Eiercreme', 'fish_seafood', 'dinner', 11, 20, 11, 'baking', LON, diasporaFor(LON)),
  B('سلطة الروبيان بالليمون', 'Prawn Salad with Lemon', 'Salade de crevettes au citron', 'Ensalada de gambas al limon', 'Krabbensalat mit Zitrone', 'fish_seafood', 'snack', 10, 8, 6, 'assembling', LON, diasporaFor(LON)),
  B('بيض مخلوط على الخبز', 'Scrambled Eggs on Toast', 'Oeufs brouilles sur toast', 'Huevos revueltos sobre tostada', 'Ruhrei auf Toast', 'breakfast_items', 'breakfast', 6, 12, 8, 'scrambling', LON, diasporaFor(LON)),
  B('خبز بالثوم والجبن', 'Garlic and Cheese Bread', 'Pain a l ail gratine au fromage', 'Pan de ajo con queso', 'Knoblauchbrot mit Kase', 'street_snacks', 'snack', 6, 22, 8, 'baking', LON, diasporaFor(LON)),
  B('رز بالدجاج واللوز', 'Rice with Chicken and Almonds', 'Riz au poulet et aux amandes', 'Arroz con pollo y almendras', 'Reis mit Huhn und Mandeln', 'rice_dishes', 'dinner', 9, 20, 8, 'simmering', LON, diasporaFor(LON)),
  B('بودنج الخبز بالزبدة', 'Bread and Butter Pudding', 'Pudding au pain et au beurre', 'Pudin de pan con mantequilla', 'Brot-und-Butter-Pudding', 'rice_cakes_sweets', 'snack', 4, 22, 8, 'baking', LON, diasporaFor(LON)),
];
