import { B } from './rows.mjs';

export default [
  B('pe-phase-a-151', 'بيكا بيكانتي أياكوتشو بالبطاطس والشمندر', 'Ayacucho Puca Picante with Potato and Beet', 'Puca picante d’Ayacucho à la pomme de terre et betterave', 'Puca picante ayacuchano con papa y betarraga', 'Ayacucho-Puca-Picante mit Kartoffel und Roter Bete', 'meat_mains', 'dinner', 17, 13, 9, 'stewing', 'cusco'),
  B('pe-phase-a-152', 'شوربة تشوكلو بالتاروي وجبن طازج', 'Choclo Soup with Tarwi and Fresh Cheese', 'Soupe de choclo au tarwi et fromage frais', 'Sopa de choclo con tarwi y queso fresco', 'Choclo-Suppe mit Tarwi und Frischkäse', 'soups_stews', 'lunch', 13, 18, 6, 'simmering', 'cajamarca'),
  B('pe-phase-a-153', 'تشوبي شوروس بالذرة والجبن', 'Choros Chupe with Corn and Cheese', 'Chupe de choros au maïs et fromage', 'Chupe de choros con maíz y queso', 'Choros-Chupe mit Mais und Käse', 'fish_seafood', 'lunch', 17, 13, 6, 'simmering', 'callao'),
  B('pe-phase-a-154', 'روكوتو ريلينو بالروبيان والكينوا', 'Rocoto Relleno with Shrimp and Quinoa', 'Rocoto relleno aux crevettes et quinoa', 'Rocoto relleno con camarones y quinoa', 'Rocoto Relleno mit Garnelen und Quinoa', 'fish_seafood', 'dinner', 18, 11, 8, 'baking', 'arequipa'),
  B('pe-phase-a-155', 'تروتا بونو بقشرة كانيوا المقرمشة', 'Puno Trout with Crispy Cañihua Crust', 'Truite de Puno en croûte croustillante de cañihua', 'Trucha de Puno con costra crujiente de cañihua', 'Puno-Forelle mit knuspriger Cañihua-Kruste', 'fish_seafood', 'dinner', 22, 10, 8, 'baking', 'puno'),
  B('pe-phase-a-156', 'تامال كينوا بالدجاج والزيتون', 'Quinoa Tamal with Chicken and Olives', 'Tamal de quinoa au poulet et olives', 'Tamal de quinoa con pollo y aceitunas', 'Quinoa-Tamal mit Hähnchen und Oliven', 'street_snacks', 'lunch', 15, 22, 8, 'steaming', 'cusco'),
  B('pe-phase-a-157', 'أولوكيتو ألباكا بالبطاطس والبقدونس', 'Alpaca Olluquito with Potato and Parsley', 'Olluquito d’alpaga à la pomme de terre et persil', 'Olluquito de alpaca con papa y perejil', 'Alpaka-Olluquito mit Kartoffel und Petersilie', 'meat_mains', 'dinner', 21, 11, 7, 'stewing', 'cusco'),
  B('pe-phase-a-158', 'كاسويلا باياريس بالديك الرومي والقرع', 'Pallares Cazuela with Turkey and Squash', 'Cazuela de pallares à la dinde et courge', 'Cazuela de pallares con pavo y zapallo', 'Pallares-Cazuela mit Pute und Kürbis', 'poultry_mains', 'dinner', 18, 15, 7, 'simmering', 'lima'),
  B('pe-phase-a-159', 'تاكو تاروي بصلصة هواكاتاي', 'Tarwi Tacu with Huacatay Sauce', 'Tacu de tarwi à la sauce huacatay', 'Tacu de tarwi con salsa de huacatay', 'Tarwi-Tacu mit Huacatay-Soße', 'vegetable_mains', 'lunch', 15, 18, 7, 'pan_frying', 'puno'),
  B('pe-phase-a-160', 'روبيان أجي أماريو مع الأرز والذرة', 'Shrimp Aji Amarillo with Rice and Corn', 'Crevettes à l’aji amarillo avec riz et maïs', 'Camarones al ají amarillo con arroz y maíz', 'Garnelen mit Aji Amarillo, Reis und Mais', 'fish_seafood', 'dinner', 19, 20, 7, 'sauteing', 'callao'),
  B('pe-phase-a-161', 'كروكيت أراجّاتشا وكينوا بجبن طازج', 'Arracacha and Quinoa Croquettes with Fresh Cheese', 'Croquettes d’arracacha et quinoa au fromage frais', 'Croquetas de arracacha y quinoa con queso fresco', 'Arracacha-Quinoa-Kroketten mit Frischkäse', 'vegetable_mains', 'lunch', 12, 20, 7, 'baking', 'huancayo'),
  B('pe-phase-a-162', 'لحم بقري بالأناناس والفلفل الأصفر', 'Beef with Pineapple and Aji Amarillo', 'Bœuf à l’ananas et aji amarillo', 'Res con piña y ají amarillo', 'Rindfleisch mit Ananas und Aji Amarillo', 'meat_mains', 'dinner', 20, 9, 8, 'braising', 'piura'),
  B('pe-phase-a-163', 'لحم بقري بصلصة الكينوا والبقدونس', 'Beef with Quinoa and Parsley Sauce', 'Bœuf à la sauce quinoa et persil', 'Res con salsa de quinoa y perejil', 'Rindfleisch mit Quinoa-Petersilien-Soße', 'meat_mains', 'dinner', 21, 8, 9, 'braising', 'cajamarca'),
];
