import { B } from './rows.mjs';

export default [
  B('pe-phase-a-076', 'مرق رأس البقر بالموتي والبصل الأخضر', 'Beef Head Broth with Mote and Scallion', 'Bouillon de tête de bœuf au mote et oignon vert', 'Caldo de cabeza de res con mote y cebolla china', 'Rinderkopfsuppe mit Mote und Frühlingszwiebel', 'soups_stews', 'lunch', 18, 12, 6, 'simmering', 'ancash'),
  B('pe-phase-a-077', 'روبيان بالثوم والليمون مع البطاطس', 'Garlic Shrimp with Lime and Potato', 'Crevettes à l’ail, citron vert et pomme de terre', 'Camarones al ajo con lima y papa', 'Knoblauchgarnelen mit Limette und Kartoffel', 'fish_seafood', 'dinner', 20, 13, 7, 'sauteing', 'piura'),
  B('pe-phase-a-078', 'تالارينيس كينوا بالفلفل الأصفر والجبن الطازج', 'Quinoa Tallarines with Aji Amarillo and Fresh Cheese', 'Tallarines de quinoa à l’aji amarillo et fromage frais', 'Tallarines de quinoa con ají amarillo y queso fresco', 'Quinoa-Tallarines mit Aji Amarillo und Frischkäse', 'vegetable_mains', 'dinner', 14, 23, 8, 'boiling', 'arequipa'),
  B('pe-phase-a-079', 'ألباكا سالتادو بالفاصولياء الخضراء والبطاطس', 'Alpaca Saltado with Green Beans and Potato', 'Alpaca saltado aux haricots verts et pomme de terre', 'Alpaca saltada con habichuelas verdes y papa', 'Alpaca Saltado mit grünen Bohnen und Kartoffel', 'meat_mains', 'dinner', 23, 11, 8, 'sauteing', 'cusco'),
  B('pe-phase-a-080', 'سمك مخبوز بهواكاتاي وكينوا', 'Baked Fish with Huacatay and Quinoa', 'Poisson au four au huacatay et quinoa', 'Pescado al horno con huacatay y quinoa', 'Ofenfisch mit Huacatay und Quinoa', 'fish_seafood', 'dinner', 20, 12, 7, 'baking', 'lima'),
  B('pe-phase-a-081', 'شوربة موتي بالدجاج والسبانخ والذرة', 'Mote Soup with Chicken, Spinach and Corn', 'Soupe de mote au poulet, épinards et maïs', 'Sopa de mote con pollo, espinaca y maíz', 'Mote-Suppe mit Hähnchen, Spinat und Mais', 'soups_stews', 'lunch', 15, 16, 5, 'simmering', 'cajamarca'),
  B('pe-phase-a-082', 'فاصولياء باياريس مطهوة بلحم البقر والهواكاتاي', 'Pallares Stewed with Beef and Huacatay', 'Pallares mijotés au bœuf et huacatay', 'Pallares guisados con res y huacatay', 'Pallares mit Rindfleisch und Huacatay geschmort', 'meat_mains', 'dinner', 18, 16, 8, 'stewing', 'lima'),
  B('pe-phase-a-083', 'بطاطس بصلصة هواكاتاي مع بيض مسلوق', 'Potatoes with Huacatay Sauce and Boiled Egg', 'Pommes de terre à la sauce huacatay et œuf dur', 'Papas con salsa de huacatay y huevo sancochado', 'Kartoffeln mit Huacatay-Soße und gekochtem Ei', 'vegetable_mains', 'lunch', 12, 18, 8, 'boiling', 'cusco'),
  B('pe-phase-a-084', 'تروتا محشوة بالتاروي والسبانخ', 'Trout Stuffed with Tarwi and Spinach', 'Truite farcie au tarwi et épinards', 'Trucha rellena de tarwi y espinaca', 'Forelle gefüllt mit Tarwi und Spinat', 'fish_seafood', 'dinner', 22, 7, 8, 'baking', 'puno'),
  B('pe-phase-a-085', 'يخنة الدجاج بالذرة والقرع والكزبرة', 'Chicken Stew with Corn, Squash and Cilantro', 'Ragoût de poulet au maïs, courge et coriandre', 'Guiso de pollo con maíz, zapallo y cilantro', 'Hähncheneintopf mit Mais, Kürbis und Koriander', 'poultry_mains', 'dinner', 18, 13, 6, 'stewing', 'amazonas'),
  B('pe-phase-a-086', 'بولينتا بيروفية بالريكوتا وصلصة أجي', 'Peruvian Polenta with Ricotta and Aji Sauce', 'Polenta péruvienne à la ricotta et sauce aji', 'Polenta peruana con ricota y salsa de ají', 'Peruanische Polenta mit Ricotta und Aji-Soße', 'vegetable_mains', 'lunch', 12, 24, 8, 'simmering', 'lima'),
  B('pe-phase-a-087', 'أرز كينوا بالتونة والبازلاء والفلفل', 'Quinoa Rice with Tuna, Peas and Pepper', 'Riz de quinoa au thon, petits pois et poivron', 'Arroz de quinoa con atún, arvejas y pimiento', 'Quinoareis mit Thunfisch, Erbsen und Paprika', 'fish_seafood', 'lunch', 18, 17, 6, 'simmering', 'piura'),
];
