import { B } from './rows.mjs';

export default [
  B('pe-phase-a-051', 'أولوكيتو بلحم البقر والذرة', 'Olluquito with Beef and Corn', 'Olluquito au bœuf et maïs', 'Olluquito con res y maíz', 'Olluquito mit Rindfleisch und Mais', 'meat_mains', 'dinner', 18, 12, 8, 'stewing', 'cusco'),
  B('pe-phase-a-052', 'سودادو سمك باليوكا والفلفل الأصفر', 'Fish Sudado with Cassava and Aji Amarillo', 'Sudado de poisson au manioc et aji amarillo', 'Sudado de pescado con yuca y ají amarillo', 'Fisch-Sudado mit Maniok und Aji Amarillo', 'fish_seafood', 'lunch', 19, 13, 6, 'braising', 'piura'),
  B('pe-phase-a-053', 'سيفيتشي نيكي بالسمك والسمسم والليمون', 'Nikkei Fish Ceviche with Sesame and Lime', 'Ceviche de poisson nikkei au sésame et citron vert', 'Ceviche nikkei de pescado con sésamo y lima', 'Nikkei-Fisch-Ceviche mit Sesam und Limette', 'fish_seafood', 'lunch', 20, 6, 5, 'marinating', 'lima'),
  B('pe-phase-a-054', 'باستيل دي تشوكلو بلحم البقر والجبن', 'Pastel de Choclo with Beef and Cheese', 'Pastel de choclo au bœuf et fromage', 'Pastel de choclo con res y queso', 'Pastel de Choclo mit Rindfleisch und Käse', 'meat_mains', 'dinner', 17, 19, 9, 'baking', 'cajamarca'),
  B('pe-phase-a-055', 'تالارينيس فيرديس بلحم البقر والسبانخ', 'Tallarines Verdes with Beef and Spinach', 'Tallarines verdes au bœuf et épinards', 'Tallarines verdes con res y espinaca', 'Tallarines Verdes mit Rindfleisch und Spinat', 'meat_mains', 'dinner', 20, 22, 9, 'boiling', 'lima'),
  B('pe-phase-a-056', 'شوربة قمح كاخاماركا بلحم البقر والخضار', 'Cajamarca Wheat Soup with Beef and Vegetables', 'Soupe de blé de Cajamarca au bœuf et légumes', 'Sopa de trigo cajamarquina con res y verduras', 'Cajamarca-Weizensuppe mit Rindfleisch und Gemüse', 'soups_stews', 'lunch', 16, 15, 6, 'simmering', 'cajamarca'),
  B('pe-phase-a-057', 'كوسا أخي دي بولبو بالبطاطس والأفوكادو', 'Pulpo Aji Causa with Potato and Avocado', 'Causa à l’aji de poulpe, pomme de terre et avocat', 'Causa de pulpo al ají con papa y aguacate', 'Pulpo-Aji-Causa mit Kartoffel und Avocado', 'fish_seafood', 'lunch', 18, 13, 7, 'assembling', 'lima'),
  B('pe-phase-a-058', 'شوربة فول عريض وكينوا بجبن طازج', 'Fava Bean and Quinoa Soup with Fresh Cheese', 'Soupe de fèves et quinoa au fromage frais', 'Sopa de habas y quinoa con queso fresco', 'Ackerbohnen-Quinoa-Suppe mit Frischkäse', 'soups_stews', 'lunch', 12, 17, 5, 'simmering', 'cusco'),
  B('pe-phase-a-059', 'سيكو لحم الضأن بالكزبرة والفاصولياء', 'Lamb Seco with Cilantro and Beans', 'Seco d’agneau à la coriandre et haricots', 'Seco de cordero con cilantro y frijoles', 'Lamm-Seco mit Koriander und Bohnen', 'meat_mains', 'dinner', 20, 10, 9, 'braising', 'cajamarca'),
  B('pe-phase-a-060', 'حليب نمر سيفيتشي بالليمون والفلفل', 'Leche de Tigre with Lime and Chile', 'Leche de tigre au citron vert et piment', 'Leche de tigre con lima y ají', 'Leche de Tigre mit Limette und Chili', 'beverages', 'snack', 10, 4, 2, 'marinating', 'lima'),
  B('pe-phase-a-061', 'تورتيّا كينوا بالفلفل الأصفر وجبن طازج', 'Quinoa Tortilla with Aji Amarillo and Fresh Cheese', 'Tortilla de quinoa à l’aji amarillo et fromage frais', 'Tortilla de quinoa con ají amarillo y queso fresco', 'Quinoa-Tortilla mit Aji Amarillo und Frischkäse', 'breakfast_items', 'breakfast', 14, 17, 8, 'pan_frying', 'puno'),
  B('pe-phase-a-062', 'تروتا بونو المشوية بالأعشاب والتاروي', 'Puno Trout with Herbs and Tarwi', 'Truite de Puno aux herbes et tarwi', 'Trucha de Puno con hierbas y tarwi', 'Puno-Forelle mit Kräutern und Tarwi', 'fish_seafood', 'dinner', 23, 7, 8, 'grilling', 'puno'),
  B('pe-phase-a-063', 'كيسو إلادو أريكويبي بالقرفة وجوز الهند', 'Arequipa Queso Helado with Cinnamon and Coconut', 'Queso helado d’Arequipa à la cannelle et noix de coco', 'Queso helado arequipeño con canela y coco', 'Arequipa-Queso-Helado mit Zimt und Kokos', 'rice_cakes_sweets', 'snack', 7, 25, 8, 'chilling', 'arequipa'),
];
