import { B } from './rows.mjs';

export default [
  B('pe-phase-a-001', 'سيفيتشي كورفينا بالليمون والذرة والبطاطا الحلوة', 'Corvina Ceviche with Lime, Corn and Sweet Potato', 'Ceviche de corvina au citron vert, maïs et patate douce', 'Ceviche de corvina con lima, maíz y camote', 'Corvina-Ceviche mit Limette, Mais und Süßkartoffel', 'fish_seafood', 'lunch', 20, 10, 3, 'marinating', 'lima'),
  B('pe-phase-a-002', 'لومو سالتادو بلحم البقر والطماطم والبصل', 'Lomo Saltado with Beef, Tomato and Onion', 'Lomo saltado au bœuf, tomate et oignon', 'Lomo saltado de res con tomate y cebolla', 'Lomo Saltado mit Rind, Tomate und Zwiebel', 'meat_mains', 'dinner', 22, 10, 9, 'sauteing', 'lima'),
  B('pe-phase-a-003', 'أخي دي غايينا بالدجاج والفلفل الأصفر', 'Aji de Gallina with Chicken and Aji Amarillo', 'Aji de gallina au poulet et aji amarillo', 'Ají de gallina con pollo y ají amarillo', 'Aji de Gallina mit Hähnchen und Aji Amarillo', 'poultry_mains', 'dinner', 20, 9, 10, 'simmering', 'lima'),
  B('pe-phase-a-004', 'بابا آ لا هوانكاينا بالبيض والجبن', 'Papa a la Huancaina with Egg and Cheese', 'Papa à la huancaína, œuf et fromage', 'Papa a la huancaína con huevo y queso', 'Papa a la Huancaina mit Ei und Käse', 'vegetable_mains', 'lunch', 11, 17, 9, 'boiling', 'huancayo'),
  B('pe-phase-a-005', 'أنتيكوتشو قلب البقر بصلصة الفلفل والبطاطس', 'Beef Heart Anticuchos with Chile Sauce and Potato', 'Anticuchos de cœur de bœuf, sauce au piment et pomme de terre', 'Anticuchos de corazón de res con salsa de ají y papa', 'Rinderherz-Anticuchos mit Chilisauce und Kartoffel', 'meat_mains', 'dinner', 23, 7, 8, 'grilling', 'lima'),
  B('pe-phase-a-006', 'كوسا ليمنيا بالدجاج والأفوكادو', 'Causa Limeña with Chicken and Avocado', 'Causa limeña au poulet et avocat', 'Causa limeña de pollo y aguacate', 'Causa Limeña mit Hähnchen und Avocado', 'poultry_mains', 'lunch', 17, 15, 8, 'assembling', 'lima'),
  B('pe-phase-a-007', 'شوربة كريولا بلحم البقر والنودلز والبيض', 'Sopa Criolla with Beef, Noodles and Egg', 'Soupe criolla au bœuf, nouilles et œuf', 'Sopa criolla con res, fideos y huevo', 'Sopa Criolla mit Rind, Nudeln und Ei', 'soups_stews', 'lunch', 16, 12, 7, 'simmering', 'lima'),
  B('pe-phase-a-008', 'روكوتو ريلينو بلحم البقر والجبن', 'Rocoto Relleno with Beef and Cheese', 'Rocoto relleno au bœuf et fromage', 'Rocoto relleno de res y queso', 'Rocoto Relleno mit Rindfleisch und Käse', 'meat_mains', 'dinner', 17, 9, 10, 'baking', 'arequipa'),
  B('pe-phase-a-009', 'تاكو تاكو الفاصولياء والأرز بالبيض', 'Tacu Tacu with Beans, Rice and Egg', 'Tacu tacu aux haricots, riz et œuf', 'Tacu tacu de frijoles, arroz y huevo', 'Tacu Tacu mit Bohnen, Reis und Ei', 'breakfast_items', 'breakfast', 13, 22, 8, 'pan_frying', 'lima'),
  B('pe-phase-a-010', 'دجاج مشوي على الطريقة البيروفية بالأعشاب', 'Peruvian Herb-Roasted Chicken', 'Poulet rôti péruvien aux herbes', 'Pollo a la brasa peruano con hierbas', 'Peruanisches Kräuter-Brathähnchen', 'poultry_mains', 'dinner', 23, 4, 8, 'roasting', 'lima'),
  B('pe-phase-a-011', 'باتشامانكا لحم بقري ودجاج بالبطاطس والفول', 'Pachamanca Beef and Chicken with Potatoes and Fava Beans', 'Pachamanca de bœuf et poulet aux pommes de terre et fèves', 'Pachamanca de res y pollo con papa y habas', 'Pachamanca mit Rind, Hähnchen, Kartoffeln und Ackerbohnen', 'meat_mains', 'dinner', 20, 12, 8, 'roasting', 'cusco'),
  B('pe-phase-a-012', 'كارابولكرا بلحم البقر والبطاطس المجففة', 'Carapulcra with Beef and Dried Potato', 'Carapulcra au bœuf et pommes de terre séchées', 'Carapulcra de res con papa seca', 'Carapulcra mit Rindfleisch und getrockneten Kartoffeln', 'meat_mains', 'dinner', 18, 14, 9, 'stewing', 'ica'),
  B('pe-phase-a-013', 'تشوبي كينوا بالدجاج والجبن', 'Quinoa Chupe with Chicken and Cheese', 'Chupe de quinoa au poulet et fromage', 'Chupe de quinoa con pollo y queso', 'Quinoa-Chupe mit Hähnchen und Käse', 'soups_stews', 'lunch', 15, 13, 6, 'simmering', 'arequipa'),
];
