import { B } from './rows.mjs';

export default [
  B('pe-phase-a-101', 'أروز كون باتو نورتيño بالكزبرة والبرتقال', 'Northern Arroz con Pato with Cilantro and Orange', 'Arroz con pato du nord à la coriandre et orange', 'Arroz con pato norteño con cilantro y naranja', 'Nordperuanischer Arroz con Pato mit Koriander und Orange', 'poultry_mains', 'dinner', 18, 20, 8, 'simmering', 'lambayeque'),
  B('pe-phase-a-102', 'سيكو دي كابريتو بالفاصولياء واليقطين', 'Seco de Cabrito with Beans and Squash', 'Seco de cabrito aux haricots et courge', 'Seco de cabrito con frijoles y zapallo', 'Seco de Cabrito mit Bohnen und Kürbis', 'meat_mains', 'dinner', 21, 10, 9, 'braising', 'cajamarca'),
  B('pe-phase-a-103', 'أروز كون ماريشكوس بالكزبرة والفلفل', 'Arroz con Mariscos with Cilantro and Chile', 'Arroz con mariscos à la coriandre et piment', 'Arroz con mariscos con cilantro y ají', 'Arroz con Mariscos mit Koriander und Chili', 'fish_seafood', 'dinner', 18, 22, 7, 'simmering', 'callao'),
  B('pe-phase-a-104', 'تالارينيس هواكّاينا بالدجاج والجبن الطازج', 'Tallarines a la Huancaina with Chicken and Fresh Cheese', 'Tallarines à la huancaína au poulet et fromage frais', 'Tallarines a la huancaína con pollo y queso fresco', 'Huancaina-Tallarines mit Hähnchen und Frischkäse', 'poultry_mains', 'dinner', 18, 22, 9, 'boiling', 'huancayo'),
  B('pe-phase-a-105', 'تروتا بونو المقرمشة بقرمشة الكيويتشا', 'Puno Trout with Kiwicha Crust', 'Truite de Puno en croûte de kiwicha', 'Trucha de Puno con costra de kiwicha', 'Puno-Forelle mit Kiwicha-Kruste', 'fish_seafood', 'dinner', 22, 8, 8, 'pan_frying', 'puno'),
  B('pe-phase-a-106', 'باتيتا دي ريس بالفول السوداني والبطاطس', 'Beef Patita with Peanut Sauce and Potato', 'Patita de bœuf à la sauce cacahuète et pomme de terre', 'Patita de res en salsa de maní con papa', 'Rinder-Patita mit Erdnusssoße und Kartoffel', 'meat_mains', 'dinner', 18, 11, 9, 'braising', 'lima'),
  B('pe-phase-a-107', 'تامال تشينشانو بالدجاج والفول العريض', 'Chinchano Chicken and Fava Bean Tamal', 'Tamal chinchano au poulet et fèves', 'Tamal chinchano de pollo y habas', 'Chinchano-Tamal mit Hähnchen und Ackerbohnen', 'street_snacks', 'lunch', 15, 22, 7, 'steaming', 'ica'),
  B('pe-phase-a-108', 'يخنة ألباكا بالخضار والفول', 'Alpaca Stew with Vegetables and Fava Beans', 'Ragoût d’alpaga aux légumes et fèves', 'Estofado de alpaca con verduras y habas', 'Alpaka-Eintopf mit Gemüse und Ackerbohnen', 'meat_mains', 'dinner', 21, 11, 7, 'stewing', 'cusco'),
  B('pe-phase-a-109', 'أروز زامبيتو بالأرز البني والبانِيلا والجوز', 'Arroz Zambito with Brown Rice, Panela and Walnuts', 'Arroz zambito au riz complet, panela et noix', 'Arroz zambito con arroz integral, panela y nueces', 'Arroz Zambito mit Vollkornreis, Panela und Walnüssen', 'rice_cakes_sweets', 'snack', 7, 31, 8, 'simmering', 'lima'),
  B('pe-phase-a-110', 'سلطة تاروي بالتونة والبيض والطماطم', 'Tarwi Salad with Tuna, Egg and Tomato', 'Salade de tarwi au thon, œuf et tomate', 'Ensalada de tarwi con atún, huevo y tomate', 'Tarwi-Salat mit Thunfisch, Ei und Tomate', 'salads', 'lunch', 17, 12, 7, 'assembling', 'puno'),
  B('pe-phase-a-111', 'شوربة باياريس بلحم البقر والكرنب', 'Pallares Soup with Beef and Cabbage', 'Soupe de pallares au bœuf et chou', 'Sopa de pallares con res y col', 'Pallares-Suppe mit Rindfleisch und Kohl', 'soups_stews', 'lunch', 16, 14, 7, 'simmering', 'lima'),
  B('pe-phase-a-112', 'كانيلوني كينوا محشو بالسبانخ والجبن', 'Quinoa Cannelloni Stuffed with Spinach and Cheese', 'Cannellonis de quinoa farcis aux épinards et fromage', 'Canelones de quinoa rellenos de espinaca y queso', 'Quinoa-Cannelloni gefüllt mit Spinat und Käse', 'vegetable_mains', 'dinner', 14, 22, 8, 'baking', 'cusco'),
  B('pe-phase-a-113', 'بابا خاوينا بالدجاج والجبن', 'Chicken Papa Huayro with Cheese', 'Papa huayro au poulet et fromage', 'Papa huayro con pollo y queso', 'Papa Huayro mit Hähnchen und Käse', 'poultry_mains', 'lunch', 16, 17, 7, 'baking', 'ancash'),
];
