import { B } from './rows.mjs';

export default [
  B('pe-phase-a-176', 'شوربة قرع بالتاروي والهواكاتاي', 'Squash Soup with Tarwi and Huacatay', 'Soupe de courge au tarwi et huacatay', 'Sopa de zapallo con tarwi y huacatay', 'Kürbissuppe mit Tarwi und Huacatay', 'soups_stews', 'lunch', 11, 16, 5, 'simmering', 'cusco'),
  B('pe-phase-a-177', 'سيكو ألباكا بالفاصولياء والبطاطس', 'Alpaca Seco with Beans and Potatoes', 'Seco d’alpaga aux haricots et pommes de terre', 'Seco de alpaca con frijoles y papas', 'Alpaka-Seco mit Bohnen und Kartoffeln', 'meat_mains', 'dinner', 22, 11, 8, 'braising', 'cusco'),
  B('pe-phase-a-178', 'تشوفا مأكولات بحرية بالكينوا والخضار', 'Seafood Chaufa with Quinoa and Vegetables', 'Chaufa de fruits de mer au quinoa et légumes', 'Chaufa de mariscos con quinoa y verduras', 'Meeresfrüchte-Chaufa mit Quinoa und Gemüse', 'fish_seafood', 'dinner', 18, 20, 7, 'sauteing', 'callao'),
  B('pe-phase-a-179', 'روكوتو ريلينو بالديك الرومي والكينوا', 'Rocoto Relleno with Turkey and Quinoa', 'Rocoto relleno à la dinde et quinoa', 'Rocoto relleno de pavo y quinoa', 'Rocoto Relleno mit Pute und Quinoa', 'poultry_mains', 'dinner', 18, 11, 8, 'baking', 'arequipa'),
  B('pe-phase-a-180', 'لحم بقري إسكابيشي بالبصل الأحمر والليمون', 'Beef Escabeche with Red Onion and Lime', 'Escabèche de bœuf à l’oignon rouge et citron vert', 'Escabeche de res con cebolla morada y lima', 'Rindfleisch-Escabeche mit roter Zwiebel und Limette', 'meat_mains', 'lunch', 20, 7, 8, 'braising', 'lima'),
  B('pe-phase-a-181', 'تورتيّا تاروي بالبطاطس والجبن', 'Tarwi Tortilla with Potato and Cheese', 'Tortilla de tarwi à la pomme de terre et fromage', 'Tortilla de tarwi con papa y queso', 'Tarwi-Tortilla mit Kartoffel und Käse', 'breakfast_items', 'breakfast', 15, 14, 8, 'pan_frying', 'puno'),
  B('pe-phase-a-182', 'كارابولكرا دجاج بالفول السوداني والبطاطس المجففة', 'Chicken Carapulcra with Peanuts and Dried Potato', 'Carapulcra de poulet aux cacahuètes et pommes de terre séchées', 'Carapulcra de pollo con maní y papa seca', 'Hähnchen-Carapulcra mit Erdnüssen und getrockneten Kartoffeln', 'poultry_mains', 'dinner', 18, 13, 9, 'stewing', 'ica'),
  B('pe-phase-a-183', 'روبيان أجي ليمو بالكينوا والذرة', 'Shrimp Aji Limo with Quinoa and Corn', 'Crevettes à l’aji limo, quinoa et maïs', 'Camarones al ají limo con quinoa y maíz', 'Garnelen mit Aji Limo, Quinoa und Mais', 'fish_seafood', 'dinner', 20, 15, 6, 'sauteing', 'piura'),
  B('pe-phase-a-184', 'تاكو تاكو باياريس بالتروتا المشوية', 'Pallares Tacu Tacu with Grilled Trout', 'Tacu tacu de pallares à la truite grillée', 'Tacu tacu de pallares con trucha a la parrilla', 'Pallares-Tacu-Tacu mit gegrillter Forelle', 'fish_seafood', 'lunch', 19, 20, 8, 'pan_frying', 'puno'),
  B('pe-phase-a-185', 'تروتا بالماراكويّا والهوكاتاي', 'Trout with Passion Fruit and Huacatay', 'Truite au fruit de la passion et huacatay', 'Trucha con maracuyá y huacatay', 'Forelle mit Passionsfrucht und Huacatay', 'fish_seafood', 'dinner', 21, 7, 7, 'baking', 'puno'),
  B('pe-phase-a-186', 'موتشيكا كروكيت بالسمك والبطاطا الحلوة', 'Moche Fish Croquettes with Sweet Potato', 'Croquettes de poisson moche à la patate douce', 'Croquetas moche de pescado con camote', 'Moche-Fischkroketten mit Süßkartoffel', 'fish_seafood', 'snack', 17, 18, 6, 'baking', 'lambayeque'),
  B('pe-phase-a-187', 'كاو كاو بطاروي والذرة والفاصولياء الخضراء', 'Cau Cau with Tarwi, Corn and Green Beans', 'Cau cau au tarwi, maïs et haricots verts', 'Cau cau con tarwi, maíz y vainitas', 'Cau Cau mit Tarwi, Mais und grünen Bohnen', 'vegetable_mains', 'dinner', 13, 16, 7, 'stewing', 'lima'),
];
