import { B } from './rows.mjs';

export default [
  B('pe-phase-a-126', 'بط مشوي بصلصة الفلفل بانكا والبرتقال', 'Roast Duck with Aji Panca and Orange Sauce', 'Canard rôti à la sauce aji panca et orange', 'Pato asado con salsa de ají panca y naranja', 'Gebratene Ente mit Aji-Panca-Orangensoße', 'poultry_mains', 'dinner', 22, 6, 10, 'roasting', 'lambayeque'),
  B('pe-phase-a-127', 'سيكو دي كابريتو بالفاصولياء والقرع', 'Cajamarca-Style Cabrito Stew with Beans and Squash', 'Seco de cabrito aux haricots et courge', 'Seco de cabrito con frijoles y zapallo', 'Seco de Cabrito mit Bohnen und Kürbis', 'meat_mains', 'dinner', 21, 10, 9, 'braising', 'cajamarca'),
  B('pe-phase-a-128', 'أروز كون ماريشكوس بالكزبرة والفلفل', 'Callao Seafood Rice with Cilantro and Chile', 'Arroz con mariscos à la coriandre et piment', 'Arroz con mariscos con cilantro y ají', 'Arroz con Mariscos mit Koriander und Chili', 'fish_seafood', 'dinner', 18, 22, 7, 'simmering', 'callao'),
  B('pe-phase-a-129', 'تالارينيس هواكّاينا بالدجاج والجبن الطازج', 'Huancayo Chicken Noodles with Fresh Cheese', 'Tallarines à la huancaína au poulet et fromage frais', 'Tallarines a la huancaína con pollo y queso fresco', 'Huancaina-Tallarines mit Hähnchen und Frischkäse', 'poultry_mains', 'dinner', 18, 22, 9, 'boiling', 'huancayo'),
  B('pe-phase-a-130', 'تروتا بونو بقشرة كيويتشا مقرمشة', 'Puno Trout with Crispy Kiwicha Crust', 'Truite de Puno en croûte croustillante de kiwicha', 'Trucha de Puno con costra crujiente de kiwicha', 'Puno-Forelle mit knuspriger Kiwicha-Kruste', 'fish_seafood', 'dinner', 22, 8, 8, 'baking', 'puno'),
  B('pe-phase-a-131', 'باتيتا لحم بقري بصلصة الفول السوداني والبطاطس', 'Lima-Style Beef Patita with Peanut Sauce and Potato', 'Patita de bœuf à la sauce cacahuète et pomme de terre', 'Patita de res en salsa de maní con papa', 'Rinder-Patita mit Erdnusssoße und Kartoffel', 'meat_mains', 'dinner', 18, 11, 9, 'braising', 'lima'),
  B('pe-phase-a-132', 'تامال تشينشانو بلحم البقر والبيض والذرة', 'Chinchano Beef Tamal with Egg and Corn', 'Tamal chinchano au bœuf, œuf et maïs', 'Tamal chinchano de res con huevo y maíz', 'Chinchano-Rindfleisch-Tamal mit Ei und Mais', 'street_snacks', 'lunch', 16, 22, 8, 'steaming', 'ica'),
  B('pe-phase-a-133', 'يخنة ألباكا بالبطاطس والفاصولياء العريضة', 'Alpaca Stew with Potato and Fava Beans', 'Ragoût d’alpaga aux pommes de terre et fèves', 'Estofado de alpaca con papa y habas', 'Alpaka-Eintopf mit Kartoffeln und Ackerbohnen', 'meat_mains', 'dinner', 21, 12, 7, 'stewing', 'cusco'),
  B('pe-phase-a-134', 'أروز زامبيتو بالكينوا والبانِيلا والجوز', 'Arroz Zambito with Quinoa, Panela and Walnuts', 'Arroz zambito au quinoa, panela et noix', 'Arroz zambito con quinoa, panela y nueces', 'Arroz Zambito mit Quinoa, Panela und Walnüssen', 'rice_cakes_sweets', 'snack', 8, 29, 8, 'simmering', 'lima'),
  B('pe-phase-a-135', 'سلطة تاروي بالتونة والفاصولياء الخضراء', 'Tarwi Salad with Tuna and Green Beans', 'Salade de tarwi au thon et haricots verts', 'Ensalada de tarwi con atún y vainitas', 'Tarwi-Salat mit Thunfisch und grünen Bohnen', 'salads', 'lunch', 18, 12, 7, 'assembling', 'puno'),
  B('pe-phase-a-136', 'شوربة باياريس بلحم البقر والكرنب', 'Lima Pallares Bean Soup with Beef and Cabbage', 'Soupe de pallares au bœuf et chou', 'Sopa de pallares con res y col', 'Pallares-Suppe mit Rindfleisch und Kohl', 'soups_stews', 'lunch', 16, 14, 7, 'simmering', 'lima'),
  B('pe-phase-a-137', 'كانيلوني كينوا محشو بالسبانخ والجبن', 'Cusco Quinoa Cannelloni with Spinach and Cheese', 'Cannellonis de quinoa farcis aux épinards et fromage', 'Canelones de quinoa rellenos de espinaca y queso', 'Quinoa-Cannelloni gefüllt mit Spinat und Käse', 'vegetable_mains', 'dinner', 14, 22, 8, 'baking', 'cusco'),
];
