import { B } from './rows.mjs';

export default [
  B('pe-phase-a-201', 'لوكرو القرع بالذرة والبازلاء والجبن الطازج', 'Locro de Zapallo with Corn, Peas and Queso Fresco', 'Locro de courge au maïs, petits pois et fromage frais', 'Locro de zapallo con choclo, arvejas y queso fresco', 'Locro mit Kürbis, Mais, Erbsen und Frischkäse', 'vegetable_mains', 'lunch', 10, 24, 8, 'stewing', 'lima'),
  B('pe-phase-a-202', 'سمك إسكابيتشي بالبطاطا الحلوة والبصل الأحمر', 'Northern Fish Escabeche with Sweet Potato and Red Onion', 'Escabèche de poisson du nord à la patate douce et oignon rouge', 'Escabeche norteño de pescado con camote y cebolla morada', 'Fisch-Escabeche aus dem Norden mit Süßkartoffel und roter Zwiebel', 'fish_seafood', 'dinner', 21, 13, 8, 'braising', 'piura'),
  B('pe-phase-a-203', 'إنشيكابي الدجاج باليوكا والفول السوداني', 'Inchicapi de Gallina with Yuca and Peanuts', 'Inchicapi de poule au manioc et aux cacahuètes', 'Inchicapi de gallina con yuca y maní', 'Inchicapi de Huhn mit Yuca und Erdnüssen', 'soups_stews', 'lunch', 18, 17, 9, 'simmering', 'loreto'),
  B('pe-phase-a-204', 'باتاراشكا البايشي في أوراق البيياو مع اليوكا', 'Patarashca de Paiche in Bijao Leaves with Cassava', 'Patarashca de paiche en feuilles de bijao au manioc', 'Patarashca de paiche en hojas de bijao con yuca', 'Patarashca de Paiche in Bijao-Blättern mit Maniok', 'fish_seafood', 'dinner', 23, 12, 7, 'grilling', 'loreto'),
  B('pe-phase-a-205', 'كابتشي الفول العريض بالبطاطس والهواكاتاي', 'Kapchi de Habas with Potato and Huacatay', 'Kapchi de fèves à la pomme de terre et huacatay', 'Kapchi de habas con papa y huacatay', 'Kapchi aus Ackerbohnen mit Kartoffel und Huacatay', 'vegetable_mains', 'lunch', 13, 21, 8, 'stewing', 'cusco'),
  B('pe-phase-a-206', 'تشايرو الأنديز بلحم البقر والتشونيو والموتي', 'Andean Chairo with Beef, Chuño and Mote', 'Chairo andin au bœuf, chuño et mote', 'Chairo andino con res, chuño y mote', 'Andiner Chairo mit Rind, Chuño und Mote', 'soups_stews', 'lunch', 18, 19, 6, 'simmering', 'puno'),
  B('pe-phase-a-207', 'أخياكو الأويوكو بالجبن الطازج والهواكاتاي', 'Ajiaco de Olluco with Fresh Cheese and Huacatay', 'Ajiaco d’olluco au fromage frais et huacatay', 'Ajiaco de olluco con queso fresco y huacatay', 'Olluco-Ajiaco mit Frischkäse und Huacatay', 'vegetable_mains', 'dinner', 12, 22, 8, 'stewing', 'ancash'),
  B('pe-phase-a-208', 'تشوبي القرع بالروبيان والذرة', 'Chupe de Zapallo with Shrimp and Corn', 'Chupe de courge aux crevettes et au maïs', 'Chupe de zapallo con camarones y choclo', 'Kürbis-Chupe mit Garnelen und Mais', 'fish_seafood', 'lunch', 18, 20, 7, 'simmering', 'arequipa'),
  B('pe-phase-a-209', 'محار كالاو على الطريقة التشالاكا بالذرة والليمون', 'Choros a la Chalaca with Corn, Lime and Red Onion', 'Choros à la chalaca au maïs, citron vert et oignon rouge', 'Choros a la chalaca con choclo, limón y cebolla morada', 'Choros a la Chalaca mit Mais, Limette und roter Zwiebel', 'fish_seafood', 'snack', 16, 14, 5, 'assembling', 'callao'),
  B('pe-phase-a-210', 'كوسا الأخطبوط ببطاطس صفراء وزيتون بوتيخا', 'Causa de Pulpo with Yellow Potato and Botija Olives', 'Causa au poulpe, pomme de terre jaune et olives botija', 'Causa de pulpo con papa amarilla y aceitunas botija', 'Causa mit Oktopus, gelber Kartoffel und Botija-Oliven', 'fish_seafood', 'lunch', 17, 19, 8, 'assembling', 'lima'),
  B('pe-phase-a-211', 'كينوا أتامالادا بالقرع والجبن الطازج', 'Quinoa Atamalada with Squash and Fresh Cheese', 'Quinoa atamalada à la courge et au fromage frais', 'Quinua atamalada con zapallo y queso fresco', 'Atamalada-Quinoa mit Kürbis und Frischkäse', 'vegetable_mains', 'lunch', 13, 24, 7, 'simmering', 'cusco'),
  B('pe-phase-a-212', 'قلي الفاصولياء الخضراء بتاروي وبطاطس الأنديز', 'Green Bean Saltado with Tarwi and Native Potato', 'Saltado de haricots verts au tarwi et pomme de terre andine', 'Saltado de vainitas con tarwi y papa nativa', 'Vainitas-Saltado mit Tarwi und Andenkartoffel', 'vegetable_mains', 'dinner', 14, 20, 8, 'sauteing', 'huancayo'),
  B('pe-phase-a-213', 'شوربة الشعير من كاخاماركا بلحم البقر والقرع والنعناع', 'Cajamarca Barley Soup with Beef, Squash and Mint', 'Soupe d’orge de Cajamarca au bœuf, courge et menthe', 'Sopa cajamarquina de cebada con res, zapallo y hierbabuena', 'Cajamarca-Graupensuppe mit Rind, Kürbis und Minze', 'soups_stews', 'lunch', 17, 21, 6, 'simmering', 'cajamarca'),
];
