import { B } from './rows.mjs';

export default [
  B('pe-phase-a-026', 'شوربة كالدّو دي غايينا بالنودلز والبيض', 'Caldo de Gallina with Noodles and Egg', 'Caldo de gallina aux nouilles et œuf', 'Caldo de gallina con fideos y huevo', 'Caldo de Gallina mit Nudeln und Ei', 'soups_stews', 'lunch', 16, 12, 6, 'simmering', 'lima'),
  B('pe-phase-a-027', 'سيفيتشي كونتشاس نيغراس بالليمون والبصل الأحمر', 'Black Shellfish Ceviche with Lime and Red Onion', 'Ceviche de conchas negras au citron vert et oignon rouge', 'Ceviche de conchas negras con lima y cebolla morada', 'Schwarzes-Muschel-Ceviche mit Limette und roter Zwiebel', 'fish_seafood', 'lunch', 18, 6, 3, 'marinating', 'piura'),
  B('pe-phase-a-028', 'كاو كاو بقلب البقر والبطاطس والكركم', 'Beef Heart Cau Cau with Potato and Turmeric', 'Cau cau de cœur de bœuf à la pomme de terre et curcuma', 'Cau cau de corazón de res con papa y cúrcuma', 'Cau Cau mit Rinderherz, Kartoffel und Kurkuma', 'meat_mains', 'dinner', 20, 9, 7, 'stewing', 'lima'),
  B('pe-phase-a-029', 'باستيل دي بابا ليماوي باللحم والبيض', 'Lima Pastel de Papa with Beef and Egg', 'Pastel de papa limeño au bœuf et œuf', 'Pastel de papa limeño con res y huevo', 'Lima-Pastel de Papa mit Rindfleisch und Ei', 'meat_mains', 'dinner', 17, 16, 8, 'baking', 'lima'),
  B('pe-phase-a-030', 'خوان دي غايينا بالأرز والدجاج والزيتون', 'Juane de Gallina with Rice, Chicken and Olives', 'Juane de gallina au riz, poulet et olives', 'Juane de gallina con arroz, pollo y aceitunas', 'Juane de Gallina mit Reis, Hähnchen und Oliven', 'poultry_mains', 'lunch', 16, 22, 8, 'steaming', 'amazonas'),
  B('pe-phase-a-031', 'كوسا دي تونا بالأفوكادو والبطاطس', 'Tuna Causa with Avocado and Potato', 'Causa au thon, avocat et pomme de terre', 'Causa de atún con aguacate y papa', 'Thunfisch-Causa mit Avocado und Kartoffel', 'fish_seafood', 'lunch', 17, 13, 8, 'assembling', 'lima'),
  B('pe-phase-a-032', 'تشوبي دي كامارون أريكويبي بالحليب والذرة', 'Arequipa Chupe de Camarones with Milk and Corn', 'Chupe de camarones d’Arequipa au lait et maïs', 'Chupe de camarones arequipeño con leche y maíz', 'Arequipa-Chupe de Camarones mit Milch und Mais', 'fish_seafood', 'lunch', 17, 11, 7, 'simmering', 'arequipa'),
  B('pe-phase-a-033', 'بيسكادو آ لو ماتشو بالمأكولات البحرية والفلفل', 'Pescado a lo Macho with Seafood and Chile', 'Pescado a lo macho aux fruits de mer et piment', 'Pescado a lo macho con mariscos y ají', 'Pescado a lo Macho mit Meeresfrüchten und Chili', 'fish_seafood', 'dinner', 21, 8, 8, 'braising', 'callao'),
  B('pe-phase-a-034', 'سلطة باياريس بالفاصولياء البيضاء والزيتون', 'Pallares Bean Salad with Olive and Onion', 'Salade de haricots pallares aux olives et oignon', 'Ensalada de pallares con aceituna y cebolla', 'Pallares-Bohnensalat mit Oliven und Zwiebel', 'salads', 'lunch', 11, 18, 5, 'assembling', 'lima'),
  B('pe-phase-a-035', 'أرز بالدجاج على طريقة الكزبرة والفلفل الأصفر', 'Cilantro Chicken Arroz con Pollo with Aji Amarillo', 'Arroz con pollo à la coriandre et aji amarillo', 'Arroz con pollo al cilantro y ají amarillo', 'Koriander-Hähnchenreis mit Aji Amarillo', 'poultry_mains', 'dinner', 17, 20, 6, 'simmering', 'lima'),
  B('pe-phase-a-036', 'هوميتا تشالا بالذرة الطازجة والجبن', 'Humita en Chala with Fresh Corn and Cheese', 'Humita en chala au maïs frais et fromage', 'Humita en chala con choclo fresco y queso', 'Humita en Chala mit frischem Mais und Käse', 'vegetable_mains', 'lunch', 10, 24, 7, 'steaming', 'cusco'),
  B('pe-phase-a-037', 'تروتا بونو المشوية بالكينوا والليمون', 'Puno Grilled Trout with Quinoa and Lime', 'Truite grillée de Puno au quinoa et citron vert', 'Trucha a la parrilla de Puno con quinoa y lima', 'Gegrillte Puno-Forelle mit Quinoa und Limette', 'fish_seafood', 'dinner', 22, 13, 7, 'grilling', 'puno'),
];
