import { B } from './rows.mjs';

export default [
  B('pe-phase-a-226', 'إسبسادو لامباييكانو بالذرة ولحم البقر والكزبرة', 'Espesado Lambayecano with Corn, Beef and Cilantro', 'Espesado lambayecano au maïs, bœuf et coriandre', 'Espesado lambayecano con choclo, res y cilantro', 'Lambayeque-Espesado mit Mais, Rind und Koriander', 'soups_stews', 'lunch', 18, 23, 7, 'simmering', 'lambayeque'),
  B('pe-phase-a-227', 'أوكوبا السلطعون بالبطاطس والهواكاتاي', 'Crab Ocopa with Potato and Huacatay', 'Ocopa au crabe, pomme de terre et huacatay', 'Ocopa de cangrejo con papa y huacatay', 'Krabben-Ocopa mit Kartoffel und Huacatay', 'fish_seafood', 'lunch', 19, 20, 9, 'assembling', 'arequipa'),
  B('pe-phase-a-228', 'مازامورا لوكومّا بالكينوا والقرفة', 'Lucuma Mazamorra with Quinoa and Cinnamon', 'Mazamorra à la lucuma, quinoa et cannelle', 'Mazamorra de lúcuma con quinua y canela', 'Lucuma-Mazamorra mit Quinoa und Zimt', 'rice_cakes_sweets', 'snack', 8, 34, 7, 'simmering', 'lima'),
  B('pe-phase-a-229', 'تيخاس إيكا بجوز البيكان وحلوى الحليب', 'Ica Tejas with Pecans and Milk Caramel', 'Tejas d’Ica aux noix de pécan et confiture de lait', 'Tejas de Ica con pecanas y manjar blanco', 'Ica-Tejas mit Pekannüssen und Milchkaramell', 'rice_cakes_sweets', 'snack', 4, 32, 12, 'assembling', 'ica'),
  B('pe-phase-a-230', 'تشومبيكي بيورانو بالبرتقال والسمسم', 'Chumbeque Piurano with Orange and Sesame', 'Chumbeque piurano à l’orange et au sésame', 'Chumbeque piurano con naranja y ajonjolí', 'Piura-Chumbeque mit Orange und Sesam', 'rice_cakes_sweets', 'snack', 5, 35, 10, 'baking', 'piura'),
  B('pe-phase-a-231', 'فريخول كولادو بالسمسم والبانِيلا', 'Frejol Colado with Sesame and Panela', 'Frejol colado au sésame et panela', 'Frejol colado con ajonjolí y panela', 'Frejol Colado mit Sesam und Panela', 'rice_cakes_sweets', 'snack', 7, 32, 6, 'simmering', 'ica'),
  B('pe-phase-a-232', 'كينغ كونغ لامباييكانو بحشوة الفاكهة وحلوى الحليب', 'King Kong de Lambayeque with Fruit Filling and Milk Caramel', 'King Kong de Lambayeque à la confiture de fruits et au lait caramélisé', 'King Kong de Lambayeque con relleno de fruta y manjar blanco', 'King Kong aus Lambayeque mit Fruchtfüllung und Milchkaramell', 'rice_cakes_sweets', 'snack', 6, 37, 13, 'baking', 'lambayeque'),
  B('pe-phase-a-233', 'رانفانيتي بالخبز المحمص والبيكان والبانِيلا', 'Ranfañote with Toasted Bread, Pecans and Panela', 'Ranfañote au pain grillé, noix de pécan et panela', 'Ranfañote con pan tostado, pecanas y panela', 'Ranfañote mit Röstbrot, Pekannüssen und Panela', 'rice_cakes_sweets', 'snack', 5, 36, 12, 'assembling', 'lima'),
  B('pe-phase-a-234', 'آبي الكانيوا بالحليب والقرفة', 'Cañihua Api with Milk and Cinnamon', 'Api de cañihua au lait et à la cannelle', 'Api de cañihua con leche y canela', 'Cañihua-Api mit Milch und Zimt', 'breakfast_items', 'breakfast', 8, 31, 6, 'simmering', 'puno'),
  B('pe-phase-a-235', 'مازامورا القرع بالبانِيلا والقرنفل', 'Pumpkin Mazamorra with Panela and Cloves', 'Mazamorra de courge à la panela et aux clous de girofle', 'Mazamorra de zapallo con panela y clavo de olor', 'Kürbis-Mazamorra mit Panela und Nelken', 'rice_cakes_sweets', 'snack', 3, 35, 4, 'simmering', 'cusco'),
  B('pe-phase-a-236', 'سلطة تشونتا بالأفوكادو والطماطم والليمون', 'Chonta Salad with Avocado, Tomato and Lime', 'Salade de chonta à l’avocat, tomate et citron vert', 'Ensalada de chonta con palta, tomate y limón', 'Chonta-Salat mit Avocado, Tomate und Limette', 'salads', 'lunch', 5, 15, 8, 'assembling', 'loreto'),
  B('pe-phase-a-237', 'شوربة كاراشاما باليوكا والكزبرة', 'Carachama Soup with Cassava and Cilantro', 'Soupe de carachama au manioc et à la coriandre', 'Sopa de carachama con yuca y cilantro', 'Carachama-Suppe mit Maniok und Koriander', 'soups_stews', 'lunch', 18, 18, 6, 'simmering', 'loreto'),
];
