import { B } from './rows.mjs';

export default [
  B('ar-phase-a-176', 'باسكوالينا السبانخ والريكوتا بالبيض', 'Spinach and Ricotta Pascualina with Egg', 'Pascualina aux épinards, ricotta et œuf', 'Pascualina de espinaca y ricota con huevo', 'Pascualina mit Spinat, Ricotta und Ei', 'vegetable_mains', 'lunch', 13, 13, 8, 'baking', 'buenos_aires'),
  B('ar-phase-a-177', 'أرز أسود بالحبار والبقدونس', 'Black Rice with Squid and Parsley', 'Riz noir au calamar et persil', 'Arroz negro con calamar y perejil', 'Schwarzer Reis mit Tintenfisch und Petersilie', 'fish_seafood', 'dinner', 17, 20, 6, 'simmering', 'buenos_aires'),
  B('ar-phase-a-178', 'كتف لحم بقري مشوي بالبولينتا والتشيميتشوري', 'Roasted Beef Shoulder with Polenta and Chimichurri', 'Épaule de bœuf rôtie, polenta et chimichurri', 'Paleta de res asada con polenta y chimichurri', 'Rinderschulterbraten mit Polenta und Chimichurri', 'meat_mains', 'dinner', 22, 16, 11, 'roasting', 'cordoba'),
  B('ar-phase-a-179', 'دجاج بالكَبَر والفطر والبطاطس', 'Chicken with Capers, Mushrooms and Potato', 'Poulet aux câpres, champignons et pomme de terre', 'Pollo con alcaparras, hongos y papa', 'Hähnchen mit Kapern, Pilzen und Kartoffel', 'poultry_mains', 'dinner', 21, 8, 8, 'braising', 'mendoza'),
  B('ar-phase-a-180', 'فطائر الكوسا والكينوا بجبن بروفولوني', 'Zucchini and Quinoa Fritters with Provolone', 'Beignets de courgette et quinoa au provolone', 'Tortitas de zapallito y quinoa con provolone', 'Zucchini-Quinoa-Bratlinge mit Provolone', 'vegetable_mains', 'lunch', 13, 14, 8, 'pan_frying', 'buenos_aires'),
  B('ar-phase-a-181', 'أسياخ لحم بقري وخضار بتشيميتشوري أخضر', 'Beef and Vegetable Skewers with Green Chimichurri', 'Brochettes de bœuf et légumes au chimichurri vert', 'Brochetas de res y verduras con chimichurri verde', 'Rind-Gemüse-Spieße mit grünem Chimichurri', 'meat_mains', 'dinner', 21, 7, 10, 'grilling', 'mendoza'),
  B('ar-phase-a-182', 'فريتاتا السلق والبطاطس بجبن البروفولوني', 'Swiss Chard and Potato Frittata with Provolone', 'Frittata aux blettes et pomme de terre à la provoleta', 'Frittata de acelga y papa con provoleta', 'Mangold-Kartoffel-Frittata mit Provolone', 'breakfast_items', 'breakfast', 15, 12, 10, 'baking', 'buenos_aires'),
  B('ar-phase-a-183', 'شوربة كريمة البروكلي بالبروفوليتا', 'Broccoli Cream Soup with Provoleta', 'Velouté de brocoli à la provoleta', 'Crema de brócoli con provoleta', 'Brokkolicremesuppe mit Provoleta', 'soups_stews', 'lunch', 12, 9, 7, 'simmering', 'cordoba'),
  B('ar-phase-a-184', 'سلطة عدس بجبن الماعز والجوز', 'Lentil Salad with Goat Cheese and Walnuts', 'Salade de lentilles au chèvre et aux noix', 'Ensalada de lentejas con queso de cabra y nueces', 'Linsensalat mit Ziegenkäse und Walnüssen', 'salads', 'lunch', 13, 15, 9, 'assembling', 'mendoza'),
  B('ar-phase-a-185', 'شوربة حمص وسلق بلحم البقر', 'Chickpea and Chard Soup with Beef', 'Soupe de pois chiches et blettes au bœuf', 'Sopa de garbanzos y acelga con res', 'Kichererbsen-Mangold-Suppe mit Rindfleisch', 'soups_stews', 'lunch', 16, 12, 6, 'simmering', 'salta'),
  B('ar-phase-a-186', 'قرع كابوتيا محشو بالفاصولياء والريكوتا', 'Cabutia Squash Stuffed with Beans and Ricotta', 'Courge cabutia farcie aux haricots et ricotta', 'Calabaza cabutia rellena de frijoles y ricota', 'Cabutia-Kürbis gefüllt mit Bohnen und Ricotta', 'vegetable_mains', 'dinner', 12, 18, 7, 'baking', 'corrientes'),
  B('ar-phase-a-187', 'سمك دورادو بتشيميتشوري وكينوا', 'Dorado with Chimichurri and Quinoa', 'Dorado au chimichurri et quinoa', 'Dorado con chimichurri y quinoa', 'Dorade mit Chimichurri und Quinoa', 'fish_seafood', 'dinner', 21, 12, 8, 'grilling', 'corrientes'),
];
