import { B } from './rows.mjs';

export default [
  B('ar-phase-a-051', 'ماتامبري بلحم البقر بصلصة الطماطم والجبن', 'Matambre a la Pizza with Tomato and Cheese', 'Matambre a la pizza à la tomate et fromage', 'Matambre a la pizza con tomate y queso', 'Matambre a la Pizza mit Tomate und Käse', 'meat_mains', 'dinner', 21, 6, 10, 'baking', 'buenos_aires'),
  B('ar-phase-a-052', 'بيف كوادريل بتشيميتشوري الليمون', 'Bife de Cuadril with Lemon Chimichurri', 'Bife de cuadril au chimichurri citronné', 'Bife de cuadril con chimichurri de limón', 'Bife de Cuadril mit Zitronen-Chimichurri', 'meat_mains', 'dinner', 23, 3, 12, 'grilling', 'mendoza'),
  B('ar-phase-a-053', 'كوليتا دي كوادريل محشوة بالسبانخ والبيض', 'Colita de Cuadril Stuffed with Spinach and Egg', 'Colita de cuadril farcie aux épinards et œuf', 'Colita de cuadril rellena de espinaca y huevo', 'Colita de Cuadril gefüllt mit Spinat und Ei', 'meat_mains', 'dinner', 20, 4, 9, 'roasting', 'cordoba'),
  B('ar-phase-a-054', 'غيسو كاريرو بلحم البقر والذرة والفاصولياء', 'Guiso Carrero with Beef, Corn and Beans', 'Guiso carrero au bœuf, maïs et haricots', 'Guiso carrero de res con maíz y frijoles', 'Guiso Carrero mit Rind, Mais und Bohnen', 'soups_stews', 'lunch', 15, 16, 7, 'simmering', 'chaco'),
  B('ar-phase-a-055', 'شوربة أرز بالدجاج والخضار الكريولا', 'Criolla Chicken, Rice and Vegetable Soup', 'Soupe criolla au poulet, riz et légumes', 'Sopa criolla de pollo, arroz y verduras', 'Criolla-Hühnersuppe mit Reis und Gemüse', 'soups_stews', 'lunch', 13, 12, 4, 'simmering', 'corrientes'),
  B('ar-phase-a-056', 'ميلانيسا دجاج مخبوزة بهريس البطاطس', 'Baked Chicken Milanesa with Potato Puree', 'Milanesa de poulet au four et purée de pommes de terre', 'Milanesa de pollo al horno con puré de papa', 'Gebackene Hähnchen-Milanesa mit Kartoffelpüree', 'poultry_mains', 'dinner', 22, 12, 7, 'baking', 'buenos_aires'),
  B('ar-phase-a-057', 'تارت الذرة والريكوتا بالأوريغانو', 'Corn and Ricotta Tart with Oregano', 'Tarte au maïs et ricotta à l’origan', 'Tarta de choclo y ricota con orégano', 'Mais-Ricotta-Tarte mit Oregano', 'vegetable_mains', 'lunch', 12, 19, 8, 'baking', 'cordoba'),
  B('ar-phase-a-058', 'سمك بيخيرّي بدقيق الذرة والليمون', 'Pejerrey with Cornmeal and Lemon', 'Pejerrey à la farine de maïs et citron', 'Pejerrey con harina de maíz y limón', 'Pejerrey mit Maismehl und Zitrone', 'fish_seafood', 'dinner', 20, 5, 7, 'pan_frying', 'buenos_aires'),
  B('ar-phase-a-059', 'بوتشيرو دجاج بالكوسا والحمص', 'Chicken Puchero with Squash and Chickpeas', 'Puchero de poulet à la courge et aux pois chiches', 'Puchero de pollo con zapallo y garbanzos', 'Hähnchen-Puchero mit Kürbis und Kichererbsen', 'poultry_mains', 'lunch', 15, 12, 5, 'simmering', 'salta'),
  B('ar-phase-a-060', 'نيوكي الريكوتا بصلصة الطماطم والريحان', 'Ricotta Gnocchi with Tomato and Basil Sauce', 'Gnocchis à la ricotta, sauce tomate et basilic', 'Ñoquis de ricota con salsa de tomate y albahaca', 'Ricotta-Gnocchi mit Tomaten-Basilikum-Soße', 'vegetable_mains', 'dinner', 13, 24, 7, 'boiling', 'buenos_aires'),
  B('ar-phase-a-061', 'إمبانادا هوميتا بالذرة والجبن', 'Humita Empanada with Corn and Cheese', 'Empanada de humita au maïs et fromage', 'Empanada de humita con maíz y queso', 'Humita-Empanada mit Mais und Käse', 'street_snacks', 'snack', 10, 23, 8, 'baking', 'tucuman'),
  B('ar-phase-a-062', 'بودينغ السلق والريكوتا بالبصل', 'Swiss Chard and Ricotta Budin with Onion', 'Budin de blettes et ricotta à l’oignon', 'Budín de acelga y ricota con cebolla', 'Mangold-Ricotta-Budin mit Zwiebel', 'vegetable_mains', 'lunch', 12, 13, 7, 'baking', 'buenos_aires'),
  B('ar-phase-a-063', 'فطيرة لحم بقري كريولا بالبيض والزيتون', 'Criolla Beef Pie with Egg and Olives', 'Tourte criolla au bœuf, œuf et olives', 'Pastel criollo de res con huevo y aceitunas', 'Criolla-Rindfleischpastete mit Ei und Oliven', 'meat_mains', 'dinner', 17, 19, 9, 'baking', 'salta'),
];
