import { B } from './rows.mjs';

export default [
  B('ar-phase-a-026', 'فيتيل توني بلحم البقر وصلصة التونة والكبر', 'Vitel Tone Beef with Tuna and Caper Sauce', 'Vitel tone au bœuf, sauce au thon et câpres', 'Vitel toné de res con salsa de atún y alcaparras', 'Vitel Toné mit Rindfleisch, Thunfisch-Kapern-Soße', 'meat_mains', 'lunch', 20, 4, 10, 'simmering', 'buenos_aires'),
  B('ar-phase-a-027', 'تامال سالتينيو بلحم البقر والبيض والذرة', 'Salteño Beef, Egg and Corn Tamal', 'Tamal salteño au bœuf, œuf et maïs', 'Tamal salteño de res, huevo y maíz', 'Salteño-Tamal mit Rind, Ei und Mais', 'street_snacks', 'lunch', 15, 22, 8, 'steaming', 'salta'),
  B('ar-phase-a-028', 'فوغازيتا محشوة بالجبن والبصل', 'Fugazzeta Stuffed with Cheese and Onion', 'Fugazzeta farcie au fromage et oignon', 'Fugazzeta rellena de queso y cebolla', 'Gefüllte Fugazzeta mit Käse und Zwiebel', 'street_snacks', 'dinner', 15, 28, 12, 'baking', 'buenos_aires'),
  B('ar-phase-a-029', 'شوربة فول سوداني شمالية بالدجاج والخضار', 'Northern Argentine Peanut Soup with Chicken and Vegetables', 'Soupe nord-argentine aux cacahuètes, poulet et légumes', 'Sopa norteña argentina de maní con pollo y verduras', 'Nordargentinische Erdnusssuppe mit Hähnchen und Gemüse', 'soups_stews', 'lunch', 14, 12, 8, 'simmering', 'salta'),
  B('ar-phase-a-030', 'ميلانيسا باذنجان مخبوزة بجبن بروفولوني', 'Baked Eggplant Milanesa with Provolone', 'Milanesa d’aubergine au four et provolone', 'Milanesa de berenjena al horno con provolone', 'Gebackene Auberginen-Milanesa mit Provolone', 'vegetable_mains', 'dinner', 13, 17, 9, 'baking', 'buenos_aires'),
  B('ar-phase-a-031', 'بيف أنشو مشوي بتشيميتشوري', 'Grilled Bife Ancho with Chimichurri', 'Bife ancho grillé au chimichurri', 'Bife ancho a la parrilla con chimichurri', 'Gegrilltes Bife Ancho mit Chimichurri', 'meat_mains', 'dinner', 24, 2, 15, 'grilling', 'mendoza'),
  B('ar-phase-a-032', 'أرز بالدجاج على الطريقة الكريولا', 'Criolla Chicken and Rice', 'Poulet et riz à la criolla', 'Arroz con pollo a la criolla', 'Criolla-Hähnchen mit Reis', 'poultry_mains', 'dinner', 16, 19, 6, 'simmering', 'corrientes'),
  B('ar-phase-a-033', 'باستيل دي تشوكلو بلحم البقر والذرة', 'Pastel de Choclo with Beef and Corn', 'Pastel de choclo au bœuf et maïs', 'Pastel de choclo con carne de res y maíz', 'Pastel de Choclo mit Rindfleisch und Mais', 'meat_mains', 'dinner', 16, 18, 8, 'baking', 'cordoba'),
  B('ar-phase-a-034', 'دجاج بروفنسال بالليمون والبقدونس', 'Argentine Chicken Provenzal with Lemon and Parsley', 'Poulet provenzal argentin au citron et persil', 'Pollo provenzal argentino con limón y perejil', 'Argentinisches Hähnchen Provenzal mit Zitrone und Petersilie', 'poultry_mains', 'dinner', 22, 3, 7, 'roasting', 'buenos_aires'),
  B('ar-phase-a-035', 'شيباغواسو بالذرة وجبن طازج', 'Chipa Guazu with Corn and Fresh Cheese', 'Chipa guazu au maïs et fromage frais', 'Chipa guazú con maíz y queso fresco', 'Chipa Guazu mit Mais und Frischkäse', 'vegetable_mains', 'side', 11, 20, 8, 'baking', 'corrientes'),
  B('ar-phase-a-036', 'سورينتينوس بالقرع والجبن', 'Pumpkin and Cheese Sorrentinos', 'Sorrentinos à la courge et au fromage', 'Sorrentinos de calabaza y queso', 'Kürbis-Käse-Sorrentinos', 'vegetable_mains', 'dinner', 12, 26, 8, 'boiling', 'buenos_aires'),
  B('ar-phase-a-037', 'تراوت باتاغوني بالكينوا والليمون', 'Patagonian Trout with Quinoa and Lemon', 'Truite de Patagonie au quinoa et citron', 'Trucha patagónica con quinoa y limón', 'Patagonische Forelle mit Quinoa und Zitrone', 'fish_seafood', 'dinner', 22, 13, 8, 'baking', 'patagonia'),
];
