import { B } from './rows.mjs';

export default [
  B('ar-phase-a-101', 'رغيف لحم أرجنتيني محشو بالسبانخ والبيض', 'Argentine Meatloaf Stuffed with Spinach and Egg', 'Pain de viande argentin farci aux épinards et œuf', 'Pan de carne argentino relleno de espinaca y huevo', 'Argentinischer Hackbraten gefüllt mit Spinat und Ei', 'meat_mains', 'dinner', 20, 5, 10, 'baking', 'buenos_aires'),
  B('ar-phase-a-102', 'أقراص ميرلوزا بالكينوا والبقدونس', 'Merluza Cakes with Quinoa and Parsley', 'Galettes de merluza au quinoa et persil', 'Tortitas de merluza con quinoa y perejil', 'Seehechtküchlein mit Quinoa und Petersilie', 'fish_seafood', 'lunch', 19, 12, 6, 'pan_frying', 'patagonia'),
  B('ar-phase-a-103', 'توماتيكان بالذرة والطماطم وجبن بانلا', 'Tomatican with Corn, Tomato and Panela', 'Tomatican au maïs, tomate et panela', 'Tomaticán con maíz, tomate y panela', 'Tomatican mit Mais, Tomate und Panela', 'vegetable_mains', 'lunch', 11, 17, 6, 'stewing', 'mendoza'),
  B('ar-phase-a-104', 'دجاج أرجنتيني بالبصل الأخضر والقشدة', 'Argentine Chicken al Verdeo with Cream', 'Poulet argentin al verdeo à la crème', 'Pollo argentino al verdeo con crema', 'Argentinisches Hähnchen al Verdeo mit Sahne', 'poultry_mains', 'dinner', 21, 4, 9, 'sauteing', 'buenos_aires'),
  B('ar-phase-a-105', 'تورتيّا السلق بجبن الماعز والبصل', 'Swiss Chard Tortilla with Goat Cheese and Onion', 'Tortilla de blettes au chèvre et oignon', 'Tortilla de acelga con queso de cabra y cebolla', 'Mangold-Tortilla mit Ziegenkäse und Zwiebel', 'breakfast_items', 'breakfast', 13, 7, 10, 'pan_frying', 'cordoba'),
  B('ar-phase-a-106', 'نيوكي البطاطس بصلصة الطماطم المشوية', 'Potato Gnocchi with Roasted Tomato Sauce', 'Gnocchis de pommes de terre à la tomate rôtie', 'Ñoquis de papa con salsa de tomate asado', 'Kartoffel-Gnocchi mit gerösteter Tomatensoße', 'vegetable_mains', 'dinner', 10, 27, 6, 'boiling', 'buenos_aires'),
  B('ar-phase-a-107', 'طاجن مأكولات بحرية باتاغوني بالطماطم والذرة', 'Patagonian Seafood Cazuela with Tomato and Corn', 'Cazuela de fruits de mer de Patagonie à la tomate et maïs', 'Cazuela patagónica de mariscos con tomate y maíz', 'Patagonischer Meeresfrüchte-Cazuela mit Tomate und Mais', 'fish_seafood', 'dinner', 18, 9, 6, 'simmering', 'patagonia'),
  B('ar-phase-a-108', 'بودينغ الخبز الأرجنتيني بدولسي دي ليتشي', 'Argentine Bread Pudding with Dulce de Leche', 'Pudding de pain argentin au dulce de leche', 'Budín de pan argentino con dulce de leche', 'Argentinischer Brotpudding mit Dulce de Leche', 'rice_cakes_sweets', 'snack', 8, 29, 7, 'baking', 'buenos_aires'),
  B('ar-phase-a-109', 'تارت الباذنجان والريكوتا بالريحان', 'Eggplant and Ricotta Tart with Basil', 'Tarte à l’aubergine et ricotta au basilic', 'Tarta de berenjena y ricota con albahaca', 'Auberginen-Ricotta-Tarte mit Basilikum', 'vegetable_mains', 'lunch', 12, 14, 8, 'baking', 'mendoza'),
  B('ar-phase-a-110', 'لحم بقري مشوي بالبطاطا الحلوة والتشيميتشوري', 'Roast Beef with Sweet Potato and Chimichurri', 'Bœuf rôti à la patate douce et chimichurri', 'Res asada con batata y chimichurri', 'Rinderbraten mit Süßkartoffel und Chimichurri', 'meat_mains', 'dinner', 22, 10, 10, 'roasting', 'cordoba'),
  B('ar-phase-a-111', 'سلطة كينوا وحمص ببذور القرع والبقدونس', 'Quinoa and Chickpea Salad with Pumpkin Seeds and Parsley', 'Salade de quinoa et pois chiches aux graines de courge et persil', 'Ensalada de quinoa y garbanzos con pepitas y perejil', 'Quinoa-Kichererbsen-Salat mit Kürbiskernen und Petersilie', 'salads', 'lunch', 11, 22, 7, 'assembling', 'salta'),
  B('ar-phase-a-112', 'تورتا روغيل بطبقات دولسي دي ليتشي', 'Torta Rogel with Layers of Dulce de Leche', 'Torta Rogel aux couches de dulce de leche', 'Torta Rogel con capas de dulce de leche', 'Torta Rogel mit Dulce-de-Leche-Schichten', 'rice_cakes_sweets', 'snack', 7, 38, 11, 'baking', 'buenos_aires'),
  B('ar-phase-a-113', 'كيسيو معجون السفرجل والجوز', 'Quesillo with Quince Paste and Walnuts', 'Quesillo à la pâte de coing et aux noix', 'Quesillo con dulce de membrillo y nueces', 'Quesillo mit Quittenpaste und Walnüssen', 'breakfast_items', 'snack', 14, 15, 9, 'assembling', 'tucuman'),
];
