import { B } from './rows.mjs';

export default [
  B('ar-phase-a-151', 'شوربة بصل كريولا ببروفوليتا', 'Criolla Onion Soup with Provoleta', 'Soupe criolla à l’oignon et provoleta', 'Sopa criolla de cebolla con provoleta', 'Criolla-Zwiebelsuppe mit Provoleta', 'soups_stews', 'lunch', 12, 11, 8, 'baking', 'buenos_aires'),
  B('ar-phase-a-152', 'بيف دي أوجو بصلصة كريولا', 'Bife de Ojo with Criolla Salsa', 'Bife de ojo à la salsa criolla', 'Bife de ojo con salsa criolla', 'Bife de Ojo mit Criolla-Salsa', 'meat_mains', 'dinner', 24, 4, 14, 'grilling', 'buenos_aires'),
  B('ar-phase-a-153', 'تارت البروكلي والريكوتا ببذور القرع', 'Broccoli and Ricotta Tart with Pumpkin Seeds', 'Tarte au brocoli et ricotta aux graines de courge', 'Tarta de brócoli y ricota con pepitas', 'Brokkoli-Ricotta-Tarte mit Kürbiskernen', 'vegetable_mains', 'lunch', 13, 13, 8, 'baking', 'cordoba'),
  B('ar-phase-a-154', 'سمك مخبوز بالليمون والزيتون والكبر', 'Baked Fish with Lemon, Olives and Capers', 'Poisson au four au citron, olives et câpres', 'Pescado al horno con limón, aceitunas y alcaparras', 'Ofenfisch mit Zitrone, Oliven und Kapern', 'fish_seafood', 'dinner', 20, 5, 7, 'baking', 'patagonia'),
  B('ar-phase-a-155', 'أومليت الذرة والسبانخ ببروفوليتا', 'Corn and Spinach Omelet with Provoleta', 'Omelette au maïs et épinards à la provoleta', 'Omelet de maíz y espinaca con provoleta', 'Mais-Spinat-Omelett mit Provoleta', 'breakfast_items', 'breakfast', 15, 10, 10, 'pan_frying', 'corrientes'),
  B('ar-phase-a-156', 'يخنة فاصولياء سوداء باللحم والقرع', 'Black Bean, Beef and Squash Stew', 'Ragoût de haricots noirs, bœuf et courge', 'Guiso de frijoles negros con res y zapallo', 'Schwarze-Bohnen-Rind-Kürbis-Eintopf', 'soups_stews', 'dinner', 16, 14, 7, 'stewing', 'chaco'),
  B('ar-phase-a-157', 'تورتا ريكوتا بالليمون والفانيليا', 'Ricotta Torta with Lemon and Vanilla', 'Torta à la ricotta, citron et vanille', 'Torta de ricota con limón y vainilla', 'Ricotta-Torta mit Zitrone und Vanille', 'rice_cakes_sweets', 'snack', 10, 26, 8, 'baking', 'buenos_aires'),
  B('ar-phase-a-158', 'لوميتو لحم بقري بالأفوكادو والبيض', 'Argentine Lomito with Avocado and Egg', 'Lomito argentin à l’avocat et œuf', 'Lomito argentino con aguacate y huevo', 'Argentinischer Lomito mit Avocado und Ei', 'meat_mains', 'lunch', 21, 18, 11, 'grilling', 'buenos_aires'),
  B('ar-phase-a-159', 'سمك مخبوز بقشرة الملح والأعشاب', 'Salt-Crusted Baked Fish with Herbs', 'Poisson en croûte de sel aux herbes', 'Pescado al horno en costra de sal y hierbas', 'Fisch in Salzkruste mit Kräutern gebacken', 'fish_seafood', 'dinner', 21, 2, 7, 'baking', 'patagonia'),
  B('ar-phase-a-160', 'نودلز شمندر طازجة بصلصة الريكوتا', 'Fresh Beet Noodles with Ricotta Sauce', 'Nouilles fraîches de betterave à la sauce ricotta', 'Fideos frescos de remolacha con salsa de ricota', 'Frische Rote-Bete-Nudeln mit Ricottasoße', 'vegetable_mains', 'dinner', 13, 24, 7, 'boiling', 'buenos_aires'),
  B('ar-phase-a-161', 'شوربة طماطم وكينوا ببروفولوني', 'Tomato and Quinoa Soup with Provolone', 'Soupe de tomate et quinoa à la provolone', 'Sopa de tomate y quinoa con provolone', 'Tomaten-Quinoa-Suppe mit Provolone', 'soups_stews', 'lunch', 12, 14, 6, 'simmering', 'mendoza'),
  B('ar-phase-a-162', 'سلطة فاصولياء الزبدة بالتونة والبيض', 'Butter Bean Salad with Tuna and Egg', 'Salade de haricots beurre au thon et œuf', 'Ensalada de porotos manteca con atún y huevo', 'Butterbohnensalat mit Thunfisch und Ei', 'salads', 'lunch', 17, 10, 6, 'assembling', 'corrientes'),
  B('ar-phase-a-163', 'كروكيت المنيهوت والريكوتا بالأوريغانو', 'Cassava and Ricotta Croquettes with Oregano', 'Croquettes de manioc et ricotta à l’origan', 'Croquetas de mandioca y ricota con orégano', 'Maniok-Ricotta-Kroketten mit Oregano', 'vegetable_mains', 'snack', 11, 20, 7, 'baking', 'misiones'),
];
