import { B } from './rows.mjs';

export default [
  B('ar-phase-a-126', 'كرات لحم بقري أرجنتينية بصلصة الطماطم', 'Argentine Beef Meatballs in Tomato Sauce', 'Boulettes de bœuf argentines à la sauce tomate', 'Albóndigas argentinas de res en salsa de tomate', 'Argentinische Rindfleischbällchen in Tomatensoße', 'meat_mains', 'dinner', 19, 8, 9, 'simmering', 'cordoba'),
  B('ar-phase-a-127', 'شوربة سوروبّي بارانا بالبطاطس والطماطم', 'Parana Surubi Soup with Potato and Tomato', 'Soupe de surubi du Paraná à la pomme de terre et tomate', 'Sopa de surubí del Paraná con papa y tomate', 'Paraná-Surubi-Suppe mit Kartoffel und Tomate', 'fish_seafood', 'lunch', 19, 9, 5, 'simmering', 'corrientes'),
  B('ar-phase-a-128', 'أومليت السبانخ ببروفوليتا والفلفل المشوي', 'Spinach Omelet with Provoleta and Roasted Pepper', 'Omelette aux épinards, provoleta et poivron rôti', 'Omelet de espinaca con provoleta y pimiento asado', 'Spinatomelett mit Provoleta und gerösteter Paprika', 'breakfast_items', 'breakfast', 16, 5, 12, 'pan_frying', 'buenos_aires'),
  B('ar-phase-a-129', 'طاجن كينوا ولحم ضأن باتاغوني بالسلق', 'Patagonian Lamb, Quinoa and Chard Cazuela', 'Cazuela d’agneau patagonien, quinoa et blettes', 'Cazuela patagónica de cordero, quinoa y acelga', 'Patagonischer Lamm-Quinoa-Mangold-Cazuela', 'meat_mains', 'dinner', 18, 12, 8, 'simmering', 'patagonia'),
  B('ar-phase-a-130', 'ميلانيسا ميرلوزا بتشيميتشوري الليمون', 'Merluza Milanesa with Lemon Chimichurri', 'Milanesa de merluza au chimichurri citronné', 'Milanesa de merluza con chimichurri de limón', 'Merluza-Milanesa mit Zitronen-Chimichurri', 'fish_seafood', 'dinner', 20, 14, 8, 'baking', 'patagonia'),
  B('ar-phase-a-131', 'دجاج محشو بالهوميتا والسبانخ', 'Chicken Stuffed with Humita and Spinach', 'Poulet farci à la humita et aux épinards', 'Pollo relleno de humita y espinaca', 'Hähnchen gefüllt mit Humita und Spinat', 'poultry_mains', 'dinner', 21, 9, 8, 'roasting', 'tucuman'),
  B('ar-phase-a-132', 'باستافولا سفرجل أرجنتينية', 'Argentine Quince Pastafrola', 'Pastafrola argentine à la pâte de coing', 'Pastafrola argentina de membrillo', 'Argentinische Quitten-Pastafrola', 'rice_cakes_sweets', 'snack', 5, 42, 10, 'baking', 'buenos_aires'),
  B('ar-phase-a-133', 'يخنة عدس وميرلوزا بالطماطم والسبانخ', 'Lentil and Merluza Stew with Tomato and Spinach', 'Ragoût de lentilles et merluza à la tomate et épinards', 'Guiso de lentejas y merluza con tomate y espinaca', 'Linsen-Merluza-Eintopf mit Tomate und Spinat', 'fish_seafood', 'dinner', 17, 14, 5, 'stewing', 'patagonia'),
  B('ar-phase-a-134', 'سورينتينوس هوميتا بصلصة الريحان', 'Humita Sorrentinos with Basil Sauce', 'Sorrentinos de humita à la sauce basilic', 'Sorrentinos de humita con salsa de albahaca', 'Humita-Sorrentinos mit Basilikumsoße', 'vegetable_mains', 'dinner', 12, 25, 8, 'boiling', 'tucuman'),
  B('ar-phase-a-135', 'بوثيكا لحم بقري بالحمص والخضار', 'Beef Buseca with Chickpeas and Vegetables', 'Buseca de bœuf aux pois chiches et légumes', 'Buseca de res con garbanzos y verduras', 'Rinder-Buseca mit Kichererbsen und Gemüse', 'soups_stews', 'lunch', 17, 11, 8, 'simmering', 'buenos_aires'),
  B('ar-phase-a-136', 'تارت البصل ببروفوليتا والأوريغانو', 'Onion Tart with Provoleta and Oregano', 'Tarte à l’oignon, provoleta et origan', 'Tarta de cebolla con provoleta y orégano', 'Zwiebel-Tarte mit Provoleta und Oregano', 'vegetable_mains', 'lunch', 13, 17, 9, 'baking', 'buenos_aires'),
  B('ar-phase-a-137', 'غطاء لحم بقري مشوي بالبطاطا الحلوة', 'Roasted Beef Tapa with Sweet Potato', 'Tapa de bœuf rôtie à la patate douce', 'Tapa de asado al horno con batata', 'Rinder-Tapa aus dem Ofen mit Süßkartoffel', 'meat_mains', 'dinner', 22, 9, 10, 'roasting', 'mendoza'),
];
