import { B } from './rows.mjs';

export default [
  B('ar-phase-a-001', 'إمبانادا كريولا باللحم البقري والزيتون', 'Argentine Beef Criolla Empanada', 'Empanada criolla argentine au bœuf et olives', 'Empanada criolla argentina de res y aceitunas', 'Argentinische Criolla-Empanada mit Rind und Oliven', 'street_snacks', 'lunch', 16, 20, 9, 'baking', 'buenos_aires'),
  B('ar-phase-a-002', 'بروفوليتا مشوية بالأوريغانو والطماطم', 'Grilled Provoleta with Oregano and Tomato', 'Provoleta grillée à l’origan et tomate', 'Provoleta a la parrilla con orégano y tomate', 'Gegrillte Provoleta mit Oregano und Tomate', 'vegetable_mains', 'side', 22, 3, 20, 'grilling', 'buenos_aires'),
  B('ar-phase-a-003', 'باستيل دي بابا بلحم البقر والبطاطس', 'Beef and Potato Pastel de Papa', 'Pastel de papa au bœuf et pommes de terre', 'Pastel de papa con carne de res', 'Pastel de Papa mit Rindfleisch und Kartoffeln', 'meat_mains', 'dinner', 16, 15, 8, 'baking', 'cordoba'),
  B('ar-phase-a-004', 'هوميتا بالإيلوت وجبن طازج بورق الذرة', 'Humita en Chala with Corn and Fresh Cheese', 'Humita en chala au maïs et fromage frais', 'Humita en chala con maíz y queso fresco', 'Humita en Chala mit Mais und Frischkäse', 'vegetable_mains', 'lunch', 10, 22, 7, 'steaming', 'salta'),
  B('ar-phase-a-005', 'أضلاع لحم بقري مشوية بصلصة تشيميتشوري', 'Asado de Tira with Chimichurri', 'Asado de tira au chimichurri', 'Asado de tira con chimichurri', 'Asado de Tira mit Chimichurri', 'meat_mains', 'dinner', 23, 2, 16, 'grilling', 'buenos_aires'),
  B('ar-phase-a-006', 'لوكرو أرجنتيني بلحم البقر والفاصولياء والقرع', 'Argentine Beef, Bean and Squash Locro', 'Locro argentin au bœuf, haricots et courge', 'Locro argentino de res, frijoles y zapallo', 'Argentinischer Locro mit Rind, Bohnen und Kürbis', 'soups_stews', 'lunch', 15, 13, 8, 'simmering', 'salta'),
  B('ar-phase-a-007', 'ميلانيسا لحم بقري نابوليتانا بالطماطم والجبن', 'Beef Milanesa Napolitana with Tomato and Cheese', 'Milanesa de bœuf napolitaine à la tomate et fromage', 'Milanesa de res napolitana con tomate y queso', 'Rinder-Milanesa Napolitana mit Tomate und Käse', 'meat_mains', 'dinner', 20, 13, 11, 'baking', 'buenos_aires'),
  B('ar-phase-a-008', 'كاربونادا كريولا بلحم البقر والذرة والخوخ', 'Carbonada Criolla with Beef, Corn and Peach', 'Carbonada criolla au bœuf, maïs et pêche', 'Carbonada criolla de res con maíz y durazno', 'Carbonada Criolla mit Rind, Mais und Pfirsich', 'soups_stews', 'lunch', 14, 12, 7, 'stewing', 'cordoba'),
  B('ar-phase-a-009', 'ماتامبري ملفوف بالبيض والجزر والسبانخ', 'Matambre Arrollado with Egg, Carrot and Spinach', 'Matambre arrollado aux œufs, carotte et épinards', 'Matambre arrollado con huevo, zanahoria y espinaca', 'Matambre Arrollado mit Ei, Karotte und Spinat', 'meat_mains', 'lunch', 20, 5, 9, 'braising', 'buenos_aires'),
  B('ar-phase-a-010', 'فائينا بدقيق الحمص وبروفولوني', 'Chickpea Faina with Provolone', 'Faina à la farine de pois chiches et provolone', 'Fainá de garbanzo con provolone', 'Kichererbsen-Faina mit Provolone', 'street_snacks', 'snack', 12, 28, 8, 'baking', 'buenos_aires'),
  B('ar-phase-a-011', 'نيوكي القرع بجبن الريكوتا', 'Pumpkin Gnocchi with Ricotta', 'Gnocchis de courge à la ricotta', 'Ñoquis de calabaza con ricota', 'Kürbis-Gnocchi mit Ricotta', 'vegetable_mains', 'dinner', 11, 24, 7, 'boiling', 'mendoza'),
  B('ar-phase-a-012', 'دجاج أرجنتيني بالديسكو مع البطاطس والفلفل', 'Argentine Pollo al Disco with Potato and Peppers', 'Pollo al disco argentin aux pommes de terre et poivrons', 'Pollo al disco argentino con papa y pimientos', 'Argentinisches Pollo al Disco mit Kartoffel und Paprika', 'poultry_mains', 'dinner', 19, 9, 8, 'stewing', 'cordoba'),
  B('ar-phase-a-013', 'تارت السلق والريكوتا بالبصل', 'Swiss Chard and Ricotta Tart with Onion', 'Tarte aux blettes, ricotta et oignon', 'Tarta de acelga y ricota con cebolla', 'Mangold-Ricotta-Tarte mit Zwiebel', 'vegetable_mains', 'lunch', 12, 12, 8, 'baking', 'buenos_aires'),
];
