import { B } from './rows.mjs';

export default [
  B('ar-phase-a-076', 'بيف آ لا كريولا بالطماطم والبطاطس والفلفل', 'Bife a la Criolla with Tomato, Potato and Pepper', 'Bife a la criolla à la tomate, pomme de terre et poivron', 'Bife a la criolla con tomate, papa y pimiento', 'Bife a la Criolla mit Tomate, Kartoffel und Paprika', 'meat_mains', 'dinner', 20, 9, 10, 'stewing', 'buenos_aires'),
  B('ar-phase-a-077', 'شوربة تشوكلو بالدجاج والقرع', 'Choclo Soup with Chicken and Squash', 'Soupe de choclo au poulet et courge', 'Sopa de choclo con pollo y zapallo', 'Choclo-Suppe mit Hähnchen und Kürbis', 'soups_stews', 'lunch', 14, 14, 5, 'simmering', 'cordoba'),
  B('ar-phase-a-078', 'سوروبّي نهر بارانا بالطماطم والبصل', 'Parana River Surubi with Tomato and Onion', 'Surubi du Paraná à la tomate et oignon', 'Surubí del Paraná con tomate y cebolla', 'Paraná-Surubi mit Tomate und Zwiebel', 'fish_seafood', 'dinner', 21, 5, 7, 'baking', 'corrientes'),
  B('ar-phase-a-079', 'كوليتا دي كوادريل مشوية بالفلفل والبقدونس', 'Grilled Colita de Cuadril with Peppers and Parsley', 'Colita de cuadril grillée aux poivrons et persil', 'Colita de cuadril a la parrilla con pimientos y perejil', 'Gegrillte Colita de Cuadril mit Paprika und Petersilie', 'meat_mains', 'dinner', 23, 4, 12, 'grilling', 'mendoza'),
  B('ar-phase-a-080', 'تارت القرع والجبن الطازج بالأوريغانو', 'Squash and Fresh Cheese Tart with Oregano', 'Tarte à la courge et fromage frais à l’origan', 'Tarta de zapallo y queso fresco con orégano', 'Kürbis-Frischkäse-Tarte mit Oregano', 'vegetable_mains', 'lunch', 11, 15, 8, 'baking', 'cordoba'),
  B('ar-phase-a-081', 'سورينتينوس الدجاج والذرة بصلصة الأعشاب', 'Chicken and Corn Sorrentinos with Herb Sauce', 'Sorrentinos au poulet et maïs, sauce aux herbes', 'Sorrentinos de pollo y maíz con salsa de hierbas', 'Hähnchen-Mais-Sorrentinos mit Kräutersoße', 'poultry_mains', 'dinner', 17, 24, 8, 'boiling', 'buenos_aires'),
  B('ar-phase-a-082', 'باذنجان محشو بلحم البقر والريكوتا', 'Eggplant Stuffed with Beef and Ricotta', 'Aubergine farcie au bœuf et ricotta', 'Berenjena rellena de res y ricota', 'Aubergine gefüllt mit Rindfleisch und Ricotta', 'meat_mains', 'dinner', 16, 8, 8, 'baking', 'mendoza'),
  B('ar-phase-a-083', 'إمبانادا الذرة والجبن الكريمية', 'Creamy Corn and Cheese Empanada', 'Empanada crémeuse au maïs et fromage', 'Empanada cremosa de choclo y queso', 'Cremige Mais-Käse-Empanada', 'street_snacks', 'snack', 11, 22, 8, 'baking', 'tucuman'),
  B('ar-phase-a-084', 'تارت الدجاج والسبانخ بجبن بروفولوني', 'Chicken and Spinach Tart with Provolone', 'Tarte au poulet, épinards et provolone', 'Tarta de pollo y espinaca con provolone', 'Hähnchen-Spinat-Tarte mit Provolone', 'poultry_mains', 'lunch', 17, 12, 8, 'baking', 'buenos_aires'),
  B('ar-phase-a-085', 'طاجن سمك باتاغوني بالكينوا والخضار', 'Patagonian Fish Cazuela with Quinoa and Vegetables', 'Cazuela de poisson de Patagonie au quinoa et légumes', 'Cazuela patagónica de pescado con quinoa y verduras', 'Patagonischer Fischtopf mit Quinoa und Gemüse', 'fish_seafood', 'dinner', 19, 11, 6, 'simmering', 'patagonia'),
  B('ar-phase-a-086', 'بيف لومي بصلصة الخردل والأعشاب', 'Bife de Lomo with Mustard and Herb Sauce', 'Bife de lomo à la moutarde et aux herbes', 'Bife de lomo con salsa de mostaza y hierbas', 'Bife de Lomo mit Senf-Kräutersoße', 'meat_mains', 'dinner', 23, 4, 12, 'grilling', 'buenos_aires'),
  B('ar-phase-a-087', 'تورتيّا البطاطس والسبانخ بجبن الماعز', 'Potato and Spinach Tortilla with Goat Cheese', 'Tortilla de pommes de terre aux épinards et chèvre', 'Tortilla de papa y espinaca con queso de cabra', 'Kartoffel-Spinat-Tortilla mit Ziegenkäse', 'breakfast_items', 'breakfast', 12, 13, 9, 'pan_frying', 'cordoba'),
];
