import React from 'react';
import { useLanguage } from '../context/LanguageContext';

const MedicalDisclaimerPage: React.FC = () => {
  const { t } = useLanguage();

  return (
    <div className="min-h-screen bg-[#f8fafc]">
      <div className="bg-gradient-to-r from-amber-500 to-orange-500 text-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-10 md:py-14">
          <div className="inline-flex items-center gap-2 bg-white/10 backdrop-blur-sm px-3 py-1.5 rounded-full mb-4">
            <span className="w-1.5 h-1.5 bg-amber-200 rounded-full" />
            <span className="text-xs font-medium text-amber-100">Important Notice</span>
          </div>
          <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight">{t('medicalDisclaimer')}</h1>
          <p className="text-amber-100 text-sm mt-2">Effective Date: January 1, 2026</p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-10">
        <div className="bg-amber-50 border border-amber-200/80 rounded-2xl p-5 mb-8 animate-fade-in">
          <div className="flex items-start gap-3">
            <div className="w-10 h-10 bg-amber-100 rounded-xl flex items-center justify-center shrink-0">
              <svg className="w-5 h-5 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
              </svg>
            </div>
            <p className="text-sm font-semibold text-amber-900 leading-relaxed">
              HealthCalc.ai provides information for educational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always consult your physician before starting any diet or workout program.
            </p>
          </div>
        </div>

        <div className="card animate-fade-in">
          <div className="prose prose-sm max-w-none space-y-8 text-gray-700">
            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">General Information</h2>
              <p className="text-sm leading-relaxed">The content provided on HealthCalc.ai, including but not limited to calculators, meal plans, workout routines, lab result interpretations, and health recommendations, is designed for general informational and educational purposes only. This content is not intended to be a substitute for professional medical advice, diagnosis, or treatment.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">Not Medical Advice</h2>
              <p className="text-sm leading-relaxed">The information provided by HealthCalc.ai should not be used as a substitute for consultation with a qualified healthcare professional. The calculations are based on general formulas and published medical guidelines (ADA, DASH, USDA, ACSM) and may not account for individual health conditions, medications, allergies, or other factors that may affect your specific needs.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">No Doctor-Patient Relationship</h2>
              <p className="text-sm leading-relaxed">Use of HealthCalc.ai does not establish a doctor-patient relationship between you and HealthCalc.ai or its operators. The results and recommendations generated by our tools should be reviewed by a qualified healthcare provider before implementation.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">Lab Results Interpretation</h2>
              <p className="text-sm leading-relaxed">Our Lab Results Interpreter provides general interpretations based on published medical guidelines. These interpretations are preliminary and should not replace a review by your physician or laboratory medicine specialist. Abnormal results should always be discussed with your healthcare provider.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">Medical Guidelines Referenced</h2>
              <ul className="space-y-2 text-sm mt-3">
                <li className="flex items-start gap-2"><span className="badge-primary shrink-0 mt-0.5">ADA</span> <span>American Diabetes Association — diabetes-related calculations and lab interpretations</span></li>
                <li className="flex items-start gap-2"><span className="badge-sage shrink-0 mt-0.5">DASH</span> <span>Dietary Approaches to Stop Hypertension — blood pressure and dietary recommendations</span></li>
                <li className="flex items-start gap-2"><span className="badge-amber shrink-0 mt-0.5">USDA</span> <span>United States Department of Agriculture — nutritional guidelines and macro calculations</span></li>
                <li className="flex items-start gap-2"><span className="badge bg-purple-50 text-purple-700 shrink-0 mt-0.5">ACSM</span> <span>American College of Sports Medicine — exercise and fitness recommendations</span></li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">Emergency Situations</h2>
              <p className="text-sm leading-relaxed">If you think you may have a medical emergency, call your doctor or emergency services immediately. HealthCalc.ai is not designed to handle emergency situations and should never be used as a resource for emergency medical advice.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-900 mb-3">Assumption of Risk</h2>
              <p className="text-sm leading-relaxed">You acknowledge that any use of information from HealthCalc.ai is at your own risk. You are responsible for consulting with a qualified healthcare professional before making any health-related decisions based on the content provided by our service.</p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MedicalDisclaimerPage;
