import { B } from '../argentina-base-data/rows.mjs';

export default [
  B('ar-phase-a-088', 'إمبانادا مندوسية بلحم البقر والزيتون', 'Mendoza Beef and Olive Empanada', 'Empanada mendocine au bœuf et olives', 'Empanada mendocina de res y aceitunas', 'Mendoza-Rindfleisch-Empanada mit Oliven', 'street_snacks', 'lunch', 17, 20, 9, 'baking', 'mendoza'),
  B('ar-phase-a-089', 'وعاء دجاج بتشيميتشوري وكينوا', 'Chicken Chimichurri Quinoa Bowl', 'Bol de poulet au chimichurri et quinoa', 'Tazón de pollo con chimichurri y quinoa', 'Hähnchen-Chimichurri-Quinoa-Schale', 'poultry_mains', 'lunch', 20, 13, 8, 'grilling', 'buenos_aires'),
  B('ar-phase-a-090', 'ألفاخور دقيق الخروب بدولسي دي ليتشي', 'Carob Alfajor with Dulce de Leche', 'Alfajor à la caroube et dulce de leche', 'Alfajor de algarroba con dulce de leche', 'Johannisbrot-Alfajor mit Dulce de Leche', 'rice_cakes_sweets', 'snack', 7, 34, 10, 'baking', 'cordoba'),
  B('ar-phase-a-091', 'ميلانيسا قرع بروفولوني مخبوزة', 'Baked Pumpkin Milanesa with Provolone', 'Milanesa de courge au four et provolone', 'Milanesa de zapallo al horno con provolone', 'Gebackene Kürbis-Milanesa mit Provolone', 'vegetable_mains', 'dinner', 12, 16, 9, 'baking', 'mendoza'),
  B('ar-phase-a-092', 'ريزوتو تشوكلو بالدجاج والجبن', 'Choclo Risotto with Chicken and Cheese', 'Risotto de choclo au poulet et fromage', 'Risotto de choclo con pollo y queso', 'Choclo-Risotto mit Hähnchen und Käse', 'poultry_mains', 'dinner', 16, 19, 7, 'simmering', 'corrientes'),
  B('ar-phase-a-093', 'لحم ضأن باتاغوني مشوي بالنعناع والبطاطس', 'Grilled Patagonian Lamb with Mint and Potato', 'Agneau de Patagonie grillé à la menthe et pomme de terre', 'Cordero patagónico a la parrilla con menta y papa', 'Gegrilltes patagonisches Lamm mit Minze und Kartoffel', 'meat_mains', 'dinner', 22, 8, 12, 'grilling', 'patagonia'),
  B('ar-phase-a-094', 'زبادي دولسي دي ليتشي بالشيا والجوز', 'Dulce de Leche Yogurt with Chia and Walnuts', 'Yaourt au dulce de leche, chia et noix', 'Yogur con dulce de leche, chía y nueces', 'Dulce-de-Leche-Joghurt mit Chia und Walnüssen', 'breakfast_items', 'breakfast', 12, 15, 9, 'assembling', 'buenos_aires'),
  B('ar-phase-a-095', 'شوربة سمك وكينوا بالسبانخ', 'Fish and Quinoa Soup with Spinach', 'Soupe de poisson et quinoa aux épinards', 'Sopa de pescado y quinoa con espinaca', 'Fisch-Quinoa-Suppe mit Spinat', 'fish_seafood', 'lunch', 17, 12, 5, 'simmering', 'patagonia'),
  B('ar-phase-a-096', 'كروكيت العدس بتشيميتشوري البقدونس', 'Lentil Croquettes with Parsley Chimichurri', 'Croquettes de lentilles au chimichurri de persil', 'Croquetas de lentejas con chimichurri de perejil', 'Linsenkroketten mit Petersilien-Chimichurri', 'vegetable_mains', 'lunch', 11, 19, 7, 'baking', 'mendoza'),
  B('ar-phase-a-097', 'تارت البصل والريكوتا بالأوريغانو', 'Onion and Ricotta Tart with Oregano', 'Tarte à l’oignon et ricotta à l’origan', 'Tarta de cebolla y ricota con orégano', 'Zwiebel-Ricotta-Tarte mit Oregano', 'vegetable_mains', 'lunch', 11, 15, 8, 'baking', 'buenos_aires'),
  B('ar-phase-a-098', 'تيرنيرا بالطماطم والزيتون والأرز البني', 'Beef with Tomato, Olives and Brown Rice', 'Bœuf à la tomate, olives et riz complet', 'Ternera con tomate, aceitunas y arroz integral', 'Rindfleisch mit Tomate, Oliven und Vollkornreis', 'meat_mains', 'dinner', 18, 15, 8, 'stewing', 'salta'),
  B('ar-phase-a-099', 'سورينتينوس بلحم البقر والسبانخ', 'Beef and Spinach Sorrentinos', 'Sorrentinos au bœuf et épinards', 'Sorrentinos de res y espinaca', 'Rindfleisch-Spinat-Sorrentinos', 'meat_mains', 'dinner', 17, 23, 8, 'boiling', 'buenos_aires'),
  B('ar-phase-a-100', 'موس دولسي دي ليتشي بجبن القريش والقرفة', 'Dulce de Leche Mousse with Cottage Cheese and Cinnamon', 'Mousse au dulce de leche, fromage frais et cannelle', 'Mousse de dulce de leche con requesón y canela', 'Dulce-de-Leche-Mousse mit Hüttenkäse und Zimt', 'rice_cakes_sweets', 'snack', 12, 18, 8, 'chilling', 'cordoba'),
];
