import { B } from '../argentina-base-data/rows.mjs';

export default [
  B('ar-phase-a-064', 'هوميتا مخبوزة بالذرة والجبن والبصل', 'Baked Humita with Corn, Cheese and Onion', 'Humita au four au maïs, fromage et oignon', 'Humita al horno con maíz, queso y cebolla', 'Gebackene Humita mit Mais, Käse und Zwiebel', 'vegetable_mains', 'lunch', 11, 20, 8, 'baking', 'salta'),
  B('ar-phase-a-065', 'دجاج محشو بالسبانخ وبروفوليتا', 'Chicken Stuffed with Spinach and Provoleta', 'Poulet farci aux épinards et provoleta', 'Pollo relleno de espinaca y provoleta', 'Hähnchen gefüllt mit Spinat und Provoleta', 'poultry_mains', 'dinner', 22, 4, 10, 'roasting', 'mendoza'),
  B('ar-phase-a-066', 'كالامار مقلي بالليمون وتشيميتشوري', 'Argentine Calamari with Lemon Chimichurri', 'Calamars argentins au chimichurri citronné', 'Calamares argentinos con chimichurri de limón', 'Argentinischer Tintenfisch mit Zitronen-Chimichurri', 'fish_seafood', 'lunch', 17, 13, 7, 'pan_frying', 'buenos_aires'),
  B('ar-phase-a-067', 'ميلانيسا قرع مخبوزة بجبن الماعز', 'Baked Squash Milanesa with Goat Cheese', 'Milanesa de courge au four et fromage de chèvre', 'Milanesa de zapallo al horno con queso de cabra', 'Gebackene Kürbis-Milanesa mit Ziegenkäse', 'vegetable_mains', 'dinner', 11, 16, 8, 'baking', 'cordoba'),
  B('ar-phase-a-068', 'طماطم محشوة بلحم البقر والأرز والبيض', 'Tomatoes Stuffed with Beef, Rice and Egg', 'Tomates farcies au bœuf, riz et œuf', 'Tomates rellenos de res, arroz y huevo', 'Tomaten gefüllt mit Rind, Reis und Ei', 'meat_mains', 'dinner', 15, 12, 7, 'baking', 'buenos_aires'),
  B('ar-phase-a-069', 'تراوت باتاغوني باللوز والكينوا', 'Patagonian Trout with Almonds and Quinoa', 'Truite de Patagonie aux amandes et quinoa', 'Trucha patagónica con almendras y quinoa', 'Patagonische Forelle mit Mandeln und Quinoa', 'fish_seafood', 'dinner', 22, 10, 9, 'baking', 'patagonia'),
  B('ar-phase-a-070', 'شوربة عدس بالدجاج والسبانخ', 'Chicken, Lentil and Spinach Soup', 'Soupe de poulet, lentilles et épinards', 'Sopa de pollo, lentejas y espinaca', 'Hühner-Linsen-Spinat-Suppe', 'soups_stews', 'lunch', 14, 12, 4, 'simmering', 'mendoza'),
  B('ar-phase-a-071', 'باستيل المنيهوت بلحم البقر والزيتون', 'Cassava Pastel with Beef and Olives', 'Pastel de manioc au bœuf et olives', 'Pastel de mandioca con res y aceitunas', 'Maniok-Pastel mit Rindfleisch und Oliven', 'meat_mains', 'dinner', 16, 19, 8, 'baking', 'misiones'),
  B('ar-phase-a-072', 'بيف لومي بصلصة الفلفل الأسود والقشدة', 'Bife de Lomo with Black Pepper Cream Sauce', 'Bife de lomo à la crème de poivre noir', 'Bife de lomo con crema de pimienta negra', 'Bife de Lomo mit schwarzer Pfefferrahmsoße', 'meat_mains', 'dinner', 23, 4, 13, 'pan_frying', 'buenos_aires'),
  B('ar-phase-a-073', 'سلطة روسية أرجنتينية بالدجاج والبازلاء', 'Argentine Ensalada Rusa with Chicken and Peas', 'Ensalada rusa argentine au poulet et petits pois', 'Ensalada rusa argentina con pollo y arvejas', 'Argentinischer Ensalada Rusa mit Hähnchen und Erbsen', 'salads', 'lunch', 15, 12, 7, 'boiling', 'buenos_aires'),
  B('ar-phase-a-074', 'شوربة كريمة الذرة بالدجاج والبقدونس', 'Creamy Corn Soup with Chicken and Parsley', 'Soupe crémeuse de maïs au poulet et persil', 'Sopa cremosa de choclo con pollo y perejil', 'Cremige Maissuppe mit Hähnchen und Petersilie', 'soups_stews', 'lunch', 13, 12, 5, 'simmering', 'corrientes'),
  B('ar-phase-a-075', 'تيريْري ماتي بالليمون والنعناع', 'Argentine Terere with Lemon and Mint', 'Terere argentin au citron et à la menthe', 'Tereré argentino con limón y menta', 'Argentinischer Terere mit Zitrone und Minze', 'beverages', 'snack', 1, 3, 0, 'steeping', 'misiones'),
];
