import { B } from '../argentina-base-data/rows.mjs';

export default [
  B('ar-phase-a-164', 'ميرلوزا بقشرة بذور القرع والليمون', 'Merluza with Pumpkin Seed Crust and Lemon', 'Merluza en croûte de graines de courge et citron', 'Merluza con costra de pepitas y limón', 'Merluza mit Kürbiskernkruste und Zitrone', 'fish_seafood', 'dinner', 21, 7, 9, 'baking', 'patagonia'),
  B('ar-phase-a-165', 'دجاج بالجوز والأوريغانو مع البطاطا الحلوة', 'Chicken with Walnut, Oregano and Sweet Potato', 'Poulet aux noix, origan et patate douce', 'Pollo con nuez, orégano y batata', 'Hähnchen mit Walnuss, Oregano und Süßkartoffel', 'poultry_mains', 'dinner', 20, 10, 10, 'roasting', 'cordoba'),
  B('ar-phase-a-166', 'تارت الهليون والريكوتا بجبن بروفولوني', 'Asparagus and Ricotta Tart with Provolone', 'Tarte aux asperges et ricotta à la provoleta', 'Tarta de espárragos y ricota con provoleta', 'Spargel-Ricotta-Tarte mit Provolone', 'vegetable_mains', 'lunch', 13, 12, 9, 'baking', 'buenos_aires'),
  B('ar-phase-a-167', 'يخنة فاصولياء بيضاء باللحم والقرع', 'White Bean, Beef and Squash Stew', 'Ragoût de haricots blancs, bœuf et courge', 'Guiso de porotos blancos con res y zapallo', 'Weiße-Bohnen-Rind-Kürbis-Eintopf', 'soups_stews', 'dinner', 16, 14, 7, 'stewing', 'salta'),
  B('ar-phase-a-168', 'كوسا محشوة بالكينوا وجبن كوتيخا', 'Zucchini Stuffed with Quinoa and Cotija', 'Courgettes farcies au quinoa et cotija', 'Zapallitos rellenos de quinoa y cotija', 'Zucchini gefüllt mit Quinoa und Cotija', 'vegetable_mains', 'dinner', 12, 14, 7, 'baking', 'mendoza'),
  B('ar-phase-a-169', 'باكو إسكابيشي بالطماطم والبصل الأحمر', 'Pacu Escabeche with Tomato and Red Onion', 'Pacu en escabèche à la tomate et oignon rouge', 'Escabeche de pacú con tomate y cebolla morada', 'Pacu-Escabeche mit Tomate und roter Zwiebel', 'fish_seafood', 'lunch', 20, 6, 8, 'braising', 'corrientes'),
  B('ar-phase-a-170', 'كروكيت العدس والريكوتا بالفلفل الأحمر', 'Lentil and Ricotta Croquettes with Red Pepper', 'Croquettes de lentilles et ricotta au poivron rouge', 'Croquetas de lentejas y ricota con pimiento rojo', 'Linsen-Ricotta-Kroketten mit roter Paprika', 'vegetable_mains', 'lunch', 12, 17, 7, 'baking', 'mendoza'),
  B('ar-phase-a-171', 'أقراص دورادو بالذرة والكزبرة', 'Dorado Cakes with Corn and Cilantro', 'Galettes de dorado au maïs et coriandre', 'Tortitas de dorado con maíz y cilantro', 'Doradenküchlein mit Mais und Koriander', 'fish_seafood', 'lunch', 19, 13, 6, 'pan_frying', 'corrientes'),
  B('ar-phase-a-172', 'بانكيك التفاح بدولسي دي ليتشي', 'Apple Panqueques with Dulce de Leche', 'Panqueques aux pommes et dulce de leche', 'Panqueques de manzana con dulce de leche', 'Apfel-Panqueques mit Dulce de Leche', 'breakfast_items', 'breakfast', 8, 29, 7, 'pan_frying', 'buenos_aires'),
  B('ar-phase-a-173', 'تارت ميرلوزا والكراث والريكوتا', 'Merluza, Leek and Ricotta Tart', 'Tarte de merluza, poireau et ricotta', 'Tarta de merluza, puerro y ricota', 'Merluza-Lauch-Ricotta-Tarte', 'fish_seafood', 'lunch', 16, 14, 8, 'baking', 'patagonia'),
  B('ar-phase-a-174', 'مالفاتي القرع والريكوتا بالمريمية', 'Squash and Ricotta Malfatti with Sage', 'Malfatti à la courge et ricotta à la sauge', 'Malfatti de zapallo y ricota con salvia', 'Kürbis-Ricotta-Malfatti mit Salbei', 'vegetable_mains', 'dinner', 12, 23, 7, 'boiling', 'cordoba'),
  B('ar-phase-a-175', 'مشروب الخروب بالحليب والقرفة', 'Carob Drink with Milk and Cinnamon', 'Boisson à la caroube, lait et cannelle', 'Bebida de algarroba con leche y canela', 'Johannisbrotgetränk mit Milch und Zimt', 'beverages', 'snack', 8, 16, 5, 'blending', 'cordoba'),
];
