import { B } from '../argentina-base-data/rows.mjs';

export default [
  B('ar-phase-a-014', 'إمبانادا دجاج أرجنتينية بالذرة والفلفل', 'Argentine Chicken Empanada with Corn and Pepper', 'Empanada argentine au poulet, maïs et poivron', 'Empanada argentina de pollo con maíz y pimiento', 'Argentinische Hähnchen-Empanada mit Mais und Paprika', 'street_snacks', 'lunch', 17, 21, 8, 'baking', 'tucuman'),
  B('ar-phase-a-015', 'بف لومي مع تشيميتشوري وبطاطس مشوية', 'Bife de Lomo with Chimichurri and Roast Potato', 'Bife de lomo au chimichurri et pommes de terre rôties', 'Bife de lomo con chimichurri y papa asada', 'Bife de Lomo mit Chimichurri und Ofenkartoffel', 'meat_mains', 'dinner', 24, 7, 12, 'grilling', 'buenos_aires'),
  B('ar-phase-a-016', 'سورينتينوس بالسبانخ والريكوتا وصلصة الطماطم', 'Spinach and Ricotta Sorrentinos with Tomato Sauce', 'Sorrentinos aux épinards et ricotta, sauce tomate', 'Sorrentinos de espinaca y ricota con salsa de tomate', 'Sorrentinos mit Spinat und Ricotta in Tomatensoße', 'vegetable_mains', 'dinner', 13, 25, 8, 'boiling', 'buenos_aires'),
  B('ar-phase-a-017', 'تورتيّا سانتياغينيا بالذرة والبيض والجبن', 'Santiagueña Corn, Egg and Cheese Tortilla', 'Tortilla santiagueña au maïs, œuf et fromage', 'Tortilla santiagueña de maíz, huevo y queso', 'Santiagueña-Maistortilla mit Ei und Käse', 'breakfast_items', 'breakfast', 13, 19, 8, 'griddling', 'santiago_del_estero'),
  B('ar-phase-a-018', 'تراوت باتاغوني مشوي بالليمون والأعشاب', 'Patagonian Trout with Lemon and Herbs', 'Truite de Patagonie au citron et aux herbes', 'Trucha patagónica con limón y hierbas', 'Patagonische Forelle mit Zitrone und Kräutern', 'fish_seafood', 'dinner', 21, 2, 8, 'grilling', 'patagonia'),
  B('ar-phase-a-019', 'يخنة عدس بلحم البقر والقرع', 'Beef and Squash Lentil Stew', 'Ragoût de lentilles au bœuf et courge', 'Guiso de lentejas con res y zapallo', 'Linseneintopf mit Rind und Kürbis', 'soups_stews', 'lunch', 14, 15, 6, 'simmering', 'mendoza'),
  B('ar-phase-a-020', 'ألفاخور نشا الذرة بحشوة دولسي دي ليتشي', 'Cornstarch Alfajor with Dulce de Leche', 'Alfajor à la fécule de maïs et dulce de leche', 'Alfajor de maicena con dulce de leche', 'Maisstärke-Alfajor mit Dulce de Leche', 'rice_cakes_sweets', 'snack', 6, 40, 11, 'baking', 'buenos_aires'),
  B('ar-phase-a-021', 'ماتي كوسيدو بالحليب والقرفة', 'Mate Cocido with Milk and Cinnamon', 'Mate cocido au lait et à la cannelle', 'Mate cocido con leche y canela', 'Mate Cocido mit Milch und Zimt', 'beverages', 'breakfast', 7, 8, 4, 'simmering', 'corrientes'),
  B('ar-phase-a-022', 'بيض مخفوق بالكوسا والريكوتا', 'Scrambled Eggs with Zucchini and Ricotta', 'Œufs brouillés aux courgettes et ricotta', 'Huevos revueltos con zapallitos y ricota', 'Rührei mit Zucchini und Ricotta', 'breakfast_items', 'breakfast', 13, 6, 10, 'sauteing', 'buenos_aires'),
  B('ar-phase-a-023', 'إمبانادا سالتينيا بلحم البقر والبطاطس', 'Salteña Beef and Potato Empanada', 'Empanada salteña au bœuf et pomme de terre', 'Empanada salteña de res y papa', 'Salteña-Empanada mit Rind und Kartoffel', 'street_snacks', 'lunch', 16, 19, 9, 'baking', 'salta'),
  B('ar-phase-a-024', 'بولينتا أرجنتينية بصلصة لحم البقر', 'Argentine Polenta with Beef Ragout', 'Polenta argentine au ragoût de bœuf', 'Polenta argentina con estofado de res', 'Argentinische Polenta mit Rinderragout', 'meat_mains', 'dinner', 16, 22, 8, 'simmering', 'mendoza'),
  B('ar-phase-a-025', 'كيسيو توكوماني بالعسل والجوز', 'Tucuman Quesillo with Honey and Walnuts', 'Quesillo tucumain au miel et noix', 'Quesillo tucumano con miel y nueces', 'Tucumán-Quesillo mit Honig und Walnüssen', 'breakfast_items', 'snack', 14, 12, 10, 'assembling', 'tucuman'),
];
