import { B } from '../argentina-base-data/rows.mjs';

export default [
  B('ar-phase-a-188', 'طاجن دجاج بالكابوتيا والكينوا', 'Chicken Cazuela with Cabutia and Quinoa', 'Cazuela de poulet à la cabutia et quinoa', 'Cazuela de pollo con cabutia y quinoa', 'Hähnchen-Cazuela mit Cabutia und Quinoa', 'poultry_mains', 'dinner', 17, 13, 6, 'simmering', 'corrientes'),
  B('ar-phase-a-189', 'بيف دي نالغا بتشيميتشوري البرتقال', 'Bife de Nalga with Orange Chimichurri', 'Bife de nalga au chimichurri à l’orange', 'Bife de nalga con chimichurri de naranja', 'Bife de Nalga mit Orangen-Chimichurri', 'meat_mains', 'dinner', 23, 4, 11, 'grilling', 'buenos_aires'),
  B('ar-phase-a-190', 'تارت ريكوتا وسفرجل أرجنتينية', 'Argentine Ricotta and Quince Tart', 'Tarte argentine à la ricotta et au coing', 'Tarta argentina de ricota y membrillo', 'Argentinische Ricotta-Quitten-Tarte', 'rice_cakes_sweets', 'snack', 10, 28, 8, 'baking', 'cordoba'),
  B('ar-phase-a-191', 'ميرلوزا بصلصة الطماطم والكبر والبطاطس', 'Merluza with Tomato, Caper and Potato Sauce', 'Merluza à la sauce tomate, câpres et pomme de terre', 'Merluza con salsa de tomate, alcaparras y papa', 'Merluza mit Tomaten-Kapern-Kartoffelsoße', 'fish_seafood', 'dinner', 20, 9, 7, 'braising', 'patagonia'),
  B('ar-phase-a-192', 'دجاج بخردل ديجون والأعشاب والكينوا', 'Chicken with Dijon Mustard, Herbs and Quinoa', 'Poulet à la moutarde de Dijon, herbes et quinoa', 'Pollo con mostaza de Dijon, hierbas y quinoa', 'Hähnchen mit Dijon-Senf, Kräutern und Quinoa', 'poultry_mains', 'dinner', 21, 9, 7, 'roasting', 'mendoza'),
  B('ar-phase-a-193', 'شوربة برغل بلحم البقر والخضار', 'Bulgur Soup with Beef and Vegetables', 'Soupe de boulgour au bœuf et légumes', 'Sopa de trigo burgol con res y verduras', 'Bulgursuppe mit Rindfleisch und Gemüse', 'soups_stews', 'lunch', 15, 14, 5, 'simmering', 'salta'),
  B('ar-phase-a-194', 'باستيلتوس محشو بدولسي دي باتاتا', 'Pastelitos Filled with Dulce de Batata', 'Pastelitos farcis au dulce de batata', 'Pastelitos rellenos de dulce de batata', 'Pastelitos gefüllt mit Dulce de Batata', 'rice_cakes_sweets', 'snack', 5, 36, 9, 'baking', 'buenos_aires'),
  B('ar-phase-a-195', 'صينية قرع بالريكوتا والبروفولوني', 'Squash Bake with Ricotta and Provolone', 'Gratin de courge à la ricotta et provoleta', 'Budín de zapallo con ricota y provolone', 'Kürbisauflauf mit Ricotta und Provolone', 'vegetable_mains', 'dinner', 12, 16, 8, 'baking', 'cordoba'),
  B('ar-phase-a-196', 'يخنة البازلاء والبيض والبطاطس بتشيميتشوري', 'Pea, Egg and Potato Stew with Chimichurri', 'Ragoût de pois, œuf et pomme de terre au chimichurri', 'Guiso de arvejas, huevo y papa con chimichurri', 'Erbsen-Ei-Kartoffel-Eintopf mit Chimichurri', 'vegetable_mains', 'lunch', 13, 15, 7, 'stewing', 'cordoba'),
  B('ar-phase-a-197', 'دورادو مشوي بالبولينتا والصلصة الخضراء', 'Grilled Dorado with Polenta and Green Sauce', 'Dorado grillé à la polenta et sauce verte', 'Dorado a la parrilla con polenta y salsa verde', 'Gegrillte Dorade mit Polenta und grüner Soße', 'fish_seafood', 'dinner', 21, 18, 8, 'grilling', 'corrientes'),
  B('ar-phase-a-198', 'يخنة لحم بقري بالقرع والكرنب الأجعد', 'Beef Stew with Squash and Kale', 'Ragoût de bœuf à la courge et au chou frisé', 'Guiso de res con zapallo y kale', 'Rindfleischeintopf mit Kürbis und Grünkohl', 'meat_mains', 'dinner', 18, 10, 8, 'stewing', 'chaco'),
  B('ar-phase-a-199', 'زبادي عالي البروتين بدولسي دي ليتشي وبذور الشيا', 'High-Protein Yogurt with Dulce de Leche and Chia', 'Yaourt protéiné au dulce de leche et chia', 'Yogur alto en proteína con dulce de leche y chía', 'Proteinreicher Joghurt mit Dulce de Leche und Chia', 'breakfast_items', 'breakfast', 15, 14, 5, 'assembling', 'buenos_aires'),
  B('ar-phase-a-200', 'آيس كريم دولسي دي ليتشي بالزبادي', 'Dulce de Leche Frozen Yogurt', 'Yaourt glacé au dulce de leche', 'Yogur helado de dulce de leche', 'Dulce-de-Leche-Frozen-Joghurt', 'rice_cakes_sweets', 'snack', 10, 22, 6, 'chilling', 'buenos_aires'),
];
