import { B } from '../argentina-base-data/rows.mjs';

export default [
  B('ar-phase-a-138', 'سمك دورادو مشوي بتشيميتشوري الأعشاب', 'Grilled Dorado with Herb Chimichurri', 'Dorado grillé au chimichurri aux herbes', 'Dorado a la parrilla con chimichurri de hierbas', 'Gegrillte Dorade mit Kräuter-Chimichurri', 'fish_seafood', 'dinner', 22, 3, 9, 'grilling', 'corrientes'),
  B('ar-phase-a-139', 'ميرلوزا مخبوزة بالكينوا والطماطم المشوية', 'Baked Merluza with Quinoa and Roasted Tomato', 'Merluza au four au quinoa et tomate rôtie', 'Merluza al horno con quinoa y tomate asado', 'Gebackene Merluza mit Quinoa und gerösteter Tomate', 'fish_seafood', 'lunch', 20, 12, 7, 'baking', 'patagonia'),
  B('ar-phase-a-140', 'تشوبين سمك النهر بالطماطم والبطاطس', 'River Fish Chupin with Tomato and Potato', 'Chupin de poisson de rivière à la tomate et pomme de terre', 'Chupín de pescado de río con tomate y papa', 'Flussfisch-Chupin mit Tomate und Kartoffel', 'fish_seafood', 'dinner', 19, 10, 6, 'simmering', 'corrientes'),
  B('ar-phase-a-141', 'شوربة القرع والريكوتا ببذور القرع', 'Squash and Ricotta Soup with Pumpkin Seeds', 'Soupe de courge et ricotta aux graines de courge', 'Sopa de zapallo y ricota con pepitas', 'Kürbis-Ricotta-Suppe mit Kürbiskernen', 'soups_stews', 'lunch', 10, 12, 6, 'simmering', 'cordoba'),
  B('ar-phase-a-142', 'شوربة كينوا بالدجاج والطماطم والزعتر', 'Chicken Quinoa Soup with Tomato and Thyme', 'Soupe de quinoa au poulet, tomate et thym', 'Sopa de quinoa con pollo, tomate y tomillo', 'Hühner-Quinoa-Suppe mit Tomate und Thymian', 'soups_stews', 'lunch', 15, 12, 5, 'simmering', 'mendoza'),
  B('ar-phase-a-143', 'كينوا مخبوزة بالفطر والجبن الطازج', 'Baked Quinoa with Mushrooms and Fresh Cheese', 'Quinoa au four aux champignons et fromage frais', 'Quinoa al horno con hongos y queso fresco', 'Gebackene Quinoa mit Pilzen und Frischkäse', 'vegetable_mains', 'dinner', 13, 20, 7, 'baking', 'mendoza'),
  B('ar-phase-a-144', 'تارت الفطر والريكوتا بالأوريغانو', 'Mushroom and Ricotta Tart with Oregano', 'Tarte aux champignons et ricotta à l’origan', 'Tarta de hongos y ricota con orégano', 'Pilz-Ricotta-Tarte mit Oregano', 'vegetable_mains', 'lunch', 12, 14, 8, 'baking', 'buenos_aires'),
  B('ar-phase-a-145', 'سلطة كالامار بالحمص وتشيميتشوري البقدونس', 'Calamari and Chickpea Salad with Parsley Chimichurri', 'Salade de calamars et pois chiches au chimichurri de persil', 'Ensalada de calamar y garbanzos con chimichurri de perejil', 'Tintenfisch-Kichererbsen-Salat mit Petersilien-Chimichurri', 'fish_seafood', 'lunch', 17, 14, 6, 'assembling', 'buenos_aires'),
  B('ar-phase-a-146', 'فلفل أحمر محشو بلحم البقر والعدس', 'Red Pepper Stuffed with Beef and Lentils', 'Poivron rouge farci au bœuf et lentilles', 'Pimiento rojo relleno de res y lentejas', 'Rote Paprika gefüllt mit Rind und Linsen', 'meat_mains', 'dinner', 17, 12, 8, 'baking', 'cordoba'),
  B('ar-phase-a-147', 'باكو مشوي بقشرة الذرة والليمون', 'Pacu with Cornmeal Crust and Lemon', 'Pacu en croûte de farine de maïs et citron', 'Pacú con costra de harina de maíz y limón', 'Pacu mit Maismehlkruste und Zitrone', 'fish_seafood', 'dinner', 21, 12, 9, 'baking', 'corrientes'),
  B('ar-phase-a-148', 'بانكيك الريكوتا بكومبوت السفرجل', 'Ricotta Panqueques with Quince Compote', 'Panqueques à la ricotta et compote de coing', 'Panqueques de ricota con compota de membrillo', 'Ricotta-Panqueques mit Quittenkompott', 'breakfast_items', 'breakfast', 11, 25, 8, 'pan_frying', 'buenos_aires'),
  B('ar-phase-a-149', 'سموذي الخوخ والزبادي والشوفان', 'Peach, Yogurt and Oat Smoothie', 'Smoothie à la pêche, au yaourt et à l’avoine', 'Batido de durazno, yogur y avena', 'Pfirsich-Joghurt-Hafer-Smoothie', 'beverages', 'breakfast', 9, 21, 4, 'blending', 'cordoba'),
  B('ar-phase-a-150', 'يخنة الدجاج والشعير والقرع بالأعشاب', 'Chicken, Barley and Squash Stew with Herbs', 'Ragoût de poulet, orge et courge aux herbes', 'Guiso de pollo, cebada y zapallo con hierbas', 'Hähnchen-Gerste-Kürbis-Eintopf mit Kräutern', 'poultry_mains', 'dinner', 15, 14, 5, 'simmering', 'corrientes'),
];
