import { B } from '../argentina-base-data/rows.mjs';

export default [
  B('ar-phase-a-114', 'ميرلوزا رومانا بالليمون والبقدونس', 'Merluza a la Romana with Lemon and Parsley', 'Merluza à la romaine au citron et persil', 'Merluza a la romana con limón y perejil', 'Merluza a la Romana mit Zitrone und Petersilie', 'fish_seafood', 'dinner', 20, 13, 8, 'pan_frying', 'buenos_aires'),
  B('ar-phase-a-115', 'بانكيك أرجنتيني محشو بدولسي دي ليتشي', 'Argentine Panqueques with Dulce de Leche', 'Panqueques argentins au dulce de leche', 'Panqueques argentinos con dulce de leche', 'Argentinische Panqueques mit Dulce de Leche', 'breakfast_items', 'breakfast', 9, 30, 8, 'pan_frying', 'buenos_aires'),
  B('ar-phase-a-116', 'مالفاتي السبانخ والريكوتا بصلصة الطماطم', 'Spinach and Ricotta Malfatti with Tomato Sauce', 'Malfatti aux épinards et ricotta, sauce tomate', 'Malfatti de espinaca y ricota con salsa de tomate', 'Spinat-Ricotta-Malfatti mit Tomatensoße', 'vegetable_mains', 'dinner', 14, 20, 8, 'boiling', 'buenos_aires'),
  B('ar-phase-a-117', 'يخنة أوسوبوكو لحم البقر بالفاصولياء البيضاء', 'Beef Osobuco Stew with White Beans', 'Ragoût d’osobuco de bœuf aux haricots blancs', 'Estofado de osobuco de res con alubias blancas', 'Rinder-Osobuco-Eintopf mit weißen Bohnen', 'meat_mains', 'dinner', 19, 10, 9, 'braising', 'mendoza'),
  B('ar-phase-a-118', 'بولينتا مشوية ببروفوليتا وصلصة الطماطم', 'Grilled Polenta with Provoleta and Tomato Sauce', 'Polenta grillée à la provoleta et sauce tomate', 'Polenta a la parrilla con provoleta y salsa de tomate', 'Gegrillte Polenta mit Provoleta und Tomatensoße', 'vegetable_mains', 'lunch', 14, 23, 10, 'grilling', 'buenos_aires'),
  B('ar-phase-a-119', 'شوربة كريمة القرع والكينوا بالزعتر', 'Squash and Quinoa Cream Soup with Thyme', 'Soupe crémeuse de courge et quinoa au thym', 'Crema de zapallo y quinoa con tomillo', 'Kürbis-Quinoa-Cremesuppe mit Thymian', 'soups_stews', 'lunch', 8, 17, 4, 'simmering', 'cordoba'),
  B('ar-phase-a-120', 'بيف دي كوستيّا بالبروفنسال والثوم', 'Bife de Costilla Provenzal with Garlic', 'Bife de costilla provenzal à l’ail', 'Bife de costilla provenzal con ajo', 'Bife de Costilla Provenzal mit Knoblauch', 'meat_mains', 'dinner', 23, 3, 15, 'grilling', 'mendoza'),
  B('ar-phase-a-121', 'بيونونو لحم البقر بالسبانخ والفلفل المشوي', 'Beef Pionono with Spinach and Roasted Pepper', 'Pionono de bœuf aux épinards et poivron rôti', 'Pionono de res con espinaca y pimiento asado', 'Rindfleisch-Pionono mit Spinat und gerösteter Paprika', 'meat_mains', 'lunch', 18, 14, 8, 'baking', 'buenos_aires'),
  B('ar-phase-a-122', 'تارت ميرلوزا بالسبانخ والريكوتا', 'Merluza Tart with Spinach and Ricotta', 'Tarte de merluza aux épinards et ricotta', 'Tarta de merluza con espinaca y ricota', 'Merluza-Tarte mit Spinat und Ricotta', 'fish_seafood', 'lunch', 17, 15, 7, 'baking', 'patagonia'),
  B('ar-phase-a-123', 'باستيل كينوا وعدس ببروفولوني', 'Quinoa and Lentil Pastel with Provolone', 'Pastel de quinoa et lentilles au provolone', 'Pastel de quinoa y lentejas con provolone', 'Quinoa-Linsen-Pastel mit Provolone', 'vegetable_mains', 'dinner', 14, 22, 8, 'baking', 'salta'),
  B('ar-phase-a-124', 'تشوكوتورتا أرجنتينية بدولسي دي ليتشي والجبن', 'Argentine Chocotorta with Dulce de Leche and Cheese', 'Chocotorta argentine au dulce de leche et fromage frais', 'Chocotorta argentina con dulce de leche y queso crema', 'Argentinische Chocotorta mit Dulce de Leche und Frischkäse', 'rice_cakes_sweets', 'snack', 8, 35, 12, 'chilling', 'buenos_aires'),
  B('ar-phase-a-125', 'أقراص تراوت باتاغوني بالبطاطس والأعشاب', 'Patagonian Trout Cakes with Potato and Herbs', 'Galettes de truite de Patagonie à la pomme de terre et herbes', 'Tortitas de trucha patagónica con papa y hierbas', 'Patagonische Forellenküchlein mit Kartoffel und Kräutern', 'fish_seafood', 'lunch', 18, 14, 7, 'pan_frying', 'patagonia'),
];
