import { B } from '../argentina-base-data/rows.mjs';

export default [
  B('ar-phase-a-038', 'إمبانادا عربية باللحم البقري والبصل والليمون', 'Argentine Arab Beef Empanada with Onion and Lemon', 'Empanada arabe argentine au bœuf, oignon et citron', 'Empanada árabe argentina de res con cebolla y limón', 'Argentinische arabische Rindfleisch-Empanada mit Zwiebel und Zitrone', 'street_snacks', 'lunch', 17, 18, 8, 'baking', 'tucuman'),
  B('ar-phase-a-039', 'بيف آ كابايو بالبيض والبطاطس', 'Bife a Caballo with Egg and Potato', 'Bife a caballo avec œuf et pomme de terre', 'Bife a caballo con huevo y papa', 'Bife a Caballo mit Ei und Kartoffel', 'meat_mains', 'dinner', 23, 9, 12, 'grilling', 'buenos_aires'),
  B('ar-phase-a-040', 'بوتشيرو كريولا بلحم البقر والحمص والخضار', 'Puchero Criollo with Beef, Chickpeas and Vegetables', 'Puchero criollo au bœuf, pois chiches et légumes', 'Puchero criollo de res con garbanzos y verduras', 'Puchero Criollo mit Rind, Kichererbsen und Gemüse', 'soups_stews', 'lunch', 16, 12, 7, 'simmering', 'cordoba'),
  B('ar-phase-a-041', 'تارت الكوسا بالبيض والريكوتا', 'Zucchini Tart with Egg and Ricotta', 'Tarte aux courgettes, œuf et ricotta', 'Tarta de zapallitos con huevo y ricota', 'Zucchini-Tarte mit Ei und Ricotta', 'vegetable_mains', 'lunch', 12, 13, 8, 'baking', 'buenos_aires'),
  B('ar-phase-a-042', 'ميلانيسا الصويا بتشيميتشوري الليمون', 'Soy Milanesa with Lemon Chimichurri', 'Milanesa de soja au chimichurri citronné', 'Milanesa de soja con chimichurri de limón', 'Soja-Milanesa mit Zitronen-Chimichurri', 'vegetable_mains', 'dinner', 17, 13, 7, 'baking', 'mendoza'),
  B('ar-phase-a-043', 'فلان أرجنتيني بدولسي دي ليتشي', 'Argentine Flan with Dulce de Leche', 'Flan argentin au dulce de leche', 'Flan argentino con dulce de leche', 'Argentinischer Flan mit Dulce de Leche', 'rice_cakes_sweets', 'snack', 8, 27, 7, 'baking', 'buenos_aires'),
  B('ar-phase-a-044', 'ريفيرو كورينتينو بالبيض والجبن', 'Corrientes Reviro with Egg and Cheese', 'Reviro de Corrientes à l’œuf et au fromage', 'Reviro correntino con huevo y queso', 'Reviro aus Corrientes mit Ei und Käse', 'breakfast_items', 'breakfast', 12, 24, 8, 'pan_frying', 'corrientes'),
  B('ar-phase-a-045', 'تشيبّا ميسيونيس بجبن بروفولوني', 'Misiones Chipa with Provolone Cheese', 'Chipa de Misiones au provolone', 'Chipa misionera con queso provolone', 'Chipa aus Misiones mit Provolone', 'street_snacks', 'snack', 13, 25, 10, 'baking', 'misiones'),
  B('ar-phase-a-046', 'باكو مشوي بالطماطم والفلفل', 'Grilled Pacu with Tomato and Pepper', 'Pacu grillé à la tomate et au poivron', 'Pacú a la parrilla con tomate y pimiento', 'Gegrillter Pacu mit Tomate und Paprika', 'fish_seafood', 'dinner', 21, 4, 9, 'grilling', 'corrientes'),
  B('ar-phase-a-047', 'يخنة لحم الضأن باتاغوني بالقرع والفاصولياء', 'Patagonian Lamb Stew with Squash and Beans', 'Ragoût d’agneau patagonien à la courge et aux haricots', 'Guiso patagónico de cordero con zapallo y frijoles', 'Patagonischer Lammeintopf mit Kürbis und Bohnen', 'meat_mains', 'dinner', 18, 10, 9, 'stewing', 'patagonia'),
  B('ar-phase-a-048', 'شوربة كينوا بالدجاج والسبانخ', 'Quinoa Soup with Chicken and Spinach', 'Soupe de quinoa au poulet et épinards', 'Sopa de quinoa con pollo y espinaca', 'Quinoasuppe mit Hähnchen und Spinat', 'soups_stews', 'lunch', 14, 12, 4, 'simmering', 'salta'),
  B('ar-phase-a-049', 'تورتا فريتا بالقرع ودولسي دي ليتشي', 'Torta Frita with Squash and Dulce de Leche', 'Torta frita à la courge et dulce de leche', 'Torta frita con zapallo y dulce de leche', 'Torta Frita mit Kürbis und Dulce de Leche', 'rice_cakes_sweets', 'snack', 6, 35, 10, 'pan_frying', 'corrientes'),
  B('ar-phase-a-050', 'أرز بالحليب ودولسي دي ليتشي', 'Argentine Rice Pudding with Dulce de Leche', 'Riz au lait argentin au dulce de leche', 'Arroz con leche argentino y dulce de leche', 'Argentinischer Milchreis mit Dulce de Leche', 'rice_cakes_sweets', 'snack', 7, 28, 6, 'simmering', 'buenos_aires'),
];
