// Vietnamese expansion part 5 of 15: meat_mains rows 1-18 of 200.
// All dishes are distinct from the base 100 and parts 1-4.
import { R, T } from './rows.mjs';

export default [
  R(`لحم مقلي بالثوم والبصل بالزنجبيل ${T}`, 'Ginger stir-fried beef with onions and garlic', 'Boeuf frit gingembre oignons ail', 'Buey salteado jengibre cebolla ajo', 'Gebratenes Rindfleisch mit Ingwer Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 17, 7, 11),
  R(`لحم مقلي بالثوم والبصل بالثوم ${T}`, 'Garlic stir-fried beef with onions and garlic', 'Boeuf frit ail oignons ail', 'Buey salteado ajo cebolla ajo', 'Gebratenes Rindfleisch mit Knoblauch Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 16, 8, 10),
  R(`لحم مقلي بالثوم والبصل بالبصل ${T}`, 'Onion stir-fried beef with onions and garlic', 'Boeuf frit oignon oignons ail', 'Buey salteado cebolla cebolla ajo', 'Gebratenes Rindfleisch mit Zwiebel Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 17, 6, 11),
  R(`لحم مقلي بالثوم والبصل بالكزبرة ${T}`, 'Cilantro stir-fried beef with onions and garlic', 'Boeuf frit coriandre oignons ail', 'Buey salteado cilantro cebolla ajo', 'Gebratenes Rindfleisch mit Koriander Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 16, 7, 10),
  R(`لحم مقلي بالثوم والبصل بالليمون ${T}`, 'Lemon stir-fried beef with onions and garlic', 'Boeuf frit citron oignons ail', 'Buey salteado limón cebolla ajo', 'Gebratenes Rindfleisch mit Zitrone Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 17, 6, 11),
  R(`لحم مقلي بالثوم والبصل بالفلفل ${T}`, 'Pepper stir-fried beef with onions and garlic', 'Boeuf frit poivre oignons ail', 'Buey salteado pimienta cebolla ajo', 'Gebratenes Rindfleisch mit Pfeffer Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 16, 7, 10),
  R(`لحم مقلي بالثوم والبصل بالكاري ${T}`, 'Curry stir-fried beef with onions and garlic', 'Boeuf frit curry oignons ail', 'Buey salteado curry cebolla ajo', 'Gebratenes Rindfleisch mit Curry Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 17, 8, 11),
  R(`لحم مقلي بالثوم والبصل بالطماطم ${T}`, 'Tomato stir-fried beef with onions and garlic', 'Boeuf frit tomate oignons ail', 'Buey salteado tomate cebolla ajo', 'Gebratenes Rindfleisch mit Tomate Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 16, 9, 10),
  R(`لحم مقلي بالثوم والبصل بالفطر ${T}`, 'Mushroom stir-fried beef with onions and garlic', 'Boeuf frit champignons oignons ail', 'Buey salteado hongos cebolla ajo', 'Gebratenes Rindfleisch mit Pilzen Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 17, 7, 11),
  R(`لحم مقلي بالثوم والبصل بالذرة ${T}`, 'Corn stir-fried beef with onions and garlic', 'Boeuf frit mais oignons ail', 'Buey salteado maíz cebolla ajo', 'Gebratenes Rindfleisch mit Mais Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 16, 8, 10),
  R(`لحم مقلي بالثوم والبصل بالبطاطس ${T}`, 'Potato stir-fried beef with onions and garlic', 'Boeuf frit pomme de terre oignons ail', 'Buey salteado papa cebolla ajo', 'Gebratenes Rindfleisch mit Kartoffel Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 17, 6, 11),
  R(`لحم مقلي بالثوم والبصل بالجزر ${T}`, 'Carrot stir-fried beef with onions and garlic', 'Boeuf frit carotte oignons ail', 'Buey salteado zanahoria cebolla ajo', 'Gebratenes Rindfleisch mit Karotte Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 16, 7, 10),
  R(`لحم مقلي بالثوم والبصل بالسبانخ ${T}`, 'Spinach stir-fried beef with onions and garlic', 'Boeuf frit epinards oignons ail', 'Buey salteado espinacas cebolla ajo', 'Gebratenes Rindfleisch mit Spinat Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 17, 6, 11),
  R(`لحم مقلي بالثوم والبصل بالبروكلي ${T}`, 'Broccoli stir-fried beef with onions and garlic', 'Boeuf frit brocoli oignons ail', 'Buey salteado brócoli cebolla ajo', 'Gebratenes Rindfleisch mit Brokkoli Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 16, 7, 10),
  R(`لحم مقلي بالثوم والبصل بالبازلاء ${T}`, 'Pea stir-fried beef with onions and garlic', 'Boeuf frit petits pois oignons ail', 'Buey salteado guisantes cebolla ajo', 'Gebratenes Rindfleisch mit Erbsen Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 17, 8, 11),
  R(`لحم مقلي بالثوم والبصل بالخضار المشكلة ${T}`, 'Mixed vegetable stir-fried beef with onions and garlic', 'Boeuf frit legumes varies oignons ail', 'Buey salteado verduras mixtas cebolla ajo', 'Gebratenes Rindfleisch mit gemischtem Gemüse Zwiebeln Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 16, 9, 10),
  R(`لحم بافلو بالزنجبيل ${T}`, 'Ginger buffalo stew', 'Stew de buffle gingembre', 'Estofado de búfalo con jengibre', 'Büffelstew mit Ingwer', 'meat_mains', 'dinner', 'pan_vietnamese', 15, 9, 10),
  R(`لحم بافلو بالثوم ${T}`, 'Garlic buffalo stew', 'Stew de buffle ail', 'Estofado de búfalo con ajo', 'Büffelstew mit Knoblauch', 'meat_mains', 'dinner', 'pan_vietnamese', 14, 10, 9),
];
