import { B } from './rows.mjs';

export default [
  B('mx-phase-a-101', 'لحم بقري بمرق التوماتيو وفاصولياء بينتو', 'Beef in Tomatillo and Pinto Bean Broth', 'Bœuf au bouillon de tomatilles et haricots pinto', 'Res en caldo de tomatillo y frijoles pintos', 'Rindfleisch in Tomatillo-Pintobohnen-Brühe', 'meat_mains', 'lunch', 17, 9, 7, 'simmering', 'jalisco'),
  B('mx-phase-a-102', 'تشيلاتولي أخضر بالدجاج والذرة', 'Green Chicken and Corn Chileatole', 'Chileatole vert au poulet et au maïs', 'Chileatole verde de pollo y maíz', 'Grünes Chileatole mit Hähnchen und Mais', 'soups_stews', 'lunch', 14, 12, 5, 'simmering', 'veracruz'),
  B('mx-phase-a-103', 'كالاباسيتاس بالذرة والفاصولياء وجبن بانلا', 'Calabacitas with Corn, Beans and Panela', 'Calabacitas au maïs, haricots et panela', 'Calabacitas con maíz, frijoles y panela', 'Calabacitas mit Mais, Bohnen und Panela', 'vegetable_mains', 'lunch', 12, 14, 7, 'sauteing', 'central_mexico'),
  B('mx-phase-a-104', 'سمك تيكين شيك بالبرتقال الحامض والأشيوت', 'Tikin Xic Fish with Sour Orange and Achiote', 'Poisson tikin xic à l’orange amère et à l’achiote', 'Pescado tikin xic con naranja agria y achiote', 'Tikin-Xic-Fisch mit Bitterorange und Achiote', 'fish_seafood', 'dinner', 21, 3, 8, 'grilling', 'yucatan'),
  B('mx-phase-a-105', 'إنفريخولادا بالبيض وجبن كوتيخا', 'Enfrijoladas with Egg and Cotija Cheese', 'Enfrijoladas à l’œuf et au fromage cotija', 'Enfrijoladas con huevo y queso cotija', 'Enfrijoladas mit Ei und Cotija-Käse', 'breakfast_items', 'breakfast', 14, 20, 8, 'simmering', 'central_mexico'),
  B('mx-phase-a-106', 'دجاج إنكاكاهواتادو بالفول السوداني والفلفل', 'Chicken Encacahuatado with Peanuts and Chile', 'Poulet encacahuatado aux cacahuètes et piment', 'Pollo encacahuatado con cacahuate y chile', 'Encacahuatado-Hähnchen mit Erdnüssen und Chili', 'poultry_mains', 'dinner', 21, 7, 12, 'braising', 'puebla'),
  B('mx-phase-a-107', 'توستادا سالبيكون لحم البقر بالجيكاما والفجل', 'Beef Salpicon Tostada with Jicama and Radish', 'Tostada de salpicon de bœuf à la jicama et au radis', 'Tostada de salpicón de res con jícama y rábano', 'Rindfleisch-Salpicon-Tostada mit Jicama und Rettich', 'meat_mains', 'lunch', 19, 12, 7, 'assembling', 'pan_mexican'),
  B('mx-phase-a-108', 'روبيان بموخو دي أخو والليمون', 'Garlic Shrimp with Lime', 'Crevettes à l’ail et au citron vert', 'Camarones al mojo de ajo con lima', 'Knoblauchgarnelen mit Limette', 'fish_seafood', 'dinner', 19, 3, 6, 'sauteing', 'veracruz'),
  B('mx-phase-a-109', 'إنتوماتادا بجبن كيسو فريسكو', 'Entomatadas with Queso Fresco', 'Entomatadas au queso fresco', 'Entomatadas con queso fresco', 'Entomatadas mit Queso Fresco', 'vegetable_mains', 'lunch', 12, 22, 8, 'simmering', 'central_mexico'),
  B('mx-phase-a-110', 'غارناتشا فيراكروز بالديك الرومي والفاصولياء', 'Veracruz Garnacha with Turkey and Beans', 'Garnacha de Veracruz à la dinde et aux haricots', 'Garnacha veracruzana de pavo y frijoles', 'Veracruz-Garnacha mit Pute und Bohnen', 'street_snacks', 'snack', 15, 20, 7, 'griddling', 'veracruz'),
  B('mx-phase-a-111', 'نوبال مطهو بالحمص والبيض والطماطم', 'Nopales Stew with Chickpeas, Egg and Tomato', 'Ragoût de nopales aux pois chiches, œuf et tomate', 'Guiso de nopales con garbanzos, huevo y tomate', 'Nopales-Eintopf mit Kichererbsen, Ei und Tomate', 'vegetable_mains', 'lunch', 11, 13, 6, 'stewing', 'central_mexico'),
  B('mx-phase-a-112', 'شايوتي محشو بلحم البقر والذرة', 'Chayote Stuffed with Beef and Corn', 'Chayotte farcie au bœuf et au maïs', 'Chayote relleno de res y maíz', 'Chayote gefüllt mit Rindfleisch und Mais', 'meat_mains', 'dinner', 15, 9, 7, 'baking', 'chiapas'),
  B('mx-phase-a-113', 'تامال تشيبيلين بجبن بانلا', 'Chipilin Tamal with Panela Cheese', 'Tamal au chipilin et fromage panela', 'Tamal de chipilín con queso panela', 'Chipilin-Tamal mit Panela-Käse', 'street_snacks', 'lunch', 11, 22, 7, 'steaming', 'chiapas'),
];
