import { B } from './rows.mjs';

export default [
  B('mx-phase-a-251', 'بانوتش يوكاتاني بالبيض وتشايا', 'Yucatecan Panucho with Egg and Chaya', 'Panucho yucatèque à l’œuf et chaya', 'Panucho yucateco con huevo y chaya', 'Yucatekischer Panucho mit Ei und Chaya', 'breakfast_items', 'breakfast', 13, 19, 8, 'griddling', 'yucatan'),
  B('mx-phase-a-252', 'شوربة كالدّو دي أوسو دورانغينيو بالسمك والذرة', 'Durango Caldo de Oso with Fish and Corn', 'Caldo de oso de Durango au poisson et maïs', 'Caldo de oso durangueño con pescado y maíz', 'Durango-Caldo-de-Oso mit Fisch und Mais', 'fish_seafood', 'lunch', 18, 10, 5, 'simmering', 'northern_mexico'),
  B('mx-phase-a-253', 'سمك تاباسكو بفلفل أماشيتو والطماطم', 'Tabasco Fish with Amashito Chile and Tomato', 'Poisson du Tabasco au piment amashito et tomate', 'Pescado tabasqueño con chile amashito y tomate', 'Tabasco-Fisch mit Amashito-Chili und Tomate', 'fish_seafood', 'dinner', 20, 6, 7, 'braising', 'veracruz'),
  B('mx-phase-a-254', 'أتباكوا دجاج بالشايوتي والذرة', 'Chicken Atapakua with Chayote and Corn', 'Atapakua de poulet à la chayotte et au maïs', 'Atapakua de pollo con chayote y maíz', 'Hähnchen-Atapakua mit Chayote und Mais', 'poultry_mains', 'dinner', 19, 9, 8, 'stewing', 'jalisco'),
  B('mx-phase-a-255', 'باكالاو فيزكاينا بالبطاطس والزيتون', 'Bacalao a la Vizcaina with Potato and Olives', 'Bacalao a la vizcaína aux pommes de terre et olives', 'Bacalao a la vizcaína con papa y aceitunas', 'Bacalao a la Vizcaina mit Kartoffeln und Oliven', 'fish_seafood', 'dinner', 19, 9, 8, 'braising', 'veracruz'),
  B('mx-phase-a-256', 'سمك بصلصة تشيلتيبين وبذور القرع', 'Fish with Chiltepin Chile and Pumpkin Seeds', 'Poisson au piment chiltepin et graines de courge', 'Pescado con chile chiltepín y pepitas', 'Fisch mit Chiltepin-Chili und Kürbiskernen', 'fish_seafood', 'dinner', 20, 6, 8, 'braising', 'northern_mexico'),
  B('mx-phase-a-257', 'لحم بقري بفلفل تشيلاكا والفطر', 'Beef with Chilaca Chile and Mushrooms', 'Bœuf au piment chilaca et champignons', 'Res con chile chilaca y hongos', 'Rindfleisch mit Chilaca-Chili und Pilzen', 'meat_mains', 'dinner', 20, 7, 8, 'stewing', 'northern_mexico'),
  B('mx-phase-a-258', 'تامال دجاج بصلصة رajas وجبن بانلا', 'Chicken Tamal with Rajas and Panela Cheese', 'Tamal au poulet, rajas et fromage panela', 'Tamal de pollo con rajas y queso panela', 'Hähnchen-Tamal mit Rajas und Panela-Käse', 'street_snacks', 'lunch', 15, 22, 7, 'steaming', 'central_mexico'),
  B('mx-phase-a-259', 'بوتشيرو يوكاتاني بلحم البقر والحمص والقرع', 'Yucatecan Beef Puchero with Chickpeas and Squash', 'Puchero yucatèque au bœuf, pois chiches et courge', 'Puchero yucateco de res con garbanzos y calabaza', 'Yucatekischer Rindfleisch-Puchero mit Kichererbsen und Kürbis', 'soups_stews', 'lunch', 16, 11, 7, 'simmering', 'yucatan'),
  B('mx-phase-a-260', 'دجاج بصلصة كاسكابيل وزوكونوستلي', 'Chicken with Cascabel Chile and Xoconostle Sauce', 'Poulet à la sauce cascabel et xoconostle', 'Pollo en salsa de cascabel y xoconostle', 'Hähnchen mit Cascabel-Xoconostle-Soße', 'poultry_mains', 'dinner', 21, 7, 8, 'braising', 'central_mexico'),
  B('mx-phase-a-261', 'فلفل كوارسيمينيو محشو بجبن بانلا والذرة', 'Cuaresmeño Chile Stuffed with Panela and Corn', 'Piment cuaresmeño farci au panela et maïs', 'Chile cuaresmeño relleno de panela y maíz', 'Cuaresmeño-Chili gefüllt mit Panela und Mais', 'vegetable_mains', 'lunch', 12, 9, 8, 'roasting', 'central_mexico'),
  B('mx-phase-a-262', 'أقراص بطاطس بالشاراليس والفلفل الأخضر', 'Potato Cakes with Charales and Green Chile', 'Galettes de pommes de terre aux charales et piment vert', 'Tortitas de papa con charales y chile verde', 'Kartoffelküchlein mit Charales und grünem Chili', 'fish_seafood', 'lunch', 16, 17, 7, 'pan_frying', 'jalisco'),
  B('mx-phase-a-263', 'باذنجان أواكساكي مشوي بجبن بانلا وفلفل', 'Oaxacan Charred Eggplant with Panela and Chile', 'Aubergine oaxaquienne grillée au panela et piment', 'Berenjena oaxaqueña tatemada con panela y chile', 'Oaxacanische Aubergine mit Panela und Chili', 'vegetable_mains', 'lunch', 11, 10, 7, 'roasting', 'oaxaca'),
];
