import { B } from './rows.mjs';

export default [
  B('mx-phase-a-176', 'فاصولياء مانيداس بجبن أواكساكا', 'Frijoles Maneados with Oaxaca Cheese', 'Frijoles maneados au fromage d’Oaxaca', 'Frijoles maneados con queso Oaxaca', 'Frijoles Maneados mit Oaxaca-Käse', 'vegetable_mains', 'side', 11, 16, 7, 'stewing', 'northern_mexico'),
  B('mx-phase-a-177', 'مكستلابيكي سمك بالذرة والأعشاب', 'Mextlapique Fish with Corn and Herbs', 'Mextlapique de poisson au maïs et aux herbes', 'Mextlapique de pescado con maíz y hierbas', 'Mextlapique-Fisch mit Mais und Kräutern', 'fish_seafood', 'dinner', 19, 8, 6, 'steaming', 'central_mexico'),
  B('mx-phase-a-178', 'بيض إنكاميسادوس بالتورتيلا والفاصولياء', 'Huevos Encamisados with Tortilla and Beans', 'Huevos encamisados à la tortilla et aux haricots', 'Huevos encamisados con tortilla y frijoles', 'Huevos Encamisados mit Tortilla und Bohnen', 'breakfast_items', 'breakfast', 14, 15, 9, 'pan_frying', 'central_mexico'),
  B('mx-phase-a-179', 'دجاج بصلصة باسيا والشايوتي', 'Chicken with Pasilla Chile and Chayote Sauce', 'Poulet à la sauce pasilla et chayotte', 'Pollo en salsa de pasilla y chayote', 'Hähnchen mit Pasilla-Chili-Chayote-Soße', 'poultry_mains', 'dinner', 21, 7, 8, 'braising', 'puebla'),
  B('mx-phase-a-180', 'نوبال محشو بجبن أواكساكا وصلصة الطماطم', 'Nopal Stuffed with Oaxaca Cheese and Tomato Salsa', 'Nopal farci au fromage d’Oaxaca et salsa tomate', 'Nopal relleno de queso Oaxaca y salsa de tomate', 'Nopal gefüllt mit Oaxaca-Käse und Tomatensalsa', 'vegetable_mains', 'lunch', 14, 8, 8, 'grilling', 'central_mexico'),
  B('mx-phase-a-181', 'روبيان أ لا ديابلا بالطماطم وفلفل تشيلي', 'Camarones a la Diabla with Tomato and Chile', 'Camarones a la diabla à la tomate et au piment', 'Camarones a la diabla con tomate y chile', 'Camarones a la Diabla mit Tomate und Chili', 'fish_seafood', 'dinner', 19, 6, 7, 'sauteing', 'veracruz'),
  B('mx-phase-a-182', 'سلطة كيليتس بالفاصولياء السوداء وجبن بانلا', 'Quelites Salad with Black Beans and Panela', 'Salade de quelites aux haricots noirs et panela', 'Ensalada de quelites con frijoles negros y panela', 'Quelites-Salat mit schwarzen Bohnen und Panela', 'salads', 'lunch', 11, 14, 7, 'assembling', 'chiapas'),
  B('mx-phase-a-183', 'يخنة خضار كيليتس بالفاصولياء والذرة', 'Quelites Stew with Beans and Corn', 'Ragoût de quelites aux haricots et maïs', 'Guiso de quelites con frijoles y maíz', 'Quelites-Eintopf mit Bohnen und Mais', 'vegetable_mains', 'lunch', 9, 17, 4, 'stewing', 'chiapas'),
  B('mx-phase-a-184', 'شوربة سمك بالإبيزوتي والفلفل الأخضر', 'Fish Soup with Epazote and Green Chile', 'Soupe de poisson à l’épazote et piment vert', 'Sopa de pescado con epazote y chile verde', 'Fischsuppe mit Epazote und grünem Chili', 'fish_seafood', 'lunch', 18, 7, 4, 'simmering', 'veracruz'),
  B('mx-phase-a-185', 'سمك بصلصة كريمة بوبلانو والذرة', 'Fish with Poblano Cream Sauce and Corn', 'Poisson à la crème de poblano et au maïs', 'Pescado con crema de poblano y maíz', 'Fisch mit Poblano-Rahmsoße und Mais', 'fish_seafood', 'dinner', 20, 9, 8, 'braising', 'puebla'),
  B('mx-phase-a-186', 'سمك بالفلفل بوبلانو والفاصولياء السوداء', 'Fish with Poblano Chile and Black Beans', 'Poisson au piment poblano et haricots noirs', 'Pescado con chile poblano y frijoles negros', 'Fisch mit Poblano-Chili und schwarzen Bohnen', 'fish_seafood', 'dinner', 20, 10, 7, 'braising', 'puebla'),
  B('mx-phase-a-187', 'قرع محشو بالديك الرومي وزهر القرع', 'Squash Stuffed with Turkey and Squash Blossom', 'Courge farcie à la dinde et fleur de courge', 'Calabaza rellena de pavo y flor de calabaza', 'Kürbis gefüllt mit Pute und Kürbisblüte', 'poultry_mains', 'dinner', 17, 9, 6, 'baking', 'central_mexico'),
];
