import { B } from './rows.mjs';

export default [
  B('mx-phase-a-026', 'دجاج موليه أخضر ببذور القرع', 'Chicken Mole Verde with Pumpkin Seeds', 'Poulet au mole verde et graines de courge', 'Pollo con mole verde y pepitas', 'Hähnchen mit Mole Verde und Kürbiskernen', 'poultry_mains', 'dinner', 20, 8, 9, 'simmering', 'puebla'),
  B('mx-phase-a-027', 'فاصولياء دي أولا بالإبيزوتي والطماطم', 'Frijoles de Olla with Epazote and Tomato', 'Frijoles de olla à l’épazote et tomate', 'Frijoles de olla con epazote y tomate', 'Frijoles de Olla mit Epazote und Tomate', 'vegetable_mains', 'side', 8, 15, 2, 'simmering', 'oaxaca'),
  B('mx-phase-a-028', 'توستادا سيفيتشي سمك بالليمون والطماطم', 'Fish Ceviche Tostada with Lime and Tomato', 'Tostada de ceviche de poisson au citron vert et tomate', 'Tostada de ceviche de pescado con lima y tomate', 'Fisch-Ceviche-Tostada mit Limette und Tomate', 'fish_seafood', 'lunch', 17, 12, 3, 'marinating', 'veracruz'),
  B('mx-phase-a-029', 'تاكو لسان البقر بالبصل والكزبرة', 'Beef Tongue Tacos with Onion and Cilantro', 'Tacos de langue de bœuf à l’oignon et coriandre', 'Tacos de lengua de res con cebolla y cilantro', 'Rinderzungen-Tacos mit Zwiebel und Koriander', 'meat_mains', 'dinner', 19, 13, 10, 'braising', 'jalisco'),
  B('mx-phase-a-030', 'سمك مشوي على طريقة ناياريت بالليمون', 'Nayarit-Style Grilled Fish with Lime', 'Poisson grillé façon Nayarit au citron vert', 'Pescado zarandeado estilo Nayarit con lima', 'Gegrillter Fisch nach Nayarit-Art mit Limette', 'fish_seafood', 'dinner', 21, 3, 7, 'grilling', 'jalisco'),
  B('mx-phase-a-031', 'سوبس دجاج بالفاصولياء والصلصة الحمراء', 'Chicken Sopes with Beans and Red Salsa', 'Sopes au poulet, haricots et salsa rouge', 'Sopes de pollo con frijoles y salsa roja', 'Sopes mit Hähnchen, Bohnen und roter Salsa', 'street_snacks', 'lunch', 16, 18, 6, 'griddling', 'central_mexico'),
  B('mx-phase-a-032', 'شوربة لحم البقر بالخضار والذرة', 'Beef Vegetable and Corn Caldo', 'Caldo de bœuf aux légumes et maïs', 'Caldo de res con verduras y maíz', 'Rinder-Caldo mit Gemüse und Mais', 'soups_stews', 'lunch', 13, 9, 5, 'simmering', 'northern_mexico'),
  B('mx-phase-a-033', 'هاراتشي نوبال بالفاصولياء وجبن طازج', 'Nopal Huarache with Beans and Fresh Cheese', 'Huarache de nopal aux haricots et fromage frais', 'Huarache de nopal con frijoles y queso fresco', 'Nopal-Huarache mit Bohnen und Frischkäse', 'vegetable_mains', 'lunch', 11, 20, 6, 'griddling', 'central_mexico'),
  B('mx-phase-a-034', 'بيريا لحم البقر بمرق الفلفل الحار', 'Beef Birria in Chile Broth', 'Birria de bœuf au bouillon de piments', 'Birria de res en caldo de chiles', 'Rinder-Birria in Chili-Brühe', 'meat_mains', 'dinner', 21, 4, 10, 'slow_braising', 'jalisco'),
  B('mx-phase-a-035', 'عجة بيض مكسيكية بالفاصولياء والأفوكادو', 'Mexican Egg Omelet with Beans and Avocado', 'Omelette mexicaine aux haricots et avocat', 'Omelet mexicano con frijoles y aguacate', 'Mexikanisches Omelett mit Bohnen und Avocado', 'breakfast_items', 'breakfast', 13, 8, 11, 'pan_frying', 'pan_mexican'),
  B('mx-phase-a-036', 'شوربة روبيان بالطماطم والذرة', 'Shrimp Soup with Tomato and Corn', 'Soupe de crevettes à la tomate et au maïs', 'Sopa de camarón con tomate y maíz', 'Garnelensuppe mit Tomate und Mais', 'fish_seafood', 'lunch', 15, 8, 3, 'simmering', 'veracruz'),
  B('mx-phase-a-037', 'سلطة فول تيباري بالفلفل والطماطم', 'Tépari Bean Salad with Chile and Tomato', 'Salade de haricots tépari au piment et tomate', 'Ensalada de frijol tépari con chile y tomate', 'Tépari-Bohnensalat mit Chili und Tomate', 'salads', 'lunch', 9, 17, 4, 'simmering', 'northern_mexico'),
];
