import { B } from './rows.mjs';

export default [
  B('mx-phase-a-051', 'تلايودا أواكساكية بالفاصولياء ولحم البقر', 'Oaxacan Tlayuda with Beans and Beef', 'Tlayuda oaxaqueña aux haricots et bœuf', 'Tlayuda oaxaqueña con frijoles y res', 'Oaxacanische Tlayuda mit Bohnen und Rindfleisch', 'meat_mains', 'dinner', 19, 22, 9, 'griddling', 'oaxaca'),
  B('mx-phase-a-052', 'وعاء دجاج بيبيل بالبرتقال المر', 'Chicken Pibil Bowl with Bitter Orange', 'Bol de poulet pibil à l’orange amère', 'Tazón de pollo pibil con naranja agria', 'Hähnchen-Pibil-Schale mit Bitterorange', 'poultry_mains', 'lunch', 21, 12, 6, 'slow_roasting', 'yucatan'),
  B('mx-phase-a-053', 'شوربة عدس ونوبال بالطماطم', 'Lentil and Nopal Tomato Soup', 'Soupe de lentilles et nopales à la tomate', 'Sopa de lentejas y nopales con tomate', 'Linsen-Nopales-Suppe mit Tomate', 'soups_stews', 'lunch', 9, 15, 3, 'simmering', 'chiapas'),
  B('mx-phase-a-054', 'إسكيتيس بالدجاج والذرة والفلفل', 'Chicken Esquites with Corn and Chile', 'Esquites au poulet, maïs et piment', 'Esquites de pollo con maíz y chile', 'Hähnchen-Esquites mit Mais und Chili', 'street_snacks', 'snack', 15, 14, 6, 'sauteing', 'central_mexico'),
  B('mx-phase-a-055', 'بيض بالنوبال والفاصولياء الحمراء', 'Eggs with Nopales and Pinto Beans', 'Œufs aux nopales et haricots pinto', 'Huevos con nopales y frijoles pintos', 'Eier mit Nopales und Pintobohnen', 'breakfast_items', 'breakfast', 13, 11, 9, 'sauteing', 'pan_mexican'),
  B('mx-phase-a-056', 'أفوكادو محشو بروبيان فيراكروز', 'Veracruz Shrimp-Stuffed Avocado', 'Avocat farci aux crevettes façon Veracruz', 'Aguacate relleno de camarón estilo Veracruz', 'Mit Garnelen gefüllte Avocado nach Veracruz-Art', 'fish_seafood', 'lunch', 16, 7, 10, 'assembling', 'veracruz'),
  B('mx-phase-a-057', 'لحم بقري أواكساكي بفلفل باسيا', 'Oaxacan Beef with Pasilla Chile', 'Bœuf façon Oaxaca au piment pasilla', 'Res oaxaqueña con chile pasilla', 'Oaxacanisches Rindfleisch mit Pasilla-Chili', 'meat_mains', 'dinner', 21, 6, 9, 'stewing', 'oaxaca'),
  B('mx-phase-a-058', 'تامال أواكساكي بالفاصولياء السوداء', 'Oaxacan Tamal with Black Beans', 'Tamal d’Oaxaca aux haricots noirs', 'Tamal oaxaqueño con frijoles negros', 'Oaxacanischer Tamal mit schwarzen Bohnen', 'street_snacks', 'lunch', 10, 24, 6, 'steaming', 'oaxaca'),
  B('mx-phase-a-059', 'شوربة سمك بالليمون والكزبرة', 'Fish Soup with Lime and Cilantro', 'Soupe de poisson au citron vert et coriandre', 'Sopa de pescado con lima y cilantro', 'Fischsuppe mit Limette und Koriander', 'fish_seafood', 'lunch', 18, 7, 4, 'simmering', 'veracruz'),
  B('mx-phase-a-060', 'بيكاديو ديك رومي بالشايوتي والطماطم', 'Turkey Picadillo with Chayote and Tomato', 'Picadillo de dinde à la chayotte et tomate', 'Picadillo de pavo con chayote y tomate', 'Puten-Picadillo mit Chayote und Tomate', 'poultry_mains', 'dinner', 18, 9, 7, 'stewing', 'central_mexico'),
  B('mx-phase-a-061', 'دجاج بالفلفل الأخضر وجبن بانلا', 'Chicken with Green Chile and Panela Cheese', 'Poulet au piment vert et fromage panela', 'Pollo con chile verde y queso panela', 'Hähnchen mit grünem Chili und Panela-Käse', 'poultry_mains', 'dinner', 21, 5, 8, 'braising', 'jalisco'),
  B('mx-phase-a-062', 'وعاء أرز بني وفاصولياء سوداء بالذرة', 'Brown Rice and Black Bean Bowl with Corn', 'Bol de riz complet et haricots noirs au maïs', 'Tazón de arroz integral y frijoles negros con maíz', 'Schale mit Vollkornreis, schwarzen Bohnen und Mais', 'vegetable_mains', 'lunch', 9, 27, 5, 'simmering', 'chiapas'),
  B('mx-phase-a-063', 'ماشاكا لحم البقر بالبيض والفلفل', 'Beef Machaca with Eggs and Peppers', 'Machaca de bœuf aux œufs et poivrons', 'Machaca de res con huevo y pimientos', 'Rindfleisch-Machaca mit Ei und Paprika', 'breakfast_items', 'breakfast', 20, 5, 11, 'sauteing', 'northern_mexico'),
];
