import { B } from './rows.mjs';

export default [
  B('mx-phase-a-001', 'توستادا دجاج تينغا مكسيكية', 'Mexican Chicken Tinga Tostada', 'Tostada mexicaine au poulet tinga', 'Tostada mexicana de pollo tinga', 'Mexikanische Chicken-Tinga-Tostada', 'poultry_mains', 'lunch', 17, 19, 7, 'braising', 'central_mexico'),
  B('mx-phase-a-002', 'بيض مكسيكي بالطماطم والفلفل', 'Mexican Eggs with Tomato and Chile', 'Œufs mexicains à la tomate et au piment', 'Huevos mexicanos con tomate y chile', 'Mexikanische Eier mit Tomate und Chili', 'breakfast_items', 'breakfast', 12, 5, 9, 'sauteing', 'pan_mexican'),
  B('mx-phase-a-003', 'تلاكيو الذرة بالفاصولياء السوداء والنوبال', 'Corn Tlacoyo with Black Beans and Nopales', 'Tlacoyo de maïs aux haricots noirs et nopales', 'Tlacoyo de maíz con frijoles negros y nopales', 'Mais-Tlacoyo mit schwarzen Bohnen und Nopales', 'street_snacks', 'snack', 9, 28, 4, 'griddling', 'central_mexico'),
  B('mx-phase-a-004', 'شوربة تلالبينيو بالدجاج والحمص', 'Tlalpeño Chicken and Chickpea Soup', 'Soupe tlalpeño au poulet et aux pois chiches', 'Sopa tlalpeña de pollo y garbanzos', 'Tlalpeño-Suppe mit Hähnchen und Kichererbsen', 'soups_stews', 'lunch', 13, 7, 4, 'simmering', 'central_mexico'),
  B('mx-phase-a-005', 'تاكو بارباكوا بلحم البقر', 'Beef Barbacoa Tacos', 'Tacos de barbacoa de bœuf', 'Tacos de barbacoa de res', 'Rindfleisch-Barbacoa-Tacos', 'meat_mains', 'dinner', 20, 12, 8, 'slow_roasting', 'central_mexico'),
  B('mx-phase-a-006', 'إنشيلادا خضراء بالدجاج وصلصة التوماتيو', 'Chicken Enchiladas Verdes with Tomatillo Salsa', 'Enchiladas verdes au poulet et tomatilles', 'Enchiladas verdes de pollo con tomatillo', 'Grüne Hähnchen-Enchiladas mit Tomatillo-Salsa', 'poultry_mains', 'dinner', 18, 16, 8, 'baking', 'central_mexico'),
  B('mx-phase-a-007', 'سلطة نوبال بالبيض والطماطم', 'Nopal Salad with Egg and Tomato', 'Salade de nopales aux œufs et à la tomate', 'Ensalada de nopales con huevo y tomate', 'Nopales-Salat mit Ei und Tomate', 'salads', 'lunch', 9, 6, 7, 'boiling', 'pan_mexican'),
  B('mx-phase-a-008', 'شوربة الفاصولياء السوداء بالإبيزوتي', 'Black Bean and Epazote Soup', 'Soupe de haricots noirs à l’épazote', 'Sopa de frijoles negros con epazote', 'Schwarze-Bohnen-Suppe mit Epazote', 'soups_stews', 'lunch', 8, 15, 3, 'simmering', 'oaxaca'),
  B('mx-phase-a-009', 'سمك فيراكروز بالطماطم والزيتون', 'Veracruz-Style Fish with Tomato and Olives', 'Poisson à la veracruzana, tomate et olives', 'Pescado a la veracruzana con tomate y aceitunas', 'Fisch nach Veracruz-Art mit Tomate und Oliven', 'fish_seafood', 'dinner', 20, 5, 7, 'braising', 'veracruz'),
  B('mx-phase-a-010', 'دجاج موليه بوبلانو ببذور القرع', 'Chicken Mole Poblano with Pumpkin Seeds', 'Poulet au mole poblano et graines de courge', 'Pollo con mole poblano y pepitas', 'Hähnchen mit Mole Poblano und Kürbiskernen', 'poultry_mains', 'dinner', 19, 11, 9, 'simmering', 'puebla'),
  B('mx-phase-a-011', 'إسكيتيس الذرة والفاصولياء وجبن بانلا', 'Esquites with Beans and Panela Cheese', 'Esquites aux haricots et fromage panela', 'Esquites con frijoles y queso panela', 'Esquites mit Bohnen und Panela-Käse', 'street_snacks', 'snack', 10, 17, 6, 'sauteing', 'central_mexico'),
  B('mx-phase-a-012', 'بيكاديو لحم البقر بالطماطم والبطاطس', 'Beef Picadillo with Tomato and Potato', 'Picadillo de bœuf à la tomate et pomme de terre', 'Picadillo de res con tomate y papa', 'Rinder-Picadillo mit Tomate und Kartoffel', 'meat_mains', 'dinner', 17, 10, 8, 'stewing', 'pan_mexican'),
  B('mx-phase-a-013', 'تشيلكيلس خضراء بالدجاج والفاصولياء', 'Green Chilaquiles with Chicken and Beans', 'Chilaquiles verts au poulet et haricots', 'Chilaquiles verdes con pollo y frijoles', 'Grüne Chilaquiles mit Hähnchen und Bohnen', 'breakfast_items', 'breakfast', 16, 18, 7, 'simmering', 'central_mexico'),
];
