import { B } from './rows.mjs';

export default [
  B('mx-phase-a-126', 'تورتاس هواوزونتلي بصلصة الطماطم', 'Huauzontle Patties in Tomato Sauce', 'Galettes de huauzontle à la sauce tomate', 'Tortitas de huauzontle en salsa de tomate', 'Huauzontle-Bratlinge in Tomatensoße', 'vegetable_mains', 'lunch', 13, 10, 7, 'pan_frying', 'puebla'),
  B('mx-phase-a-127', 'طبق تامبيكينيا بلحم البقر والفاصولياء', 'Tampiqueña Beef with Beans and Poblano', 'Bœuf à la tampiqueña, haricots et poblano', 'Tampiqueña de res con frijoles y poblano', 'Tampiqueña-Rindfleisch mit Bohnen und Poblano', 'meat_mains', 'dinner', 22, 11, 10, 'grilling', 'northern_mexico'),
  B('mx-phase-a-128', 'سمك كالدّو دي بيدرا بالأفوكادو والطماطم', 'Caldo de Piedra Fish with Avocado and Tomato', 'Caldo de piedra au poisson, avocat et tomate', 'Caldo de piedra de pescado con aguacate y tomate', 'Caldo de Piedra mit Fisch, Avocado und Tomate', 'fish_seafood', 'lunch', 18, 6, 5, 'simmering', 'oaxaca'),
  B('mx-phase-a-129', 'دجاج إسكابيشي شرقي من يوكاتان', 'Yucatan-Style Eastern Chicken Escabeche', 'Escabèche orientale de poulet du Yucatán', 'Escabeche oriental de pollo yucateco', 'Östliches Hähnchen-Escabeche aus Yucatán', 'poultry_mains', 'dinner', 20, 5, 8, 'braising', 'yucatan'),
  B('mx-phase-a-130', 'تيتيلا أواكساكية بالفاصولياء وبذور القرع', 'Oaxacan Tetela with Beans and Pumpkin Seeds', 'Tetela oaxaqueña aux haricots et graines de courge', 'Tetela oaxaqueña con frijoles y pepitas', 'Oaxacanische Tetela mit Bohnen und Kürbiskernen', 'street_snacks', 'lunch', 11, 23, 7, 'griddling', 'oaxaca'),
  B('mx-phase-a-131', 'شوربة الفطر والفول العريض بالأعشاب', 'Mushroom and Fava Bean Soup with Herbs', 'Soupe de champignons et fèves aux herbes', 'Sopa de hongos y habas con hierbas', 'Pilz-Brechbohnensuppe mit Kräutern', 'soups_stews', 'lunch', 9, 13, 4, 'simmering', 'central_mexico'),
  B('mx-phase-a-132', 'فلفل بوبلانو محشو بلحم البقر والجوز والرمان', 'Poblano Chile Stuffed with Beef, Walnut and Pomegranate', 'Piment poblano farci au bœuf, noix et grenade', 'Chile poblano relleno de res, nuez y granada', 'Poblano-Chili gefüllt mit Rindfleisch, Walnuss und Granatapfel', 'meat_mains', 'dinner', 17, 14, 11, 'baking', 'puebla'),
  B('mx-phase-a-133', 'أرز فيراكروز بالمأكولات البحرية والطماطم', 'Veracruz Seafood Rice with Tomato', 'Riz de Veracruz aux fruits de mer et tomate', 'Arroz a la tumbada veracruzano con tomate', 'Veracruz-Meeresfrüchtereis mit Tomate', 'fish_seafood', 'dinner', 16, 20, 6, 'simmering', 'veracruz'),
  B('mx-phase-a-134', 'بيض بزهر القرع والإبيزوتي', 'Eggs with Squash Blossom and Epazote', 'Œufs aux fleurs de courge et épazote', 'Huevos con flor de calabaza y epazote', 'Eier mit Kürbisblüte und Epazote', 'breakfast_items', 'breakfast', 13, 5, 10, 'sauteing', 'central_mexico'),
  B('mx-phase-a-135', 'كالديو دورانغينيو بلحم البقر والفلفل الأخضر', 'Durango Beef Caldillo with Green Chile', 'Caldillo de bœuf de Durango au piment vert', 'Caldillo durangueño de res con chile verde', 'Durango-Rinder-Caldillo mit grünem Chili', 'soups_stews', 'lunch', 16, 8, 7, 'simmering', 'northern_mexico'),
  B('mx-phase-a-136', 'ديك رومي ميكسيّوت بالنوبال وفلفل غواخيو', 'Turkey Mixiote with Nopales and Guajillo Chile', 'Mixiote de dinde aux nopales et piment guajillo', 'Mixiote de pavo con nopales y chile guajillo', 'Puten-Mixiote mit Nopales und Guajillo-Chili', 'poultry_mains', 'dinner', 21, 5, 7, 'steaming', 'central_mexico'),
  B('mx-phase-a-137', 'سوبس زهر القرع بجبن أواكساكا', 'Squash Blossom Sopes with Oaxaca Cheese', 'Sopes aux fleurs de courge et fromage d’Oaxaca', 'Sopes de flor de calabaza con queso Oaxaca', 'Sopes mit Kürbisblüte und Oaxaca-Käse', 'street_snacks', 'snack', 11, 20, 7, 'griddling', 'central_mexico'),
];
