import { B } from './rows.mjs';

export default [
  B('mx-phase-a-276', 'تاتيمادو كوليما بلحم البقر والطماطم', 'Colima Beef Tatemado with Tomato', 'Tatemado de Colima au bœuf et tomate', 'Tatemado colimense de res con tomate', 'Colima-Rindfleisch-Tatemado mit Tomate', 'meat_mains', 'dinner', 20, 8, 9, 'slow_braising', 'central_mexico'),
  B('mx-phase-a-277', 'مرق سمك بالفلفل الأنشو وزهر القرع', 'Fish Broth with Ancho Chile and Squash Blossom', 'Bouillon de poisson au piment ancho et fleur de courge', 'Caldo de pescado con chile ancho y flor de calabaza', 'Fischbrühe mit Ancho-Chili und Kürbisblüte', 'fish_seafood', 'lunch', 18, 8, 5, 'simmering', 'veracruz'),
  B('mx-phase-a-278', 'يخنة ديك رومي بالفاصولياء الخضراء وزوكونوستلي', 'Turkey Stew with Green Beans and Xoconostle', 'Ragoût de dinde aux haricots verts et xoconostle', 'Guiso de pavo con ejotes y xoconostle', 'Puteneintopf mit grünen Bohnen und Xoconostle', 'poultry_mains', 'dinner', 20, 8, 7, 'stewing', 'central_mexico'),
  B('mx-phase-a-279', 'لحم بقري بصلصة الفلفل كوستينيو والنوبال', 'Beef with Costeño Chile Sauce and Nopales', 'Bœuf à la sauce costeño et nopales', 'Res en salsa de chile costeño con nopales', 'Rindfleisch mit Costeño-Chilisoße und Nopales', 'meat_mains', 'dinner', 20, 7, 8, 'braising', 'oaxaca'),
  B('mx-phase-a-280', 'باذنجان محشو بهويتلاكوتشي وجبن بانلا', 'Eggplant Stuffed with Huitlacoche and Panela', 'Aubergine farcie au huitlacoche et panela', 'Berenjena rellena de huitlacoche y panela', 'Aubergine gefüllt mit Huitlacoche und Panela', 'vegetable_mains', 'dinner', 13, 9, 8, 'baking', 'central_mexico'),
  B('mx-phase-a-281', 'إمبانادا كاسون بالبطاطس والفلفل', 'Cazon Empanada with Potato and Chile', 'Empanada de cazón à la pomme de terre et piment', 'Empanada de cazón con papa y chile', 'Cazon-Empanada mit Kartoffel und Chili', 'street_snacks', 'lunch', 17, 21, 8, 'baking', 'veracruz'),
  B('mx-phase-a-282', 'روبيان بصلصة أكويو والثوم والليمون', 'Shrimp with Acuyo, Garlic and Lime', 'Crevettes à l’acuyo, ail et citron vert', 'Camarones con acuyo, ajo y lima', 'Garnelen mit Acuyo, Knoblauch und Limette', 'fish_seafood', 'dinner', 19, 4, 6, 'sauteing', 'veracruz'),
  B('mx-phase-a-283', 'كالديو بوبلانو بالدجاج والذرة المحمصة', 'Poblano Chicken Caldillo with Charred Corn', 'Caldillo poblano au poulet et maïs grillé', 'Caldillo poblano de pollo con maíz tatemado', 'Poblano-Hähnchen-Caldillo mit geröstetem Mais', 'poultry_mains', 'lunch', 16, 10, 6, 'simmering', 'puebla'),
  B('mx-phase-a-284', 'لحم بقري بصلصة أنشو وبذور السمسم', 'Beef with Ancho Chile and Sesame Sauce', 'Bœuf à la sauce ancho et sésame', 'Res con salsa de chile ancho y ajonjolí', 'Rindfleisch mit Ancho-Chili-Sesamsoße', 'meat_mains', 'dinner', 21, 6, 9, 'braising', 'puebla'),
  B('mx-phase-a-285', 'نوبال مطهو بالشايا وجبن بانلا', 'Nopales Stewed with Chaya and Panela', 'Nopales mijotés à la chaya et panela', 'Nopales guisados con chaya y panela', 'Geschmorte Nopales mit Chaya und Panela', 'vegetable_mains', 'lunch', 11, 10, 6, 'stewing', 'yucatan'),
  B('mx-phase-a-286', 'بيض مخبوز بفلفل كاسكابيل وجبن أواكساكا', 'Baked Eggs with Cascabel Chile and Oaxaca Cheese', 'Œufs au four au cascabel et fromage d’Oaxaca', 'Huevos al horno con chile cascabel y queso Oaxaca', 'Ofeneier mit Cascabel-Chili und Oaxaca-Käse', 'breakfast_items', 'breakfast', 14, 6, 10, 'baking', 'central_mexico'),
  B('mx-phase-a-287', 'بيض مكسيكي بالفطر والسبانخ والفاصولياء', 'Mexican Eggs with Mushrooms, Spinach and Beans', 'Œufs mexicains aux champignons, épinards et haricots', 'Huevos mexicanos con hongos, espinaca y frijoles', 'Mexikanische Eier mit Pilzen, Spinat und Bohnen', 'breakfast_items', 'breakfast', 14, 8, 9, 'sauteing', 'central_mexico'),
];
