import { B } from './rows.mjs';

export default [
  B('mx-phase-a-226', 'ديك رومي بصلصة كساتيك والفاصولياء البيضاء', 'Turkey with Xcatik Chile and White Beans', 'Dinde au piment xcatik et haricots blancs', 'Pavo con chile xcatik y frijoles blancos', 'Pute mit Xcatik-Chili und weißen Bohnen', 'poultry_mains', 'dinner', 20, 9, 7, 'braising', 'yucatan'),
  B('mx-phase-a-227', 'سمك بصلصة الفلفل باسيا وبذور القرع', 'Fish with Pasilla Chile and Pumpkin Seed Sauce', 'Poisson à la sauce pasilla et graines de courge', 'Pescado con salsa de pasilla y pepitas', 'Fisch mit Pasilla-Chili-Kürbiskernsoße', 'fish_seafood', 'dinner', 20, 7, 8, 'braising', 'central_mexico'),
  B('mx-phase-a-228', 'شوربة الفاصولياء الخضراء بجبن بانلا', 'Green Bean Soup with Panela Cheese', 'Soupe de haricots verts au fromage panela', 'Sopa de ejotes con queso panela', 'Grüne-Bohnen-Suppe mit Panela-Käse', 'soups_stews', 'lunch', 10, 12, 5, 'simmering', 'central_mexico'),
  B('mx-phase-a-229', 'بوريتو ماشاكا اللحم بالأفوكادو والفاصولياء', 'Beef Machaca Burrito with Avocado and Beans', 'Burrito de machaca de bœuf à l’avocat et haricots', 'Burrito de machaca de res con aguacate y frijoles', 'Rindfleisch-Machaca-Burrito mit Avocado und Bohnen', 'meat_mains', 'lunch', 20, 22, 10, 'griddling', 'northern_mexico'),
  B('mx-phase-a-230', 'تاكو كيليتس بجبن بانلا وصلصة الطماطم الخضراء', 'Quelites Tacos with Panela and Green Tomatillo Salsa', 'Tacos de quelites au panela et salsa verte de tomatilles', 'Tacos de quelites con panela y salsa verde de tomatillo', 'Quelites-Tacos mit Panela und grüner Tomatillo-Salsa', 'street_snacks', 'lunch', 12, 19, 7, 'griddling', 'oaxaca'),
  B('mx-phase-a-231', 'سيفيتشي إسكالوب بالخيار والفلفل الأخضر', 'Scallop Ceviche with Cucumber and Green Chile', 'Ceviche de pétoncles au concombre et piment vert', 'Ceviche de callo de hacha con pepino y chile verde', 'Jakobsmuschel-Ceviche mit Gurke und grünem Chili', 'fish_seafood', 'lunch', 18, 6, 2, 'marinating', 'baja_california'),
  B('mx-phase-a-232', 'لحم بقري بصلصة غواخيو والفيردولاغاس', 'Beef with Guajillo Chile and Purslane', 'Bœuf au guajillo et pourpier', 'Res con chile guajillo y verdolagas', 'Rindfleisch mit Guajillo-Chili und Portulak', 'meat_mains', 'dinner', 20, 7, 8, 'stewing', 'northern_mexico'),
  B('mx-phase-a-233', 'فلفل كابون محشو بجبن بانلا والفاصولياء', 'Chile Capon Stuffed with Panela and Beans', 'Piment capon farci au panela et haricots', 'Chile capón relleno de panela y frijoles', 'Capon-Chili gefüllt mit Panela und Bohnen', 'vegetable_mains', 'lunch', 13, 10, 8, 'roasting', 'central_mexico'),
  B('mx-phase-a-234', 'كريمة الشايوتي بجبن القريش وبذور القرع', 'Chayote Cream with Cottage Cheese and Pumpkin Seeds', 'Crème de chayotte au fromage frais et graines de courge', 'Crema de chayote con requesón y pepitas', 'Chayotecreme mit Hüttenkäse und Kürbiskernen', 'soups_stews', 'lunch', 12, 10, 7, 'simmering', 'chiapas'),
  B('mx-phase-a-235', 'تشالوبا بوبلانا بلحم البقر والصلصة', 'Poblano Beef Chalupas with Salsa', 'Chalupas poblanas au bœuf et salsa', 'Chalupas poblanas de res con salsa', 'Poblano-Chalupas mit Rindfleisch und Salsa', 'street_snacks', 'lunch', 17, 20, 8, 'griddling', 'puebla'),
  B('mx-phase-a-236', 'تشايا مطهوة بالطماطم والذرة وجبن بانلا', 'Chaya Stewed with Tomato, Corn and Panela', 'Chaya mijotée à la tomate, maïs et panela', 'Chaya guisada con tomate, maíz y panela', 'Geschmorte Chaya mit Tomate, Mais und Panela', 'vegetable_mains', 'lunch', 11, 12, 6, 'stewing', 'yucatan'),
  B('mx-phase-a-237', 'ديك رومي ببيبيان أبيض باللوز والسمسم', 'Turkey in White Pipian with Almond and Sesame', 'Dinde au pipian blanc, amandes et sésame', 'Pavo en pipián blanco con almendra y ajonjolí', 'Pute in weißem Pipián mit Mandel und Sesam', 'poultry_mains', 'dinner', 21, 6, 11, 'braising', 'puebla'),
];
