import { B } from './rows.mjs';

export default [
  B('mx-phase-a-151', 'دجاج تشيلاخو بالثوم والبرتقال الحامض', 'Yucatecan Chicken Chileajo with Sour Orange', 'Chileajo yucatèque de poulet à l’orange amère', 'Chileajo yucateco de pollo con naranja agria', 'Yucatekisches Chileajo-Hähnchen mit Bitterorange', 'poultry_mains', 'dinner', 21, 5, 8, 'braising', 'yucatan'),
  B('mx-phase-a-152', 'بيض مطلقان بصلصتي الطماطم الخضراء والحمراء', 'Huevos Divorciados with Green and Red Salsa', 'Huevos divorciados aux salsas verte et rouge', 'Huevos divorciados con salsa verde y roja', 'Huevos Divorciados mit grüner und roter Salsa', 'breakfast_items', 'breakfast', 13, 8, 10, 'pan_frying', 'central_mexico'),
  B('mx-phase-a-153', 'موليه دي أولا بلحم البقر والذرة', 'Beef Mole de Olla with Corn', 'Mole de olla au bœuf et au maïs', 'Mole de olla de res con maíz', 'Rindfleisch-Mole de Olla mit Mais', 'soups_stews', 'lunch', 16, 9, 8, 'simmering', 'central_mexico'),
  B('mx-phase-a-154', 'شوربة تاراسكا بالفاصولياء بينتو وفلفل أنشو', 'Tarascan Pinto Bean Soup with Ancho Chile', 'Soupe tarasque de haricots pinto au piment ancho', 'Sopa tarasca de frijol pinto con chile ancho', 'Taraskische Pintobohnensuppe mit Ancho-Chili', 'soups_stews', 'lunch', 9, 15, 5, 'simmering', 'jalisco'),
  B('mx-phase-a-155', 'تامال زاكاويل بالدجاج والفاصولياء السوداء', 'Zacahuil Tamal with Chicken and Black Beans', 'Tamal zacahuil au poulet et haricots noirs', 'Tamal zacahuil de pollo y frijoles negros', 'Zacahuil-Tamal mit Hähnchen und schwarzen Bohnen', 'street_snacks', 'lunch', 15, 24, 7, 'steaming', 'veracruz'),
  B('mx-phase-a-156', 'سيسينا هواستيكا بالفاصولياء والأفوكادو', 'Huasteca Cecina with Beans and Avocado', 'Cecina huastèque aux haricots et avocat', 'Cecina huasteca con frijoles y aguacate', 'Huasteca-Cecina mit Bohnen und Avocado', 'meat_mains', 'dinner', 23, 8, 9, 'grilling', 'veracruz'),
  B('mx-phase-a-157', 'تاكو رأس البقر بالبصل والكزبرة', 'Beef Head Tacos with Onion and Cilantro', 'Tacos de tête de bœuf à l’oignon et coriandre', 'Tacos de cabeza de res con cebolla y cilantro', 'Rinderkopffleisch-Tacos mit Zwiebel und Koriander', 'meat_mains', 'dinner', 19, 12, 9, 'steaming', 'central_mexico'),
  B('mx-phase-a-158', 'موليتيس بالفاصولياء السوداء وجبن بانلا', 'Molletes with Black Beans and Panela Cheese', 'Molletes aux haricots noirs et fromage panela', 'Molletes con frijoles negros y queso panela', 'Molletes mit schwarzen Bohnen und Panela-Käse', 'breakfast_items', 'breakfast', 14, 23, 8, 'baking', 'central_mexico'),
  B('mx-phase-a-159', 'إمبانادا دجاج بصلصة أماريلو الأواكساكية', 'Oaxacan Chicken Empanada with Amarillo Sauce', 'Empanada oaxaqueña au poulet et sauce amarillo', 'Empanada oaxaqueña de pollo con salsa amarillo', 'Oaxacanische Hähnchen-Empanada mit Amarillo-Soße', 'street_snacks', 'lunch', 16, 22, 8, 'baking', 'oaxaca'),
  B('mx-phase-a-160', 'ديك رومي بوك تشوك بالبرتقال الحامض', 'Turkey Poc Chuc with Sour Orange', 'Poc chuc de dinde à l’orange amère', 'Poc chuc de pavo con naranja agria', 'Puten-Poc-Chuc mit Bitterorange', 'poultry_mains', 'dinner', 22, 4, 7, 'grilling', 'yucatan'),
  B('mx-phase-a-161', 'سمك مطهو بأوراق أكويو وصلصة الليمون', 'Fish Braised with Acuyo Leaves and Lime Sauce', 'Poisson braisé aux feuilles d’acuyo et sauce au citron vert', 'Pescado guisado con hoja de acuyo y salsa de lima', 'Fisch mit Acuyo-Blättern und Limettensoße geschmort', 'fish_seafood', 'dinner', 20, 4, 7, 'braising', 'veracruz'),
  B('mx-phase-a-162', 'سيكيل باك ببذور القرع مع شرائح الديك الرومي', 'Sikil Pak Pumpkin Seed Dip with Turkey Slices', 'Sikil pak aux graines de courge et tranches de dinde', 'Sikil pak de pepita con rebanadas de pavo', 'Sikil Pak mit Kürbiskernen und Putenscheiben', 'poultry_mains', 'lunch', 18, 8, 11, 'assembling', 'yucatan'),
  B('mx-phase-a-163', 'نوبال مطهو بلحم البقر وفلفل كولورادو', 'Nopales Stewed with Beef and Chile Colorado', 'Nopales mijotés au bœuf et piment colorado', 'Nopales guisados con res y chile colorado', 'Geschmorte Nopales mit Rindfleisch und Colorado-Chili', 'meat_mains', 'dinner', 18, 8, 8, 'stewing', 'northern_mexico'),
];
