import { B } from './rows.mjs';

export default [
  B('mx-phase-a-201', 'جبن محشو يوكاتاني بلحم البقر والزيتون', 'Yucatecan Queso Relleno with Beef and Olives', 'Queso relleno yucatèque au bœuf et aux olives', 'Queso relleno yucateco de res y aceitunas', 'Yucatekischer Queso Relleno mit Rindfleisch und Oliven', 'meat_mains', 'dinner', 18, 8, 12, 'braising', 'yucatan'),
  B('mx-phase-a-202', 'بيض تشايا بالطماطم والبصل', 'Eggs with Chaya, Tomato and Onion', 'Œufs à la chaya, tomate et oignon', 'Huevos con chaya, tomate y cebolla', 'Eier mit Chaya, Tomate und Zwiebel', 'breakfast_items', 'breakfast', 13, 6, 9, 'sauteing', 'yucatan'),
  B('mx-phase-a-203', 'شوربة غواياس بالذرة وجبن بانلا', 'Sopa de Guias with Corn and Panela', 'Sopa de guias au maïs et panela', 'Sopa de guías con maíz y panela', 'Sopa de Guias mit Mais und Panela', 'soups_stews', 'lunch', 10, 12, 5, 'simmering', 'oaxaca'),
  B('mx-phase-a-204', 'سيميتا بوبلانا بلحم البقر والأفوكادو', 'Poblano Cemita with Beef and Avocado', 'Cemita poblana au bœuf et avocat', 'Cemita poblana de res y aguacate', 'Poblano-Cemita mit Rindfleisch und Avocado', 'street_snacks', 'lunch', 20, 23, 10, 'baking', 'puebla'),
  B('mx-phase-a-205', 'ماشاكا السمك بالبيض والطماطم', 'Fish Machaca with Eggs and Tomato', 'Machaca de poisson aux œufs et tomate', 'Machaca de pescado con huevo y tomate', 'Fisch-Machaca mit Ei und Tomate', 'fish_seafood', 'breakfast', 19, 5, 9, 'sauteing', 'baja_california'),
  B('mx-phase-a-206', 'إمبانادا أواكساكية بزهر القرع وجبن أواكساكا', 'Oaxacan Empanada with Squash Blossom and Oaxaca Cheese', 'Empanada oaxaqueña à la fleur de courge et fromage d’Oaxaca', 'Empanada oaxaqueña de flor de calabaza y queso Oaxaca', 'Oaxacanische Empanada mit Kürbisblüte und Oaxaca-Käse', 'street_snacks', 'snack', 12, 24, 8, 'baking', 'oaxaca'),
  B('mx-phase-a-207', 'لحم بقري زاكاتيكانو بالفلفل الأنشو والبطاطس', 'Zacatecan Beef with Ancho Chile and Potatoes', 'Bœuf zacatecano au piment ancho et pommes de terre', 'Res zacatecana con chile ancho y papas', 'Zacatecanisches Rindfleisch mit Ancho-Chili und Kartoffeln', 'meat_mains', 'dinner', 19, 10, 9, 'stewing', 'northern_mexico'),
  B('mx-phase-a-208', 'روبيان بجوز الهند والفلفل الحار', 'Coconut Shrimp with Chile', 'Crevettes à la noix de coco et au piment', 'Camarones al coco con chile', 'Kokosgarnelen mit Chili', 'fish_seafood', 'dinner', 18, 9, 8, 'pan_frying', 'veracruz'),
  B('mx-phase-a-209', 'إنشيلادا منيرا بالدجاج والبطاطس والجزر', 'Mineras Enchiladas with Chicken, Potato and Carrot', 'Enchiladas mineras au poulet, pomme de terre et carotte', 'Enchiladas mineras de pollo con papa y zanahoria', 'Mineras-Enchiladas mit Hähnchen, Kartoffel und Karotte', 'poultry_mains', 'dinner', 16, 18, 8, 'baking', 'central_mexico'),
  B('mx-phase-a-210', 'ديك رومي بصلصة تشايا وبذور القرع', 'Turkey with Chaya and Pumpkin Seed Sauce', 'Dinde à la chaya et sauce aux graines de courge', 'Pavo con chaya y salsa de pepita', 'Pute mit Chaya und Kürbiskernsoße', 'poultry_mains', 'dinner', 21, 6, 10, 'braising', 'yucatan'),
  B('mx-phase-a-211', 'فلفل كساتيك محشو بلحم البقر والذرة', 'Xcatik Chile Stuffed with Beef and Corn', 'Piment xcatik farci au bœuf et maïs', 'Chile xcatik relleno de res y maíz', 'Xcatik-Chili gefüllt mit Rindfleisch und Mais', 'meat_mains', 'dinner', 17, 11, 8, 'roasting', 'yucatan'),
  B('mx-phase-a-212', 'أقراص فاصولياء بينتو بجبن كوتيخا والإبيزوتي', 'Pinto Bean Patties with Cotija and Epazote', 'Galettes de haricots pinto au cotija et épazote', 'Tortitas de frijol pinto con cotija y epazote', 'Pintobohnen-Bratlinge mit Cotija und Epazote', 'vegetable_mains', 'lunch', 12, 18, 7, 'pan_frying', 'central_mexico'),
  B('mx-phase-a-213', 'شوربة جبن سونورا بالبطاطس والفلفل الأخضر', 'Sonoran Cheese Soup with Potato and Green Chile', 'Soupe au fromage sonorienne, pomme de terre et piment vert', 'Caldo de queso sonorense con papa y chile verde', 'Sonorische Käsesuppe mit Kartoffel und grünem Chili', 'soups_stews', 'lunch', 12, 9, 8, 'simmering', 'northern_mexico'),
];
