import { B } from './rows.mjs';

export default [
  B('mx-phase-a-076', 'بوزولي أحمر بالدجاج والذرة والليمون', 'Red Chicken Pozole with Hominy and Lime', 'Pozole rouge au poulet, maïs et citron vert', 'Pozole rojo de pollo con maíz y lima', 'Rotes Pozole mit Hähnchen, Mais und Limette', 'soups_stews', 'lunch', 15, 11, 5, 'simmering', 'jalisco'),
  B('mx-phase-a-077', 'فلفل أنشو محشو بلحم البقر والفاصولياء', 'Ancho Chile Stuffed with Beef and Beans', 'Piment ancho farci au bœuf et aux haricots', 'Chile ancho relleno de res y frijoles', 'Ancho-Chili gefüllt mit Rindfleisch und Bohnen', 'meat_mains', 'dinner', 18, 12, 8, 'baking', 'puebla'),
  B('mx-phase-a-078', 'توستادا دجاج تينغا بالأفوكادو', 'Chicken Tinga Tostada with Avocado', 'Tostada de poulet tinga à l’avocat', 'Tostada de pollo tinga con aguacate', 'Chicken-Tinga-Tostada mit Avocado', 'poultry_mains', 'lunch', 18, 15, 8, 'braising', 'central_mexico'),
  B('mx-phase-a-079', 'شوربة سمك هواستيكا بالفلفل والخضار', 'Huasteca Fish Soup with Chile and Vegetables', 'Soupe de poisson huastèque aux piments et légumes', 'Sopa de pescado huasteca con chile y verduras', 'Huasteca-Fischsuppe mit Chili und Gemüse', 'fish_seafood', 'lunch', 17, 9, 4, 'simmering', 'veracruz'),
  B('mx-phase-a-080', 'وعاء إفطار بالفاصولياء والبيض والذرة', 'Breakfast Bowl with Beans, Egg and Corn', 'Bol du matin aux haricots, œuf et maïs', 'Tazón de desayuno con frijoles, huevo y maíz', 'Frühstücksschale mit Bohnen, Ei und Mais', 'breakfast_items', 'breakfast', 13, 16, 8, 'assembling', 'pan_mexican'),
  B('mx-phase-a-081', 'تاكو لحم البقر بفلفل غواخيو', 'Beef Tacos with Guajillo Chile', 'Tacos de bœuf au piment guajillo', 'Tacos de res con chile guajillo', 'Rindfleisch-Tacos mit Guajillo-Chili', 'meat_mains', 'dinner', 21, 12, 8, 'braising', 'northern_mexico'),
  B('mx-phase-a-082', 'دجاج بيبيان أحمر بالسمسم والقرع', 'Red Pipian Chicken with Sesame and Squash Seeds', 'Poulet pipian rouge au sésame et graines de courge', 'Pollo en pipián rojo con ajonjolí y pepitas', 'Rotes Pipián-Hähnchen mit Sesam und Kürbiskernen', 'poultry_mains', 'dinner', 20, 7, 10, 'braising', 'oaxaca'),
  B('mx-phase-a-083', 'سلطة نوبال بالروبيان والأفوكادو', 'Nopal Salad with Shrimp and Avocado', 'Salade de nopales aux crevettes et avocat', 'Ensalada de nopales con camarón y aguacate', 'Nopales-Salat mit Garnelen und Avocado', 'fish_seafood', 'lunch', 16, 7, 8, 'grilling', 'baja_california'),
  B('mx-phase-a-084', 'تامال ذرة طازجة بجبن القريش والفلفل', 'Fresh Corn Tamal with Cottage Cheese and Chile', 'Tamal de maïs frais au fromage frais et piment', 'Tamal de elote con requesón y chile', 'Frischer Maistamal mit Hüttenkäse und Chili', 'breakfast_items', 'breakfast', 12, 23, 6, 'steaming', 'jalisco'),
  B('mx-phase-a-085', 'شوربة دجاج بالأرز والخضار', 'Chicken Caldo with Rice and Vegetables', 'Caldo de poulet au riz et aux légumes', 'Caldo de pollo con arroz y verduras', 'Hähnchen-Caldo mit Reis und Gemüse', 'soups_stews', 'lunch', 14, 10, 4, 'simmering', 'central_mexico'),
  B('mx-phase-a-086', 'إنشيلادا حمراء بالدجاج والفاصولياء', 'Red Chicken and Bean Enchiladas', 'Enchiladas rouges au poulet et haricots', 'Enchiladas rojas de pollo y frijoles', 'Rote Hähnchen-Bohnen-Enchiladas', 'poultry_mains', 'dinner', 17, 18, 7, 'baking', 'puebla'),
  B('mx-phase-a-087', 'دجاج مفتت بصلصة الطماطم الخضراء', 'Shredded Chicken with Green Tomatillo Salsa', 'Poulet effiloché à la salsa verte de tomatilles', 'Pollo deshebrado con salsa verde de tomatillo', 'Gezupftes Hähnchen mit grüner Tomatillo-Salsa', 'poultry_mains', 'dinner', 22, 5, 6, 'braising', 'central_mexico'),
];
