import { B, diasporaFor } from '../uk-base-data/rows.mjs';

const EA = 'east_anglia';
const ML = 'midlands';
const NW = 'north_west';

export default [
  B('مرق شراب القيقب', 'Ely Boiled Gingerbread', 'Pain d épices bouilli', 'Pan de jengibre cocido', 'Gekochtes Ingwerbrot', 'rice_cakes_sweets', 'snack', 2, 30, 6, 'baking', EA, diasporaFor(EA)),
  B('فطيرة اللوز', 'Almond Tart', 'Tarte aux amandes', 'Tarta de almendras', 'Mandel-Tarte', 'rice_cakes_sweets', 'snack', 5, 26, 14, 'baking', EA, diasporaFor(EA)),
  B('سلطة الجزر황', 'Raw Carrot Ribbon Salad', 'Salade de carottes en rubans', 'Ensalada de zanahoria en cintas', 'Karottenband-Salat', 'vegetable_mains', 'lunch', 1, 9, 4, 'raw', EA, diasporaFor(EA)),
  B('بطاطا مقلية بالسمن الصافي', 'Chips with Salt and Butter', 'Frites au beurre sale', 'Patatas fritas con mantequilla y sal', 'Pommes mit Butter und Salz', 'vegetable_mains', 'snack', 3, 24, 9, 'frying', EA, diasporaFor(EA)),
  B('كعك الكبريت', 'Custard and Jelly Pastry', 'Feuilleté crème et gelee', 'Hojaldre de crema y gelatima', 'Creme-Gelee-Gebäck', 'rice_cakes_sweets', 'snack', 4, 30, 11, 'baking', EA, diasporaFor(EA)),
  B('شوربة البازلاء自卫', 'Split Pea Soup', 'Soupe de pois secs', 'Sopa de guisantes secos', 'Erbsensuppe', 'soups_stews', 'lunch', 5, 10, 2, 'simmering', EA, diasporaFor(EA)),
  B('صلصة التوت البري', 'Bramble Sauce', 'Sauce de mûres', 'Salsa de mora', 'Brombeersauce', 'condiments_sauces', 'snack', 0, 10, 0, 'simmering', EA, diasporaFor(EA)),
  B('مربى البرتقال', 'Orange Marmalade', 'Marmelade d orange', 'Mermelada de naranja', 'Orangenmarmelade', 'condiments_sauces', 'snack', 0, 22, 0, 'boiling', EA, diasporaFor(EA)),
  B('شوربة الخرشوف', 'Artichoke Soup', 'Soupe d artichaut', 'Sopa de alcachofa', 'Artischockensuppe', 'soups_stews', 'lunch', 2, 9, 3, 'simmering', EA, diasporaFor(EA)),
  B('محمص البازلاء', 'Peas with Mint Butter', 'Petits pois au beurre a la menthe', 'Guisantes con mantequilla y menta', 'Erbsen mit Minzbutter', 'vegetable_mains', 'dinner', 4, 10, 5, 'boiling', EA, diasporaFor(EA)),
  B('برغل بالجزر', 'Pearl Barley Pilaf', 'Orge perlee aux legumes', 'Cebada perla con verduras', 'Perlgraupen-Pilaw', 'rice_dishes', 'dinner', 5, 22, 4, 'simmering', EA, diasporaFor(EA)),
  B('خبز قمح نورفولك', 'Norfolk Wheat Bread', 'Pain de froment du Norfolk', 'Pan de trigo de Norfolk', 'Norfolk-Weizenbrot', 'breakfast_items', 'breakfast', 7, 28, 3, 'baking', EA, diasporaFor(EA)),
  B('كعك العسل', 'Honeycomb Tart', 'Tarte en nid d abeille', 'Tarta de panal', 'Honigwaben-Tarte', 'rice_cakes_sweets', 'snack', 3, 28, 10, 'baking', EA, diasporaFor(EA)),
  B('سلطة الكرفس539', 'Celery and Apple Salad', 'Salade celeri pomme', 'Ensalada de apio y manzana', 'Sellerie-Apfel-Salat', 'vegetable_mains', 'lunch', 1, 10, 4, 'raw', EA, diasporaFor(EA)),
  B('بودنج السمولينا', 'Semolina Pudding', 'Pudding semoule', 'Pudin de sémola', 'Grießpudding', 'rice_cakes_sweets', 'snack', 3, 22, 4, 'baking', EA, diasporaFor(EA)),
  B('زيت عباد الشمس', 'Cold Pressed Sunflower Oil', 'Huile de tournesol pressee a froid', 'Aceite de girasol prensado en frío', 'Kaltgepresstes Sonnenblumenöl', 'condiments_sauces', 'snack', 0, 0, 100, 'pressing', EA, diasporaFor(EA)),
  B('شوربة الفاصولي الحمراء', 'Red Bean Soup', 'Soupe de haricots rouges', 'Sopa de judias rojas', 'Rote-Bohnen-Suppe', 'soups_stews', 'lunch', 6, 12, 2, 'simmering', EA, diasporaFor(EA)),
  B('بطاطا حلوة مشوية بالقرفة', 'Cinnamon Roast Sweet Potato', 'Patate douce rotie a la cannelle', 'Bonata asada con canela', 'Süßkartoffel mit Zimt', 'vegetable_mains', 'snack', 2, 20, 1, 'roasting', EA, diasporaFor(EA)),
  B('جبن مثلثات الشيدر', 'Cheddar Triangles', 'Triangles de cheddar', 'Triángulos de cheddar', 'Cheddar-Dreiecke', 'vegetable_mains', 'snack', 9, 2, 22, 'aging', EA, diasporaFor(EA)),
  B('شوربة الخردل', 'Mustard Seed Soup', 'Soupe aux graines de moutarde', 'Sopa de semillas de mostaza', 'Senfkorn-Suppe', 'soups_stews', 'lunch', 5, 9, 3, 'simmering', EA, diasporaFor(EA)),
  B('شريحة الكستارد', 'Custard Slice', 'Tarte a la creme pâtissière', 'Tarta de crema pastelera', 'Cremetorte', 'rice_cakes_sweets', 'snack', 4, 30, 11, 'baking', ML, diasporaFor(ML)),
  B('حساء الطماطم المشوية', 'Roasted Tomato Soup', 'Veloute de tomates grillees', 'Sopa de tomate asado', 'Geröstete Tomatensuppe', 'soups_stews', 'lunch', 2, 10, 4, 'roasting', ML, diasporaFor(ML)),
  B('كعك بحيرة', 'Bakewell Pudding', 'Pudding Bakewell', 'Pudin Bakewell', 'Bakewell-Pudding', 'rice_cakes_sweets', 'snack', 5, 28, 12, 'baking', ML, diasporaFor(ML)),
  B('فطيرة اللحم بدويرة', 'Pork Pie Substitute Bake', 'Tourte au boeuf hachee', 'Pastel de beef hacheado', 'Hack-Pastete', 'meat_mains', 'dinner', 13, 20, 12, 'baking', ML, diasporaFor(ML)),
  B('شوربة الكرفس بالجبنة', 'Leek and Cheddar Soup', 'Soupe poireaux cheddar', 'Sopa de puerro y cheddar', 'Lauch-Cheddar-Suppe', 'soups_stews', 'lunch', 4, 10, 7, 'simmering', ML, diasporaFor(ML)),
  B('صلصة الجبن', 'Cheese Sauce', 'Sauce au fromage', 'Salsa de queso', 'Käsesauce', 'condiments_sauces', 'snack', 2, 6, 16, 'mixing', ML, diasporaFor(ML)),
  B('شوربة الفطر', 'Mushroom Soup', 'Soupe de champignons', 'Sopa de setas', 'Pilzsuppe', 'soups_stews', 'lunch', 3, 7, 3, 'simmering', ML, diasporaFor(ML)),
  B('فطيرة المكسرات', 'Nut Roast', 'Rôti de noix', 'Asado de frutos secos', 'Nussbraten', 'vegetable_mains', 'dinner', 8, 16, 14, 'roasting', ML, diasporaFor(ML)),
  B('بودنج المانجو', 'Mango Pudding', 'Pudding a la mangue', 'Pudin de mango', 'Mango-Pudding', 'rice_cakes_sweets', 'snack', 2, 24, 6, 'chilling', ML, diasporaFor(ML)),
  B('شوربة الجزر والكركم', 'Carrot Turmeric Soup', 'Soupe carottes-curcuma', 'Sopa de zanahoria y cúrcuma', 'Karotten-Kurkuma-Suppe', 'soups_stews', 'lunch', 2, 10, 3, 'simmering', ML, diasporaFor(ML)),
  B('سلطة الطحينة', 'Tahini Slaw', 'Coleslaw au tahini', 'Ensalada de col con tahini', 'Tahini-Krautsalat', 'vegetable_mains', 'lunch', 3, 9, 7, 'tossing', ML, diasporaFor(ML)),
  B('شورتمبريد بخلية النحل', 'Honeycomb Shortbread', 'Shortbread en nid d abeille', 'Shortbread de panal', 'Honigwaben-Shortbread', 'rice_cakes_sweets', 'snack', 2, 24, 13, 'baking', ML, diasporaFor(ML)),
  B('شوربة العدس الأخضر', 'Green Lentil Soup', 'Soupe de lentilles vertes', 'Sopa de lentejas verdes', 'Grüne-Linsen-Suppe', 'soups_stews', 'lunch', 6, 12, 2, 'simmering', ML, diasporaFor(ML)),
  B('فطيرة البطاطا والجبن', 'Cheese and Potato Pie', 'Tourte pommes de terre fromage', 'Pastel de patatas y queso', 'Kartoffel-Käse-Pastete', 'vegetable_mains', 'dinner', 7, 20, 11, 'baking', ML, diasporaFor(ML)),
  B('صلصة الشوكولاتة الداكنة', 'Dark Chocolate Spread', 'Pate a tartiner au chocolat noir', 'Crema de chocolate negro', 'Dunkle-Schokoladen-Creme', 'condiments_sauces', 'snack', 2, 14, 22, 'mixing', ML, diasporaFor(ML)),
  B('عجة مخبوزة بالخضار', 'Baked Vegetable Frittata', 'Frittata de legumes', 'Frittata de verduras', 'Gemüse-Frittata', 'breakfast_items', 'lunch', 6, 8, 12, 'baking', ML, diasporaFor(ML)),
  B('شوربة الطماطم الحار', 'Spiced Tomato Broth', 'Bouillon tomates aux épices', 'Caldo de tomate especiado', 'Gewürz-Tomatenbrühe', 'soups_stews', 'lunch', 2, 9, 3, 'simmering', ML, diasporaFor(ML)),
  B('فطيرة اللحم بالجزر', 'Beef and Carrot Pie', 'Tourte boeuf carottes', 'Pastel de res y zanahoria', 'Rindfleisch-Möhren-Pastete', 'meat_mains', 'dinner', 12, 19, 11, 'baking', ML, diasporaFor(ML)),
  B('برغل الفاصولي', 'Bean and Bulgur Pilaf', 'Pilaf haricots-boulgour', 'Pilaf de judias y bulgur', 'Bohnen-Bulgur-Pilaw', 'rice_dishes', 'dinner', 6, 22, 5, 'simmering', ML, diasporaFor(ML)),
  B('كعك الزنجبيل بالقطر', 'Ginger Cake with Syrup', 'Gateau au gingembre au sirop', 'Bizcocho de jengibre con jarabe', 'Ingwerkuchen mit Sirup', 'rice_cakes_sweets', 'snack', 3, 28, 9, 'baking', ML, diasporaFor(ML)),
  B('لحم بقر مطهو بالبرغل', 'Beef Stroganoff with Bulgur', 'Boeuf stroganoff au boulgour', 'Stroganoff de res con bulgur', 'Rinder-Stroganoff mit Bulgur', 'meat_mains', 'dinner', 15, 18, 13, 'simmering', ML, diasporaFor(ML)),
  B('سلطة الحمص الكاملة', 'Chickpea Salad Bowl', 'Bol de salade de pois chiches', 'Bol de ensalada de garbanzos', 'Kichererbsen-Salat', 'vegetable_mains', 'lunch', 6, 14, 6, 'tossing', ML, diasporaFor(ML)),
  B('كعكة السمسم', 'Sesame Seed Cake', 'Gateau aux graines de sesame', 'Bizcocho de sésamo', 'Sesamkuchen', 'rice_cakes_sweets', 'snack', 4, 26, 12, 'baking', ML, diasporaFor(ML)),
  B('شوربة الجرجير الورد', 'Watercress and Pea Soup', 'Soupe cresson petits pois', 'Sopa de berro y guisantes', 'Brunnenkresse-Erbsen-Suppe', 'soups_stews', 'lunch', 4, 9, 3, 'simmering', ML, diasporaFor(ML)),
  B('فطيرة تفاح بالبرتقال', 'Apple and Orange Pie', 'Tarte pommes orange', 'Tarta de manzana y naranja', 'Apfel-Orangen-Tarte', 'rice_cakes_sweets', 'snack', 1, 28, 9, 'baking', ML, diasporaFor(ML)),
  B('شوربة الطماطم الجافة', 'Sun Dried Tomato Soup', 'Veloute tomates sechees', 'Crema de tomate seco', 'Getrocknete Tomatensuppe', 'soups_stews', 'lunch', 2, 9, 3, 'simmering', ML, diasporaFor(ML)),
  B('صلصة الفلفل الحلو', 'Roasted Pepper Sauce', 'Sauce poivrons grilles', 'Salsa de pimientos asados', 'Geröstete Paprikasauce', 'condiments_sauces', 'snack', 1, 6, 5, 'roasting', ML, diasporaFor(ML)),
  B('كعك التمر', 'Date and Walnut Cake', 'Gateau dattes noix', 'Bizcocho de dátiles y nueces', 'Dattel-Walnußkuchen', 'rice_cakes_sweets', 'snack', 4, 28, 11, 'baking', ML, diasporaFor(ML)),
  B('مرق بيرتون', 'Burton Water Gravy', 'Gravy de bouillon', 'Sopa de carne de Burton', 'Burton-Bouillon', 'condiments_sauces', 'snack', 4, 3, 4, 'simmering', ML, diasporaFor(ML)),
  B('شوربة الشعير اللندني', 'London Barley Broth', 'Bouillon d orge de Londres', 'Caldo de cebada londinense', 'Londoner Gerstenbrühe', 'soups_stews', 'lunch', 5, 12, 3, 'simmering', NW, diasporaFor(NW)),
];
