import { B, diasporaFor } from '../uk-base-data/rows.mjs';

const P = 'pan_british';
const LON = 'london';

export default [
  B('لحم بقر مشوي بصلصة البصل', 'Roast Beef with Onion Gravy', 'Roti de boeuf au gravy dormeaux', 'Asado de res con gravy de cebolla', 'Rinderbraten mit Zwiebel-Gravy', 'meat_mains', 'dinner', 17, 18, 12, 'roasting', P, diasporaFor(P)),
  B('كباب لحم البقر والكفتة', 'Beef Meatballs in Tomato Sauce', 'Boulettes de boeuf a la tomate', 'Albóndigas de res en salsa de tomate', 'Rindfleischklosschen in Tomatensauce', 'meat_mains', 'dinner', 15, 10, 11, 'simmering', P, diasporaFor(P)),
  B('لحم بقري مطهو ببطء', 'Slow-Cooked Beef Brisket', 'Poitrine de boeuf mijotee', 'Brisket cocido lento', 'Geschmortes Rinderbrust', 'meat_mains', 'dinner', 18, 4, 16, 'braising', P, diasporaFor(P)),
  B('لحم بقر مشوي بصلصة الباربكيو', 'Beef Ribs with Barbecue Glaze', 'Cotes de boeuf au barbecue', 'Costillas de res con glaseado barbacoa', 'Rinderrippen mit Barbecue-Glasur', 'meat_mains', 'dinner', 19, 12, 15, 'roasting', P, diasporaFor(P)),
  B('كعك المحشي باللحم', 'Steak and Kidney Pie', 'Tourte au boeuf et rognons', 'Pastel de vacuno y riñones', 'Steak-Nieren-Pastete', 'meat_mains', 'dinner', 14, 20, 13, 'baking', P, diasporaFor(P)),
  B('فطيرة لحم الغنم بالقرنبيط', 'Lamb and Cauliflower Pie', 'Tourte agneau-chou-fleur', 'Pastel de cordero y coliflor', 'Lamm-Blumenkohl-Pastete', 'meat_mains', 'dinner', 12, 18, 11, 'baking', P, diasporaFor(P)),
  B('لحم غنم مشوي بالروزماري', 'Roast Lamb with Rosemary', 'Agneau rôti au romarin', 'Cordero asado con romero', 'Rinderbraten-Lamm mit Rosmarin', 'meat_mains', 'dinner', 17, 2, 15, 'roasting', P, diasporaFor(P)),
  B('دجاج مشوي بالثوم والأعشاب', 'Roast Chicken with Garlic and Herbs', 'Poulet rôti a l ail et aux herbes', 'Pollo asado con ajo y hierbas', 'Gebratenes Hähnchen mit Knoblauch', 'poultry_mains', 'dinner', 18, 2, 14, 'roasting', P, diasporaFor(P)),
  B('دجاج مقلي بالزبدة', 'Butter Fried Chicken', 'Poulet frit au beurre', 'Pollo frito con mantequilla', 'Buttergebratenes Hähnchen', 'poultry_mains', 'dinner', 17, 4, 15, 'frying', P, diasporaFor(P)),
  B('لحم دجاج مشوي بالليمون', 'Roast Turkey Breast', 'Dinde rôtie au citron', 'Pavo asado al limón', 'Truthahnbrust mit Zitrone', 'poultry_mains', 'dinner', 19, 2, 11, 'roasting', P, diasporaFor(P)),
  B('صدر دجاج مشوي بالزعتر', 'Grilled Chicken Breast with Thyme', 'Poulet grille au thym', 'Pechuga de pollo a la parrilla con tomillo', 'Gegrillte Hähnchenbrust mit Thymian', 'poultry_mains', 'dinner', 22, 1, 7, 'grilling', P, diasporaFor(P)),
  B('سمك السلمون المشوي بالليمون', 'Grilled Salmon with Lemon', 'Saumon grillé au citron', 'Salmón a la parrilla con limón', 'Gegrillter Lachs mit Zitrone', 'fish_seafood', 'dinner', 21, 1, 11, 'grilling', P, diasporaFor(P)),
  B('سمك التونة المعلب', 'Tinned Tuna with Butter Beans', 'Thon au haricots blancs', 'Atún con habas blancas', 'Thunfisch mit weißen Bohnen', 'fish_seafood', 'lunch', 14, 12, 5, 'simmering', P, diasporaFor(P)),
  B('سمك الحد在与', 'Fish Pie', 'Tourte au poisson', 'Pastel de pescado', 'Fischpastete', 'fish_seafood', 'dinner', 11, 20, 11, 'baking', P, diasporaFor(P)),
  B('روبيان مشوي بالثوم', 'Garlic Butter Prawns', 'Crevettes au beurre d ail', 'Gambas con mantequilla de ajo', 'Knoblauchbutter-Garnelen', 'fish_seafood', 'dinner', 18, 3, 12, 'grilling', P, diasporaFor(P)),
  B('بلح البحر بالصلصة البيضاء', 'Mussels with Cream Sauce', 'Moules a la creme', 'Mejillones con salsa de nata', 'Muscheln mit Rahmsauce', 'fish_seafood', 'dinner', 13, 8, 8, 'steaming', P, diasporaFor(P)),
  B('سلطة الكينوا بالخضار', 'Quinoa Vegetable Salad', 'Salade de quinoa aux légumes', 'Ensalada de quinoa con verduras', 'Quinoa-Gemüsesalat', 'vegetable_mains', 'lunch', 4, 18, 5, 'tossing', P, diasporaFor(P)),
  B('جراتان بالخميرة والزيت', 'Baked Camembert with Bread', 'Camembert au four avec pain', 'Camembert al horno con pan', 'Gebackener Camembert mit Brot', 'vegetable_mains', 'snack', 8, 10, 15, 'baking', P, diasporaFor(P)),
  B('طبق الدجاج المتوازن', 'Chicken Power Bowl', 'Poke bowl au poulet', 'Bowl de pollo estilo poke', 'Chicken-Poke-Bowl', 'rice_dishes', 'dinner', 12, 22, 8, 'assembling', P, diasporaFor(P)),
  B('برغر فطر بالجبنة', 'Mushroom and Cheese Burger', 'Burger champignons et fromage', 'Hamburguesa de champinones y queso', 'Pilz-Käse-Burger', 'street_snacks', 'dinner', 12, 10, 14, 'grilling', P, diasporaFor(P)),
  B('كبة مقلية بصلصة الطماطم', 'Fried Falafel Pita', 'Falafel frit en pita', 'Falafel frito en pita', 'Gebratener Falafel im Pita', 'street_snacks', 'snack', 6, 20, 8, 'frying', P, diasporaFor(P)),
  B('سلطة فول مدمس', 'Fava Bean Salad', 'Salade de fèves', 'Ensalada de habas', 'Ackerbohnen-Salat', 'vegetable_mains', 'lunch', 6, 14, 5, 'boiling', P, diasporaFor(P)),
  B('فاصولي مخبوزة مع لحم الديك الرومي', 'Baked Beans with Turkey Bacon', 'Haricots cuits au bacon de dinde', 'Judías con bacon de pavo', 'Ofenbohnen mit Truthahn-Speck', 'breakfast_items', 'breakfast', 8, 20, 5, 'baking', P, diasporaFor(P)),
  B('فاصولي بيضاء بالجبن', 'Baked Cheese Beans', 'Haricots blancs au fromage', 'Judías blancas al horno con queso', 'Weiße Bohnen mit Käse', 'vegetable_mains', 'dinner', 7, 16, 6, 'baking', P, diasporaFor(P)),
  B('شوربة الخضراوات بالزبدة', 'Vegetable Soup with Butter', 'Soupe aux légumes au beurre', 'Sopa de verduras con mantequilla', 'Gemüsesuppe mit Butter', 'soups_stews', 'lunch', 3, 10, 4, 'simmering', P, diasporaFor(P)),
  B('حساء الطماطم بالسماق', 'Spiced Tomato Soup', 'Soupe de tomates aux épices', 'Sopa de tomate especiada', 'Gewürz-Tomatensuppe', 'soups_stews', 'lunch', 2, 9, 3, 'simmering', P, diasporaFor(P)),
  B('حساء العدس الأحمر', 'Red Lentil Soup', 'Soupe de lentilles rouges', 'Sopa de lentejas rojas', 'Rote-Linsen-Suppe', 'soups_stews', 'lunch', 6, 14, 2, 'simmering', P, diasporaFor(P)),
  B('حساء الجزر والزنجبيل', 'Carrot and Ginger Soup', 'Soupe carottes-gingembre', 'Sopa de zanahoria y jengibre', 'Möhren-Ingwer-Suppe', 'soups_stews', 'lunch', 2, 10, 3, 'simmering', P, diasporaFor(P)),
  B('معدوسة بالخبز', 'Mulligatawny Soup', 'Mulligatawny soup', 'Sopa Mulligatawny', 'Mulligatawny-Suppe', 'soups_stews', 'lunch', 5, 10, 5, 'simmering', P, diasporaFor(P)),
  B('حساء البصل الفرنسي', 'French Onion Soup', 'Soupe a l oignon gratinee', 'Sopa de cebolla gratinada', 'Franzosische Zwiebelsuppe', 'soups_stews', 'lunch', 4, 12, 8, 'baking', P, diasporaFor(P)),
  B('سموذي الفواكه المختلط', 'Mixed Fruit Smoothie', 'Smoothie aux fruits', 'Batido de frutas', 'Obst-Smoothie', 'beverages', 'breakfast', 1, 14, 1, 'blending', P, diasporaFor(P)),
  B('شاي أخضر بالنعناع', 'Mint Tea', 'Tisane a la menthe', 'Té de menta', 'Pfefferminztee', 'beverages', 'snack', 0, 1, 0, 'brewing', P, diasporaFor(P)),
  B('شاي أحمر بالليمون', 'Black Tea with Lemon', 'The noir au citron', 'Té negro con limón', 'Schwarzer Tee mit Zitrone', 'beverages', 'snack', 0, 1, 0, 'brewing', P, diasporaFor(P)),
  B('قهوة نبضية بالحليب', 'Flat White Coffee', 'Cafe flat white', 'Café flat white', 'Flat White Kaffee', 'beverages', 'breakfast', 3, 4, 3, 'brewing', P, diasporaFor(P)),
  B('كابتشينو', 'Cappuccino', 'Cappuccino', 'Capuchino', 'Cappuccino', 'beverages', 'breakfast', 3, 5, 3, 'brewing', P, diasporaFor(P)),
  B('لاتيه بالنعناع', 'Peppermint Latte', 'Latte a la menthe poivree', 'Latte de menta', 'Pfefferminz-Latte', 'beverages', 'snack', 3, 5, 3, 'brewing', P, diasporaFor(P)),
  B('ماء غازي الليمون', 'Sparkling Lemon Water', 'Eau gazeuse citronnée', 'Agua con gas y limón', 'Sprudelndes Zitronenwasser', 'beverages', 'snack', 0, 3, 0, 'brewing', P, diasporaFor(P)),
  B('شاي المريمية', 'Lemon Balm Tea', 'Tisane verveine', 'Té de melisa', 'Zitronenmelissentee', 'beverages', 'snack', 0, 1, 0, 'brewing', P, diasporaFor(P)),
  B('شراب الورد', 'Rose Cordial Syrup', 'Sirop de rose', 'Sirope de rosas', 'Rosen-Sirup', 'beverages', 'snack', 0, 16, 0, 'simmering', P, diasporaFor(P)),
  B('خبز الثفل الشامي', 'Fruit Loaf Bread', 'Pain aux fruits', 'Pan de frutas', 'Obstbrot', 'breakfast_items', 'breakfast', 5, 30, 4, 'baking', P, diasporaFor(P)),
  B('خبز الم八方', 'Crumpet Spread', 'Crumpets a tartiner', 'Tostada de crumpet', 'Crumpet-Aufstrich', 'breakfast_items', 'breakfast', 3, 16, 4, 'griddled', P, diasporaFor(P)),
  B('سلطة الحبوب المفلفل', 'Peppered Couscous', 'Couscous au poivre', 'Cuscús con pimienta', 'Gewürz-Couscous', 'rice_dishes', 'lunch', 5, 22, 4, 'simmering', P, diasporaFor(P)),
  B('أرز بالبازلاء والكاروت', 'Pea and Carrot Rice', 'Riz aux petits pois et carottes', 'Arroz con guisantes y zanahoria', 'Reis mit Erbsen und Möhren', 'rice_dishes', 'dinner', 4, 26, 3, 'simmering', P, diasporaFor(P)),
  B('مكرونة بالصلصة البيضاء', 'Pasta with White Sauce', 'Pates a la sauce blanche', 'Pasta con salsa blanca', 'Nudeln mit heller Sauce', 'noodle_dishes', 'dinner', 6, 26, 8, 'simmering', P, diasporaFor(P)),
  B('مكرونة بالصلصة الحمراء', 'Pasta with Tomato Sauce', 'Pates a la sauce tomate', 'Pasta con salsa de tomate', 'Nudeln mit Tomatensauce', 'noodle_dishes', 'dinner', 6, 26, 6, 'simmering', P, diasporaFor(P)),
  B('نودلز بالخضار', 'Vegetable Noodles', 'Nouilles aux légumes', 'Fideos de verduras', 'Gemüse-Nudeln', 'noodle_dishes', 'lunch', 4, 24, 4, 'stir_frying', P, diasporaFor(P)),
  B('دجاج بالتكماري مع الأرز', 'Chicken Tikka with Rice', 'Poulet tikka avec riz', 'Pollo tikka con arroz', 'Hähnchen-Tikka mit Reis', 'rice_dishes', 'dinner', 14, 22, 9, 'grilling', LON, diasporaFor(LON)),
  B('سمك مشوي على الفحم', 'Charcoal Grilled Fish', 'Poisson grille au charbon', 'Pescado a la parrilla de carbón', 'Fisch auf Holzkohle gegrillt', 'fish_seafood', 'dinner', 19, 2, 8, 'grilling', LON, diasporaFor(LON)),
  B('صدر دجاج مقرمش', 'Crispy Chicken Breast', 'Poulet croustillant', 'Pechuga de pollo crujiente', 'Knusprige Hähnchenbrust', 'poultry_mains', 'dinner', 18, 8, 13, 'frying', LON, diasporaFor(LON)),
  B('برغر لحم بقر بالجبنة', 'Beef Cheeseburger', 'Cheeseburger au boeuf', 'Hamburguesa de res con queso', 'Rindfleisch-Cheeseburger', 'street_snacks', 'dinner', 14, 8, 15, 'grilling', LON, diasporaFor(LON)),
];
