import { B, diasporaFor } from '../uk-base-data/rows.mjs';

const LON = 'london';
const NW = 'north_west';
const Y = 'yorkshire';

export default [
  B('بطاطا مقلية بالجبن والبهارات', 'Loaded Cheese Fries', 'Frites fromage et herbes', 'Patatas con queso y hierbas', 'Pommes mit Käse und Kräutern', 'street_snacks', 'snack', 5, 22, 11, 'frying', LON, diasporaFor(LON)),
  B('فراخ مسحّبة', 'Buffalo Chicken Wings', 'Ailes de poulet buffalo', 'Alitas de pollo buffalo', 'Buffalo-Hühnerflügel', 'poultry_mains', 'dinner', 16, 6, 14, 'frying', LON, diasporaFor(LON)),
  B('ساندوتش دجاج مقلي', 'Fried Chicken Sandwich', 'Sandwich au poulet frit', 'Sándwich de pollo frito', 'Gebratenes Hähnchen-Sandwich', 'street_snacks', 'lunch', 13, 16, 12, 'frying', LON, diasporaFor(LON)),
  B('كاري دجاج بحليب جوز الهند', 'Coconut Chicken Curry', 'Curry au poulet au lait de coco', 'Curry de pollo con leche de coco', 'Kokos-Hähnchen-Curry', 'poultry_mains', 'dinner', 13, 10, 13, 'simmering', LON, diasporaFor(LON)),
  B('لحم بقر بالبرغل', 'Beef Bulgur Pilaf', 'Pilaf de boeuf au boulgour', 'Pilaf de res con bulgur', 'Rind-Bulgur-Pilaw', 'rice_dishes', 'dinner', 14, 20, 8, 'simmering', LON, diasporaFor(LON)),
  B('مقبلات مشكلة بالصلصة', 'Mixed Mezze Platter', 'Mezze varié', 'Plato de mezze mixto', 'Mezze-Platte', 'street_snacks', 'snack', 6, 14, 9, 'assembling', LON, diasporaFor(LON)),
  B('حمص بالطحينة', 'Hummus with Tahini', 'Houmous tahini', 'Hummus con tahini', 'Hummus mit Tahini', 'condiments_sauces', 'snack', 4, 8, 8, 'mixing', LON, diasporaFor(LON)),
  B('تبولة', 'Tabbouleh Salad', 'Tabouleh', 'Tabulé', 'Tabouleh', 'vegetable_mains', 'lunch', 2, 10, 5, 'tossing', LON, diasporaFor(LON)),
  B('سلطة الفتوش', 'Fattoush Salad', 'Fattouch', 'Ensalada fattoush', 'Fattoush-Salat', 'vegetable_mains', 'lunch', 2, 9, 6, 'tossing', LON, diasporaFor(LON)),
  B('سمك بالحرارة والبهارات', 'Fish Curry with Coconut Milk', 'Curry de poisson au lait de coco', 'Curry de pescado con leche de coco', 'Fisch-Curry mit Kokosmilch', 'fish_seafood', 'dinner', 15, 9, 10, 'simmering', LON, diasporaFor(LON)),
  B('فطيرة اللحم المفروم والكرنب', 'Corned Beef and Cabbage Pie', 'Tourte viande de boeef et chou', 'Pastel de carne y col', 'Corned-Beef-Kohl-Pastete', 'meat_mains', 'dinner', 12, 20, 12, 'baking', NW, diasporaFor(NW)),
  B('بيضة مسلوقة في الكسكروت', 'Egg in a Hole', 'Oeuf dans un trou', 'Huevo al hole-in-one', 'Ei im Loch', 'breakfast_items', 'breakfast', 6, 14, 8, 'griddled', NW, diasporaFor(NW)),
  B('حساء البطاطا والكرفس الكريمي', 'Creamy Potato Leek Soup', 'Veloute pommes de terre poireaux', 'Crema de patata y puerro', 'Kartoffel-Lauch-Creme', 'soups_stews', 'lunch', 3, 12, 5, 'simmering', NW, diasporaFor(NW)),
  B('شخصي', 'Grilled Halloumi', 'Halloumi grille', 'Halloumi a la parrilla', 'Gegrillter Halloumi', 'vegetable_mains', 'dinner', 10, 3, 18, 'grilling', NW, diasporaFor(NW)),
  B('فطيرة الجزر يوركشاير', 'Yorkshire Carrot Pie', 'Tourte carottes du Yorkshire', 'Pastel de zanahoria de Yorkshire', 'Yorkshire-Karottelpastete', 'vegetable_mains', 'dinner', 3, 18, 9, 'baking', Y, diasporaFor(Y)),
  B('براوني يوركشاير', 'Yorkshire Brownies', 'Brownies du Yorkshire', 'Brownies de Yorkshire', 'Yorkshire-Brownies', 'rice_cakes_sweets', 'snack', 4, 30, 14, 'baking', Y, diasporaFor(Y)),
  B('خردل يوركشاير', 'Yorkshire Mustard', 'Moutarde du Yorkshire', 'Mostaza de Yorkshire', 'Yorkshire-Senf', 'condiments_sauces', 'snack', 0, 6, 0, 'mixing', Y, diasporaFor(Y)),
  B('مربى الراونبارد يوركشاير', 'Yorkshire Forced Rhubarb Compote', 'Compote de rhubarbe du Yorkshire', 'Compota de ruibarbo de Yorkshire', 'Yorkshire-Rhabarber-Kompott', 'fruit', 'snack', 1, 16, 0, 'simmering', Y, diasporaFor(Y)),
  B('ماء الشعير في هال', 'Hull Barley Water', 'Eau d orge de Hull', 'Agua de cebada de Hull', 'Hull-Gerstenwasser', 'beverages', 'snack', 1, 6, 0, 'boiling', Y, diasporaFor(Y)),
  B('كعكة الستيفاج', 'Stilton and Pear Tart', 'Tarte Stilton et poire', 'Tarta Stilton y pera', 'Stilton-Birnen-Tarte', 'rice_cakes_sweets', 'snack', 6, 24, 14, 'baking', Y, diasporaFor(Y)),
  B('فطيرة الدجاج يوركشاير', 'Yorkshire Chicken Pie', 'Tourte au poulet du Yorkshire', 'Pastel de pollo de Yorkshire', 'Yorkshire-Hähnchen-Pastete', 'poultry_mains', 'dinner', 13, 18, 11, 'baking', Y, diasporaFor(Y)),
  B('شفط يوركشاير', 'Yorkshire Shrimp Toast', 'Pain aux crevettes du Yorkshire', 'Tostada de gambas de Yorkshire', 'Yorkshire-Garnelenbrot', 'fish_seafood', 'snack', 10, 14, 6, 'grilling', Y, diasporaFor(Y)),
  B('بودنج الرز بالبهارات', 'Yorkshire Spiced Rice Pudding', 'Riz au lait aux epices', 'Arroz con leche especiado', 'Gewuerzter Milchreis', 'rice_cakes_sweets', 'snack', 4, 20, 5, 'baking', Y, diasporaFor(Y)),
  B('قضيب الشوفان يوركشاير', 'Yorkshire Oat Flapjack', 'Flapjack avoine du Yorkshire', 'Flapjack de avena de Yorkshire', 'Yorkshire-Haferfladen', 'rice_cakes_sweets', 'snack', 3, 26, 9, 'baking', Y, diasporaFor(Y)),
  B('كناك الاعشاب', 'Lancashire Oatcake', 'Galette d avoine du Lancashire', 'Galleta de avena de Lancashire', 'Lancashire-Haferkuchen', 'rice_cakes_sweets', 'snack', 3, 22, 8, 'baking', NW, diasporaFor(NW)),
  B('صلصة الكبد', 'Liver Pate', 'Pain de foie', 'Paté de hígado', 'Leberpastete', 'meat_mains', 'snack', 9, 6, 16, 'baking', NW, diasporaFor(NW)),
  B('شوربة الشحم', 'Hotpot Broth', 'Bouillon du hotpot', 'Caldo del hotpot', 'Hotpot-Brühe', 'soups_stews', 'dinner', 14, 8, 12, 'stewing', NW, diasporaFor(NW)),
  B('فطيرة بطاطا لانكشاير', 'Lancashire Potato Pie', 'Tourte pommes de terre Lancashire', 'Pastel de patatas de Lancashire', 'Lancashire-Kartoffelpastete', 'vegetable_mains', 'dinner', 5, 22, 8, 'baking', NW, diasporaFor(NW)),
  B('كعك اللوز الثاني', 'Almond Biscuit Rings', 'Biscuits aux amandes', 'Galletas de almendras', 'Mandelkekse', 'rice_cakes_sweets', 'snack', 4, 24, 12, 'baking', NW, diasporaFor(NW)),
  B('حساء الجزر والكزبرة في لانكشاير', 'Lancashire Carrot and Coriander Soup', 'Soupe carottes coriandre', 'Sopa de zanahoria y cilantro', 'Karotten-Koriander-Suppe', 'soups_stews', 'lunch', 2, 10, 3, 'simmering', NW, diasporaFor(NW)),
  B('فطيرة لحم البقر بالفطر', 'Beef and Mushroom Pie', 'Tourte au boeuf et champignons', 'Pastel de vacuno y champinones', 'Rindersteak-Pilz-Pastete', 'meat_mains', 'dinner', 13, 21, 12, 'baking', NW, diasporaFor(NW)),
  B('سلطة البازلاء', 'Pea Salad', 'Salade de petits pois', 'Ensalada de guisantes', 'Erbsensalat', 'vegetable_mains', 'lunch', 5, 9, 4, 'boiling', NW, diasporaFor(NW)),
  B('كعك الزبيب', 'Fruit Teacake', 'Gateau aux fruits secs', 'Bizcocho de fruta seca', 'Obst-Teekuchen', 'rice_cakes_sweets', 'snack', 3, 28, 10, 'baking', NW, diasporaFor(NW)),
  B('شوربة اللوز', 'Almond Milk Soup', 'Soupe au lait d amande', 'Sopa de leche de almendra', 'Mandelmilchsuppe', 'soups_stews', 'lunch', 3, 10, 5, 'simmering', NW, diasporaFor(NW)),
  B('مربى اللوز', 'Almond Jam', 'Confiture d amandes', 'Mermelada de almendras', 'Mandelgelee', 'condiments_sauces', 'snack', 3, 20, 6, 'boiling', NW, diasporaFor(NW)),
  B('برجر لانكشاير', 'Lancashire Burger', 'Burger Lancashire', 'Hamburguesa de Lancashire', 'Lancashire-Burger', 'street_snacks', 'dinner', 13, 8, 13, 'grilling', NW, diasporaFor(NW)),
  B('كعك السمسم الثاني', 'Sesame Snack Bar', 'Barre de sesame', 'Barra de sésamo', 'Sesam-Riegel', 'rice_cakes_sweets', 'snack', 4, 22, 12, 'baking', NW, diasporaFor(NW)),
  B('حساء الطماطم الكريمي', 'Cream of Tomato Soup', 'Veloute de tomates a la creme', 'Crema de tomate', 'Tomatencremesuppe', 'soups_stews', 'lunch', 2, 9, 4, 'simmering', NW, diasporaFor(NW)),
  B('فطيرة يوركشير الثانية', 'Yorkshire Cheese Pie', 'Tourte fromage Yorkshire', 'Pastel de queso de Yorkshire', 'Yorkshire-Käsepastete', 'vegetable_mains', 'lunch', 9, 18, 12, 'baking', Y, diasporaFor(Y)),
  B('ملقم', 'Yorkshire Parkin', 'Parkin du Yorkshire', 'Parkin de Yorkshire', 'Yorkshire-Parkin', 'rice_cakes_sweets', 'snack', 2, 28, 9, 'baking', Y, diasporaFor(Y)),
  B('حساء الجزر في يوركشاير', 'Yorkshire Carrot Soup', 'Soupe carottes Yorkshire', 'Sopa de zanahoria de Yorkshire', 'Yorkshire-Karottensuppe', 'soups_stews', 'lunch', 2, 10, 3, 'simmering', Y, diasporaFor(Y)),
  B('صلصة الورد يوركشاير', 'Rose Cream', 'Creme a la rose', 'Crema de rosas', 'Rosencreme', 'condiments_sauces', 'snack', 1, 8, 12, 'mixing', Y, diasporaFor(Y)),
  B('كعك اللوزرابع', 'Yorkshire Almond Loaf', 'Pain amandes Yorkshire', 'Pan de almendras de Yorkshire', 'Yorkshire-Mandelbrot', 'rice_cakes_sweets', 'snack', 5, 24, 10, 'baking', Y, diasporaFor(Y)),
  B('حساء جبنة وينسليديل', 'Wensleydale Cream Soup', 'Veloute Wensleydale', 'Crema Wensleydale', 'Wensleydale-Cremesuppe', 'soups_stews', 'lunch', 3, 10, 6, 'simmering', Y, diasporaFor(Y)),
  B('مرق سوالديل', 'Swaledale Broth', 'Bouillon Swaledale', 'Caldo Swaledale', 'Swaledale-Brühe', 'soups_stews', 'lunch', 4, 10, 3, 'simmering', Y, diasporaFor(Y)),
  B('فطيرة يوركشاير الصغيرة', 'Yorkshire Patty', 'Galette de Yorkshire', 'Torta de Yorkshire', 'Yorkshire-Pastete', 'vegetable_mains', 'snack', 4, 20, 9, 'baking', Y, diasporaFor(Y)),
  B('كعك شاي يوركشاير', 'Yorkshire Teacake', 'Gateau thé du Yorkshire', 'Bizcocho de té de Yorkshire', 'Yorkshire-Teekuchen', 'rice_cakes_sweets', 'snack', 3, 28, 9, 'baking', Y, diasporaFor(Y)),
  B('مربى الفراولة يشور', 'Yorkshire Strawberry Jam', 'Confiture fraises Yorkshire', 'Mermelada de fresa de Yorkshire', 'Yorkshire-Erdbeergelee', 'condiments_sauces', 'snack', 0, 20, 0, 'boiling', Y, diasporaFor(Y)),
  B('حساء جبنة ثيرسك', 'Thirsk Cheese Soup', 'Veloute fromage Thirsk', 'Crema de queso Thirsk', 'Thirsk-Käsesuppe', 'soups_stews', 'lunch', 3, 10, 6, 'simmering', Y, diasporaFor(Y)),
  B('صلصة بودنج يوركشاير', 'Yorkshire Pudding Sauce', 'Sauce pour pudding Yorkshire', 'Salsa para pudin de Yorkshire', 'Yorkshire-Pudding-Sauce', 'condiments_sauces', 'snack', 2, 8, 6, 'simmering', Y, diasporaFor(Y)),
];
