import { B, diasporaFor } from '../uk-base-data/rows.mjs';

const SE = 'south_east';
const NW = 'north_west';

export default [
  B('تارت جبنة سليكوت', 'Sussex Slipcote Tart', 'Tarte au Slipcote', 'Tarta de Slipcote', 'Slipcote-Tarte', 'rice_cakes_sweets', 'snack', 5, 26, 12, 'baking', SE, diasporaFor(SE)),
  B('كعك العسل الكتني', 'Kentish Honey Cake', 'Gateau au miel du Kent', 'Bizcocho de miel de Kent', 'Kent-Honigkuchen', 'rice_cakes_sweets', 'snack', 3, 30, 8, 'baking', SE, diasporaFor(SE)),
  B('بودنج دبس ساسكس', 'Sussex Treacle Pudding', 'Pudding au melasse du Sussex', 'Pudin de melaza de Sussex', 'Sussex-Melasse-Pudding', 'rice_cakes_sweets', 'snack', 3, 30, 8, 'steaming', SE, diasporaFor(SE)),
  B('سلطة البطاطا الجديدة', 'New Potato Salad', 'Salade de nouvelles pommes de terre', 'Ensalada de patatas nuevas', 'Neue-Kartoffel-Salat', 'vegetable_mains', 'lunch', 3, 16, 6, 'boiling', SE, diasporaFor(SE)),
  B('كعك الصفيحة الساسكسي', 'Sussex Slab Cake', 'Gateau slab du Sussex', 'Bizcocho slab de Sussex', 'Sussex-Slabkuchen', 'rice_cakes_sweets', 'snack', 3, 28, 9, 'baking', SE, diasporaFor(SE)),
  B('حساء الكرفس بالكريمة', 'Cream of Celery Soup', 'Veloute de celeri a la creme', 'Crema de apio', 'Selleriecremesuppe', 'soups_stews', 'lunch', 2, 8, 4, 'simmering', SE, diasporaFor(SE)),
  B('حساء البازلاء والنعناع', 'Green Pea and Mint Soup', 'Soupe de petits pois verts a la menthe', 'Sopa de guisantes verdes y menta', 'Gruene-Erbsen-Minz-Suppe', 'soups_stews', 'lunch', 3, 9, 2, 'simmering', SE, diasporaFor(SE)),
  B('سلطة ورقية بالزيت', 'Dressed Leaf Salad', 'Salade verte assaisonnee', 'Ensalada verde aliñada', 'Angemachter Blattsalat', 'vegetable_mains', 'lunch', 2, 5, 4, 'tossing', SE, diasporaFor(SE)),
  B('فاصولي خضراء بالزيت', 'Dressed Green Beans', 'Haricots verts a l huile', 'Judias verdes con aceite', 'Gurkenbohnen mit Oel', 'vegetable_mains', 'dinner', 2, 6, 4, 'boiling', SE, diasporaFor(SE)),
  B('جزر مبشور بالليمون', 'Grated Carrot Salad', 'Salade de carottes rapees', 'Ensalada de zanahoria rallada', 'Geraffelte Karottensalat', 'vegetable_mains', 'lunch', 1, 8, 3, 'raw', SE, diasporaFor(SE)),
  B('مربى الفراولة', 'Strawberry Preserve', 'Confiture de fraises', 'Mermelada de fresa', 'Erdbeer-Gelee', 'condiments_sauces', 'snack', 0, 20, 0, 'boiling', SE, diasporaFor(SE)),
  B('مربى الخوخ', 'Peach Jam', 'Confiture de peaches', 'Mermelada de melocoton', 'Pfirsich-Gelee', 'condiments_sauces', 'snack', 0, 20, 0, 'boiling', SE, diasporaFor(SE)),
  B('صلصة الزنجبيل', 'Ginger Sauce', 'Sauce au gingembre', 'Salsa de jengibre', 'Ingwer-Sauce', 'condiments_sauces', 'snack', 0, 8, 0, 'simmering', SE, diasporaFor(SE)),
  B('صلصة الحل والخل', 'Brown Sugar and Vinegar Sauce', 'Sauce sucre brun et vinaigre', 'Salsa de azucar moreno y vinagre', 'Braunzucker-Essig-Sauce', 'condiments_sauces', 'snack', 0, 12, 0, 'simmering', SE, diasporaFor(SE)),
  B('شاي معتّق الأيرلندي', 'Spiced Black Tea', 'The noire aux epices', 'Tè negro especiado', 'Gewuerzter Schwarztee', 'beverages', 'snack', 0, 1, 0, 'brewing', SE, diasporaFor(SE)),
  B('كرواسون بالجبن', 'Cheese Croissant', 'Croissant au fromage', 'Croissant de queso', 'Kaese-Croissant', 'breakfast_items', 'breakfast', 7, 24, 12, 'baking', SE, diasporaFor(SE)),
  B('خبز الفين,),', 'Fougasse Bread', 'Pain de fougasse', 'Pan de fogasa', 'Fougasse-Brot', 'breakfast_items', 'breakfast', 6, 28, 3, 'baking', SE, diasporaFor(SE)),
  B('كعك اسفنجي بالليمون', 'Lemon Sponge Cake', 'Gateau epais au citron', 'Bizcocho esponjoso de limon', 'Zitronen-Biskuitkuchen', 'rice_cakes_sweets', 'snack', 3, 30, 10, 'baking', SE, diasporaFor(SE)),
  B('كاسي远处的', 'Sussex Apple Tart', 'Tarte pommes du Sussex', 'Tarta de manzana de Sussex', 'Sussex-Apfel-Tarte', 'rice_cakes_sweets', 'snack', 2, 28, 10, 'baking', SE, diasporaFor(SE)),
  B('شوربة قرنبيط بالجبنة', 'Cauliflower and Stilton Soup', 'Veloute chou-fleur au Stilton', 'Crema de coliflor con Stilton', 'Blumenkohl-Stilton-Suppe', 'soups_stews', 'lunch', 4, 10, 8, 'simmering', SE, diasporaFor(SE)),
  B('كوسا محشية بالأرز', 'Stuffed Courgettes with Rice', 'Courgettes farcies au riz', 'Calabacines rellenas de arroz', 'Gefuellte Zucchini mit Reis', 'vegetable_mains', 'dinner', 4, 18, 6, 'baking', SE, diasporaFor(SE)),
  B('قرنبيط بالبارميزان', 'Cauliflower with Parmesan', 'Chou-fleur au parmesan', 'Coliflor con parmesano', 'Blumenkohl mit Parmesan', 'vegetable_mains', 'dinner', 6, 8, 9, 'roasting', SE, diasporaFor(SE)),
  B('فطيرة السبانخ', 'Spinach and Feta Pie', 'Tourte aux epinards et feta', 'Pastel de espinacas y feta', 'Spinat-Feta-Pastete', 'vegetable_mains', 'dinner', 6, 16, 12, 'baking', SE, diasporaFor(SE)),
  B('سلطة الفلفل', 'Roasted Pepper Salad', 'Salade de poivrons grilles', 'Ensalada de pimientos asados', 'Geröstete Paprikasalat', 'vegetable_mains', 'lunch', 1, 8, 6, 'roasting', SE, diasporaFor(SE)),
  B('كوسة مقطعة في الفرن', 'Baked Courgette Slices', 'Courgettes au four', 'Calabacines al horno', 'Ofengebackene Zucchini', 'vegetable_mains', 'dinner', 2, 7, 4, 'baking', SE, diasporaFor(SE)),
  B('بياز是通过', 'Ratatouille', 'Ratatouille', 'Ratatouille', 'Ratatouille', 'vegetable_mains', 'dinner', 2, 10, 8, 'stewing', SE, diasporaFor(SE)),
  B('صلصة الريحان بالخبز', 'Basil Bread Sauce', 'Sauge basilic au pain', 'Salsa de albahaca con pan', 'Basilikum-Brot-Sauce', 'condiments_sauces', 'snack', 1, 10, 6, 'mixing', SE, diasporaFor(SE)),
  B('بودنج الخبز بالتين', 'Bread Pudding with Sultanas', 'Pudding au pain et raisins secs', 'Pudin de pan con pasas', 'Brotenpudding mit Sultaninen', 'rice_cakes_sweets', 'snack', 4, 26, 7, 'baking', SE, diasporaFor(SE)),
  B('تارت التفاح والنعناع', 'Apple and Mint Tart', 'Tarte pommes et menthe', 'Tarta de manzana y menta', 'Apfel-Minz-Tarte', 'rice_cakes_sweets', 'snack', 1, 28, 8, 'baking', SE, diasporaFor(SE)),
  B('مرق اللحم بالخضار', 'Gravy with Vegetables', 'Gravy aux legumes', 'Sopa de carne con verduras', 'Gemüse-Gravy', 'condiments_sauces', 'snack', 2, 4, 4, 'simmering', SE, diasporaFor(SE)),
  B('سلطة الشمندر الساخنة', 'Warm Beetroot Salad', 'Salade de betteraves tiede', 'Ensalada de remolacha tibia', 'Warme Rot-Bete-Salat', 'vegetable_mains', 'lunch', 2, 9, 5, 'roasting', SE, diasporaFor(SE)),
  B('كعكة الطحين', 'Shortcrust Pastry Case', 'Pate brisee', 'Masa quebrada', 'Mürbeteigboden', 'rice_cakes_sweets', 'snack', 3, 30, 10, 'baking', SE, diasporaFor(SE)),
  B('فاكهة المطعم', 'Poached Fruit Compote', 'Compote de fruits pochés', 'Compota de frutas pochadas', 'Pochiertes Obst', 'fruit', 'snack', 1, 16, 0, 'simmering', SE, diasporaFor(SE)),
  B('شوربة الكارنب بالليمون', 'Cabbage and Lemon Soup', 'Soupe chou citron', 'Sopa de col con limon', 'Kohl-Zitronen-Suppe', 'soups_stews', 'lunch', 2, 9, 3, 'simmering', SE, diasporaFor(SE)),
  B('فطيرة البطاطا واللحم', 'Lancashire Potato and Meat Pie', 'Tourte pommes de terre viande', 'Pastel de patatas y carne', 'Kartoffel-Fleisch-Pastete', 'meat_mains', 'dinner', 11, 20, 11, 'baking', NW, diasporaFor(NW)),
  B('كرواسون بالشوكولا', 'Chocolate Croissant', 'Croissant au chocolat', 'Croissant de chocolate', 'Schokoladen-Croissant', 'rice_cakes_sweets', 'snack', 6, 28, 14, 'baking', NW, diasporaFor(NW)),
  B('كعك الأرز', 'Rice Cake', 'Gateau de riz', 'Bizcocho de arroz', 'Reiskuchen', 'rice_cakes_sweets', 'snack', 3, 26, 9, 'baking', NW, diasporaFor(NW)),
  B('شوربة اللحم الكاملة', 'Nettle Soup', 'Soupe d orties', 'Sopa de ortiga', 'Nesselsuppe', 'soups_stews', 'lunch', 3, 8, 3, 'simmering', NW, diasporaFor(NW)),
  B('سلطة الجزر', 'Carrot Salad', 'Salade de carottes', 'Ensalada de zanahoria', 'Karottensalat', 'vegetable_mains', 'lunch', 1, 10, 5, 'raw', NW, diasporaFor(NW)),
  B('خبز بذور الكتان الثاني', 'Seeded Rye Loaf', 'Pain de seigle aux graines', 'Pan de centeno con semillas', 'Roggenbrot mit Kernen', 'breakfast_items', 'breakfast', 7, 26, 4, 'baking', NW, diasporaFor(NW)),
  B('فلان جبنة لانكشاير', 'Lancashire Cheese Flan', 'Tourte fromage Lancashire', 'Flan de queso Lancashire', 'Lancashire-Kaeseflan', 'vegetable_mains', 'dinner', 8, 16, 13, 'baking', NW, diasporaFor(NW)),
  B('بودنج الأرز بزبدة اللوز', 'Rice Pudding with Almonds', 'Riz au lait aux amandes', 'Arroz con leche y almendras', 'Milchreis mit Mandeln', 'rice_cakes_sweets', 'snack', 4, 20, 5, 'baking', NW, diasporaFor(NW)),
  B('تارت الكريمة', 'Custard Tart', 'Tarte a la creme', 'Tarta de crema', 'Creme-Torte', 'rice_cakes_sweets', 'snack', 4, 28, 11, 'baking', NW, diasporaFor(NW)),
  B('سلطة البصل والخل', 'Onion and Vinegar Salad', 'Salade oignons vinaigre', 'Ensalada de cebolla y vinagre', 'Zwiebel-Essig-Salat', 'vegetable_mains', 'lunch', 1, 8, 4, 'raw', NW, diasporaFor(NW)),
  B('شوربة اللحم الاسكتلندي', 'Scotch Broth Lamb', 'Bouillon d agneau', 'Caldo de cordero', 'Lammbouillon', 'soups_stews', 'lunch', 10, 8, 4, 'simmering', NW, diasporaFor(NW)),
  B('كعك الفاصولي', 'Bean Cake', 'Gateau aux haricots', 'Bizcocho de judias', 'Bohnenkuchen', 'rice_cakes_sweets', 'snack', 5, 24, 8, 'baking', NW, diasporaFor(NW)),
  B('فطيرة رقيق بالتفاح', 'Apple Pastry Strip', 'Bandelette de paste pommes', 'Tira de pastel de manzana', 'Apfelgebäck-Streifen', 'rice_cakes_sweets', 'snack', 2, 28, 9, 'baking', NW, diasporaFor(NW)),
  B('صلصة لانكشاير', ' Lancashire Sauce', 'Sauce Lancashire', 'Salsa Lancashire', 'Lancashire-Sauce', 'condiments_sauces', 'snack', 1, 6, 8, 'simmering', NW, diasporaFor(NW)),
  B('شوربة الجزرمانشستر', 'Manchester Carrot Soup', 'Soupe carottes de Manchester', 'Sopa de zanahoria de Manchester', 'Manchester-Karottensuppe', 'soups_stews', 'lunch', 2, 10, 3, 'simmering', NW, diasporaFor(NW)),
  B('خبز الشوفان الاسكتلندي الثاني', 'Rolled Oat Loaf', 'Pain d avoine roule', 'Pan de avena enrollado', 'Gerollter Haferlaib', 'breakfast_items', 'breakfast', 6, 24, 5, 'baking', NW, diasporaFor(NW)),
];
