import { B, diasporaFor } from './rows.mjs';

export default [
  // ---- new_england (4) ----
  B('فطيرة جبن أمريكية', 'Cheesecake', 'Cheesecake americain', 'Tarta de queso americana', 'Amerikanischer Käsekuchen', 'rice_cakes_sweets', 'snack', 8, 24, 18, 'baked', 'new_england', diasporaFor('new_england')),
  B('شوربة طماطم أمريكية', 'Tomato soup', 'Soupe de tomate americaine', 'Sopa de tomate americana', 'Amerikanische Tomatensuppe', 'soups_stews', 'lunch', 3, 14, 4, 'simmered', 'new_england', diasporaFor('new_england')),
  B('بودينغ أرز أمريكي', 'Rice pudding', 'Pudding de riz americain', 'Arroz con leche americano', 'Amerikanischer Reispudding', 'rice_cakes_sweets', 'snack', 4, 24, 6, 'simmered', 'new_england', diasporaFor('new_england')),
  B('دونات أمريكية', 'Donuts', 'Beignets americains', 'Donas americana', 'Amerikanische Donuts', 'street_snacks', 'snack', 5, 28, 12, 'deep-fried', 'new_england', diasporaFor('new_england')),
  // ---- mid_atlantic (14) ----
  B('تشيز ستيك فيلادلفيا أمريكي', 'Philly cheesesteak', 'Cheesesteak de Philadelphie americain', 'Cheesesteak de Filadelfia americano', 'Amerikanischer Philly Cheesesteak', 'meat_mains', 'lunch', 20, 18, 18, 'griddled', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('بريتزل ناعم أمريكي', 'Soft pretzel', 'Bretzel moelleux americain', 'Pretzel suave americano', 'Amerikanischer Weichbrezel', 'street_snacks', 'snack', 8, 30, 4, 'baked', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('بيتزا نيويورك أمريكي', 'New York pizza', 'Pizza de New York americaine', 'Pizza de Nueva York americana', 'Amerikanische New-York-Pizza', 'street_snacks', 'lunch', 14, 32, 12, 'baked', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('كراب كيك ماريلاند أمريكي', 'Maryland crab cake', 'Galette de crabe du Maryland americaine', 'Pastelito de cangrejo de Maryland americano', 'Amerikanischer Maryland-Krabbenkuchen', 'fish_seafood', 'lunch', 14, 12, 12, 'pan-fried', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('بافالو وينغز أمريكي', 'Buffalo wings', 'Ailes de Buffalo americaines', 'Alitas de Buffalo americano', 'Amerikanische Buffalo-Wings', 'poultry_mains', 'lunch', 18, 4, 16, 'deep-fried', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('باسترامي ساندويتش أمريكي', 'English', 'French', 'Spanish', 'German', 'meat_mains', 'lunch', 18, 20, 12, 'steamed', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('ريز بيلاف أمريكي', 'Rice pilaf', 'Pilaf de riz americain', 'Pilaf de arroz americano', 'Amerikanischer Reispilaf', 'rice_dishes', 'lunch', 5, 28, 4, 'simmered', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('تشيز كيك نيويورك أمريكي', 'New York cheesecake', 'Cheesecake de New York americain', 'Tarta de queso de Nueva York americana', 'Amerikanischer New-York-Käsekuchen', 'rice_cakes_sweets', 'snack', 8, 24, 18, 'baked', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('أونيون رينغز أمريكي', 'Onion rings', 'Rondelles d oignon americaines', 'Aros de cebolla americano', 'Amerikanische Onion Rings', 'street_snacks', 'snack', 4, 24, 12, 'deep-fried', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('تشيكن بارميزان أمريكي', 'Chicken parmesan', 'Poulet parmesan americain', 'Pollo parmesano americano', 'Amerikanischer Hähnchen-Parmesan', 'poultry_mains', 'dinner', 20, 16, 16, 'baked', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('سباغيتي بولونيز أمريكي', 'Spaghetti bolognese', 'Spaghetti bolognaise americains', 'Espagueti boloñesa americano', 'Amerikanische Spaghetti Bolognese', 'noodle_dishes', 'dinner', 14, 30, 12, 'simmered', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('مكرونة جبن أمريكية', 'Macaroni cheese', 'Macaroni au fromage americain', 'Macarrones con queso americano', 'Amerikanische Macaroni-Käse', 'noodle_dishes', 'lunch', 12, 28, 14, 'baked', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('سلطة بطاطس أمريكية', 'Potato salad', 'Salade de pommes de terre americaine', 'Ensalada de papas americana', 'Amerikanischer Kartoffelsalat', 'vegetable_mains', 'lunch', 3, 18, 10, 'boiled', 'mid_atlantic', diasporaFor('mid_atlantic')),
  B('فطيرة ليمون أمريكية', 'Lemon pie', 'Tarte au citron americaine', 'Tarta de limón americana', 'Amerikanischer Zitronenkuchen', 'rice_cakes_sweets', 'snack', 4, 30, 10, 'baked', 'mid_atlantic', diasporaFor('mid_atlantic')),
  // ---- south (14) ----
  B('دجاج مقلي جنوبي أمريكي', 'Southern fried chicken', 'Poulet frit du Sud americain', 'Pollo frito sureño americano', 'Amerikanisches Southern Fried Chicken', 'poultry_mains', 'lunch', 18, 12, 16, 'deep-fried', 'south', diasporaFor('south')),
  B('بيسكويت وجراف أمريكي', 'Biscuits and gravy', 'Biscuits et sauce americains', 'Galletas con salsa americana', 'Amerikanischen Biscuits mit Gravy', 'breakfast_items', 'breakfast', 8, 24, 12, 'baked', 'south', diasporaFor('south')),
  B('جريت جنوبي أمريكي', 'Southern grits', 'Grits du Sud americains', 'Sémola sureña americana', 'Amerikanische Southern Grits', 'breakfast_items', 'breakfast', 3, 16, 2, 'simmered', 'south', diasporaFor('south')),
  B('كولارد جرينز أمريكي', 'Collard greens', 'Chou vert du Sud americain', 'Col rizada sureña americana', 'Amerikanische Southern Collard Greens', 'vegetable_mains', 'lunch', 4, 8, 2, 'simmered', 'south', diasporaFor('south')),
  B('طماطم خضراء مقلية أمريكية', 'Fried green tomatoes', 'Tomates vertes frites americaines', 'Tomates verdes fritos americano', 'Amerikanische fritierte grüne Tomaten', 'vegetable_mains', 'lunch', 4, 16, 10, 'pan-fried', 'south', diasporaFor('south')),
  B('هش بابيز أمريكي', 'Hush puppies', 'Beignets de maïs americains', 'Buñuelos de maíz americano', 'Amerikanische Hush Puppies', 'street_snacks', 'snack', 4, 22, 10, 'deep-fried', 'south', diasporaFor('south')),
  B('بودينغ موز أمريكي', 'Banana pudding', 'Pudding de banane americain', 'Pudín de plátano americano', 'Amerikanischer Bananenpudding', 'rice_cakes_sweets', 'snack', 4, 26, 8, 'baked', 'south', diasporaFor('south')),
  B('بيتزا دجاج أمريكية', 'Chicken pot pie', 'Tourte au poulet americaine', 'Pastel de pollo americano', 'Amerikanischer Hähnchenpastete', 'poultry_mains', 'dinner', 14, 20, 14, 'baked', 'south', diasporaFor('south')),
  B('روبيان جريت أمريكي', 'Shrimp and grits', 'Crevettes et grits americains', 'Camarones con sémola americano', 'Amerikanische Garnelen mit Grits', 'fish_seafood', 'lunch', 14, 18, 10, 'simmered', 'south', diasporaFor('south')),
  B('لحم بقري مفروم جنوبي أمريكي', 'Southern meatloaf', 'Pain de viande du Sud americain', 'Pastel de carne sureño americano', 'Amerikanischer Southern Hackbraten', 'meat_mains', 'dinner', 17, 10, 15, 'baked', 'south', diasporaFor('south')),
  B('بطاطا حلوة أمريكية', 'Sweet potato casserole', 'Gratin de patates douces americain', 'Cazuela de batata americana', 'Amerikanischer Süßkartoffelauflauf', 'vegetable_mains', 'lunch', 3, 24, 6, 'baked', 'south', diasporaFor('south')),
  B('فطيرة خوخ أمريكية', 'Peach cobbler', 'Cobbler de peche americain', 'Cobbler de durazno americano', 'Amerikanischer Pfirsich-Cobbler', 'rice_cakes_sweets', 'snack', 4, 30, 8, 'baked', 'south', diasporaFor('south')),
  B('بازلاء سوداء أمريكية', 'Black-eyed peas', 'Haricots à œil noir americains', 'Frijoles de ojo negro americano', 'Amerikanische Augenbohnen', 'vegetable_mains', 'lunch', 8, 18, 2, 'simmered', 'south', diasporaFor('south')),
  B('كيك جزر أمريكي', 'Carrot cake', 'Gâteau de carotte americain', 'Pastel de zanahoria americano', 'Amerikanischer Möhrenkuchen', 'rice_cakes_sweets', 'snack', 5, 28, 12, 'baked', 'south', diasporaFor('south')),
  // ---- deep_south (14) ----
  B('غومبو أمريكي', 'Gumbo', 'Gumbo americain', 'Gumbo americano', 'Amerikanisches Gumbo', 'soups_stews', 'dinner', 12, 10, 8, 'simmered', 'deep_south', diasporaFor('deep_south')),
  B('جامبالايا أمريكي', 'Jambalaya', 'Jambalaya americain', 'Jambalaya americano', 'Amerikanisches Jambalaya', 'rice_dishes', 'dinner', 14, 24, 10, 'simmered', 'deep_south', diasporaFor('deep_south')),
  B('ديري رايز أمريكي', 'Dirty rice', 'Riz sale americain', 'Arroz sucio americano', 'Amerikanisches Dirty Rice', 'rice_dishes', 'lunch', 8, 24, 6, 'simmered', 'deep_south', diasporaFor('deep_south')),
  B('بيجن أمريكي', 'Beignets', 'Beignets americains', 'Beignets americano', 'Amerikanische Beignets', 'street_snacks', 'snack', 5, 28, 12, 'deep-fried', 'deep_south', diasporaFor('deep_south')),
  B('بريد بودينغ أمريكي', 'Bread pudding', 'Pudding de pain americain', 'Budín de pan americano', 'Amerikanischer Brotpudding', 'rice_cakes_sweets', 'snack', 6, 26, 10, 'baked', 'deep_south', diasporaFor('deep_south')),
  B('فطيرة جوز أمريكية', 'Pecan pie', 'Tarte aux noix de pecan americaine', 'Tarta de nuez americana', 'Amerikanischer Pekannusskuchen', 'rice_cakes_sweets', 'snack', 4, 32, 14, 'baked', 'deep_south', diasporaFor('deep_south')),
  B('سجق لحم بقري ديب ساوث أمريكي', 'Deep South beef sausage', 'Saucisse de boeuf du Sud americaine', 'Salchicha de res sureña americana', 'Amerikanische Deep-South-Rindswurst', 'meat_mains', 'lunch', 14, 2, 16, 'grilled', 'deep_south', diasporaFor('deep_south')),
  B('دجاج بالفرن ديب ساوث أمريكي', 'Deep South baked chicken', 'Poulet au four du Sud americain', 'Pollo al horno sureño americano', 'Amerikanisches Deep-South-Brathähnchen', 'poultry_mains', 'dinner', 20, 4, 12, 'baked', 'deep_south', diasporaFor('deep_south')),
  B('بطاطا مهروسة ديب ساوث أمريكية', 'Deep South mashed potatoes', 'Purée du Sud americaine', 'Puré sureño americano', 'Amerikanisches Deep-South-Kartoffelpüree', 'vegetable_mains', 'lunch', 3, 18, 6, 'boiled', 'deep_south', diasporaFor('deep_south')),
  B('فول سوداني أمريكي', 'Boiled peanuts', 'Cacahuètes bouillies americaines', 'Cacahuetes hervidos americano', 'Amerikanische gekochte Erdnüsse', 'street_snacks', 'snack', 8, 8, 12, 'boiled', 'deep_south', diasporaFor('deep_south')),
  B('كيك بريد أمريكي', 'Pound cake', 'Gâteau quatre-quarts americain', 'Pastel de libra americano', 'Amerikanischer Rührkuchen', 'rice_cakes_sweets', 'snack', 6, 28, 12, 'baked', 'deep_south', diasporaFor('deep_south')),
  B('شوربة طماطم ديب ساوث أمريكية', 'Deep South tomato soup', 'Soupe de tomate du Sud americaine', 'Sopa de tomate sureña americana', 'Amerikanische Deep-South-Tomatensuppe', 'soups_stews', 'lunch', 3, 14, 4, 'simmered', 'deep_south', diasporaFor('deep_south')),
  B('سلمون ديب ساوث أمريكي', 'Deep South salmon', 'Saumon du Sud americain', 'Salmón sureño americano', 'Amerikanischer Deep-South-Lachs', 'fish_seafood', 'dinner', 20, 2, 12, 'grilled', 'deep_south', diasporaFor('deep_south')),
  B('بودينغ شوكولاتة أمريكي', 'Chocolate pudding', 'Pudding au chocolat americain', 'Pudín de chocolate americano', 'Amerikanischer Schokoladenpudding', 'rice_cakes_sweets', 'snack', 4, 24, 6, 'simmered', 'deep_south', diasporaFor('deep_south')),
  // ---- cajun (4) ----
  B('إيتوفيه أمريكي', 'Crawfish étouffée', 'Étouffée d écrevisses americaine', 'Étouffée de cangrejo americano', 'Amerikanische Crawfish-Étouffée', 'fish_seafood', 'dinner', 14, 12, 10, 'simmered', 'cajun', diasporaFor('cajun')),
  B('ريد بينز أند رايز أمريكي', 'Red beans and rice', 'Haricots rouges et riz americains', 'Frijoles rojos con arroz americano', 'Amerikanische Rote Bohnen mit Reis', 'rice_dishes', 'lunch', 10, 26, 4, 'simmered', 'cajun', diasporaFor('cajun')),
  B('بودين لحم بقري أمريكي', 'Beef boudin', 'Boudin de boeuf americain', 'Boudin de res americano', 'Amerikanischer Rindfleisch-Boudin', 'meat_mains', 'lunch', 14, 8, 14, 'steamed', 'cajun', diasporaFor('cajun')),
  B('سجق لحم بقري كاجن أمريكي', 'Cajun beef sausage', 'Saucisse de boeuf cajun americaine', 'Salchicha de res cajún americana', 'Amerikanische Cajun-Rindswurst', 'meat_mains', 'lunch', 14, 2, 16, 'grilled', 'cajun', diasporaFor('cajun')),
];
