import { B, diasporaFor } from './rows.mjs';

export default [
  // ---- pan_american (40) ----
  B('بانكيك أمريكي', 'American pancakes', 'Pancakes americaines', 'Panqueques americanos', 'Amerikanische Pfannkuchen', 'breakfast_items', 'breakfast', 6, 25, 8, 'griddled', 'pan_american', diasporaFor('pan_american')),
  B('وافل أمريكي', 'American waffles', 'Gaufres americanas', 'Waffles americanos', 'Amerikanische Waffeln', 'breakfast_items', 'breakfast', 7, 28, 9, 'baked', 'pan_american', diasporaFor('pan_american')),
  B('فرنش توست أمريكي', 'French toast', 'Pain perdu americain', 'Tostada francesa americana', 'Amerikanischer French Toast', 'breakfast_items', 'breakfast', 8, 22, 7, 'griddled', 'pan_american', diasporaFor('pan_american')),
  B('شوفان أمريكي', 'Oatmeal', 'Flocons d avoine americains', 'Avena americana', 'Amerikanische Haferflocken', 'breakfast_items', 'breakfast', 5, 18, 3, 'simmered', 'pan_american', diasporaFor('pan_american')),
  B('بوريتو فطار أمريكي', 'Breakfast burrito', 'Burrito du petit-dejeuner americain', 'Burrito de desayuno americano', 'Amerikanisches Frühstücksburrito', 'breakfast_items', 'breakfast', 12, 24, 10, 'griddled', 'pan_american', diasporaFor('pan_american')),
  B('أومليت بيض أمريكي', 'American omelette', 'Omelette americaine', 'Omelette americano', 'Amerikanisches Omelett', 'breakfast_items', 'breakfast', 14, 3, 12, 'pan-fried', 'pan_american', diasporaFor('pan_american')),
  B('جريت أمريكي', 'Grits', 'Grits americains', 'Sémola de maíz americana', 'Amerikanische Grießbrei', 'breakfast_items', 'breakfast', 3, 16, 1, 'simmered', 'pan_american', diasporaFor('pan_american')),
  B('بيكون ديك رومي أمريكي', 'Turkey bacon', 'Bacon de dinde americain', 'Tocino de pavo americano', 'Amerikanischer Puten-Speck', 'breakfast_items', 'breakfast', 10, 1, 8, 'pan-fried', 'pan_american', diasporaFor('pan_american')),
  B('سجق لحم بقري أمريكي', 'Beef sausage', 'Saucisse de boeuf americaine', 'Salchicha de res americana', 'Amerikanische Rindswurst', 'breakfast_items', 'breakfast', 12, 2, 14, 'pan-fried', 'pan_american', diasporaFor('pan_american')),
  B('بطاطس مهروسة أمريكية', 'Mashed potatoes', 'Purée de pommes de terre americaine', 'Puré de papas americano', 'Amerikanisches Kartoffelpüree', 'vegetable_mains', 'lunch', 3, 18, 6, 'boiled', 'pan_american', diasporaFor('pan_american')),
  B('برجر لحم بقري أمريكي', 'Cheeseburger', 'Cheeseburger americain', 'Hamburguesa con queso americana', 'Amerikanischer Cheeseburger', 'meat_mains', 'lunch', 16, 20, 18, 'grilled', 'pan_american', diasporaFor('pan_american')),
  B('هوت دوج لحم بقري أمريكي', 'Beef hot dog', 'Hot-dog de boeuf americain', 'Perro caliente de res americano', 'Amerikanischer Rind-Hotdog', 'street_snacks', 'lunch', 11, 18, 12, 'grilled', 'pan_american', diasporaFor('pan_american')),
  B('دجاج مقلي أمريكي', 'Fried chicken', 'Poulet frit americain', 'Pollo frito americano', 'Amerikanisches Brathähnchen', 'poultry_mains', 'lunch', 18, 12, 16, 'deep-fried', 'pan_american', diasporaFor('pan_american')),
  B('لحم مفروم مشوي أمريكي', 'Meatloaf', 'Pain de viande americain', 'Pastel de carne americano', 'Amerikanischer Hackbraten', 'meat_mains', 'dinner', 17, 10, 15, 'baked', 'pan_american', diasporaFor('pan_american')),
  B('ماك أند تشيز أمريكي', 'Mac and cheese', 'Macaroni au fromage americain', 'Macarrones con queso americano', 'Amerikanische Mac and Cheese', 'noodle_dishes', 'lunch', 12, 28, 14, 'baked', 'pan_american', diasporaFor('pan_american')),
  B('كول سلو أمريكي', 'Coleslaw', 'Salade de chou americaine', 'Ensalada de col americana', 'Amerikanischer Krautsalat', 'vegetable_mains', 'lunch', 2, 10, 8, 'raw', 'pan_american', diasporaFor('pan_american')),
  B('كورن بريد أمريكي', 'Cornbread', 'Pain de maïs americain', 'Pan de maíz americano', 'Amerikanisches Maisbrot', 'street_snacks', 'lunch', 5, 24, 6, 'baked', 'pan_american', diasporaFor('pan_american')),
  B('ستيك لحم بقري أمريكي', 'Grilled steak', 'Steak grille americain', 'Bistec asado americano', 'Amerikanisches gegrilltes Steak', 'meat_mains', 'dinner', 24, 0, 18, 'grilled', 'pan_american', diasporaFor('pan_american')),
  B('ريز لحم بقري أمريكي', 'Beef ribs', 'Côtes de boeuf americaines', 'Costillas de res americana', 'Amerikanische Rinderrippen', 'meat_mains', 'dinner', 20, 4, 20, 'smoked', 'pan_american', diasporaFor('pan_american')),
  B('دجاج مشوي أمريكي', 'Roast chicken', 'Poulet rôti americain', 'Pollo asado americano', 'Amerikanisches Brathähnchen', 'poultry_mains', 'dinner', 22, 2, 14, 'roasted', 'pan_american', diasporaFor('pan_american')),
  B('سلمون مشوي أمريكي', 'Grilled salmon', 'Saumon grille americain', 'Salmón a la parrilla americano', 'Amerikanischer gegrillter Lachs', 'fish_seafood', 'dinner', 22, 0, 14, 'grilled', 'pan_american', diasporaFor('pan_american')),
  B('روبيان مقلي أمريكي', 'Fried shrimp', 'Crevettes frites americaines', 'Camarones fritos americano', 'Amerikanische fritierte Garnelen', 'fish_seafood', 'lunch', 16, 14, 12, 'deep-fried', 'pan_american', diasporaFor('pan_american')),
  B('سلطة سيزر أمريكية', 'Caesar salad', 'Salade César americaine', 'Ensalada César americana', 'Amerikanischer Caesarsalat', 'vegetable_mains', 'lunch', 8, 8, 12, 'raw', 'pan_american', diasporaFor('pan_american')),
  B('شوربة دجاج أمريكية', 'Chicken noodle soup', 'Soupe de poulet americaine', 'Sopa de pollo americana', 'Amerikanische Hühnernudelsuppe', 'soups_stews', 'lunch', 8, 12, 4, 'simmered', 'pan_american', diasporaFor('pan_american')),
  B('تشيلي لحم بقري أمريكي', 'Beef chili', 'Chili de boeuf americain', 'Chili de res americano', 'Amerikanischer Rindfleisch-Chili', 'soups_stews', 'dinner', 16, 12, 12, 'simmered', 'pan_american', diasporaFor('pan_american')),
  B('بيتزا أمريكية', 'Pizza', 'Pizza americaine', 'Pizza americana', 'Amerikanische Pizza', 'street_snacks', 'lunch', 14, 30, 12, 'baked', 'pan_american', diasporaFor('pan_american')),
  B('باستا أمريكية', 'Pasta', 'Pâtes americaines', 'Pasta americana', 'Amerikanische Pasta', 'noodle_dishes', 'dinner', 10, 32, 6, 'boiled', 'pan_american', diasporaFor('pan_american')),
  B('تاكو لحم بقري أمريكي', 'Beef taco', 'Taco de boeuf americain', 'Taco de res americano', 'Amerikanischer Rindfleisch-Taco', 'street_snacks', 'lunch', 14, 18, 12, 'grilled', 'pan_american', diasporaFor('pan_american')),
  B('بوريتو لحم بقري أمريكي', 'Beef burrito', 'Burrito de boeuf americain', 'Burrito de res americano', 'Amerikanischer Rindfleisch-Burrito', 'street_snacks', 'lunch', 16, 26, 14, 'grilled', 'pan_american', diasporaFor('pan_american')),
  B('ساندويتش لحم بقري أمريكي', 'Roast beef sandwich', 'Sandwich de boeuf americain', 'Sándwich de rosbif americano', 'Amerikanisches Rindfleisch-Sandwich', 'meat_mains', 'lunch', 18, 22, 10, 'roasted', 'pan_american', diasporaFor('pan_american')),
  B('فطيرة تفاح أمريكية', 'Apple pie', 'Tarte aux pommes americaine', 'Tarta de manzana americana', 'Amerikanischer Apfelkuchen', 'rice_cakes_sweets', 'snack', 4, 32, 12, 'baked', 'pan_american', diasporaFor('pan_american')),
  B('كوكيز أمريكي', 'Chocolate chip cookies', 'Cookies americains', 'Galletas de chocolate americana', 'Amerikanische Schokoladenkekse', 'rice_cakes_sweets', 'snack', 4, 28, 12, 'baked', 'pan_american', diasporaFor('pan_american')),
  B('براونيز أمريكي', 'Brownies', 'Brownies americains', 'Brownies americano', 'Amerikanische Brownies', 'rice_cakes_sweets', 'snack', 5, 26, 14, 'baked', 'pan_american', diasporaFor('pan_american')),
  B('تشيز كيك أمريكي', 'Cheesecake', 'Cheesecake americain', 'Tarta de queso americana', 'Amerikanischer Käsekuchen', 'rice_cakes_sweets', 'snack', 8, 24, 18, 'baked', 'pan_american', diasporaFor('pan_american')),
  B('آيس كريم أمريكي', 'Ice cream', 'Glace americaine', 'Helado americano', 'Amerikanisches Eis', 'rice_cakes_sweets', 'snack', 4, 22, 12, 'frozen', 'pan_american', diasporaFor('pan_american')),
  B('صوص باربيكيو أمريكي', 'BBQ sauce', 'Sauce barbecue americaine', 'Salsa barbacoa americana', 'Amerikanische BBQ-Sauce', 'condiments_sauces', 'lunch', 1, 18, 0, 'simmered', 'pan_american', diasporaFor('pan_american')),
  B('كيك لحم بقري أمريكي', 'Ketchup', 'Ketchup americain', 'Kétchup americano', 'Amerikanischer Ketchup', 'condiments_sauces', 'lunch', 1, 12, 0, 'simmered', 'pan_american', diasporaFor('pan_american')),
  B('رانش أمريكي', 'Ranch dressing', 'Sauce ranch americaine', 'Aderezo ranch americano', 'Amerikanische Ranch-Dressing', 'condiments_sauces', 'lunch', 1, 4, 14, 'mixed', 'pan_american', diasporaFor('pan_american')),
  B('شاي مثلج أمريكي', 'Sweet tea', 'Thé glacé americain', 'Té helado americano', 'Amerikanischer Eistee', 'beverages', 'lunch', 0, 12, 0, 'brewed', 'pan_american', diasporaFor('pan_american')),
  B('ليموناضة أمريكية', 'Lemonade', 'Limonade americaine', 'Limonada americana', 'Amerikanische Limonade', 'beverages', 'lunch', 0, 10, 0, 'mixed', 'pan_american', diasporaFor('pan_american')),
  // ---- new_england (10) ----
  B('شوربة كلام أمريكية', 'Clam chowder', 'Soupe de palourdes americaine', 'Sopa de almejas americana', 'Amerikanische Muschelsuppe', 'soups_stews', 'lunch', 8, 14, 10, 'simmered', 'new_england', diasporaFor('new_england')),
  B('لوبستر رول أمريكي', 'Lobster roll', 'Rouleau de homard americain', 'Rollo de langosta americano', 'Amerikanischer Hummer-Rolle', 'fish_seafood', 'lunch', 16, 20, 12, 'steamed', 'new_england', diasporaFor('new_england')),
  B('كراب كيك أمريكي', 'Crab cakes', 'Galettes de crabe americaines', 'Pastelitos de cangrejo americano', 'Amerikanische Krabbenkuchen', 'fish_seafood', 'lunch', 14, 12, 12, 'pan-fried', 'new_england', diasporaFor('new_england')),
  B('بوسطن بينز أمريكي', 'Boston baked beans', 'Haricots cuits americains', 'Frijoles horneados americano', 'Amerikanische Bohnen', 'vegetable_mains', 'lunch', 8, 22, 2, 'baked', 'new_england', diasporaFor('new_england')),
  B('براون بريد أمريكي', 'Brown bread', 'Pain brun americain', 'Pan moreno americano', 'Amerikanisches Vollkornbrot', 'street_snacks', 'lunch', 6, 24, 3, 'baked', 'new_england', diasporaFor('new_england')),
  B('سيدر تفاح أمريكي', 'Apple cider', 'Cidre de pomme americain', 'Sidra de manzana americana', 'Amerikanischer Apfelmost', 'beverages', 'lunch', 0, 12, 0, 'pressed', 'new_england', diasporaFor('new_england')),
  B('كيك مابل أمريكي', 'Maple cake', 'Gâteau d érable americain', 'Pastel de arce americano', 'Amerikanischer Ahornkuchen', 'rice_cakes_sweets', 'snack', 5, 30, 10, 'baked', 'new_england', diasporaFor('new_england')),
  B('سلمون مدخن أمريكي', 'Smoked salmon', 'Saumon fumé americain', 'Salmón ahumado americano', 'Amerikanischer Räucherlachs', 'fish_seafood', 'lunch', 20, 0, 10, 'smoked', 'new_england', diasporaFor('new_england')),
  B('بلح البحر أمريكي', 'Steamed clams', 'Palourdes vapeur americaines', 'Almejas al vapor americano', 'Amerikanische gedämpfte Muscheln', 'fish_seafood', 'lunch', 14, 4, 4, 'steamed', 'new_england', diasporaFor('new_england')),
  B('فطيرة توت أمريكية', 'Berry pie', 'Tarte aux baies americaine', 'Tarta de bayas americana', 'Amerikanischer Beerenkuchen', 'rice_cakes_sweets', 'snack', 4, 30, 10, 'baked', 'new_england', diasporaFor('new_england')),
  B('كيك جوز هند أمريكي', 'Coconut cake', 'Gâteau de coco americain', 'Pastel de coco americano', 'Amerikanischer Kokoskuchen', 'rice_cakes_sweets', 'snack', 5, 30, 12, 'baked', 'pan_american', diasporaFor('pan_american')),
];
