import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { PROFILES, REGIONS } from './ukraine-base-data/profiles.mjs';

const REGIONAL_TAGS = ['ukrainian', 'east_european', 'slavic'];
const EXPECTED_PROFILES = { 1: 10, 2: 10, 3: 5 };
const LANGUAGES = ['ar', 'en', 'fr', 'es', 'de'];

function validateSource() {
  if (PROFILES.length !== 25) throw new Error(`Expected 25 source profiles; found ${PROFILES.length}`);
  if (REGIONS.length !== 10) throw new Error(`Expected 10 regional anchors; found ${REGIONS.length}`);
  if (new Set(PROFILES.map((profile) => profile.id)).size !== PROFILES.length) {
    throw new Error('Source profile IDs must be unique');
  }
  for (const profile of PROFILES) {
    for (const language of LANGUAGES) {
      if (typeof profile.names?.[language] !== 'string' || !profile.names[language].trim()) {
        throw new Error(`Profile ${profile.id} has no ${language.toUpperCase()} name`);
      }
    }
    if (!profile.category || !profile.mealType || !profile.cooking || !profile.region) {
      throw new Error(`Profile ${profile.id} is missing required dish fields`);
    }
    const expectedKcal = Math.round(4 * profile.protein + 4 * profile.carbs + 9 * profile.fat);
    if (profile.kcal !== expectedKcal) throw new Error(`Profile ${profile.id} calories do not match its macros`);
  }
}

function buildDish(profile, region) {
  return {
    id: `ukraine_${profile.id}_${region.id}`,
    nameAr: `${region.ar} ${profile.names.ar}`,
    nameEn: `${region.en} ${profile.names.en}`,
    nameFr: `${region.fr} : ${profile.names.fr}`,
    nameEs: `${region.es}: ${profile.names.es}`,
    nameDe: `${region.de}: ${profile.names.de}`,
    category: profile.category,
    mealType: profile.mealType,
    grams: 100,
    kcal: profile.kcal,
    protein: profile.protein,
    carbs: profile.carbs,
    fat: profile.fat,
    cooking: profile.cooking,
    region: region.id,
    diaspora_priority: [...REGIONAL_TAGS],
  };
}

export function generateUkraineParts() {
  validateSource();
  return [1, 2, 3].map((part) => {
    const profiles = PROFILES.filter((profile) => profile.part === part);
    if (profiles.length !== EXPECTED_PROFILES[part]) {
      throw new Error(`Part ${part} requires ${EXPECTED_PROFILES[part]} profiles; found ${profiles.length}`);
    }
    return {
      part,
      rows: profiles.flatMap((profile) => REGIONS.map((region) => buildDish(profile, region))),
    };
  });
}

export function generateUkraineRows() {
  return generateUkraineParts().flatMap(({ rows }) => rows);
}

export function renderUkraineTypeScript(rows = generateUkraineRows()) {
  return `// AUTO-GENERATED by scripts/build-ukraine.js from scripts/ukraine-base-data/profiles.mjs. Do not edit.\n` +
    'export interface KitchenDish { id: string; nameAr: string; nameEn: string; nameFr: string; nameEs: string; nameDe: string; category: string; mealType: string; grams: number; kcal: number; protein: number; carbs: number; fat: number; cooking?: string; region?: string; diaspora_priority?: string[]; }\n' +
    `export const UKRAINE_FULL: KitchenDish[] = ${JSON.stringify(rows, null, 2)};\n`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const parts = generateUkraineParts();
  const total = parts.reduce((count, part) => count + part.rows.length, 0);
  if (total !== 250) throw new Error(`Expected 250 Ukrainian rows; generated ${total}`);
  for (const { part, rows } of parts) console.log(`Part ${part}: ${rows.length} dishes`);
  console.log(`Total: ${total} dishes`);
  if (process.argv.includes('--write-static')) {
    const output = resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/ukraine-full.ts');
    writeFileSync(output, renderUkraineTypeScript(parts.flatMap(({ rows }) => rows)), 'utf8');
    console.log(`Wrote ${output}`);
  }
}
