import { B } from './rows.mjs';

export default [
  B('cl-phase-a-001', 'إمبانادا لحم تشيلي مع البيض والزيتون', 'Chilean Beef Empanada de Pino with Egg and Olive', 'Empanada chilienne au bœuf, œuf et olive', 'Empanada chilena de pino con huevo y aceituna', 'Chilenische Rindfleisch-Empanada mit Ei und Olive', 'street_snacks', 'lunch', 17, 25, 10, 'baking', 'santiago'),
  B('cl-phase-a-002', 'إمبانادا الدجاج مع الذرة والفلفل الأخضر', 'Chicken Empanada with Corn and Green Chile', 'Empanada au poulet, maïs et piment vert', 'Empanada de pollo con maíz y ají verde', 'Hähnchen-Empanada mit Mais und grüner Chili', 'street_snacks', 'lunch', 18, 24, 9, 'baking', 'valparaiso'),
  B('cl-phase-a-003', 'باستيل دي تشوكلو باللحم والدجاج والريحان', 'Pastel de Choclo with Lean Beef, Chicken and Basil', 'Pastel de choclo au bœuf maigre, poulet et basilic', 'Pastel de choclo con res magra, pollo y albahaca', 'Pastel de Choclo mit magerem Rind, Hähnchen und Basilikum', 'meat_mains', 'dinner', 19, 20, 8, 'baking', 'santiago'),
  B('cl-phase-a-004', 'كازويلا اللحم البقري بالبطاطس والقرع', 'Cazuela de Vacuno with Beef, Potato and Squash', 'Cazuela de bœuf à la pomme de terre et courge', 'Cazuela de vacuno con res, papa y zapallo', 'Rindfleisch-Cazuela mit Kartoffel und Kürbis', 'soups_stews', 'lunch', 17, 16, 7, 'simmering', 'maule'),
  B('cl-phase-a-005', 'كازويلا الدجاج بالذرة والفاصولياء الخضراء', 'Cazuela de Ave with Chicken, Corn and Green Beans', 'Cazuela de volaille au poulet, maïs et haricots verts', 'Cazuela de ave con pollo, choclo y porotos verdes', 'Hähnchen-Cazuela mit Mais und grünen Bohnen', 'soups_stews', 'lunch', 18, 18, 6, 'simmering', 'bio_bio'),
  B('cl-phase-a-006', 'كومبليتو الدجاج بالأفوكادو والطماطم والبيبر', 'Chicken Completo with Avocado, Tomato and Pebre', 'Completo au poulet, avocat, tomate et pebre', 'Completo de pollo con palta, tomate y pebre', 'Chicken-Completo mit Avocado, Tomate und Pebre', 'street_snacks', 'lunch', 20, 25, 9, 'grilling', 'santiago'),
  B('cl-phase-a-007', 'رينيتا مشوية مع كينوا الأفوكادو والكزبرة', 'Grilled Reineta with Avocado-Cilantro Quinoa', 'Reineta grillée au quinoa, avocat et coriandre', 'Reineta a la parrilla con quinua, palta y cilantro', 'Gegrillte Reineta mit Avocado-Koriander-Quinoa', 'fish_seafood', 'dinner', 23, 16, 8, 'grilling', 'valparaiso'),
  B('cl-phase-a-008', 'كالدييو دي كونغريو بالبطاطس والطماطم', 'Caldillo de Congrio with Potato and Tomato', 'Caldillo de congrio à la pomme de terre et tomate', 'Caldillo de congrio con papa y tomate', 'Caldillo de Congrio mit Kartoffel und Tomate', 'soups_stews', 'lunch', 18, 13, 6, 'simmering', 'coquimbo'),
  B('cl-phase-a-009', 'باستيل دي خايبا بالذرة والجبن الطازج', 'Pastel de Jaiba with Corn and Fresh Cheese', 'Pastel de jaiba au maïs et fromage frais', 'Pastel de jaiba con choclo y queso fresco', 'Pastel de Jaiba mit Mais und Frischkäse', 'fish_seafood', 'dinner', 19, 18, 8, 'baking', 'valparaiso'),
  B('cl-phase-a-010', 'بوروتوس غرانادوس بالفاصولياء والذرة والقرع', 'Porotos Granados with Cranberry Beans, Corn and Squash', 'Porotos granados aux haricots, maïs et courge', 'Porotos granados con porotos, choclo y zapallo', 'Porotos Granados mit Bohnen, Mais und Kürbis', 'vegetable_mains', 'lunch', 11, 27, 5, 'stewing', 'maule'),
  B('cl-phase-a-011', 'هوميتاس تشيليّة بالذرة والريحان والجبن الطازج', 'Humitas Chilenas with Corn, Basil and Fresh Cheese', 'Humitas chilenas au maïs, basilic et fromage frais', 'Humitas chilenas con choclo, albahaca y queso fresco', 'Chilenische Humitas mit Mais, Basilikum und Frischkäse', 'street_snacks', 'lunch', 12, 26, 7, 'steaming', 'santiago'),
  B('cl-phase-a-012', 'تشاركيكان اللحم البقري بالبطاطس والقرع', 'Charquican de Vacuno with Beef, Potato and Squash', 'Charquicán de bœuf à la pomme de terre et courge', 'Charquicán de vacuno con res, papa y zapallo', 'Rindfleisch-Charquicán mit Kartoffel und Kürbis', 'meat_mains', 'lunch', 18, 19, 7, 'stewing', 'araucania'),
  B('cl-phase-a-013', 'ميرلوزا مخبوزة بقشرة الكوچايو والليمون', 'Baked Merluza with Cochayuyo Crust and Lemon', 'Merluza au four en croûte de cochayuyo et citron', 'Merluza al horno con costra de cochayuyo y limón', 'Gebackene Merluza mit Cochayuyo-Kruste und Zitrone', 'fish_seafood', 'dinner', 22, 9, 7, 'baking', 'los_lagos'),
];
