import { B } from './rows.mjs';

export default [
  B('cl-phase-a-026', 'رينيتا مخبوزة مع البطاطس المهروسة بالقرع', 'Baked Reineta with Potato and Squash Mash', 'Reineta au four avec purée de pomme de terre et courge', 'Reineta al horno con puré de papa y zapallo', 'Gebackene Reineta mit Kartoffel-Kürbis-Püree', 'fish_seafood', 'dinner', 23, 17, 8, 'baking', 'valparaiso'),
  B('cl-phase-a-027', 'شوربة كازويلا اللحم مع تشوتشوكا والذرة', 'Beef Cazuela with Chuchoca and Corn', 'Cazuela de bœuf à la chuchoca et au maïs', 'Cazuela de vacuno con chuchoca y choclo', 'Rindfleisch-Cazuela mit Chuchoca und Mais', 'soups_stews', 'lunch', 18, 18, 7, 'simmering', 'maule'),
  B('cl-phase-a-028', 'كالدييو السمك بالرينيتا والذرة والبطاطس', 'Fish Caldillo with Reineta, Corn and Potato', 'Caldillo de poisson à la reineta, maïs et pomme de terre', 'Caldillo de pescado con reineta, choclo y papa', 'Fisch-Caldillo mit Reineta, Mais und Kartoffel', 'fish_seafood', 'lunch', 19, 16, 6, 'simmering', 'coquimbo'),
  B('cl-phase-a-029', 'بوروتوس غرانادوس بالديك الرومي والريحان', 'Porotos Granados with Turkey and Basil', 'Porotos granados à la dinde et au basilic', 'Porotos granados con pavo y albahaca', 'Porotos Granados mit Pute und Basilikum', 'poultry_mains', 'dinner', 17, 25, 6, 'stewing', 'maule'),
  B('cl-phase-a-030', 'كيرانتو تشيلوتي بالمحار والبطاطس وميلكاو', 'Chilote Curanto with Seafood, Potatoes and Milcao', 'Curanto chilote aux fruits de mer, pommes de terre et milcao', 'Curanto chilote con mariscos, papas y milcao', 'Chilote-Curanto mit Meeresfrüchten, Kartoffeln und Milcao', 'fish_seafood', 'dinner', 21, 20, 7, 'steaming', 'los_lagos'),
  B('cl-phase-a-031', 'ميلكاو البطاطس مع السلمون والجبن الطازج', 'Potato Milcao with Salmon and Fresh Cheese', 'Milcao de pomme de terre au saumon et fromage frais', 'Milcao de papa con salmón y queso fresco', 'Kartoffel-Milcao mit Lachs und Frischkäse', 'fish_seafood', 'lunch', 20, 22, 8, 'pan_frying', 'los_lagos'),
  B('cl-phase-a-032', 'تشاباليلي بالدجاج والذرة والبيبر', 'Chapalele with Chicken, Corn and Pebre', 'Chapalele au poulet, maïs et pebre', 'Chapalele con pollo, choclo y pebre', 'Chapalele mit Hähnchen, Mais und Pebre', 'poultry_mains', 'lunch', 18, 24, 7, 'steaming', 'los_lagos'),
  B('cl-phase-a-033', 'سيفيتشي رينيتا بالأفوكادو والكزبرة', 'Reineta Ceviche with Avocado and Cilantro', 'Ceviche de reineta à l’avocat et coriandre', 'Ceviche de reineta con palta y cilantro', 'Reineta-Ceviche mit Avocado und Koriander', 'fish_seafood', 'lunch', 21, 8, 7, 'marinating', 'valparaiso'),
  B('cl-phase-a-034', 'تشوبي خايبا بالذرة والجبن الطازج', 'Chupe de Jaiba with Corn and Fresh Cheese', 'Chupe de jaiba au maïs et fromage frais', 'Chupe de jaiba con choclo y queso fresco', 'Jaiba-Chupe mit Mais und Frischkäse', 'fish_seafood', 'lunch', 19, 17, 8, 'baking', 'valparaiso'),
  B('cl-phase-a-035', 'بايلا مارينا بالكونغريو والروبيان والمحار', 'Paila Marina with Congrio, Shrimp and Shellfish', 'Paila marina au congrio, crevettes et coquillages', 'Paila marina con congrio, camarones y mariscos', 'Paila Marina mit Congrio, Garnelen und Muscheln', 'fish_seafood', 'lunch', 20, 11, 5, 'simmering', 'valparaiso'),
  B('cl-phase-a-036', 'باستيل البطاطس بلحم البقر والبيض والزيتون', 'Pastel de Papas with Beef, Egg and Olive', 'Pastel de pommes de terre au bœuf, œuf et olive', 'Pastel de papas con res, huevo y aceituna', 'Kartoffel-Pastel mit Rind, Ei und Olive', 'meat_mains', 'dinner', 18, 22, 9, 'baking', 'santiago'),
  B('cl-phase-a-037', 'سلطة تشيليّة بالأفوكادو والطماطم والتونة', 'Ensalada Chilena with Avocado, Tomato and Tuna', 'Salade chilienne à l’avocat, tomate et thon', 'Ensalada chilena con palta, tomate y atún', 'Chilenischer Salat mit Avocado, Tomate und Thunfisch', 'salads', 'lunch', 17, 9, 9, 'assembling', 'santiago'),
];
