import { B } from './rows.mjs';

export default [
  B('cl-phase-a-126', 'إمبانادا البيض والجبن الطازج والذرة', 'Egg, Quesillo and Corn Empanada', 'Empanada à l’œuf, quesillo et maïs', 'Empanada de huevo, quesillo y choclo', 'Empanada mit Ei, Quesillo und Mais', 'street_snacks', 'lunch', 16, 25, 9, 'baking', 'santiago'),
  B('cl-phase-a-127', 'كازويلا السمك بالروبيان والبطاطس والذرة', 'Fish Cazuela with Shrimp, Potato and Corn', 'Cazuela de poisson aux crevettes, pomme de terre et maïs', 'Cazuela de pescado con camarones, papa y choclo', 'Fisch-Cazuela mit Garnelen, Kartoffel und Mais', 'fish_seafood', 'lunch', 20, 17, 6, 'simmering', 'valparaiso'),
  B('cl-phase-a-128', 'بوروتوس كون ريئنداس بالدجاج والقرع', 'Porotos con Riendas with Chicken and Squash', 'Porotos con riendas au poulet et à la courge', 'Porotos con riendas con pollo y zapallo', 'Porotos con Riendas mit Hähnchen und Kürbis', 'poultry_mains', 'dinner', 18, 24, 7, 'stewing', 'maule'),
  B('cl-phase-a-129', 'باستيل البطاطس بلحم الضأن والبازلاء', 'Lamb Pastel de Papas with Peas', 'Pastel de pommes de terre à l’agneau et aux petits pois', 'Pastel de papas con cordero y arvejas', 'Lamm-Kartoffel-Pastel mit Erbsen', 'meat_mains', 'dinner', 19, 22, 9, 'baking', 'magallanes'),
  B('cl-phase-a-130', 'تشوبي الخرشوف والذرة والجبن الطازج', 'Artichoke Chupe with Corn and Fresh Cheese', 'Chupe d’artichaut au maïs et fromage frais', 'Chupe de alcachofa con choclo y queso fresco', 'Artischocken-Chupe mit Mais und Frischkäse', 'vegetable_mains', 'lunch', 12, 20, 9, 'baking', 'santiago'),
  B('cl-phase-a-131', 'سلمون مخبوز بقشرة الكينوا وبيبر الليمون', 'Quinoa-Crusted Salmon with Lemon Pebre', 'Saumon en croûte de quinoa au pebre citronné', 'Salmón con costra de quinua y pebre de limón', 'Lachs mit Quinoa-Kruste und Zitronen-Pebre', 'fish_seafood', 'dinner', 24, 15, 10, 'baking', 'aysen'),
  B('cl-phase-a-132', 'كازويلا الدجاج بالموتي والفاصولياء الخضراء', 'Chicken Cazuela with Mote and Green Beans', 'Cazuela de poulet au mote et haricots verts', 'Cazuela de pollo con mote y porotos verdes', 'Hähnchen-Cazuela mit Mote und grünen Bohnen', 'poultry_mains', 'lunch', 19, 19, 6, 'simmering', 'bio_bio'),
  B('cl-phase-a-133', 'تشاركيكان الماكريل بالبطاطس والقرع والذرة', 'Mackerel Charquican with Potato, Squash and Corn', 'Charquicán de maquereau à la pomme de terre, courge et maïs', 'Charquicán de jurel con papa, zapallo y choclo', 'Makrelen-Charquicán mit Kartoffel, Kürbis und Mais', 'fish_seafood', 'lunch', 19, 21, 8, 'stewing', 'valparaiso'),
  B('cl-phase-a-134', 'كومبليتو باللحم البقري قليل الدهن والأفوكادو والطماطم', 'Lean Beef Completo with Avocado and Tomato', 'Completo au bœuf maigre, avocat et tomate', 'Completo de res magra con palta y tomate', 'Completo mit magerem Rind, Avocado und Tomate', 'street_snacks', 'lunch', 21, 25, 10, 'grilling', 'santiago'),
  B('cl-phase-a-135', 'سلطة التشونغاس بالبطاطس والذرة والبيض', 'Chungas Salad with Potato, Corn and Egg', 'Salade de chungas à la pomme de terre, maïs et œuf', 'Ensalada de chungas con papa, choclo y huevo', 'Chungas-Salat mit Kartoffel, Mais und Ei', 'salads', 'lunch', 13, 19, 7, 'assembling', 'arica'),
  B('cl-phase-a-136', 'طاجن الكينوا بالقرع والسبانخ والجبن الطازج', 'Quinoa Bake with Squash, Spinach and Fresh Cheese', 'Gratin de quinoa à la courge, épinards et fromage frais', 'Budín de quinua con zapallo, espinaca y queso fresco', 'Quinoa-Auflauf mit Kürbis, Spinat und Frischkäse', 'vegetable_mains', 'dinner', 15, 22, 8, 'baking', 'araucania'),
  B('cl-phase-a-137', 'روبيان سوتيه بميركين والذرة والكينوا', 'Merkén Shrimp with Corn and Quinoa', 'Crevettes au merkén, maïs et quinoa', 'Camarones al merkén con choclo y quinua', 'Merkén-Garnelen mit Mais und Quinoa', 'fish_seafood', 'dinner', 22, 18, 6, 'sauteing', 'atacama'),
];
