import { B } from './rows.mjs';

export default [
  B('cl-phase-a-076', 'سمك الماكريل المخبوز مع الكينوا والبيبر', 'Baked Mackerel with Quinoa and Pebre', 'Maquereau au four avec quinoa et pebre', 'Jurel al horno con quinua y pebre', 'Gebackene Makrele mit Quinoa und Pebre', 'fish_seafood', 'dinner', 22, 15, 11, 'baking', 'valparaiso'),
  B('cl-phase-a-077', 'باستيل البطاطس بالدجاج والذرة والبيض', 'Chicken Pastel de Papas with Corn and Egg', 'Pastel de pommes de terre au poulet, maïs et œuf', 'Pastel de papas con pollo, choclo y huevo', 'Hähnchen-Kartoffel-Pastel mit Mais und Ei', 'poultry_mains', 'dinner', 19, 22, 8, 'baking', 'santiago'),
  B('cl-phase-a-078', 'إمبانادا لحم الضأن بالزيتون والبيض', 'Lamb Empanada with Olive and Egg', 'Empanada d’agneau à l’olive et à l’œuf', 'Empanada de cordero con aceituna y huevo', 'Lamm-Empanada mit Olive und Ei', 'street_snacks', 'lunch', 18, 23, 10, 'baking', 'magallanes'),
  B('cl-phase-a-079', 'توماتيكان اللحم البقري بالطماطم والذرة والريحان', 'Tomatican de Vacuno with Tomato, Corn and Basil', 'Tomaticán de bœuf à la tomate, maïs et basilic', 'Tomaticán de vacuno con tomate, choclo y albahaca', 'Rindfleisch-Tomaticán mit Tomate, Mais und Basilikum', 'meat_mains', 'lunch', 18, 20, 7, 'stewing', 'maule'),
  B('cl-phase-a-080', 'شوربة العدس التشيلية بالبيض والقرع', 'Chilean Lentil Soup with Egg and Squash', 'Soupe chilienne de lentilles à l’œuf et courge', 'Sopa chilena de lentejas con huevo y zapallo', 'Chilenische Linsensuppe mit Ei und Kürbis', 'soups_stews', 'lunch', 13, 22, 5, 'simmering', 'santiago'),
  B('cl-phase-a-081', 'بطاطس تشيلوتي مع السلمون والشبت', 'Chilote Potatoes with Salmon and Dill', 'Pommes de terre chilotes au saumon et à l’aneth', 'Papas chilotas con salmón y eneldo', 'Chilote-Kartoffeln mit Lachs und Dill', 'fish_seafood', 'dinner', 19, 22, 9, 'baking', 'los_lagos'),
  B('cl-phase-a-082', 'كازويلا الديك الرومي بالبطاطس والقرع والفاصولياء', 'Turkey Cazuela with Potato, Squash and Green Beans', 'Cazuela de dinde à la pomme de terre, courge et haricots verts', 'Cazuela de pavo con papa, zapallo y porotos verdes', 'Puten-Cazuela mit Kartoffel, Kürbis und grünen Bohnen', 'poultry_mains', 'lunch', 19, 18, 6, 'simmering', 'maule'),
  B('cl-phase-a-083', 'تشوبي السلمون بالبطاطس والذرة والجبن الطازج', 'Salmon Chupe with Potato, Corn and Fresh Cheese', 'Chupe de saumon à la pomme de terre, maïs et fromage frais', 'Chupe de salmón con papa, choclo y queso fresco', 'Lachs-Chupe mit Kartoffel, Mais und Frischkäse', 'fish_seafood', 'lunch', 20, 17, 9, 'baking', 'los_lagos'),
  B('cl-phase-a-084', 'شوربة قمح مجروش بالدجاج والخضار', 'Cracked Wheat Soup with Chicken and Vegetables', 'Soupe de blé concassé au poulet et légumes', 'Sopa de trigo mote con pollo y verduras', 'Suppe aus gebrochenem Weizen mit Hähnchen und Gemüse', 'soups_stews', 'lunch', 17, 20, 6, 'simmering', 'bio_bio'),
  B('cl-phase-a-085', 'دجاج مشوي بميركين والذرة والبطاطس', 'Roasted Chicken with Merkén, Corn and Potato', 'Poulet rôti au merkén, maïs et pomme de terre', 'Pollo asado con merkén, choclo y papa', 'Brathähnchen mit Merkén, Mais und Kartoffel', 'poultry_mains', 'dinner', 25, 15, 8, 'roasting', 'araucania'),
  B('cl-phase-a-086', 'تورتيّا الفاصولياء الخضراء بالبيض والجبن الطازج', 'Green Bean Tortilla with Egg and Quesillo', 'Tortilla de haricots verts à l’œuf et quesillo', 'Tortilla de porotos verdes con huevo y quesillo', 'Bohnentortilla mit Ei und Quesillo', 'breakfast_items', 'breakfast', 14, 11, 8, 'pan_frying', 'santiago'),
  B('cl-phase-a-087', 'سيفيتشي لوكوس بالبطاطس والليمون والكزبرة', 'Locos Ceviche with Potato, Lime and Cilantro', 'Ceviche de locos à la pomme de terre, citron vert et coriandre', 'Ceviche de locos con papa, limón y cilantro', 'Locos-Ceviche mit Kartoffel, Limette und Koriander', 'fish_seafood', 'lunch', 22, 10, 5, 'marinating', 'coquimbo'),
];
