import { B } from './rows.mjs';

export default [
  B('cl-phase-a-101', 'إمبانادا تشوريتوس مع الكزبرة والليمون', 'Choritos Empanada with Cilantro and Lemon', 'Empanada de choritos à la coriandre et au citron', 'Empanada de choritos con cilantro y limón', 'Choritos-Empanada mit Koriander und Zitrone', 'street_snacks', 'lunch', 18, 24, 8, 'baking', 'los_lagos'),
  B('cl-phase-a-102', 'كازويلا كرات الديك الرومي بالبطاطس والقرع', 'Turkey Meatball Cazuela with Potato and Squash', 'Cazuela de boulettes de dinde à la pomme de terre et courge', 'Cazuela de albóndigas de pavo con papa y zapallo', 'Putenbällchen-Cazuela mit Kartoffel und Kürbis', 'poultry_mains', 'lunch', 19, 17, 7, 'simmering', 'maule'),
  B('cl-phase-a-103', 'تشوبي لوكوس بالكينوا والذرة', 'Locos Chupe with Quinoa and Corn', 'Chupe de locos au quinoa et au maïs', 'Chupe de locos con quinua y choclo', 'Locos-Chupe mit Quinoa und Mais', 'fish_seafood', 'lunch', 21, 18, 7, 'baking', 'coquimbo'),
  B('cl-phase-a-104', 'بوروتوس كون موتي بالقرع والريحان', 'Porotos con Mote with Squash and Basil', 'Porotos con mote à la courge et au basilic', 'Porotos con mote con zapallo y albahaca', 'Porotos con Mote mit Kürbis und Basilikum', 'vegetable_mains', 'lunch', 12, 27, 5, 'stewing', 'maule'),
  B('cl-phase-a-105', 'سلمون مشوي ببيبر مورْتا والكينوا', 'Grilled Salmon with Murta Pebre and Quinoa', 'Saumon grillé au pebre de murta et quinoa', 'Salmón a la parrilla con pebre de murta y quinua', 'Gegrillter Lachs mit Murta-Pebre und Quinoa', 'fish_seafood', 'dinner', 24, 15, 10, 'grilling', 'los_lagos'),
  B('cl-phase-a-106', 'تشوراسكا القمح الكامل بالأفوكادو والبيض', 'Whole-Wheat Churrasca with Avocado and Egg', 'Churrasca complète à l’avocat et à l’œuf', 'Churrasca integral con palta y huevo', 'Vollkorn-Churrasca mit Avocado und Ei', 'breakfast_items', 'breakfast', 13, 29, 10, 'griddling', 'bio_bio'),
  B('cl-phase-a-107', 'باستيل تشوكلو بالسلطعون والذرة والريحان', 'Crab Pastel de Choclo with Corn and Basil', 'Pastel de choclo au crabe, maïs et basilic', 'Pastel de choclo con jaiba, maíz y albahaca', 'Krabben-Pastel de Choclo mit Mais und Basilikum', 'fish_seafood', 'dinner', 19, 21, 8, 'baking', 'valparaiso'),
  B('cl-phase-a-108', 'كاربونادا الديك الرومي بالذرة والبطاطس والفاصولياء', 'Turkey Carbonada with Corn, Potato and Green Beans', 'Carbonada de dinde au maïs, pomme de terre et haricots verts', 'Carbonada de pavo con choclo, papa y porotos verdes', 'Puten-Carbonada mit Mais, Kartoffel und grünen Bohnen', 'poultry_mains', 'lunch', 19, 19, 6, 'simmering', 'santiago'),
  B('cl-phase-a-109', 'تشوريتوس مطهوّة بالثوم والبقدونس والليمون', 'Steamed Choritos with Garlic, Parsley and Lemon', 'Choritos vapeur à l’ail, au persil et au citron', 'Choritos al vapor con ajo, perejil y limón', 'Gedämpfte Choritos mit Knoblauch, Petersilie und Zitrone', 'fish_seafood', 'lunch', 21, 9, 5, 'steaming', 'los_lagos'),
  B('cl-phase-a-110', 'تشاركيكان العدس بالذرة والقرع والبيض', 'Lentil Charquican with Corn, Squash and Egg', 'Charquicán de lentilles au maïs, courge et œuf', 'Charquicán de lentejas con choclo, zapallo y huevo', 'Linsen-Charquicán mit Mais, Kürbis und Ei', 'vegetable_mains', 'lunch', 15, 24, 7, 'stewing', 'araucania'),
  B('cl-phase-a-111', 'إمبانادا السلمون بالجبن الطازج والشبت', 'Salmon Empanada with Fresh Cheese and Dill', 'Empanada au saumon, fromage frais et aneth', 'Empanada de salmón con queso fresco y eneldo', 'Lachs-Empanada mit Frischkäse und Dill', 'street_snacks', 'lunch', 20, 23, 9, 'baking', 'aysen'),
  B('cl-phase-a-112', 'تورتيّا الذرة والكينوا بجبن كيسيو', 'Corn and Quinoa Tortilla with Quesillo', 'Tortilla de maïs et quinoa au quesillo', 'Tortilla de maíz y quinua con quesillo', 'Mais-Quinoa-Tortilla mit Quesillo', 'breakfast_items', 'breakfast', 15, 22, 8, 'pan_frying', 'santiago'),
  B('cl-phase-a-113', 'كازويلا كونغريو بالكينوا والبطاطس والكزبرة', 'Congrio Cazuela with Quinoa, Potato and Cilantro', 'Cazuela de congrio au quinoa, pomme de terre et coriandre', 'Cazuela de congrio con quinua, papa y cilantro', 'Congrio-Cazuela mit Quinoa, Kartoffel und Koriander', 'fish_seafood', 'lunch', 21, 17, 6, 'simmering', 'coquimbo'),
];
