import { B } from './rows.mjs';

export default [
  B('cl-phase-a-051', 'سلمون مخبوز مع الكينوا والليمون', 'Baked Chilean Salmon with Quinoa and Lemon', 'Saumon chilien au four, quinoa et citron', 'Salmón chileno al horno con quinua y limón', 'Gebackener chilenischer Lachs mit Quinoa und Zitrone', 'fish_seafood', 'dinner', 23, 14, 11, 'baking', 'los_lagos'),
  B('cl-phase-a-052', 'تشوبي الروبيان بالبطاطس والذرة والجبن', 'Shrimp Chupe with Potato, Corn and Fresh Cheese', 'Chupe de crevettes à la pomme de terre, maïs et fromage frais', 'Chupe de camarones con papa, choclo y queso fresco', 'Garnelen-Chupe mit Kartoffel, Mais und Frischkäse', 'fish_seafood', 'lunch', 19, 18, 8, 'simmering', 'coquimbo'),
  B('cl-phase-a-053', 'إمبانادا السبانخ والجبن الطازج', 'Spinach and Quesillo Empanada', 'Empanada aux épinards et quesillo', 'Empanada de espinaca y quesillo', 'Empanada mit Spinat und Quesillo', 'street_snacks', 'lunch', 14, 24, 9, 'baking', 'santiago'),
  B('cl-phase-a-054', 'تشوبي الإريزو بالذرة والبطاطس والجبن', 'Sea Urchin Chupe with Corn, Potato and Cheese', 'Chupe d’oursins au maïs, pomme de terre et fromage', 'Chupe de erizos con choclo, papa y queso', 'Seeigel-Chupe mit Mais, Kartoffel und Käse', 'fish_seafood', 'lunch', 18, 16, 8, 'baking', 'coquimbo'),
  B('cl-phase-a-055', 'كالدييو المحار بالبطاطس والطماطم والكزبرة', 'Clam Caldillo with Potato, Tomato and Cilantro', 'Caldillo de palourdes à la pomme de terre, tomate et coriandre', 'Caldillo de almejas con papa, tomate y cilantro', 'Muschel-Caldillo mit Kartoffel, Tomate und Koriander', 'fish_seafood', 'lunch', 18, 14, 6, 'simmering', 'atacama'),
  B('cl-phase-a-056', 'لحم بقري مطهو ببطء مع الأفوكادو والقرع', 'Slow-Braised Carne Mechada with Avocado and Squash', 'Carne mechada braisée lentement à l’avocat et courge', 'Carne mechada cocida lento con palta y zapallo', 'Langsam geschmortes Carne Mechada mit Avocado und Kürbis', 'meat_mains', 'dinner', 22, 13, 9, 'braising', 'santiago'),
  B('cl-phase-a-057', 'تشاركيكان الديك الرومي بالبطاطس والفاصولياء الخضراء', 'Turkey Charquican with Potato and Green Beans', 'Charquicán de dinde à la pomme de terre et haricots verts', 'Charquicán de pavo con papa y porotos verdes', 'Puten-Charquicán mit Kartoffel und grünen Bohnen', 'poultry_mains', 'dinner', 19, 20, 6, 'stewing', 'araucania'),
  B('cl-phase-a-058', 'كاربونادا تشيليّة بلحم البقر والقرع والذرة', 'Chilean Carbonada with Beef, Squash and Corn', 'Carbonada chilienne au bœuf, courge et maïs', 'Carbonada chilena con res, zapallo y choclo', 'Chilenische Carbonada mit Rind, Kürbis und Mais', 'soups_stews', 'lunch', 17, 20, 7, 'simmering', 'maule'),
  B('cl-phase-a-059', 'سيفيتشي السلمون بالأفوكادو والليمون', 'Salmon Ceviche with Avocado and Lime', 'Ceviche de saumon à l’avocat et citron vert', 'Ceviche de salmón con palta y limón', 'Lachs-Ceviche mit Avocado und Limette', 'fish_seafood', 'lunch', 21, 7, 10, 'marinating', 'los_lagos'),
  B('cl-phase-a-060', 'دجاج ميركين مع الكينوا والخضار المشوية', 'Merkén Chicken with Quinoa and Roasted Vegetables', 'Poulet au merkén, quinoa et légumes rôtis', 'Pollo al merkén con quinua y verduras asadas', 'Merkén-Hähnchen mit Quinoa und Ofengemüse', 'poultry_mains', 'dinner', 24, 17, 7, 'roasting', 'araucania'),
  B('cl-phase-a-061', 'تورتيّا الكوچايو بالبيض والبطاطس والبصل', 'Cochayuyo Tortilla with Egg, Potato and Onion', 'Tortilla de cochayuyo à l’œuf, pomme de terre et oignon', 'Tortilla de cochayuyo con huevo, papa y cebolla', 'Cochayuyo-Tortilla mit Ei, Kartoffel und Zwiebel', 'vegetable_mains', 'lunch', 12, 18, 8, 'pan_frying', 'valparaiso'),
  B('cl-phase-a-062', 'وعاء بيبر بالتونة والأفوكادو والفاصولياء', 'Pebre Bowl with Tuna, Avocado and Beans', 'Bol de pebre au thon, avocat et haricots', 'Bowl de pebre con atún, palta y porotos', 'Pebre-Bowl mit Thunfisch, Avocado und Bohnen', 'fish_seafood', 'lunch', 20, 18, 9, 'assembling', 'santiago'),
  B('cl-phase-a-063', 'لحم بقري ميركين مع البطاطس والفاصولياء الخضراء', 'Merkén Beef with Potato and Green Beans', 'Bœuf au merkén, pomme de terre et haricots verts', 'Res al merkén con papa y porotos verdes', 'Merkén-Rind mit Kartoffel und grünen Bohnen', 'meat_mains', 'dinner', 23, 18, 8, 'grilling', 'araucania'),
];
