import { B } from './rows.mjs';

export default [
  B('co-phase-a-076', 'كوتشوكو القمح بلحم البقر والفاصولياء', 'Wheat Cuchuco with Beef and Beans', 'Cuchuco de blé au bœuf et haricots', 'Cuchuco de trigo con res y frijoles', 'Weizen-Cuchuco mit Rindfleisch und Bohnen', 'soups_stews', 'lunch', 16, 16, 6, 'simmering', 'boyaca'),
  B('co-phase-a-077', 'سمك مخبوز بهوغاو والذرة', 'Baked Fish with Hogao and Corn', 'Poisson au four au hogao et maïs', 'Pescado al horno con hogao y maíz', 'Ofenfisch mit Hogao und Mais', 'fish_seafood', 'dinner', 20, 9, 7, 'baking', 'caribe'),
  B('co-phase-a-078', 'دجاج مطهو بالأفوكادو والطماطم الخضراء', 'Chicken Stewed with Avocado and Green Tomato', 'Poulet mijoté à l’avocat et tomate verte', 'Pollo guisado con aguacate y tomate verde', 'Hähnchen mit Avocado und grüner Tomate geschmort', 'poultry_mains', 'dinner', 20, 7, 8, 'stewing', 'cundinamarca'),
  B('co-phase-a-079', 'لحمة لانيرا مشوية بكاسابي وهوغاو', 'Llanero Grilled Beef with Casabe and Hogao', 'Bœuf llanero grillé au casabe et hogao', 'Res llanera asada con casabe y hogao', 'Gegrilltes Llanero-Rind mit Casabe und Hogao', 'meat_mains', 'dinner', 23, 19, 9, 'grilling', 'llanos'),
  B('co-phase-a-080', 'أريبا يوكا بالجبن والأعشاب', 'Cassava Arepa with Cheese and Herbs', 'Arepa de manioc au fromage et herbes', 'Arepa de yuca con queso y hierbas', 'Maniok-Arepa mit Käse und Kräutern', 'breakfast_items', 'breakfast', 11, 25, 7, 'griddling', 'narino'),
  B('co-phase-a-081', 'صدر دجاج بصلصة الماراكويّا والأفوكادو', 'Chicken Breast with Passion Fruit and Avocado Sauce', 'Blanc de poulet à la sauce maracuja et avocat', 'Pechuga de pollo con salsa de maracuyá y aguacate', 'Hähnchenbrust mit Maracuja-Avocado-Soße', 'poultry_mains', 'dinner', 23, 7, 7, 'grilling', 'valle'),
  B('co-phase-a-082', 'أرز جوز الهند بالسرابي والذرة', 'Coconut Rice with Surubi and Corn', 'Riz coco au surubi et maïs', 'Arroz con coco, surubí y maíz', 'Kokosreis mit Surubi und Mais', 'fish_seafood', 'dinner', 18, 22, 7, 'simmering', 'llanos'),
  B('co-phase-a-083', 'يخنة لحم بقري بالعدس والطماطم والبطاطس', 'Beef Lentil Stew with Tomato and Potato', 'Ragoût de bœuf aux lentilles, tomate et pomme de terre', 'Guiso de res con lentejas, tomate y papa', 'Rind-Linsen-Eintopf mit Tomate und Kartoffel', 'meat_mains', 'dinner', 18, 14, 7, 'stewing', 'tolima'),
  B('co-phase-a-084', 'شوربة يوكا بالدجاج والكزبرة', 'Cassava Soup with Chicken and Cilantro', 'Soupe de manioc au poulet et coriandre', 'Sopa de yuca con pollo y cilantro', 'Manioksuppe mit Hähnchen und Koriander', 'soups_stews', 'lunch', 14, 13, 5, 'simmering', 'narino'),
  B('co-phase-a-085', 'يوكا مشوية بجبن كوستينيو والهوغاو', 'Grilled Cassava with Queso Costeno and Hogao', 'Manioc grillé au queso costeno et hogao', 'Yuca asada con queso costeño y hogao', 'Gegrillter Maniok mit Queso Costeno und Hogao', 'vegetable_mains', 'side', 10, 25, 7, 'grilling', 'caribe'),
  B('co-phase-a-086', 'كاسويلا دجاج بالأرز وحليب جوز الهند', 'Chicken Cazuela with Rice and Coconut Milk', 'Cazuela de poulet au riz et lait de coco', 'Cazuela de pollo con arroz y leche de coco', 'Hähnchen-Cazuela mit Reis und Kokosmilch', 'poultry_mains', 'dinner', 16, 18, 7, 'simmering', 'pacifico'),
  B('co-phase-a-087', 'يخنة باذنجان وفاصولياء بالأفوكادو والليمون', 'Eggplant and Bean Stew with Avocado and Lime', 'Ragoût d’aubergine et haricots à l’avocat et citron vert', 'Guiso de berenjena y frijoles con aguacate y lima', 'Auberginen-Bohnen-Eintopf mit Avocado und Limette', 'vegetable_mains', 'lunch', 10, 15, 7, 'stewing', 'santander'),
];
