import { B } from './rows.mjs';

export default [
  B('co-phase-a-026', 'بوستا نيغرا كارتاخينا بلحم البقر والبانِيلا', 'Cartagena Posta Negra with Beef and Panela', 'Posta negra de Carthagène au bœuf et panela', 'Posta negra cartagenera de res con panela', 'Cartagena-Posta-Negra mit Rind und Panela', 'meat_mains', 'dinner', 21, 8, 9, 'braising', 'caribe'),
  B('co-phase-a-027', 'فيودو السمك باليوكا والموز والبطاطس', 'Fish Viudo with Cassava, Plantain and Potato', 'Viudo de poisson au manioc, plantain et pomme de terre', 'Viudo de pescado con yuca, plátano y papa', 'Fisch-Viudo mit Maniok, Kochbanane und Kartoffel', 'fish_seafood', 'lunch', 19, 15, 5, 'simmering', 'cundinamarca'),
  B('co-phase-a-028', 'شوربة أراجّاتشا باللحم البقري والأعشاب', 'Arracacha Soup with Beef and Herbs', 'Soupe d’arracacha au bœuf et herbes', 'Sopa de arracacha con res y hierbas', 'Arracacha-Suppe mit Rindfleisch und Kräutern', 'soups_stews', 'lunch', 15, 12, 6, 'simmering', 'boyaca'),
  B('co-phase-a-029', 'أريبا سانتافيرينيا بالدجاج والجبن', 'Santafereña Arepa with Chicken and Cheese', 'Arepa santafereña au poulet et fromage', 'Arepa santafereña con pollo y queso', 'Santafereña-Arepa mit Hähnchen und Käse', 'poultry_mains', 'breakfast', 17, 20, 8, 'griddling', 'bogota'),
  B('co-phase-a-030', 'مرق كبد البقر بالبصل والبطاطس', 'Beef Liver Caldo with Onion and Potato', 'Caldo de foie de bœuf à l’oignon et pomme de terre', 'Caldo de hígado de res con cebolla y papa', 'Rinderleber-Caldo mit Zwiebel und Kartoffel', 'meat_mains', 'breakfast', 18, 8, 5, 'simmering', 'antioquia'),
  B('co-phase-a-031', 'كيك الذرة بجبن بانلا والبصل', 'Corn Cake with Panela Cheese and Onion', 'Gâteau de maïs au panela et oignon', 'Torta de choclo con queso panela y cebolla', 'Maiskuchen mit Panela-Käse und Zwiebel', 'vegetable_mains', 'snack', 11, 23, 7, 'baking', 'valle'),
  B('co-phase-a-032', 'أرز بالدجاج وغواندوليس', 'Chicken Rice with Pigeon Peas', 'Riz au poulet et pois d’Angole', 'Arroz con pollo y guandules', 'Hähnchenreis mit Straucherbsen', 'poultry_mains', 'dinner', 17, 19, 6, 'simmering', 'caribe'),
  B('co-phase-a-033', 'باستيل اليوكا بالدجاج والجبن', 'Cassava Pastel with Chicken and Cheese', 'Pastel de manioc au poulet et fromage', 'Pastel de yuca con pollo y queso', 'Maniok-Pastel mit Hähnchen und Käse', 'poultry_mains', 'dinner', 16, 20, 8, 'baking', 'llanos'),
  B('co-phase-a-034', 'لحم بقري على طريقة لو ترابو بالفلفل', 'Lomo al Trapo with Pepper', 'Lomo al trapo au poivre', 'Lomo al trapo con pimienta', 'Lomo al Trapo mit Pfeffer', 'meat_mains', 'dinner', 24, 2, 12, 'grilling', 'antioquia'),
  B('co-phase-a-035', 'إنيوكادو جوز الهند واليوكا بالجبن', 'Coconut Cassava Enyucado with Cheese', 'Enyucado de manioc à la noix de coco et fromage', 'Enyucado de yuca, coco y queso', 'Kokos-Maniok-Enyucado mit Käse', 'rice_cakes_sweets', 'snack', 8, 30, 9, 'baking', 'caribe'),
  B('co-phase-a-036', 'فريخولادا الدجاج والفاصولياء والأفوكادو', 'Chicken Frijolada with Beans and Avocado', 'Frijolada de poulet aux haricots et avocat', 'Frijolada de pollo con frijoles y aguacate', 'Hähnchen-Frijolada mit Bohnen und Avocado', 'soups_stews', 'lunch', 18, 13, 7, 'simmering', 'antioquia'),
  B('co-phase-a-037', 'تروتا الأنديز بالخضار والبطاطس', 'Andean Trout with Vegetables and Potato', 'Truite des Andes aux légumes et pomme de terre', 'Trucha andina con verduras y papa', 'Andenforelle mit Gemüse und Kartoffel', 'fish_seafood', 'dinner', 20, 10, 6, 'baking', 'narino'),
];
