import { B } from './rows.mjs';

export default [
  B('co-phase-a-051', 'لحم بقري مفتت بهوغاو والأفوكادو', 'Shredded Beef with Hogao and Avocado', 'Bœuf effiloché au hogao et avocat', 'Carne desmechada con hogao y aguacate', 'Gezupftes Rind mit Hogao und Avocado', 'meat_mains', 'lunch', 21, 8, 10, 'braising', 'antioquia'),
  B('co-phase-a-052', 'سمك مطهو بحليب جوز الهند والموز الأخضر', 'Pacific Fish Stewed with Coconut Milk and Green Plantain', 'Poisson du Pacifique au lait de coco et banane plantain verte', 'Pescado del Pacífico guisado con leche de coco y plátano verde', 'Pazifikfisch mit Kokosmilch und grüner Kochbanane geschmort', 'fish_seafood', 'dinner', 19, 12, 7, 'stewing', 'pacifico'),
  B('co-phase-a-053', 'أبورّاخادو موز ناضج محشو بجبن كوستينيو', 'Aborrajado Ripe Plantain Stuffed with Queso Costeno', 'Aborrajado de banane plantain mûre farcie au queso costeno', 'Aborrajado de plátano maduro relleno de queso costeño', 'Aborrajado aus reifer Kochbanane mit Queso Costeno', 'street_snacks', 'snack', 11, 30, 8, 'frying', 'valle'),
  B('co-phase-a-054', 'أرز دي ليسا بالسمك والخضار', 'Arroz de Lisa with Fish and Vegetables', 'Arroz de lisa au poisson et légumes', 'Arroz de lisa con pescado y verduras', 'Arroz de Lisa mit Fisch und Gemüse', 'fish_seafood', 'dinner', 17, 21, 6, 'simmering', 'caribe'),
  B('co-phase-a-055', 'تامال نارينيو بالدجاج والذرة', 'Narinense Chicken and Corn Tamal', 'Tamal nariñense au poulet et maïs', 'Tamal nariñense de pollo y maíz', 'Nariño-Hähnchen-Maistamal', 'poultry_mains', 'lunch', 16, 23, 7, 'steaming', 'narino'),
  B('co-phase-a-056', 'أريبا بيتو بلحم البقر والأفوكادو', 'Arepa de Peto with Beef and Avocado', 'Arepa de peto au bœuf et avocat', 'Arepa de peto con res y aguacate', 'Arepa de Peto mit Rindfleisch und Avocado', 'meat_mains', 'lunch', 19, 21, 9, 'griddling', 'santander'),
  B('co-phase-a-057', 'دجاج بصلصة التمر الهندي والليمون', 'Chicken with Tamarind and Lime Sauce', 'Poulet à la sauce tamarin et citron vert', 'Pollo con salsa de tamarindo y lima', 'Hähnchen mit Tamarinden-Limetten-Soße', 'poultry_mains', 'dinner', 21, 8, 7, 'braising', 'valle'),
  B('co-phase-a-058', 'يخنة لحم بقري باليوكا والموز الأخضر', 'Beef Stew with Cassava and Green Plantain', 'Ragoût de bœuf au manioc et banane plantain verte', 'Guiso de res con yuca y plátano verde', 'Rindereintopf mit Maniok und grüner Kochbanane', 'meat_mains', 'dinner', 18, 13, 8, 'stewing', 'llanos'),
  B('co-phase-a-059', 'أقراص يوكا بجبن كوستينيو والبيض', 'Cassava Cakes with Queso Costeno and Egg', 'Galettes de manioc au queso costeno et œuf', 'Torticas de yuca con queso costeño y huevo', 'Maniokküchlein mit Queso Costeno und Ei', 'breakfast_items', 'breakfast', 12, 24, 8, 'pan_frying', 'caribe'),
  B('co-phase-a-060', 'بيض بيريكوس بالبصل الأخضر والطماطم', 'Huevos Pericos with Scallion and Tomato', 'Huevos pericos à l’oignon vert et tomate', 'Huevos pericos con cebolla larga y tomate', 'Huevos Pericos mit Frühlingszwiebel und Tomate', 'breakfast_items', 'breakfast', 13, 5, 9, 'sauteing', 'bogota'),
  B('co-phase-a-061', 'كوسيدو بوياكينسي بلحم البقر والذرة', 'Boyaca Cocido with Beef and Corn', 'Cocido de Boyaca au bœuf et maïs', 'Cocido boyacense con res y maíz', 'Boyaca-Cocido mit Rindfleisch und Mais', 'soups_stews', 'lunch', 16, 15, 7, 'simmering', 'boyaca'),
  B('co-phase-a-062', 'فريخولادا دجاج بالذرة والموز الناضج', 'Chicken Frijolada with Corn and Ripe Plantain', 'Frijolada de poulet au maïs et banane plantain mûre', 'Frijolada de pollo con maíz y plátano maduro', 'Hähnchen-Frijolada mit Mais und reifer Kochbanane', 'soups_stews', 'lunch', 16, 17, 6, 'simmering', 'antioquia'),
  B('co-phase-a-063', 'يخنة عدس بالكركم ولحم البقر والبطاطس', 'Lentil Stew with Turmeric, Beef and Potato', 'Ragoût de lentilles au curcuma, bœuf et pomme de terre', 'Guiso de lentejas con cúrcuma, res y papa', 'Linseneintopf mit Kurkuma, Rind und Kartoffel', 'soups_stews', 'dinner', 17, 14, 6, 'simmering', 'cundinamarca'),
];
