import { B } from './rows.mjs';

export default [
  B('co-phase-a-201', 'شوربة كارانْتانتا بالدجاج والذرة', 'Carantanta Soup with Chicken and Corn', 'Soupe de carantanta au poulet et maïs', 'Sopa de carantanta con pollo y maíz', 'Carantanta-Suppe mit Hähnchen und Mais', 'soups_stews', 'lunch', 14, 13, 5, 'simmering', 'narino'),
  B('co-phase-a-202', 'لحم بقري بصلصة أوفّاس والكينوا', 'Beef with Uchuva Sauce and Quinoa', 'Bœuf à la sauce uchuva et quinoa', 'Res con salsa de uchuva y quinoa', 'Rindfleisch mit Uchuva-Soße und Quinoa', 'meat_mains', 'dinner', 21, 10, 8, 'braising', 'cundinamarca'),
  B('co-phase-a-203', 'روندون ساحلي بالسمك واليوكا وحليب جوز الهند', 'Coastal Rondón with Fish, Cassava and Coconut Milk', 'Rondón côtier au poisson, manioc et lait de coco', 'Rondón costeño de pescado con yuca y leche de coco', 'Küsten-Rondón mit Fisch, Maniok und Kokosmilch', 'fish_seafood', 'dinner', 18, 15, 8, 'simmering', 'caribe'),
  B('co-phase-a-204', 'كاسويلا تشونتادورو بالديك الرومي والذرة', 'Chontaduro Cazuela with Turkey and Corn', 'Cazuela de chontaduro à la dinde et au maïs', 'Cazuela de chontaduro con pavo y maíz', 'Chontaduro-Cazuela mit Pute und Mais', 'poultry_mains', 'dinner', 19, 13, 7, 'simmering', 'pacifico'),
  B('co-phase-a-205', 'مرق سمك نهري بالتشونتادورو والليمون', 'River Fish Broth with Chontaduro and Lime', 'Bouillon de poisson de rivière au chontaduro et citron vert', 'Caldo de pescado de río con chontaduro y lima', 'Flussfischbrühe mit Chontaduro und Limette', 'fish_seafood', 'lunch', 18, 9, 5, 'simmering', 'llanos'),
  B('co-phase-a-206', 'كوسيدو تشوغواس بلحم البقر والذرة', 'Cocido de Chuguas with Beef and Corn', 'Cocido de chuguas au bœuf et maïs', 'Cocido de chuguas con res y maíz', 'Chuguas-Cocido mit Rindfleisch und Mais', 'soups_stews', 'lunch', 16, 15, 7, 'simmering', 'boyaca'),
  B('co-phase-a-207', 'دجاج بالكوروزو والكينوا', 'Chicken with Corozo and Quinoa', 'Poulet au corozo et quinoa', 'Pollo con corozo y quinoa', 'Hähnchen mit Corozo und Quinoa', 'poultry_mains', 'dinner', 21, 10, 7, 'braising', 'caribe'),
  B('co-phase-a-208', 'تارت تشونتادورو بالريكوتا والليمون', 'Chontaduro Ricotta Tart with Lime', 'Tarte de chontaduro à la ricotta et citron vert', 'Tarta de chontaduro con ricota y lima', 'Chontaduro-Ricotta-Tarte mit Limette', 'rice_cakes_sweets', 'snack', 10, 25, 8, 'baking', 'pacifico'),
  B('co-phase-a-209', 'ميداليونات لحم بقري بالأفوكادو وهوغاو', 'Beef Medallions with Avocado and Hogao', 'Médaillons de bœuf à l’avocat et hogao', 'Medallones de res con aguacate y hogao', 'Rindermedaillons mit Avocado und Hogao', 'meat_mains', 'dinner', 23, 5, 11, 'grilling', 'antioquia'),
  B('co-phase-a-210', 'سيفيتشي قلوب النخيل بالروبيان والليمون', 'Palm Heart and Shrimp Ceviche with Lime', 'Ceviche de cœurs de palmier et crevettes au citron vert', 'Ceviche de palmito y camarón con lima', 'Palmherz-Garnelen-Ceviche mit Limette', 'fish_seafood', 'lunch', 17, 8, 4, 'marinating', 'pacifico'),
  B('co-phase-a-211', 'شوربة موز أخضر باللحم البقري والكزبرة', 'Green Plantain Soup with Beef and Cilantro', 'Soupe de banane plantain verte au bœuf et coriandre', 'Sopa de plátano verde con res y cilantro', 'Grüne-Kochbananen-Suppe mit Rindfleisch und Koriander', 'soups_stews', 'lunch', 15, 15, 5, 'simmering', 'caribe'),
  B('co-phase-a-212', 'كروكيت أرز بالجبن والفاصولياء', 'Rice Croquettes with Cheese and Beans', 'Croquettes de riz au fromage et haricots', 'Croquetas de arroz con queso y frijoles', 'Reiskroketten mit Käse und Bohnen', 'vegetable_mains', 'snack', 12, 22, 7, 'baking', 'cundinamarca'),
  B('co-phase-a-213', 'لحم بقري بصلصة الطماطم والجوافة الخضراء', 'Beef with Tomato and Green Guava Sauce', 'Bœuf à la sauce tomate et goyave verte', 'Res con salsa de tomate y guayaba verde', 'Rindfleisch mit Tomaten-Gravensoße', 'meat_mains', 'dinner', 20, 9, 8, 'stewing', 'valle'),
];
