import { B } from './rows.mjs';

export default [
  B('co-phase-a-176', 'شوربة جبن كوستينيو بالذرة والبصل الأخضر', 'Queso Costeno Soup with Corn and Scallion', 'Soupe de queso costeno au maïs et oignon vert', 'Sopa de queso costeño con maíz y cebolla larga', 'Queso-Costeno-Suppe mit Mais und Frühlingszwiebel', 'soups_stews', 'lunch', 13, 11, 8, 'simmering', 'caribe'),
  B('co-phase-a-177', 'أريبا قمح كاملة بالبيض والأفوكادو', 'Whole Wheat Arepa with Egg and Avocado', 'Arepa de blé complet à l’œuf et avocat', 'Arepa integral con huevo y aguacate', 'Vollkorn-Arepa mit Ei und Avocado', 'breakfast_items', 'breakfast', 13, 20, 8, 'griddling', 'boyaca'),
  B('co-phase-a-178', 'بوكاتشيكو بصلصة الجوافة والبانِيلا', 'Bocachico with Guava and Panela Sauce', 'Bocachico à la sauce goyave et panela', 'Bocachico con salsa de guayaba y panela', 'Bocachico mit Guaven-Panela-Soße', 'fish_seafood', 'dinner', 20, 9, 7, 'braising', 'caribe'),
  B('co-phase-a-179', 'يخنة لحم بقري بالتشونتادورو والذرة', 'Beef Stew with Chontaduro and Corn', 'Ragoût de bœuf au chontaduro et maïs', 'Guiso de res con chontaduro y maíz', 'Rindfleischeintopf mit Chontaduro und Mais', 'meat_mains', 'dinner', 19, 12, 8, 'stewing', 'pacifico'),
  B('co-phase-a-180', 'دجاج مطهو بالأراجّاتشا والذرة والأوريغانو', 'Chicken Stewed with Arracacha, Corn and Oregano', 'Poulet mijoté à l’arracacha, maïs et origan', 'Pollo guisado con arracacha, maíz y orégano', 'Hähnchen mit Arracacha, Mais und Oregano geschmort', 'poultry_mains', 'dinner', 20, 12, 7, 'stewing', 'boyaca'),
  B('co-phase-a-181', 'كروكيت العدس والموز الأخضر بالكزبرة', 'Lentil and Green Plantain Croquettes with Cilantro', 'Croquettes de lentilles et banane plantain verte à la coriandre', 'Croquetas de lentejas y plátano verde con cilantro', 'Linsen-Grüne-Kochbananen-Kroketten mit Koriander', 'vegetable_mains', 'lunch', 12, 19, 6, 'baking', 'caribe'),
  B('co-phase-a-182', 'سودادو ذيل البقر بالأراجّاتشا والطماطم', 'Oxtail Sudado with Arracacha and Tomato', 'Sudado de queue de bœuf à l’arracacha et tomate', 'Sudado de cola de res con arracacha y tomate', 'Ochsenschwanz-Sudado mit Arracacha und Tomate', 'meat_mains', 'dinner', 19, 8, 10, 'braising', 'cundinamarca'),
  B('co-phase-a-183', 'كاسويلا أسماك وفاصولياء سوداء بحليب جوز الهند', 'Fish and Black Bean Cazuela with Coconut Milk', 'Cazuela de poisson et haricots noirs au lait de coco', 'Cazuela de pescado y frijoles negros con leche de coco', 'Fisch-Schwarze-Bohnen-Cazuela mit Kokosmilch', 'fish_seafood', 'dinner', 18, 13, 7, 'simmering', 'pacifico'),
  B('co-phase-a-184', 'أريبا موز أخضر بجبن طازج والهوغاو', 'Green Plantain Arepa with Fresh Cheese and Hogao', 'Arepa de banane plantain verte au fromage frais et hogao', 'Arepa de plátano verde con queso fresco y hogao', 'Grüne Kochbananen-Arepa mit Frischkäse und Hogao', 'breakfast_items', 'breakfast', 12, 24, 7, 'griddling', 'caribe'),
  B('co-phase-a-185', 'سيفيتشي سمك باللولو والبصل الأحمر', 'Fish Ceviche with Lulo and Red Onion', 'Ceviche de poisson au lulo et oignon rouge', 'Ceviche de pescado con lulo y cebolla morada', 'Fisch-Ceviche mit Lulo und roter Zwiebel', 'fish_seafood', 'lunch', 19, 7, 4, 'marinating', 'valle'),
  B('co-phase-a-186', 'أرز بني بالدجاج والتشونتادورو والفاصولياء', 'Brown Rice with Chicken, Chontaduro and Beans', 'Riz complet au poulet, chontaduro et haricots', 'Arroz integral con pollo, chontaduro y frijoles', 'Vollkornreis mit Hähnchen, Chontaduro und Bohnen', 'poultry_mains', 'dinner', 17, 21, 7, 'simmering', 'pacifico'),
  B('co-phase-a-187', 'سلطة تشونتادورو بالأفوكادو والطماطم', 'Chontaduro Salad with Avocado and Tomato', 'Salade de chontaduro à l’avocat et tomate', 'Ensalada de chontaduro con aguacate y tomate', 'Chontaduro-Salat mit Avocado und Tomate', 'salads', 'lunch', 10, 16, 6, 'assembling', 'pacifico'),
];
