import { B } from './rows.mjs';

export default [
  B('co-phase-a-126', 'بيض في مرق الدجاج بالأريبا والسبانخ', 'Eggs in Chicken Broth with Arepa and Spinach', 'Œufs au bouillon de poulet avec arepa et épinards', 'Huevos en caldo de pollo con arepa y espinaca', 'Eier in Hühnerbrühe mit Arepa und Spinat', 'breakfast_items', 'breakfast', 14, 12, 8, 'simmering', 'bogota'),
  B('co-phase-a-127', 'دجاج مطهو بأراجّاتشا والذرة', 'Chicken Sudado with Arracacha and Corn', 'Sudado de poulet à l’arracacha et maïs', 'Sudado de pollo con arracacha y maíz', 'Hähnchen-Sudado mit Arracacha und Mais', 'poultry_mains', 'dinner', 18, 12, 6, 'braising', 'boyaca'),
  B('co-phase-a-128', 'أريبا موتي بالدجاج والفاصولياء وجبن كوستينيو', 'Mote Arepa with Chicken, Beans and Queso Costeno', 'Arepa de mote au poulet, haricots et queso costeno', 'Arepa de mote con pollo, frijoles y queso costeño', 'Mote-Arepa mit Hähnchen, Bohnen und Queso Costeno', 'poultry_mains', 'lunch', 16, 21, 8, 'griddling', 'santander'),
  B('co-phase-a-129', 'أرز باللحم البقري والموز الناضج', 'Beef Rice with Ripe Plantain', 'Riz au bœuf et banane plantain mûre', 'Arroz con res y plátano maduro', 'Rindfleischreis mit reifer Kochbanane', 'meat_mains', 'dinner', 18, 22, 7, 'simmering', 'caribe'),
  B('co-phase-a-130', 'بيستيك كريولا بهوغاو وبيوريه الذرة', 'Bistec Criollo with Hogao and Corn Puree', 'Bistec criollo au hogao et purée de maïs', 'Bistec criollo con hogao y puré de maíz', 'Bistec Criollo mit Hogao und Maispüree', 'meat_mains', 'dinner', 22, 9, 11, 'pan_frying', 'antioquia'),
  B('co-phase-a-131', 'كاسويلا غاندول بالدجاج والقرع', 'Guandu Bean Cazuela with Chicken and Squash', 'Cazuela de pois guandu au poulet et courge', 'Cazuela de guandú con pollo y zapallo', 'Guandu-Bohnen-Cazuela mit Hähnchen und Kürbis', 'soups_stews', 'lunch', 16, 15, 6, 'simmering', 'caribe'),
  B('co-phase-a-132', 'تورتا موز ناضج بلحم البقر وجبن كوستينيو', 'Ripe Plantain Bake with Beef and Queso Costeno', 'Gratin de banane plantain mûre au bœuf et queso costeno', 'Torta de plátano maduro con res y queso costeño', 'Auflauf aus reifer Kochbanane mit Rind und Queso Costeno', 'meat_mains', 'dinner', 17, 17, 9, 'baking', 'caribe'),
  B('co-phase-a-133', 'سودادو ميرلوزا باليوكا والطماطم والذرة', 'Merluza Sudado with Cassava, Tomato and Corn', 'Sudado de merluza au manioc, tomate et maïs', 'Sudado de merluza con yuca, tomate y maíz', 'Merluza-Sudado mit Maniok, Tomate und Mais', 'fish_seafood', 'lunch', 19, 13, 5, 'braising', 'caribe'),
  B('co-phase-a-134', 'دجاج بصلصة اللولو والبازلاء', 'Chicken with Lulo Sauce and Peas', 'Poulet à la sauce lulo et petits pois', 'Pollo en salsa de lulo y arvejas', 'Hähnchen mit Lulo-Soße und Erbsen', 'poultry_mains', 'dinner', 21, 8, 7, 'braising', 'valle'),
  B('co-phase-a-135', 'كروكيت يوكا بالجبن والكزبرة', 'Cassava Croquettes with Cheese and Cilantro', 'Croquettes de manioc au fromage et coriandre', 'Croquetas de yuca con queso y cilantro', 'Maniokkroketten mit Käse und Koriander', 'vegetable_mains', 'snack', 11, 23, 7, 'baking', 'narino'),
  B('co-phase-a-136', 'شوربة أرز باللحم البقري والفاصولياء الخضراء', 'Beef Rice Soup with Green Beans', 'Soupe de riz au bœuf et haricots verts', 'Sopa de arroz con res y habichuelas verdes', 'Rind-Reis-Suppe mit grünen Bohnen', 'soups_stews', 'lunch', 15, 13, 5, 'simmering', 'cundinamarca'),
  B('co-phase-a-137', 'سمك موخارّا بصلصة جوز الهند والتمر الهندي', 'Mojarra with Coconut and Tamarind Sauce', 'Mojarra à la sauce coco et tamarin', 'Mojarra con salsa de coco y tamarindo', 'Mojarra mit Kokos-Tamarinden-Soße', 'fish_seafood', 'dinner', 20, 8, 8, 'braising', 'caribe'),
];
