import { B } from './rows.mjs';

export default [
  B('co-phase-a-151', 'بوتشيرو بوغوتا بلحم البقر والذرة واليوكا', 'Bogota Puchero with Beef, Corn and Cassava', 'Puchero de Bogota au bœuf, maïs et manioc', 'Puchero bogotano con res, maíz y yuca', 'Bogota-Puchero mit Rind, Mais und Maniok', 'soups_stews', 'lunch', 17, 14, 7, 'simmering', 'bogota'),
  B('co-phase-a-152', 'شوربة إنديوس بكرات الذرة والبيض', 'Sopa de Indios with Corn Dumplings and Egg', 'Sopa de indios aux boulettes de maïs et œuf', 'Sopa de indios con bolitas de maíz y huevo', 'Sopa de Indios mit Maisklößchen und Ei', 'soups_stews', 'lunch', 12, 15, 5, 'simmering', 'boyaca'),
  B('co-phase-a-153', 'تورتيّا تشونتادورو بالبيض وجبن بانلا', 'Chontaduro Tortilla with Egg and Panela', 'Tortilla de chontaduro à l’œuf et panela', 'Tortilla de chontaduro con huevo y panela', 'Chontaduro-Tortilla mit Ei und Panela', 'breakfast_items', 'breakfast', 13, 18, 7, 'pan_frying', 'pacifico'),
  B('co-phase-a-154', 'مازامورا تشيكا بلحم البقر والفاصولياء والذرة', 'Mazamorra Chiquita with Beef, Beans and Corn', 'Mazamorra chiquita au bœuf, haricots et maïs', 'Mazamorra chiquita con res, frijoles y maíz', 'Mazamorra Chiquita mit Rind, Bohnen und Mais', 'soups_stews', 'lunch', 16, 15, 7, 'simmering', 'boyaca'),
  B('co-phase-a-155', 'كرات لحم بقري بأراجّاتشا وصلصة الكريولا', 'Beef Meatballs with Arracacha and Criolla Sauce', 'Boulettes de bœuf à l’arracacha et sauce criolla', 'Albóndigas de res con arracacha y salsa criolla', 'Rindfleischbällchen mit Arracacha und Criolla-Soße', 'meat_mains', 'dinner', 19, 10, 8, 'simmering', 'cundinamarca'),
  B('co-phase-a-156', 'سمك مخبوز بالتمر الهندي والغواسكاس', 'Baked Fish with Tamarind and Guascas', 'Poisson au four au tamarin et guascas', 'Pescado al horno con tamarindo y guascas', 'Ofenfisch mit Tamarinde und Guascas', 'fish_seafood', 'dinner', 20, 7, 7, 'baking', 'bogota'),
  B('co-phase-a-157', 'كيك أرز بجبن كامبيسينو وهوغاو', 'Rice Cake with Queso Campesino and Hogao', 'Gâteau de riz au queso campesino et hogao', 'Torta de arroz con queso campesino y hogao', 'Reiskuchen mit Queso Campesino und Hogao', 'vegetable_mains', 'lunch', 12, 21, 7, 'baking', 'cundinamarca'),
  B('co-phase-a-158', 'دجاج بالكوروزو واليوكا', 'Chicken with Corozo Sauce and Cassava', 'Poulet à la sauce corozo et manioc', 'Pollo con salsa de corozo y yuca', 'Hähnchen mit Corozo-Soße und Maniok', 'poultry_mains', 'dinner', 20, 11, 7, 'braising', 'caribe'),
  B('co-phase-a-159', 'فريخول العين السوداء بالطماطم والتشونتادورو', 'Black-Eyed Peas with Tomato and Chontaduro', 'Niébés à la tomate et chontaduro', 'Frijol cabecita negra con tomate y chontaduro', 'Augenbohnen mit Tomate und Chontaduro', 'vegetable_mains', 'lunch', 10, 20, 5, 'stewing', 'pacifico'),
  B('co-phase-a-160', 'روبيان بالأناناس والبانِيلا', 'Shrimp with Pineapple and Panela', 'Crevettes à l’ananas et panela', 'Camarones con piña y panela', 'Garnelen mit Ananas und Panela', 'fish_seafood', 'dinner', 19, 9, 6, 'sauteing', 'caribe'),
  B('co-phase-a-161', 'أريبا أرز بجبن كوستينيو والأفوكادو', 'Rice Arepa with Queso Costeno and Avocado', 'Arepa de riz au queso costeno et avocat', 'Arepa de arroz con queso costeño y aguacate', 'Reis-Arepa mit Queso Costeno und Avocado', 'breakfast_items', 'breakfast', 12, 23, 8, 'griddling', 'tolima'),
  B('co-phase-a-162', 'سمك مملح مطهو بجوز الهند والموز الأخضر', 'Salted Fish Stewed with Coconut and Green Plantain', 'Poisson salé mijoté à la noix de coco et banane plantain verte', 'Pescado salado guisado con coco y plátano verde', 'Gesalzener Fisch mit Kokos und grüner Kochbanane geschmort', 'fish_seafood', 'dinner', 19, 13, 7, 'stewing', 'pacifico'),
  B('co-phase-a-163', 'تامال بيبيان بلحم البقر والفول السوداني والبطاطس', 'Pipian Tamal with Beef, Peanuts and Potato', 'Tamal pipian au bœuf, cacahuètes et pomme de terre', 'Tamal de pipián con res, maní y papa', 'Pipian-Tamal mit Rindfleisch, Erdnüssen und Kartoffel', 'street_snacks', 'lunch', 16, 22, 8, 'steaming', 'narino'),
];
