import { B } from './rows.mjs';

export default [
  B('co-phase-a-001', 'أريبا بيض باللحم وصلصة هوغاو', 'Caribbean Arepa de Huevo with Beef and Hogao', 'Arepa de huevo caraïbe au bœuf et hogao', 'Arepa de huevo caribeña con res y hogao', 'Karibische Arepa de Huevo mit Rind und Hogao', 'breakfast_items', 'breakfast', 14, 19, 9, 'frying', 'caribe'),
  B('co-phase-a-002', 'أخياكو بوغوتا بالدجاج والذرة والبطاطس', 'Bogota Ajiaco with Chicken, Corn and Potatoes', 'Ajiaco de Bogota au poulet, maïs et pommes de terre', 'Ajiaco bogotano de pollo, maíz y papa', 'Bogota-Ajiaco mit Hähnchen, Mais und Kartoffeln', 'soups_stews', 'lunch', 16, 10, 5, 'simmering', 'bogota'),
  B('co-phase-a-003', 'سانكوتشو دجاج باليوكا والموز الأخضر', 'Chicken Sancocho with Cassava and Green Plantain', 'Sancocho de poulet au manioc et banane plantain verte', 'Sancocho de pollo con yuca y plátano verde', 'Hähnchen-Sancocho mit Maniok und grüner Kochbanane', 'soups_stews', 'lunch', 15, 13, 5, 'simmering', 'valle'),
  B('co-phase-a-004', 'فريخول أنتيوقينو بلحم البقر وفاصولياء كارجامانتو', 'Antioquian Beef and Cargamanto Bean Stew', 'Ragoût antioquien de bœuf et haricots cargamanto', 'Guiso antioqueño de res y frijol cargamanto', 'Antioquischer Rind-Cargamanto-Bohneneintopf', 'soups_stews', 'dinner', 17, 14, 8, 'stewing', 'antioquia'),
  B('co-phase-a-005', 'باتاكون باللحم المفتت والأفوكادو وهوغاو', 'Patacon with Shredded Beef, Avocado and Hogao', 'Patacon au bœuf effiloché, avocat et hogao', 'Patacón con carne desmechada, aguacate y hogao', 'Patacon mit gezupftem Rind, Avocado und Hogao', 'meat_mains', 'lunch', 18, 17, 9, 'frying', 'caribe'),
  B('co-phase-a-006', 'أريبا بوياكينسي بالذرة والجبن الطازج', 'Boyaca Arepa with Corn and Fresh Cheese', 'Arepa de Boyaca au maïs et fromage frais', 'Arepa boyacense de maíz y queso fresco', 'Boyaca-Arepa mit Mais und Frischkäse', 'street_snacks', 'snack', 11, 24, 7, 'griddling', 'boyaca'),
  B('co-phase-a-007', 'لحم سانتانديري مجفف مشوي بالهوغاو', 'Santander Carne Oreada with Hogao', 'Carne oreada de Santander au hogao', 'Carne oreada santandereana con hogao', 'Santander-Carne-Oreada mit Hogao', 'meat_mains', 'dinner', 24, 4, 9, 'grilling', 'santander'),
  B('co-phase-a-008', 'موتي دي كيسو باليام وجبن كوستينيو', 'Mote de Queso with Yam and Queso Costeno', 'Mote de queso à l’igname et queso costeno', 'Mote de queso con ñame y queso costeño', 'Mote de Queso mit Yamswurzel und Queso Costeno', 'soups_stews', 'lunch', 12, 15, 7, 'simmering', 'caribe'),
  B('co-phase-a-009', 'دجاج مطهو باليوكا والبطاطس والطماطم', 'Chicken Sudado with Cassava, Potato and Tomato', 'Poulet sudado au manioc, pomme de terre et tomate', 'Sudado de pollo con yuca, papa y tomate', 'Hähnchen-Sudado mit Maniok, Kartoffel und Tomate', 'poultry_mains', 'dinner', 17, 11, 6, 'braising', 'cundinamarca'),
  B('co-phase-a-010', 'مرق أضلاع البقر بالذرة والبطاطس', 'Beef Rib Caldo with Corn and Potato', 'Caldo de côtes de bœuf au maïs et pomme de terre', 'Caldo de costilla de res con maíz y papa', 'Rinder-Rippchen-Caldo mit Mais und Kartoffel', 'soups_stews', 'breakfast', 16, 9, 8, 'simmering', 'bogota'),
  B('co-phase-a-011', 'إمبانادا بيبيان بالدجاج والبطاطس والفول السوداني', 'Pipian Empanada with Chicken, Potato and Peanuts', 'Empanada pipian au poulet, pomme de terre et cacahuètes', 'Empanada de pipián con pollo, papa y maní', 'Pipian-Empanada mit Hähnchen, Kartoffel und Erdnüssen', 'street_snacks', 'snack', 15, 19, 8, 'baking', 'narino'),
  B('co-phase-a-012', 'كايييه بالموز الأخضر وجبن كوستينيو والبيض', 'Cayeye with Green Plantain, Queso Costeno and Egg', 'Cayeye à la banane plantain verte, queso costeno et œuf', 'Cayeye de plátano verde con queso costeño y huevo', 'Cayeye mit grüner Kochbanane, Queso Costeno und Ei', 'breakfast_items', 'breakfast', 13, 22, 8, 'mashing', 'caribe'),
  B('co-phase-a-013', 'تامال توليمينسي بالدجاج ولحم البقر والأرز', 'Tolima Tamal with Chicken, Beef and Rice', 'Tamal du Tolima au poulet, bœuf et riz', 'Tamal tolimense de pollo, res y arroz', 'Tolima-Tamal mit Hähnchen, Rind und Reis', 'street_snacks', 'lunch', 16, 21, 9, 'steaming', 'tolima'),
];
