import { B } from './rows.mjs';

export default [
  B('co-phase-a-226', 'شوربة باغري باليوكا وحليب جوز الهند', 'Bagre Soup with Cassava and Coconut Milk', 'Soupe de bagre au manioc et lait de coco', 'Sopa de bagre con yuca y leche de coco', 'Bagre-Suppe mit Maniok und Kokosmilch', 'fish_seafood', 'lunch', 18, 12, 7, 'simmering', 'pacifico'),
  B('co-phase-a-227', 'أريبا كينوا بالدجاج والأفوكادو', 'Quinoa Arepa with Chicken and Avocado', 'Arepa au quinoa, poulet et avocat', 'Arepa de quinoa con pollo y aguacate', 'Quinoa-Arepa mit Hähnchen und Avocado', 'poultry_mains', 'breakfast', 17, 22, 8, 'griddling', 'boyaca'),
  B('co-phase-a-228', 'لحم بقري بأراجّاتشا وصلصة أوفّاس', 'Beef with Arracacha and Uchuva Sauce', 'Bœuf à l’arracacha et sauce uchuva', 'Res con arracacha y salsa de uchuva', 'Rindfleisch mit Arracacha und Uchuva-Soße', 'meat_mains', 'dinner', 21, 8, 9, 'braising', 'cundinamarca'),
  B('co-phase-a-229', 'شوربة غواسكاس بالدجاج وكرات الذرة', 'Guascas Chicken Soup with Corn Dumplings', 'Soupe de poulet aux guascas et boulettes de maïs', 'Sopa de pollo con guascas y bolitas de maíz', 'Guascas-Hühnersuppe mit Maisklößchen', 'soups_stews', 'lunch', 15, 13, 5, 'simmering', 'bogota'),
  B('co-phase-a-230', 'أرز بني بالتشونتادورو وبيوريه الفاصولياء', 'Brown Rice with Chontaduro and Bean Puree', 'Riz complet au chontaduro et purée de haricots', 'Arroz integral con chontaduro y puré de frijoles', 'Vollkornreis mit Chontaduro und Bohnenpüree', 'vegetable_mains', 'lunch', 11, 24, 6, 'simmering', 'pacifico'),
  B('co-phase-a-231', 'خبز يوكا محشو بالفاصولياء السوداء والجبن', 'Cassava Bread Stuffed with Black Beans and Cheese', 'Pain de manioc farci aux haricots noirs et fromage', 'Pan de yuca relleno de frijoles negros y queso', 'Maniokbrot gefüllt mit schwarzen Bohnen und Käse', 'street_snacks', 'snack', 12, 23, 7, 'baking', 'narino'),
  B('co-phase-a-232', 'سمك بصلصة الطماطم الخضراء والموز', 'Fish with Green Tomato Sauce and Plantain', 'Poisson à la sauce de tomate verte et plantain', 'Pescado con salsa de tomate verde y plátano', 'Fisch mit grüner Tomatensoße und Kochbanane', 'fish_seafood', 'dinner', 20, 10, 7, 'braising', 'valle'),
  B('co-phase-a-233', 'سلطة ديك رومي باليوكا والمانجو', 'Turkey Salad with Cassava and Mango', 'Salade de dinde au manioc et à la mangue', 'Ensalada de pavo con yuca y mango', 'Putensalat mit Maniok und Mango', 'salads', 'lunch', 18, 11, 6, 'assembling', 'caribe'),
  B('co-phase-a-234', 'فطيرة العدس وجبن كوستينيو بالأوريغانو', 'Lentil and Queso Costeno Pie with Oregano', 'Tourte aux lentilles et queso costeno à l’origan', 'Pastel de lentejas y queso costeño con orégano', 'Linsen-Queso-Costeno-Pastete mit Oregano', 'vegetable_mains', 'dinner', 13, 19, 8, 'baking', 'santander'),
  B('co-phase-a-235', 'كاسويلا بوكاتشيكو بالموز الناضج والذرة', 'Bocachico Cazuela with Ripe Plantain and Corn', 'Cazuela de bocachico à la banane plantain mûre et maïs', 'Cazuela de bocachico con plátano maduro y maíz', 'Bocachico-Cazuela mit reifer Kochbanane und Mais', 'fish_seafood', 'dinner', 19, 18, 7, 'simmering', 'caribe'),
  B('co-phase-a-236', 'ديك رومي بصلصة الطماطم الشجرية والغواسكاس', 'Turkey with Tree Tomato and Guascas Sauce', 'Dinde à la sauce tomate en arbre et guascas', 'Pavo con salsa de tomate de árbol y guascas', 'Pute mit Baumtomaten-Guascas-Soße', 'poultry_mains', 'dinner', 21, 8, 7, 'braising', 'boyaca'),
  B('co-phase-a-237', 'سمك قاروص بدقيق اليوكا والليمون', 'Sea Bass with Cassava Flour and Lime', 'Bar à la farine de manioc et citron vert', 'Róbalo con harina de yuca y lima', 'Wolfsbarsch mit Maniokmehl und Limette', 'fish_seafood', 'dinner', 21, 4, 7, 'pan_frying', 'caribe'),
];
