import { B } from './rows.mjs';

export default [
  B('co-phase-a-101', 'طبق بنديخا بايزا بلحم البقر والفاصولياء والبيض', 'Beef Bandeja Paisa with Beans, Egg and Avocado', 'Bandeja paisa au bœuf, haricots, œuf et avocat', 'Bandeja paisa de res con frijoles, huevo y aguacate', 'Bandeja Paisa mit Rind, Bohnen, Ei und Avocado', 'meat_mains', 'lunch', 19, 20, 12, 'grilling', 'antioquia'),
  B('co-phase-a-102', 'كاسويلا مأكولات بحرية بكريمة جوز الهند واليوكا', 'Seafood Cazuela with Coconut Cream and Cassava', 'Cazuela de fruits de mer à la crème de coco et manioc', 'Cazuela de mariscos con crema de coco y yuca', 'Meeresfrüchte-Cazuela mit Kokoscreme und Maniok', 'fish_seafood', 'dinner', 18, 14, 8, 'simmering', 'caribe'),
  B('co-phase-a-103', 'مازامورا أنتيوقينا بالذرة والحليب وجبن كوستينيو', 'Antioquian Mazamorra with Corn, Milk and Queso Costeno', 'Mazamorra antioquienne au maïs, lait et queso costeno', 'Mazamorra antioqueña con maíz, leche y queso costeño', 'Antioquische Mazamorra mit Mais, Milch und Queso Costeno', 'breakfast_items', 'breakfast', 10, 19, 6, 'simmering', 'antioquia'),
  B('co-phase-a-104', 'شوربة موندونغو بكرش البقر واليوكا', 'Beef Mondongo Soup with Cassava', 'Soupe de mondongo au bœuf et manioc', 'Sopa de mondongo de res con yuca', 'Rinder-Mondongo-Suppe mit Maniok', 'soups_stews', 'lunch', 17, 12, 6, 'simmering', 'bogota'),
  B('co-phase-a-105', 'أريبا ذرة مقشورة باللحم والأفوكادو', 'Pelao Corn Arepa with Beef and Avocado', 'Arepa de maïs pelao au bœuf et avocat', 'Arepa de maíz pelao con res y aguacate', 'Pelao-Mais-Arepa mit Rindfleisch und Avocado', 'meat_mains', 'lunch', 18, 22, 9, 'griddling', 'santander'),
  B('co-phase-a-106', 'موتي سانتانديريانو بلحم البقر والحمص والذرة', 'Santander Mute with Beef, Chickpeas and Corn', 'Mute santandereano au bœuf, pois chiches et maïs', 'Mute santandereano con res, garbanzos y maíz', 'Santander-Mute mit Rind, Kichererbsen und Mais', 'soups_stews', 'lunch', 16, 14, 7, 'simmering', 'santander'),
  B('co-phase-a-107', 'مرق باخاريا بلحم البقر والبطاطس', 'Beef Pajarilla Broth with Potato', 'Bouillon de pajarilla au bœuf et pomme de terre', 'Caldo de pajarilla de res con papa', 'Rinder-Pajarilla-Brühe mit Kartoffel', 'soups_stews', 'breakfast', 18, 7, 6, 'simmering', 'antioquia'),
  B('co-phase-a-108', 'بوكاتشيكو بصلصة هوغاو والطماطم', 'Bocachico with Hogao Tomato Sauce', 'Bocachico à la sauce tomate hogao', 'Bocachico con salsa de tomate y hogao', 'Bocachico mit Hogao-Tomatensoße', 'fish_seafood', 'dinner', 20, 6, 7, 'braising', 'caribe'),
  B('co-phase-a-109', 'كاسويلا دجاج وتشونتادورو والذرة', 'Chicken and Chontaduro Cazuela with Corn', 'Cazuela de poulet et chontaduro au maïs', 'Cazuela de pollo y chontaduro con maíz', 'Hähnchen-Chontaduro-Cazuela mit Mais', 'poultry_mains', 'dinner', 17, 14, 7, 'simmering', 'pacifico'),
  B('co-phase-a-110', 'أريبا الكينوا بالبيض والجبن الطازج', 'Quinoa Arepa with Egg and Fresh Cheese', 'Arepa au quinoa, œuf et fromage frais', 'Arepa de quinoa con huevo y queso fresco', 'Quinoa-Arepa mit Ei und Frischkäse', 'breakfast_items', 'breakfast', 14, 22, 7, 'griddling', 'santander'),
  B('co-phase-a-111', 'ألموخـابانا بالبيض والجبن والذرة', 'Almojabana with Egg, Cheese and Corn', 'Almojabana à l’œuf, fromage et maïs', 'Almojábana con huevo, queso y maíz', 'Almojabana mit Ei, Käse und Mais', 'breakfast_items', 'breakfast', 13, 22, 8, 'baking', 'cundinamarca'),
  B('co-phase-a-112', 'يخنة عدس بالدجاج واليقطين والذرة', 'Chicken Lentil Stew with Pumpkin and Corn', 'Ragoût de lentilles au poulet, courge et maïs', 'Guiso de lentejas con pollo, zapallo y maíz', 'Hühner-Linsen-Eintopf mit Kürbis und Mais', 'soups_stews', 'lunch', 15, 16, 5, 'stewing', 'tolima'),
  B('co-phase-a-113', 'أضلاع بقري بطلاء البانيلا والبرتقال', 'Beef Ribs with Panela and Orange Glaze', 'Côtes de bœuf glacées à la panela et orange', 'Costillas de res glaseadas con panela y naranja', 'Rinderrippen mit Panela-Orangen-Glasur', 'meat_mains', 'dinner', 22, 8, 12, 'roasting', 'antioquia'),
];
