import { E, T } from './rows.mjs';

export default [
  // noodle_dishes (20)
  E(`شعيرية الأرز الباردة بالخل ${T}`, 'Vinegary cold noodles', 'Nouilles froides vinaigrees', 'Fideos frios con vinagre', 'Kalte Essig-Nudeln', 'noodle_dishes', 'lunch', 6, 40, 4, 'raw', 'pan_korean'),
  E(`حساء الشعيرية البارد ${T}`, 'Mul naengmyeon cold noodle soup', 'Soupe de nouilles froides', 'Sopa fria de fideos', 'Kalte Nudelsuppe', 'noodle_dishes', 'lunch', 8, 42, 5, 'simmered', 'pan_korean'),
  E(`شعيرية الحنطة الحارة الباردة ${T}`, 'Bibim naengmyeon spicy cold noodles', 'Nouilles froides epicees', 'Fideos frios picantes', 'Scharfe kalte Nudeln', 'noodle_dishes', 'lunch', 6, 44, 6, 'raw', 'pan_korean'),
  E(`شعيرية الولائم ${T}`, 'Janchi guksu banquet noodles', 'Nouilles de banquet', 'Fideos de banquete', 'Bankett-Nudeln', 'noodle_dishes', 'lunch', 7, 40, 4, 'simmered', 'pan_korean'),
  E(`شعيرية الجيلاتين المطاطية ${T}`, 'Jjolmyeon chewy cold noodles', 'Nouilles froides elastiques', 'Fideos frios elasticos', 'Zaehe kalte Nudeln', 'noodle_dishes', 'lunch', 5, 45, 5, 'raw', 'pan_korean'),
  E(`شعيرية براعم الصويا ${T}`, 'Soybean sprout noodles', 'Nouilles aux germes de soja', 'Fideos con brotes de soja', 'Sojasprossen-Nudeln', 'noodle_dishes', 'lunch', 8, 38, 5, 'simmered', 'jeonju'),
  E(`شعيرية سمك القد المجفف ${T}`, 'Dried pollack noodles', 'Nouilles au colin seche', 'Fideos con abadejo seco', 'Getrocknete-Pollack-Nudeln', 'noodle_dishes', 'lunch', 11, 36, 4, 'simmered', 'gangneung'),
  E(`شعيرية الدجاج المقطعة ${T}`, 'Chicken knife-cut noodles', 'Nouilles coupees au poulet', 'Fideos cortados con pollo', 'Haehnchen-Bandnudeln', 'noodle_dishes', 'lunch', 14, 36, 7, 'simmered', 'pan_korean'),
  E(`شعيرية المحار المقطعة ${T}`, 'Clam knife-cut noodles', 'Nouilles coupees aux palourdes', 'Fideos cortados con almejas', 'Muschel-Bandnudeln', 'noodle_dishes', 'lunch', 12, 37, 5, 'simmered', 'tongyeong'),
  E(`شعيرية القمح المطاطية ${T}`, 'Wheat noodles', 'Nouilles de ble', 'Fideos de trigo', 'Weizennudeln', 'noodle_dishes', 'lunch', 7, 44, 3, 'raw', 'pan_korean'),
  E(`شعيرية الكمثرى الباردة ${T}`, 'Pear cold noodles', 'Nouilles froides a la poire', 'Fideos frios con pera', 'Kalte Birnen-Nudeln', 'noodle_dishes', 'lunch', 6, 42, 4, 'raw', 'pan_korean'),
  E(`شعيرية السمسم الباردة ${T}`, 'Sesame cold noodles', 'Nouilles froides au sesame', 'Fideos frios con sesamo', 'Kalte Sesam-Nudeln', 'noodle_dishes', 'lunch', 9, 40, 9, 'raw', 'pan_korean'),
  E(`شعيرية الفلفل الباردة ${T}`, 'Spicy cold noodles', 'Nouilles froides epicees au piment', 'Fideos frios con pimiento', 'Kalte Chili-Nudeln', 'noodle_dishes', 'lunch', 7, 43, 5, 'raw', 'pan_korean'),
  E(`حساء الشعيرية بالماكريل ${T}`, 'Mackerel noodle soup', 'Soupe de nouilles au maquereau', 'Sopa de fideos con caballa', 'Makrelen-Nudelsuppe', 'noodle_dishes', 'lunch', 16, 34, 7, 'simmered', 'busan'),
  E(`حساء الشعيرية بلحم البقر ${T}`, 'Beef and leek noodle soup', 'Soupe de nouilles au boeuf et poireau', 'Sopa de fideos con ternera y puerro', 'Rindfleisch-Lauch-Nudelsuppe', 'noodle_dishes', 'lunch', 15, 35, 7, 'simmered', 'seoul'),
  E(`حساء الشعيرية بالمحار الأخضر ${T}`, 'Green mussel noodle soup', 'Soupe de nouilles aux moules vertes', 'Sopa de fideos con mejillones', 'Gruene-Muschel-Nudelsuppe', 'noodle_dishes', 'lunch', 14, 35, 5, 'simmered', 'mokpo'),
  E(`حساء الشعيرية بالفطر ${T}`, 'Mushroom noodle soup', 'Soupe de nouilles aux champignons', 'Sopa de fideos con setas', 'Pilz-Nudelsuppe', 'noodle_dishes', 'lunch', 8, 38, 4, 'simmered', 'pan_korean'),
  E(`شعيرية الأرز الحارة ${T}`, 'Spicy rice noodles', 'Nouilles de riz epicees', 'Fideos de arroz picantes', 'Scharfe Reisnudeln', 'noodle_dishes', 'lunch', 8, 41, 7, 'stir-fried', 'pan_korean'),
  E(`حساء العجين الممزق ${T}`, 'Hand-torn dough soup', 'Soupe de pate dechiree', 'Sopa de masa desgarrada', 'Gerissene Teigsuppe', 'noodle_dishes', 'lunch', 9, 40, 5, 'simmered', 'pan_korean'),
  E(`حساء الشعيرية بالجبن ${T}`, 'Cheese ramyeon noodles', 'Nouilles instantanees au fromage', 'Fideos instantaneos con queso', 'Kaese-Ramyeon', 'noodle_dishes', 'lunch', 13, 42, 12, 'simmered', 'pan_korean'),

  // soups_stews (20)
  E(`حساء ضلع البقر ${T}`, 'Beef short rib soup', 'Soupe de cotes de boeuf', 'Sopa de costilla de ternera', 'Rinderrippen-Suppe', 'soups_stews', 'dinner', 22, 6, 10, 'simmered', 'seoul'),
  E(`حساء عظام البقر الأبيض ${T}`, 'Ox bone soup', 'Soupe a l os de boeuf', 'Sopa de hueso de buey', 'Ochsenknochen-Suppe', 'soups_stews', 'dinner', 20, 5, 9, 'simmered', 'pan_korean'),
  E(`حساء صدر البقر ${T}`, 'Beef brisket soup', 'Soupe de poitrine de boeuf', 'Sopa de pecho de ternera', 'Rinderbrust-Suppe', 'soups_stews', 'dinner', 19, 5, 10, 'simmered', 'pan_korean'),
  E(`حساء البقر الحار بالكراث ${T}`, 'Spicy beef and leek soup', 'Soupe epicee au boeuf et poireau', 'Sopa picante de ternera y puerro', 'Scharfe Rindfleisch-Lauch-Suppe', 'soups_stews', 'dinner', 17, 7, 9, 'simmered', 'pan_korean'),
  E(`حساء دجاج الجينسنغ ${T}`, 'Samgyetang ginseng chicken stew', 'Ragout de poulet au ginseng', 'Guiso de pollo con ginseng', 'Ginseng-Haehnchen-Eintopf', 'soups_stews', 'dinner', 24, 8, 12, 'simmered', 'pan_korean'),
  E(`حساء عظام الدجاج ${T}`, 'Chicken bone soup', 'Soupe a l os de poulet', 'Sopa de hueso de pollo', 'Haehnchenknochen-Suppe', 'soups_stews', 'dinner', 18, 5, 8, 'simmered', 'pan_korean'),
  E(`حساء كعك الأرز ${T}`, 'Rice cake soup', 'Soupe de gateau de riz', 'Sopa de pastel de arroz', 'Reiskuchen-Suppe', 'soups_stews', 'dinner', 10, 26, 5, 'simmered', 'pan_korean'),
  E(`حساء الزلابية ${T}`, 'Dumpling soup', 'Soupe de raviolis', 'Sopa de empanadillas', 'Teigtaschen-Suppe', 'soups_stews', 'dinner', 12, 24, 8, 'simmered', 'pan_korean'),
  E(`حساء الأعشاب البحرية ${T}`, 'Seaweed soup', 'Soupe d algues', 'Sopa de algas', 'Algensuppe', 'soups_stews', 'dinner', 6, 6, 4, 'simmered', 'busan'),
  E(`حساء براعم الصويا الحار ${T}`, 'Spicy soybean sprout soup', 'Soupe epicee de germes de soja', 'Sopa picante de brotes de soja', 'Scharfe Sojasprossen-Suppe', 'soups_stews', 'dinner', 7, 9, 4, 'simmered', 'jeonju'),
  E(`حساء القد المجفف ${T}`, 'Dried pollack soup', 'Soupe de colin seche', 'Sopa de abadejo seco', 'Getrocknete-Pollack-Suppe', 'soups_stews', 'dinner', 14, 5, 3, 'simmered', 'gangneung'),
  E(`حساء المحار الصغير ${T}`, 'Small clam soup', 'Soupe de petites palourdes', 'Sopa de almejas pequenas', 'Kleine-Muschel-Suppe', 'soups_stews', 'dinner', 11, 6, 3, 'simmered', 'mokpo'),
  E(`يخنة السمك الحارة ${T}`, 'Spicy fish stew', 'Ragout de poisson epice', 'Guiso picante de pescado', 'Scharfer Fischeintopf', 'soups_stews', 'dinner', 18, 8, 7, 'simmered', 'busan'),
  E(`حساء بيض القد ${T}`, 'Pollack roe soup', 'Soupe d oeufs de colin', 'Sopa de huevas de abadejo', 'Pollackrogen-Suppe', 'soups_stews', 'dinner', 15, 5, 7, 'simmered', 'pohang'),
  E(`حساء سمك اللوش ${T}`, 'Loach soup', 'Soupe de loche', 'Sopa de locha', 'Schmerlen-Suppe', 'soups_stews', 'dinner', 14, 6, 8, 'simmered', 'namhae'),
  E(`حساء عمود البقر بالبطاطس ${T}`, 'Beef spine and potato soup', 'Soupe d echine de boeuf et pommes de terre', 'Sopa de espinazo de ternera y patata', 'Rinderruecken-Kartoffel-Suppe', 'soups_stews', 'dinner', 20, 14, 12, 'simmered', 'daejeon'),
  E(`حساء علاج الإدمان ${T}`, 'Hangover beef soup', 'Soupe de boeuf pour la gueule de bois', 'Sopa de ternera para la resaca', 'Rindfleisch-Katersuppe', 'soups_stews', 'dinner', 17, 8, 10, 'simmered', 'seoul'),
  E(`حساء الدجاج الحار ${T}`, 'Spicy chicken soup', 'Soupe de poulet epicee', 'Sopa picante de pollo', 'Scharfe Haehnchensuppe', 'soups_stews', 'dinner', 18, 9, 9, 'simmered', 'daegu'),
  E(`حساء كرشة البقر ${T}`, 'Beef tripe soup', 'Soupe de tripes de boeuf', 'Sopa de callos de ternera', 'Rinderkuttel-Suppe', 'soups_stews', 'dinner', 19, 6, 11, 'simmered', 'pan_korean'),
  E(`يخنة بلح البحر ${T}`, 'Mussel stew', 'Ragout de moules', 'Guiso de mejillones', 'Muschel-Eintopf', 'soups_stews', 'dinner', 16, 10, 5, 'simmered', 'pohang'),
];
