import { E, T } from './rows.mjs';

export default [
  // fish_seafood (20)
  E(`ماكريل مشوي بالملح ${T}`, 'Salt-grilled mackerel', 'Maquereau grille au sel', 'Caballa a la parrilla con sal', 'Gegrillte Makrele mit Salz', 'fish_seafood', 'dinner', 20, 4, 12, 'grilled', 'busan'),
  E(`ماكريل مطهو ${T}`, 'Braised mackerel', 'Maquereau braise', 'Caballa guisada', 'Geschmorte Makrele', 'fish_seafood', 'dinner', 21, 6, 13, 'simmered', 'yeosu'),
  E(`سمك البوريان مشوي ${T}`, 'Grilled saury', 'Saury grille', 'Saury a la parrilla', 'Gegrillte Japan-Sardine', 'fish_seafood', 'dinner', 18, 3, 11, 'grilled', 'pan_korean'),
  E(`سمك الروبيان المشوي ${T}`, 'Grilled yellow croaker', 'Seiagre grille', 'Corvina a la parrilla', 'Gegrillte Gelbkopf-Seezunge', 'fish_seafood', 'dinner', 19, 3, 10, 'grilled', 'mokpo'),
  E(`سمك المسطوح المشوي ${T}`, 'Grilled flatfish', 'Cabillaud plat grille', 'Lenguado a la parrilla', 'Gegrillte Scholle', 'fish_seafood', 'dinner', 17, 3, 8, 'grilled', 'busan'),
  E(`سمك الصخر المشوي ${T}`, 'Grilled rockfish', 'Batrachope grouille', 'Raya a la parrilla', 'Gegrillter Klumpenfisch', 'fish_seafood', 'dinner', 19, 3, 8, 'grilled', 'pohang'),
  E(`سلطعون مبخر ${T}`, 'Steamed crab', 'Crabe vapeur', 'Cangrejo al vapor', 'Gedampfter Krebs', 'fish_seafood', 'dinner', 18, 2, 8, 'steamed', 'pan_korean'),
  E(`أخطبوط مطهو ${T}`, 'Braised octopus', 'Poulpe braise', 'Pulpo guisado', 'Geschmorener Oktopus', 'fish_seafood', 'dinner', 21, 6, 9, 'simmered', 'busan'),
  E(`أخطبوط مقلي حار ${T}`, 'Spicy stir-fried octopus', 'Poulpe saute epice', 'Pulpo salteado picante', 'Scharfer gebratener Oktopus', 'fish_seafood', 'dinner', 20, 7, 11, 'stir-fried', 'busan'),
  E(`جمبري مشوي ${T}`, 'Grilled shrimp', 'Crevettes grillees', 'Gambas a la parrilla', 'Gegrillte Garnelen', 'fish_seafood', 'dinner', 21, 3, 9, 'grilled', 'incheon'),
  E(`محار مشوي ${T}`, 'Grilled scallops', 'Coquilles Saint-Jacques grillees', 'Vieiras a la parrilla', 'Gegrillte Jakobsmuscheln', 'fish_seafood', 'dinner', 17, 5, 7, 'grilled', 'mokpo'),
  E(`المحار المطهو ${T}`, 'Braised razor clams', 'Couteaux cuits', 'Navajas guisadas', 'Geschmorte Raspmuscheln', 'fish_seafood', 'dinner', 15, 6, 5, 'simmered', 'namhae'),
  E(`محار مقلي حار ${T}`, 'Spicy stir-fried razor clams', 'Couteaux sautes epices', 'Navajas salteadas picantes', 'Scharf gebratene Raspmuscheln', 'fish_seafood', 'dinner', 15, 7, 7, 'stir-fried', 'namhae'),
  E(`حبار مشوي ${T}`, 'Grilled squid', 'Calmar grille', 'Calamar a la parrilla', 'Gegrillter Kalmarl', 'fish_seafood', 'dinner', 18, 4, 8, 'grilled', 'pan_korean'),
  E(`حبار مقلي حار ${T}`, 'Spicy stir-fried squid', 'Calmar saute epice', 'Calamar salteado picante', 'Scharf gebratener Kalmarl', 'fish_seafood', 'dinner', 18, 6, 10, 'stir-fried', 'busan'),
  E(`انقليس مطهو ${T}`, 'Simmered eel', 'Anguille mijotee', 'Anguila guisada', 'Geschmorter Aal', 'fish_seafood', 'dinner', 22, 3, 16, 'simmered', 'pan_korean'),
  E(`سردين مشوي ${T}`, 'Grilled sardines', 'Sardines grillees', 'Sardinas a la parrilla', 'Gegrillte Sardinen', 'fish_seafood', 'dinner', 20, 3, 10, 'grilled', 'busan'),
  E(`أخطبوط مبخر ${T}`, 'Steamed octopus', 'Poulpe vapeur', 'Pulpo al vapor', 'Gedampfter Oktopus', 'fish_seafood', 'dinner', 20, 3, 7, 'steamed', 'busan'),
  E(`حساء السلطعون الحار ${T}`, 'Spicy crab soup', 'Soupe de crabe epicee', 'Sopa picante de cangrejo', 'Scharfe Krebssuppe', 'fish_seafood', 'dinner', 18, 8, 8, 'simmered', 'mokpo'),
  E(`أنشوجة مشوية ${T}`, 'Grilled anchovies', 'Anchois grilles', 'Anchoas a la parrilla', 'Gegrillte Sardellen', 'fish_seafood', 'snacks', 22, 3, 11, 'grilled', 'busan'),

  // vegetable_mains (18)
  E(`كيمتشي اليقطين الشتوي ${T}`, 'Winter melon kimchi', 'Kimchi de melon d hiver', 'Kimchi de melon de invierno', 'Wintermelonen-Kimchi', 'vegetable_mains', 'side', 2, 5, 1, 'fermented', 'pan_korean'),
  E(`كيمتشي المورقوفليش ${T}`, 'Mustard leaf kimchi', 'Kimchi de feuilles de moutarde', 'Kimchi de hojas de mostaza', 'Senfblatt-Kimchi', 'vegetable_mains', 'side', 2, 5, 1, 'fermented', 'sunchang'),
  E(`كيمتشي الخيار ${T}`, 'Cucumber kimchi', 'Kimchi de concombre', 'Kimchi de pepino', 'Gurken-Kimchi', 'vegetable_mains', 'side', 2, 5, 1, 'fermented', 'jeonju'),
  E(`كيمتشي البصل الأخضر ${T}`, 'Green onion kimchi', 'Kimchi d oignon vert', 'Kimchi de cebolla verde', 'Fruehlingszwiebel-Kimchi', 'vegetable_mains', 'side', 2, 4, 1, 'fermented', 'pan_korean'),
  E(`كيمتشي الفجل بمحلول الملح ${T}`, 'Saltwater radish kimchi', 'Kimchi de radis en saumure', 'Kimchi de rabano en salmuera', 'Salzwasser-Rettich-Kimchi', 'vegetable_mains', 'side', 4, 7, 1, 'fermented', 'pan_korean'),
  E(`كيمتشي اليوسني ${T}`, 'Water spinach kimchi', 'Kimchi d ipomoee aquatique', 'Kimchi de espinaca de agua', 'Wasserspinat-Kimchi', 'vegetable_mains', 'side', 3, 5, 1, 'fermented', 'sunchang'),
  E(`كيمتشي براعم الفول ${T}`, 'Bean sprout kimchi', 'Kimchi de germes de haricot', 'Kimchi de brotes de judia', 'Bohnensprossen-Kimchi', 'vegetable_mains', 'side', 3, 5, 1, 'fermented', 'jeonju'),
  E(`سلطة الأعشاب البحرية ${T}`, 'Seaweed salad', 'Salade d algues', 'Ensalada de algas', 'Meersalatat-Salat', 'vegetable_mains', 'side', 3, 8, 3, 'fermented', 'pan_korean'),
  E(`سبانخ متبل ${T}`, 'Seasoned spinach', 'Epinards assaisonnes', 'Espinacas sazonadas', 'Gewuerzter Spinat', 'vegetable_mains', 'side', 4, 5, 3, 'stir-fried', 'pan_korean'),
  E(`فطر الملك المشوي ${T}`, 'Grilled king oyster mushroom', 'Pleurote grille', 'Setas de ostra a la parrilla', 'Gegrillte Austernpilze', 'vegetable_mains', 'side', 3, 8, 4, 'grilled', 'pan_korean'),
  E(`كوسا مقلي ${T}`, 'Stir-fried zucchini', 'Courgette sautee', 'Calabacín salteado', 'Gebratene Zucchini', 'vegetable_mains', 'side', 2, 8, 5, 'stir-fried', 'pan_korean'),
  E(`باذنجان مطهو ${T}`, 'Braised eggplant', 'Aubergine braisee', 'Berenjena guisada', 'Geschmorte Aubergine', 'vegetable_mains', 'side', 2, 12, 5, 'simmered', 'pan_korean'),
  E(`أوراق البطاطا الحلوة المقلي ${T}`, 'Stir-fried sweet potato leaves', 'Feuilles de patate douce sautees', 'Hojas de boniato salteadas', 'Suesskartoffelblaetter', 'vegetable_mains', 'side', 4, 9, 4, 'stir-fried', 'pan_korean'),
  E(`الفصليص البري المقلي بالثوم ${T}`, 'Stir-fried bracken with garlic', 'Fougere sautee a l ail', 'Helecho salteado con ajo', 'Gebratener Farn mit Knoblauch', 'vegetable_mains', 'side', 4, 8, 3, 'stir-fried', 'jeonju'),
  E(`أوراق السوسية المشوية ${T}`, 'Grilled perilla leaves', 'Feuilles de perilla grillees', 'Hojas de perilla a la parrilla', 'Gegrillte Perillablaetter', 'vegetable_mains', 'side', 5, 8, 4, 'grilled', 'pan_korean'),
  E(`جذر اللوتس المبخر ${T}`, 'Steamed lotus root', 'Racine de lotus vapeur', 'Raiz de loto al vapor', 'Gedampfte Lotuswurzel', 'vegetable_mains', 'side', 3, 18, 1, 'steamed', 'pan_korean'),
  E(`التوفو المقلي ${T}`, 'Stir-fried tofu', 'Tofu saute', 'Tofu salteado', 'Gebratener Tofu', 'vegetable_mains', 'side', 11, 6, 9, 'stir-fried', 'pan_korean'),
  E(`الخضار المسلوقة بالسمسم ${T}`, 'Boiled greens with sesame', 'Legumes cuits au sesame', 'Verduras cocidas con sesamo', 'Gekochtes Gemuese mit Sesam', 'vegetable_mains', 'side', 3, 7, 3, 'steamed', 'pan_korean'),
];
