import { B } from '../colombia-base-data/rows.mjs';

export default [
  B('co-phase-a-138', 'أريبا يانسون بجبن كوستينيو وبيوريه الفاصولياء', 'Anise Arepa with Queso Costeno and Bean Puree', 'Arepa à l’anis au queso costeno et purée de haricots', 'Arepa de anís con queso costeño y puré de frijoles', 'Anis-Arepa mit Queso Costeno und Bohnenpüree', 'breakfast_items', 'breakfast', 13, 22, 8, 'griddling', 'santander'),
  B('co-phase-a-139', 'سمك مطهو بهوغاو والليمون', 'Fish Braised with Hogao and Lime', 'Poisson braisé au hogao et citron vert', 'Pescado sudado con hogao y lima', 'Fisch mit Hogao und Limette geschmort', 'fish_seafood', 'dinner', 20, 7, 7, 'braising', 'caribe'),
  B('co-phase-a-140', 'باستيل يوكا باللحم والسبانخ والزيتون', 'Cassava Pastel with Beef, Spinach and Olives', 'Pastel de manioc au bœuf, épinards et olives', 'Pastel de yuca con res, espinaca y aceitunas', 'Maniok-Pastel mit Rindfleisch, Spinat und Oliven', 'meat_mains', 'dinner', 17, 20, 8, 'baking', 'llanos'),
  B('co-phase-a-141', 'كاسويلا أرويا بالبازلاء ولحم البقر', 'Arveja Bean Cazuela with Beef', 'Cazuela de pois arveja au bœuf', 'Cazuela de arveja con res', 'Arveja-Bohnen-Cazuela mit Rindfleisch', 'soups_stews', 'lunch', 17, 15, 7, 'simmering', 'cundinamarca'),
  B('co-phase-a-142', 'تروتا مدخنة بسلطة الأفوكادو والغواسكاس', 'Smoked Trout with Avocado and Guascas Salad', 'Truite fumée avec salade d’avocat et guascas', 'Trucha ahumada con ensalada de aguacate y guascas', 'Geräucherte Forelle mit Avocado-Guascas-Salat', 'fish_seafood', 'lunch', 21, 5, 9, 'smoking', 'narino'),
  B('co-phase-a-143', 'دجاج هوغاو بالجوافة والفلفل الحلو', 'Chicken Hogao with Guava and Sweet Pepper', 'Poulet au hogao, goyave et poivron doux', 'Pollo en hogao con guayaba y pimiento dulce', 'Hähnchen-Hogao mit Guave und Paprika', 'poultry_mains', 'dinner', 21, 9, 7, 'braising', 'valle'),
  B('co-phase-a-144', 'آريبا تشونتا بالبيض والبصل الأخضر', 'Chonta Arepa with Egg and Scallion', 'Arepa de chonta à l’œuf et oignon vert', 'Arepa de chonta con huevo y cebolla larga', 'Chonta-Arepa mit Ei und Frühlingszwiebel', 'breakfast_items', 'breakfast', 13, 20, 8, 'griddling', 'pacifico'),
  B('co-phase-a-145', 'حساء بطاطس أنديزية بالذرة والبيض', 'Andean Potato Soup with Corn and Egg', 'Soupe de pommes de terre andines au maïs et œuf', 'Sopa andina de papa con maíz y huevo', 'Anden-Kartoffelsuppe mit Mais und Ei', 'soups_stews', 'lunch', 12, 14, 5, 'simmering', 'boyaca'),
  B('co-phase-a-146', 'بولفورون موز ناضج بالجبن واليانسون', 'Ripe Plantain Polvoron with Cheese and Anise', 'Polvoron de banane plantain mûre au fromage et anis', 'Polvorón de plátano maduro con queso y anís', 'Polvoron aus reifer Kochbanane mit Käse und Anis', 'street_snacks', 'snack', 10, 24, 8, 'baking', 'caribe'),
  B('co-phase-a-147', 'أقراص غواسكاس بالفاصولياء والريكوتا', 'Guascas Cakes with Beans and Ricotta', 'Galettes de guascas aux haricots et ricotta', 'Torticas de guascas con frijoles y ricota', 'Guascas-Küchlein mit Bohnen und Ricotta', 'vegetable_mains', 'lunch', 12, 16, 7, 'pan_frying', 'bogota'),
  B('co-phase-a-148', 'أريبا تشونتا بجبن كوستينيو والذرة', 'Chonta Arepa with Queso Costeno and Corn', 'Arepa de chonta au queso costeno et maïs', 'Arepa de chonta con queso costeño y maíz', 'Chonta-Arepa mit Queso Costeno und Mais', 'street_snacks', 'snack', 12, 23, 8, 'griddling', 'pacifico'),
  B('co-phase-a-149', 'سلطة كينوا وتونة بالمانجو والأفوكادو', 'Quinoa Tuna Salad with Mango and Avocado', 'Salade de quinoa au thon, mangue et avocat', 'Ensalada de quinoa con atún, mango y aguacate', 'Quinoa-Thunfisch-Salat mit Mango und Avocado', 'salads', 'lunch', 18, 13, 8, 'assembling', 'valle'),
  B('co-phase-a-150', 'تورتا يوكا بالذرة والجبن الطازج', 'Cassava Cake with Corn and Fresh Cheese', 'Gâteau de manioc au maïs et fromage frais', 'Torta de yuca con maíz y queso fresco', 'Maniokkuchen mit Mais und Frischkäse', 'vegetable_mains', 'snack', 11, 25, 7, 'baking', 'narino'),
];
