import { B } from '../colombia-base-data/rows.mjs';

export default [
  B('co-phase-a-064', 'شوربة غاندول بلحم البقر والقرع', 'Guandu Bean Soup with Beef and Squash', 'Soupe de pois guandu au bœuf et courge', 'Sopa de guandú con res y zapallo', 'Guandu-Bohnensuppe mit Rind und Kürbis', 'soups_stews', 'lunch', 16, 14, 7, 'simmering', 'caribe'),
  B('co-phase-a-065', 'أريبا تشوكولو بالدجاج وجبن كوستينيو', 'Chocolo Arepa with Chicken and Queso Costeno', 'Arepa de chocolo au poulet et queso costeno', 'Arepa de chocolo con pollo y queso costeño', 'Chocolo-Arepa mit Hähnchen und Queso Costeno', 'poultry_mains', 'breakfast', 17, 21, 8, 'griddling', 'valle'),
  B('co-phase-a-066', 'باتاكون بالدجاج المفتت والأفوكادو', 'Patacon with Shredded Chicken and Avocado', 'Patacon au poulet effiloché et avocat', 'Patacón con pollo desmechado y aguacate', 'Patacon mit gezupftem Hähnchen und Avocado', 'poultry_mains', 'lunch', 18, 17, 8, 'frying', 'caribe'),
  B('co-phase-a-067', 'أرز تشوكو المحشو باللحم والفاصولياء', 'Choco Arroz Clavado with Beef and Beans', 'Arroz clavado du Choco au bœuf et haricots', 'Arroz clavado chocoano con res y frijoles', 'Choco-Arroz-Clavado mit Rindfleisch und Bohnen', 'meat_mains', 'lunch', 17, 21, 7, 'simmering', 'pacifico'),
  B('co-phase-a-068', 'لحم بقري على طريقة لانيرو مع الكاسابي', 'Llanero Beef with Casabe', 'Bœuf llanero au casabe', 'Res llanera con casabe', 'Llanero-Rindfleisch mit Casabe', 'meat_mains', 'dinner', 23, 18, 8, 'grilling', 'llanos'),
  B('co-phase-a-069', 'سلطة كاساڤا وأفوكادو بالدجاج والليمون', 'Cassava and Avocado Chicken Salad with Lime', 'Salade de manioc et avocat au poulet et citron vert', 'Ensalada de yuca y aguacate con pollo y lima', 'Maniok-Avocado-Hähnchensalat mit Limette', 'salads', 'lunch', 17, 13, 7, 'assembling', 'cundinamarca'),
  B('co-phase-a-070', 'لحم بقري مطهو باللولو والفلفل الحلو', 'Beef Braised with Lulo and Sweet Pepper', 'Bœuf braisé au lulo et poivron doux', 'Res estofada con lulo y pimiento dulce', 'Rindfleisch mit Lulo und Paprika geschmort', 'meat_mains', 'dinner', 20, 8, 8, 'braising', 'valle'),
  B('co-phase-a-071', 'أقراص ذرة كاريبية بالبيض وجبن كوستينيو', 'Caribbean Corn Cakes with Egg and Queso Costeno', 'Galettes de maïs caraïbes à l’œuf et queso costeno', 'Torticas caribeñas de maíz con huevo y queso costeño', 'Karibische Maisküchlein mit Ei und Queso Costeno', 'breakfast_items', 'breakfast', 13, 20, 8, 'pan_frying', 'caribe'),
  B('co-phase-a-072', 'تروتا بصلصة غواسكاس والقشدة', 'Trout with Guascas Cream Sauce', 'Truite à la crème de guascas', 'Trucha con salsa cremosa de guascas', 'Forelle mit Guascas-Rahmsoße', 'fish_seafood', 'dinner', 21, 4, 9, 'baking', 'boyaca'),
  B('co-phase-a-073', 'ديك رومي مطهو بأراجّاتشا والذرة', 'Turkey Stewed with Arracacha and Corn', 'Dinde mijotée à l’arracacha et au maïs', 'Pavo guisado con arracacha y maíz', 'Pute mit Arracacha und Mais geschmort', 'poultry_mains', 'dinner', 19, 11, 7, 'stewing', 'boyaca'),
  B('co-phase-a-074', 'سلطة لولو وغوافة بالريكوتا وبذور الشيا', 'Lulo and Guava Salad with Ricotta and Chia', 'Salade de lulo et goyave à la ricotta et chia', 'Ensalada de lulo y guayaba con ricota y chía', 'Lulo-Guaven-Salat mit Ricotta und Chia', 'salads', 'snack', 10, 17, 6, 'assembling', 'valle'),
  B('co-phase-a-075', 'إنڤويلتو الذرة بجبن طازج وبذور القرع', 'Corn Envueltos with Fresh Cheese and Pumpkin Seeds', 'Envueltos de maïs au fromage frais et graines de courge', 'Envueltos de maíz con queso fresco y pepitas', 'Mais-Envueltos mit Frischkäse und Kürbiskernen', 'street_snacks', 'snack', 11, 24, 8, 'steaming', 'narino'),
];
