import { B } from '../colombia-base-data/rows.mjs';

export default [
  B('co-phase-a-238', 'سلطة دافئة من بوريه وبطاطس وأفوكادو', 'Warm Bore, Potato and Avocado Salad', 'Salade tiède de bore, pomme de terre et avocat', 'Ensalada tibia de bore, papa y aguacate', 'Warmer Bore-Kartoffel-Avocado-Salat', 'salads', 'lunch', 10, 18, 6, 'boiling', 'santander'),
  B('co-phase-a-239', 'بطاطس تشورّياداس بالهوغاو والبيض', 'Papas Chorreadas with Hogao and Egg', 'Papas chorreadas au hogao et œuf', 'Papas chorreadas con hogao y huevo', 'Papas Chorreadas mit Hogao und Ei', 'breakfast_items', 'breakfast', 12, 16, 8, 'boiling', 'cundinamarca'),
  B('co-phase-a-240', 'باستيل بطاطس كريولا بلحم البقر والبيض', 'Criolla Potato Pastel with Beef and Egg', 'Pastel criollo de pommes de terre au bœuf et œuf', 'Pastel criollo de papa con res y huevo', 'Criolla-Kartoffelpastete mit Rind und Ei', 'meat_mains', 'dinner', 17, 16, 9, 'baking', 'antioquia'),
  B('co-phase-a-241', 'روبيان مشوي بالهوغاو والأفوكادو', 'Grilled Shrimp with Hogao and Avocado', 'Crevettes grillées au hogao et avocat', 'Camarones a la parrilla con hogao y aguacate', 'Gegrillte Garnelen mit Hogao und Avocado', 'fish_seafood', 'dinner', 19, 6, 7, 'grilling', 'caribe'),
  B('co-phase-a-242', 'مازامورا الموز الناضج بجبن القريش', 'Ripe Plantain Mazamorra with Cottage Cheese', 'Mazamorra de banane plantain mûre au fromage frais', 'Mazamorra de plátano maduro con requesón', 'Mazamorra aus reifer Kochbanane mit Hüttenkäse', 'breakfast_items', 'breakfast', 11, 22, 6, 'simmering', 'caribe'),
  B('co-phase-a-243', 'بوكاتشيكو بصلصة كوروبا والكينوا', 'Bocachico with Curuba Sauce and Quinoa', 'Bocachico à la sauce curuba et quinoa', 'Bocachico en salsa de curuba y quinoa', 'Bocachico mit Curuba-Soße und Quinoa', 'fish_seafood', 'dinner', 20, 10, 7, 'braising', 'valle'),
  B('co-phase-a-244', 'أقراص أرز بالبانِيلا وجبن كوستينيو', 'Rice Cakes with Panela and Queso Costeno', 'Galettes de riz au panela et queso costeno', 'Torticas de arroz con panela y queso costeño', 'Reisküchlein mit Panela und Queso Costeno', 'street_snacks', 'snack', 10, 25, 7, 'pan_frying', 'caribe'),
  B('co-phase-a-245', 'موخارّا محشوة بالهوغاو واليوكا', 'Mojarra Stuffed with Hogao and Cassava', 'Mojarra farcie au hogao et manioc', 'Mojarra rellena de hogao y yuca', 'Mojarra gefüllt mit Hogao und Maniok', 'fish_seafood', 'dinner', 20, 10, 8, 'baking', 'caribe'),
  B('co-phase-a-246', 'كاسويلا عدس بالدجاج والأفوكادو', 'Lentil Cazuela with Chicken and Avocado', 'Cazuela de lentilles au poulet et avocat', 'Cazuela de lentejas con pollo y aguacate', 'Linsen-Cazuela mit Hähnchen und Avocado', 'soups_stews', 'lunch', 16, 15, 6, 'simmering', 'cundinamarca'),
  B('co-phase-a-247', 'سلطة تشونتادورو باللولو والجبن الطازج', 'Chontaduro Salad with Lulo and Fresh Cheese', 'Salade de chontaduro au lulo et fromage frais', 'Ensalada de chontaduro con lulo y queso fresco', 'Chontaduro-Salat mit Lulo und Frischkäse', 'salads', 'lunch', 10, 17, 6, 'assembling', 'pacifico'),
  B('co-phase-a-248', 'كوكادا المانجو والريكوتا ببذور الشيا', 'Mango and Ricotta Cocada with Chia Seeds', 'Cocada à la mangue, ricotta et graines de chia', 'Cocada de mango y ricota con semillas de chía', 'Mango-Ricotta-Cocada mit Chiasamen', 'rice_cakes_sweets', 'snack', 9, 25, 7, 'baking', 'caribe'),
  B('co-phase-a-249', 'أريبا بيبيان بالفاصولياء والبيض', 'Pipian Arepa with Beans and Egg', 'Arepa pipian aux haricots et œuf', 'Arepa de pipián con frijoles y huevo', 'Pipian-Arepa mit Bohnen und Ei', 'breakfast_items', 'breakfast', 13, 21, 8, 'griddling', 'narino'),
  B('co-phase-a-250', 'شوربة بوغوتا بالذرة واليوكا وجبن طازج', 'Bogota Corn and Cassava Soup with Fresh Cheese', 'Soupe de Bogota au maïs, manioc et fromage frais', 'Sopa bogotana de maíz y yuca con queso fresco', 'Bogota-Mais-Maniok-Suppe mit Frischkäse', 'soups_stews', 'lunch', 11, 17, 5, 'simmering', 'bogota'),
];
