import { B } from '../colombia-base-data/rows.mjs';

export default [
  B('co-phase-a-114', 'خبز باندييوكا بالريكوتا وبذور الشيا', 'Pandeyuca with Ricotta and Chia Seeds', 'Pandeyuca à la ricotta et graines de chia', 'Pandeyuca con ricota y semillas de chía', 'Pandeyuca mit Ricotta und Chiasamen', 'street_snacks', 'snack', 12, 25, 8, 'baking', 'valle'),
  B('co-phase-a-115', 'بوكاتشيكو بصلصة حليب جوز الهند وهوغاو', 'Bocachico with Coconut Milk and Hogao Sauce', 'Bocachico au lait de coco et sauce hogao', 'Bocachico con leche de coco y salsa de hogao', 'Bocachico mit Kokosmilch und Hogao-Soße', 'fish_seafood', 'dinner', 20, 8, 8, 'braising', 'caribe'),
  B('co-phase-a-116', 'أريبا بيتو محشوة بلحم البقر والجبن', 'Arepa de Peto Stuffed with Beef and Cheese', 'Arepa de peto farcie au bœuf et fromage', 'Arepa de peto rellena de res y queso', 'Arepa de Peto gefüllt mit Rindfleisch und Käse', 'meat_mains', 'lunch', 18, 22, 9, 'griddling', 'santander'),
  B('co-phase-a-117', 'شوربة أرز بالدجاج والغواسكاس', 'Chicken Rice Soup with Guascas', 'Soupe de riz au poulet et guascas', 'Sopa de arroz con pollo y guascas', 'Hühnerreissuppe mit Guascas', 'soups_stews', 'lunch', 14, 14, 4, 'simmering', 'bogota'),
  B('co-phase-a-118', 'لحم بقري مطحون أنتيوقينو مع الأريبا والهوغاو', 'Antioquian Carne en Polvo with Arepa and Hogao', 'Carne en polvo antioquienne avec arepa et hogao', 'Carne en polvo antioqueña con arepa y hogao', 'Antioquische Carne en Polvo mit Arepa und Hogao', 'meat_mains', 'lunch', 22, 15, 8, 'braising', 'antioquia'),
  B('co-phase-a-119', 'كيك أراجّاتشا بالبانِيلا والجبن', 'Arracacha Cake with Panela and Cheese', 'Gâteau d’arracacha à la panela et fromage', 'Torta de arracacha con panela y queso', 'Arracacha-Kuchen mit Panela und Käse', 'vegetable_mains', 'snack', 10, 23, 7, 'baking', 'boyaca'),
  B('co-phase-a-120', 'لولادا لولو بالثلج والليمون', 'Lulada Lulo Drink with Ice and Lime', 'Lulada de lulo glacée au citron vert', 'Lulada de lulo con hielo y lima', 'Lulada aus Lulo mit Eis und Limette', 'beverages', 'snack', 2, 16, 1, 'blending', 'valle'),
  B('co-phase-a-121', 'كوكادا جوز الهند والبانِيلا واللوز', 'Coconut Cocada with Panela and Almonds', 'Cocada à la noix de coco, panela et amandes', 'Cocada de coco con panela y almendras', 'Kokos-Cocada mit Panela und Mandeln', 'rice_cakes_sweets', 'snack', 6, 30, 10, 'baking', 'caribe'),
  B('co-phase-a-122', 'توستادا كاسابي بالفاصولياء السوداء والبروفولوني', 'Casabe Toast with Black Beans and Provolone', 'Toast de casabe aux haricots noirs et provolone', 'Tostada de casabe con frijoles negros y provolone', 'Casabe-Toast mit schwarzen Bohnen und Provolone', 'street_snacks', 'snack', 13, 23, 8, 'baking', 'llanos'),
  B('co-phase-a-123', 'لسان بقر بصلصة كريولا والكبر', 'Beef Tongue with Criolla Sauce and Capers', 'Langue de bœuf à la sauce criolla et câpres', 'Lengua de res con salsa criolla y alcaparras', 'Rinderzunge mit Criolla-Soße und Kapern', 'meat_mains', 'dinner', 20, 5, 9, 'braising', 'bogota'),
  B('co-phase-a-124', 'شوربة البطاطس بالكزبرة والبصل الأخضر', 'Potato Soup with Cilantro and Scallion', 'Soupe de pommes de terre à la coriandre et oignon vert', 'Sopa de papa con cilantro y cebolla larga', 'Kartoffelsuppe mit Koriander und Frühlingszwiebel', 'soups_stews', 'lunch', 9, 15, 5, 'simmering', 'boyaca'),
  B('co-phase-a-125', 'وعاء غوافا وجبن قريش وشوفان', 'Guava and Cottage Cheese Oat Bowl', 'Bol d’avoine à la goyave et fromage frais', 'Tazón de avena con guayaba y requesón', 'Hafer-Bowl mit Guave und Hüttenkäse', 'breakfast_items', 'breakfast', 13, 22, 6, 'simmering', 'valle'),
];
