import { B } from '../colombia-base-data/rows.mjs';

export default [
  B('co-phase-a-214', 'خبز بوروخو بالحليب والشوفان', 'Borojó Bread with Milk and Oats', 'Pain au borojó, lait et avoine', 'Pan de borojó con leche y avena', 'Borojó-Brot mit Milch und Hafer', 'breakfast_items', 'breakfast', 10, 25, 6, 'baking', 'pacifico'),
  B('co-phase-a-215', 'شرائح لحم بقري مع المانجو الأخضر والأفوكادو', 'Beef Strips with Green Mango and Avocado', 'Émincé de bœuf à la mangue verte et avocat', 'Tiras de res con mango verde y aguacate', 'Rindfleischstreifen mit grüner Mango und Avocado', 'meat_mains', 'lunch', 21, 8, 9, 'sauteing', 'valle'),
  B('co-phase-a-216', 'تروتا محشوة بالسبانخ وجبن بانلا', 'Trout Stuffed with Spinach and Panela', 'Truite farcie aux épinards et panela', 'Trucha rellena de espinaca y panela', 'Forelle gefüllt mit Spinat und Panela', 'fish_seafood', 'dinner', 21, 4, 8, 'baking', 'narino'),
  B('co-phase-a-217', 'شوربة فاصولياء غاندول باليوكا وجبن كوستينيو', 'Guandu Bean Soup with Cassava and Queso Costeno', 'Soupe de pois guandu au manioc et queso costeno', 'Sopa de guandú con yuca y queso costeño', 'Guandu-Bohnensuppe mit Maniok und Queso Costeno', 'soups_stews', 'lunch', 12, 18, 6, 'simmering', 'caribe'),
  B('co-phase-a-218', 'يخنة حمص وذرة بالفلفل الحلو', 'Chickpea and Corn Stew with Sweet Pepper', 'Ragoût de pois chiches et maïs au poivron doux', 'Guiso de garbanzos y maíz con pimiento dulce', 'Kichererbsen-Mais-Eintopf mit Paprika', 'vegetable_mains', 'lunch', 11, 20, 5, 'stewing', 'cundinamarca'),
  B('co-phase-a-219', 'دجاج بالكريما والأفوكادو والليمون', 'Chicken with Cream, Avocado and Lime', 'Poulet à la crème, avocat et citron vert', 'Pollo con crema, aguacate y lima', 'Hähnchen mit Sahne, Avocado und Limette', 'poultry_mains', 'dinner', 21, 5, 10, 'braising', 'bogota'),
  B('co-phase-a-220', 'كروكيت سلطعون بالأراجّاتشا والفلفل', 'Crab Croquettes with Arracacha and Pepper', 'Croquettes de crabe à l’arracacha et poivron', 'Croquetas de jaiba con arracacha y pimiento', 'Krabbenkroketten mit Arracacha und Paprika', 'fish_seafood', 'snack', 16, 13, 6, 'baking', 'caribe'),
  B('co-phase-a-221', 'شوربة كينوا بالدجاج والخضار', 'Chicken Quinoa Soup with Vegetables', 'Soupe de quinoa au poulet et légumes', 'Sopa de quinoa con pollo y verduras', 'Hühner-Quinoa-Suppe mit Gemüse', 'soups_stews', 'lunch', 15, 14, 5, 'simmering', 'boyaca'),
  B('co-phase-a-222', 'تشونتادورو بصلصة جوز الهند والليمون', 'Chontaduro with Coconut and Lime Sauce', 'Chontaduro à la sauce coco et citron vert', 'Chontaduro con salsa de coco y lima', 'Chontaduro mit Kokos-Limetten-Soße', 'vegetable_mains', 'snack', 8, 24, 7, 'simmering', 'pacifico'),
  B('co-phase-a-223', 'لحم بقري بالكوروزو والفاصولياء البيضاء', 'Beef with Corozo and White Beans', 'Bœuf au corozo et haricots blancs', 'Res con corozo y alubias blancas', 'Rindfleisch mit Corozo und weißen Bohnen', 'meat_mains', 'dinner', 19, 13, 8, 'stewing', 'caribe'),
  B('co-phase-a-224', 'بطاطا أراجّاتشا مهروسة بجبن بانلا والهوغاو', 'Arracacha Mash with Panela and Hogao', 'Purée d’arracacha au panela et hogao', 'Puré de arracacha con panela y hogao', 'Arracacha-Püree mit Panela und Hogao', 'vegetable_mains', 'side', 10, 20, 6, 'boiling', 'boyaca'),
  B('co-phase-a-225', 'تورتا مانجو وكوروزو بجبن طازج', 'Mango and Corozo Cake with Fresh Cheese', 'Gâteau à la mangue et corozo au fromage frais', 'Torta de mango y corozo con queso fresco', 'Mango-Corozo-Kuchen mit Frischkäse', 'rice_cakes_sweets', 'snack', 9, 28, 7, 'baking', 'caribe'),
];
