import { B } from '../colombia-base-data/rows.mjs';

export default [
  B('co-phase-a-038', 'سيفيتشي روبيان بالمانجو والليمون', 'Shrimp Ceviche with Mango and Lime', 'Ceviche de crevettes à la mangue et citron vert', 'Ceviche de camarón con mango y lima', 'Garnelen-Ceviche mit Mango und Limette', 'fish_seafood', 'lunch', 17, 8, 3, 'marinating', 'caribe'),
  B('co-phase-a-039', 'دجاج مشوي بصلصة الجوافة والأعشاب', 'Grilled Chicken with Guava Herb Glaze', 'Poulet grillé glacé à la goyave et aux herbes', 'Pollo a la parrilla glaseado con guayaba y hierbas', 'Gegrilltes Hähnchen mit Guavenglasur und Kräutern', 'poultry_mains', 'dinner', 22, 7, 7, 'grilling', 'valle'),
  B('co-phase-a-040', 'سودادو سمك كاتفيش باليوكا والطماطم', 'Catfish Sudado with Cassava and Tomato', 'Sudado de poisson-chat au manioc et tomate', 'Sudado de bagre con yuca y tomate', 'Wels-Sudado mit Maniok und Tomate', 'fish_seafood', 'lunch', 18, 12, 5, 'braising', 'llanos'),
  B('co-phase-a-041', 'كالينتادو أنتيوقينو بالبيض ولحم البقر', 'Antioquian Calentado with Egg and Beef', 'Calentado antioquien à l’œuf et au bœuf', 'Calentado antioqueño con huevo y res', 'Antioquischer Calentado mit Ei und Rindfleisch', 'breakfast_items', 'breakfast', 16, 18, 9, 'sauteing', 'antioquia'),
  B('co-phase-a-042', 'أريبا بيتو بالفاصولياء السوداء وجبن كوستينيو', 'Arepa de Peto with Black Beans and Queso Costeno', 'Arepa de peto aux haricots noirs et queso costeno', 'Arepa de peto con frijoles negros y queso costeño', 'Arepa de Peto mit schwarzen Bohnen und Queso Costeno', 'street_snacks', 'snack', 12, 23, 7, 'griddling', 'santander'),
  B('co-phase-a-043', 'بونويلوس كولومبية بجبن طازج', 'Colombian Buñuelos with Fresh Cheese', 'Buñuelos colombiens au fromage frais', 'Buñuelos colombianos con queso fresco', 'Kolumbianische Buñuelos mit Frischkäse', 'street_snacks', 'snack', 11, 24, 10, 'frying', 'antioquia'),
  B('co-phase-a-044', 'سمك أروز دي كوكونت بالكركم والخضار', 'Coconut Fish Rice with Turmeric and Vegetables', 'Riz coco au poisson, curcuma et légumes', 'Arroz con coco y pescado, cúrcuma y verduras', 'Kokosfischreis mit Kurkuma und Gemüse', 'fish_seafood', 'dinner', 17, 21, 7, 'simmering', 'caribe'),
  B('co-phase-a-045', 'كريمة القرع بالدجاج وجبن كوستينيو', 'Squash Cream Soup with Chicken and Queso Costeno', 'Crème de courge au poulet et queso costeno', 'Crema de zapallo con pollo y queso costeño', 'Kürbiscremesuppe mit Hähnchen und Queso Costeno', 'soups_stews', 'lunch', 15, 10, 6, 'simmering', 'boyaca'),
  B('co-phase-a-046', 'أريبا تشوكولو محشوة بجبن بانلا', 'Chocolo Arepa Stuffed with Panela Cheese', 'Arepa de chocolo farcie au fromage panela', 'Arepa de chocolo rellena de queso panela', 'Chocolo-Arepa gefüllt mit Panela-Käse', 'breakfast_items', 'breakfast', 12, 24, 7, 'griddling', 'valle'),
  B('co-phase-a-047', 'موز ناضج مخبوز بالجبن والقرفة', 'Baked Ripe Plantain with Cheese and Cinnamon', 'Banane plantain mûre au four, fromage et cannelle', 'Plátano maduro al horno con queso y canela', 'Gebackene reife Kochbanane mit Käse und Zimt', 'vegetable_mains', 'snack', 9, 31, 7, 'baking', 'caribe'),
  B('co-phase-a-048', 'سلطة فواكه استوائية بالزبادي والشيا', 'Tropical Fruit Salad with Yogurt and Chia', 'Salade de fruits tropicaux au yaourt et chia', 'Ensalada de frutas tropicales con yogur y chía', 'Tropischer Obstsalat mit Joghurt und Chia', 'salads', 'breakfast', 9, 18, 5, 'assembling', 'valle'),
  B('co-phase-a-049', 'دجاج مشوي بصلصة الماراكويّا', 'Grilled Chicken with Passion Fruit Sauce', 'Poulet grillé à la sauce au fruit de la passion', 'Pollo a la parrilla con salsa de maracuyá', 'Gegrilltes Hähnchen mit Maracuja-Soße', 'poultry_mains', 'dinner', 22, 8, 7, 'grilling', 'valle'),
  B('co-phase-a-050', 'تاكو يوكا بالدجاج والأفوكادو', 'Cassava Tacos with Chicken and Avocado', 'Tacos de manioc au poulet et avocat', 'Tacos de yuca con pollo y aguacate', 'Maniok-Tacos mit Hähnchen und Avocado', 'street_snacks', 'lunch', 17, 22, 8, 'griddling', 'narino'),
];
