import { B } from '../colombia-base-data/rows.mjs';

export default [
  B('co-phase-a-014', 'كاسويلا ساحلية بالروبيان واليوكا وحليب جوز الهند', 'Coastal Shrimp Cazuela with Cassava and Coconut Milk', 'Cazuela côtière de crevettes au manioc et lait de coco', 'Cazuela costeña de camarón con yuca y leche de coco', 'Küstliche Garnelen-Cazuela mit Maniok und Kokosmilch', 'fish_seafood', 'dinner', 17, 11, 7, 'simmering', 'caribe'),
  B('co-phase-a-015', 'أريبا الذرة الحلوة بالدجاج والجبن', 'Sweet Corn Arepa with Chicken and Cheese', 'Arepa de maïs doux au poulet et fromage', 'Arepa de choclo con pollo y queso', 'Süßmais-Arepa mit Hähnchen und Käse', 'poultry_mains', 'breakfast', 17, 20, 8, 'griddling', 'antioquia'),
  B('co-phase-a-016', 'أرز أتيولادو بالدجاج والخضار', 'Arroz Atollado with Chicken and Vegetables', 'Arroz atollado au poulet et légumes', 'Arroz atollado con pollo y verduras', 'Arroz Atollado mit Hähnchen und Gemüse', 'poultry_mains', 'dinner', 16, 20, 6, 'simmering', 'valle'),
  B('co-phase-a-017', 'سوبراباريغا بصلصة كريولا', 'Sobrebarriga in Criolla Sauce', 'Sobrebarriga à la sauce criolla', 'Sobrebarriga en salsa criolla', 'Sobrebarriga in Criolla-Soße', 'meat_mains', 'dinner', 21, 6, 9, 'braising', 'bogota'),
  B('co-phase-a-018', 'تشانغوا بالحليب والبيض والبصل الأخضر', 'Changua with Milk, Egg and Scallion', 'Changua au lait, œuf et oignon vert', 'Changua con leche, huevo y cebolla larga', 'Changua mit Milch, Ei und Frühlingszwiebel', 'breakfast_items', 'breakfast', 11, 8, 8, 'simmering', 'bogota'),
  B('co-phase-a-019', 'موخارّا مشوية بالليمون والباتاكون', 'Grilled Mojarra with Lime and Patacon', 'Mojarra grillée au citron vert et patacon', 'Mojarra a la parrilla con lima y patacón', 'Gegrillte Mojarra mit Limette und Patacon', 'fish_seafood', 'dinner', 20, 14, 8, 'grilling', 'caribe'),
  B('co-phase-a-020', 'باندبونو بجبن قريش ونشا اليوكا', 'Pandebono with Cottage Cheese and Cassava Starch', 'Pandebono au fromage frais et amidon de manioc', 'Pandebono con requesón y almidón de yuca', 'Pandebono mit Hüttenkäse und Maniokstärke', 'street_snacks', 'snack', 12, 22, 8, 'baking', 'valle'),
  B('co-phase-a-021', 'بيستيك آ كابايو بصلصة هوغاو', 'Bistec a Caballo with Hogao', 'Bistec a caballo au hogao', 'Bistec a caballo con hogao', 'Bistec a Caballo mit Hogao', 'meat_mains', 'dinner', 22, 5, 12, 'pan_frying', 'antioquia'),
  B('co-phase-a-022', 'كاريمانولا اليوكا محشوة بلحم البقر', 'Cassava Carimanola Stuffed with Beef', 'Carimanola de manioc farcie au bœuf', 'Carimañola de yuca rellena de res', 'Maniok-Carimañola gefüllt mit Rindfleisch', 'street_snacks', 'snack', 16, 23, 7, 'frying', 'caribe'),
  B('co-phase-a-023', 'سلطة دجاج بالأفوكادو والمانجو', 'Chicken Salad with Avocado and Mango', 'Salade de poulet à l’avocat et mangue', 'Ensalada de pollo con aguacate y mango', 'Hähnchensalat mit Avocado und Mango', 'salads', 'lunch', 18, 10, 8, 'grilling', 'valle'),
  B('co-phase-a-024', 'سمك بأرز جوز الهند والليمون', 'Fish with Coconut Rice and Lime', 'Poisson au riz coco et citron vert', 'Pescado con arroz con coco y lima', 'Fisch mit Kokosreis und Limette', 'fish_seafood', 'dinner', 19, 19, 8, 'baking', 'caribe'),
  B('co-phase-a-025', 'عصير غوانابانا بالزبادي والشيا', 'Soursop Yogurt Smoothie with Chia', 'Smoothie de corossol au yaourt et chia', 'Batido de guanábana con yogur y chía', 'Guanabana-Joghurt-Smoothie mit Chia', 'beverages', 'breakfast', 9, 18, 4, 'blending', 'valle'),
];
