import { B } from '../colombia-base-data/rows.mjs';

export default [
  B('co-phase-a-088', 'سيفيتشي تروتا بالأفوكادو والليمون', 'Trout Ceviche with Avocado and Lime', 'Ceviche de truite à l’avocat et citron vert', 'Ceviche de trucha con aguacate y lima', 'Forellen-Ceviche mit Avocado und Limette', 'fish_seafood', 'lunch', 19, 6, 5, 'marinating', 'narino'),
  B('co-phase-a-089', 'صينية بطاطس أنديزية بالبيض والبصل الأخضر', 'Andean Potato Bake with Egg and Scallion', 'Gratin de pommes de terre andines à l’œuf et oignon vert', 'Pastel andino de papa con huevo y cebolla larga', 'Anden-Kartoffelauflauf mit Ei und Frühlingszwiebel', 'breakfast_items', 'breakfast', 13, 17, 8, 'baking', 'boyaca'),
  B('co-phase-a-090', 'كاريمانولا سلطعون باليوكا وجبن كوستينيو', 'Crab Carimanola with Cassava and Queso Costeno', 'Carimanola de crabe au manioc et queso costeno', 'Carimañola de jaiba con yuca y queso costeño', 'Krabben-Carimanola mit Maniok und Queso Costeno', 'fish_seafood', 'snack', 16, 22, 7, 'frying', 'caribe'),
  B('co-phase-a-091', 'أريبا سانتانديريّة باللحم والأفوكادو', 'Santander Arepa with Beef and Avocado', 'Arepa de Santander au bœuf et avocat', 'Arepa santandereana con res y aguacate', 'Santander-Arepa mit Rindfleisch und Avocado', 'meat_mains', 'breakfast', 17, 21, 9, 'griddling', 'santander'),
  B('co-phase-a-092', 'تروتا مشوية بصلصة الماراكويّا والكزبرة', 'Grilled Trout with Passion Fruit and Cilantro Sauce', 'Truite grillée à la sauce maracuja et coriandre', 'Trucha a la parrilla con salsa de maracuyá y cilantro', 'Gegrillte Forelle mit Maracuja-Koriander-Soße', 'fish_seafood', 'dinner', 21, 6, 7, 'grilling', 'narino'),
  B('co-phase-a-093', 'كروكيت بطاطس باللحم البقري والفاصولياء', 'Potato Croquettes with Beef and Beans', 'Croquettes de pommes de terre au bœuf et haricots', 'Croquetas de papa con res y frijoles', 'Kartoffelkroketten mit Rindfleisch und Bohnen', 'meat_mains', 'snack', 14, 22, 8, 'baking', 'antioquia'),
  B('co-phase-a-094', 'أرز بالروبيان وهوغاو وجوز الهند', 'Shrimp Rice with Hogao and Coconut', 'Riz aux crevettes, hogao et noix de coco', 'Arroz con camarones, hogao y coco', 'Garnelenreis mit Hogao und Kokos', 'fish_seafood', 'dinner', 17, 22, 7, 'simmering', 'caribe'),
  B('co-phase-a-095', 'فطائر شوكولو بالريكوتا والذرة', 'Chocolo Fritters with Ricotta and Corn', 'Beignets de chocolo à la ricotta et maïs', 'Torticas de chocolo con ricota y maíz', 'Chocolo-Küchlein mit Ricotta und Mais', 'street_snacks', 'snack', 11, 23, 8, 'pan_frying', 'valle'),
  B('co-phase-a-096', 'أريبا فاصولياء العين السوداء بجبن كوستينيو والأفوكادو', 'Black-Eyed Pea Arepa with Queso Costeno and Avocado', 'Arepa de niébé au queso costeno et avocat', 'Arepa de frijol cabecita negra con queso costeño y aguacate', 'Augenbohnen-Arepa mit Queso Costeno und Avocado', 'street_snacks', 'lunch', 13, 21, 8, 'griddling', 'antioquia'),
  B('co-phase-a-097', 'سمك إنكوكادو باليوكا والموز الأخضر', 'Fish Encocado with Cassava and Green Plantain', 'Poisson encocado au manioc et banane plantain verte', 'Pescado encocado con yuca y plátano verde', 'Encocado-Fisch mit Maniok und grüner Kochbanane', 'fish_seafood', 'dinner', 19, 14, 8, 'simmering', 'pacifico'),
  B('co-phase-a-098', 'سانكوتشو دي ريس بالذرة والبطاطس', 'Beef Sancocho with Corn and Potatoes', 'Sancocho de bœuf au maïs et pommes de terre', 'Sancocho de res con maíz y papa', 'Rindfleisch-Sancocho mit Mais und Kartoffeln', 'soups_stews', 'lunch', 16, 14, 6, 'simmering', 'llanos'),
  B('co-phase-a-099', 'خبز غوافا بجبن طازج وبذور الشيا', 'Guava Bread with Fresh Cheese and Chia', 'Pain à la goyave, fromage frais et chia', 'Pan de guayaba con queso fresco y chía', 'Guavenbrot mit Frischkäse und Chia', 'rice_cakes_sweets', 'snack', 9, 29, 6, 'baking', 'valle'),
  B('co-phase-a-100', 'عصير لولو باللبن والليمون', 'Lulo Smoothie with Yogurt and Lime', 'Smoothie de lulo au yaourt et citron vert', 'Batido de lulo con yogur y lima', 'Lulo-Smoothie mit Joghurt und Limette', 'beverages', 'breakfast', 9, 15, 4, 'blending', 'valle'),
];
