import { B } from '../colombia-base-data/rows.mjs';

export default [
  B('co-phase-a-188', 'سمك بجوز الهند والواسكاس والبازلاء', 'Fish with Coconut, Guascas and Peas', 'Poisson à la noix de coco, guascas et petits pois', 'Pescado con coco, guascas y arvejas', 'Fisch mit Kokos, Guascas und Erbsen', 'fish_seafood', 'dinner', 19, 10, 7, 'braising', 'caribe'),
  B('co-phase-a-189', 'مازامورا موز أخضر بجبن كوستينيو والقرفة', 'Green Plantain Mazamorra with Queso Costeno and Cinnamon', 'Mazamorra de banane plantain verte au queso costeno et cannelle', 'Mazamorra de plátano verde con queso costeño y canela', 'Grüne Kochbananen-Mazamorra mit Queso Costeno und Zimt', 'breakfast_items', 'breakfast', 10, 22, 6, 'simmering', 'caribe'),
  B('co-phase-a-190', 'بيستيك كريولا بالفاصولياء والخضار', 'Criolla Bistec with Beans and Vegetables', 'Bistec criollo aux haricots et légumes', 'Bistec criollo con frijoles y verduras', 'Criolla-Bistec mit Bohnen und Gemüse', 'meat_mains', 'dinner', 21, 12, 9, 'braising', 'antioquia'),
  B('co-phase-a-191', 'كاسويلا فاصولياء العين السوداء بالروبيان', 'Black-Eyed Pea Cazuela with Shrimp', 'Cazuela de niébés aux crevettes', 'Cazuela de frijol cabecita negra con camarones', 'Augenbohnen-Cazuela mit Garnelen', 'fish_seafood', 'dinner', 18, 17, 7, 'simmering', 'caribe'),
  B('co-phase-a-192', 'سمك بصلصة الطماطم وجوز الهند', 'Fish with Tomato and Coconut Sauce', 'Poisson à la sauce tomate et noix de coco', 'Pescado en salsa de tomate y coco', 'Fisch mit Tomaten-Kokos-Soße', 'fish_seafood', 'dinner', 19, 8, 7, 'braising', 'pacifico'),
  B('co-phase-a-193', 'دجاج بجوز الهند والجوافة', 'Chicken with Coconut and Guava', 'Poulet à la noix de coco et goyave', 'Pollo con coco y guayaba', 'Hähnchen mit Kokos und Guave', 'poultry_mains', 'dinner', 21, 9, 8, 'braising', 'pacifico'),
  B('co-phase-a-194', 'أريبا تشونتادورو بجبن كوستينيو', 'Chontaduro Arepa with Queso Costeno', 'Arepa de chontaduro au queso costeno', 'Arepa de chontaduro con queso costeño', 'Chontaduro-Arepa mit Queso Costeno', 'street_snacks', 'snack', 12, 23, 8, 'griddling', 'pacifico'),
  B('co-phase-a-195', 'كوكادا تشونتادورو بجوز الهند والبانِيلا', 'Chontaduro Cocada with Coconut and Panela', 'Cocada de chontaduro à la noix de coco et panela', 'Cocada de chontaduro con coco y panela', 'Chontaduro-Cocada mit Kokos und Panela', 'rice_cakes_sweets', 'snack', 6, 30, 9, 'baking', 'pacifico'),
  B('co-phase-a-196', 'دجاج مطهو بفاصولياء العين السوداء والموز', 'Chicken Stewed with Black-Eyed Peas and Plantain', 'Poulet mijoté aux niébés et banane plantain', 'Pollo guisado con frijol cabecita negra y plátano', 'Hähnchen mit Augenbohnen und Kochbanane geschmort', 'poultry_mains', 'dinner', 17, 17, 6, 'stewing', 'caribe'),
  B('co-phase-a-197', 'تورتا يوكا بالموز الناضج والجبن', 'Cassava Cake with Ripe Plantain and Cheese', 'Gâteau de manioc à la banane plantain mûre et fromage', 'Torta de yuca con plátano maduro y queso', 'Maniokkuchen mit reifer Kochbanane und Käse', 'vegetable_mains', 'snack', 10, 28, 8, 'baking', 'caribe'),
  B('co-phase-a-198', 'عصير بوروهّو بالحليب والشوفان', 'Borojó Smoothie with Milk and Oats', 'Smoothie de borojó au lait et avoine', 'Batido de borojó con leche y avena', 'Borojó-Smoothie mit Milch und Hafer', 'beverages', 'breakfast', 10, 20, 5, 'blending', 'pacifico'),
  B('co-phase-a-199', 'طماطم محشوة بالكينوا والموز الأخضر', 'Tomatoes Stuffed with Quinoa and Green Plantain', 'Tomates farcies au quinoa et banane plantain verte', 'Tomates rellenos de quinoa y plátano verde', 'Tomaten gefüllt mit Quinoa und grüner Kochbanane', 'vegetable_mains', 'lunch', 10, 18, 5, 'baking', 'valle'),
  B('co-phase-a-200', 'شوربة باغري بجوز الهند والليمون', 'Bagre Soup with Coconut and Lime', 'Soupe de bagre à la noix de coco et citron vert', 'Sopa de bagre con coco y lima', 'Bagre-Suppe mit Kokos und Limette', 'fish_seafood', 'lunch', 18, 8, 6, 'simmering', 'pacifico'),
];
