import { B } from '../colombia-base-data/rows.mjs';

export default [
  B('co-phase-a-164', 'تامال حمص بالدجاج والبطاطس', 'Chickpea Tamal with Chicken and Potato', 'Tamal aux pois chiches, poulet et pomme de terre', 'Tamal de garbanzo con pollo y papa', 'Kichererbsen-Tamal mit Hähnchen und Kartoffel', 'street_snacks', 'lunch', 15, 23, 7, 'steaming', 'cundinamarca'),
  B('co-phase-a-165', 'وعاء تروتا بالمانجو والكينوا', 'Trout Bowl with Mango and Quinoa', 'Bol de truite à la mangue et quinoa', 'Tazón de trucha con mango y quinoa', 'Forellenschale mit Mango und Quinoa', 'fish_seafood', 'lunch', 21, 14, 7, 'grilling', 'narino'),
  B('co-phase-a-166', 'يوكا مشوية بصلصة الفلفل والفاصولياء', 'Grilled Cassava with Chile and Beans', 'Manioc grillé au piment et haricots', 'Yuca asada con chile y frijoles', 'Gegrillter Maniok mit Chili und Bohnen', 'vegetable_mains', 'lunch', 10, 25, 6, 'grilling', 'llanos'),
  B('co-phase-a-167', 'باستيل موز ناضج بلحم البقر والجبن', 'Ripe Plantain Pastel with Beef and Cheese', 'Pastel de banane plantain mûre au bœuf et fromage', 'Pastel de plátano maduro con res y queso', 'Pastel aus reifer Kochbanane mit Rind und Käse', 'meat_mains', 'dinner', 17, 20, 9, 'baking', 'caribe'),
  B('co-phase-a-168', 'أرز بقلب النخيل والدجاج والخضار', 'Palmito Rice with Chicken and Vegetables', 'Riz au cœur de palmier, poulet et légumes', 'Arroz con palmito, pollo y verduras', 'Palmito-Reis mit Hähnchen und Gemüse', 'poultry_mains', 'dinner', 16, 21, 6, 'simmering', 'pacifico'),
  B('co-phase-a-169', 'قرع محشو بسمك الباغري وهوغاو', 'Squash Stuffed with Bagre and Hogao', 'Courge farcie au bagre et hogao', 'Zapallo relleno de bagre y hogao', 'Kürbis gefüllt mit Bagre und Hogao', 'fish_seafood', 'dinner', 18, 10, 7, 'baking', 'llanos'),
  B('co-phase-a-170', 'بطاطس تشورّياداس بالبيض والهوغاو', 'Papas Chorreadas with Egg and Hogao', 'Papas chorreadas à l’œuf et hogao', 'Papas chorreadas con huevo y hogao', 'Papas Chorreadas mit Ei und Hogao', 'breakfast_items', 'breakfast', 12, 16, 8, 'boiling', 'cundinamarca'),
  B('co-phase-a-171', 'دجاج محشو بالتشونتادورو وجبن بانلا', 'Chicken Stuffed with Chontaduro and Panela', 'Poulet farci au chontaduro et panela', 'Pollo relleno de chontaduro y panela', 'Hähnchen gefüllt mit Chontaduro und Panela', 'poultry_mains', 'dinner', 21, 8, 8, 'roasting', 'pacifico'),
  B('co-phase-a-172', 'أريبا كاسابي بجبن بانلا والفاصولياء', 'Casabe Arepa with Panela and Beans', 'Arepa de casabe au panela et haricots', 'Arepa de casabe con panela y frijoles', 'Casabe-Arepa mit Panela und Bohnen', 'street_snacks', 'snack', 11, 23, 6, 'griddling', 'llanos'),
  B('co-phase-a-173', 'سودادو سمك اللولو والليمون', 'Fish Sudado with Lulo and Lime', 'Sudado de poisson au lulo et citron vert', 'Sudado de pescado con lulo y lima', 'Fisch-Sudado mit Lulo und Limette', 'fish_seafood', 'dinner', 20, 8, 6, 'braising', 'valle'),
  B('co-phase-a-174', 'تورتا موز أخضر بجبن كوستينيو والبيض', 'Green Plantain Cake with Queso Costeno and Egg', 'Gâteau de banane plantain verte au queso costeno et œuf', 'Torta de plátano verde con queso costeño y huevo', 'Grüne Kochbananen-Torte mit Queso Costeno und Ei', 'vegetable_mains', 'lunch', 12, 24, 8, 'baking', 'caribe'),
  B('co-phase-a-175', 'مازامورا موز أخضر بالجبن والقرفة', 'Green Plantain Mazamorra with Cheese and Cinnamon', 'Mazamorra de banane plantain verte au fromage et cannelle', 'Mazamorra de plátano verde con queso y canela', 'Grüne Kochbananen-Mazamorra mit Käse und Zimt', 'breakfast_items', 'breakfast', 10, 21, 6, 'simmering', 'caribe'),
];
