export const BASE_DIASPORA = ['turkish', 'middle_eastern', 'mediterranean', 'halal_lifestyle'];
export const REGION_DIASPORA = { istanbul: 'istanbulite', gaziantep: 'southeastern', trabzon: 'black_sea' };

// Each anchor owns one stable Arabic token; no Turkish row belongs in asian_shared.
export const REGION_DEMONYM = {
  pan_turkish: 'تركي',
  istanbul: 'إسطنبولي',
  ankara: 'أنقري',
  izmir: 'إزميري',
  bursa: 'بورصي',
  antalya: 'أنطالي',
  gaziantep: 'عنتابي',
  konya: 'قوني',
  adana: 'أدني',
  trabzon: 'طرابزوني',
  diyarbakir: 'دياربكري',
  kayseri: 'قيصري',
  mardin: 'مارديني',
  sanliurfa: 'أورفاوي',
  van: 'وانلي',
  eskisehir: 'أسكي_شهيرلي',
};

const REGIONS = [
  ['pan_turkish', 'مطابخ تركيا', 'Turkish', 'Cuisine turque : ', 'Cocina turca: ', 'Türkische Küche: '],
  ['istanbul', 'مطابخ إسطنبول', 'Istanbul', 'À l’istanbulite : ', 'Al estilo de Estambul: ', 'Istanbuler Art: '],
  ['ankara', 'مطابخ أنقرة', 'Ankara', 'À l’ankariote : ', 'Al estilo de Ankara: ', 'Ankara-Art: '],
  ['izmir', 'مطابخ إزمير', 'Izmir', 'À l’izmiriote : ', 'Al estilo de Esmirna: ', 'Izmir-Art: '],
  ['bursa', 'مطابخ بورصة', 'Bursa', 'À la bursaliote : ', 'Al estilo de Bursa: ', 'Bursa-Art: '],
  ['antalya', 'مطابخ أنطاليا', 'Antalya', 'À l’antalyote : ', 'Al estilo de Antalya: ', 'Antalya-Art: '],
  ['gaziantep', 'مطابخ غازي عنتاب', 'Gaziantep', 'À la gaziantepo : ', 'Al estilo de Gaziantep: ', 'Gaziantep-Art: '],
  ['konya', 'مطابخ قونية', 'Konya', 'À la konyote : ', 'Al estilo de Konya: ', 'Konya-Art: '],
  ['adana', 'مطابخ أضنة', 'Adana', 'À l’adanaise : ', 'Al estilo de Adana: ', 'Adana-Art: '],
  ['trabzon', 'مطابخ طرابزون', 'Trabzon', 'À la trabzonide : ', 'Al estilo de Trebisonda: ', 'Trabzon-Art: '],
  ['diyarbakir', 'مطابخ ديار بكر', 'Diyarbakir', 'À la diyarbakiriote : ', 'Al estilo de Diyarbakır: ', 'Diyarbakır-Art: '],
  ['kayseri', 'مطابخ قيصرية', 'Kayseri', 'À la kayseriote : ', 'Al estilo de Kayseri: ', 'Kayseri-Art: '],
  ['mardin', 'مطابخ ماردين', 'Mardin', 'À la mardiniote : ', 'Al estilo de Mardin: ', 'Mardin-Art: '],
  ['sanliurfa', 'مطابخ شانلي أورفة', 'Sanliurfa', 'À l’urfaote : ', 'Al estilo de Şanlıurfa: ', 'Şanlıurfa-Art: '],
  ['van', 'مطابخ وان', 'Van', 'À la vanote : ', 'Al estilo de Van: ', 'Van-Art: '],
  ['eskisehir', 'مطابخ أسكي شهير', 'Eskisehir', 'À l’eskisehirote : ', 'Al estilo de Eskişehir: ', 'Eskişehir-Art: '],
];

const profile = (ar, en, fr, es, de, category, meal, protein, carbs, fat, cooking) =>
  ({ ar, en, fr, es, de, category, meal, protein, carbs, fat, cooking });

export const BASE_REGIONAL_RECIPES = {
  grilled_kebab: profile('كباب مشوي بالخضار', 'Grilled Kebab with Vegetables', 'Kebab grillé aux légumes', 'Kebab a la parrilla con verduras', 'Gegrillter Kebab mit Gemüse', 'meat_mains', 'dinner', 19, 4, 11, 'grilling'),
  bulgur_pilaf: profile('برغل بيلاف', 'Bulgur Pilaf', 'Pilav de boulgour', 'Pilav de bulgur', 'Bulgur-Pilaw', 'rice_dishes', 'lunch', 5, 26, 5, 'simmering'),
  yogurt_soup: profile('شوربة الزبادي بالنعناع', 'Yogurt Soup with Mint', 'Soupe au yaourt et à la menthe', 'Sopa de yogur con menta', 'Joghurtsuppe mit Minze', 'soups_stews', 'lunch', 4, 14, 4, 'simmering'),
  red_lentil_soup: profile('شوربة العدس', 'Red Lentil Soup', 'Soupe de lentilles corail', 'Sopa de lentejas rojas', 'Rote-Linsen-Suppe', 'soups_stews', 'lunch', 7, 19, 3, 'simmering'),
  shepherd_salad: profile('سلطة الراعي', 'Shepherd Salad', 'Salade du berger', 'Ensalada del pastor', 'Hirtensalat', 'vegetable_mains', 'lunch', 2, 7, 6, 'tossing'),
  roast_chicken: profile('دجاج مشوي بالأعشاب', 'Herb-Roasted Chicken', 'Poulet rôti aux herbes', 'Pollo asado a las hierbas', 'Kräuter-Brathähnchen', 'poultry_mains', 'dinner', 22, 2, 9, 'roasting'),
  grilled_fish: profile('سمك مشوي بالليمون', 'Grilled Fish with Lemon', 'Poisson grillé au citron', 'Pescado a la parrilla con limón', 'Gegrillter Fisch mit Zitrone', 'fish_seafood', 'dinner', 21, 2, 8, 'grilling'),
  white_bean_stew: profile('يخنة الفاصولياء البيضاء', 'White Bean Stew', 'Mijoté de haricots blancs', 'Estofado de alubias blancas', 'Eintopf mit weißen Bohnen', 'soups_stews', 'dinner', 9, 21, 4, 'stewing'),
};

export const BASE_NATIONAL_RECIPES = {
  doner_chicken: profile('شاورما دجاج دونر حلال', 'Chicken Döner, Halal', 'Döner au poulet halal', 'Döner de pollo halal', 'Hähnchen-Döner, halal', 'meat_mains', 'lunch', 20, 6, 10, 'roasting'),
  doner_beef: profile('دونر لحم بقري حلال', 'Beef Döner, Halal', 'Döner au bœuf halal', 'Döner de ternera halal', 'Rindfleisch-Döner, halal', 'meat_mains', 'lunch', 22, 4, 12, 'roasting'),
  adana_kebab: profile('كباب أضنة بالضأن الحار حلال', 'Adana Kebab, Spicy Halal Lamb', 'Kebab d’Adana à l’agneau halal épicé', 'Kebab de Adana de cordero halal picante', 'Adana-Kebab, scharfes Halal-Lamm', 'meat_mains', 'dinner', 21, 3, 13, 'grilling'),
  urfa_kebab: profile('كباب أورفة بالضأن حلال', 'Urfa Kebab, Mild Halal Lamb', 'Kebab d’Urfa à l’agneau halal doux', 'Kebab de Urfa de cordero halal suave', 'Urfa-Kebab, mildes Halal-Lamm', 'meat_mains', 'dinner', 21, 3, 12, 'grilling'),
  iskender: profile('إسكندر بصلصة الطماطم والزبادي حلال', 'İskender Kebab with Tomato Sauce and Yogurt, Halal', 'İskender à la sauce tomate et au yaourt halal', 'İskender con salsa de tomate y yogur halal', 'İskender mit Tomatensoße und Joghurt, halal', 'meat_mains', 'dinner', 19, 9, 12, 'grilling'),
  lahmacun: profile('لحماجون بعجين رقيق ولحم بقري حلال', 'Lahmacun with Spiced Halal Beef', 'Lahmacun au bœuf épicé halal', 'Lahmacun con ternera especiada halal', 'Lahmacun mit gewürztem Halal-Rind', 'street_snacks', 'lunch', 10, 26, 8, 'baking'),
  pide_cheese: profile('بيده بالجبن', 'Pide with Kashar Cheese', 'Pide au fromage kaşar', 'Pide con queso kashar', 'Pide mit Kashar-Käse', 'street_snacks', 'lunch', 11, 28, 9, 'baking'),
  pide_meat: profile('بيده باللحم البقري الحلال', 'Pide with Halal Ground Beef', 'Pide au bœuf haché halal', 'Pide con carne picada de ternera halal', 'Pide mit Halal-Rinderhack', 'street_snacks', 'lunch', 12, 27, 9, 'baking'),
  pide_spinach: profile('بيده بالسبانخ والجبن', 'Pide with Spinach and Cheese', 'Pide aux épinards et au fromage', 'Pide con espinacas y queso', 'Pide mit Spinat und Käse', 'street_snacks', 'lunch', 9, 27, 8, 'baking'),
  menemen: profile('منمن بالطماطم والبيض والفلفل', 'Menemen with Tomato, Egg and Peppers', 'Menemen aux tomates, œufs et poivrons', 'Menemen con tomate, huevo y pimientos', 'Menemen mit Tomaten, Ei und Paprika', 'breakfast_items', 'breakfast', 9, 6, 10, 'pan_frying'),
  borek_cheese: profile('بوريك بالجبن والبقدونس', 'Börek with Cheese and Parsley', 'Börek au fromage et au persil', 'Börek con queso y perejil', 'Börek mit Käse und Petersilie', 'street_snacks', 'breakfast', 9, 28, 12, 'baking'),
  borek_spinach: profile('بوريك بالسبانخ', 'Börek with Spinach', 'Börek aux épinards', 'Börek con espinacas', 'Börek mit Spinat', 'street_snacks', 'breakfast', 8, 27, 11, 'baking'),
  su_boregi: profile('سو بوريك بالجبن', 'Su Böreği with Cheese Layers', 'Su böreği au fromage', 'Su böreği con queso', 'Su Böreği mit Käse', 'street_snacks', 'lunch', 10, 26, 13, 'boiling'),
  sigara_boregi: profile('بوريك سيجارة بالجبن', 'Sigara Böreği, Crispy Cheese Rolls', 'Sigara böreği croustillant au fromage', 'Sigara böreği crujiente con queso', 'Sigara Böreği, knusprige Käseröllchen', 'street_snacks', 'snack', 9, 24, 13, 'frying'),
  manti: profile('مانتي باللحم البقري والزبادي حلال', 'Mantı Dumplings with Halal Beef and Yogurt', 'Mantı au bœuf halal et au yaourt', 'Mantı con ternera halal y yogur', 'Mantı mit Halal-Rind und Joghurt', 'noodle_dishes', 'dinner', 13, 24, 8, 'boiling'),
  kofte: profile('كفتة مشوية باللحم البقري حلال', 'Köfte Grilled with Halal Beef', 'Köfte grillé au bœuf halal', 'Köfte a la parrilla con ternera halal', 'Köfte vom Grill mit Halal-Rind', 'meat_mains', 'dinner', 20, 5, 11, 'grilling'),
  cig_kofte: profile('تشي كفتة بالبرغل حلال', 'Çiğ Köfte with Bulgur, Halal No-Raw-Meat Version', 'Çiğ köfte au boulgour, version halal sans viande crue', 'Çiğ köfte con bulgur, versión halal sin carne cruda', 'Çiğ Köfte mit Bulgur, halal ohne Rohfleisch', 'street_snacks', 'snack', 5, 22, 6, 'assembling'),
  baklava: profile('بقلاوة بالفستق والعسل', 'Baklava with Pistachio and Honey', 'Baklava aux pistaches et au miel', 'Baklava con pistacho y miel', 'Baklava mit Pistazien und Honig', 'rice_cakes_sweets', 'snack', 6, 45, 22, 'baking'),
  kunefe: profile('كنافة بالجبن والفستق', 'Künefe with Cheese and Pistachio', 'Künefe au fromage et aux pistaches', 'Künefe con queso y pistacho', 'Künefe mit Käse und Pistazien', 'rice_cakes_sweets', 'snack', 9, 42, 19, 'baking'),
  lokum: profile('لوكوم بالورد والفستق', 'Turkish Delight with Rose and Pistachio', 'Loukoum à la rose et aux pistaches', 'Delicia turca con rosa y pistacho', 'Lokum mit Rose und Pistazien', 'rice_cakes_sweets', 'snack', 1, 60, 4, 'confectioning'),
  mercimek_corbasi: profile('شوربة العدس الأحمر', 'Classic Red Lentil Soup, Mercimek', 'Soupe mercimek aux lentilles corail', 'Sopa mercimek de lentejas rojas', 'Mercimek, klassische rote Linsensuppe', 'soups_stews', 'lunch', 7, 20, 3, 'simmering'),
  ezogelin: profile('شوربة إزوغلين بالبرغل', 'Ezogelin Soup with Bulgur', 'Soupe ezogelin au boulgour', 'Sopa ezogelin con bulgur', 'Ezogelin-Suppe mit Bulgur', 'soups_stews', 'lunch', 6, 19, 4, 'simmering'),
  yayla: profile('شوربة يايلا بالزبادي والأرز', 'Yayla Soup with Yogurt and Rice', 'Soupe yayla au yaourt et au riz', 'Sopa yayla con yogur y arroz', 'Yayla-Suppe mit Joghurt und Reis', 'soups_stews', 'lunch', 4, 15, 4, 'simmering'),
  tarhana: profile('شوربة طرخنة', 'Tarhana Soup', 'Soupe tarhana', 'Sopa tarhana', 'Tarhana-Suppe', 'soups_stews', 'lunch', 5, 17, 3, 'simmering'),
  domates_corbasi: profile('شوربة الطماطم بالريحان', 'Tomato Soup with Basil', 'Soupe de tomates au basilic', 'Sopa de tomate con albahaca', 'Tomatensuppe mit Basilikum', 'soups_stews', 'lunch', 3, 11, 4, 'simmering'),
  iskembe: profile('شوربة إشكيمبة بالثوم', 'İşkembe Tripe Soup with Garlic', 'Soupe de tripes işkembe à l’ail', 'Sopa de callos işkembe con ajo', 'İşkembe-Kuttelsuppe mit Knoblauch', 'soups_stews', 'lunch', 12, 3, 6, 'simmering'),
  pilav: profile('أرز بيلاف بالشعيرية', 'Rice Pilaf with Vermicelli', 'Pilav au riz et aux vermicelles', 'Pilav de arroz con fideos', 'Reis-Pilaw mit Fadennudeln', 'rice_dishes', 'lunch', 5, 28, 6, 'simmering'),
  bulgur_pilavi: profile('برغل بيلاف بالطماطم', 'Bulgur Pilaf with Tomato', 'Pilav de boulgour à la tomate', 'Pilav de bulgur con tomate', 'Bulgur-Pilaw mit Tomate', 'rice_dishes', 'lunch', 5, 26, 5, 'simmering'),
  ic_pilav: profile('أرز داخلي بالصنوبر والزبيب', 'İç Pilav with Pine Nuts and Raisins', 'İç pilav aux pignons et aux raisins secs', 'İç pilav con piñones y pasas', 'İç Pilaw mit Pinienkernen und Rosinen', 'rice_dishes', 'lunch', 5, 30, 7, 'simmering'),
  nohutlu_pilav: profile('أرز بالحمص', 'Rice Pilaf with Chickpeas', 'Pilav aux pois chiches', 'Pilav con garbanzos', 'Pilaw mit Kichererbsen', 'rice_dishes', 'lunch', 7, 30, 5, 'simmering'),
  kuru_fasulye: profile('فاصولياء بيضاء بصلصة الطماطم', 'Kuru Fasulye White Beans in Tomato Sauce', 'Kuru fasulye à la sauce tomate', 'Kuru fasulye con salsa de tomate', 'Kuru Fasulye in Tomatensoße', 'soups_stews', 'dinner', 9, 22, 4, 'stewing'),
  nohut_yemegi: profile('يخنة الحمص باللحم حلال', 'Chickpea Stew with Halal Beef', 'Mijoté de pois chiches au bœuf halal', 'Estofado de garbanzos con ternera halal', 'Kichererbseneintopf mit Halal-Rind', 'soups_stews', 'dinner', 12, 18, 6, 'stewing'),
  barbunya: profile('باربونيا بالفاصولياء الحمراء', 'Barbunya Borlotti Beans in Olive Oil', 'Barbunya à l’huile d’olive', 'Barbunya con aceite de oliva', 'Barbunya in Olivenöl', 'vegetable_mains', 'lunch', 8, 21, 6, 'stewing'),
  turlu: profile('تورلو بالخضار الموسمية', 'Türlü Vegetable Stew', 'Türlü aux légumes de saison', 'Türlü con verduras de temporada', 'Türlü-Gemüseeintopf', 'vegetable_mains', 'dinner', 4, 13, 6, 'stewing'),
  zeytinyagli_fasulye: profile('فاصولياء خضراء بزيت الزيتون', 'Green Beans in Olive Oil', 'Haricots verts à l’huile d’olive', 'Judías verdes en aceite de oliva', 'Grüne Bohnen in Olivenöl', 'vegetable_mains', 'lunch', 3, 12, 6, 'stewing'),
  yaprak_sarma: profile('يالنجي بأوراق العنب والأرز', 'Yaprak Sarma, Stuffed Vine Leaves', 'Sarma de feuilles de vigne au riz', 'Yaprak sarma de hojas de parra', 'Yaprak Sarma, gefüllte Weinblätter', 'vegetable_mains', 'lunch', 3, 18, 6, 'simmering'),
  dolma: profile('محشو فلفل بالأرز', 'Dolma, Stuffed Peppers with Rice', 'Dolma de poivrons farcis au riz', 'Dolma de pimientos rellenos de arroz', 'Dolma, gefüllte Paprika mit Reis', 'vegetable_mains', 'dinner', 3, 17, 5, 'simmering'),
  kisir: profile('كسير بالبرغل والرمان', 'Kısır Bulgur Salad with Pomegranate', 'Kısır au boulgour et à la grenade', 'Kısır con bulgur y granada', 'Kısır, Bulgursalat mit Granatapfel', 'vegetable_mains', 'lunch', 4, 22, 6, 'assembling'),
  cacik: profile('جاجيك بالزبادي والخيار', 'Cacık with Yogurt and Cucumber', 'Cacık au yaourt et au concombre', 'Cacık con yogur y pepino', 'Cacık mit Joghurt und Gurke', 'condiments_sauces', 'lunch', 5, 6, 4, 'assembling'),
  haydari: profile('حيدري بالزبادي والشبت', 'Haydari with Yogurt and Dill', 'Haydari au yaourt et à l’aneth', 'Haydari con yogur y eneldo', 'Haydari mit Joghurt und Dill', 'condiments_sauces', 'lunch', 5, 5, 6, 'assembling'),
  ezme: profile('إزمة بالطماطم والفلفل الحار', 'Ezme Spicy Tomato and Pepper Dip', 'Ezme à la tomate et au piment', 'Ezme con tomate y pimiento picante', 'Ezme, scharfer Tomaten-Paprika-Dip', 'condiments_sauces', 'lunch', 2, 8, 5, 'assembling'),
  coban_salata: profile('سلطة الراعي بالخيار والطماطم', 'Çoban Salad with Cucumber and Tomato', 'Salade çoban au concombre et à la tomate', 'Ensalada çoban con pepino y tomate', 'Çoban-Salat mit Gurke und Tomate', 'vegetable_mains', 'lunch', 2, 7, 6, 'tossing'),
  piyaz: profile('سلطة الفاصولياء بالطحينة', 'Piyaz White Bean Salad with Tahini', 'Piyaz aux haricots blancs et au tahini', 'Piyaz con alubias y tahini', 'Piyaz, weißer Bohnensalat mit Tahini', 'vegetable_mains', 'lunch', 8, 18, 7, 'tossing'),
  roka_salata: profile('سلطة الجرجير بالرمان', 'Arugula Salad with Pomegranate', 'Salade de roquette à la grenade', 'Ensalada de rúcula con granada', 'Rucolasalat mit Granatapfel', 'vegetable_mains', 'lunch', 2, 8, 5, 'tossing'),
  imam_bayildi: profile('إمام بايلدي بالباذنجان', 'İmam Bayıldı, Eggplant with Tomato and Onion', 'İmam bayıldı aux aubergines et tomates', 'İmam bayıldı con berenjena y tomate', 'İmam Bayıldı mit Aubergine und Tomate', 'vegetable_mains', 'dinner', 3, 12, 8, 'braising'),
  karniyarik: profile('قارني يارق بالباذنجان ولحم بقري حلال', 'Karnıyarık Eggplant with Halal Beef', 'Karnıyarık aux aubergines et au bœuf halal', 'Karnıyarık con berenjena y ternera halal', 'Karnıyarık mit Aubergine und Halal-Rind', 'meat_mains', 'dinner', 12, 10, 11, 'braising'),
  patlican_kebab: profile('كباب الباذنجان بالضأن حلال', 'Eggplant Kebab with Halal Lamb', 'Kebab d’aubergines à l’agneau halal', 'Kebab de berenjena con cordero halal', 'Auberginen-Kebab mit Halal-Lamm', 'meat_mains', 'dinner', 17, 8, 12, 'roasting'),
  tas_kebab: profile('تاس كباب بلحم الضأن حلال', 'Tas Kebab, Halal Lamb Stew', 'Tas kebab à l’agneau halal', 'Tas kebab con cordero halal', 'Tas Kebab, Halal-Lammeintopf', 'meat_mains', 'dinner', 19, 8, 11, 'stewing'),
  hunkar_begendi: profile('هونكار بياندي بالضأن حلال', 'Hünkâr Beğendi with Halal Lamb', 'Hünkâr beğendi à l’agneau halal', 'Hünkâr beğendi con cordero halal', 'Hünkâr Beğendi mit Halal-Lamm', 'meat_mains', 'dinner', 18, 7, 13, 'stewing'),
  ali_nazik: profile('علي نازك بالضأن والزبادي حلال', 'Ali Nazik with Halal Lamb and Yogurt', 'Ali nazik à l’agneau halal et au yaourt', 'Ali nazik con cordero halal y yogur', 'Ali Nazik mit Halal-Lamm und Joghurt', 'meat_mains', 'dinner', 18, 7, 12, 'stewing'),
  kuzu_tandir: profile('تندير ضأن حلال بالأرز', 'Kuzu Tandır Slow-Roast Halal Lamb with Rice', 'Kuzu tandır à l’agneau halal et au riz', 'Kuzu tandır con cordero halal y arroz', 'Kuzu Tandır mit Halal-Lamm und Reis', 'meat_mains', 'dinner', 20, 15, 13, 'roasting'),
  tavuk_sis: profile('شيش دجاج متبل حلال', 'Tavuk Şiş Marinated Halal Chicken Skewers', 'Tavuk şiş au poulet halal mariné', 'Tavuk şiş con pollo halal marinado', 'Tavuk Şiş, marinierte Halal-Hähnchenspieße', 'poultry_mains', 'dinner', 23, 2, 7, 'grilling'),
  tavuk_doner: profile('دونر دجاج حلال', 'Tavuk Döner, Halal Chicken', 'Tavuk döner au poulet halal', 'Tavuk döner de pollo halal', 'Tavuk Döner, Halal-Hähnchen', 'poultry_mains', 'lunch', 21, 4, 9, 'roasting'),
  kanat: profile('أجنحة دجاج مشوية حلال', 'Grilled Halal Chicken Wings', 'Ailes de poulet grillées halal', 'Alitas de pollo a la parrilla halal', 'Gegrillte Halal-Hähnchenflügel', 'poultry_mains', 'dinner', 22, 1, 12, 'grilling'),
  pirzola: profile('ضلوع ضأن مشوية حلال', 'Pirzola Grilled Halal Lamb Chops', 'Pirzola, côtelettes d’agneau grillées halal', 'Pirzola, chuletas de cordero a la parrilla halal', 'Pirzola, gegrillte Halal-Lammkoteletts', 'meat_mains', 'dinner', 24, 0, 15, 'grilling'),
  sac_kavurma: profile('ساتش كافورما بلحم الضأن حلال', 'Saç Kavurma Sautéed Halal Lamb', 'Saç kavurma à l’agneau halal sauté', 'Saç kavurma con cordero halal salteado', 'Saç Kavurma mit gebratenem Halal-Lamm', 'meat_mains', 'dinner', 20, 5, 12, 'pan_frying'),
  guvec: profile('كوفيتش بالخضار واللحم حلال', 'Güveç Casserole with Halal Beef and Vegetables', 'Güveç au bœuf halal et aux légumes', 'Güveç con ternera halal y verduras', 'Güveç mit Halal-Rind und Gemüse', 'soups_stews', 'dinner', 15, 10, 9, 'stewing'),
  hamsi: profile('هامسي مقلي', 'Fried Black Sea Anchovies, Hamsi', 'Hamsi frits de la mer Noire', 'Hamsi frito del mar Negro', 'Gebratene Schwarzmeer-Sardellen, Hamsi', 'fish_seafood', 'dinner', 19, 6, 12, 'frying'),
  levrek: profile('قاروص مشوي بالليمون', 'Grilled Sea Bass with Lemon, Levrek', 'Loup grillé au citron, levrek', 'Lubina a la parrilla con limón, levrek', 'Gegrillter Wolfsbarsch mit Zitrone, Levrek', 'fish_seafood', 'dinner', 21, 1, 8, 'grilling'),
  cupra: profile('دنيس مشوي بالأعشاب', 'Grilled Sea Bream with Herbs, Çipura', 'Dorade grillée aux herbes, çipura', 'Dorada a la parrilla con hierbas, çipura', 'Gegrillte Dorade mit Kräutern, Çipura', 'fish_seafood', 'dinner', 21, 1, 8, 'grilling'),
  palamut: profile('تونة بلاميدا مشوية', 'Grilled Bonito, Palamut', 'Bonite grillée, palamut', 'Bonito a la parrilla, palamut', 'Gegrillter Bonito, Palamut', 'fish_seafood', 'dinner', 22, 0, 9, 'grilling'),
  mezgit: profile('سمك مزجيت مخبوز', 'Baked Whiting, Mezgit', 'Merlan au four, mezgit', 'Pescadilla al horno, mezgit', 'Gebackener Wittling, Mezgit', 'fish_seafood', 'dinner', 19, 3, 6, 'baking'),
  kalamar: profile('كالاماري مقلي بالطرطور', 'Fried Calamari with Tarator Sauce', 'Calamars frits à la sauce tarator', 'Calamares fritos con salsa tarator', 'Gebratener Calamari mit Tarator-Soße', 'fish_seafood', 'snack', 15, 12, 11, 'frying'),
  midye_dolma: profile('بلح البحر المحشو بالأرز', 'Midye Dolma, Stuffed Mussels with Rice', 'Midye dolma farcies au riz', 'Midye dolma rellenos de arroz', 'Midye Dolma, gefüllte Miesmuscheln mit Reis', 'fish_seafood', 'snack', 8, 15, 5, 'simmering'),
  balik_ekmek: profile('بالك أكمك ساندويتش السمك', 'Balık Ekmek Fish Sandwich', 'Balık ekmek, sandwich au poisson', 'Balık ekmek, bocadillo de pescado', 'Balık Ekmek, Fischsandwich', 'street_snacks', 'lunch', 14, 26, 8, 'grilling'),
  sucuklu_yumurta: profile('بيض بالسجق البقري الحلال', 'Eggs with Halal Beef Sucuk', 'Œufs au sucuk de bœuf halal', 'Huevos con sucuk de ternera halal', 'Eier mit Halal-Rinder-Sucuk', 'breakfast_items', 'breakfast', 13, 2, 14, 'pan_frying'),
  pastirmali_yumurta: profile('بيض بالبسطرمة البقرية الحلال', 'Eggs with Halal Beef Pastırma', 'Œufs au pastırma de bœuf halal', 'Huevos con pastırma de ternera halal', 'Eier mit Halal-Rinder-Pastırma', 'breakfast_items', 'breakfast', 14, 2, 13, 'pan_frying'),
  kaymak_bal: profile('قيمر بالعسل والخبز', 'Kaymak with Honey and Bread', 'Kaymak au miel et au pain', 'Kaymak con miel y pan', 'Kaymak mit Honig und Brot', 'breakfast_items', 'breakfast', 4, 26, 14, 'assembling'),
  simit: profile('سميط بالسمسم', 'Simit Sesame Bread Ring', 'Simit au sésame', 'Simit con sésamo', 'Simit mit Sesam', 'breakfast_items', 'breakfast', 8, 40, 6, 'baking'),
  pogaca: profile('بوعاتشا بالزيتون', 'Poğaça with Olives', 'Poğaça aux olives', 'Poğaça con aceitunas', 'Poğaça mit Oliven', 'breakfast_items', 'breakfast', 6, 36, 11, 'baking'),
  acma: profile('أشمة بالجبن', 'Açma Soft Roll with Cheese', 'Açma au fromage', 'Açma con queso', 'Açma mit Käse', 'breakfast_items', 'breakfast', 7, 35, 12, 'baking'),
  gozleme: profile('كوزلمة بالجبن والسبانخ', 'Gözleme with Cheese and Spinach', 'Gözleme au fromage et aux épinards', 'Gözleme con queso y espinacas', 'Gözleme mit Käse und Spinat', 'street_snacks', 'breakfast', 8, 30, 9, 'pan_frying'),
  bazlama: profile('بزلمة بالزبدة', 'Bazlama Flatbread with Butter', 'Bazlama au beurre', 'Bazlama con mantequilla', 'Bazlama mit Butter', 'breakfast_items', 'breakfast', 7, 38, 8, 'pan_frying'),
  sutlac: profile('سوتلاج أرز بالحليب', 'Sütlaç Rice Pudding', 'Sütlaç, riz au lait', 'Sütlaç, arroz con leche', 'Sütlaç, Milchreis', 'rice_cakes_sweets', 'snack', 5, 24, 5, 'simmering'),
  kazandibi: profile('قزان ديبي بالكراميل', 'Kazandibi Caramelized Milk Pudding', 'Kazandibi caramélisé', 'Kazandibi caramelizado', 'Kazandibi, karamellisierter Milchpudding', 'rice_cakes_sweets', 'snack', 5, 25, 6, 'simmering'),
  asure: profile('آشورة بالحبوب والفواكه المجففة', 'Aşure with Grains and Dried Fruit', 'Aşure aux céréales et aux fruits secs', 'Aşure con cereales y frutos secos', 'Aşure mit Getreide und Trockenfrüchten', 'rice_cakes_sweets', 'snack', 5, 34, 4, 'simmering'),
  tavuk_gogsu: profile('حلوى صدر الدجاج بالحليب', 'Tavuk Göğsü Milk Pudding', 'Tavuk göğsü au lait', 'Tavuk göğsü con leche', 'Tavuk Göğsü, Milchpudding', 'rice_cakes_sweets', 'snack', 5, 22, 4, 'simmering'),
  sekerpare: profile('شاكربارة باللوز', 'Şekerpare Almond Cookies in Syrup', 'Şekerpare aux amandes au sirop', 'Şekerpare con almendra en almíbar', 'Şekerpare, Mandelgebäck in Sirup', 'rice_cakes_sweets', 'snack', 4, 40, 12, 'baking'),
  tulumba: profile('طولومبة بالقطر', 'Tulumba in Syrup', 'Tulumba au sirop', 'Tulumba en almíbar', 'Tulumba in Sirup', 'rice_cakes_sweets', 'snack', 3, 46, 13, 'frying'),
  revani: profile('ريفاني بالسميد', 'Revani Semolina Cake in Syrup', 'Revani à la semoule au sirop', 'Revani de sémola en almíbar', 'Revani, Grießkuchen in Sirup', 'rice_cakes_sweets', 'snack', 4, 42, 10, 'baking'),
  irmik_helva: profile('حلاوة السميد بالصنوبر', 'İrmik Helvası with Pine Nuts', 'İrmik helvası aux pignons', 'İrmik helvası con piñones', 'İrmik Helvası mit Pinienkernen', 'rice_cakes_sweets', 'snack', 5, 38, 12, 'simmering'),
  tahin_helva: profile('حلاوة الطحينة بالفستق', 'Tahini Helva with Pistachio', 'Helva au tahini et aux pistaches', 'Helva de tahini con pistacho', 'Tahini-Helva mit Pistazien', 'rice_cakes_sweets', 'snack', 8, 40, 18, 'confectioning'),
  kabak_tatlisi: profile('حلوى اليقطين بالجوز', 'Kabak Tatlısı, Pumpkin Dessert with Walnuts', 'Kabak tatlısı à la citrouille et aux noix', 'Kabak tatlısı de calabaza con nueces', 'Kabak Tatlısı, Kürbisdessert mit Walnüssen', 'rice_cakes_sweets', 'snack', 3, 30, 7, 'simmering'),
  ayva_tatlisi: profile('حلوى السفرجل بالقيمر', 'Ayva Tatlısı, Quince Dessert with Kaymak', 'Ayva tatlısı au coing et au kaymak', 'Ayva tatlısı de membrillo con kaymak', 'Ayva Tatlısı, Quittendessert mit Kaymak', 'rice_cakes_sweets', 'snack', 2, 28, 6, 'poaching'),
  ekmek_kadayifi: profile('أكمك قديف بالقطر والقيمر', 'Ekmek Kadayıfı in Syrup with Kaymak', 'Ekmek kadayıfı au sirop et au kaymak', 'Ekmek kadayıfı en almíbar con kaymak', 'Ekmek Kadayıfı in Sirup mit Kaymak', 'rice_cakes_sweets', 'snack', 4, 44, 12, 'baking'),
  lokma: profile('لقمة بالقطر', 'Lokma Fried Dough in Syrup', 'Lokma frit au sirop', 'Lokma frito en almíbar', 'Lokma, frittierte Teigbällchen in Sirup', 'rice_cakes_sweets', 'snack', 3, 45, 12, 'frying'),
  kumpir: profile('كومبير بطاطس محشوة', 'Kumpir Stuffed Baked Potato', 'Kumpir, pomme de terre farcie', 'Kumpir, patata asada rellena', 'Kumpir, gefüllte Ofenkartoffel', 'street_snacks', 'lunch', 7, 30, 9, 'baking'),
  ayran: profile('عيران بالزبادي', 'Ayran Yogurt Drink', 'Ayran au yaourt', 'Ayran con yogur', 'Ayran, Joghurtgetränk', 'beverages', 'snack', 3, 5, 2, 'blending'),
  salep: profile('سحلب بالقرفة', 'Salep with Cinnamon', 'Salep à la cannelle', 'Salep con canela', 'Salep mit Zimt', 'beverages', 'snack', 4, 20, 4, 'simmering'),
  turk_kahvesi: profile('قهوة تركية', 'Turkish Coffee', 'Café turc', 'Café turco', 'Türkischer Kaffee', 'beverages', 'breakfast', 0, 1, 0, 'brewing'),
  etli_ekmek: profile('خبز باللحم البقري الحلال', 'Etli Ekmek with Halal Beef', 'Etli ekmek au bœuf halal', 'Etli ekmek con ternera halal', 'Etli Ekmek mit Halal-Rind', 'street_snacks', 'lunch', 11, 27, 8, 'baking'),
  beyti: profile('بيتي كباب ملفوف حلال', 'Beyti Kebab Wrap with Halal Beef', 'Beyti au bœuf halal', 'Beyti con ternera halal', 'Beyti mit Halal-Rind', 'meat_mains', 'dinner', 18, 14, 11, 'grilling'),
  adana_durum: profile('دوروم أضنة بالضأن حلال', 'Adana Dürüm Wrap with Halal Lamb', 'Dürüm d’Adana à l’agneau halal', 'Dürüm de Adana con cordero halal', 'Adana-Dürüm mit Halal-Lamm', 'street_snacks', 'lunch', 17, 22, 11, 'grilling'),
  tavuk_durum: profile('دوروم دجاج حلال', 'Chicken Dürüm Wrap, Halal', 'Dürüm au poulet halal', 'Dürüm de pollo halal', 'Hähnchen-Dürüm, halal', 'street_snacks', 'lunch', 16, 23, 8, 'grilling'),
  kokorec_halal: profile('كوكوريتش ضأن حلال', 'Kokoreç with Halal Lamb', 'Kokoreç à l’agneau halal', 'Kokoreç con cordero halal', 'Kokoreç mit Halal-Lamm', 'street_snacks', 'snack', 16, 4, 13, 'grilling'),
  midye_tava: profile('بلح البحر المقلي', 'Midye Tava, Fried Mussels', 'Midye tava frites', 'Midye tava fritos', 'Midye Tava, frittierte Miesmuscheln', 'fish_seafood', 'snack', 12, 11, 10, 'frying'),
  katmer: profile('قطمر بالفستق والقيمر', 'Katmer with Pistachio and Kaymak', 'Katmer aux pistaches et au kaymak', 'Katmer con pistacho y kaymak', 'Katmer mit Pistazien und Kaymak', 'breakfast_items', 'breakfast', 6, 40, 16, 'baking'),
  boyoz: profile('بويوز بالزبدة', 'Boyoz with Butter', 'Boyoz au beurre', 'Boyoz con mantequilla', 'Boyoz mit Butter', 'breakfast_items', 'breakfast', 5, 38, 12, 'baking'),
  tahin_pekmez: profile('طحينة بالدبس', 'Tahini with Grape Molasses', 'Tahini à la mélasse de raisin', 'Tahini con melaza de uva', 'Tahini mit Traubensirup', 'breakfast_items', 'breakfast', 6, 24, 12, 'assembling'),
  biberli_yumurta: profile('بيض بالفلفل المشوي', 'Eggs with Roasted Peppers', 'Œufs aux poivrons rôtis', 'Huevos con pimientos asados', 'Eier mit gerösteter Paprika', 'breakfast_items', 'breakfast', 9, 5, 10, 'pan_frying'),
  sahanda_yumurta: profile('بيض مقلي بالزبدة', 'Sahanda Yumurta, Fried Eggs in Butter', 'Sahanda yumurta, œufs au beurre', 'Sahanda yumurta, huevos en mantequilla', 'Sahanda Yumurta, Spiegeleier in Butter', 'breakfast_items', 'breakfast', 9, 1, 12, 'pan_frying'),
  misir_ekmegi: profile('خبز الذرة', 'Cornbread, Mısır Ekmeği', 'Pain de maïs, mısır ekmeği', 'Pan de maíz, mısır ekmeği', 'Maisbrot, Mısır Ekmeği', 'breakfast_items', 'breakfast', 6, 32, 7, 'baking'),
  kuymak: profile('كويماك بالجبن والذرة', 'Kuymak with Cheese and Cornmeal', 'Kuymak au fromage et à la semoule de maïs', 'Kuymak con queso y sémola de maíz', 'Kuymak mit Käse und Maisgrieß', 'breakfast_items', 'breakfast', 9, 22, 15, 'pan_frying'),
  kaygana: profile('كايغانة بالأعشاب', 'Kaygana Herb Omelette', 'Kaygana, omelette aux herbes', 'Kaygana, tortilla de hierbas', 'Kaygana, Kräuteromelett', 'breakfast_items', 'breakfast', 9, 4, 10, 'pan_frying'),
  pide_kasarli_yumurta: profile('بيده بالجبن والبيض', 'Pide with Cheese and Egg', 'Pide au fromage et à l’œuf', 'Pide con queso y huevo', 'Pide mit Käse und Ei', 'breakfast_items', 'breakfast', 11, 27, 10, 'baking'),
  borek_patates: profile('بوريك بالبطاطس', 'Börek with Potato', 'Börek à la pomme de terre', 'Börek con patata', 'Börek mit Kartoffel', 'street_snacks', 'breakfast', 7, 29, 10, 'baking'),
  kol_boregi: profile('بوريك ذراع باللحم البقري حلال', 'Kol Böreği with Halal Beef', 'Kol böreği au bœuf halal', 'Kol böreği con ternera halal', 'Kol Böreği mit Halal-Rind', 'street_snacks', 'snack', 10, 27, 12, 'baking'),
  ciborek: profile('تشيبوريك مقلي باللحم البقري حلال', 'Çibörek Fried with Halal Beef', 'Çibörek frit au bœuf halal', 'Çibörek frito con ternera halal', 'Çibörek, frittiert mit Halal-Rind', 'street_snacks', 'snack', 10, 25, 13, 'frying'),
  icli_kofte: profile('إكلي كفتة محشوة بالبرغل حلال', 'İçli Köfte Stuffed Bulgur with Halal Beef', 'İçli köfte farci au boulgour et au bœuf halal', 'İçli köfte relleno de bulgur y ternera halal', 'İçli Köfte, gefüllter Bulgur mit Halal-Rind', 'street_snacks', 'snack', 11, 20, 10, 'frying'),
  oruk: profile('أوروك بالبرغل حلال', 'Oruk Bulgur Kofta with Halal Beef', 'Oruk au boulgour et au bœuf halal', 'Oruk con bulgur y ternera halal', 'Oruk, Bulgur-Köfte mit Halal-Rind', 'street_snacks', 'snack', 10, 21, 9, 'baking'),
  mercimek_koftesi: profile('كفتة العدس الأحمر', 'Red Lentil Kofta, Mercimek Köftesi', 'Mercimek köftesi aux lentilles corail', 'Mercimek köftesi de lentejas rojas', 'Mercimek Köftesi, rote Linsenbällchen', 'street_snacks', 'snack', 7, 20, 5, 'assembling'),
  fellah_koftesi: profile('كفتة فلاح بالبرغل', 'Fellah Köftesi with Bulgur', 'Fellah köftesi au boulgour', 'Fellah köftesi con bulgur', 'Fellah Köftesi mit Bulgur', 'street_snacks', 'snack', 7, 21, 5, 'boiling'),
  siron: profile('سيرون بالزبادي والثوم', 'Siron with Yogurt and Garlic', 'Siron au yaourt et à l’ail', 'Siron con yogur y ajo', 'Siron mit Joghurt und Knoblauch', 'noodle_dishes', 'dinner', 9, 24, 8, 'boiling'),
  tepsi_mantisi: profile('مانتي صينية بالفرن', 'Tepsi Mantısı, Baked Dumplings with Yogurt', 'Tepsi mantısı au yaourt, au four', 'Tepsi mantısı con yogur, al horno', 'Tepsi Mantısı, Ofen-Dumplings mit Joghurt', 'noodle_dishes', 'dinner', 12, 25, 9, 'baking'),
  eriste: profile('إريشتة بالزبدة والجبن', 'Erişte Noodles with Butter and Cheese', 'Erişte au beurre et au fromage', 'Erişte con mantequilla y queso', 'Erişte mit Butter und Käse', 'noodle_dishes', 'lunch', 8, 28, 9, 'boiling'),
  keskek: profile('كشك بالقمح ولحم الضأن حلال', 'Keşkek Wheat and Halal Lamb Porridge', 'Keşkek au blé et à l’agneau halal', 'Keşkek con trigo y cordero halal', 'Keşkek, Weizenbrei mit Halal-Lamm', 'soups_stews', 'dinner', 14, 24, 7, 'simmering'),
  alaca_corbasi: profile('شوربة ألاجا بالخضار', 'Alaca Soup with Vegetables', 'Soupe alaca aux légumes', 'Sopa alaca con verduras', 'Alaca-Suppe mit Gemüse', 'soups_stews', 'lunch', 4, 14, 3, 'simmering'),
  dugun_corbasi: profile('شوربة الزفاف بالضأن حلال', 'Düğün Soup with Halal Lamb', 'Soupe düğün à l’agneau halal', 'Sopa düğün con cordero halal', 'Düğün-Suppe mit Halal-Lamm', 'soups_stews', 'lunch', 10, 8, 5, 'simmering'),
  sehriye_corbasi: profile('شوربة الشعيرية', 'Vermicelli Soup, Şehriye', 'Soupe şehriye aux vermicelles', 'Sopa şehriye con fideos', 'Şehriye, Fadennudelsuppe', 'soups_stews', 'lunch', 4, 13, 3, 'simmering'),
  tavuk_corbasi: profile('شوربة الدجاج بالليمون', 'Chicken Soup with Lemon', 'Soupe de poulet au citron', 'Sopa de pollo con limón', 'Hühnersuppe mit Zitrone', 'soups_stews', 'lunch', 11, 7, 3, 'simmering'),
  balik_corbasi: profile('شوربة السمك بالخضار', 'Fish Soup with Vegetables, No Wine', 'Soupe de poisson aux légumes, sans vin', 'Sopa de pescado con verduras, sin vino', 'Fischsuppe mit Gemüse, ohne Wein', 'soups_stews', 'lunch', 12, 6, 3, 'simmering'),
  pacanga_boregi: profile('بوريك باتشانجا بالبسطرمة البقرية حلال', 'Paçanga Böreği with Halal Beef Pastırma', 'Paçanga böreği au pastırma de bœuf halal', 'Paçanga böreği con pastırma de ternera halal', 'Paçanga Böreği mit Halal-Rinder-Pastırma', 'street_snacks', 'snack', 10, 24, 13, 'frying'),
};

export const EXPANSION_REGIONAL_RECIPES = {
  tomato_bulgur: profile('برغل بالطماطم والفلفل', 'Tomato Bulgur with Peppers', 'Boulgour à la tomate et aux poivrons', 'Bulgur con tomate y pimientos', 'Bulgur mit Tomate und Paprika', 'rice_dishes', 'lunch', 5, 25, 5, 'simmering'),
  chicken_skewers: profile('أسياخ دجاج متبلة', 'Marinated Chicken Skewers', 'Brochettes de poulet mariné', 'Brochetas de pollo marinado', 'Marinierte Hähnchenspieße', 'poultry_mains', 'dinner', 22, 2, 7, 'grilling'),
  vegetable_stew: profile('يخنة الخضار الموسمية', 'Seasonal Vegetable Stew', 'Mijoté de légumes de saison', 'Estofado de verduras de temporada', 'Saisongemüse-Eintopf', 'vegetable_mains', 'dinner', 3, 12, 5, 'stewing'),
  cucumber_yogurt: profile('زبادي بالخيار والنعناع', 'Yogurt with Cucumber and Mint', 'Yaourt au concombre et à la menthe', 'Yogur con pepino y menta', 'Joghurt mit Gurke und Minze', 'condiments_sauces', 'lunch', 5, 6, 4, 'assembling'),
  tahini_salad: profile('سلطة الطحينة بالليمون', 'Tahini Salad with Lemon', 'Salade au tahini et au citron', 'Ensalada de tahini con limón', 'Tahini-Salat mit Zitrone', 'vegetable_mains', 'lunch', 3, 10, 8, 'tossing'),
  lamb_stew: profile('يخنة الضأن بالخضار', 'Lamb and Vegetable Stew', 'Mijoté d’agneau aux légumes', 'Estofado de cordero con verduras', 'Lamm-Gemüse-Eintopf', 'meat_mains', 'dinner', 18, 9, 11, 'stewing'),
  eggplant_puree: profile('هريس الباذنجان المشوي', 'Smoked Eggplant Purée', 'Purée d’aubergines fumées', 'Puré de berenjena ahumada', 'Geräuchertes Auberginenpüree', 'vegetable_mains', 'lunch', 3, 8, 6, 'roasting'),
  semolina_helva: profile('حلاوة السميد', 'Semolina Helva', 'Helva à la semoule', 'Helva de sémola', 'Grieß-Helva', 'rice_cakes_sweets', 'snack', 5, 37, 11, 'simmering'),
};

export const EXPANSION_NATIONAL_RECIPES = {
  muska_boregi: profile('بوريك مثلث بالجبن', 'Muska Böreği Triangle with Cheese', 'Muska böreği triangulaire au fromage', 'Muska böreği triangular con queso', 'Muska Böreği, Dreiecke mit Käse', 'street_snacks', 'snack', 8, 25, 12, 'baking'),
  dible: profile('ديبله أرز بالخضار', 'Dible Rice with Vegetables', 'Dible au riz et aux légumes', 'Dible de arroz con verduras', 'Dible, Reis mit Gemüse', 'rice_dishes', 'lunch', 5, 27, 5, 'simmering'),
  acem_pilavi: profile('أرز عجمي بالضأن حلال', 'Acem Pilavı with Halal Lamb', 'Acem pilavı à l’agneau halal', 'Acem pilavı con cordero halal', 'Acem Pilavı mit Halal-Lamm', 'rice_dishes', 'dinner', 13, 27, 9, 'simmering'),
  perde_pilavi: profile('أرز الستار بالدجاج واللوز', 'Perde Pilavı with Chicken and Almonds', 'Perde pilavı au poulet et aux amandes', 'Perde pilavı con pollo y almendras', 'Perde Pilavı mit Hähnchen und Mandeln', 'rice_dishes', 'dinner', 12, 28, 10, 'baking'),
  firik_pilavi: profile('فريك بيلاف بالضأن حلال', 'Firik Pilaf with Halal Lamb', 'Pilav firik à l’agneau halal', 'Pilav firik con cordero halal', 'Firik-Pilaw mit Halal-Lamm', 'rice_dishes', 'dinner', 13, 26, 9, 'simmering'),
  maklube: profile('مقلوبة بالخضار والدجاج', 'Maklube Upside-Down Rice with Chicken and Vegetables', 'Maklube au riz, poulet et légumes', 'Maklube de arroz invertido con pollo y verduras', 'Maklube, gestürzter Reis mit Hähnchen und Gemüse', 'rice_dishes', 'dinner', 12, 27, 8, 'simmering'),
  nokul: profile('نوكول بالجبن', 'Nokul with Cheese', 'Nokul au fromage', 'Nokul con queso', 'Nokul mit Käse', 'breakfast_items', 'breakfast', 7, 34, 10, 'baking'),
  ay_coregi: profile('كعكة القمر بالجوز', 'Ay Çöreği, Crescent Cookies with Walnuts', 'Ay çöreği aux noix', 'Ay çöreği con nueces', 'Ay Çöreği, Mondgebäck mit Walnüssen', 'rice_cakes_sweets', 'snack', 6, 38, 13, 'baking'),
  tahini_corek: profile('خبز الطحينة الحلو', 'Tahini Sweet Bread', 'Pain sucré au tahini', 'Pan dulce de tahini', 'Tahini-Süßbrot', 'breakfast_items', 'breakfast', 7, 36, 11, 'baking'),
  zeytinyagli_kabak: profile('كوسا بزيت الزيتون', 'Zucchini in Olive Oil', 'Courgettes à l’huile d’olive', 'Calabacín en aceite de oliva', 'Zucchini in Olivenöl', 'vegetable_mains', 'lunch', 2, 9, 6, 'stewing'),
  zeytinyagli_pirasa: profile('كراث بزيت الزيتون', 'Leeks in Olive Oil', 'Poireaux à l’huile d’olive', 'Puerros en aceite de oliva', 'Lauch in Olivenöl', 'vegetable_mains', 'lunch', 2, 10, 5, 'stewing'),
  zeytinyagli_enginar: profile('خرشوف بزيت الزيتون', 'Artichokes in Olive Oil', 'Artichauts à l’huile d’olive', 'Alcachofas en aceite de oliva', 'Artischocken in Olivenöl', 'vegetable_mains', 'lunch', 3, 11, 6, 'stewing'),
  zeytinyagli_bakla: profile('فول أخضر بزيت الزيتون', 'Fava Beans in Olive Oil', 'Fèves à l’huile d’olive', 'Habas en aceite de oliva', 'Dicke Bohnen in Olivenöl', 'vegetable_mains', 'lunch', 6, 13, 5, 'stewing'),
  zeytinyagli_bamya: profile('بامية بزيت الزيتون', 'Okra in Olive Oil', 'Gombos à l’huile d’olive', 'Ocra en aceite de oliva', 'Okra in Olivenöl', 'vegetable_mains', 'lunch', 2, 10, 5, 'stewing'),
  zeytinyagli_kereviz: profile('كرفس بزيت الزيتون', 'Celeriac in Olive Oil', 'Céleri-rave à l’huile d’olive', 'Apionabo en aceite de oliva', 'Sellerie in Olivenöl', 'vegetable_mains', 'lunch', 2, 11, 6, 'stewing'),
  kabak_mucver: profile('موجفر كوسا', 'Zucchini Fritters, Mücver', 'Mücver, beignets de courgettes', 'Mücver, buñuelos de calabacín', 'Mücver, Zucchinipuffer', 'vegetable_mains', 'lunch', 6, 8, 8, 'frying'),
  patlican_musakka: profile('مسقعة الباذنجان بلحم بقري حلال', 'Eggplant Moussaka with Halal Beef', 'Moussaka d’aubergines au bœuf halal', 'Musaka de berenjena con ternera halal', 'Auberginen-Moussaka mit Halal-Rind', 'meat_mains', 'dinner', 12, 10, 11, 'baking'),
  firinda_makarna: profile('معكرونة بالفرن بالجبن', 'Baked Pasta with Cheese, Fırında Makarna', 'Fırında makarna au fromage', 'Fırında makarna con queso', 'Fırında Makarna, Ofennudeln mit Käse', 'noodle_dishes', 'lunch', 9, 28, 10, 'baking'),
  karnabahar_kizartma: profile('قرنبيط مقلي بالزبادي', 'Fried Cauliflower with Yogurt', 'Chou-fleur frit au yaourt', 'Coliflor frita con yogur', 'Gebratener Blumenkohl mit Joghurt', 'vegetable_mains', 'lunch', 5, 9, 8, 'frying'),
  kapuska: profile('كابوسكا ملفوف باللحم حلال', 'Kapuska Cabbage Stew with Halal Beef', 'Kapuska au chou et au bœuf halal', 'Kapuska con col y ternera halal', 'Kapuska, Kohleintopf mit Halal-Rind', 'soups_stews', 'dinner', 11, 11, 7, 'stewing'),
  lahana_sarma: profile('ملفوف محشو بالأرز', 'Stuffed Cabbage Rolls with Rice', 'Chou farci au riz', 'Repollo relleno de arroz', 'Kohlrouladen mit Reis', 'vegetable_mains', 'dinner', 4, 16, 5, 'simmering'),
  patates_oturtma: profile('بطاطس بالفرن بلحم بقري حلال', 'Potato Bake with Halal Beef', 'Gratin de pommes de terre au bœuf halal', 'Patatas al horno con ternera halal', 'Kartoffelauflauf mit Halal-Rind', 'meat_mains', 'dinner', 12, 14, 9, 'baking'),
  fasulye_pilaki: profile('فاصولياء بيلاكي بالزيت', 'Fasulye Pilaki in Olive Oil', 'Fasulye pilaki à l’huile d’olive', 'Fasulye pilaki en aceite de oliva', 'Fasulye Pilaki in Olivenöl', 'vegetable_mains', 'lunch', 8, 20, 6, 'stewing'),
  soslu_patlican: profile('باذنجان مقلي بصلصة الزبادي', 'Fried Eggplant with Yogurt Sauce', 'Aubergines frites à la sauce yaourt', 'Berenjena frita con salsa de yogur', 'Gebratene Aubergine mit Joghurtsoße', 'vegetable_mains', 'lunch', 4, 9, 8, 'frying'),
  domates_dolmasi_etli: profile('طماطم محشوة باللحم حلال', 'Tomatoes Stuffed with Halal Beef', 'Tomates farcies au bœuf halal', 'Tomates rellenos de ternera halal', 'Tomaten gefüllt mit Halal-Rind', 'meat_mains', 'dinner', 11, 10, 7, 'simmering'),
  kabak_dolmasi: profile('كوسا محشوة بالأرز', 'Zucchini Dolma with Rice', 'Courgettes farcies au riz', 'Calabacín relleno de arroz', 'Zucchini-Dolma mit Reis', 'vegetable_mains', 'dinner', 3, 16, 5, 'simmering'),
  biber_dolmasi_etli: profile('فلفل محشو باللحم حلال', 'Peppers Stuffed with Halal Beef', 'Poivrons farcis au bœuf halal', 'Pimientos rellenos de ternera halal', 'Paprika gefüllt mit Halal-Rind', 'meat_mains', 'dinner', 11, 11, 8, 'simmering'),
  kuzu_guvec: profile('كوفيتش ضأن حلال بالخضار', 'Lamb Güveç with Vegetables, Halal', 'Güveç d’agneau halal aux légumes', 'Güveç de cordero halal con verduras', 'Lamm-Güveç mit Gemüse, halal', 'meat_mains', 'dinner', 18, 10, 11, 'stewing'),
  tavuk_guvec: profile('كوفيتش دجاج بالخضار', 'Chicken Güveç with Vegetables', 'Güveç de poulet aux légumes', 'Güveç de pollo con verduras', 'Hähnchen-Güveç mit Gemüse', 'poultry_mains', 'dinner', 17, 10, 8, 'stewing'),
  orman_kebabi: profile('كباب الغابة بالضأن حلال', 'Orman Kebabı Forest Stew with Halal Lamb', 'Orman kebabı à l’agneau halal', 'Orman kebabı con cordero halal', 'Orman Kebabı, Forsteintopf mit Halal-Lamm', 'meat_mains', 'dinner', 18, 9, 11, 'stewing'),
  elbasan_tava: profile('تاوة إلباسان بالضأن حلال', 'Elbasan Tava with Halal Lamb', 'Elbasan tava à l’agneau halal', 'Elbasan tava con cordero halal', 'Elbasan Tava mit Halal-Lamm', 'meat_mains', 'dinner', 19, 6, 12, 'baking'),
  cokertme_kebabi: profile('كباب تشوكرتمة بلحم بقري حلال', 'Çökertme Kebabı with Halal Beef and Potato Straws', 'Çökertme kebabı au bœuf halal et aux pailles de pommes de terre', 'Çökertme kebabı con ternera halal y pajitas de patata', 'Çökertme Kebabı mit Halal-Rind und Kartoffelstroh', 'meat_mains', 'dinner', 18, 12, 11, 'stewing'),
  cag_kebabi: profile('كباب تشاغ بالضأن حلال', 'Cağ Kebabı with Halal Lamb', 'Cağ kebabı à l’agneau halal', 'Cağ kebabı con cordero halal', 'Cağ Kebabı mit Halal-Lamm', 'meat_mains', 'dinner', 22, 2, 13, 'roasting'),
  testi_kebabi: profile('كباب الجرة بالضأن حلال', 'Testi Kebabı Pottery Stew with Halal Lamb', 'Testi kebabı en jarre à l’agneau halal', 'Testi kebabı en vasija con cordero halal', 'Testi Kebabı, Topfeintopf mit Halal-Lamm', 'meat_mains', 'dinner', 18, 9, 11, 'stewing'),
  kuzu_kapama: profile('ضأن مطهو بالأعشاب حلال', 'Kuzu Kapama Herb-Braised Halal Lamb', 'Kuzu kapama braisé aux herbes, agneau halal', 'Kuzu kapama estofado con hierbas, cordero halal', 'Kuzu Kapama, kräutergeschmortes Halal-Lamm', 'meat_mains', 'dinner', 21, 4, 13, 'braising'),
  kuzu_incik: profile('ساق ضأن مطهو حلال', 'Kuzu İncik Braised Halal Lamb Shank', 'Kuzu incik, jarret d’agneau braisé halal', 'Kuzu incik, jarrete de cordero estofado halal', 'Kuzu İncik, geschmorte Halal-Lammhaxe', 'meat_mains', 'dinner', 22, 3, 14, 'braising'),
  dana_antrikot: profile('أنتريكوت بقري مشوي حلال', 'Grilled Halal Beef Entrecôte', 'Entrecôte de bœuf grillée halal', 'Entrecot de ternera a la parrilla halal', 'Gegrilltes Halal-Rinderentrecôte', 'meat_mains', 'dinner', 25, 0, 14, 'grilling'),
  kofte_domates: profile('كفتة بصلصة الطماطم حلال', 'Köfte in Tomato Sauce with Halal Beef', 'Köfte à la sauce tomate au bœuf halal', 'Köfte en salsa de tomate con ternera halal', 'Köfte in Tomatensoße mit Halal-Rind', 'meat_mains', 'dinner', 16, 7, 10, 'simmering'),
  izmir_kofte: profile('كفتة إزمير بالفرن حلال', 'İzmir Köfte Baked with Halal Beef', 'İzmir köfte au four au bœuf halal', 'İzmir köfte al horno con ternera halal', 'İzmir Köfte, Ofenköfte mit Halal-Rind', 'meat_mains', 'dinner', 15, 10, 10, 'baking'),
  tekirdag_kofte: profile('كفتة تكيرداغ حلال', 'Tekirdağ Köfte with Halal Beef', 'Tekirdağ köfte au bœuf halal', 'Tekirdağ köfte con ternera halal', 'Tekirdağ Köfte mit Halal-Rind', 'meat_mains', 'dinner', 19, 5, 11, 'grilling'),
  akcaabat_kofte: profile('كفتة أقجة أباد حلال', 'Akçaabat Köfte with Halal Beef', 'Akçaabat köfte au bœuf halal', 'Akçaabat köfte con ternera halal', 'Akçaabat Köfte mit Halal-Rind', 'meat_mains', 'dinner', 19, 6, 10, 'grilling'),
  tire_kofte: profile('كفتة تيرة حلال', 'Tire Köfte with Halal Beef', 'Tire köfte au bœuf halal', 'Tire köfte con ternera halal', 'Tire Köfte mit Halal-Rind', 'meat_mains', 'dinner', 18, 5, 10, 'grilling'),
  sogan_kebabi: profile('كباب البصل بالضأن حلال', 'Soğan Kebabı Onion Stew with Halal Lamb', 'Soğan kebabı aux oignons et à l’agneau halal', 'Soğan kebabı con cebolla y cordero halal', 'Soğan Kebabı, Zwiebeleintopf mit Halal-Lamm', 'meat_mains', 'dinner', 17, 9, 11, 'stewing'),
  fistikli_kebab: profile('كباب بالفستق بالضأن حلال', 'Fıstıklı Kebab with Pistachio and Halal Lamb', 'Fıstıklı kebab aux pistaches et à l’agneau halal', 'Fıstıklı kebab con pistacho y cordero halal', 'Fıstıklı Kebab mit Pistazien und Halal-Lamm', 'meat_mains', 'dinner', 20, 5, 13, 'grilling'),
  simit_kebabi: profile('كباب السميط بالبرغل حلال', 'Simit Kebabı with Bulgur and Halal Lamb', 'Simit kebabı au boulgour et à l’agneau halal', 'Simit kebabı con bulgur y cordero halal', 'Simit Kebabı mit Bulgur und Halal-Lamm', 'meat_mains', 'dinner', 18, 8, 11, 'grilling'),
  belen_tava: profile('تاوة بلن بالضأن حلال', 'Belen Tava with Halal Lamb and Vegetables', 'Belen tava à l’agneau halal et aux légumes', 'Belen tava con cordero halal y verduras', 'Belen Tava mit Halal-Lamm und Gemüse', 'meat_mains', 'dinner', 18, 8, 12, 'roasting'),
  abagannus: profile('أبا جانوش بالباذنجان', 'Aba Gannuş Eggplant Dip with Tahini', 'Aba gannuş à l’aubergine et au tahini', 'Aba gannuş con berenjena y tahini', 'Aba Gannuş, Auberginen-Dip mit Tahini', 'condiments_sauces', 'snack', 3, 7, 8, 'assembling'),
  muhammara: profile('محمرة بالفلفل والجوز', 'Muhammara Pepper and Walnut Dip', 'Muhammara au poivron et aux noix', 'Muhammara con pimiento y nueces', 'Muhammara, Paprika-Walnuss-Dip', 'condiments_sauces', 'snack', 3, 8, 9, 'blending'),
  gavurdagi: profile('سلطة غافورداغي بالجوز', 'Gavurdağı Salad with Walnuts', 'Salade gavurdağı aux noix', 'Ensalada gavurdağı con nueces', 'Gavurdağı-Salat mit Walnüssen', 'vegetable_mains', 'lunch', 3, 8, 7, 'tossing'),
  sumakli_sogan: profile('سلطة البصل بالسماق', 'Onion Salad with Sumac', 'Salade d’oignons au sumac', 'Ensalada de cebolla con zumaque', 'Zwiebelsalat mit Sumach', 'vegetable_mains', 'lunch', 1, 6, 4, 'tossing'),
  cevizli_biber: profile('فلفل بالجوز والثوم', 'Peppers with Walnut and Garlic', 'Poivrons aux noix et à l’ail', 'Pimientos con nueces y ajo', 'Paprika mit Walnuss und Knoblauch', 'vegetable_mains', 'snack', 3, 7, 8, 'assembling'),
  bostana: profile('بوستانة بالخضار النيئة', 'Bostana Fresh Vegetable Dip', 'Bostana aux légumes crus', 'Bostana con verduras crudas', 'Bostana, frischer Gemüse-Dip', 'condiments_sauces', 'snack', 2, 8, 5, 'blending'),
  gullac: profile('كولاج بحليب الورد', 'Güllaç with Rose Milk', 'Güllaç au lait de rose', 'Güllaç con leche de rosas', 'Güllaç mit Rosenmilch', 'rice_cakes_sweets', 'snack', 4, 26, 4, 'assembling'),
  hosaf: profile('هوشاف بالفواكه المجففة', 'Hoşaf Dried Fruit Compote', 'Hoşaf aux fruits secs', 'Hoşaf con frutos secos', 'Hoşaf, Trockenfruchtkompott', 'rice_cakes_sweets', 'snack', 1, 18, 0, 'simmering'),
  komposto: profile('كومبوستو بالكرز', 'Komposto Cherry Compote', 'Komposto aux cerises', 'Komposto con cerezas', 'Komposto, Kirschkompott', 'rice_cakes_sweets', 'snack', 0, 16, 0, 'simmering'),
  tel_kadayif: profile('تل قديف بالجوز', 'Tel Kadayıf with Walnuts', 'Tel kadayıf aux noix', 'Tel kadayıf con nueces', 'Tel Kadayıf mit Walnüssen', 'rice_cakes_sweets', 'snack', 4, 42, 15, 'baking'),
  burma_kadayif: profile('بورما قديف بالفستق', 'Burma Kadayıf with Pistachio', 'Burma kadayıf aux pistaches', 'Burma kadayıf con pistacho', 'Burma Kadayıf mit Pistazien', 'rice_cakes_sweets', 'snack', 4, 44, 16, 'baking'),
  halka_tatlisi: profile('حلقة حلوة مقلية', 'Halka Tatlısı Fried Rings in Syrup', 'Halka tatlısı frits au sirop', 'Halka tatlısı fritos en almíbar', 'Halka Tatlısı, frittierte Ringe in Sirup', 'rice_cakes_sweets', 'snack', 3, 44, 13, 'frying'),
  lor_peynirli_borek: profile('بوريك بجبن اللور', 'Börek with Lor Cheese', 'Börek au fromage lor', 'Börek con queso lor', 'Börek mit Lor-Käse', 'street_snacks', 'breakfast', 8, 28, 11, 'baking'),
  otlu_peynirli_borek: profile('بوريك بالجبن والأعشاب', 'Börek with Herbed Cheese', 'Börek au fromage aux herbes', 'Börek con queso y hierbas', 'Börek mit Kräuterkäse', 'street_snacks', 'breakfast', 8, 28, 11, 'baking'),
  tavuklu_borek: profile('بوريك بالدجاج', 'Börek with Chicken', 'Börek au poulet', 'Börek con pollo', 'Börek mit Hähnchen', 'street_snacks', 'snack', 10, 27, 11, 'baking'),
  kiymali_borek: profile('بوريك باللحم المفروم حلال', 'Börek with Halal Ground Beef', 'Börek au bœuf haché halal', 'Börek con carne picada halal', 'Börek mit Halal-Hackfleisch', 'street_snacks', 'snack', 11, 26, 12, 'baking'),
  patlicanli_borek: profile('بوريك بالباذنجان', 'Börek with Eggplant', 'Börek aux aubergines', 'Börek con berenjena', 'Börek mit Aubergine', 'street_snacks', 'snack', 7, 27, 10, 'baking'),
  tereyagli_pilav: profile('أرز بالزبدة', 'Butter Rice Pilaf', 'Pilav au beurre', 'Pilav con mantequilla', 'Butterreis-Pilaw', 'rice_dishes', 'lunch', 5, 29, 7, 'simmering'),
  sehriyeli_bulgur: profile('برغل بالشعيرية', 'Bulgur with Vermicelli', 'Boulgour aux vermicelles', 'Bulgur con fideos', 'Bulgur mit Fadennudeln', 'rice_dishes', 'lunch', 5, 27, 5, 'simmering'),
  domatesli_pilav: profile('أرز بالطماطم', 'Tomato Rice Pilaf', 'Pilav à la tomate', 'Pilav con tomate', 'Tomatenreis-Pilaw', 'rice_dishes', 'lunch', 4, 28, 5, 'simmering'),
  meyhane_pilavi: profile('أرز المحشرة بالعدس', 'Meyhane Pilavı with Lentils', 'Meyhane pilavı aux lentilles', 'Meyhane pilavı con lentejas', 'Meyhane Pilavı mit Linsen', 'rice_dishes', 'lunch', 7, 29, 5, 'simmering'),
  havuclu_bulgur: profile('برغل بالجزر', 'Bulgur with Carrots', 'Boulgour aux carottes', 'Bulgur con zanahorias', 'Bulgur mit Karotten', 'rice_dishes', 'lunch', 5, 26, 4, 'simmering'),
  mantarli_pilav: profile('أرز بالفطر', 'Rice Pilaf with Mushrooms', 'Pilav aux champignons', 'Pilav con setas', 'Pilaw mit Pilzen', 'rice_dishes', 'lunch', 4, 27, 5, 'simmering'),
  sebze_corbasi: profile('شوربة الخضار التركية', 'Turkish Vegetable Soup', 'Soupe de légumes à la turque', 'Sopa de verduras turca', 'Türkische Gemüsesuppe', 'soups_stews', 'lunch', 3, 11, 3, 'simmering'),
  patates_corbasi: profile('شوربة البطاطس بالكريمة', 'Potato Soup with Cream', 'Soupe de pommes de terre à la crème', 'Sopa de patata con crema', 'Kartoffelsuppe mit Sahne', 'soups_stews', 'lunch', 4, 12, 5, 'simmering'),
  karnabahar_corbasi: profile('شوربة القرنبيط', 'Cauliflower Soup', 'Soupe de chou-fleur', 'Sopa de coliflor', 'Blumenkohlsuppe', 'soups_stews', 'lunch', 3, 9, 4, 'simmering'),
  mantar_corbasi: profile('شوربة الفطر بالكريمة', 'Mushroom Soup with Cream', 'Soupe de champignons à la crème', 'Sopa de setas con crema', 'Pilzsuppe mit Sahne', 'soups_stews', 'lunch', 4, 8, 5, 'simmering'),
  kabak_corbasi: profile('شوربة اليقطين', 'Pumpkin Soup', 'Soupe de potiron', 'Sopa de calabaza', 'Kürbissuppe', 'soups_stews', 'lunch', 2, 10, 4, 'simmering'),
  tutmac_corbasi: profile('شوربة توتماش بالعدس', 'Tutmaç Soup with Lentils and Yogurt', 'Soupe tutmaç aux lentilles et au yaourt', 'Sopa tutmaç con lentejas y yogur', 'Tutmaç-Suppe mit Linsen und Joghurt', 'soups_stews', 'lunch', 6, 15, 3, 'simmering'),
  arabasi_corbasi: profile('شوربة أراباشي بالدجاج', 'Arabaşı Chicken Soup', 'Soupe arabaşı au poulet', 'Sopa arabaşı con pollo', 'Arabaşı-Hühnersuppe', 'soups_stews', 'lunch', 10, 8, 4, 'simmering'),
  yuvalama_corbasi: profile('شوربة يوفالاما باللحم حلال', 'Yuvalama Soup with Halal Meatballs', 'Soupe yuvalama aux boulettes halal', 'Sopa yuvalama con albóndigas halal', 'Yuvalama-Suppe mit Halal-Fleischbällchen', 'soups_stews', 'lunch', 10, 10, 4, 'simmering'),
  anali_kizli: profile('أنالي قزلي بالبرغل حلال', 'Analı Kızlı Bulgur Dumplings with Halal Beef', 'Analı kızlı au boulgour et au bœuf halal', 'Analı kızlı con bulgur y ternera halal', 'Analı Kızlı, Bulgurklößchen mit Halal-Rind', 'soups_stews', 'dinner', 11, 19, 7, 'simmering'),
  lebeniye_corbasi: profile('شوربة لبنية باللحم حلال', 'Lebeniye Soup with Halal Meatballs', 'Soupe lebeniye aux boulettes halal', 'Sopa lebeniye con albóndigas halal', 'Lebeniye-Suppe mit Halal-Fleischbällchen', 'soups_stews', 'lunch', 9, 9, 4, 'simmering'),
  beyran_corbasi: profile('شوربة بيران بالضأن والأرز حلال', 'Beyran Soup with Halal Lamb and Rice', 'Soupe beyran à l’agneau halal et au riz', 'Sopa beyran con cordero halal y arroz', 'Beyran-Suppe mit Halal-Lamm und Reis', 'soups_stews', 'lunch', 11, 9, 6, 'simmering'),
  kelle_paca: profile('شوربة كلا باتشا بالثوم', 'Kelle Paça Soup with Garlic', 'Soupe kelle paça à l’ail', 'Sopa kelle paça con ajo', 'Kelle-Paça-Suppe mit Knoblauch', 'soups_stews', 'lunch', 11, 2, 6, 'simmering'),
  tavuk_kanat_firin: profile('أجنحة دجاج بالفرن بالثوم', 'Baked Garlic Chicken Wings', 'Ailes de poulet à l’ail au four', 'Alitas de pollo al horno con ajo', 'Knoblauch-Hähnchenflügel aus dem Ofen', 'poultry_mains', 'dinner', 21, 2, 11, 'baking'),
  tavuk_pirzola: profile('ضلوع دجاج مشوية حلال', 'Grilled Chicken Pirzola, Halal', 'Pirzola de poulet grillé halal', 'Pirzola de pollo a la parrilla halal', 'Gegrillte Hähnchen-Pirzola, halal', 'poultry_mains', 'dinner', 22, 2, 9, 'grilling'),
  tavuk_sote: profile('سوتيه دجاج بالفلفل', 'Chicken Sauté with Peppers', 'Poulet sauté aux poivrons', 'Pollo salteado con pimientos', 'Hähnchenpfanne mit Paprika', 'poultry_mains', 'dinner', 22, 6, 8, 'pan_frying'),
  tavuk_kapama: profile('دجاج مطهو بالبصل', 'Chicken Kapama with Onions', 'Poulet kapama aux oignons', 'Pollo kapama con cebollas', 'Hähnchen Kapama mit Zwiebeln', 'poultry_mains', 'dinner', 21, 5, 10, 'stewing'),
  firinda_tavuk_patates: profile('دجاج بالفرن بالبطاطس', 'Oven Chicken with Potatoes', 'Poulet au four aux pommes de terre', 'Pollo al horno con patatas', 'Ofenhähnchen mit Kartoffeln', 'poultry_mains', 'dinner', 20, 12, 10, 'baking'),
  hindi_etli: profile('صدر هندي مشوي بالأعشاب', 'Roast Turkey Breast with Herbs', 'Blanc de dinde rôti aux herbes', 'Pechuga de pavo asada con hierbas', 'Gebratene Putenbrust mit Kräutern', 'poultry_mains', 'dinner', 24, 1, 8, 'roasting'),
  kuzu_sote: profile('سوتيه ضأن بالخضار حلال', 'Lamb Sauté with Vegetables, Halal', 'Agneau halal sauté aux légumes', 'Cordero halal salteado con verduras', 'Lammpfanne mit Gemüse, halal', 'meat_mains', 'dinner', 19, 6, 11, 'pan_frying'),
  dana_sote: profile('سوتيه لحم بقري بالفلفل حلال', 'Beef Sauté with Peppers, Halal', 'Bœuf halal sauté aux poivrons', 'Ternera halal salteada con pimientos', 'Rindpfanne mit Paprika, halal', 'meat_mains', 'dinner', 21, 5, 10, 'pan_frying'),
  etli_nohut: profile('حمص بالضأن حلال', 'Chickpeas with Halal Lamb', 'Pois chiches à l’agneau halal', 'Garbanzos con cordero halal', 'Kichererbsen mit Halal-Lamm', 'soups_stews', 'dinner', 13, 17, 7, 'stewing'),
  etli_kuru_fasulye: profile('فاصولياء بيضاء باللحم حلال', 'White Beans with Halal Beef', 'Haricots blancs au bœuf halal', 'Alubias blancas con ternera halal', 'Weiße Bohnen mit Halal-Rind', 'soups_stews', 'dinner', 11, 20, 6, 'stewing'),
  etli_taze_fasulye: profile('فاصولياء خضراء بالضأن حلال', 'Green Beans with Halal Lamb', 'Haricots verts à l’agneau halal', 'Judías verdes con cordero halal', 'Grüne Bohnen mit Halal-Lamm', 'vegetable_mains', 'dinner', 11, 12, 8, 'stewing'),
  etli_bamya: profile('بامية بالضأن حلال', 'Okra with Halal Lamb', 'Gombos à l’agneau halal', 'Ocra con cordero halal', 'Okra mit Halal-Lamm', 'vegetable_mains', 'dinner', 10, 10, 7, 'stewing'),
  etli_ispanak: profile('سبانخ باللحم حلال', 'Spinach with Halal Beef', 'Épinards au bœuf halal', 'Espinacas con ternera halal', 'Spinat mit Halal-Rind', 'vegetable_mains', 'dinner', 10, 8, 7, 'stewing'),
  ispanak_yumurta: profile('سبانخ بالبيض', 'Spinach with Eggs', 'Épinards aux œufs', 'Espinacas con huevos', 'Spinat mit Eiern', 'vegetable_mains', 'lunch', 8, 6, 8, 'pan_frying'),
  pazi_yemegi: profile('يخنة السلق بالبرغل', 'Chard Stew with Bulgur', 'Mijoté de blettes au boulgour', 'Estofado de acelga con bulgur', 'Mangoldeintopf mit Bulgur', 'vegetable_mains', 'lunch', 4, 14, 5, 'stewing'),
  kabak_kalye: profile('يخنة الكوسا بالطماطم', 'Zucchini Stew with Tomato', 'Mijoté de courgettes à la tomate', 'Estofado de calabacín con tomate', 'Zucchinieintopf mit Tomate', 'vegetable_mains', 'dinner', 3, 10, 5, 'stewing'),
  enginar_dolmasi: profile('خرشوف محشو بالأرز', 'Stuffed Artichokes with Rice', 'Artichauts farcis au riz', 'Alcachofas rellenas de arroz', 'Gefüllte Artischocken mit Reis', 'vegetable_mains', 'lunch', 3, 13, 6, 'simmering'),
  kereviz_dolmasi: profile('كرفس محشو بالأرز', 'Stuffed Celeriac with Rice', 'Céleri-rave farci au riz', 'Apionabo relleno de arroz', 'Gefüllter Sellerie mit Reis', 'vegetable_mains', 'lunch', 3, 12, 6, 'simmering'),
  havuc_tarator: profile('جزر بالزبادي', 'Carrot Tarator with Yogurt', 'Carottes au tarator de yaourt', 'Zanahorias con tarator de yogur', 'Karotten-Tarator mit Joghurt', 'condiments_sauces', 'lunch', 3, 7, 5, 'assembling'),
  kabak_tarator: profile('كوسا بالزبادي', 'Zucchini Tarator with Yogurt', 'Courgettes au tarator de yaourt', 'Calabacín con tarator de yogur', 'Zucchini-Tarator mit Joghurt', 'condiments_sauces', 'lunch', 3, 6, 5, 'assembling'),
  semizotu_salata: profile('سلطة البقلة بالزبادي', 'Purslane Salad with Yogurt', 'Salade de pourpier au yaourt', 'Ensalada de verdolaga con yogur', 'Portulaksalat mit Joghurt', 'vegetable_mains', 'lunch', 3, 6, 4, 'tossing'),
  acuka: profile('أجوجة بالجوز والفلفل', 'Acuka Walnut Pepper Spread', 'Acuka aux noix et aux poivrons', 'Acuka con nueces y pimientos', 'Acuka, Walnuss-Paprika-Aufstrich', 'condiments_sauces', 'snack', 3, 6, 9, 'blending'),
  cemen: profile('تشمن بالثوم والكمون', 'Çemen Garlic Cumin Paste', 'Çemen à l’ail et au cumin', 'Çemen con ajo y comino', 'Çemen, Knoblauch-Kreuzkümmel-Paste', 'condiments_sauces', 'snack', 2, 5, 7, 'blending'),
  kozlenmis_biber: profile('فلفل مشوي بزيت الزيتون', 'Roasted Peppers in Olive Oil', 'Poivrons rôtis à l’huile d’olive', 'Pimientos asados en aceite de oliva', 'Geröstete Paprika in Olivenöl', 'vegetable_mains', 'lunch', 2, 8, 5, 'roasting'),
  kozlenmis_patlican_salata: profile('سلطة الباذنجان المشوي', 'Smoked Eggplant Salad', 'Salade d’aubergines fumées', 'Ensalada de berenjena ahumada', 'Geräucherter Auberginensalat', 'vegetable_mains', 'lunch', 2, 8, 5, 'tossing'),
  saksuka: profile('شقشوقة بالخضار المقلية', 'Şakşuka Fried Vegetables with Yogurt', 'Şakşuka de légumes frits au yaourt', 'Şakşuka de verduras fritas con yogur', 'Şakşuka, gebratenes Gemüse mit Joghurt', 'vegetable_mains', 'lunch', 3, 10, 8, 'frying'),
  istavrit_tava: profile('إستاوريت مقلي', 'Fried Horse Mackerel, İstavrit', 'İstavrit frit, chinchard', 'İstavrit frito, jurel', 'İstavrit, gebratene Stöcker', 'fish_seafood', 'dinner', 18, 8, 11, 'frying'),
  sardalya_izgara: profile('سردين مشوي بالأعشاب', 'Grilled Sardines with Herbs, Sardalya', 'Sardalya, sardines grillées aux herbes', 'Sardalya, sardinas a la parrilla con hierbas', 'Sardalya, gegrillte Sardinen mit Kräutern', 'fish_seafood', 'dinner', 19, 1, 10, 'grilling'),
  uskumru_izgara: profile('ماكريل مشوي', 'Grilled Mackerel, Uskumru', 'Uskumru, maquereau grillé', 'Uskumru, caballa a la parrilla', 'Uskumru, gegrillte Makrele', 'fish_seafood', 'dinner', 20, 0, 11, 'grilling'),
  lakerda: profile('لاكةردة بونيتو مملح', 'Lakerda Cured Bonito', 'Lakerda, bonite marinée', 'Lakerda, bonito en salmuera', 'Lakerda, pökelter Bonito', 'fish_seafood', 'snack', 18, 0, 8, 'marinating'),
  tarama: profile('تراما بيض السمك', 'Tarama Fish Roe Spread', 'Tarama, crème d’œufs de poisson', 'Tarama, crema de huevas', 'Tarama, Fischrogen-Aufstrich', 'condiments_sauces', 'snack', 10, 3, 9, 'blending'),
  karides_guvec: profile('كوفيتش جمبري بالخضار', 'Shrimp Güveç with Vegetables', 'Güveç de crevettes aux légumes', 'Güveç de gambas con verduras', 'Garnelen-Güveç mit Gemüse', 'fish_seafood', 'dinner', 15, 7, 7, 'stewing'),
  ahtapot_salata: profile('سلطة الأخطبوط بالليمون', 'Octopus Salad with Lemon', 'Salade de poulpe au citron', 'Ensalada de pulpo con limón', 'Oktopussalat mit Zitrone', 'fish_seafood', 'lunch', 14, 4, 6, 'boiling'),
  balik_pilaki: profile('سمك بيلاكي بزيت الزيتون', 'Fish Pilaki in Olive Oil', 'Poisson pilaki à l’huile d’olive', 'Pescado pilaki en aceite de oliva', 'Fisch-Pilaki in Olivenöl', 'fish_seafood', 'lunch', 13, 8, 6, 'stewing'),
  cevizli_baklava: profile('بقلاوة بالجوز', 'Walnut Baklava', 'Baklava aux noix', 'Baklava con nueces', 'Baklava mit Walnüssen', 'rice_cakes_sweets', 'snack', 6, 46, 21, 'baking'),
  fistikli_sarma: profile('سرما بالفستق', 'Fıstıklı Sarma Pistachio Rolls', 'Fıstıklı sarma aux pistaches', 'Fıstıklı sarma con pistacho', 'Fıstıklı Sarma, Pistazienrollen', 'rice_cakes_sweets', 'snack', 5, 44, 20, 'baking'),
  sobiyet: profile('سوبيت بالفستق والكريمة', 'Şöbiyet with Pistachio and Cream', 'Şöbiyet aux pistaches et à la crème', 'Şöbiyet con pistacho y crema', 'Şöbiyet mit Pistazien und Sahne', 'rice_cakes_sweets', 'snack', 6, 43, 18, 'baking'),
  bulbul_yuvasi: profile('عش البلبل بالفستق', 'Bülbül Yuvası with Pistachio', 'Bülbül yuvası aux pistaches', 'Bülbül yuvası con pistacho', 'Bülbül Yuvası mit Pistazien', 'rice_cakes_sweets', 'snack', 5, 42, 17, 'baking'),
  saray_lokmasi: profile('لقمة القصر بالجوز', 'Saray Lokması with Walnuts', 'Saray lokması aux noix', 'Saray lokması con nueces', 'Saray Lokması mit Walnüssen', 'rice_cakes_sweets', 'snack', 5, 41, 16, 'baking'),
  kalburabasti: profile('كلبورباستي بالجوز', 'Kalburabastı with Walnuts in Syrup', 'Kalburabastı aux noix au sirop', 'Kalburabastı con nueces en almíbar', 'Kalburabastı mit Walnüssen in Sirup', 'rice_cakes_sweets', 'snack', 4, 43, 14, 'baking'),
  dilber_dudagi: profile('شفاه دلبير بالجوز', 'Dilber Dudağı with Walnuts', 'Dilber dudağı aux noix', 'Dilber dudağı con nueces', 'Dilber Dudağı mit Walnüssen', 'rice_cakes_sweets', 'snack', 4, 44, 15, 'baking'),
};

export function B(profileRow, region) {
  const token = REGION_DEMONYM[region];
  if (!token) throw new Error(`Unknown Turkey region: ${region}`);
  const extra = REGION_DIASPORA[region];
  const national = region === 'pan_turkish';
  const descriptor = REGIONS.find(([id]) => id === region);
  return {
    id: '',
    nameAr: `${national ? '' : `${descriptor[1]} `}${profileRow.ar} ${token}`.trim(),
    nameEn: `${national ? 'Turkish ' : `${descriptor[2]} `}${profileRow.en}`,
    nameFr: `${national ? 'Cuisine turque : ' : `${descriptor[3]} `}${profileRow.fr}`,
    nameEs: `${national ? 'Cocina turca: ' : `${descriptor[4]} `}${profileRow.es}`,
    nameDe: `${national ? 'Türkische Küche: ' : `${descriptor[5]} `}${profileRow.de}`,
    category: profileRow.category,
    mealType: profileRow.meal,
    grams: 100,
    kcal: Math.round(4 * profileRow.protein + 4 * profileRow.carbs + 9 * profileRow.fat),
    protein: profileRow.protein,
    carbs: profileRow.carbs,
    fat: profileRow.fat,
    cooking: profileRow.cooking,
    region,
    diaspora_priority: extra ? [...BASE_DIASPORA, extra] : [...BASE_DIASPORA],
  };
}

export function buildRows(regionalKeys, nationalKeys, recipes) {
  const rows = [];
  for (const [region] of REGIONS) {
    for (const key of regionalKeys) {
      if (!recipes[key]) throw new Error(`Unknown Turkey recipe profile: ${key}`);
      rows.push(B(recipes[key], region));
    }
  }
  for (const key of nationalKeys) {
    if (!recipes[key]) throw new Error(`Unknown Turkey recipe profile: ${key}`);
    rows.push(B(recipes[key], 'pan_turkish'));
  }
  return rows;
}
